### ISSUE TITLE
Plan FMB sub-hub landing pages

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#76427] opened 2024-02-15 23:40 UTC
## Issue description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Health care and disabilities:  http://preview-prod.vfs.va.gov/preview?nodeId=65069
- Education:   http://preview-prod.vfs.va.gov/preview?nodeId=65340
- Survivors page:  http://preview-prod.vfs.va.gov/preview?nodeId=65341
- Burials: http://preview-prod.vfs.va.gov/preview?nodeId=65328
- Life insurance: http://preview-prod.vfs.va.gov/preview?nodeId=65664 
- Home loans: http://preview-prod.vfs.va.gov/preview?nodeId=65665

I've broken these out into individual tickets, but will keep this ticket open since it has valuable background in the comments.

**Comment by mnorthuis** [comment] 2024-02-16 15:05
- The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"


Related IA work
- Structure links on parent family member hub page and document changes needed and identify if page should be redirected to new URL
- build out a left nav component to appear on each of the benefit category landing pages 
- adding left nav to the PCAFCG content page and changing its URL for proper placement
- submit issue to PCAFCG team to update URL and breadcrumb based on new structure

**Comment by mnorthuis** [comment] 2024-03-04 21:50
@strelichl let's get an IA assigned to this to start working asap so that work can be ready for when a writer is available. Thank you!

**Comment by kristinoletmuskat** [comment] 2024-04-03 21:06
@strelichl prelim IA work is here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1712161697570

You mentioned other tickets for each 'subhub' page -- could we link those here? Or tag IA on them so they show on my board?

**Comment by kristinoletmuskat** [comment] 2024-04-05 18:52
Hey hey done with the IA spec draft -- if ya'll could review it and lmk if you have any open Qs. I imagine Qs might come up as you start building the page too.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md

**Comment by mnorthuis** [comment] 2024-04-08 15:46
@kristinoletmuskat A couple of notes after reviewing this:

1) Were you able to ensure that Drupal will allow two notes to have the same URL slug? This would impact Life insurance and Burials and memorials URLs.
2) In the user flow - we are not focusing on tasks or information related to managing a Veteran's care, so that is a use case that should not be represented here, so let's remove that.
3) The site map or crosslinks section does not reference the application for the PCAFC.  We may initially link to it where it is today, but we will need to work with that team to update the current placement of the form to it's new home - that requires a URL change for the form, updates to their breadcrumb, and a redirect. I would also include the CHAMPVA application which is currently being worked on and finalize it's placement within this structure. 
4) Under entry points, can you indicate when an entry point is being added/updated/removed so that is clear?  For example, for the top menu, the family member hub link is being modified.  Then highlight what is being modified. 
5) For the left nav, lets take it out of the image and list the items out for a11y/readability and maintenance. If this order is not final,  you can indicate as so and then modify this doc once it is finalized.
6) For crosslinks/the links on the page, the landing page should be linking to all of the pages referenced - your images indicates only those in light blue stickies.  Also, please take out of the image, and list out the pages along with their URLs. 
7) For each landing page, there are multiple sections of links that I started creating a definition around. As part of this work, we should indicate what additional links appear in each of those sections, in collaboration with content. This creates the hierarchy of the page. 


As a secondary effort to this, we should create a ticket in the backlog to document that structure and hierarchy of these landing pages, similar to the hub page template, so we have guidance on how content is placed within the page. 

Thank you!

**Comment by kristinoletmuskat** [comment] 2024-04-08 20:04
@mnorthuis hey hey thank you for this input. Here are answers:

1. Yes, confirmed with Randi.
2. Edited user flow in mural and github doc
3. Added PCAFG and CHAMPVA forms -- still trying to work through left nav.
4. updated entry points
5. Added left nav as text
6. I updated the key to be more specific about the light-blue pages and will work on adding the links to all of those pages. 
7. For this last one, I wanted to confirm that we're ONLY pulling in those pages/sections identified in the crossliknks in the mural for Phase 1. So only the 'get' benefits. So it sounds like you're asking for a template for the subhub pages that will include manage/more links as well. Does that sound right? I can also add this to our sync on wednesday.

**Comment by mnorthuis** [comment] 2024-04-08 21:41
Excellent! 

For 7, we can definitely chat on Wednesday.  If you look at the wireframes I created, you'll see that the main benefits are linked at the top of the page and that is core content of each sub-hub and what will make up the left nav.  However, that page has more content and links on it in additional sections.  None of that content will live in this hub, it is all truly crosslinked content.

**Comment by laurwill** [comment] 2024-05-13 16:44
Hi @kristinoletmuskat @d-beyer ,
Should we work out H1s for all these FMB landing pages in this central ticket? I think the idea is to consider overlap with Veteran hub page H1s and any SEO issues around that, and length issues with some of these.

Main hub H1: 
- Should we change from "VA benefits for spouses, dependents, survivors, and family caregivers" to "VA benefits for family members and caregivers"? Matches URL and breadcrumb better.

Options for landing page H1s:
- **Health & disability:** 
     - "Health care and disability benefits for family members and caregivers" is 70 characters. Ideas for how to cut?
     - Do we want to try to get "VA" into these H1s, or is that not needed because they're nested under the "VA benefits for family members" hub page?

**Comment by kristinoletmuskat** [comment] 2024-05-13 22:39
Hey hey! I think we can track the H1s in this ticket -- I'm honestly a little confused about what each of our diff tickets is for, so we might want to meet to clarify or break them out in whatever way works best for us. 

1) I support the shortening to "VA benefits for family members and caregivers". If we want to make sure we're maximizing SEO, we might want to make sure that our intro paragraph includes the other terms (spouses, dependents, survivors, etc). 

2) In our recent audit we identified that we don't want to add 'VA' to H1s unless we 1) need to for SEO or 2) need to for clarity if we have evidence veterans might get confused. So I support not including VA in the H1s for the subhubs if possible, unless we think Veterans would get confused or expect non-VA benefits to show up there. Which I suppose could be possible if they end up on this page from a search engine and not through the family member hub. Not a conclusive answer for you, but if our recent audit is an indication, I think we don't need the VA in H1s for the most part.

@laurwill @d-beyer 

Also, is there a source of truth ya'll are using to write these pages? Github, sharepoint, drupal? I'd love to be able to poke around in there just to make sure we're on the same page!

**Comment by laurwill** [comment] 2024-05-15 21:10
We're doing this all direct in Drupal — you can use the links at top of page to poke around :) So far we've only worked on health & disability, but Derek's building out the rest now.

**Closed** 2024-05-16 16:24 UTC
Labels: sitewide content, sitewide IA, sitewide CAIA
