### ISSUE TITLE
[Content] Direct deposit: Remove old unauthenticated content page on direct deposit

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7995] opened 2020-04-14 15:31 UTC
## Background

When we launched direct deposit for comp & pen on VA.gov, we updated the unauthenticated content page https://www.va.gov/change-direct-deposit/. However we did not realize that the old content page was never taken down: https://www.va.gov/change-your-va-direct-deposit-and-contact-information/. This content is out of date and needs to be removed from the website.

## Tasks

- [x] Delete https://www.va.gov/change-your-va-direct-deposit-and-contact-information/

## Acceptance criteria

- [ ] https://www.va.gov/change-your-va-direct-deposit-and-contact-information/ is no longer live on VA.gov

**Comment by RLHecht** [comment] 2020-04-14 16:22
I've archived this page so it should be removed from the site after the next deployment.

**Comment by Samara-Strauss** [comment] 2020-04-14 18:58
Great, thanks! I'll close this after I can confirm the page is down.

**Comment by Samara-Strauss** [comment] 2020-04-14 19:46
@RLHecht — I am still seeing the old direct deposit page when I click the link. I would have thought the daily deploy would be complete by now. Any thoughts?

**Comment by RLHecht** [comment] 2020-04-14 20:03
@Samara-Strauss I believe there was an issue with the daily deploy, which is why it's not showing yet. I can keep checking back later this afternoon and if it's still not working I'll reach out to the CMS team again to see what the issue is.

**Comment by Samara-Strauss** [comment] 2020-04-14 20:04
Thank you @RLHecht!

**Comment by RLHecht** [comment] 2020-04-15 01:04
@Samara-Strauss Turns out this page was also linked from find-forms, so it was still showing up when archived. I'll remove from there as well and then it should really be fixed!

**Comment by Samara-Strauss** [comment] 2020-04-15 13:36
Updating with convo from Slack: the old DD page was linked to from /find-forms. @RLHecht is changing the link destination on that page to the new DD page, so then we should be able to archive the old one.

**Comment by RLHecht** [comment] 2020-04-15 13:41
@Samara-Strauss Page archived again and the link from /find-forms was changed to the new one. Should now all work after today's deploy.

**Comment by Samara-Strauss** [comment] 2020-04-15 13:47
Great! I'll check later this afternoon.

**Comment by Samara-Strauss** [comment] 2020-04-15 20:15
The page has been removed! Closing. Thanks @RLHecht!

**Comment by Samara-Strauss** [comment] 2020-04-20 21:05
Hey @stephorkandatx — can you let me know why this was reopened?

**Comment by stephorkandatx** [comment] 2020-04-21 13:53
@Samara-Strauss I am so sorry about that, That was a mistake on my part from accidentally moving this ticket. I have set it back to Closed.

**Closed** 2020-04-21 13:53 UTC
Labels: content, direct deposit, vsa-authenticated-exp
