### ISSUE TITLE
Discovery: incorrect regex routing matches

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#62353] opened 2023-07-20 18:14 UTC
Occasionally, invalid URLs are not returning a 404 and instead are returning a blank page. This seems to take place when the URL has a partial match to a valid page, but the exact route match does not return any content. We should investigate the cause of this and try and push all invalid URLs to 404 errors to avoid user confusion. 

Source support request: https://dsva.slack.com/archives/CBU0KDSB1/p1687964314731719

Tasks 
- [x] Document reason for this behavior
- [x] Document recommended solution to correct the behavior

**Comment by rmessina1010** [comment] 2023-08-22 14:57
### Rage of  error
Confirmed: Behavior occurs in all environments ( dev, staging, prod)


### Test methodology 
URL
Test Pattern:
	Ad character 
		* start
		* end 
		* middle

	Remove character 
		* start
		* end 
		* middle

### Current findings
The first directory can be appended to, but no other change is allowed.
	* staging.va.gov/view-change-dependents (works)
	* staging.va.gov/view-change-dependents123(works)
	* staging.va.gov/view-change-dependent123s( page not found)

From the first directory, default entirely  non existent  paths can be added,  it will go to the default page?
	* staging.va.gov/view-change-dependents (works)
	* staging.va.gov/view-change-dependents/view (works, is actual page)
	* staging.va.gov/view-change-dependents/123 (works)
	* staging.va.gov/view-change-dependents/123/123/…ad infinitum(works)

**Comment by rmessina1010** [comment] 2023-08-24 04:17
Given the aforementioned results, I  think the reason behind the false positive re-routs  is not due to regex or parsing,  but simply the natural behavior of React-router to leave paths appendable.

**Comment by rmessina1010** [comment] 2023-08-25 13:44
Still looking for a way to pass `exact:true` to Route components, as it seems they are dynamically generated from a config object.  The following doesn't seem to work, however:

```
const routes = {
  path: '/',
  component: IncomeLimitsApp,
  indexRoute: {
    onEnter: (nextState, replace) => replace('/introduction'),
    component: HomePage,
  },
  childRoutes: [
    { path: ROUTES.HOME, component: HomePage, exact: true },
    { path: ROUTES.DEPENDENTS, component: DependentsPage, exact: true },
    { path: ROUTES.REVIEW, component: ReviewPage, exact: true },
    { path: ROUTES.RESULTS, component: ResultsPage, exact: true },
    { path: ROUTES.YEAR, component: YearPage, exact: true },
    { path: ROUTES.ZIPCODE, component: ZipCodePage, exact: true },
    { path: '*', component: FourOFour },
  ],
};
```

**Comment by rmessina1010** [comment] 2023-08-25 14:13
Addendums:

 adding  `{ path: '*', component: null },` to `childRoutes`, actually  renders the app (with a null route) when a non existent path is given. As can be observed by the fact that the breadcrumbs for the path display.

Breadcrumbs,  for the path do not display  without this option however. 
I am considering that reteaching having the default result for` startApp() `, other than on the home page, be 404.. maybe a hot fix.  In other words, I think what might be happening right now, is that nonexistent  paths as are correctly seen as such but rendered as `null` instead of 404

**Comment by rmessina1010** [comment] 2023-08-28 20:19
### Closing summary
Two things seemed to actually be happening here that lead  to the problematic described behavior:
1) The routes  aren't set to  `exact:true`;  or the setting isn't being recognized.  This why you can could add characters to the END  of the url, and it still gave you  the same page
2) Looks like the site was  relying on a complete  fail  when resolving the url to throw a 404  or some other error to then load the "Page could not be found / Search".  But  the router is defaulting to null/undefined. That is, a failed url does not re route you to a 404, index page, or anywhere outside the app that has been started... instead  a empty (null) element is displayed.

I have created a ticket here to address this issues, [https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/64366](https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/64366), and noted additional findings in said ticket

**Closed by rmessina1010** 2023-08-28 20:19 UTC
Labels: low-priority, platform-reliability-team, platform-cop-frontend
