### ISSUE TITLE
[Spike] - Better Understanding of vaos-eligibility-direct-available-clinics-failed

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#52162] opened 2023-01-18 15:06 UTC
## Background/Request
The vaos-eligibility-direct-available-clinics-event-failed event has the highest number of failed events compared to all other eligibility failures being tracked.  Therefore, we would like a better understanding of this event, including when it is occurring and what is triggering this event to reduce the number of times it is triggered.

### Goal
1) Understand where in the VAOS workflow this event is being triggered
2) Understand what the possible conditions are triggering this event
3) What data can be logged to identify any sites, clinics, etc. that this occurs at frequently

## Tasks
- Answer the following questions:
  - Q  Where in the direct scheduling workflow does this event occur?
  - Q  What are the root causes for this event being triggered?
  - Q  What data can be logged to identify conditions that cause this event to be triggered frequently?

## Time Box
12 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ajmagdub** [comment] 2023-10-30 15:39
Changing the appointment list impacted Google Analytics capturing of eligibility errors. @JRRoof will return the ticket to the ready state so that the FE team can investigate the monitoring changes.

**Comment by simiadebowale** [comment] 2024-02-06 16:37
@JRRoof - I believe this ticket will be better answered by the FE engineers as we handle sending GA events in vets-website. cc: @cferris32 @ldelacosta

**Comment by JRRoof** [comment] 2024-02-09 20:38
[Domo report](https://va-gov.domo.com/page/1769944412/kpis/details/1781674633) showing how many times this event is triggered per month.
<img width="1594" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cef84dc6f5f1ae92ad4bebc43106894208c201a9/image.png" alt="image.png" />

**Comment by JRRoof** [comment] 2024-02-09 20:42
[Google Analytics report](https://analytics.google.com/analytics/web/#/my-reports/RB6puMA0RfGceEn_o2njLg/a50123418w177519031p184624291/_u.date00=20240101&_u.date01=20240131&1052-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22vaos-eligibility-direct%22,0%5D%5D&1052-table.plotKeys=%5B%5B%22vaos-eligibility-direct-available-clinics-failed%22%5D,%5B%22vaos-eligibility-direct-check-past-visits-failed%22%5D,%5B%22vaos-eligibility-direct-no-matching-past-clinics-failed%22%5D%5D&1052-graphOptions.selected=analytics.nthDay/) showing number of times eligibility checks are triggered per month (January 2024)
<img width="1653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--182e4fb26bd7a3eaa3831dd8759c59d1e35fccb4/image.png" alt="image.png" />

**Comment by JRRoof** [comment] 2024-02-09 20:50
[Google Analytics report](https://analytics.google.com/analytics/web/#/my-reports/RB6puMA0RfGceEn_o2njLg/a50123418w177519031p184624291/_u.date00=20240101&_u.date01=20240131&1052-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22vaos-eligibility-direct-available-clinics-failed%22,0%5D%5D&1052-table.plotKeys=%5B%5B%22vaos-eligibility-direct-available-clinics-failed%22,%22323%22%5D,%5B%22vaos-eligibility-direct-available-clinics-failed%22,%22502%22%5D,%5B%22vaos-eligibility-direct-available-clinics-failed%22,%22408%22%5D,%5B%22vaos-eligibility-direct-available-clinics-failed%22,%22203%22%5D%5D&1052-table.secSegmentId=analytics.customDimension72&1052-graphOptions.selected=analytics.nthDay/) breaking down the vaos-eligibility-direct-available-clinics-failed broken down by "Type of Care".
<img width="1658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--365a77fb562957a91f993c2e822be57b3e1a2483/image.png" alt="image.png" />

**Comment by JRRoof** [comment] 2024-02-09 20:52
[Google Analytics report](https://analytics.google.com/analytics/web/#/my-reports/RB6puMA0RfGceEn_o2njLg/a50123418w177519031p184624291/_u.date00=20240101&_u.date01=20240131&1052-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22vaos-eligibility-direct-available-clinics-failed%22,0%5D%5D&1052-table.plotKeys=%5B%5D&1052-table.secSegmentId=analytics.customDimension85&1052-graphOptions.selected=analytics.nthDay/) breaking down the vaos-eligibility-available-clinics-failed broken down by "Facility ID".
<img width="1658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c29ecc62da9296c63353cef83c94cb10ec137a11/image.png" alt="image.png" />

**Comment by jenniemc** [comment] 2024-09-10 01:24
Q Where in the direct scheduling workflow does this event occur?
A: It happens when the user selects a facility at the “Choose a VA location” page. It triggers an eligibility call to check (1) direct schedule for type of care is set to enabled. (2) clinic api call is send to retrieve the clinics
Q What are the root causes for this event being triggered?
A: The event “vaos-eligibility-direct-available-clinics-failed” is triggered because the API call is returning empty clinics. (facility has option to turn on/off direct schedule for the clinic)
Q What data can be logged to identify conditions that cause this event to be triggered frequently?
A: The event “vaos-eligibility-direct-available-clinics-failed” also logs the facilityID along with the type of care. The event name is not necessarily a failure/error in the api call but that there are no clinics returned for the type of care at the particular facility. **Each facility has ability to turn on/off direct schedule for the clinic at the vista level. Please confirm this with Marcy.**
Q. What is the user experience when the event is triggered?
A. When the event is triggered, the app then checks if (1) request appointment configuration is enabled and (2) user passes the request eligibility check. If the two conditions are met, then the user will be sent to the request appointment flow. 
Q. What happens if the event is triggered but user fails the request eligibility check?
A. The request eligibility check evaluates the past history visit with the clinic.  It can be 12 or 36 months past history requirement. If the user doesn’t meet the history check, it will display the following message:
![Screenshot 2024-09-09 at 6 01 16 PM](https://github.com/user-attachments/assets/1df5f1e8-633f-4104-bf1d-106ffe33a636)
Q. What happens if the event is triggered and request appointment configuration for type of care is disabled?
A. It will display the following message:
![Screenshot 2024-09-05 at 2 31 07 PM](https://github.com/user-attachments/assets/3bc3ea75-f0c4-46a6-b0b8-2a5e7c911286)
Q. What other message will the user see if the event is triggered
A. If direct appointment configuration and request appointment configuration are both enabled but past history visit fails for both of appointment types and event is triggered, then user will see
![Screenshot 2024-09-09 at 5 15 29 PM](https://github.com/user-attachments/assets/0f46965d-2210-4562-9ff0-8eb0f1536e0b)

**Comment by ldelacosta** [comment] 2024-09-16 14:20
@JRRoof and I will review this ticket. No further action needed. Closing out the ticket.

**Closed by ldelacosta** 2024-09-16 14:20 UTC
Labels: frontend, appointments, spike
