### ISSUE TITLE
Update ordering of Dependent Child section in PDF

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74700] opened 2024-01-28 03:32 UTC
Dependent children information is all there, but the order of fields may cause confusion to the reader of the PDF. 

**Some suggestions:** 
Start the overflow list with the child/dependent’s name, and then the rest of the fields that correspond to that person
If they don’t live with them, place amount $ contributed after their custodian name and address

_Example if they live with you:_
- Child name
- DOB
- Place of birth
- SSN
- Child status line

_Example if they DO NOT live with you:_
- Child name
- DOB
- Place of birth
- SSN
- Child status line
- Custodian name
- Custodian address
- Amount of contribution for child

**Comment by vbellissimo** [comment] 2024-01-31 15:48
Closing this ticket, as it is now a duplicate of #74994

**Closed by vbellissimo** 2024-01-31 15:48 UTC
Labels: backend, pension, engineering
