### ISSUE TITLE
[Links] [508] Create a download & video link component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#11852] opened 2020-07-30 17:20 UTC
## Description

Build a download & video link React component based on the [markup examples comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340) from @jenstrickland .

Consider building two separate components: one for download & a second for video links

<details open><summary>Markup Examples</summary>

<br />
Note: This content was copy/pasted from the comment linked above, it may not exactly match if edited after July 28, 2020

-----

Collaborating with @1copenut, we reviewed the icon implementations to ensure accessibility. 
- Added `aria-hidden="true"` to `<i>` to suppress the injected text content (that renders the icon) from screen readers
- To comply with WCAG, we edited link text to be clear about what the link does without the surrounding content. _(2.4.4, 2.4.9 - "**The link text MUST make sense in context, and should make sense when taken out of context** (problematic phrases include: “click here,” “learn more,” “more,” “read more,” etc.).)"_

**Download PDF Link Example**
```HTML
<a 
  href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" 
  download="Voices_Of_Veterans.pdf" 
  type="application/pdf">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download the Voices of Veterans <dfn><abbr title="Portable Document Format">PDF</abbr> (4.9<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

**View Video Example**
```HTML
<a 
  class="video-link" 
  href="https://www.youtube.com/watch?time_continue=3&amp;v=xE0LzeRgdAk" 
  target="_blank" 
  rel="noopener ">
    <i aria-hidden="true" class="fas fa-play-circle vads-u-padding-right--1" role="img"></i>
      View video about VA disability compensation <dfn>on Youtube</dfn>
</a> 
```

**Download Graphic Link Example**
```HTML
<a 
  class="file-download-with-icon" 
  href="/img/2019-07/VA-020-Web-Badges-205x175-al-1.02.jpg" 
  download="/img/2019-07/VA-020-Web-Badges-205x175-al-1.02.jpg">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download VA benefits to people who've served <dfn><abbr title="graphic">JPG</abbr> (0.11<abbr title="Megabytes">MB</abbr>)</dfn> 
</a>
```

**Download Word Document Example**
```HTML
<a 
  class="file-download-with-icon" 
  href="/files/2019-07/190111-ChooseVA-Marketing-Flyer-2019.docx" 
  download="/files/2019-07/190111-ChooseVA-Marketing-Flyer-2019.docx">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download Learn how to apply for VA benefits <dfn><abbr title="Word document">DOCX</abbr> (0.49<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12184

### Guidance

* [Proposal for a more accessible Download Link](https://accessabilly.com/proposal-for-a-more-accessible-download-link/)

* [CSS Tricks - Building a Good Download "button"](https://css-tricks.com/building-good-download-button/)

* [I thought title text improved accessibility. I was wrong.](https://silktide.com/blog/i-thought-title-text-improved-accessibility-i-was-wrong/)
</details>

## Acceptance Criteria

- [ ] Download link follows example patterns
- [ ] Video link follows example patterns

**Comment by vhenry07** [comment] 2022-01-25 19:57
Work owned by design system team.

**Comment by caw310** [comment] 2022-04-14 18:32
Fixes from this ticket are addressed in another ticket so closing.

**Comment by caw310** [comment] 2022-04-18 18:51
@k80bowman Please identify development work that is needed.

**Comment by andresriveratoro** [comment] 2022-07-08 20:49
I believe we can close this ticket because our [va-link web component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/974) will include download and video link variations.

**Comment by bkjohnson** [comment] 2022-09-09 19:53
Final review is finished.

**Closed by bkjohnson** 2022-09-09 19:53 UTC
Labels: 508/Accessibility, 508-issue-semantic-markup, 508-experiment, vsp-design-system-team, DST-audited
