### ISSUE TITLE
Build va-notify template for Submitted Email

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94194] opened 2024-10-02 23:13 UTC
### User Story
As a Veteran, I want to get an email from VA that acknowledges my application has been successfully submitted, using plain language and a consistent visual format, so that I feel confident my claim submission was submitted and I can easily reference key details about my claim.

### Background
Currently, Veterans get a "received" email only after their claim has been received by VA systems, which can take up to several hours or even days. This creates uncertainty immediately following submission when Veterans most need confirmation. To address this gap, we are introducing a new "submitted" email that will be sent immediately after claim submission. This immediate confirmation will help Veterans feel confident their claim was received and provide them with essential reference information.

### Tasks

- [ ]  

### Acceptance Criteria

Content Requirements  
- Match approved content from Figma design specifications
- Include Form 21-526EZ as the form name
- Display the submission date in standard VA.gov date format
- Show the claim ID number prominently (for primary path submissions)
- Use approved VA plain language standards for all text content

Technical Requirements  

- Template is prepared for sending emails correctly for both primary and backup path submissions using the email trigger
- Template is prepared to send through va-notify using a unique template id
- Handle missing data fields gracefully with appropriate fallback content (or null content - i.e. no claim id for backup path)

Design Requirements

- Follow email design patterns as specified in [Figma](https://www.figma.com/design/f0CuXrBUVs86NDm6cqmduK/(526ez)-Submission-Experience?node-id=1-40)
- Meet VA accessibility standards for email communications
- Display properly across desktop and mobile email clients
- Maintain consistent formatting in major email platforms (Gmail, Outlook, Apple Mail)
- Reviewed by Design

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/f9d47c80-c3b9-4f35-8b37-8f42b9bfdbc8" />

**Comment by christinec-fftc** [comment] 2024-12-23 22:17
Created a new template for staging called 'Form 56ez Submited email' with template id `9b5510d4-f115-4735-b2e4-726f4ff281ad`

**Comment by christinec-fftc** [comment] 2024-12-23 23:51
```# We've received your VA Disability Compensation Claim Form (21-526EZ)

Dear ((first_name)),

We received the VA Disability Compensation Claim Form 21-526EZ you submitted on [VA.gov](https://www.va.gov). Keep reading for more details and what to expect next.

^ ## Submission details
^ ### Form submitted
^ Disability Compensation Claim
^ VA Form 21-526EZ
^
^ ### Date submitted
^ ((date_submitted))
^
^ ### Date received
^ ((date_received))
^
^ ### Claim ID number
^ ((claim_id))


## What to expect next
We’ll send you a letter to let you know we have your claim. You should get this letter in about 1 week, plus mailing time.

## Your VA Form 21-526EZ submission
Call us at [800-827-1000](tel:8008271000) ([TTY: 711](tel:711)). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

Thank you

---
You are receiving this email because you filed a claim on [VA.gov](https://va.gov). Don't reply to this email.```

**Comment by christinec-fftc** [comment] 2024-12-24 00:15
test email sent from the va-notify tool <img width="660" alt="Image" src="https://github.com/user-attachments/assets/46e7ca0a-a5c1-4c4b-bbca-eafef894fd04" />

**Comment by christinec-fftc** [comment] 2024-12-24 19:26
We mobbed on this and we were able to get the conditional logic for claim id working 🎉  cc @sethdarragile6 

Note: when we create/update the job that sends the email, make sure that claim id values is an empty string. Does not work if using `nil`

**Example 1: with claim id**
<img width="605" alt="Image" src="https://github.com/user-attachments/assets/5d72f06f-f17b-423c-abd6-73508df8a19f" />

**Example 2: no claim id**
<img width="605" alt="Image" src="https://github.com/user-attachments/assets/086e22ea-6722-48ad-adfa-57120b2e2b54" />

**Comment by bacitracin** [comment] 2024-12-24 23:06
Reviewed by design & a11y, all looks good. Closing issue

**Closed by bacitracin** 2024-12-24 23:06 UTC
Labels: frontend, engineering, disability-experience, DBEX-TREX
