### ISSUE TITLE
Debt Resolution: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52710] opened 2023-01-27 18:20 UTC
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [x] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [x] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [x] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [x] Check for missing tests or duplicated tests
- [x] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by laineymajor** [comment] 2023-02-14 18:44
@denisecoveyduc How is testing going? Do you all anticipate being able to sign off on staging by end of February?

**Comment by denisecoveyduc** [comment] 2023-02-14 21:27
Hey @laineymajor Thanks for checking in. I just confirmed with @ScottyRJames who will be doing the work needed for this as part of [#52938](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52938). We do have that slated for our next sprint which runs Feb 15-28... so assuming there are no issues we will be able to sign off by the end of February. 

I added a note to have Scott add a comment here when work is done.

**Comment by laineymajor** [comment] 2023-02-23 03:33
Thanks @denisecoveyduc and @ScottyRJames 

If any questions or issues come up, please ping us in #eks-migration-support and someone from my team will jump in!

**Comment by denisecoveyduc** [comment] 2023-03-01 20:50
Move to blocked until @ScottyRJames  has had a chance to wrap up #52938

**Comment by ScottyRJames** [comment] 2023-03-06 14:26
Hi @laineymajor, just wanted to followup that we are currently in progress with testing our endpoints and getting close to validating!

**Comment by ScottyRJames** [comment] 2023-03-06 18:54
Hey @laineymajor, apologies for the delay on this testing. We have tested and validated the following endpoints on dev and staging environment. I used Postman since I currently don't have access to Datadog synthetic tests. I did not notice anything out of the ordinary or any errors with the endpoints!

- `GET /v0/medical_copays`
- `GET /v0/medical_copays/:id`
- `GET /v0/medical_copays/get_pdf_statement_by_id/:statement_id`
- `GET /v0/debts`
- `GET /v0/debts/:id`
- `POST /v0/financial_status_reports`
- `GET /v0/financial_status_reports/download_pdf`
- `GET /v0/debt_letters`
- `GET /v0/debt_letters/:id`
- `GET /v0/in_progress_forms/5655`
- `PUT /v0/in_progress_forms/5655`

**Comment by ScottyRJames** [comment] 2023-03-14 22:09
Our team has tested our owned endpoints within staging and found no problems. Closing this out but if any concerns or issues arise it can be reopened or communicated in the `#eks-migration-support` channel.

**Closed by ScottyRJames** 2023-03-14 22:09 UTC
Labels: backend, blocked, vsa-debt, platform-tech-team-1
