### ISSUE TITLE
[Design] DD4edu: Kickoff UAT recruiting

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19741] opened 2021-02-10 16:23 UTC
## Background
We  need to recruit participants for DD4edu UAT.

## Tasks
- [ ] Recruit participants for UAT

## Acceptance Criteria
- [ ] Perigean has been contacted for scheduling

**Comment by Samara-Strauss** [comment] 2021-03-05 22:24
Closing, This is a duplicate of #20388.

**Closed by Samara-Strauss** 2021-03-05 22:24 UTC
Labels: design, direct deposit, vsa, vsa-authenticated-exp, vsa-ebenefits
