### ISSUE TITLE
[FwdProxy,GHA] VA Certificate Testing in Dev

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#81291] opened 2024-04-22 17:54 UTC
## Description
Anytime we rebuild the VA cert image we need to test it.  This needs to be automated through Github Actions

## Notes
- We may have to update our script that pulls down all the VA certs  
- We need parity with what we have setup today 

## Acceptance Criteria
- [ ] VA certs are verified by GitHub actions anytime they are updated

**Comment by npeterson54** [comment] 2024-05-08 15:21
Removing from sprint since https://app.zenhub.com/workspaces/platform-infrastructure-services-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/81841 was pulled in

**Comment by ph-One** [comment] 2024-09-05 12:25
Closing. Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/81277

**Closed by ph-One** 2024-09-05 12:25 UTC
Labels: Infrastructure-Services
