### ISSUE TITLE
[Development] Letters: Issues with Address

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7701] opened 2020-04-07 15:05 UTC
## What happened?
We are still seeing errors with the address validation on the back end when submitting requests for letters.

Transaction ids:
vagov-fb7cd275-702b-43f8-9f32-f20d1fd0a7b1
vagov-0e97be3a-14b2-43f1-8f40-ca70f8b70798
vagov-57bed181-f252-4d71-855f-138781eabc92
vagov-93ffd01a-cb30-4c35-aff6-4197979da8e9

> We have researched each Transaction IDs you provided us with and found the veteran's records are missing addressLine1 element for each of them. The service immediately returns letterDestination.addressLine1.invalid for empty addressLine1 and that is valid.

> According to service implementation of Letter Generator, the error related to invalid address lines (key: letterDestination.addressLine1.invalid) is thrown when addressLine1 is missing in CORP RECORD and that's an expected behavior.

Inconsistency between CORP and VA profile is being examined.

## Desired behavior
No errors!

## Acceptance Criteria
- [ ] Fix is identified (whether our end or otherwise.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by annaswims** [comment] 2020-05-11 15:22
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8575#issue-609247664 is a dublicate issue with additional steps to reproduce.

**Comment by annaswims** [comment] 2020-05-11 18:04
The timeline looks similar to the release/rollback/re-release of EVSS ![Screen Shot 2020-05-11 at 2.00.33 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/0ca0cbe6-2cc5-4737-90b7-382a958ad9cd)

**Comment by annaswims** [comment] 2020-05-11 18:07
`vagov-4f6a32bc-6207-4c80-9c38-08ec19b7976f` is an example of a transaction where there was an address in vets360, prior to the evss call.

**Comment by annaswims** [comment] 2020-05-15 17:56
The issue looks to be an EVSS issue that is resolved now.  I say that it was an evss issue because I think the timing corresponds with their deploy->revert->re-deploy>new deply
<img width="326" alt="Screen Shot 2020-05-15 at 1 26 42 PM" src="https://user-images.githubusercontent.com/19188/82080968-8a30fc80-96b3-11ea-8dd8-55943e7fe105.png">

**Comment by annaswims** [comment] 2020-05-19 14:52
It's been 6 days since we've last seen this error.  Looks to be resolved by evss.

**Comment by annaswims** [comment] 2020-08-27 16:14
We're seeing the error again from evss http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/154347/?query=addressLine1

**Comment by luke-gcio** [comment] 2020-11-18 16:29
Adding Lihan to assignment list but this is a Luke action to follow through on first.

**Comment by annaswims** [comment] 2021-02-09 20:08
future work will be tracked in #7816

**Closed** 2021-02-09 20:14 UTC
Labels: Debt Letters MVP, backend, bug, discovery, vsa, vsa-benefits
