### ISSUE TITLE
QA Standards - Employee Experience Team - 21-526EZ/Max CFI

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#83975] opened 2024-05-28 03:19 UTC
#### VFS team name
Employee Experience Team

#### VFS product name
21-526EZ

#### VFS feature name
Max CFI

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Regression Plan included - it is not clear to me if this feature is entirely new (ie has no analog or precursor even outside of va.gov); if it is not entirely new then a Regression Plan is required.
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No traceability reports included.
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 87.17

- Functions %: 84.01

- Statements %: 87.09

- Branches %: 81.09

- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [x] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by mackhowell-nava** [comment] 2024-06-03 20:43
Hi @it-harrison we created a regression test plan and ran the test in TestRail here: https://dsvavsp.testrail.io/index.php?/plans/view/5579

This should satisfy the Regression Test Plan requirement, but let me know if you have any questions! 

If not, are we OK to close this ticket? 

Thank you! 
cc @dfitchett @ChristineRoseSteiffer

**Comment by mackhowell-nava** [comment] 2024-06-04 16:57
Ah, looks like according to the directions above: 

"Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards."

I will make sure to share this with @jenniferbertsch today.

**Comment by mackhowell-nava** [comment] 2024-06-04 17:45
Closing this ticket as we've met all the requirements.

**Closed** 2024-06-04 17:45 UTC
Labels: QA, collab-cycle-feedback, qa-standards, Staging, launch-blocking
