### ISSUE TITLE
Deprecate - Google Analytics OPIA Property (Ending in 418-15 in Google Analytics)

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#7837] opened 2020-04-09 21:07 UTC
# Analytics Review

## What this form is for
Prior to Brand Consolidation in 2018 with Vets.gov, the former contract team configured Google Tag Manager to also send data to a Google Analytics property called OPIA Joint Data (which has a unique identifier ending in `418-5`). While this does not add any lift to our implementations, discovery should be completed to see if this  Google Analytics property may be deprecated. 

This is referenced in documentation within the [Teams Folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md#vagov-account-and-active-properties).

## Acceptance Criteria
- [ ] Team decides if this property should be deprecated
- [ ] Google Tag Manager reconfigured so it does not send data to OPIA

## Definition of Done
- [x] Slack announcement made 30 days ahead of archiving
- [ ] OPIA Joint Data tags and variables removed from GTM
- [ ] Property is renamed with _Historical -_ prefix

**Comment by jonwehausen** [comment] 2020-11-10 13:52
@bsmartin-ep @bmcgrady-ep @joanneesteban 

Met with Josh Tuscher last week and he confirmed that the OPIA property is currently not actively being used -- 

We currently send a page view tag to their property ending in 418-15 in addition to our own that eats into our GA360 hit quota. 

@bsmartin-ep **We can setup a workspace to pause (_or delete, whichever your prefer_) this tag and before deploying we can do some final due-diligence checks / message blasts before deprecating.**

**Comment by joanneesteban** [comment] 2020-12-01 22:45
It looks like that workspace was set up [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15793#issuecomment-731619641). Is that correct?

**Comment by bsmartin-ep** [comment] 2020-12-02 04:00
@joanneesteban -

I believe that is different from this.

That is the GTM implementation for this site:  www.choose.va.gov

...which will start logging those pageviews to our usual modernized GA property.

This is a tag (two actually - OPIA Joint and OPIA Property) that log pageviews and events from www.va.gov to other GA properties:

![image](https://user-images.githubusercontent.com/62304138/100826534-96e72900-3428-11eb-859d-a3fe5f6db982.png)

**OPIA Joint:**
UA-50123418-15

**OPIA Property:**
UA-69938072-4

(Correct me if I'm wrong @jonwehausen)

**Comment by joanneesteban** [comment] 2020-12-02 16:50
Moving to Blocked until we hear back from Josh.

**Comment by bsmartin-ep** [comment] 2020-12-06 23:54
The following tags have been paused [in this GTM workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000403)

- OPIA Joint Events
- OPIA Joint Pageviews
- OPIA Property Events
- OPIA Property Pageviews

These are the individual pageview and event tags for OPIA Joint and OPIA Property.  

Are we pausing (eventually deleting) both?  They are attached to these GA properties:

**OPIA Joint:**
UA-50123418-15

**OPIA Property:**
UA-69938072-4

(cc @Hampshire100)

**Comment by jonwehausen** [comment] 2021-05-12 00:52
### Next Steps
- Upon final approval from Josh Tuscher, work to completely deprecate the OPIA property in order to free up hit count utilization

cc: @bsmartin-ep @laurensimpson14

**Comment by bsmartin-ep** [comment] 2021-07-02 23:51
Bumping this @joanneesteban 

OPIA logged 105,712,370 hits in 2021-June.  ~32% of our monthly usage. 

https://marketingplatform.google.com/home/orgs/oXPY3GFFQwaHnjNHpFLyFg/usage?period=2021-06&orderType=1&authuser=0

**Comment by joanneesteban** [comment] 2021-07-06 13:37
@bsmartin-ep it looks like this needed approval from Josh? Have y'all linked up with him for choose.va.gov?

**Comment by bsmartin-ep** [comment] 2021-07-28 18:46
As [noted on Slack](https://dsva.slack.com/archives/CE4304QPK/p1627497325387700), this property will be disconnected and archived on Friday August 27, 2021.

**Closed** 2022-01-05 15:38 UTC
Labels: analytics-insights, analytics-request
