### ISSUE TITLE
[Design] Preferred Medical Facilities: Create Research Plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22763] opened 2021-04-06 20:39 UTC
## Background
We need to create our research plan for preferred medical facilities. We'll do this in collaboration with VAOS. 

## Tasks
- [ ] Identify questions we want answered through our research
- [ ] Coordinate with VAOS
- [ ] Document detailed plan/questions

**Comment by andaleliz** [comment] 2021-04-21 17:18
This is a duplicate of #23320

**Closed by andaleliz** 2021-04-21 17:18 UTC
Labels: design, needs-grooming, planned-work, preferred-facility, research, vsa-authenticated-exp
