### ISSUE TITLE
[Content styleguide] Content doesn't align with style guidance in VA.gov content style guide (05.08.1)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34810] opened 2022-01-05 21:20 UTC
#### VFS team name

Claims & Appeals

#### VFS product name

HLR v2

#### Point of Contact/Reviewers (Practice area)

Randi Hecht (Content)

---

### Platform Issue

Content doesn't align with style guidance in VA.gov content style guide.

### Issue Details

There needs to be a comma after the year in the date: Your application is in progress and was last saved on January 4, 2022, at 2:37 p.m. 
We need to add ET to the end of the time. (Assuming this is in ET, which is what we use as our standard.)

<img width="761" alt="Screen Shot 2022-01-05 at 1 59 27 PM" src="https://user-images.githubusercontent.com/48728214/148273470-da1a8fb2-29e8-4f11-9893-d4d26c638f02.png">

When links stand alone, we don't use periods. There are a few instances throughout.

<img width="582" alt="Screen Shot 2022-01-05 at 4 19 51 PM" src="https://user-images.githubusercontent.com/48728214/148291039-18becd85-f9cd-40af-aa91-8789826748c8.png">

Don't use italics per style guide. 

<img width="806" alt="Screen Shot 2022-01-05 at 3 51 39 PM" src="https://user-images.githubusercontent.com/48728214/148287648-fce7eca1-7627-4c0a-8dfb-78e0adb1b52c.png">

Use the % symbol instead of spelling out the word. 

<img width="686" alt="Screen Shot 2022-01-05 at 4 06 29 PM" src="https://user-images.githubusercontent.com/48728214/148289494-27b669bc-4d8d-4246-9812-5f0e8fc06fa9.png">

### VA.gov Experience Standard

[Category 5, Issue 8. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

WCAG SC 3.2.4 AA

---

### Platform Recommendation

Add comma after date.
Add ET to time.
Remove periods from any links that stand alone. 
Remove italics.
Use % symbol.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket. 

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by Mottie** [comment] 2022-01-10 17:22
@RLHecht For the last issue "Use the % symbol instead of spelling out the word.", the content "Service connection for..." comes directly from Case Flow. It would be possible for me to replace "percent" with a symbol on the front-end, if that would better match our guidelines.

**Comment by bethpottsVADEPO** [comment] 2022-01-18 18:17
@RLHecht Want to answer this last question and then this ticket can probably be closed?

**Comment by Mottie** [comment] 2022-01-18 18:19
Hi @bethpottsVADEPO, I've already implemented code to visually replace "percent" with "%" within the issue description.

**Comment by RLHecht** [comment] 2022-01-18 18:27
That works @Mottie. Thanks for making this fix!

**Comment by Mottie** [comment] 2022-01-19 15:29
All the work for this ticket has been completed. The timezone change will be available in staging soon.

**Comment by shiragoodman** [comment] 2022-01-19 22:26
@Mottie just FYI, Platform Collab Cycle folks will never close these tickets. Per the VFS Team Tasks to Complete section above, you are free to close the ticket when the fix has been validated with your Product Owner. If it's an accessibility issue and you don't have the expertise to know if the issue is solved, you can tag us and we can assist. Let me know if you have any questions!

**Closed** 2022-03-01 14:24 UTC
Labels: content, frontend, 508/Accessibility, vsa-claims-appeals, collab-cycle-feedback, Staging, CCIssue05.08, CC-Dashboard, benefits-crew
