### ISSUE TITLE
[SCREENREADER]: VoiceOver in Safari, page load time interferes with access to Skip to Content link

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#3673] opened 2019-11-22 18:57 UTC
## Description

**[SCREENREADER]: VoiceOver in Safari, page load time interferes with access to Skip to Content link**

In other screen readers, when the page loads, tab reveals Skip to Content link. On VA.gov home, the Skip to Content link is immediately available. However, on this page, the Skip to Content link isn't available on tab, unless user waits 20 seconds. 

## Point of Contact

Jennifer

## Acceptance Criteria

As a screenreader, keyboard, or switch user, I want to skip the navigation area of a page and go directly to the main content area so I may access content without tabbing through all of the navigation content.

## Environment

* Operating System: Mac
* Browser: Safari
* Screenreading device: VoiceOver
* Server destination: https://staging.va.gov/disability/view-disability-rating/rating/

## Steps to Recreate

1. Enter `https://staging.va.gov/disability/view-disability-rating/rating/` in browser
2. Log in as `vets.gov.user+228@gmail.com`
2. Start screenreading device listed in Environment
3. Tab to reveal Skip to Content link
4. Verify that Skip to Content link isn't available
5. Reload page, then wait 20 seconds
6. Verify that Skip to Content link is now available

## Possible Fixes (optional)

There is a possibility this is web performance related, and could be resolved by prioritizing resources. Loading slow resources like the Facility Locator data in the `<head>` may be creating a delay for this page, causing VoiceOver to not be able to hook in.

## WCAG or Vendor Guidance (optional)

[Resource Prioritization](https://developers.google.com/web/fundamentals/performance/resource-prioritization)

[Marcy Sutton on Accessibility and Performance](https://marcysutton.com/accessibility-and-performance)

## Screenshots or Trace Logs

![3577-perfprofile.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/9a48200f-29ca-40b4-9150-ceec3d7f0598)

![3577-lighthouse-perf.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/e017f832-bbb5-4903-bb01-7230355e4d0d)

**Comment by jason-gcio** [comment] 2019-12-21 00:57
While this has not been resolved it has been moved to the correct team to address it further.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3673

**Comment by jenstrickland** [comment] 2019-12-21 14:39
VA gov performance team is evaluating web performance and the possible impact on this page.

**Comment by laflannery** [comment] 2023-08-23 18:56
I'm not entirely sure this is a PW issue. It seems like a duplicate of #3961 which specific specifically to authenticated pages and is more an overall performance issue, not something for the PW team to tackle.

**Comment by FranECross** [comment] 2023-12-07 15:44
@jilladams @laflannery Laura's comment above indicates this doesn't belong with the PW team, but I'm not sure which team it would go to. Do either of you know? 😁

**Comment by jilladams** [comment] 2023-12-07 17:54
From a11y perspective, if @laflannery  understands this to be a dupe, we could just close it, and add VA.gov homepage to the list of pages that need to be evaluated in #3961.  THe only reason we'd need to keep it open would be if the behavior in question is particular to the homepage (whether authed or unauthed). That doesn't seem to be the case here, but will let Laura confirm and then either Fran or I can do the ticket cleanup.

**Comment by FranECross** [comment] 2023-12-07 19:20
We don't believe this is a PW specific issue; more of an overall issue. Removing PW from label and will check with Jill to determine which team it belongs with.

**Comment by FranECross** [comment] 2024-07-12 20:38
Info added to 3961. Closing this ticket.

**Closed by FranECross** 2024-07-12 20:38 UTC
Labels: accessibility, sitewide
