### ISSUE TITLE
[UX][SPIKE] Expired session/no appointments refresh

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#49400] opened 2022-11-07 21:37 UTC
## Description
When a user reloads the day-of check-in application, we request data to rebuild the page. If a user's session is expired or if there are no appointments returned in the payload we send them to a generic error page that makes it seem like there was an issue performing a check-in. 

This ticket is to determine if we need another type of error page, or if we should redirect the user back to va.gov, or if the current system is as designed and good. 

## Acceptance Criteria
- [ ] Content has been created & reviewed

**Comment by benbrasso-agile6** [comment] 2022-11-08 14:15
@brianseek do you have a screenshot of the existing message?

**Comment by ytsaoca** [comment] 2022-11-10 18:46
Current screenshot:![localhost_3001_health-care_appointment-check-in_see-staff (1).png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/b4356a6b-d1a1-4b1a-9f69-1770beb74c30)

**Comment by ytsaoca** [comment] 2022-11-10 18:46
Current screenshot:![localhost_3001_health-care_appointment-check-in_see-staff (1).png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/b4356a6b-d1a1-4b1a-9f69-1770beb74c30)

**Comment by ytsaoca** [comment] 2022-11-10 22:38
From @brianseek :

People never get “logged out” because technically they never log in. Instead, they validate their identity and access the application. Their session is saved in the back-end meaning permissions get checked when the api is called. Which only happens at validation, and then again when they complete demographics, and again when they check-in. 

Now with the reload ability, the API will fetch the appointment and veteran payload again if they reload the page. So if you have the application open on your phone, it will stay open for days…until you reload or do something to trigger another api request.

The time out is pretty long, something like 15 hours….I’ll have to double check that with the backend team

**Comment by ytsaoca** [comment] 2022-11-10 22:38
From @brianseek :

People never get “logged out” because technically they never log in. Instead, they validate their identity and access the application. Their session is saved in the back-end meaning permissions get checked when the api is called. Which only happens at validation, and then again when they complete demographics, and again when they check-in. 

Now with the reload ability, the API will fetch the appointment and veteran payload again if they reload the page. So if you have the application open on your phone, it will stay open for days…until you reload or do something to trigger another api request.

The time out is pretty long, something like 15 hours….I’ll have to double check that with the backend team

**Comment by ytsaoca** [comment] 2022-11-15 22:59
From @brianseek 

session expiration happens without regard to check-in window. But with the session timeout being so long, it is safe to say that it always happens outside of the check-in window. If there is no session, we can’t know anything about the appointment.

--------
If it is safe to say that it always happens outside of the check-in window because of the long session timeout, maybe we can edit based on this wireframe? https://share.goabstract.com/522b18f5-15b7-4d5d-9a52-d01455accd24?mode=design&sha=64d51ab960ccab254571c9537551980a4ab90afb

**Comment by loripusey** [comment] 2022-11-16 14:39
Why can't we just tell them what is actually happening, which is the check-in link has expired and they will need to initiate a new check-in if that is their intent?

**Comment by loripusey** [comment] 2022-11-16 14:40
Are we done with this ticket? It doesn't sound like we have reached a way forward, I am inclined to put it back on the backlog for a future sprint.
cc: @benbrasso-agile6

**Comment by loripusey** [comment] 2022-11-16 14:42
This seems like a duplicate of this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49521) I'm going to close this ticket and reference it the other ticket for further discovery

**Closed by loripusey** 2022-11-16 14:42 UTC
Labels: content, research, ux, HCE-Checkin

**Comment by benbrasso-agile6** [comment] 2022-11-16 18:07
Thanks, sounds good
