### ISSUE TITLE
Spike: Determine how `vets-api` can render `html` on a browser with a simple form that calls a `vets-api` backend route

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53029] opened 2023-02-03 16:12 UTC
Investigation for frontend 'mocked credential provider' component of mocked authentication.

The intention of this investigation are to:
- Discover ways in which the `vets-api` backend can render a single page with simple forms on a browser
- Ensure the authentication redirect flow is possible with a rendered page from `vets-api`
  - Redirect flow is:
    - `vets-website` calls `v0/sign_in/authorize` on `vets-api` backend
    - `v0/sign_in/authorize` returns html that `vets-website` renders
    - This html will redirect to the 'mocked credential provider' frontend page served by `vets-api`
    - The 'mocked credential provider' frontend page will make some server call to `vets-api`
    - The 'mocked credential provider' frontend page will make call to `v0/sign_in/callback`
    - Expectation is that once `v0/sign_in/callback` completes, it will redirect back to `vets-website` frontend successfully
- It is possible that `vets-api` is currently in 'api only mode', which may complicate options (although services like sidekiq UI are rendered, so there must be possibilities)
- Solution must be able to work for localhost, and dev.va.gov stack

**Comment by bosawt** [comment] 2023-05-03 17:11
this has been completed by other tickets

**Comment by rileyanderson** [comment] 2023-05-03 17:11
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/53030

**Closed** 2023-05-05 03:31 UTC
Labels: Identity, spike, identity-backend
