### ISSUE TITLE
[DUPLICATE] SEP walkthrough Derrick

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69583] opened 2023-11-09 15:27 UTC

**Comment by nihil2501** [comment] 2024-01-18 20:03
Closed as duplicate of [this](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/69576)

**Closed by nihil2501** 2024-01-18 20:03 UTC
Labels: accredited-rep-facing
