### ISSUE TITLE
Refactor VA appointment E2E tests

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#67320] opened 2023-10-11 15:19 UTC
## Description
We want to remove any skipped test(s) in this file `src/applications/vaos/tests/e2e/flows/va-appointment.cypress.spec.js` and update our VA appointment e2e tests to match the VA appointment flow in production.

---

## Acceptance Criteria
- [ ] No test is skipped
- [ ] Feature flags should be set to match production settings. All unused feature flag settings should be removed as well.
- [ ] VA appointment e2e tests to match the VA appointment flow in production.

## Definition of Done
- [ ] All acceptance criteria are met

---

**Comment by JRRoof** [comment] 2023-11-15 17:57
Closed as duplicate of [#69615](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69615)

**Closed by JRRoof** 2023-11-15 17:57 UTC
Labels: frontend, appointments
