### ISSUE TITLE
Resources and Support FE bug from Sitewide Content team

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#29538] opened 2021-08-31 20:45 UTC
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [x] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Resources and Support 
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * https://www.va.gov/resources/search/?query=disability

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [x ] **Other**
   * Please describe in detail
For [this page](https://prod.cms.va.gov/resources/combat-related-special-compensation-crsc), front end [here](https://www.va.gov/resources/combat-related-special-compensation-crsc/) when searching for "Disability", the article does not return. It appears that the search is only returning off of what's in the title.

![image](https://user-images.githubusercontent.com/60702623/131905020-3fd52619-958a-45cd-a4ed-cc04e44ec918.png)

Expected behavior is when something is checked as an article category in the CMS:

![image (30)](https://user-images.githubusercontent.com/60702623/131905134-c48ec86e-0840-47c6-bc04-f3bd3e75efc7.png)
 
it would return when searching for that article category.

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* would like to get in before sending for stakeholder review. @RLHecht will have specifics on the date needed.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *Sitewide Content*
- DEPO product owner: *Beth Potts and Danielle Thierry*
- Product manager: *Randi Hecht*
- Designer: *enter name*
- FE engineer: *enter name*
- Product/team Slack channel: *enter*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by RLHecht** [comment] 2021-09-02 15:52
@cmaeng I think I misunderstood what was showing on the preview page. The article categories is separate from the benefit hubs. Those 3 are checked and correctly showing so this isn't a bug after all. But I guess a new question is what do those article categories do? You can't search by the category on the Resources landing page--if you do, only the articles that have that word in the H1 will show up, not all that are in that category. Is that supposed to happen?

**Comment by cmaeng** [comment] 2021-09-02 18:34
@RLHecht yes, articles should come up in search based on those categories and not just what's in the title.

@brianalloyd should we tweak this ticket to reflect or close and open a new one?

**Comment by brianalloyd** [comment] 2021-09-02 18:38
@cmaeng we could probably tweak to support new objective. Either way works for me.

**Comment by cmaeng** [comment] 2021-09-02 19:35
k, should be good to go now @brianalloyd . let me know if you have any questions. thanks!

**Comment by brianalloyd** [comment] 2021-10-01 15:28
@kelsonic does this fit the search logic you and Jen Lee were implementing for R&S?  The search team is going to be taking over R&S and may shift this ticket over to them for future action but would like to get your technical analysis on search logic based on past work with Jen Lee.

**Comment by kelsonic** [comment] 2021-10-01 15:57
Jen and I had many conversations about optimizing search for R&S, and by the end of it we got it in a state where she was very happy with it. This ticket is stating this as a bug but it was designed this way for a reason:

1. Omit words in the search query that are on [our search ignore list](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/resources-and-support/constants/index.js#L2).
1. Un-pluralize words in the search query (e.g. `disabilities` => `disability`).
1. Find articles that include any of the remaining search query words in its title (casing agnostic).
1. Sort articles first by the number of exact query matches (ignoring casing) in the `title`, `introText`, and `searchableContent` descending.
1. Sort ties by query word instances found in `title` descending.
1. Sort ties then by query word instances found in `introText` and `searchableContent` descending.
1. Sort ties then by alphabetical `title` descending.

We purposefully only show results if the article includes any of the remaining search query words in its title (casing agnostic). The reason for this is because imagine if someone typed in `health` and we pulled all articles that had not only the word `health` in the article's `title`, but also in its searchable content or intro text. We would get almost 10x+ results, which is actually not desirable we found when looking through the analytics data.

**Comment by cmaeng** [comment] 2021-10-01 20:18
thanks @kelsonic that helps a ton.

@RLHecht i was mistaken in that the search was designed not to pull from the article categories. please let us know if you have any additional questions or concerns regarding this. @brianalloyd i believe this ticket can be closed to no action.

**Comment by brianalloyd** [comment] 2021-10-04 18:02
Closing in support, thanks Team.

**Closed by brianalloyd** 2021-10-04 18:02 UTC
Labels: vsa-public-websites, vsa, needs-grooming, vsa-public-websites-intake, planned-work
