### ISSUE TITLE
[Development] Claims Status: Do We Still Have Upload Issues

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11865] opened 2020-07-30 19:53 UTC
## Issue Description
EVSS deployed Tika (https://tika.apache.org/) and it should have taken care of a lot the file upload issues.  This story is to investigate whether this is still happening.

1. What are we seeing in Sentry?
2. What does the Call Center say? Update: Waiting on Call Center to respond to question.

## Acceptance Criteria
- [x] We document any kinds of errors (get some specifics and send them to EVSS)

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment] 2020-09-28 16:31
yes, still a lot of file upload errors

http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/activity/?query=is%3Aunresolved%20assigned%3Ame

**Comment by annaswims** [comment] 2020-09-28 17:04
reopened https://github.com/department-of-veterans-affairs/va.gov-team/issues/13293

**Comment by annaswims** [comment] 2021-01-21 18:49
Still plenty of errors http://sentry.vfs.va.gov/organizations/vsp/issues/452/?query=transaction%3A%22Sidekiq%2FEVSS%3A%3ADocumentUpload%22&statsPeriod=14d

**Comment by annaswims** [comment] 2021-02-09 20:13
related https://github.com/department-of-veterans-affairs/va.gov-team/issues/19680

**Comment by michelpmcdonald** [comment] 2022-03-08 21:03
Yes, we still hit upload errors.

**PDFs:**
We have problems with PDF permissions.  PDFs have two type of permissions, "User" and "Owner".
User permissions are "**view**" permissions that allow the PDF to be un-openable(can't view it) unless the owner password is provided.  We currently deal with user permissions, the user provides the user password during upload, and vets-api removes the view only restriction before sending the PDF to evss.  This part is working.

Owner permission involve restrictions to **editing** the PDF document.  In vets-api, we don't. currently have a way to remove "owner" permissions and these files are failing when we send them to evss.  I believe the issue is that evss attempts to modify the PDFs before they send them downstream to VBMS.  I think they add some page headers to the PDF like Receive Date.  However, since the pdf have edit restrictions, the library evss uses, itext, won't allow the PDF to be opend for writing, and the pdf upload fails out with something like "[{"key"=>"EVSS_15006", "text"=>"We were unable to complete your upload because the uploaded file is corrupted and cannot be uploaded. Please verify that the file is valid. If you still have problems, call the VA at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, provide the following error code: EVSS_15006.", "severity"=>"ERROR"}]" visable in sidekiq.
Slack: https://dsva.slack.com/archives/C8R3JS8BU/p1643057449027300?thread_ts=1643053905.026900&cid=C8R3JS8BU

**Comment by michelpmcdonald** [comment] 2022-03-09 15:27
Also, another error we have is text files.  EVSS requires text files to be ascii(7 byte 127 characters avail, yea THAT ascii, from 1961) encoded files.

The core issue is that a text file does not contain it's encoding as part of the file, so it's hard to determine the encoding of the text file, and to properly re-encode the user's uploaded text files files as ascii to send to evss, the files current encoding must be known.

I'm trying to solve the text file encoding issue in this ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37947

**Comment by michelpmcdonald** [comment] 2022-03-09 15:29
I'm closing this ticket.  I answered the tickets question and provided the two current reoccurring upload issues

**Closed by michelpmcdonald** 2022-03-09 15:29 UTC
Labels: frontend, backend, vsa-claims-appeals, 526, Claim Status Tool, benefits-crew
