### ISSUE TITLE
Analytics Implementation for Booz Allen - VRRAP Application

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#23723] opened 2021-04-23 18:30 UTC
# Google Analytics Implementation for Veteran Rapid Retraining Assistance Program (VRRAP)

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics Implementation

- Who is this request for?

    - Amy Knox, knox_amy@bah.com
    - Darrell Neel, neel_darrell@bah.com
    
- What team/project is this work for?
    
    - Booz Allen / Education Applications Team
    
- Provide the Domain where Google Analytics needs to be implemented

    - Static landing page www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance
    - Application intro page www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s
    
    _Identify if PII is passed in URL or title tag_  **no PII passed in URL or Title Tag**
    
- Please provide any upcoming deadlines or important milestones
    
    - Anticipated launch NLT 4/30

- Typical Website Interactions to Track

    - This is a very short form: intro page, input page, review page, confirmation. 
    - No conditional pages. 
    - Applicants must be authenticated to enter the application. 
    
    - *Other User Interactions* 
    
**Banking Information** 
Tracks user behavior regarding direct deposit information
•	Updates to pre-fill direct deposit info
•	Selections of "I don't want to use direct deposit"
•	Opens of "What if I don't have a bank account" learn more

**Program Selection**
Provides insight into level of preparedness of applicants
•	Applicants indicate they have / have not selected a program 
Also interested in what's possible to track for the following free text fields in the "Program selection" area: 
•	School/training provider (Free-text field)
•	Program name (Free-text field)
•	States selected (Free-text field)

**Application Review Page**
Tracking user behavior regarding review and confirmation of form input
•	Opens of VRRAP application accordion on Review application page
•	Edits on Review application page
  
**Application Funnel**
Tracks user flow through application introduction, application completion, form review, and confirmation pages
•	Where applicants come from (Form finder, static content page, direct to application: previous page)
•	Application abandonment - location
•	Successful submissions
•	Time in funnel

- Sample Users when authentication is required  

    - [Test users / mvi-staging-users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

- Additional Comments

   [VRRAP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)

> Please leave the following blank

## Acceptance Criteria
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups
- [x] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [x] All appropriate issue tagging is completed
- [x] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by amyknox** [comment] 2021-05-04 20:41
@bsmartin-ep when you start to review this ticket, could you let me know what's possible to track for the following free text fields in the "Program selection" area:
• School/training provider 
• Program name  
• States selected

**Comment by bsmartin-ep** [comment] 2021-05-12 19:12
> @bsmartin-ep when you start to review this ticket, could you let me know what's possible to track for the following free text fields in the "Program selection" area:
• School/training provider
• Program name
• States selected

@amyknox -

We don't have any automatic tracking on any text inputs on va.gov due to PII/PHI concerns.  However, we have recently added component level analytics to the _TextArea_ and _TextInput_ controls in the component-library. 

If you're not using those, we can give you the event taxonomy (`int-text-input-blur`) for these and your developer can implement them.

Looking at the rest of this shortly.

**Comment by amyknox** [comment] 2021-05-12 19:21
@bsmartin-ep - when a text input is tracked, what does the data we get back look like? Will they be full names of Provider, Program, and state? Just info that the field was completed? Other??

**Comment by bsmartin-ep** [comment] 2021-05-13 02:29
@amyknox -

> @bsmartin-ep - when a text input is tracked, what does the data we get back look like? Will they be full names of Provider, Program, and state? Just info that the field was completed? Other??

Our current TextArea and TextInput event taxonomy captures the textbox value and label when the value is blurred.

I went through all of your items.  Most of the form interactions are not being tracked.  Your developers can either drop in the corresponding component form the component-library or (what I expect would be easier), push a custom event like this to the dataLayer....

```js
{
     event: 'int-radio-button-option-click',
     'radio-button-label': 'your label',
     'radio-button-optionLabel': 'your option label',
     'radio-button-required': false
}
```

I can map out the all the events if that's the route you want to take.

Some interactions are already tracked and I think we have the pageviews and events necessary for your funnel.

Let me know if you want to meet for a few minutes about this.

-------------------------------------
## Banking Information

Tracks user behavior regarding direct deposit information


<table>
  <tr>
   <td width="50%">Updates to pre-fill direct deposit info
   </td>
   <td>Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
  <tr>
   <td>Selections of "I don't want to use direct deposit"
   </td>
   <td width="50%">Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
  <tr>
   <td>Opens of "What if I don't have a bank account" learn more
   </td>
   <td>Tracked under event actions (<a href="https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Additional%20Info%20-%20.*%20-%20What%20if%20I%20don%5Cu2019t%20have%20a%20bank%20account%3F%22,0%5D%5D/ ">link to GA report</a>): 

<pre>
Additional Info - Expand - What if I don’t have a bank account? 
Additional Info - Collapse - What if I don’t have a bank account?
</pre>
   </td>
  </tr>
</table>



## Program Selection

Provides insight into level of preparedness of applicants


<table>
  <tr>
   <td width="50%">Applicants indicate they have / have not selected a program
   </td>
   <td>Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
</table>


Also interested in what's possible to track for the following free text fields in the "Program selection" area:


<table>
  <tr>
   <td>School/training provider (Free-text field)
   </td>
   <td>Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
  <tr>
   <td width="50%">Program name (Free-text field)
   </td>
   <td>Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
  <tr>
   <td>States selected (Free-text field)
   </td>
   <td>Not currently tracked.  Developers would either need to use a  component or add a custom event.
   </td>
  </tr>
</table>



## Application Review Page

Tracking user behavior regarding review and confirmation of form input


<table>
  <tr>
   <td width="50%">Opens of VRRAP application accordion on Review application page
   </td>
   <td>Not currently tracked.  Developers would either need to use &lt;va-accordion> web component or add custom event.
   </td>
  </tr>
  <tr>
   <td>Edits on Review application page
   </td>
   <td>I'm not seeing tracking on any form components, the edit button, the update button, or a change in URL.
   </td>
  </tr>
</table>



## Application Funnel

Tracks user flow through application introduction, application completion, form review, and confirmation pages


<table>
  <tr>
   <td width="50%">Where applicants come from (Form finder, static content page, direct to application: previous page)
   </td>
   <td>If you just want the previous page of the intro, you can <a href="https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&_r.drilldown=analytics.pagePath:www.va.gov~2Feducation~2Fother-va-education-benefits~2Fveteran-rapid-retraining-assistance~2F/">pull that here</a>.  Source / medium <a href="https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.sourceMedium&_r.drilldown=analytics.pagePath:www.va.gov~2Feducation~2Fother-va-education-benefits~2Fveteran-rapid-retraining-assistance~2F/">may also be helpful</a>. If you are looking for deeper path analysis, we can create a segment and use it in a Behavior flow.
   </td>
  </tr>
  <tr>
   <td width="50%">Application abandonment - location
   </td>
   <td><h3>Is this our funnel?</h3>
<br>
<ol>

<li><a href="https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/</a>

<li><a href="http://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/</a>

<li><a href="http://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply/</a>

<li><a href="http://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/review-and-submit/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/review-and-submit/</a> 

<li>Event Label:  edu-1990s--submission-successful

<li><a href="http://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/confirmation/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/confirmation/</a> 
</li>
</ol>
   </td>
  </tr>
  <tr>
   <td width="50%">Successful submissions
   </td>
   <td width="50%">Event Label:  edu-1990s--submission-successful 
 
(<a href="https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last7days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:edu-1990s--submission-successful/ ">Link to GA report</a>)
   </td>
  </tr>
  <tr>
   <td width="50%">Time in funnel
   </td>
   <td>This would need to be done in BigQuery.  Would you want to DIFF these two hits?
<ol>

<li><a href="www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/">www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/</a>

<li>Event Label:  edu-1990s--submission-successful
</li>
</ol>
   </td>
  </tr>
</table>

**Comment by amyknox** [comment] 2021-05-17 21:54
@dneel-bah & @desireeturner - Pls review Brian's comments then let's discuss how to best address and prioritize?

**Comment by amyknox** [comment] 2021-06-03 15:45
@bsmartin-ep 

We'll take you up on your offer to map out the all the events. Can you give an ETA for delivery of that info?

Thanks!

**Comment by joanneesteban** [comment] 2021-06-09 18:14
@amyknox - @bsmartin-ep will follow up with you today!

**Comment by bsmartin-ep** [comment] 2021-06-11 03:13
@amyknox -

Your developer can find overall [design documentation here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md) if that helps.

Here are the events I would send in for these various interactions.  I'll be out next week, but let @laurensimpson14 know if you have any questions.

<table>
<tr>
    <th>Interactions</th>
    <th>Data Layer</th>
    <th>Notes</th>
</tr>
<tr><td>
Updates to pre-fill direct deposit info</td><td> 
<pre lang="js">
{
 event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Save',
'button-background-color': '#0071BB',
}
</pre></td><td>I interpreted "Updates to pre-fill direct deposit info" as to mean the "Save" button click.  Let me know if that is incorrect.</td>
</tr>
<tr>
<td>Selections of "I don't want to use direct deposit"</td>
<td><pre lang="js">{
event: 'int-checkbox-option-click',
'checkbox-label': 'I don’t want to use direct deposit',
}</pre>

</tr>

<tr>
    <td>Applicants indicate they have / have not selected a program	</td>
<td><pre lang="js">{
event: 'int-radio-button-option-click',
'radio-button-label': "Do you know which program 
you'd like to enroll in?",
'radio-button-optionLabel': 'Yes' or 'No',
'radio-button-required': true
}</pre>

</tr>

<tr>
    <td>School/training provider (Free-text field)	</td>
<td><pre lang="js">{
event: 'int-text-input-blur',
'text-input-label': "What's the name of the school 
or training provider?",
'text-input-value': {{{value they entered}}}
}</pre></td><td>Note we will have <em>(not set)</em> in the Event Action for input value if you choose to withhold that for privacy reasons.</td>

</tr>

<tr>
    <td>Program name (Free-text field)		</td>
<td><pre lang="js">{
event: 'int-text-input-blur',
'text-input-label': "What's the name of the program?",
'text-input-value': {{{value they entered}}}
}</pre></td><td>Note we will have <em>(not set)</em> in the Event Action for input value if you choose to withhold that for privacy reasons.</td>

</tr>

<tr>
    <td>States selected (Free-text field)		</td>
<td><pre lang="js">{
event: 'int-text-input-blur',
'text-input-label': "Which state is the program in?,
'text-input-value': {{{value they entered}}}
}</pre></td><td>Note we will have <em>(not set)</em> in the Event Action for input value if you choose to withhold that for privacy reasons.</td>

</tr>

<tr>
<td>Opens of VRRAP application accordion on Review application page	</td>
<td><pre lang="js">{
event: 'int-accordion-expand' OR 'int-accordion-collapse'
'accordion-header' 'VRRAP application'
}</pre>

</tr>

<tr>
<td>Edits on Review application page</td>
<td><pre lang="js">{
event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Edit',
'button-background-color': 'transparent',
}</pre>

...and...

<pre lang="js">{
event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Update page',
'button-background-color': '#0071BB',
}</pre>

</td>


<td>To me, it makes sense to track both the Edit and Update page buttons.</td>
</tr>
</tr>
</table>

**Comment by amyknox** [comment] 2021-06-11 14:10
@bsmartin-ep  Thanks for the info.  2 questions on the funnel to get this moving on our end. 

1. The funnel you outlined is accurate.  Don't know if this impacts tracking the funnel but... all applicants need to be logged-in and cannot get to www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply/ without authenticating.  

2. RE: Time in funnel / Would you want to DIFF these two hits?
> www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/
> Event Label: edu-1990s--submission-successful

I'm not sure what you mean by that.  Could you explain?

**Comment by bsmartin-ep** [comment] 2021-06-11 15:54
@amyknox -

No problem here, but if you wanted to track the other path - when someone gets to the introduction page and DOESN'T authenticate - we may have to make a separate funnel for that.

I went ahead and put your steps in to a quick GA analysis funnel - "VRRAP Application":

https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361

You will probably want to duplicate it from the menu (three dots on the right) so you can add your extra dimensions _etc._  Remember to share it from that same menu if you want other people to be able to access it.

----------

> I'm not sure what you mean by that. Could you explain?

GA doesn't give us a clean way to determine the AVG time between specific events or pages.  We usually have to write a BigQuery query for that.  My question is how you define the start and end of the funnel.  Are we looking for the AVG time between a page view of...

`www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/`

...and a event hit of...

`edu-1990s--submission-successful`

Conversely, we can also directly look at the AVG `time on page` for each step in the funnel, though that would include people who didn't finish as well.

**Comment by amyknox** [comment] 2021-06-11 16:48
@bsmartin-ep 

**Authentication:**  

I think we're on the same page.  I just want to be sure the funnel doesn't break if applicants go` intro > [authenticate] > apply > `

**Time in Funnel:**  

We **are** looking for the AVG time between a page view of...

www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction/

...and a event hit of...

edu-1990s--submission-successful


We can also track average time on page but I think we can just do that natively looking at time on page for www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply/

**Comment by laurensimpson14** [comment] 2021-06-16 14:15
@amyknox Brian is out this week, but I can confirm that the funnel won't break if applicants go to `intro > [authenticate] > apply >`.

**Comment by sonntag-adam** [comment] 2021-06-21 16:12
[#25963](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25963) is in staging.

**Comment by laurensimpson14** [comment] 2021-06-23 15:07
Thank you @sonntag-adam! @amyknox Below are my notes from QA-ing everything that you and Brian discussed above. It is all tracking correctly! Please let me know if there are any items that I've missed. 

| Interaction | Screenshot | Status |
| :------- | :-------: | :-------:|
|Updates to pre-fill direct deposit info| ![image](https://user-images.githubusercontent.com/80417436/123117808-101f8b00-d410-11eb-97cd-deb76d207c19.png) | 🟢 Tracking Correctly|
|Selections of "I don't want to use direct deposit"|![image](https://user-images.githubusercontent.com/80417436/123119377-7953ce00-d411-11eb-9962-b60dd551800f.png)| 🟢 Tracking Correctly|
|Applicants indicate they have / have not selected a program| ![image](https://user-images.githubusercontent.com/80417436/123119469-912b5200-d411-11eb-80e0-ce5a91d2be9a.png)| 🟢 Tracking Correctly|
|School/training provider (Free-text field)|![image](https://user-images.githubusercontent.com/80417436/123119590-aacc9980-d411-11eb-99f5-2f27fdeeee5f.png)| 🟢 Tracking Correctly|
|Program name (Free-text field)|![image](https://user-images.githubusercontent.com/80417436/123119683-bddf6980-d411-11eb-8b5e-ebf3e8c35c99.png)| 🟢 Tracking Correctly|
|States selected (Free-text field)|![image](https://user-images.githubusercontent.com/80417436/123119768-cfc10c80-d411-11eb-9106-2c4ba4b8a5e0.png)| 🟢 Tracking Correctly|
|Opens of VRRAP application accordion on Review application page|![image](https://user-images.githubusercontent.com/80417436/123119902-e6fffa00-d411-11eb-9ee4-2ac899d92ad6.png)![image](https://user-images.githubusercontent.com/80417436/123119947-f2532580-d411-11eb-99a1-8b1236567fea.png)| 🟢 Tracking Correctly|
|Edits on Review application page - Edit| ![image](https://user-images.githubusercontent.com/80417436/123120207-1f073d00-d412-11eb-91f2-82759bec2b66.png)| 🟢 Tracking Correctly|
|Edits on Review application page - Update| ![image](https://user-images.githubusercontent.com/80417436/123120268-2cbcc280-d412-11eb-8300-77e33f3f3b75.png)| 🟢 Tracking Correctly|
|Successful submissions| ![image](https://user-images.githubusercontent.com/80417436/123121141-eb78e280-d412-11eb-9c73-5481a7b3f5e2.png)| 🟢 Tracking Correctly|

**Comment by amyknox** [comment] 2021-06-25 16:09
@laurensimpson14 - will there be a single location within GA that we could direct stakeholders to so they can review the customizations for VRRAP analytics?

**Comment by bsmartin-ep** [comment] 2021-06-25 21:23
@amyknox -

All of our events (and pageviews as well) occur on the same URLs, so that [makes it easy to query](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22BW%22,%22www.va.gov~2Feducation~2Fother-va-education-benefits~2Fveteran-rapid-retraining-assistance%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=50).

Are there specific interactions or events you want to highlight?

**Comment by joanneesteban** [comment] 2021-07-14 17:31
Hi @amyknox ! Do you need anything else from the Analytics team, or are you okay if we close this out? Thanks!

**Comment by amyknox** [comment] 2021-07-14 20:32
@joanneesteban Close. This. Ticket. 

:)

**Comment by joanneesteban** [comment] 2021-07-14 20:41
@amyknox :success-kid:

**Closed by joanneesteban** 2021-07-14 20:41 UTC
Labels: analytics-insights, analytics-request, bah-vrrap, collab-cycle-review, collaboration-cycle, gtm
