### ISSUE TITLE
Investigate InProgressForm expires_at discrepency.

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#71885] opened 2023-12-13 18:14 UTC
All InProgressForms have `created_at`, `updated_at` and `expires_at` fields. When a given form is saved, `updated_at` is set to today and `expires_at` is set to 2 months from today. When the expires_at date arrives the form is deleted. In this way, a given form's `updated_at` and `expires_at` values should never be more than 2 months apart. 
We have discovered a possible discrepancy, in which very long lived forms seem to have very old `updated_at` values while still having `expires_at` values in the future. 

This ticket exists to determine what logic, frontend or otherwise could be updating `expires_at` without also updating `updated_at`.

- Does this discrepancy exist outside of form 5655?
- Are there ActiveRecord calls that can trigger the `before_save` callback without updating `updated_at`?
- Does this discrepancy have any bearing on the age of our long lived forms in the first place?

**Comment by HeatherRienks** [comment] 2024-03-06 18:47
Dupe of another ticket - work has been completed, per @kjsuarez

**Closed by HeatherRienks** 2024-03-06 18:47 UTC
Labels: backend, vsa-debt, needs-refinement
