### ISSUE TITLE
Explore and revisit Visual Regression Testing to aid in modifications to CMS templates and style

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#18869] opened 2021-01-22 17:48 UTC
Problem statement: when working with old style that has affects across layers of the website, how can we ensure our intended change doesn't have impacts.  i.e. visual regression test once we have some development bandwidth.

**Comment by kelsonic** [comment] 2021-07-08 16:43
Would the idea here be to add e2e tests for at least 1 instance per template? CC @brianalloyd

**Comment by kelsonic** [comment] 2021-07-08 16:59
We should probably break up this ticket's AC into the exact template files we want to create tests for, but I think the [`/layouts`](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts) directory would be a great place to start! 🙂

**Comment by Rleahy22** [comment] 2021-08-05 19:30
A few thoughts while looking into this:

1. I really like [Cypress Image Snapshot](https://github.com/jaredpalmer/cypress-image-snapshot) for visual regression testing as it works well and we already use Cypress. I've managed to get it working locally and had it catch changes made to the templates.
2. For my first pass I tested snapshots against actual pages in content-build, and feel that is probably not the direction we would want to go for a couple reasons. 1. It introduces too much flakiness, because the content can change between actual code deploys. 2. I believe the philosophy of testing should be to test what you can control. By pointing at pages that render CMS content we test changes to the CMS which we do not control. Which leads to #3.
3. I feel the best strategy is to add functionality to render the templates in https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts using static fixtures that we control. This allows us to test that our templates render consistently and visual regression tests will only fail when we make changes to templates or styles in `content-build`, `vets-website`, or `veteran-facing-services-tools`. 

For me the big open questions are: Do we want to move forward with Cypress Image Snapshot? and more important, would we be amenable to adding routes to dev/staging that serve the output of the templates in `src/site/layouts` using static fixtures. That would allow us to run snapshot testing against a live environment in CI by doing `cy.visit('https://staging.va.gov/templates?layout=basic_landing_page')` for example. As an added bonus this type of layout rendering makes local development much easier as it eliminates the need for socks proxy to test changes and pages can be quickly rendered as needed at runtime instead of waiting for the entire 15 minute build. (I've been using this setup locally for about a month now and it is a game changer)

See POC with lots of fixtures on the `cypress` branch here: https://github.com/department-of-veterans-affairs/content-build/compare/cypress?expand=1

Thoughts @kelsonic (and whoever else I should include)?

**Comment by brianalloyd** [comment] 2021-10-01 16:08
This is happening naturally as we build new liquid templates.  Closing based on the fact this is happening already as part of our workflows when building elements/templates.

**Closed by brianalloyd** 2021-10-01 16:08 UTC
Labels: vsa-public-websites, vsa, needs-grooming, unplanned-work
