### ISSUE TITLE
Datadog Metric Source Configuration Info for Vets-ApI, Sidekiq, Forward Proxy, Reverse Proxy

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41663] opened 2022-05-19 17:32 UTC
## Who is the devops resource on your team?
@zachclarity 

@github-name
@zachclarity 

## Description

We need a list of all the configuration files and info related to metrics values in Datadog.

Demian Ginther created some of them and we are unsure who owns and configures them now.

## Background/context 
We need to know and document all monitors and the metrics associated with how they are configured and if they provide enough details to help with incident root or related cause analysis.

## Technical notes
We need to know what is configured by Terraform, Ansible or manually configured.
---
## Tasks
- [ ] Identify and document the details for all the Datadog configuration files/processes for metrics related to vets-api, sidekiq, puma, and proxies.

## Acceptance Criteria 
- [ ] A github files or Conflunce document with a list and links to related configuration files in devops repo.

**Comment by jbritt1** [comment] 2022-06-22 15:10
@zachclarity is this a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/41738? If so, can this be closed?

**Comment by jbritt1** [comment] 2022-07-13 19:26
@zachclarity

**Comment by jbritt1** [comment] 2022-07-13 19:33
Closing as a duplicate, feel free to reopen if needed.

**Closed by jbritt1** 2022-07-13 19:33 UTC
Labels: operations, devops, needs-grooming, Awaiting Feedback
