### ISSUE TITLE
FE | My VA | Make H4 in benefit cards instead a P to make more semantically accurate

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#57388] opened 2023-04-25 19:55 UTC
## Issue Description
Feedback from Platform following collab cycle session: Instead of using H4 in benefit card (which doesn't really work semantically), make this instead a p (paragraph) and associate it with preceding H3.

See exact wording from Platform here: 

>Using test user 80, you get this benefit payment card:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2">
      +$3,057.13
   </h3>
   <h4 class="vads-u-margin-top--0">
      Compensation &amp; Pension - Recurring
   </h4>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

### Platform Recommendation
>My best suggestion would be to make the `h4` a `p` paragraph with styling to make it look like a heading, and then using `aria-describedby` to associate it with the `h3`. That would look something like this:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2" aria-describedby="some-unique-id">
      +$3,057.13
   </h3>
   <p class="..." id="some-unique-id">
      Compensation &amp; Pension - Recurring
   </p>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

>Screen readers will announce the `h3` and the line beneath it together, providing full context while still having a heading structure that models the content.

## Related tickets
- [49264](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49264)
- [54878](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54878)

## Tasks
- [ ] Change h4 to p with styling to keep visual design the same
- [ ] Use aria described by to associate with h3

**Comment by ajakabcin** [comment] 2023-04-26 13:57
Closing - accidental duplicate of #57393

**Closed by ajakabcin** 2023-04-26 13:57 UTC
Labels: frontend, my-va-dashboard, authenticated-experience
