### ISSUE TITLE
User Survey Request for the VA.gov Profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#32540] opened 2021-11-05 19:28 UTC
# Request the Feedback Survey

**Moving this convo from a DM with Jason to GitHub for easier tracking**

## Description

Prior to moving from Foresee to Medallia, our team had a Foresee feedback survey on the VA.gov profile. However, the survey is no longer showing in our profile. **The profile does not have one URL -- www.va.gov/profile redirects to www.va.gov/profile/personal-information, so please do not put a survey on www.va.gov/profile. No one will see it.**

Can you look at why the Feedback survey is not showing on the following pages?

https://www.va.gov/profile/personal-information
https://www.va.gov/profile/military-information
https://www.va.gov/profile/direct-deposit
https://www.va.gov/profile/account-security
https://www.va.gov/profile/connected-applications

If you're able to fix this issue, we'll also need the Medallia survey added to the new page of the profile: https://www.va.gov/profile/notifications

### Launch Date

The profile redesign launched in September 2020, so it has been live for a while.

### Staging URLs

https://staging.va.gov/profile/personal-information
https://staging.va.gov/profile/military-information
https://staging.va.gov/profile/notifications
https://staging.va.gov/profile/direct-deposit
https://staging.va.gov/profile/account-security
https://staging.va.gov/profile/connected-applications

### Production URLs

https://www.va.gov/profile/personal-information
https://www.va.gov/profile/military-information
https://www.va.gov/profile/notifications
https://www.va.gov/profile/direct-deposit
https://www.va.gov/profile/account-security
https://www.va.gov/profile/connected-applications

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by Samara-Strauss** [comment] 2021-11-05 19:30
@MarciMcGuireGCIO just pulling you in for awareness. It looks like the user feedback survey is not working in our profile right now, likely due to something going wrong during the move from Foresee to Medallia.

**Comment by MarciMcGuireGCIO** [comment] 2021-11-05 19:30
Thank you @Samara-Strauss!

**Comment by jwoodman5** [comment] 2021-11-05 19:36
I checked our records with the Medallia folks and confirmed the Medallia Feedback survey was added to va.gov/profile/ on May 7th. The way it works is it should show for that directory and all sub-directories/pages. That is how they prefer to implement and how it has work for other directories, so all sub-directories/pages are automatically included. However, I will consider the redirect(s) in place here while troubleshooting why it is not showing now.

**Comment by jwoodman5** [comment] 2021-11-06 01:23
Update: I reached out to our Medallia team to help troubleshoot. I am seeing the `Feedback` button on `va.gov/profile/` as shown below. This is the URL (directory) we had listed in ForeSee. However, we are _not_ seeing the `Feedback`button on any of the sub-pages here (it should have automatically propagated):

https://www.va.gov/profile/personal-information
https://www.va.gov/profile/military-information
https://www.va.gov/profile/direct-deposit
https://www.va.gov/profile/account-security
https://www.va.gov/profile/connected-applications

No answers yet, so we will be diving in further on Monday and will update was warranted.

![image](https://user-images.githubusercontent.com/45946766/140593077-94acb72c-c231-40a5-844f-e076d5bfddcb.png)

**Comment by Samara-Strauss** [comment] 2021-11-08 15:25
Thanks for letting us know! Keep us posted on what you find.

**Comment by jwoodman5** [comment] 2021-11-09 01:00
@Samara-Strauss @MarciMcGuireGCIO I spent time with our Medallia technical expert today trying to figure this out and here is what we ended up with.

- The Medallia Feedback Survey has only been live on `www.va.gov/?next=%2Fprofile` (no other profile pages)
- This is because when we added the Medallia Feedback Survey for `www.va.gov/profile/` back in May there was a redirect in place, which landed users on `www.va.gov/?next=%2Fprofile` instead of `www.va.gov/profile`. The former URL is shown in the screenshot from my previous comment. 
- Because of that redirect, they had to add the survey for that URL (`www.va.gov/?next=%2Fprofile`) in order for the Feedback button to show. 
- This prevented the button/survey from propagating to other va.gov/profile/... URLs as they don't match the URL path/directory
- We did, however, successfully add the survey to all URLs listed in this ticket today
- While I did test and all seems good, I do encourage you to do your own testing as well. I am not terribly familiar with the logged-in experience and can't access some of the URLs due to my own identity verification. 

I realize this is not an ideal situation, but I am happy to help however I can and answer any questions or concerns you may have. Thanks.

**Comment by Samara-Strauss** [comment] 2021-11-09 15:07
@jwoodman5 I am still *not* seeing the survey in staging or production. If you need to get into staging for testing, you can use staging user 36. Let me know if you need the link to the staging user information.

**Comment by jwoodman5** [comment] 2021-11-09 17:27
@Samara-Strauss Can you please try a hard refresh? I had to do the same when testing. Hopefully that does the trick for you. Thanks.

**Comment by Samara-Strauss** [comment] 2021-11-09 19:47
@jwoodman5 ok, I am seeing it after I refresh, but I'm worried that people won't see the survey without refreshing. I tried it in a couple different browsers, and I didn't see the survey when I logged in and went to profile unless I did the refresh. I assume most people won't refresh when they go to a page and will not see the survey.

**Comment by jwoodman5** [comment] 2021-11-09 22:02
@Samara-Strauss I understand what you're saying and will see if there is anything we can do about that, and let you know.

**Comment by jwoodman5** [comment] 2021-11-11 01:35
@Samara-Strauss Here is what I got from the Medallia folks: "Company laptops (gov or non-gov) usually have caching locked,.... Ideally (on personal laptops) you don't need to clear cache, the surveys will show upon loading anytime." 

I realize that may not totally put you at ease, but does line up with what I have experienced with cache clearing and new features in the past. If you want to brainstorm ways to supplement this, I'm happy to chat more. Just let me know.

**Comment by Samara-Strauss** [comment] 2021-11-15 14:54
> @paul and @Samara (She/Her). Sorry to be late to this conversation! If I’m understanding the question correctly, I think a Veteran CAN see information about an upcoming hearing on VA.gov. It’s  on the Check Your Claims and Appeals page. Here’s a screenshot from Staging, with an upcoming hearing listed. (URL: https://staging.va.gov/track-claims/appeals/2221530/status)

I checked on my personal laptop and am still not seeing the survey without a hard refresh. I don't use my personal laptop to sign in to VA.gov, so I don't think this is a caching issue.

Question -- are we seeing responses come in for the survey? If not, that might be an indicator that people aren't seeing it.

**Comment by jwoodman5** [comment] 2021-11-15 18:55
@Samara-Strauss Thanks for the additional feedback. That is frustrating for sure. I will continue digging and check to see if we have gotten responses yet.

**Comment by jwoodman5** [comment] 2021-11-16 02:17
@Samara-Strauss Since pushing the `Feedback` survey live, we have received 5 responses. I don't know how much traffic the `/profile/...` pages get, but other pages we have the survey on will get anywhere from a handful up to maybe 50 in a 30 day time frame. We implemented the survey the same way for other folks, so I am not concerned users are seeing the survey. However, if you are still concerned, I am happy to chat more about it.

**Comment by Samara-Strauss** [comment] 2021-11-16 15:16
@jwoodman5 we get thousands of profile updates in a week, so 5 responses seems low. But, I don't know how many we were getting before. Can you check to see what the results were prior to migrating to Medallia? I don't know where to access our old data.

**Comment by jwoodman5** [comment] 2021-11-16 16:40
@Samara-Strauss That is helpful to know and I will check with ForeSee.

**Comment by jwoodman5** [comment] 2021-11-17 22:16
@Samara-Strauss I have been working on this and was able to pull data from ForeSee. I am not resolved on where we are at or our technical options at the moment, so I am continuing to dig. Here are my current thoughts after reviewing data:

- 78 ForeSee `Feedback` survey responses from desktop in November 2020. (I highlight desktop, because Medallia is only serving on desktop at the moment due to a 508 issue on mobile we are actively working on).
- On track for <20 Meddallia Feeddback survey responses in a 30 day window
- Our research has indicated users are more likely to click on the Medallia button. (we should not be seeing fewer responses)
- I am confident the survey implementation is correct as we implemented in the same fashion as other surveys in which we are getting a significant amount of responses.
- I am unaware of anything we can do technically, but am continuing my conversation about this with the Medallia folks and will keep you updated.

**Comment by jwoodman5** [comment] 2021-11-20 04:45
@Samara-Strauss I heard back from the Medallia engineering team and they were unable to find anything incorrect or fixable about the survey implementation. In order to troubleshoot instances where the survey is not showing, we will need to have specific examples. 

I did not have have time to try and recreate this and I am out of office all of next week. I will have revisit this when I return. In the meantime, if you are aware of any users we could potentially screenshare with to troubhleshoot their inability to see the survey when visiting `/profile/...` pages, please let me know. Thank you.

**Comment by Samara-Strauss** [comment] 2021-11-22 14:58
@jwoodman5 This is happening for me on prod, so I am happy to hop on a call with folks. Let's regroup when you're back. Happy Thanksgiving!

**Comment by jwoodman5** [comment] 2022-02-09 18:37
@Samara-Strauss Thanks for raising this back up. We are releasing the new Feedback button location (at the bottom of main) in about 30 minutes. I'd like to wait and see how that propagates before calling a meeting. It "should" propagate like any other release on VA.gov and I hope it solves your issue. If not, we will dive back in.

We have been getting responses, so it's really hard to say what could be going on for you and possibly others.

In the meantime, please feel free to check out the Medallia reporting dashboard [here](https://va-gov.domo.com/page/825663825). There is a `how-to use the dashboard` link in the upper right. The link I shared should be filtered to only `Profile` page responses, but if you need to apply filters, just select **VA Product** - `Authenticated Experience` > **Directory** - `Profile` near the top. Please let me know if you have questions.

@MarciMcGuireGCIO Please check out that dashboard as well if you haven't already. Also, I will pull the raw data with comments for you. What date range(s) would you like?

Thanks.

**Comment by MarciMcGuireGCIO** [comment] 2022-02-09 18:58
Thank you, @jwoodman5!   @Samara-Strauss is there  a particular date range you're interested in for comments/feedback?

**Comment by Samara-Strauss** [comment] 2022-02-09 19:20
> Thanks for raising this back up. We are releasing the new Feedback button location (at the bottom of main) in about 30 minutes. 

I literally just noticed this for the first time about an hour ago. It was working in the profile, so it will likely resolve the issue with the current button. Thanks!

> In the meantime, please feel free to check out the Medallia reporting dashboard [here](https://va-gov.domo.com/page/825663825). There is a how-to use the dashboard link in the upper right. The link I shared should be filtered to only Profile page responses, but if you need to apply filters, just select VA Product - Authenticated Experience > Directory - Profile near the top. Please let me know if you have questions.

Thanks! I have the report filtered to the profile, but I can't figure out a way to get an export of individual responses, just aggregate results. Since the overall score for the profile is quite low, I want to see if I can figure out what happened. We had some serious issues with the profile, specifically direct deposit, for a few days in December, so I'm curious if the low scores correspond to those issues. Is there a way to export individual scores?

**Comment by jwoodman5** [comment] 2022-02-09 20:45
@Samara-Strauss 

> I literally just noticed this for the first time about an hour ago. It was working in the profile, so it will likely resolve the issue with the current button. Thanks!

That's great to hear! I am cautiously (and hopefully) optimistic.

> ...but I can't figure out a way to get an export of individual responses,...

Unfortunately, due to PII concerns, we can display comments within DOMO. I will have to pull those manually and send them to you and @MarciMcGuireGCIO on the network. What date range(s) would you like me to pull in addition to December? Thanks.

**Comment by Samara-Strauss** [comment] 2022-02-09 21:35
> What date range(s) would you like me to pull in addition to December? 

The last six months for both My VA and Profile (all pages) would be great. Thank you!

**Comment by jwoodman5** [comment] 2022-02-19 01:38
Hi @Samara-Strauss and @MarciMcGuireGCIO Thank you, Samara for confirming you're seeing the survey more consistently now. I shared the data on the network with both of you. I included results for both the `Feedback` survey and the `A11 Satisfaction` (intercept) survey. I shared all data within the same excel doc, broken out by `MyVA` and `Profile` for each of the surveys. You should see 4 different tabs in the workbook.

Since the `A11 Satisfaction` survey did not launch until Mid-September, responses are from then through Feb. 17th. Since we did not get the `Feedback` survey implemented on these pages until late October/early November, responses for the `Feedback` survey are from then through Feb. 17th. 

I did see a notable uptick for `Feedback` survey responses since launching the new button location. Have fun exploring the data and let me know if you have any questions. Thanks.

**Closed by jwoodman5** 2022-02-19 01:38 UTC
Labels: VSP-contact-center, vsa-authenticated-exp, profile, medallia

**Comment by Samara-Strauss** [comment] 2022-02-22 16:51
Thank you!
