### ISSUE TITLE
Learning Center `field_related_links` refactoring

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#14189] opened 2020-09-29 19:30 UTC
## Issue Description

due to content model refactoring, `field_related_links` will be disabled and replaced with `field_related_information` ([2955](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2955)) and then removed ([3038](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3038)) from the following Learning Center content types :
* `checklist`
* `faq_multiple_q_a`
* `step_by_step`
* `media_list_images`
* `media_list_videos`
* `q_a` 

## Acceptance Criteria
- [ ] FE team replaces all LC query/template usages of `field_related_links` with `field_related_information`, once [2955](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2955) is deployed to production

**Comment by kelsonic** [comment] 2020-09-29 20:03
New field not deployed until tomorrow after deployment

**Comment by kelsonic** [comment] 2020-09-29 20:04
CC @MickinSahni @brianalloyd think we should pull this into sprint i think since it affects all the templates? 🙂

**Comment by brianalloyd** [comment] 2020-09-29 20:17
@kelsonic makes sense as it is related.  Do you have bandwidth to work this sprint?

**Comment by kelsonic** [comment] 2020-09-29 20:41
I think so! We can certainly give it a try! 🙂

**Comment by brianalloyd** [comment] 2020-09-29 20:48
Gotcha, sounds good. I've added to Sprint 31.  Appreciate the follow up and tracking on this @kelsonic

**Comment by kelsonic** [comment] 2020-09-29 20:58
Of course! 🙂

**Comment by kelsonic** [comment] 2020-10-05 16:13
It looks like `fieldRelatedInformation` is there now, but it's always empty (also tried with `q_a` entities). Perhaps we need to add related info data in Drupal?

CC @oksana-c @RLHecht 

![image](https://user-images.githubusercontent.com/12773166/95104647-4cc91c00-06f3-11eb-9e22-de022c399423.png)

**Comment by jenniferlee-dsva** [comment] 2020-10-05 16:54
@RLHecht There is a content ticket to add sample `Related information` content here: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14336 

This is a freeform field, so you can link to any page, internal or external to VA.gov. For FE @kelsonic 's needs, I think he just needs any data added here, so he can validate the FE template is working. 

**Requirements/description of this component in the LC:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#related-information-section

**Comment by jenniferlee-dsva** [comment] 2020-10-05 17:07
Also - is this a duplicate of ticket #14333 (or vice versa)?

**Comment by kelsonic** [comment] 2020-10-05 19:04
Thanks @RLHecht for adding the content! I can't see how related links were supposed to look beforehand, does this look correct?

![image](https://user-images.githubusercontent.com/12773166/95120761-434bae00-070b-11eb-8ed1-93195966f282.png)

**Comment by jenniferlee-dsva** [comment] 2020-10-29 14:40
Validating and closing.

**Closed by jenniferlee-dsva** 2020-10-29 14:40 UTC
Labels: frontend, unplanned-work, vsa, vsa-public-websites
