### ISSUE TITLE
Create smoke tests for E2E login flow

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#6177] opened 2020-02-25 21:55 UTC
Similar to [Oauth](https://github.com/department-of-veterans-affairs/va-api-smoketests), we want to have a series of smoke tests to test users of different Identity Providers and LOA levels in a more automated fashion. 

# ACs

- [ ] Successfully runs puppeteer tests that login in combinations of users between different services:
     - MHV, DSLogon, ID.me
     - LOA1, LOA3

**Comment by ambikaroos** [comment] 2020-03-02 19:08
Test cases: https://docs.google.com/spreadsheets/d/1V4iQ1qtpDh_w0_Lruo13d7U6xi-qpCktFEkOe3pHyeQ/edit#gid=0

**Comment by hinzed1127** [comment] 2020-07-15 17:00
Outbound smoke tests for ID.me and DSLogon cases are in this [repo](https://github.com/department-of-veterans-affairs/va.gov-sso-smoke-tests). I will continue to fill in inbound cases for those credential types.

MHV is very similar and doesn't require too much more code, but it requires access to MHV staging. There's a [conversation happening](https://dsva.slack.com/archives/C0S6H6BQU/p1594686162109800) with devops folks on the best option for automating this in CI, which would include the MHV access.

**Comment by AGarcia-Clarity** [comment] 2020-12-14 15:27
After reading [archived discussions](https://dsva.slack.com/archives/GLDNCMRSP/p1596665520067100) between Rian Fowler, Eugene Doan, and Chris Valarida about End-to-End testing in Staging environments it was determined that this is a bad idea because the staging environment connects to upstream/third-party services.

I reached out in the VSP FE Review Group to confirm was still the [case](https://dsva.slack.com/archives/GLDNCMRSP/p1607721434145500) and it was confirmed by Chris Valarida & Eugene Doan that this is still the case as they do not want SSO Smoketests to run as part of the staging CI/CD process.  I mentioned to Eugene that it's in a separate repo and ran manually on AWS CodeBuild and that I wasn't aware of how to resolve accessing the MHV staging URL from the Docker container on CodeBuild (that was the original blocker for me).  He mentioned that this will have to be part of a larger discussion.

**Comment by AGarcia-Clarity** [comment] 2021-07-19 19:47
Update
We will be closing this issue because the providers/technologies will be changing soon.  At the time of the ticket creation there was also no Testing team.

**Closed by AGarcia-Clarity** 2021-07-19 19:47 UTC
Labels: Identity, SSO-Login
