### ISSUE TITLE
Update VFS Team Orientation Documentation

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#121] opened 2019-05-29 21:24 UTC
## Story
As a VSP Platform Support team member, we need clear procedures for intaking new projects and a set of standards and expectations for new teams onboarding.

## Problem
We've learned from our early platform users that it's difficult to drive quality product decisions with teams that aren't managed by DSVA leadership [source](https://github.com/department-of-veterans-affairs/va.gov-team/pull/27/files#diff-6cf528a9aa486f23146abf1860c64291R40)

In response, we're looking to change the process of onboarding from using the handbook (which has procedures that we're going to deprecate) to using the `va.gov-vfs-teams` repo to be the starting place for new VFS teams.

## Goals
- Identify which information in the Handbook is still relevant
- Improve/iterate on the intake/onbaording documentation in the `va.gov-vfs-teams` treating it as the sole source for new teams working on Va.gov applications

## Tasks
- Create a set of intake criteria for incoming VFS teams
- Iterate on handbook onboarding documentation with learnings from past VFS teams
- Establish a plan for deprecating/shutting down the handbook

**Comment by shiragoodman** [comment] 2021-07-19 14:08
closing as this appears to be a duplicate of #13709 which is currently in progress

**Closed by shiragoodman** 2021-07-19 14:08 UTC
Labels: Epic, product support, vsp-product-support
