### ISSUE TITLE
10-7959a: Health insurance information

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86952] opened 2024-06-25 22:06 UTC
As a VA.gov user, I want to fill out the CHAMPVA claim form with health insurance information so that I can file a claim.

~~[Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=961-139667&t=Ko13IszQmJiM9ZRY-0)~~ -> Updated July 3rd: [Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1481-276887&t=LG8dR86iRSeFHJg4-11)

- Page elements:
  - breadcrumb 
  - header and subhead
  - copy
  - footer
- health insurance status 
  - if no, move to claims section
  - if yes, [list and loop](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md), see list and loop [figma](https://www.figma.com/design/OxzngjwHg4n0oNSGHkwJ5Z/DSC---WIP---Pattern---Multi-page-List-and-Loop?node-id=534-59955&t=DnywGZBbgdeXJ0zF-0) for reference
     - policy information
       - user is able to cancel adding insurance
     - insurance type
        - user is able to cancel adding insurance
        - if user selects last option - not listed, then display open text field
     - insurance review
        - max of 2 (see figma)
        - user can delete or edit
        - list types in order

Acceptance criteria:

- Given the user is on VA.gov and about to fill out the CHAMPVA claim form
- When the user gets to the health insurance info section
- Then the user can add their health insurance information before moving on to the claim section

**Comment by michaelclement** [comment] 2024-07-03 23:29
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30693)

@syd-hoeper There are a few more differences between the Figma and what the current list loop actually allows. Here's a screen recording of a quick run-through.
Some callouts:
- Had to add an intro page at the start of the list loop
- Can't insert beneficiary name into labels inside the list loop because (accessing data outside loop not supported currently)
- The label text above the "do you have another to add?" yes/no is an H5 tag. Changing it to a paragraph isn't currently supported.
- On the final review page for the form the data shows up as cards (showing the data in list view rather than card view isn't supported currently)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE95QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad69ab396f0db034036dccbe0f2379e6bfacde35/Screen%20Recording%202024-07-03%20at%2018.23.37.mov)

**Comment by michaelclement** [comment] 2024-07-05 17:54
@baltes @marywang2 @syd-hoeper This has been merged and should be visible on staging- thanks!

**Comment by marywang2** [comment] 2024-07-15 14:24
For the new intro page, can we make the url: insurance-intro (to differentiate from the true 'intro' page)?

**Comment by michaelclement** [comment] 2024-07-15 15:47
@marywang2 Yes, I can update that URL no problem. That yellow warning is a part of the new list loop pattern. I can hide it if we determine we really need to, but it is the standard behavior for when you hit the max on a loop.

**Comment by marywang2** [comment] 2024-07-15 15:53
@michaelclement I added 2 policies - shouldn't the error message display only if you add 3? @syd-hoeper

**Comment by syd-hoeper** [comment] 2024-07-15 16:06
Looks good to me! Thanks, Michael!

**Comment by michaelclement** [comment] 2024-07-15 16:12
@marywang2 the warning lets you know why you can't add another, so it shows up when you've added the max, so it's showing up as intended. It's just a warning, not an error

**Comment by syd-hoeper** [comment] 2024-07-15 16:50
Just checked staging and everything is working as expected @marywang2

**Closed** 2024-07-15 21:01 UTC
Labels: frontend, ivc-forms, 10-7959a
