### ISSUE TITLE
Salesforce-GIBFT Staging issues

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#19353] opened 2021-02-01 21:13 UTC
## Issue Description
On 1/29, a [request](https://dsva.slack.com/archives/CBU0KDSB1/p1611854550363900) to update some salesforce consumer keys was posted in #vfs-platform-support. In the past, Johnny Holton took care of these requests and some notes were left [here]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/14921). The request turned out to be more than just updating the keys, as salesforce renamed their staging env (called uat) to reg. Changes were made [here](https://github.com/department-of-veterans-affairs/devops/pull/8449#discussion_r567952388) and [here](https://github.com/department-of-veterans-affairs/vets-api/pull/5807) associated to the environment name change. 

On 2/1/2021, Ops and Be-Tools met with the Salesforce and tried to debug the issue. I was able to successfully make a post request in the rails console in the staging environment after the keys/settings were updated, but the Salesforce rep was running into a submission issue when testing in the UI.

**Note**: Jeremy created a branch and had the staging deploy point to the branch, so the keys may not be exactly correct until everything is deployed

After the Salesforce rep could not successfully submit, I was able to find this [Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/5210/?environment=staging&project=3&statsPeriod=14d) which basically is saying that the body being returned [does not have an access token](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/salesforce/service.rb#L37) 

Additional information in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19331

Debugging information
1. Open a rails console in a vets-api server instance 
2. service = Gibft::Service.new
3. body = service.send(:request, :post, '', service.oauth_params).body (this should return an access token)

There is an [in progress branch](https://github.com/department-of-veterans-affairs/vets-api/pull/5816) to catch the access token error before the Restforce client is instantiated. 

---

**Comment by LindseySaari** [comment] 2021-02-02 14:37
When I run the [get_client method](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/gibft/service.rb#L21) in the rails console in staging `client = Gibft::Service.new.get_client`, the Restforce client object that gets returned has a host of :host=>"login.salesforce.com". login is associated with the prod env and this should be test I believe (test.salesforce.com). Just something I noticed that might contribute to the invalid credentials/access token issues

**Comment by omgitsbillryan** [comment] 2021-02-03 21:30
We don't specify a `host` when instantiating the new Restforce instance and according to [the Restforce readme](https://github.com/restforce/restforce#sandbox-organizations):

> The default host is 'login.salesforce.com'

I can verify this in the console:
```
2.6.6 :001 > Restforce.new.options[:host]
 => "login.salesforce.com" 
 ```

The `Gibft::Service` suspiciously defines a `SALESFORCE_HOST` _class_ variable, but maybe the author meant to define that as an _ENV_ variable 🤷 ? Because if they did, `Resforce` would use that ENV['SALESFORCE_HOST'] as the default `host` for the `Restforce` instance, and it kind of looks like that was the intended purpose.

**Comment by alexpappasoddball** [comment] 2021-03-02 16:48
@LindseySaari Can you update this ticket with the current state and close it out as the issue is now complete?

**Closed** 2021-03-17 18:35 UTC
Labels: bug, tools-be
