### ISSUE TITLE
Disable issue tracker for non va.gov-team repos

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#40004] opened 2022-04-14 16:35 UTC
## AC
- Issue tracker disabled
- README should have link to an issue template

 - [ ] https://github.com/department-of-veterans-affairs/vets-website/
 - [ ] https://github.com/department-of-veterans-affairs/vets-api
 - [ ] https://github.com/department-of-veterans-affairs/vets-json-schema
 - [ ] https://github.com/department-of-veterans-affairs/content-build

**Comment by andreahewitt-odd** [comment] 2022-05-18 20:12
Duplicate of the repo guidance ticket because once that is implemented folks will know where to put in tickets for that repo

**Closed by andreahewitt-odd** 2022-05-18 20:12 UTC
Labels: platform-leads, engineering
