### ISSUE TITLE
Refactor covid19-vaccine E2E tests

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#67321] opened 2023-10-11 15:21 UTC
## Description
We want to remove any skipped test(s) in this file `src/applications/vaos/tests/e2e/flows/covid19-vaccine.cypress.spec.js` and update our covid19-vaccine e2e tests to match the covid19-vaccine flow in production.

---

## Acceptance Criteria
- [ ] No test is skipped
- [ ] Feature flags should be set to match production settings. All unused feature flag settings should be removed as well.
- [ ] covid19-vaccine e2e tests to match the covid19-vaccine flow in production.

## Definition of Done
- [ ] All acceptance criteria are met

---

**Comment by vbahinwillit** [comment] 2023-11-17 17:18
Duplicate of [68904](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68904)

**Closed by vbahinwillit** 2023-11-17 17:18 UTC
Labels: frontend, appointments
