### ISSUE TITLE
Remove Code to Prevent Lovell Appointment booking

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#78946] opened 2024-03-21 16:14 UTC
Code to prevent veterans registered at just the Lovell sites from scheduling & showing an Alert for veterans registered at Lovell prior to their Oracle Health cutover was added in [PR-28259](https://github.com/department-of-veterans-affairs/vets-website/pull/28259) behind Feature toggle, `va_online_scheduling_booking_exclusion` under Github issue [Scheduling flow at Lovell site - Part 2#77055](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/77055). The Lovell cutover to Oracle Health is complete.

Lovell appointment booking exclusion is no longer needed and the code should be removed from Vets website.

**Comment by ajmagdub** [comment] 2024-03-21 16:34
Closing duplicate of [#78780](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/78780)

Work will be done under #78780

**Closed** 2024-04-04 16:12 UTC
Labels: frontend, appointments
