### ISSUE TITLE
General Analytics Request for Campaign Landing Page (Public Websites)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#16749] opened 2020-12-01 20:07 UTC
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics.

- Who is this request for?

    - John Hashimoto @johnhashva (DEPO PO)
    - Brian Lloyd @brianalloyd (VSA PM)
    
_Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
   

- What team/project is this work for?
   - Public Websites.   
   - The [Product Outline is here.](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md)
   - The [Product Super Epic is here.](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4621)

_Provide the Domain where Google Analytics needs to be implemented_

URL/Domain has not yet been specified; and the URL for each Campaign Landing Page will be unique.  That said, we will build-out a CLP prototype for staging.va.gov by early January.

- Please provide any upcoming deadlines or important milestones

    - November-December 2020: CMS tooling development
    - December 2020: Prototype content build by Public Websites of a CLP (using archived content)
    - January 2021: Front end development of the CLP template components
    - January-February 2021: User Testing of the CLP (e.g. up to three VA business teams will build prototype CLPs to test the ease of use of CMS-based page builder and effectiveness of the front-end experience to accomplish their marketing/communication goals).
    - March 2021: MVP 1.0 of CLP is available for use by select VA stakeholders to launch production campaigns.

- Website Interactions to Track

    - *Usage: As marketing/communication SMEs, the VA stakeholders will want to know how well their CLP performs.  They will drive traffic to the page through various means: Targeted email, social media ads, events, even brochures/flyers.  Key metrics they will want to know for each unique CLP created:
      - Page Views
      - Clicks per Content Panel (e.g. watch a video, download a PDF, etc.)
      - Click through rate for on-page CTAs (calls to action) to external sites
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - TBD

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by brianalloyd** [comment] 2020-12-01 21:17
@joanneesteban we'll be submitting a KPI Dashboard request in-connection with this General Analytics request in the near future as soon as we finalize our OKR/KPIs in support.  This request is a little different then previous requests so let me know if you would like to link up (zoom) with @johnhashva and I to review the details based on the current Product Outline.  Thanks.

**Comment by joanneesteban** [comment] 2020-12-01 22:51
Thank you, @johnhashva !

**Comment by joanneesteban** [comment] 2020-12-09 17:00
@brianalloyd fysa we'll be keeping this in the backlog until we have capacity to take a look. Will keep you posted!

**Comment by jonwehausen** [comment] 2021-01-26 13:21
Hi @brianalloyd & @kelsonic 

Thanks for your patience on this request. 

I have taken a look at your [MURAL mockup here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1607363793772/b7f9e809d68ace9c8d75ab649a758ed7653c8461) and have proposed a draft data layer specification for tracking, and analytics & insights. 

### KPI Review
- KPIs refenced below, from [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md): 

> KPIs
> We will know the initial set of functionality is meeting the desired user and business outcomes when the CLP template is used by (or via the PW content team on behalf of) at least three business stakeholders -- and there are no requests for major changes. This would validate the following:
> 
> - the capabilities of the CLP template (the various content components) meet the minimum needs of the business stakeholders
> - the CMS functionality of the template builder is bug-free and user/author-friendly
> - the user permissions allow for guard-railing/governance by DEPO (the Public Websites Product leads)
> - the Campaign Landing Page supports the success metrics for traffic/reach as outlined by the business stakeholders
> 
> To measure the effectiveness of the CLP for campaign purposes, we will require the use of CTAs that would be prominently required and automatically tracked as a primary metric (e.g. whatever campaign X's success measure is, at least one required CTA button would be required that would automatically be tracked by analytics).
> 
> Every content component/panel in the template - whether it is the video panel or the downloadable resources panel - should be automatically tracked. Instrumenting this auto-tracking capability into the CMS front-end template will not only ensure the ability to track CLP performance but also will be used as a lever to govern the business users of the template.

- @kelsonic Can you tell me a bit more what auto-tracking through the CMS you're able to implement here? 
- @brianalloyd In order to understand who is using the CLP template in the CMS, we can ensure our tracking within the CMS is capturing the necessary CTA's / pages to do so. Can you direct me to where the template lives in the CMS today? 
- We also measure PDF downloads globally through GTM
- For campaign effectiveness metrics, please see the remaining sections below 
--------------------------------------------------

### Campaign Acquisition
- One piece to the puzzle here is understanding how you all are planning on driving visitors to the CLP's. 
- As well as ensuring we are deploying `utm` parameters in the proper touchpoints where users may be acquired (email, social media, print, etc) 
- Let us know if you all have a current taxonomy for acquisition or if need of us to propose one. 

--------------------------------------------------
### Video Tracking
- @kelsonic could you ensure the following `src` is loaded at page load, this will ensure our built-in out-of-box GTM video tracking can be utilized effectively
```html
<script src="https://www.youtube.com/iframe_api">
```
--------------------------------------------------
### Datalayer Specification
- Many of the items below are reflected in our recently updated and ongoing effort to standardize the data layer according to [VA.gov design system components](https://design.va.gov/components)
- I realize many of these pieces are coming from Drupal as well, so may not be aligned exactly with a design system component

Description / Component | Data Layer Specification | Dev Notes
------------ | ------------- | -------- |
Accordions - Expand/Collapse ![image](https://user-images.githubusercontent.com/48527022/105846104-b3778b80-5fa9-11eb-99a7-ee0b0fe197b7.png) | `'event': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'accordion-parent-label' //accordion parent label (**IF** there are two labels on the accordion, if only one label on accordion, populate this value with the accordion text and make 'accordion-child-label' undefined`<br>`'accordion-child-label': //dynamically populate with secondary label of the accordion`<br>`'accordion-section-label': //populate with the label of the section where the accordion is present` | • **IF** there are two labels on the accordion, if only one label on accordion, populate this value with the accordion text and make 'accordion-child-label' undefined <br> • We're making an adjustment from `nav` to `int` for the prefix of the event name, this is to help standardize our event meanings further across all components
Button CTAs ![image](https://user-images.githubusercontent.com/48527022/105848134-91333d00-5fac-11eb-815e-a55438a1afca.png) | `'event': 'cta-button-click' //consistently populate for ALL types of button clicks`<br>`'button-type' //'primary', 'secondary', 'default'`<br>`'button-click-label': //dynamically populate with text of button`<br>`'button-background-color': //dynamically populate with the background color of the button` | ⚠️ Please do not implement this portion yet, as it may begin to be captured from our effort [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14491)
Link clicks in "Events", "Stories" light blue background area | _Will provide when component confirmed_ | @kelsonic Can you confirm are these sections [featured content](https://design.va.gov/components/featured-content) or [alert boxes with background only](https://design.va.gov/components/alertboxes#background-color-only), thanks
Link clicks in gray area boxes | _Will provide when component confirmed_ | @kelsonic Same question here
PDF Downloads | _see notes_ | If most of the PDF links are contained within a design system component, we'll want to implement that spec here according to the question above for data consistency purposes, otherwise we have PDF downloads globally tracked through GTM
"VA Benefits" section links ![image](https://user-images.githubusercontent.com/48527022/105850137-54b51080-5faf-11eb-987e-149ae0a1c746.png) | _see notes_ | Let's confirm what this markup looks like before setting specification

**Comment by jonwehausen** [comment] 2021-01-26 13:21
@kelsonic Is there a staging link or a drupal preview I can take a look at currently?

**Comment by kelsonic** [comment] 2021-01-26 14:49
Not yet, but soon! 🙂 If you have socks, you could technically go to http://preview-prod.vfs.va.gov/preview?nodeId=15051 but it doesn't have styling yet

**Comment by brianalloyd** [comment] 2021-01-26 15:17
@jonwehausen Thanks for working up the details.  I'm tagging @kevwalsh on this ticket as he can assist us with any CMS related items required in support.  We're still in the FE build process and hope to have that wrapped up in the next few sprints.

**Comment by jonwehausen** [comment] 2021-02-03 17:08
## Note to self/team for scope

- With the various marketing touchpoints that will occur here, I feel it would be in our best interest to develop a campaign URL builder that teams can leverage to build their UTM links for marketing content self-service 
- We should also add as a piece of documentation with our conventions
- Do as an excel file rather than a google sheet?

**Comment by kelsonic** [comment] 2021-02-10 20:47
@brianalloyd can we bring this one into sprint?

**Comment by brianalloyd** [comment] 2021-02-10 20:52
@kelsonic ready for action.

**Comment by kelsonic** [comment] 2021-02-11 23:28
![image](https://user-images.githubusercontent.com/12773166/107712072-fe6df000-6c85-11eb-9b17-83e0ee92dea1.png)

Hey @jonwehausen sorry just saw your questions! So both of those are derived from completely custom html/css that is only used in the campaign landing page. The blue light background doesn't indicate importance or anything, it's just a design thing to make it pretty afaik 🙂

**Comment by kelsonic** [comment] 2021-02-11 23:30
@jonwehausen also if you want you can now see more or less the full markup here for CLP now! 🙂 http://preview-prod.vfs.va.gov/preview?nodeId=15068

**Comment by kelsonic** [comment] 2021-02-11 23:32
Not sure if you have time to update those other sections that were missing the `Data Layer Specification` parts tomorrow but I'll be working on this ticket tomorrow and it'd be very helpful if you could!

**Comment by jonwehausen** [comment] 2021-02-12 21:29
### Standard Event Listener for CLPs - Pivot from initial design 
- Since this page is primarily driven via drupal with little expectation of consistently correlating back to the design system, I'm proposing we create 1 standard click event listener that is generic enough to collect any link click on the page
- We will be deploying our global button event listener over the coming days that will capture the CTA clicks so nothing to implement on that front
- If you could still adjust the accordion expand/collapses to reflect the new `int` prefixed taxonomy we would certainly appreciate it
- Please see the taxonomy below to listen for all links on the page, and track them according to documented taxonomy, whatever variable is not available please populate with `undefined` 😄 

Thank you sir and please let me know any questions you may have


```javascript
'event': 'clp-link-click', //consistently populate for any link click
'clp-section-category': //dynamically populate according to the `<p>` tag text directly above main title i.e 'WHAT YOU CAN DO', and links in the hero section can populate with `'hero'`
'clp-section-title': //dynamically populate according to the section title, i.e "Where you can get your flu shot" 
'clp-section-index': //beginning with 1, and 1 being the first section with a category, and increment each section below by 1
'clp-total-sections': //populate with the number of total sections 
'clp-section-background-color': //dynamically populate with the background color hex code 
'clp-click-label': //dynamically populate according to the link text
'clp-faq-text': //if a link is contained within an accordion that is a faq, populate with the accordion text, otherwise undefined
'clp-event-name': //if a link is related to an event, populate with the name of the relevant event
```

**Comment by kelsonic** [comment] 2021-02-16 20:10
After discussing with @jonwehausen we've decided to omit `clp-section-index` and `clp-section-background-color` for now 🙂

**Comment by kelsonic** [comment] 2021-02-16 20:15
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16070

**Comment by brianalloyd** [comment] 2021-02-16 20:25
Thanks @kelsonic

**Comment by jonwehausen** [comment] 2021-02-16 23:40
@ianMcCullough-ob Would you mind taking care of the QA for this issue? 

Kelson's changes should be merged into staging over the next 24 hours; you can find the appropriate GTM container [here](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000454)

Feel free to QA the data layer and tagging separately or in-tandem, whichever you would prefer. 

### Items to QA
- [ ] Ensure each piece of metadata is separated by "~" within the Event Action and captured according to taxonomy below
    - The taxonomy is as follows "Campaign Landing Page ~ <section category> ~ <section title> ~ <click label>
- [ ] Ensure the links inside of accordions with questions populate the FAQ text to custom dimension index 77
- [ ] Ensure when a link is clicked within an "Event" section the `clp-event-name` is captured within the tag and the event name is pushed to custom dimension index 124
- [ ] Ensure accordions are appropriately tracked according to data layer outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16749#issuecomment-767536837)
- [ ] Ensure button CTAs are firing the data layer and tagging per our recent standardization `cta-button-click` event

Please don't hesitate to reach out with any questions you may have and we appreciate your assistance here.

**Comment by ianMcCullough-ob** [comment] 2021-02-18 13:50
Sure thing @jonwehausen I can take a look.

Not sure what URL I should be testing though.

**Comment by jonwehausen** [comment] 2021-02-18 15:50
Thanks @ianMcCullough-ob, my apologies -- You can use http://preview-prod.vfs.va.gov/preview?nodeId=15068 with SOCKS proxy enabled for the time being until a staging link becomes available. 

@johnhashva When you have a moment, would you be able to provide an update on a) when the first staging URL will be available & b) when the first CLP is planning on launching?

**Comment by johnhashva** [comment] 2021-02-18 17:18
@jonwehausen we may be able to put a fully produced beta CLP on staging in the next week if that is helpful for this -- as for a CLP production release -- our latest estimate is no sooner than late March.

**Comment by jonwehausen** [comment] 2021-02-24 15:41
Handing QA off to @bmcgrady-ep

**Comment by bmcgrady-ep** [comment] 2021-03-01 16:36
Hi @johnhashva or @brianalloyd - Just following up to see if a staging URL is available? Thank you!

**Comment by johnhashva** [comment] 2021-03-01 16:40
Hi @bmcgrady-ep -- yes, if you can access the CMS preview you can see a fully built CLP (for MISSION Act) here as an example:

**Comment by bmcgrady-ep** [comment] 2021-03-02 22:46
Hey @kelsonic, I am not seeing any CLP link clicks coming into the Data Layer. That said we see that you set the custom event listeners in the page source, but are not actually seeing the events fire in the Data Layer.

**Comment by kelsonic** [comment] 2021-03-03 02:32
Interesting, thanks for letting me know! I'll check this out first thing tomorrow 👀

**Comment by brianalloyd** [comment] 2021-03-03 16:04
Thanks @kelsonic

**Comment by kelsonic** [comment] 2021-03-04 17:56
Oh whoops, I see the issue

**Comment by kelsonic** [comment] 2021-03-04 18:20
Oh! I bet `recordEvent` isn't defined on the preview server! Checking now

**Comment by kelsonic** [comment] 2021-03-04 18:55
[I just tested it locally with GTM](https://tagassistant.google.com/#/!%23source=TAG_MANAGER&id=GTM-WFJWBD&gtm_auth=3nsmBjX8YS8-fwR0o3ntKg&gtm_preview=327) and the events are coming through, what URL were you testing exactly @bmcgrady-ep?

![image](https://user-images.githubusercontent.com/12773166/110014790-70af7e80-7ce0-11eb-9606-72fb9fff037a.png)

**Comment by bmcgrady-ep** [comment] 2021-03-05 19:36
Hi @kelsonic - Thanks for the update. [This](http://preview-prod.vfs.va.gov/preview?nodeId=16139) is the link that I am testing, but I believe I may need a different link as I am not seeing anything come into the Data Layer for it.

**Comment by kelsonic** [comment] 2021-03-08 14:46
hey @bmcgrady-ep that looks like the correct link! 🙂 I just tried it out with [GTM assistance](https://tagassistant.google.com/#/!%23source=TAG_MANAGER&id=GTM-WFJWBD&gtm_auth=3nsmBjX8YS8-fwR0o3ntKg&gtm_preview=327) and the clp events are indeed not coming through:

![image](https://user-images.githubusercontent.com/12773166/110335715-655e9a80-7fe1-11eb-9c43-5bc17c3b70b7.png)

I also tried it on staging (http://preview-staging.vfs.va.gov/preview?nodeId=16139&gtm_debug=x):

![image](https://user-images.githubusercontent.com/12773166/110336274-f2095880-7fe1-11eb-8bef-6305885f6860.png)

Very odd 🤔 I'll investigate today, I wonder if this has to do with the preview server...

**Comment by bmcgrady-ep** [comment] 2021-03-08 17:47
Thanks for looking into this @kelsonic! Also tagging @bsmartin-ep to look into this as well.

**Comment by brianalloyd** [comment] 2021-03-17 15:25
@kelsonic @bmcgrady-ep @bsmartin-ep just checking back into this ticket as we're wrapping up CLP build actions in preparations for launch.  We're we able to establish the necessary links in support of tracking?  What else is needed from our team in support and we'll follow up soonest in support.  CC @johnhashva

**Comment by bsmartin-ep** [comment] 2021-03-17 15:33
We are verifying if the CTA button events are firing, correct @brianalloyd @kelsonic ?

**Comment by johnhashva** [comment] 2021-03-17 16:30
@kelsonic and @brianalloyd  -- let's discuss in grooming this week the idea/merit/risk of putting this CLP test build (Mission Act) on staging with a banner that says "this is a test".  I know we need it there to test some things, so time to make a call.

**Comment by brianalloyd** [comment] 2021-03-17 16:45
Great idea @johnhashva I've got it queued up on our grooming breakdown for Friday.

**Comment by kelsonic** [comment] 2021-04-01 15:30
Hey folks! Pretty soon here CLP pages will be on staging (behind a simple auth check), I'll post here when they are on staging! 🙂 Related thread: https://dsva.slack.com/archives/C01DS1XDEQ0/p1617200171010300

**Comment by brianalloyd** [comment] 2021-04-01 18:43
Campaign is now on staging at: https://staging.va.gov/campaign-mission-act/ Code: clptest123 @bsmartin-ep and @jonwehausen hoping that we can use this opportunity to test the Data Layer and validate analytics tracking while in 'staging state'.  Let me know if you have any questions and thanks or the support.

**Comment by brianalloyd** [comment] 2021-04-12 20:57
@jonwehausen would it possible to link up this week after you've had a change to validate CTA buttons are firing and data is being tracked appropriately.  I would like to build a rough GA dashboard for this data that we might be able to share with stakeholders forward and would like to just talk through options with you.  LMK, thanks.

**Comment by jonwehausen** [comment] 2021-04-16 18:53
@bsmartin-ep Could you prioritize this QA ASAP when you have capacity. 

As for your request on a GA dashboard @brianalloyd --  in correlation with our initiative to revamp our DOMO dashboarding, the Analytics and Insights team has put a pause on building all reporting/dashboarding requests until further notice. That said, following Brian's QA validation we can supply Google Analytics report links to the various components we're tracking within the CLP. Many of which will simply be filtering the [parent events report ](https://analytics.google.com/analytics/web/#/report/content-event-overview/a50123418w177519031p176188361/overview-dimensionSummary.selectedGroup=visitors&overview-dimensionSummary.selectedDimension=analytics.eventLabel/) according to the event labels contained within the data layer specification and filtering for the relevant CLP page. 

cc: @joanneesteban

**Comment by bsmartin-ep** [comment] 2021-04-16 19:33
@jonwehausen -

Still not seeing these events...

Description|dataLayer|GTM|Pass?
-----|-----|-----|----
Accordions - Expand/Collapse|![image](https://user-images.githubusercontent.com/62304138/115073557-7e067e00-9ec6-11eb-9c88-038e349726d0.png) ![image](https://user-images.githubusercontent.com/62304138/115073684-af7f4980-9ec6-11eb-9833-c7e2b327f568.png)|![image](https://user-images.githubusercontent.com/62304138/115073648-a1c9c400-9ec6-11eb-9f8e-997a75000b3c.png) **![image](https://user-images.githubusercontent.com/62304138/115073730-bd34cf00-9ec6-11eb-8fbd-b05f18488f0a.png)|**PASS**
Button CTAs|N/A|N/A|Are these all now action links @jonwehausen?
Link clicks in "Events", "Stories" light blue background area|N/A|N/A|Fail - not seeing any `clp-link-click` events
PDF Downloads|![image](https://user-images.githubusercontent.com/62304138/115074867-44cf0d80-9ec8-11eb-9d55-03d92a629bdf.png)|![image](https://user-images.githubusercontent.com/62304138/115074825-35e85b00-9ec8-11eb-92f2-66608de908ce.png)|**PASS**
"VA Benefits" section links|N/A|N/A|Fail - not seeing any `clp-link-click` events

**Comment by brianalloyd** [comment] 2021-04-19 14:30
@bsmartin-ep @jonwehausen per slack thread @kelsonic will be looking into the failing areas and trying to diagnose solution.  Plan to follow up on this ticket in support.  CC @johnhashva

**Comment by brianalloyd** [comment] 2021-04-26 16:37
@bmcgrady-ep @jonwehausen @bsmartin-ep we've completed work on the failed areas as reflected in #23418, would you please retest and confirm.  TIA.

**Comment by bsmartin-ep** [comment] 2021-04-26 17:38
Overall I would give this a pass @jonwehausen.  Any issues with the wordiness of `clp-action-title` in the action links?

Description|dataLayer|GTM|Pass?
-----|-----|-----|----
Accordions - Expand/Collapse|![image](https://user-images.githubusercontent.com/62304138/115073557-7e067e00-9ec6-11eb-9c88-038e349726d0.png) ![image](https://user-images.githubusercontent.com/62304138/115073684-af7f4980-9ec6-11eb-9833-c7e2b327f568.png)|![image](https://user-images.githubusercontent.com/62304138/115073648-a1c9c400-9ec6-11eb-9f8e-997a75000b3c.png) **![image](https://user-images.githubusercontent.com/62304138/115073730-bd34cf00-9ec6-11eb-8fbd-b05f18488f0a.png)|**PASS**
~Button CTAs~ Action Links|![image](https://user-images.githubusercontent.com/62304138/116124468-52d41980-a692-11eb-9fbb-15f43d3ab491.png) ![image](https://user-images.githubusercontent.com/62304138/116124609-80b95e00-a692-11eb-9b35-47d8bd641070.png)|![image](https://user-images.githubusercontent.com/62304138/116124530-697a7080-a692-11eb-8c6d-7ff834ff1574.png) ![image](https://user-images.githubusercontent.com/62304138/116126454-a9425780-a694-11eb-9f44-cbe34ccacad9.png)|**PASS** Two parallel events, as expected @jonwehausen.
Link clicks in "Events", "Stories" light blue background area|![image](https://user-images.githubusercontent.com/62304138/116124772-ba8a6480-a692-11eb-86bd-207dbeade02c.png)|![image](https://user-images.githubusercontent.com/62304138/116124877-d857c980-a692-11eb-9063-eeaa02e0c113.png)|**PASS**
PDF Downloads|![image](https://user-images.githubusercontent.com/62304138/115074867-44cf0d80-9ec8-11eb-9d55-03d92a629bdf.png)|![image](https://user-images.githubusercontent.com/62304138/115074825-35e85b00-9ec8-11eb-92f2-66608de908ce.png)|**PASS**
"VA Benefits" section links|![image](https://user-images.githubusercontent.com/62304138/116125025-04734a80-a693-11eb-91a2-f15d01bc6f9c.png)|![image](https://user-images.githubusercontent.com/62304138/116125079-1228d000-a693-11eb-8e4c-e80f1cdad506.png)|**PASS**

**Comment by brianalloyd** [comment] 2021-04-27 20:41
Thanks you @bsmartin-ep and @jonwehausen, going to close out this ticket as we've achieved desired connections and will work independent CLP requirements in future campaign requests.  Thanks all for the support.

**Closed by brianalloyd** 2021-04-27 20:41 UTC
Labels: PR-open, analytics-insights, analytics-request, collab-cycle-review, collaboration-cycle, frontend, gtm, vsa, vsa-public-websites

**Comment by jonwehausen** [comment] 2021-04-29 15:59
No concern with that @bsmartin-ep , thanks for closing here.
