### ISSUE TITLE
Analytics Implementation for  Medical Device Reordering Tool - BAM2

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6510] opened 2020-03-04 19:27 UTC
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
This is for FE implementation 

- Who is this request for?

    - Leah Keeler @leahkeeler, FE Team
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _BAM2, Medical Device Reordering Tool
    
 
    
- Provide the Domain where Google Analytics needs to be implemented
    _https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
   _Design - https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407910003
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _projected launch
    
    - Mid-late May 

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [https://staging.va.gov/hearing-aid-batteries-and-accessories/review-and-submit to track conversion and abandon 
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    -I met with Joanne to set KPIs already, the bottom of the funnel conversion page is not in staging yet. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment] 2020-03-10 02:40
@leahkeeler Confirming receipt--we will send you a Slack to coordinate an initial discovery discussion. Thanks!

**Comment by joanneesteban** [comment] 2020-03-25 21:00
Will be working on this Sprint 23 or 24. Moving the Backlog.

**Comment by jonwehausen** [comment] 2020-04-03 13:51
@leahkeeler @mr0sari0 

Wanted to reach out here - We are on track to bring this story in for Sprint 24 and will begin drafting dataLayer requirements as it relates to fulfilling your KPIs. 

A couple follow-up items we would like to request: 
- Authenticated test users who are eligible and ineligible - we will need these for our QA purposes. 
- Info / URL structure for as it becomes finalized

**Comment by leahkeeler** [comment] 2020-04-03 16:37
@jonwehausen Here are the test users: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/benefits-memorials-2/qa-test-plan-users.md  with all the different use case scenarios. 

AI Review is pending, will update once links are finalized. Thanks!!!!

**Comment by jonwehausen** [comment] 2020-04-15 12:59
### Datalayer Requirements (WIP)

## Form Events

## Interactions
Description of Interaction | Screenshot | DataLayer Push
------------ | ------------- | -------------
Any click on the "Do you need to order batteries for any of your hearing aids?" radio button |
![image](https://user-images.githubusercontent.com/48527022/79339673-38038c80-7ef7-11ea-8ec8-106e201b8580.png)  | dataLayer.push{(	'event': 'bam-form-change','bam-form-field': 'batteries-for-hearing-aids', 'bam-form-value': 'yes' // no)};

**Comment by jonwehausen** [comment] 2020-04-28 17:31
Hi @leahkeeler ,

Wanted to follow-up here and see if you and your team were able to get a ticket created on your side for dataLayer implementation. Let us know if you have any further questions.

**Comment by leahkeeler** [comment] 2020-04-28 17:51
Hi Jon, We have been working through some forms system blockers and will be working in next sprint. Thanks!!!

**Comment by bsmartin-ep** [comment] 2020-05-05 17:59
@jonwehausen -

Here's a workspace I started for this implementation...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000285

Thinking this will be broken out into it's own tag(s) like VAOS and GIBCT or we letting this run through the basic Form Event tag?  I lean towards the latter.  In fact, I think Nedie suggested folding the VAOS tag back into the main form tag now that the custom dimension bleed over has been addressed.

Drop these new fields in custom dimensions or should we get them into the Form Action like the navigation click events?

**Comment by mr0sari0** [comment] 2020-05-13 20:30
@jonwehausen implementation is in progress.

**Comment by mr0sari0** [comment] 2020-05-14 17:36
@jonwehausen Not sure if you know this but our design has changed to remove the radio button gating of needing to order batteries or order accessories.  We are displaying the batteries/ accessories directly, which would erase the need for the interaction dataLayer push.

**Comment by jonwehausen** [comment] 2020-05-14 19:07
Hi @mr0sari0 ,

Thanks for your updates here! No problem. Sounds like we can just ignore that portion then. 

One other item to make note of - for the `error-key`, if there is a meaningful error code number you all would like to include there, please record as the first reference in the variable where you you see with the "XXX" in the [spec here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6510#issuecomment-614024612).

**Comment by mr0sari0** [comment] 2020-05-15 15:45
Hi @jonwehausen, thanks for the note about the `error-key`, I'll review with them team on what would be meaningful fo us.

Do you know if the workspace has been created? I am doing some tests currently and wanted to see if they were firing correctly. 

I was reviewing the ticket more and had some thoughts, and feel free to add to this @leahkeeler :

- It is possible for the Veteran to be ineligible for batteries and eligible for accessories and vice versa, so could we have a case for if battery options are ineligible and if accessories are ineligible?
- I am also checking to see if it would be possible to have GA for the 403/404 pages. If so, we would like to have a case for if the Veteran is deceased (403 error),  if the Veteran does not any any supplies eligible for reorder (one of our 404 errors), and if the Veteran was not found in the Denver Logistic Center's database (our other 404 error). 
- I also was reviewing the case for if a Veteran tries to order a product within 6 months of their previous order of that product and I don't think that case will be relevant anymore as we are removing the option to reorder if they are within that timeframe.

**Comment by mr0sari0** [comment] 2020-05-19 16:35
> I am also checking to see if it would be possible to have GA for the 403/404 pages. If so, we would like to have a case for if the Veteran is deceased (403 error), if the Veteran does not have any supplies eligible for reorder (one of our 404 errors), and if the Veteran was not found in the Denver Logistic Center's database (our other 404 error).

I was speaking with @Clark-W-Griswold and it looks like they are using this implementation for the 403/404 error pages:

` event: ${trackingPrefix}sip-form-load-failed`

This should cover our 403 and 404 use cases.

**Comment by jonwehausen** [comment] 2020-05-19 17:56
Hi @mr0sari0 ,

Thanks for your notes there! 

Per our Slack conversation:
- The `sip-form-load-failed` event can include the 403/404 scenarios you described
- We can also move forward with implementing the more descriptive dataLayer error tracking events for ineligibility of batteries, accessories, vice versa. Example syntax: 
```javascript
dataLayer.push({
'event':'bam-error'
'error-key': 'XXX_bam-ineligibility-no-prescription'
});`
```

**Comment by mr0sari0** [comment] 2020-05-21 17:28
Hi @jonwehausen, the PR for our analytics has been merged into staging so you should be able to test it as well. Let me know if you have any questions!

**Comment by jonwehausen** [comment] 2020-05-21 18:45
@mr0sari0 Thank you sir, we will take a look and get back with you!

**Comment by bsmartin-ep** [comment] 2020-05-26 20:26
## QA - WIP

### Form Events

### Ineligibility Errors

### Interactions

n/a

**Comment by bsmartin-ep** [comment] 2020-05-26 20:40
FYI @mr0sari0 -

I tried to order with my test user and received the _bam-ineligibility-no-prescription_ event / message.  The app then allowed me to continue with the application and submit a "shopping cart" with no items:

![image](https://user-images.githubusercontent.com/62304138/82948234-6bfab480-9f6f-11ea-8e8e-7675fba4eef1.png)

I was then sent to _/hearing-aid-batteries-and-accessories/confirmation_ with no content / messaging:

![image](https://user-images.githubusercontent.com/62304138/82948289-86349280-9f6f-11ea-9a92-c381907b39fd.png)

**Comment by mr0sari0** [comment] 2020-06-01 21:19
> FYI @mr0sari0 -
> 
> I tried to order with my test user on staging and received the _bam-ineligibility-no-prescription_ event / message. The app then allowed me to continue with the application and submit a "shopping cart" with no items:
> 
> ![image](https://user-images.githubusercontent.com/62304138/82948234-6bfab480-9f6f-11ea-8e8e-7675fba4eef1.png)
> 
> I was then sent to _/hearing-aid-batteries-and-accessories/confirmation_ with no content / messaging:
> 
> ![image](https://user-images.githubusercontent.com/62304138/82948289-86349280-9f6f-11ea-9a92-c381907b39fd.png)

Hey @bsmartin-ep, we are in the midst of getting updated data from our stakeholder as what's coming in now is inaccurate. I would hold off on testing until we sort out the data issues.

**Comment by bsmartin-ep** [comment] 2020-06-12 12:45
Hi @mr0sari0 -  Are we ready to test this again?

**Comment by jonwehausen** [comment] 2020-06-17 15:09
@bmcgrady-ep Can you please begin mocking up the GA goal configuration within the "VA.gov - Non-Production" property and "Health Care Modernized View - VA.gov Testing Environments" ?

**Comment by mr0sari0** [comment] 2020-06-17 15:39
Hi @bsmartin-ep and @jonwehausen, our staging environment is still having some data fluctuations and we're having to ask the DLC to restart their server every day. 

I would say if time is an issue and you want to continue testing, keep in mind that you may have some errors show up for test users that are supposed to be fine and that you may want to check every few days or so for issues that you come across.

We are currently working on putting in error handling and displaying a UI element to prevent submission with no products selected.

**Comment by jonwehausen** [comment] 2020-06-24 19:42
### Update

Per @mr0sari0 and I's conversation over Slack we would like to institute tracking on the batteries / accessories check/uncheck screen prior to submission. 

### Screenshot Example
![image](https://user-images.githubusercontent.com/48527022/85619915-031b6080-b631-11ea-97e9-ddb14b81fa6e.png)

### Datalayer Code
```
dataLayer.push{(
'event': 'bam-form-change',
'bam-form-field': 'batteries-for-this-device', //'accessories-for-this-device'
'bam-form-value': 'yes' // 'no'
'device-name': 'ER HOOK HE11 680 MINI', 
'device-quantity': 1
)};
```

**Comment by jonwehausen** [comment] 2020-07-07 01:11
Hi @leahkeeler & @mr0sari0 , 

This evening we attempted to QA the latest DL changes and were unable to reach the form at https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction with a few different users.

cc: @bsmartin-ep @bmcgrady-ep

**Comment by jonwehausen** [comment] 2020-07-07 02:18
### QA - WIP - 7/6/2020

At https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories we were able to get to the form with test user+1. 

Description of Interaction | DL Screenshot | Test Status
------------ | ------------- | -------------
Form Loaded | ![image](https://user-images.githubusercontent.com/48527022/86685827-d886bb80-bfd1-11ea-8b27-994289753a84.png) | ✔️**PASS**
Failed Form Submission | ![image](https://user-images.githubusercontent.com/48527022/86689468-03264380-bfd5-11ea-9b20-6723536f2370.png) | ❌ **DOES NOT PASS**

## Changes to Request
- Apologies @mr0sari0 this was my mistyping on the initial spec-- we would like to have the failure event read `'--submission-failed'` past tense instead of `'--submission-failure'`
- Also, each of the submission events should have 2 hypens "--" directly before `submission`, like `'--submission'`, `'--submission-failed'`, and `'--submission-successful'`

### Test Flag ❗ 
While testing with user+1, on the /supplies page, we noticed the error event `bam-error` is toggling with every click of "Order batteries for this device". @bsmartin-ep found where in [the code this seems to be happening](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/2346/components/Accessories.jsx). We expected the use of this button to fire the event [described here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6510#issuecomment-649028431). 

![image](https://user-images.githubusercontent.com/48527022/86686637-82fede80-bfd2-11ea-8e77-315beac667fb.png)

## Outstanding Questions
- We still have been unable to test a successful scenario, would you all have a recommendation of a user to test this path with? Thank you very much.

**Comment by mr0sari0** [comment] 2020-07-09 01:56
@jonwehausen @bsmartin-ep I have updated the tense and dashes on the events as well as added the dataLayer pushes for when products are selected/unselected.

They have been added to this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13419

Locally, I was not able to replicate the `bam-error` event when clicking on a battery supply.    The logic is for that event to fire is if all available batteries or accessories are unable to be reordered. Once the changes have been pushed to staging, I will do another check.

**Comment by bsmartin-ep** [comment] 2020-07-09 18:01
@jonwehausen -

A quick QA of the dataLayer.

I see double dataLayer pushes of `bam-2346a--submission`.

I also see undefined `quantityOrdered` dataLayer variables. 

Are there any other `bam-form-change` events to review?

Description|Screenshot|Data Layer|GA Event
--|--|--|--|
Check _Order batteries for this device_|![image](https://user-images.githubusercontent.com/62304138/87073266-1d396f00-c1eb-11ea-9bb8-5dec7c8fbe16.png)|![image](https://user-images.githubusercontent.com/62304138/87073299-29bdc780-c1eb-11ea-9233-1b031a093218.png)|![image](https://user-images.githubusercontent.com/62304138/87073389-52de5800-c1eb-11ea-96ab-7897ecd37b90.png)
Uncheck _Order batteries for this device_|![image](https://user-images.githubusercontent.com/62304138/87073455-6f7a9000-c1eb-11ea-94a5-c97049db6530.png)|![image](https://user-images.githubusercontent.com/62304138/87073490-7e614280-c1eb-11ea-8c14-9ddad69e34ce.png)|![image](https://user-images.githubusercontent.com/62304138/87073549-920ca900-c1eb-11ea-9534-122076697d8d.png)
All submissions of 2346a|![image](https://user-images.githubusercontent.com/62304138/87073659-bec0c080-c1eb-11ea-97f1-bb156a6e0d40.png)|![image](https://user-images.githubusercontent.com/62304138/87073726-dc8e2580-c1eb-11ea-9fb7-4d131485f72a.png) ![image](https://user-images.githubusercontent.com/62304138/87073765-e879e780-c1eb-11ea-8ae2-3c1e0035ccfb.png) |![image](https://user-images.githubusercontent.com/62304138/87073845-06dfe300-c1ec-11ea-9bcf-2de2f3017db9.png) ![image](https://user-images.githubusercontent.com/62304138/87073817-f891c700-c1eb-11ea-8bea-f95493eb8c85.png)
All **SUCCESSFUL** submissions of 2346a|![image](https://user-images.githubusercontent.com/62304138/87073659-bec0c080-c1eb-11ea-97f1-bb156a6e0d40.png)|![image](https://user-images.githubusercontent.com/62304138/87073965-3262cd80-c1ec-11ea-8165-a9580d1117e0.png)|![image](https://user-images.githubusercontent.com/62304138/87074003-40185300-c1ec-11ea-8c0a-ec30de0b9bcd.png)

**Comment by mr0sari0** [comment] 2020-07-09 18:43
@bsmartin-ep At the moment, the DLC is not providing a`deviceName` for batteries in their staging database, but they have said they will provide it in their production database.

Looking into the double `dataLayer` pushes for the submission and the `undefined` for `quantityOrdered`...

**Comment by mr0sari0** [comment] 2020-07-09 22:13
@bsmartin-ep @jonwehausen  I have identified the cause of the undefined `quantityOrdered` and have fixed it. 

For the double dataLayer pushes of bam-2346a--submission, I have discovered that if I remove the snippet I put in for it, it still fires. I am wondering if there is something in the form system that is firing as well.

<img width="1440" alt="Screen Shot 2020-07-09 at 6 13 01 PM" src="https://user-images.githubusercontent.com/12755283/87096003-dca01c80-c20f-11ea-9810-73f4b7886628.png">

**Comment by bsmartin-ep** [comment] 2020-07-10 01:03
@mr0sari0 -

> I am wondering if this push is something in the form system that happens when submissions occur.

Maybe this?

https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L158

@jonwehausen - What's the best solution for this?  A separate dataLayer push before the submission event?

```
dataLayer.push({
'bam-quantityOrdered': '<quantity_ordered>'
});
```

**Comment by jonwehausen** [comment] 2020-07-10 12:46
Hey @mr0sari0 and @bsmartin-ep , 

Thanks for your work here and investigating this -- You both are correct in that there is a default `--submission` event (your code link @bsmartin-ep) that is baked-in to the platform forms system code, so that's most likely what's causing the duplicate event push. 

That said, we would like to include the `bam-quantityOrdered` variable with the `--submission` and `--submission-successful` events and without duplicating events if possible.

Please see the bottom of [this documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md) as a reference for those form events that are traditionally baked-in to our forms tracking.

**Comment by bsmartin-ep** [comment] 2020-07-10 13:00
@mr0sari0 -

I do see this `submitToUrl` method which accepts an `eventData` param.

`export function submitToUrl(body, submitUrl, trackingPrefix, eventData) {
`
https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L81

Here it is being used in _1995_:

https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/applications/edu-benefits/1995/submitForm.js

(cc @jonwehausen)

**Comment by mr0sari0** [comment] 2020-07-10 19:31
@bsmartin-ep and @jonwehausen  1995 has its own `submitToUrl` which is called in their `submitForm`. Platform has its own `submitToUrl` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L81) and `submitForm` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L141) which handles the submission along with the dataLayer pushes...except there are not passing in `eventData` in their `submitForm`.

I'd prefer to use platform's code to keep consistent with latest changes and features. I'll probably make a PR adding in `eventData` to their `submitForm` and implement it [here](https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L150) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/137ace1d874eff3d02485dd1580906449824c7d4/src/platform/forms-system/src/js/actions.js#L159). That way we can add it the item quantities and avoid the duplicate dataLayer pushes and remove extra code on our side.

**Comment by mr0sari0** [comment] 2020-07-10 19:49
@bsmartin-ep @jonwehausen [Here's the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13454) for adding `eventData` to platform's `submitForm`.

**Comment by bsmartin-ep** [comment] 2020-07-14 13:06
@mr0sari0 / @jonwehausen -

I tested this AM and am seeing two `--submission` events (one with an undefined `bam-quantityOrdered` var).

![image](https://user-images.githubusercontent.com/62304138/87428992-2773b880-c5b1-11ea-8001-c62ccdf85b8b.png)
![image](https://user-images.githubusercontent.com/62304138/87429009-2b9fd600-c5b1-11ea-9e85-b55b547dfdbd.png)

And the `--submission-successful` event has an undefined `bam-quantityOrdered` var.

![image](https://user-images.githubusercontent.com/62304138/87429021-322e4d80-c5b1-11ea-9c1c-682931acc404.png)

**Comment by jonwehausen** [comment] 2020-07-15 11:39
### QA 

@leahkeeler / @bradl3yC 

### Notes
- Good news: We are no longer seeing the duplicate `--submission` events
- Unfortunate news:  we are seeing the `--submission-succesful` event under the failed scenario (see testing below) 

### [Test with user+1](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/benefits-memorials-2/qa-test-plan-users.md)
Description of Interaction | DL Screenshot | Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Automatic save of form  | ![image](https://user-images.githubusercontent.com/48527022/87535721-ebe6f600-c665-11ea-9f2b-50f77b3ab0be.png) | ![image](https://user-images.githubusercontent.com/48527022/87536016-66b01100-c666-11ea-970a-188754bfc94c.png) ![image](https://user-images.githubusercontent.com/48527022/87536076-7b8ca480-c666-11ea-8521-008892d880b2.png) | ✔️ **PASS**
User is ineligible to order hearing aids | ![image](https://user-images.githubusercontent.com/48527022/87536178-ad057000-c666-11ea-90a1-e2e0a96fdb24.png) | ![image](https://user-images.githubusercontent.com/48527022/87536247-cdcdc580-c666-11ea-91e8-c1fa90403b98.png) ![image](https://user-images.githubusercontent.com/48527022/87536291-e342ef80-c666-11ea-869d-c4f624abb22e.png) | ✔️ **PASS**
Click on "Order batteries for this device" | ![image](https://user-images.githubusercontent.com/48527022/87536429-17b6ab80-c667-11ea-97a5-7e4368931919.png) | ![image](https://user-images.githubusercontent.com/48527022/87536493-36b53d80-c667-11ea-908f-a9c2295f962a.png) ![image](https://user-images.githubusercontent.com/48527022/87537038-00c48900-c668-11ea-873f-356ac3d5a6a3.png)| ✔️ **PASS**
**FAILED** submission of form | ![image](https://user-images.githubusercontent.com/48527022/87537305-6add2e00-c668-11ea-8bd6-a7c395d5665e.png) | ![image](https://user-images.githubusercontent.com/48527022/87537369-7a5c7700-c668-11ea-9ca7-1d3f7f95c04b.png) ![image](https://user-images.githubusercontent.com/48527022/87537453-9cee9000-c668-11ea-854d-5a43bc42caf6.png) | ❗ **DOES NOT PASS** Seeing `--successful` event on **failed** submission

### Test with user+17
Description of Interaction | Interaction / DL Screenshot | Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Accessories cannot be added | ![image](https://user-images.githubusercontent.com/48527022/87539492-fc01d400-c66b-11ea-806d-b73a34a1ec6d.png) | ![image](https://user-images.githubusercontent.com/48527022/87539521-091ec300-c66c-11ea-937d-176312e86e63.png) ![image](https://user-images.githubusercontent.com/48527022/87539570-1cca2980-c66c-11ea-8da8-f19f94c4b727.png) | ✔️ **PASS**
Remote control cannot be ordered | ![image](https://user-images.githubusercontent.com/48527022/87539661-4c793180-c66c-11ea-89d0-c19ac7380f08.png) | | ❗ Do we need to record a separate `error-key` for remote control? 
Click to add batteries | ![image](https://user-images.githubusercontent.com/48527022/87539046-3ae35a00-c66b-11ea-8fec-5c170f90f7f5.png) | ![image](https://user-images.githubusercontent.com/48527022/87539077-4c2c6680-c66b-11ea-9d42-29cf6efd0c05.png) ![image](https://user-images.githubusercontent.com/48527022/87539138-62d2bd80-c66b-11ea-8d4f-35e9eec3ceed.png) | ✔️ **PASS**
Click to remove batteries | ![image](https://user-images.githubusercontent.com/48527022/87539219-8138b900-c66b-11ea-876d-49bd378f5dca.png) | ![image](https://user-images.githubusercontent.com/48527022/87539246-8c8be480-c66b-11ea-8b8f-a3869127b349.png) ![image](https://user-images.githubusercontent.com/48527022/87539284-9b729700-c66b-11ea-8b64-9e79c1875a67.png) | ✔️ **PASS**
Failed submission | ![image](https://user-images.githubusercontent.com/48527022/87539835-a2e67000-c66c-11ea-866b-b1919856219e.png) | | ❗  **DOES NOT PASS**

### Test with user+14 
- Accessed form with for a user who cannot order
- No `event` recorded for this scenario. Do we want to add an event to track this? 
 ![image](https://user-images.githubusercontent.com/48527022/87537988-872d9a80-c669-11ea-83f2-3322c2512550.png)

### Test with user+21
- Veteran is deceased
- No `event` recorded for this scenario. 
![image](https://user-images.githubusercontent.com/48527022/87540330-78e17d80-c66d-11ea-8bcb-fae441348ae5.png)

**Comment by leahkeeler** [comment] 2020-07-15 21:39
Did this resolve after the changes make for other analytics issue cc: @mr0sari0 @bradl3yC

**Comment by bradl3yC** [comment] 2020-07-15 23:05
There is still one issue to resolve

**Comment by jonwehausen** [comment] 2020-07-15 23:06
Thanks @bradl3yC and @leahkeeler ,

We've got our container deployed to support any events that come through over the evening hours. 

We'll want to make sure we get the `--submission-successful` and `--submission-failed` events correct asap.

**Comment by jonwehausen** [comment] 2020-07-16 15:45
https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/423013061

Working with Brad on adding the following variables for the partial failed ubmission scenario: 
```javascript
   'event': 'bam-2346a--submission-successful', 
   'partial-failed': true,
   'product-ids-successful': '44444 55555 66666',
   'product-ids-failed': '11111'
```
and ensuring the `--submission-failed` event is only firing for total failures

**Comment by jonwehausen** [comment] 2020-07-23 20:10
Scenarios outlined above have been verified, tested and deployed.

**Closed by jonwehausen** 2020-07-23 20:10 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle, frontend, gtm, vsa, vsa-benefits-2
