### ISSUE TITLE
Validation errors setting date fields to null 

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#90446] opened 2024-08-09 22:50 UTC
## Issue Description
in Windows > Edge (via citrix access gateway)

Currently on date pages like 'Service post-9/11' in staging, When I choose a complete start date and then try to set the values to null, I get a validation error. Expected to not have a validation error when setting month back to "select" and day and year back to null. https://jmp.sh/6vYevlSM . However, I was able to successfully click "continue"

---

## Tasks
- [ ] …

## Acceptance Criteria
- [ ] …

**Comment by christinec-fftc** [comment] 2024-08-12 22:17
I can reproduce this in storybook https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--docs We should ask if this is expected behavior or something that should be fixed in the component library

**Comment by pacerwow** [comment] 2024-08-14 22:20
Also occurs on Safari in iOS

**Comment by christinec-fftc** [comment] 2024-08-15 19:26
Started a [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1723748504080179) asking about expected behavior for this component

**Comment by christinec-fftc** [comment] 2024-09-11 18:03
Closing this out since it is an issue with the component library. Follow [#78778](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78778) for further updates

**Comment by christinec-fftc** [comment] 2024-09-11 18:03
Closing this out since it is an issue with the component library. Follow [#78778](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78778) for further updates

**Closed by christinec-fftc** 2024-09-11 18:03 UTC
Labels: bug, engineering, needs-refinement, needs-estimate, front end, disability-experience, DBEX-TREX
