### ISSUE TITLE
Quality Assurance Feedback - Staging Review - Search & Discovery - Typeahead 1.0

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#20841] opened 2021-03-04 16:06 UTC
Staging review ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20532

## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great work! The feature works as expected in multiple browsers and on mobile.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
1. [x] The TestRail valid search string test case should be updated to use a search term that matches the updated suggestion database (such as `ebenefits` instead of `benefits`).

**Should:**
1. [x] Since this is a site-wide feature that will impact lots of users, automated tests should be written to ensure type-ahead suggestions work as expected. The valid test case in TestRail has an `Automation Type` of `None` at the moment.

**Consider:**
1. [x] In some browsers (such as Firefox on macOS), focus sometimes does not go to the search input field after clicking `Search`. Consider investigating whether the type-ahead feature affects this.

**Comment by tlei123** [comment] 2021-03-04 16:46
@ddzz , Valid-search-string test-case [C3164](https://dsvavsp.testrail.io/index.php?/cases/view/3164) now updated for **ebenefits** keyword, as well as [referenced use-case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/type-ahead/type-ahead-use-cases.md#use-case-b---valid-search-string).

**Comment by tlei123** [comment] 2021-03-04 16:52
@denisecoveyduc , re. the Should & Consider items...

I'll leave it to your team to handle these for now, as I'm busy with other teams' test planning/cases.  I'll circle back when I can.

**Comment by denisecoveyduc** [comment] 2021-05-27 20:22
@tlei123 Circling back on the feedback here.

1- Must : Was resolved as per above comments
2- Should: Can we sync up on establishing a Test Rail account?  What are the best next steps? We will that work in #25364 so feel free to comment there with next steps. cc: @srsuddath  -fyi
3- Consider: We have since set an autofocus on the search input field so this is no longer a concern.

**Comment by tlei123** [comment] 2021-06-04 01:16
@srsuddath , re. the **Should** item [automated E2E test w/ corresponding TestRail test-case]...

Request TR creds from @denisecoveyduc .  You can create your TestRail test-case [here](https://dsvavsp.testrail.io/index.php?/suites/view/150&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=642) for your automated E2E test.

Peter has some [basic Cypress-TestRail-Reporter doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/e2e-testing/cypress-testrail-reporter-config.md), and I also have an [add'l help doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/testrail/vsa-qa-cypress-testrail.md).

Of course, feel free to ping me as needed on Slack for any further questions/concerns.

**Comment by denisecoveyduc** [comment] 2021-07-08 02:23
@srsuddath @tlei123  Since our existing cypress tests are now connected to TestRail does this resolve the "should" Are we now able to close? or what steps need to be addressed going forward?

> Should:
> 
> Since this is a site-wide feature that will impact lots of users, automated tests should be written to ensure type-ahead suggestions work as expected. The valid test case in TestRail has an Automation Type of None at the moment.

**Comment by tlei123** [comment] 2021-07-08 17:52
@denisecoveyduc , yep, this is ready for Closing.  I just confirmed  @srsuddath 's satisfied the Should item, and Closed the [automated E2E test-run](https://dsvavsp.testrail.io/index.php?/runs/view/1975&group_by=cases:section_id&group_order=asc) in TestRail.

cc @ddzz

**Comment by denisecoveyduc** [comment] 2021-07-08 18:00
Thanks @tlei123  & @srsuddath

**Closed by denisecoveyduc** 2021-07-08 18:00 UTC
Labels: collab-cycle-feedback, collaboration-cycle, vsa-search-discovery, vsp-product-support
