### ISSUE TITLE
[UX] [SPIKE] Review end of interaction for DAY OF CHECK IN

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49521] opened 2022-11-09 23:30 UTC
## Background

Similar [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49400) that contains potential solution

If a user opens a check-in page without a current valid session, we show a generic error page. This might be confusing/worrying to users and give the impression that they have done something wrong.

How might we improve users' interactions after they have completed their task?

## (Proposed) User Story

As a Veteran, I do not wish to see an error when re-opening my browser after using day-of check-in, so that I do not think I have done something wrong.

## ACs

TBD

**Comment by loripusey** [comment] 2022-11-16 14:41
This seems like a duplicate of this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49400)

**Comment by kellysmith1008** [comment] 2022-12-20 17:05
I'm creating a few mockups around ways to handle closing the active sessions, but have a few questions for @benbrasso-agile6 and maybe @acrollet or @brianseek could answer as I build out these mockups:
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/955fb349-7936-44f5-a41d-0b97e2028908)
Questions:
1. When a user selects “Find out how to check in on the day of your appointment” link, where does that take them? How do they get back to the pre-check-in confirmation page?
2. Is there a way we can add those same 2 links on the appointment list page? Or does adding the “Sign in to manage all appointments seem redundant there?
3. Will we need these two links in the future if we move forward with the unified PCI/CI experience?
4. If we don’t need them, could we code a “Check in now” CTA button to work in place of the “Confirm appointment” CTA button as a redirect, so the error in the ticket wouldn’t be an issue?

**Comment by benbrasso-agile6** [comment] 2022-12-20 17:15
Are we solving for day of or pre-check-in? I thought the conversation has been around day of? But, now this ticket is about pre check in. Just want to double check.

**Comment by benbrasso-agile6** [comment] 2022-12-20 17:19
1. That link goes to - https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/. How do you get back? You can access pre-check-in again by clicking the pre-check-in link from your text messages. 
2. We can technically add any link to any page. When you say the appointment list page... there are two pages in pre check in that list appointments. The intro page and the confirmation page. Or, were you talking about day of check in? 
3. Too difficult to say, but I'd recommend if we have a problem now, we should solve it now within the current application. 
4. Not sure I'm following about the "confirm appointment" CTA. What page is that on? 

I'd be in favor of a coworking session between the 4 of us to tackle this ticket.

**Comment by kellysmith1008** [comment] 2022-12-20 17:28
@benbrasso-agile6 Thanks! Those answers make sense to me. I can definitely set up a coworking session. I'll do that here shortly!

**Comment by benbrasso-agile6** [comment] 2022-12-20 17:29
The other factor here is the speed at which the API team solves for some of these scenarios via redirects. We briefly touched on that ticket that's with the API team in scrum this morning.

**Comment by benbrasso-agile6** [comment] 2023-01-03 18:35
Let's use this ticket for day of, I'll create a separate one for pre check in to tackle another day/sprint

**Comment by kellysmith1008** [comment] 2023-01-03 18:43
Notes from today's meeting: [https://app.zenhub.com/files/133843125/5ddc65dc-f97d-46d8-835c-1346136d1577/download](https://app.zenhub.com/files/133843125/5ddc65dc-f97d-46d8-835c-1346136d1577/download)

**Comment by benbrasso-agile6** [comment] 2023-01-03 19:03
I removed the missing uuid widget from the check in GA dashboard. 

This error will still populate in the errors widget as www.va.gov/health-care/appointment-check-in/error?error=no-token

If/when we create a new page (e.g., /no-token) for this type of "error," theoretically the number of www.va.gov/health-care/appointment-check-in/error?error=no-token "errors" will be reduced. 

If/when we add this new page, I'll make room for it somewhere in the GA dashboard.

**Comment by benbrasso-agile6** [comment] 2023-01-03 19:22
Ticket created for pre-check-in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51411

Pull into whichever relevant sprint

**Comment by kellysmith1008** [comment] 2023-01-11 14:04
[Updated design for possible solutions](https://www.sketch.com/s/1576a7ec-7a24-4b52-acc8-925109b96853).

**Comment by loripusey** [comment] 2023-01-11 14:34
I feel like these solutions don't really solve the problem of vets using old links but just work towards some clarification; perhaps the unified experience can work to solve this problem. 

Ideally if they access an old link under these scenarios, this is what I would expect as a user:
1. I use an old link and **I DO** in fact have appointments for today --> I am taken to check-in where I can verify my identity and then see my appointments for today and check-in if I am in the check-in window
2. I use an old link but I DO NOT have any appointments for today --> I am taken to check-in where I can verify my identity and then see that I DO NOT have any appointments for today

Whether this is even possible without completely re-architecting, I don't know. I think we have to weigh the effort versus the value to end users to change it. I think the architecture for having a link that expires is a valid one and I have seen it used many times out in the real world, but it seems that there will always be folks who don't get it.

I still think that UX's ideas for unified experience will certainly go a long way towards solving this problem. Perhaps we shelve the "end of interactions" discussions or incorporate them into the unified experience discussions. Thoughts?

@benbrasso-agile6 @acrollet @kellysmith1008

**Comment by benbrasso-agile6** [comment] 2023-01-11 14:44
Am going to chat a bit with the ux team about it.

If I recall correctly, we're really solving for how we're tracking and interpreting this scenario in GA. Historically, this scenario throws caution to us because it's presented as an "error" in GA, when in fact it's not really an error. 

I don't believe there's much of anyone actually trying to check in. Therefore, it doesn't seem worth trying to rejig our architecture to try and somehow recreate a UUID on the fly. 

I can see the ux team finishing this up in a day or two, so, if we want to proceed with engineering, that would be nice. It would be a way for us to no longer interpret this as an "error" in GA and throw caution. Plus, the very small percent of Veterans that ARE trying to check in will have a better solution than what exists today.

**Comment by loripusey** [comment] 2023-01-11 15:03
So, why is this not an engineering problem to solve?

**Comment by benbrasso-agile6** [comment] 2023-01-11 15:13
ux and engineering met together last week. We're working on giving the wireframes as a result of that conversation.

**Comment by kellysmith1008** [comment] 2023-01-11 16:42
Merged a bit of conversation and input around this and created this mockup as an iteration - @zach-park or @ytsaoca to create the branch in abstract if time. I can do it if they don't have capacity. ![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/e80036a9-6679-4c70-9a7d-547316a63f44)

**Comment by acrollet** [comment] 2023-01-11 17:37
> 1. I use an old link and **I DO** in fact have appointments for today --> I am taken to check-in where I can verify my identity and then see my appointments for today and check-in if I am in the check-in window
> 2. I use an old link but I DO NOT have any appointments for today --> I am taken to check-in where I can verify my identity and then see that I DO NOT have any appointments for today

just to clarify, when a veteran accesses a pre-checkin link, we don't know if they have appointments for today or not, we only know the time of the appointment associated with that pre-checkin UUID.

**Comment by benbrasso-agile6** [comment] 2023-01-11 17:47
Just making sure we don’t get confused… this thread is for the day of app reopening for an expired session

**Comment by acrollet** [comment] 2023-01-11 17:52
> Just making sure we don’t get confused… this thread is for the day of app reopening for an expired session

very good point, I hadn't realized that until a few minutes ago!

**Comment by acrollet** [comment] 2023-01-11 17:53
the summary does mention pre-check-in as well, should we split that into a separate story?

**Comment by benbrasso-agile6** [comment] 2023-01-11 17:58
Yes it’s located here https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51411

**Comment by acrollet** [comment] 2023-01-11 18:18
> Yes it’s located here https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51411

great, I updated the summary to remove references to precheckin.

**Comment by loripusey** [comment] 2023-01-11 18:30
sorry, I have COVID brain, just ignore my comments.

**Comment by acrollet** [comment] 2023-01-11 18:31
> Am going to chat a bit with the ux team about it.
> 
> If I recall correctly, we're really solving for how we're tracking and interpreting this scenario in GA. Historically, this scenario throws caution to us because it's presented as an "error" in GA, when in fact it's not really an error.

I think there's more nuance to this, at least from my standpoint. We've noticed the issue because it surfaces as an error in GA, but it's happening when veterans are seeing an error page when they didn't do anything wrong, which seems like a negative interaction to me.

**Comment by ytsaoca** [comment] 2023-01-13 19:13
If a user opens a check-in page without a current valid session, this user may assume that he should have a valid session to check in. I think[ this page was created for this scenario](https://share.goabstract.com/522b18f5-15b7-4d5d-9a52-d01455accd24?mode=design&sha=599aa9584a5d97c41d61c6f89228738f6cc2fb1f).

Any thoughts?

@benbrasso-agile6 @kellysmith1008

**Comment by kellysmith1008** [comment] 2023-01-13 19:53
Oh nice @ytsaoca ! I think this is more for when they are trying to reopen an expired session, what that error message looks like. But this wording is very similar, so I don't know if we need to make the distinction between the two errors - no valid session vs reopening and expired session. I'll let @benbrasso-agile6 weigh-in when he gets back in on Tuesday. But I didn't know that page existed - sorry for possibly duplicating work!

**Comment by ytsaoca** [comment] 2023-01-13 21:30
No worries! Yeah, we can discuss if we want/ need to make the distinction between no valid session vs reopening and expired session!

**Comment by ytsaoca** [comment] 2023-01-20 16:55
Final mockup: https://share.goabstract.com/4d46f6ca-4303-4a55-89a2-686f13514d50

**Comment by benbrasso-agile6** [comment] 2023-01-20 17:13
@ytsaoca @kellysmith1008 Looks nice!

Should we put a period after 53079? 

Should we update the Need help? content to be consistent with what's on production? 

**For questions about your appointment or if you have a health-related concern**, ask a staff member at your VA health facility. 

Does the FE team know this is ready to be worked on?

**Comment by loripusey** [comment] 2023-01-23 14:20
So, this new wireframe would ONLY show when there is no LOROTA entry for them (i.e. it has been deleted or doesn't exist); is that a correct statement? Also, other than the period, is this now ready for engineering to work on it?
@benbrasso-agile6 @kellysmith1008 @ytsaoca

**Comment by benbrasso-agile6** [comment] 2023-01-23 14:26
@loripusey it's possible there's still a scenario where a user will get to http://www.va.gov/health-care/appointment-check-in/error?error=no-token. @acrollet and @brianseek would be good to weigh in here. 

But, yes, this new page will be something like http://www.va.gov/health-care/appointment-check-in/no-token

**Comment by ytsaoca** [comment] 2023-01-23 17:42
Thanks for reviewing it. @benbrasso-agile6 @kellysmith1008 
- Added the period after 53079 
- Updated Need help section, "ask a staff member"
- Edited "Text check in to 53079.", and used bold for "check in" and "53079."
 
Final mockup: https://share.goabstract.com/4d46f6ca-4303-4a55-89a2-686f13514d50

**Comment by benbrasso-agile6** [comment] 2023-01-23 17:49
Very nice 👍

**Comment by ytsaoca** [comment] 2023-01-23 17:50
@loripusey Sorry for not syncing with you to have a mechanism before closing the ticket. Will make sure doing it in the future!

@benbrasso-agile6  Do we want to change the Need Help of other error page, too? If yes,  do we need to have ticket for this?

**Comment by ytsaoca** [comment] 2023-01-23 17:50
@loripusey Sorry for not syncing with you to have a mechanism before closing the ticket. Will make sure doing it in the future!

@benbrasso-agile6  Do we want to change the Need Help of other error page, too? If yes,  do we need to have ticket for this?

**Comment by benbrasso-agile6** [comment] 2023-01-23 17:55
It's more than the error pages. I think the plan is to update all of them in check in once @zach-park [pushes this branch to master](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2), which will happen in 2-3 weeks when we're ready. So, I think we were just waiting for this to happen, and then they will all update for check in.

**Comment by benbrasso-agile6** [comment] 2023-01-23 17:57
If it's easy to push that Need Help content into master now, I don't think anyone would be against it. I think the reason we haven't done that is because it was sort of stuck in that travel branch that isn't ready to go into master yet.

**Comment by ytsaoca** [comment] 2023-01-23 22:16
@loripusey , The mockup is ready for the FE team to work on. Thanks!

**Closed** 2023-01-24 16:33 UTC
Labels: design, ux, HCE-Checkin
