### ISSUE TITLE
[Bug] Address validation: All addresses are causing the same response

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#6277] opened 2020-02-27 21:02 UTC
## What happened?

From staging (user 226, but you can use any user):

1. Log in and go to the profile.
2. Edit mailing address and enter 811 Vermont Ave NW, Washington DC, 12345.
3. Click update.
4. This is the screen I got. Problem: this is an old state that should no longer show now that override should always exist. It should elicit the overide w/ no suggestions state:

<img width="470" alt="Screen Shot 2020-02-27 at 3 50 08 PM" src="https://user-images.githubusercontent.com/34068740/75486076-dce2fe00-5979-11ea-8849-3a931920b690.png">

Additionally I tried 36320 Coronado Dr Fremont, CA 94537, which should elicit override + two suggestion [according to this](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md). I also got the same, old screen that did not allow override:

<img width="467" alt="Screen Shot 2020-02-27 at 3 51 10 PM" src="https://user-images.githubusercontent.com/34068740/75486204-11ef5080-597a-11ea-9fd7-3919de51fbbe.png">

Finally, I tested with a good address that should have saved without showing the address validation screen — 811 Vermont Ave NW, Washington, DC 20571 and still got the same screen as above.

## Specs:
- Device: Macbook
- Browser: Chrome, latest version
- Test User: 226 but any should work

## Steps to Reproduce
- URL: https://staging.va.gov/profile/

See above for steps to reproduce.

## Desired behavior

1. We should not be showing a state without override.
2. We shouldn't be showing address validation for good addresses.
3. We should be showing the correct response based on whether the address elicits suggestions or not, or needs a unit number.

## Acceptance Criteria
- [ ] The address validation is working again, and [these addresses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md) elicit the correct response.
- [ ] Valid addresses do not cause the address validation screen to show.

**Comment by erikphansen** [comment] 2020-02-27 21:12
I'm gonna close this one in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/6278 which digs into the root cause of this problem.

**Closed by erikphansen** 2020-02-27 21:12 UTC
Labels: bug, frontend, profile
