### ISSUE TITLE
Analytics Implementation or QA Support for [VA Notify Forms Strike Team - In Progress Reminders]

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#43322] opened 2022-06-23 19:55 UTC
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - VA Notify Forms Strike Team and Benefits-1 Team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/
    - https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/resume/
    
- **When is the launch date?**
    - Link is already in production but we would like to implement the additional dimension tracking June 29th

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    - I believe all interactions are properly tracked. We are trying to implement another dimension being tracked. We would like to have the age of the form tracked. Options sent as a dimension would be 7_days, 21_days, 35_days, and 49_days
    -
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - Our currently mocked URL is:
             -  https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/?utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&7_days
             - https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/resume/?utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&7_days
    
> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment] 2022-06-30 16:11
@megansiddle we were able to work around having to add a custom dimension to create a segment to account for 7 days, according to the Mocked URLs. Here is the [segment](https://analytics.google.com/analytics/web/template?uid=b4mrTpcbTmuZqEQQq7gpkA), might have to be added(created) to see the data (when in production) in GA. [Event Landing Page report attached.](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_.useg=user1bzDIEP4SRSfSJWrmsDmRg&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22view-change-dependents%22,0%5D%5D/) Let me know if you have any questions.

Below is a screenshot for how the segment works:
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/cae5fa79-0c4e-47f8-8bc8-da6e2950c947)

**Comment by megansiddle** [comment] 2022-06-30 17:27
@jonathan-epstein13 that is super awesome!!! So we don't need a special UTM parameter name? Like UTM-dimension=7_days?
Also would the campaign then get broken out on the events page by the "&7_days"?

**Comment by megansiddle** [comment] 2022-06-30 19:38
Closing this out since I got my questions answered! Thanks again!

**Comment by megansiddle** [comment] 2022-07-22 19:55
Hi @jonathan-epstein13! We are live in production with the new links. I tried creating segments but none of them show data and I know we have had at least 20 form submissions from following the new links. 

These are the links that have been included in the Reminder emails:
https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&7_days

https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&21_days

https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&35_days

https://va.gov/view-change-dependents/add-remove-form-21-686c/resume/utm_source=VANotify&utm_medium=email&utm_campaign=686c-SIP-reminder&49_days

**Comment by jonathan-epstein13** [comment] 2022-07-25 11:09
Hello @megansiddle. I am looking into this and will post here with any questions.

**Comment by jonathan-epstein13** [comment] 2022-07-25 11:19
@megansiddle [This report link](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_.useg=builtin1&explorer-table.secSegmentId=analytics.campaign&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22www.va.gov~2Fview-change-dependents~2Fadd-remove-form-21-686c~2Fresume~2F%22,0%5D%5D/) looks to show it is tracking correctly. Let me know if this looks correct.

**Comment by jonathan-epstein13** [comment] 2022-07-28 20:00
As per office hours, @megansiddle you and your team would like to have 7 day, 14 day, 21 day and 35 segments that can be used across all campaigns. Is there anything else that can be added to this request? Just want to make sure I have all the information. Thank you!

**Comment by megansiddle** [comment] 2022-07-28 20:39
That sounds right, I just want to make sure that the added segment can then be used as a dimension in GA...as in it would show when adjusting the "+ Add a dimension or metric" dropdown?
<img width="157" alt="image" src="https://user-images.githubusercontent.com/99678581/181632916-0a25282a-699a-4a83-aa5a-0eb42b12b649.png">

**Comment by jonathan-epstein13** [comment] 2022-07-28 21:59
@megansiddle here is an example of a [segment ](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20220717&_u.date01=20220723&_.useg=userZSCcBOIHTkylHFcR75IjkA&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.campaign&_r.tabId=explorer/) for 7 days. 

Since they are at the end of the landing page, I just added a general 7_days segment, but if you're looking for something else. I'll confirm with @jennaouellet to see what would be done based on last office hours (Tuesday 7/26.) I apologize for any confusion.

**Comment by jonathan-epstein13** [comment] 2022-07-28 22:06
@megansiddle here is an example of a [segment ](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20220717&_u.date01=20220723&_.useg=userZSCcBOIHTkylHFcR75IjkA&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.campaign&_r.tabId=explorer/) for 7 days. Since they are at the end of the landing page, I made it a simple 7_days segment, but a dimensions is different and I'd have to check back with @jennaouellet to create a new dimension for 7_days, 14_days etc. according to the office hours from Tuesday, 7/26/22. Just want to make sure everything is correct. 


![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/73385a30-c521-4ef9-8ca1-20fc734dbc8c)
I apologize for the drawing, but was this the other option below what you were looking for?
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/293946f3-5c4a-42f1-99f6-ec2597eabcd9)

**Comment by megansiddle** [comment] 2022-08-02 15:22
Yeah, the other option below is what I was hoping to be able to get.

**Comment by jonathan-epstein13** [comment] 2022-08-02 16:11
@megansiddle I'll be in touch with @jennaouellet and discuss how we can do that. I know it was mentioned, but I just want to make sure this is done correctly to you and your team's specifications.

**Comment by michelle-dooley** [comment] 2022-08-08 18:06
@megansiddle - we have met and @jonathan-epstein13 will be working on creating these new dimensions for you.

**Comment by jonathan-epstein13** [comment] 2022-08-09 16:44
@megansiddle here is the example taxonomy for implementing the cadences of 7 days, 14 days, 21 days and 35 days. This will then show up in as an `event_action`. Let me know if this makes sense and we could test as soon as these are implemented. 

```
{
     event: 'api_call',
     api-name: 'email',
     api-status: 7_days,
}

{
     event: 'api_call',
     api-name: 'email',
     api-status: 14_days,
}


{
     event: 'api_call',
     api-name: 'email',
     api-status: 21_days,
}
{
     event: 'api_call',
     api-name: 'email',
     api-status: 35_days,
}

```

**Comment by megansiddle** [comment] 2022-08-09 17:41
I think that makes sense @jonathan-epstein13

**Comment by jonathan-epstein13** [comment] 2022-08-09 17:48
Great! @megansiddle as soon as these are implemented, we can go ahead and test.

**Comment by jonathan-epstein13** [comment] 2022-08-12 17:05
@megansiddle wanted to follow up to see if there is anything else on our end that you will need? Let us know when we can test and if you have a specific login/URL to test, we can do that.

**Comment by megansiddle** [comment] 2022-08-12 17:18
@jonathan-epstein13 so sorry I got confused. I thought this was something your team implemented. How do I go about implementing these?

**Comment by jonathan-epstein13** [comment] 2022-08-12 17:27
No worries! @megansiddle I should have been more clear. I believe FE would need to implement, similar to how you and your implemented for the URLs  7_days 14_days etc. I can confirm this on my end as well, but once this is implemented, we can start seeing it in GA.

**Comment by jonathan-epstein13** [comment] 2022-08-15 12:25
@michelle-dooley might need some clarification on next steps with the `api_call `taxonomy sent over.

**Comment by jonathan-epstein13** [comment] 2022-08-19 17:12
Hello @megansiddle. So we wanted to see if there is a developer on your team that puts in the code for the `api_call` taxonomy, and/or others events that are already tracked in GA? Maybe this can be resolved with the developer. Let us know if there are any questions.
cc: @michelle-dooley

**Comment by michelle-dooley** [comment] 2022-09-14 19:36
@megansiddle - unfortunately we have lost Jenna and Jonathan so I am trying to go through all their outstanding tickets.  Do you have what you need here?  It looks like you were able to track days via the utm parameters of the campaign.

**Closed** 2022-09-27 15:11 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle, gtm, collab-cycle-review
