### ISSUE TITLE
Staging review - design feedback - DS  Memorable date, Select and Breadcrumbs

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#64201] opened 2023-08-24 12:26 UTC
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Memorable date
- [Sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F8230127-0500-4C1A-BBBB-821299A5BDFF/canvas) has a month/year option. That option is not in [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default) or the [Design System](https://design.va.gov/components/form/memorable-date). Can we add those to both Storybook and the Design System? Is there guidance around using the month/year option?

### All components
 - All the components seem to have different versions. For example, the memorable date component in [sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F8230127-0500-4C1A-BBBB-821299A5BDFF/canvas) is showing a V2 version, the [design system](https://design.va.gov/components/form/memorable-date#default) has V1 and V3 and [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default) does not mention a version. I would suggest labeling every version and adding the most current to each file.

**Comment by caw310** [comment] 2023-10-11 14:53
This is a duplicate of 64200 (https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/64201) so closing.

**Closed by caw310** 2023-10-11 14:53 UTC
Labels: design, platform-design-system-team, DS-Staging-Review
