### ISSUE TITLE
GFE IE11 Console errors on sign-in page due to Compatibility View 

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#15517] opened 2020-10-28 18:30 UTC
## What happened?
Console errors on GFE IE11

## Specs:
- Device: GFE Windows 10 Laptop
- Browser: IE 11
- Test User: n/a

## Steps to Reproduce
1. Go to https://www.va.gov/sign-in/
1. Open developer tools (F12)
1. Script errors

---
![image](https://user-images.githubusercontent.com/63597655/97480743-39902180-192a-11eb-990e-ae50cfb4eed8.png)

---
![image](https://user-images.githubusercontent.com/63597655/97480755-3eed6c00-192a-11eb-8cbe-2fc33bb93ecb.png)

---
![image](https://user-images.githubusercontent.com/63597655/97480771-43b22000-192a-11eb-8304-f3a45c96e11f.png)

## Desired behavior
No script errors, maybe configure GFE IE11 to not use compatibility view?

## Acceptance Criteria
- [ ] No script errors on GFE IE11

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mchelen-gov** [comment] 2020-10-28 18:35
still get 1 of the errors with compat view disabled

![image](https://user-images.githubusercontent.com/63597655/97481229-dfdc2700-192a-11eb-97e3-67c08d20718c.png)

**Comment by mchelen-gov** [comment] 2020-10-28 18:41
IE11 user agent string with compatibility view disabled:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; Trident/7.0; rv:11.0) like Gecko`

`window.navigator.userAgent` =
`"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Zoom 3.6.0; wbx 1.0.0; wbxapp 1.0.0; rv:11.0) like Gecko"`

**Comment by AGarcia-Clarity** [comment] 2021-08-16 20:07
@joeniquette I'm going to verify this is not still happening, if it isn't we can close it.

**Comment by AGarcia-Clarity** [comment] 2021-08-17 16:15
Update:
- The `Syntax error: sign-in` no longer displays in Compatibility view in IE11 ✅ 
- The `XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013` still occurs however this is a known issue with IE11 running on Windows 10.  (Most likely caused by HTTP/2 requests Google Analytics is  making).

**Closed by AGarcia-Clarity** 2021-08-17 16:15 UTC
Labels: bug, Identity, Cerner-patient, Cerner-MHV-patient
