### ISSUE TITLE
[FSR] Decommission duplicated fsr service code.

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#66650] opened 2023-09-29 17:55 UTC
The debts-api module has been working in production for multiple sprints. It's time to remove the old namespace code that is no longer being referenced by anything.

**Comment by HeatherRienks** [comment] 2023-10-04 17:54
closing -this is a duplicate of xxx

**Closed by HeatherRienks** 2023-10-04 17:54 UTC
Labels: backend, vsa-debt, FSR Enhancements
