### ISSUE TITLE
Redirect Request - VAMC - VA Altoona health care

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26201] opened 2021-06-16 18:17 UTC
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
VHA Digital Media and VA Altoona health care have approved moving VA Altoona health care from dual state to full production, which includes redirecting traffic from TeamSite to new VAMC - System website. 
** Set URL redirect for June 30th, 2021 **
Requesting that Current URLs be redirect for primary URLs listed below and that all remaining URLs under the root URL to be redirected to new VAMC - Website URLs.

### Requesting team info
VAMC - upgrade team - Stan Gardner - sgardner@governmencio.com
[vsa-vamc-upgrade Slack Channel](https://dsva.slack.com/archives/CPQFCQKEH) 

### Implementation date
**June 30th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday June 30th, 2021

Please indicate when the change/redirect(s) needs to be implemented"
**June 30th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday June 30th, 2021
- Redirect can occur at start of day so site can be validated and tested. 

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.altoona.va.gov/ | https://www.va.gov/altoona-health-care/
https://www.altoona.va.gov/locations/directions.asp | https://www.va.gov/altoona-health-care/locations/james-e-van-zandt-veterans-administration-medical-center/
https://www.altoona.va.gov/locations/DuBois.asp | https://www.va.gov/altoona-health-care/locations/dubois-va-clinic/
https://www.altoona.va.gov/locations/Huntingdon_VA_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/altoona-health-care/locations/huntingdon-county-va-clinic/
https://www.altoona.va.gov/locations/Indiana_VA_Outpatient_Clinic.asp | https://www.va.gov/altoona-health-care/locations/indiana-county-va-clinic/
https://www.altoona.va.gov/locations/Johnstown.asp | https://www.va.gov/altoona-health-care/locations/johnstown-va-clinic/
https://www.altoona.va.gov/locations/StateCollege.asp | https://www.va.gov/altoona-health-care/locations/state-college-va-clinic/
https://www.altoona.va.gov/services/covid-19-vaccines.asp | ~~https://www.va.gov/altoona-health-care/health-services/covid-19-vaccines/~~  New: https://www.va.gov/altoona-health-care/programs/covid-19-vaccines/
**All remaining URLs under root** https://www.altoona.va.gov/   |https://www.va.gov/altoona-health-care/ 

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [ ] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [ ] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment] 2021-06-16 21:44
@SgardnerPMP Is this a duplicate of #26200?

**Comment by mnorthuis** [comment] 2021-06-23 13:06
@SgardnerPMP @mmiddaugh this is a duplicate request. Please correct information if it is incorrect, or close the issue if it was a mistake.  Thank you!

**Comment by SgardnerPMP** [comment] 2021-06-25 15:56
Menus have been updated.

**Closed** 2021-09-22 03:07 UTC
Labels: VAMC-Upgrade
