### ISSUE TITLE
Update 526EZ mural journey map to be the 527EZ journey map

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#78073] opened 2024-03-11 20:22 UTC

**Comment by djones2113** [comment] 2024-04-18 20:17
FYI this looks to be a duplicate of #79864

**Comment by aplatt-coforma** [comment] 2024-04-19 20:36
Thanks for pointing this out @djones2113. Closing this one.

**Closed** 2024-04-19 20:35 UTC
Labels: research, pension
