### ISSUE TITLE
[FRONT-END] Save-In-Progress Bug (Inflection Header)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#17411] opened 2020-12-14 16:48 UTC
This is the front-end ticket. [Here's the back-end ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17595)

**For a more complete description of the bug, [see the back-end ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17595)**

## Acceptance Criteria

- [x] provide a way for a form to opt-out of sending the inflection header
- [x] stop sending the inflection header for _Form 526 family_ forms

**Comment by ndsprinkle** [comment] 2020-12-14 17:47
@Mottie @edmangimelli @annaswims This is what we met about this morning, correct? The original disability names contained "(at c4-c5 and c4-c3)" but were changed to "(at c4C5 and c4C3)"? Are we cool to just block users from entering dashes for now (until platform gives us a better solution) or did we have a better temporary solution?

**Comment by ndsprinkle** [comment] 2020-12-14 17:56
Because it's actually becoming "(at c4_c5 and c4_c3)" in the back end and then the conversion from snake case to camel case happens and the dashes are lost?

The only issues I can see with restricting dashes for now (Robin originally mentioned this) is that our official disabilities list contains lots of disabilities with dashes: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/content/disabilityLabels.js

A lot of those disabilities with dashes are in this format " - " where there are spaces on both sides of the dashes. Would those get messed up in the same way that disabilities with dashes next to letters do?

Here's an example of both a dash with spaces on both side and a dash with a letter on both sides in the same disability: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/content/disabilityLabels.js#L564

**Comment by Mottie** [comment] 2020-12-14 18:35
The problem is that this also applies to `ratedDisabilities`... they may include dashes and or commas, and we must submit them exactly as provided or EVSS will reject them.

**Comment by annaswims** [comment] 2020-12-14 18:38
This issue is a continuation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/15368

**Comment by ndsprinkle** [comment] 2020-12-16 14:35
@Mottie Absolutely true about rated disabilities, and that's honestly a much more widespread issue than the treatment center disabilities. I know it's just a band-aid, but for now through the holidays I am just going to slap the no special characters restriction on new disabilities. @annaswims Do I need to just say no to dashes or are there others that cause issues? In addition to adding that restriction on the new disabilities field, I am going to adjust our `disabilityLabels` list I reference above to not have the special characters. I will make a back up of our current list.

**Comment by edmangimelli** [comment] 2021-01-04 15:30
While @Mottie and @ndsprinkle were out, discussed this problem with the Forms team engineers (@cvalarida @bkjohnson). We all agreed that tweaking the platform code so that some forms can optionally _not_ send the inflection header would be the best way to go. The Forms team has a lot of ticket ahead of this one, and is hoping that BAM1 could tackle it with their guidance.

**Comment by ndsprinkle** [comment] 2021-01-04 16:27
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/15517

Fingers crossed

**Comment by edmangimelli** [comment] 2021-01-04 17:50
Old description:

## Bug Description
In certain cases, we are having errors saving disabilities through EVSS that have some special characters.

`“form526.treatments.treatedDisabilityNames.isInvalidValue: The disability name cervical adjacent level disease (at c4C5 and c4C3) does not match any disability name from your list of disabilities”:
“form526.treatments.treatedDisabilityNames.isInvalidValue: The disability name cancer pancreas (mass):: esophageal cancer does not match any disability name from your list of disabilities”:`

## Expected Behavior
These errors do not occur, and therefore we need to remove them from the submissions.

**Comment by edmangimelli** [comment] 2021-01-04 17:51
blocking PR until BE PR is merged

**Comment by annaswims** [comment] 2021-02-11 20:53
Validated.  Last `form526.treatments.treatedDisabilityNames.isInvalidValue`  error was on 1/14

**Closed by annaswims** 2021-02-11 20:53 UTC
Labels: 526, SIP inflection bug, bug, development, frontend, sitewide, vsa, vsa-benefits
