### ISSUE TITLE
Facility Locator and Urgent Care searches

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1961] opened 2019-09-23 14:21 UTC
As of this work - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1499 - users can now search for Urgent Care and Retail Pharmacies from a Community Cares search. However, we still have come messaging on the Facility Locator that somewhat suggests that you still need to leave the website to do one of these searches. These should be updated so that the user knows this is something that can be done from va.gov now.

1. Message above search box
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/9df7d900-9c2a-4a37-b277-a96ab2ee767a)

1. Error messaging
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/11cafcff-374d-4e2e-bf45-9e4e368ed283)

**Comment by ncksllvn** [comment] 2019-09-23 14:23
@chrisj-usds @jenniferlee-dsva thoughts on this one? Maybe it should go to content first?

CC: @Karak888

**Comment by Karak888** [comment] 2019-09-25 18:11
@jenniferlee-dsva  will follow up to see if that haven't had any data issues we will move forward with updating the messaging.

**Comment by jenniferlee-dsva** [comment] 2019-09-25 20:05
Pending stakeholder confirmation. Email comms and notes pasted below. @ncksllvn re your note ^ - If we're just removing that paragraph of text, not sure we need to say anything. I don't have the full history though, so let's talk when this gets worked on. IF text is needed, yes, can def assign to content team first. 


From: Lee, Jennifer Y. 
Sent: Wednesday, September 25, 2019 3:45 PM
To: Rollins, Aszur <Aszur.Rollins@va.gov>
Cc: Johnston, Christopher M. <Christopher.Johnston2@va.gov>; Benitez, Nora G. <Nora.Benitez@va.gov>; Triebenbacher, Pauline <Pauline.Triebenbacher@va.gov>; Amanda Villa (Amanda.Villa@va.gov) <Amanda.Villa@va.gov>; Cizmadia, Peter R. <Peter.Cizmadia@va.gov>; Johnson, Michael A. (OCC) <Michael.Johnsonc12c7@va.gov>; Sharma, Amit (Trilogy) <Amit.Sharma@va.gov>
Subject: RE: Facility Locator updates and introduction

Thank you for answering my questions to better understand the in/out of network topic. I’ll send out another call to continue what we started. 

Just wanted to provide a quick summary of our call. 

Facility locator, per PPMS data fix, is now pulling PPMS urgent care data:
•	Aszur and team raised a flag that PPMS data was not validated by the CC team, so will check and let us know if we need to revert this. 
•	Important note: The FL page continues to link to the TriWest locator, so Veterans still have access to that path. 
•	We will not remove this TriWest link and update on-page messaging until we hear from you that the data is okay. This next task is tracked in this GitHub ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1961
•	
Better communications:
•	Jen will work with the development team to come up with a forum and cadence for more regular check-ins. 
•	Aszur has been our team’s POC, but we can also include other key individuals – from PPMS? – if needed. 


In vs. out of network – clarification:
(Please feel free add/correct/clarify below if I misunderstood anything.)
•	There are 6 CCN (community care network) regions – 1 – 6. All providers in any of these 6 regions are in the VA network of approved providers. 
•	There’s another level of ‘in’ vs. ‘out’ of network, and that is from the Veteran’s POV. EX: The Veteran may be in region 1; so technically, the providers in the other regions are ‘out’ of the Veteran’s assigned network. 
•	In the scenario where a Veteran lives in region 1 and the closest geographical provider, for instance for urgent care,  is in a different region, say, the bordering region 2:  the Veteran may use the provider in region 2 (technically outside of their assigned region, but still within VA network), and VA will reimburse for that service. Caveat: the Veteran may need to fill out or provide additional information or forms. 
•	We believe that veterans do receive information about what CCN they belong to via communications, but we don’t know exactly what or from which team it comes from. (Possibly a number of communications, via email, letter?)

Qs for next call:

•	Does the Veteran need to get pre-authorization before using a community care provider who is in (their) network? 
•	Does the Veteran need to get pre-authorization before using a community care provider who is out of (their) network, but still in VA network? 
•	If the provider is in their network, can they make an appointment directly? (I.e., how would they act on this information)
•	RE contractual requirements for providing network info.

**Comment by chrisj-usds** [comment] 2019-09-25 23:49
RE: the messaging and links to Tri-west. I think there are a few steps in that work: 

1/ Ensure that the urgent care data in PPMS is correct. (I believe we're still waiting on the OCC team for confirmation)

2/ Remove the message above the search box that links to Tri-west. *

OCC suggested (and I concur) that this be replaced with some simple instructions on how to search for urgent care and retail pharmacy location. It's not necessarily obvious what to type into the "service type" box. 

Another idea is to replace the example searches in that box with those examples? (Cardiology is a terrible example, fwiw).  

3/ Future: improve the list of services available in "service type". 
That is currently a type ahead of what appears to be a list of thousands of possible services in PPMS. 
Again, perhaps for the future (unless it's easy now) would be to try to map those to the Health Care Service Taxonomy that was done as part of the Pittsburgh VAMC redesign.

**Comment by jenniferlee-dsva** [comment] 2019-09-26 13:19
Second what Chris said here: "Another idea is to replace the example searches in that box with those examples? (Cardiology is a terrible example, fwiw)"  - in lieu of instructional text. (More sense to test with less text, and then add if we need to.)

**Comment by jenniferlee-dsva** [comment] 2019-10-08 15:18
@Chris - RE messaging, want to make sure I understand. See screenshot. FYI - Kara is looking into whether we can make this messaging update in staging, so we can share with Aszur et al. And send it to them with - 'let us know when you'd like this change to go live.'

1/ Need same-day care for a minor illness or injury? Select VA Health or Community Care (Non-VA Health) from the dropdown menu. Then select or enter urgent care as the service type. 

2/ Inside service type field, replace "Like primary care, cardiology" with "Like urgent care"

3/ Remove the link below search fields (and above the map): "Find VA-approved urgent care locations and pharmacies near you" 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/fda40d98-9497-4a79-b0c5-8c83c8efe8f4)

**Comment by Karak888** [comment] 2019-10-09 18:06
@ncksllvn did say staging would be possible, he just needs to review ticket. @jenniferlee-dsva to follow-up with @chrisj-usds

**Comment by jenniferlee-dsva** [comment] 2019-10-09 21:32
@Karak888 @ncksllvn - followed up, @chrisj-usds is okay to go forward in staging. Caveat: just as long as staging doesn't go straight to prod -- will have to hold back until stakeholder ok.

**Comment by Karak888** [comment] 2019-10-14 15:44
so @ncksllvn just to confirm this work should go to staging and please KEEP the link to Tri-West- I am referencing the ticket so you have latest information.  Thank you! cc:  @jenniferlee-dsva @chrisj-usds 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/1519#issuecomment-540101781

**Comment by Karak888** [comment] 2019-10-16 17:43
@ncksllvn @jenniferlee-dsva will be meeting with client tomorrow , and didn't know if getting this to be ready by then?   If no that's fine, please just let us know! thanks!

**Comment by jenniferlee-dsva** [comment] 2019-10-16 20:32
Chris and I met with Aszure and team. They confirmed there are some data discrepancies between the Tri-West, Facility Locator, and PPMS location results. 

Conclusion: 
Do not remove Tri-West link or update messaging for now. 

Next step:
- They're sending over the spreadsheet with examples of discrepancies. 
- We'll need to take a closer look at the specific fields that aren't quite mapping and suggest a new/updated rubric or schema of fields for displaying. 
- **Really important:** When we update this schema in the FL, we need to share update in staging, so Aszure and team can do their own testing before going live. 

Other important learnings:
- PPMS will include providers that are in VA network and also those that are "out" of VA network. 
- Veterans can still see "out" of VA network providers, but just like for appointments with "in" VA network providers, they have to call their primary care dr/team to get a referral.  
- VA will reimburse "out" of VA network providers but this isn't something the Veteran is involved with. 
- The value for this info is still mostly internal facing. 
- There may be a scenario at the provider level where this might be useful info (but actually I'm still not sure about that, so I think I need to sync with Chris on this.)

**Comment by Karak888** [comment] 2019-10-28 14:12
[PPMS Results Testing_092319_ (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3779031/PPMS.Results.Testing_092319_.1.xlsx)
@jenniferlee-dsva @davidconlon @mmiddaugh 

This is the file with the data discrepncies.  I don't know where it went, but this is the one!

**Comment by jenniferlee-dsva** [comment] 2019-10-28 20:00
Conclusion re in vs. out of network – we are not including this data in the FL, per Dr. Kameron Matthews call. 

Show Provider Network [WILL NOT DO]
Office of Comm. Care has asked for this database field to be shown in provider result. Supposedly we're contractually required.
Unclear if there is any actual user value here. [ IT IS NOT]

**Comment by mmiddaugh** [comment] 2019-11-01 18:53
Converting this to an epic so we can breakdown the various tasks that need to be done as part of this effort while keeping the excellent history.

**Comment by ncksllvn** [comment] 2019-11-04 16:39
Hey all, just an FYI that no work has been done on this in Staging. It was planned to be, but paused after data issues were discovered. A quick history on this -

When the Community Cares searches were first added to the Facility Locator, we found that there were issues with the data for the Urgent Care and Retail Pharmacies service types (the second input after changing `Search for` to Community Cares.) So, those service types were excluded by the API as options. We added this message for users interested in searching for those service types - 
![image](https://user-images.githubusercontent.com/1915775/68138824-21dcb380-fef7-11e9-8b3d-cb0790a0ab1f.png)


However, the data was then said to be fixed. So, we stopped excluding those service types from our API. Since those service types are now available here, it seemed like we should update that message shown in the screenshot above.

However, it turns out that there are still some data issues as noted here, so we're leaving the message as-is, so that users can use the link to get the most reliable data (I'm assuming here.)

 The original intent of this ticket was simply to update that message, but it was written under the assumption that there were no longer any data issues. So, the scope of this has definitely increased from probably a `1` to an `8` or so, since there is now discovery mixed in.

**Comment by mmiddaugh** [comment] 2019-11-07 19:58
@davidconlon @arickalewis1 based on my review of some old issues, I have questions about the intended results from urgent care and emergency locations, including:
- If a VAMC facility offers urgent and/or emergency care, should the Facility Locator return the location along with the TriCare (and future optum) locations?
- Should this type of location be differentiated from those in the TriCare/Optum network during the search or display? 
- Is the intermediate Benefits page relevant for those VAMC urgent/emergency care locations?

**Comment by mmiddaugh** [comment] 2019-11-08 00:49
Also leaving this comment for @davidconlon and @arickalewis1 , related to the comment above and to current functionality, let's remember to consider naming conventions as part of this redesign. 

We know that Community Care locations have **provider** rather than **facility** names. But here's something I found recently: 

![emergency hfh](https://user-images.githubusercontent.com/55411834/68439672-4ea1fc80-017d-11ea-8761-40a999e9036e.png)

I searched for **emergency** as a service type for Community Care. The highlighted result is actually a **hospital** and is returned repeatedly under different **provider** names. 

I think facilities need to be identified by the Facility name, not the provider name (or in addition to). Finding the destination will be much easier if we give Veterans information consistent with the name of the practice or building, especially for urgent and emergency care.

**Comment by davidconlon** [comment] 2019-12-12 14:17
Because there is a pending deadline now of 2/1 and TriWest is putting pressure to try to keep their locator, there are certain things we need to do as MVP for 2/1 that we can iterate/improve on later.

1. Make sure we can query Vets-API/PPMS to differentiate between Place of Service (PoS) Pharmacy (01),  Urgent Care Walk-In Retail (17), Urgent Care (20) for In-Network
2. Provide a means for the veteran to select and/or filter according to that above Place of Service codes (based on research, is this in the dropdown, dropdown plus filter, what gets us to MVP and can iterate without painting ourselves into a corner?)
3. Remove "Referral" language from the cards and detail pages for Urgent Care Walk-In Retail (17) and Urgent Care (20) _unsure about Pharmacy, Dave to check with OCC_
4. Add link to PDF (forthcoming from OCC, pending testing) to site (card? detail? both?)
5. Provide a means for users to understand the difference between Walk-In Retail Urgent Care and Urgent Care
6. Make sure Veteran understands specifics around Urgent Care Pharmacy Prescriptions

JR Ruble is running point and keeping pressure on items that need to be completed but are not on our dance card, but instead on PPMS/TriWest/Optum:
1. Completion of PDF (for us to test)
2. Proper input of data into PPMS by TriWest & Optum to resolve Facility names matching, Facility PoS code correction
3. Benefit Page

**Comment by mmiddaugh** [comment] 2019-12-31 20:08
Linked for reference in [#4200] so this backstory/history is not lost. 
Otherwise, this work has been broken down into other issues.
Closing as duplicate.

**Closed by mmiddaugh** 2019-12-31 20:08 UTC
Labels: Epic, facility locator, vsa-facilities
