### ISSUE TITLE
[Research] Implement VAOS custom events to GA4

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57623] opened 2023-04-28 16:19 UTC
## Request
Our team is looking for assistance from the Analytics team to start implementing the appointment events to GA4. 

### Goal
Implement VAOS events to Google Analytics 4

### Requirements to Consider
We will start with the following custom events: 

1. `vaos-cancel-appointment-submission`
2. `vaos-cancel-booked-clicked`
3.  `vaos-direct-path-started`
4. `vaos-direct-submission`
5.  `vaos-eligibility-direct-check-past-visits-failed `

---

## Tasks
- Answer the following questions:
  - Q1: How should the VAOS team code the events for Google Analytics 4

## Reference 
- Our team did an analysis of the events for appointments. Here's the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57623) for reference. 

## Definition of Done
- Tasks are complete

---

**Comment by michelle-dooley** [comment] 2023-05-09 17:07
@ldelacosta - I would like to run a test.  Can you add this to the data layer code and then I will see how it flows in GA. 

The only required fields are "event" and "action".  All other fields are optional so you can decide if you want to use (if you do not then just remove that line from the code)

Note the following click parameters are auto collected (do not need to add to you DL code):
click text, click target, click element, click ID, click URL and click class.

{ 
event: 'interaction',
action:  'vaos-cancel-booked-clicked'
custom_string_1: '<custom_string_1>',
custom_string_2: '<custom_string_2>',
custom_number_1: <custom_number_1>,
custom_number_2: <custom_number_2>,
selected: '<selected>',
status: <status>,
previous_value: '<previous_value>',
value: '<value>',
selected: '<selected>',
type: '<type>',
required: '<required>',
heading_1: <heading_1>,
heading_2: <heading_2>,
component_name: <component_name>,
component_version: <component_version>
}

{ 
event: 'interaction',
action:  'vaos-cancel-appointment-submission'
custom_string_1: '<custom_string_1>',
custom_string_2: '<custom_string_2>',
custom_number_1: <custom_number_1>,
custom_number_2: <custom_number_2>,
selected: '<selected>',
status: <status>,
previous_value: '<previous_value>',
value: '<value>',
selected: '<selected>',
type: '<type>',
required: '<required>',
heading_1: <heading_1>,
heading_2: <heading_2>,
component_name: <component_name>,
component_version: <component_version>
}

**Comment by ldelacosta** [comment] 2023-05-10 17:16
Thanks @michelle-dooley. We are meeting with the team tomorrow to discuss. Will let you know when we could get this done or if we have any questions. Thanks!

**Comment by jenniemc** [comment] 2023-05-12 20:44
**vaos-cancel-appointment-submission**: This event requires interaction with a button click. The event name will display additional information about the type of cancel appointment such as pending or confirmed, cc or va appointment

> const eventPrefix = `${GA_PREFIX}-cancel-appointment-submission`;
> async function cancelV2Appointment(appointment, useAcheron) {
>   const additionalEventData = {
>     appointmentType:
>       appointment.status === APPOINTMENT_STATUS.proposed
>         ? 'pending'
>         : 'confirmed',
>     facilityType: appointment.vaos?.isCommunityCare ? 'cc' : 'va',
>   };
> 
>   recordEvent({
>     event: eventPrefix,
>     ...additionalEventData,
>   });

**vaos-cancel-booked-clicked**: This event requires interaction with a button click.

> onClick={() => {
>   recordEvent({
>     event: `${GA_PREFIX}-cancel-booked-clicked`,
>   });

**vaos-direct-path-started**: This event requires interaction with a button click. There are 2 triggers to this event. First at the facility page when the user clicks 'continue' which calls on the `startDirectScheduleFlow` and again at the clinic page when the user clicks 'continue' that also calls on `startDirectScheduleFlow`. Hence this event triggers twice in the same DS flow. (Suggest removing the trigger in the facility page for accuracy).

> export function startDirectScheduleFlow() {
>   recordEvent({ event: 'vaos-direct-path-started' });

**vaos-direct-submission**: This event requires interaction with a button click. This event name will show additional information such as type of care and reason for appointment

> if (newAppointment.flowType === FLOW_TYPES.DIRECT) {
>       const flow = GA_FLOWS.DIRECT;
>       recordEvent({
>         event: `${GA_PREFIX}-direct-submission`,
>         flow,
>         ...additionalEventData,
>       });

**vaos-eligibility-direct-check-past-visits-failed**: This event requires interaction with a button click in the facility page that will then call the eligibility api. The event name will show additional information such as type of care and facilityID.

> export function recordEligibilityFailure(
>   errorKey,
>   typeOfCare = null,
>   facilityId = null,
> ) {
>   recordEvent({
>     event: `vaos-eligibility${errorKey ? `-${errorKey}` : ''}-failed`,
>     'health-TypeOfCare': typeOfCare,
>     'health-FacilityID': facilityId,
>   });
> }

cc: @ldelacosta, @simiadebowale

**Comment by ldelacosta** [comment] 2023-05-18 15:15
@michelle-dooley - We have made the code updates. Please let us know if you have any questions or run into any issues. Thanks!

**Comment by ldelacosta** [comment] 2023-05-18 21:45
@michelle-dooley - I'm glad one of them worked! Let me double check. It should be for all 5 events. I'll keep you posted.

**Comment by michelle-dooley** [comment] 2023-05-19 13:44
@ldelacosta - To clarify I was only able to find/recreate cancel-appointment-submission and cancel-booked-clicked.  cancel-booked-clicked is working.  I am not seeing anything in GA4 for cancel-appointment-submission.

I have not been able to figure out how to recreate/walk through the flow to see the others (direct-path-started, direct-submission, and eligibility-direct-check-past-visits-failed).  Can you tell me what/where I need to go to trigger those events so I can test those too?

**Comment by ldelacosta** [comment] 2023-05-19 15:57
@michelle-dooley - We'll need to re-review the code changes from the developer. 

- For `direct-path-started`, this event triggers when the user is able to select a Facility followed by a clinic in the flow. It is a 2 part event. 
- For `direct-submission`, this event happens when user schedules the appointment 
- For `eligibility-direct-check-past-visits-failed`, this event triggers when the user did not have any past visits at the facility (would need to find a user that meets this criteria). 

I'll let you know when we have completed our review so that we can re-test. Thanks!

**Comment by michelle-dooley** [comment] 2023-05-30 16:55
@ldelacosta - I was not able to re-create each of those myself but I do see them showing up in reports.  However the numbers do not match what I am seeing current UA reports so not sure what is going on there?!?!  We can discuss when we meet in a bit.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/1dd285be-0658-4255-88eb-0a92faf0d315)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/bd379cfd-9956-46b0-9e05-33616b4a4ced)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/4bd00f0e-1f03-4420-a459-04301051e4e9)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/628cff13-c3ba-4323-8532-a1c483fe72cf)

**Comment by ldelacosta** [comment] 2023-06-05 23:04
Hi @michelle-dooley. We recently made some code changes in staging. Could you please verify if things look OK on your end? cc: @JRRoof

**Comment by JRRoof** [comment] 2023-06-06 15:26
Seeing custom strings come through now.

@michelle-dooley - Engineering says they will eventually need 5 custom strings all together.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/06f926d8-8d4b-4029-91c0-9c783dd466b4)

**Comment by JRRoof** [comment] 2023-06-07 16:45
@michelle-dooley - Not sure the modifications we made to events stopped them from being recorded in UA.  Can we meet and look at this in more detail?  We may need to create different names for events in UA and GA4.

**Comment by michelle-dooley** [comment] 2023-06-09 12:46
@JRRoof - yes we can meet.  You shouldn't of turned anything off just added the GA4 tracking code same places you have the UA code.

**Comment by michelle-dooley** [comment] 2023-08-30 13:21
@ldelacosta and @JRRoof - with our new GA Specialist @jestutt we are reviewing the current implementation and next steps.  There is some work that still needs to be done with web components that we need to complete before we can complete custom work.  I am going to move this to backlog for now but will pick back up as soon as we can once the core config work is complete.

**Comment by ldelacosta** [comment] 2023-09-11 21:12
@michelle-dooley @jestutt  - thanks for the info! We added a feature toggle for migrating our events to GA4.

**Comment by michelle-dooley** [comment] 2024-01-17 17:01
I'm going to close this ticket since things have changed since this time. @jestutt will work with you to create new tickets as part of the GA4 migration, more to come.

**Closed** 2024-01-17 17:02 UTC
Labels: analytics-insights, analytics-request, spike, appointments-product-design
