### ISSUE TITLE
[Bug] Unable to update a user's profile address in Review Instances

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20021] opened 2021-02-16 17:00 UTC
**User Story**
We (vsa-caregivers team) are not able to update users' profiles in the RI environment (due to some kind of bug or unsupported feature in RI env). When updating a profile, changes aren't saved. So in order to test certain scenarios (like form prefill), we have to find users with the profile structure that you need (versus updating a user's profile to be in the structure you need).

https://user-images.githubusercontent.com/7391284/107408175-9d54e980-6ad8-11eb-97e0-7761992b57c9.mov

**Comment by kevinmirc** [comment] 2021-02-19 14:36
This created a blocker during our testing on [January 19, 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/use-cases.md#team-testing) and [February 18, 2021](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18969#issuecomment-781547169) which forced us to merge our code and conduct testing in staging with the risk that the code would be promoted to production without thorough testing.

**Comment by kevinmirc** [comment] 2021-02-22 21:27
This was a blocker for our QA session on [February 22, 2021](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18969#issuecomment-783529416)

**Comment by mlighdc** [comment] 2021-05-28 02:49
@kevinmirc has this been communicated to Platform and should it be assigned to them? Or has this been resolved since it happens in RI?

**Comment by tchrisdyer** [comment] 2021-06-09 14:50
Justin confirmed that the review instances are mocked on profile updates, so this is working as designed. Closing.

**Closed** 2021-06-09 14:50 UTC
Labels: vsa-caregiver, vsa-hca
