### ISSUE TITLE
Researching Pager Duty Incidents API

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#18516] opened 2021-01-13 19:11 UTC
As part of this ticket I would like to see an RFC style write-up of what an integration with Pager Duty incidents API on vets-api would look like. Currently there is only an integration on vets-api with the maintenance window API.

As part of this research, we should evaluate what the capabilities of the API are.
Additionally we should cement an understanding on how a new incident can be captured using Prometheus / StatsD.

**Comment by laurenernest** [comment] 2021-01-14 22:47
Dupe of #18515

**Closed by laurenernest** 2021-01-14 22:47 UTC
Labels: backend, needs-grooming, vaos
