### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#98207] opened 2024-12-03 18:23 UTC
## User story

As a Veteran ordering medical device supplies, I would like to be able to know that the correct Contact Information is auto-filled for my Order and if not, that I am able to correct it.

## User flow/Possible-tasks

- Veteran is starting a new order and contact information is loaded from the API response
- Veteran is continuing an order and contact information is prefilled from existing order
- Veteran updates the email address
-  Veterans updates the shipping address
    

    - [ ] Addresses need to be validated and be able to include APO, etc. 

- Veteran wants to finish the order later
  

     - [ ]   Save off the form data (built-in to the form platform)
     - [ ]     Need to verify the in progress order is saved to the Veteran's profile (I believe this is built-in to the forms platform)

- Form selections are automatically saved
   

    - [ ]   Verify forms are autosaved as data is filled in/changed

**Comment by radavis** [comment] 2024-12-12 21:27
Duplicate of #96505

**Closed by radavis** 2024-12-12 21:27 UTC
