### ISSUE TITLE
Spike - Notification of Appointment

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13394] opened 2020-09-10 15:12 UTC
After a trigger is received from VeText or somewhere indicating that an appointment has been booked then events need to occur to cause the clipboard to be viewable with pertinent information as needed

## Tasks
- [ ] create final document with diagram

## Acceptance Criteria

- [ ] Document written and reviewed

**Comment by massrb** [comment] 2020-09-10 15:19
Added SMS based trigger concept

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/trigger.md

**Comment by massrb** [comment] 2020-09-10 15:26
Stephen Barrs mentioned this which is to be expected, this means that doing the same thing that VeText does would not be possible as that application is part of an internal infrastructure that vets-api is outside of : 

>> VetText has a custom Weblogic based implementation of VistaLink (I think thats the one) that lets them integrate with all Vistas. we def dont want to stand up our own VistALink

**Comment by abuckley3385** [comment] 2020-09-11 19:39
Hey guys - I didn't' notice this ticket was pulled into this sprint.- We committed to #11345 and we discussed in Tech meeting the different in Questionnaire Trigger and our VetText notification being separate work. @massrb  can you clarify why this is being worked on in this sprint?

**Comment by massrb** [comment] 2020-09-14 12:40
Sorry, there was confusion about notifications and triggers because the diagram was actually about triggers even though it may have sounded like it was not but I understand now what caused the confusion. That diagram will need to be changed after we talk with Stephen and Shane Elliot

**Comment by mdewey** [comment] 2020-11-30 20:27
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/13145

closing

**Closed by mdewey** 2020-11-30 20:27 UTC
Labels: backend, vsa-healthcare-exp
