### ISSUE TITLE
[Development] HLR: Analytics Prep

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#9861] opened 2020-06-04 21:41 UTC
## Issue Description
Edit front-end JS to capture the events already worked with VSP.

There was work done by Kevin and John Wehausen

## Acceptance Criteria
- [ ] Make sure what we agreed to with VSP is captured in the JS tags

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment] 2020-07-01 19:58
Related to/duplicate of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3825

**Closed** 2020-07-08 15:54 UTC
Labels: HLR, frontend, vsa-benefits
