### ISSUE TITLE
Practitioner Name No Longer Shows for Comm Care Cancelled Appointment Request

### ISSUE THREAD

**Issue by CielitoBates** [department-of-veterans-affairs/va.gov-team#83900] opened 2024-05-23 19:55 UTC
## Summary
When a community care appointment is cancelled, the preferred community care provider no longer shows up as selected.

## Specs
- Device: 
- Browser: 

## Steps to Reproduce

1. Create a CC request with a preferred provider selected.
2. Cancel the CC request.

### Actual Result
Observe the Preferred community care provider field change from the selected provider name to "No provider selected". See attached screenshot.

![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/125504932/0703c9f3-c715-41d9-8c8a-5352ea06f63e)

### Desired Result
Preferred provider appears.

## Definition of Done

- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by CielitoBates** [comment] 2024-05-23 20:06
Test user was brienne.b.ferrara@id.me

**Comment by mshatalov-va** [comment] 2024-05-23 20:35
Steps to reproduce:

1. Login as CC eligible user (we used brienne.b.ferrara@id.me)
2. Navigate to https://staging.va.gov/my-health/appointments/?postLogin=true
3. Select Start Scheduling
4. Select Podiatry  and click Continue
5. Select desired date and time and click Continue
6. Select Provider, by Location = Dayton, OH
7. Select Preferred provider  and click Continue
8. Select preferred  and enter comments if desired.   click Continue
9. Enter phone number, email and  best time to call. click Continue
10. on the Review Request summary screen validate the preferred provider info to compare to results later.
11. Click submit
12. Validate the results show the correct preferred provider
13. Navigate back to Pending appointments and select the newly created request
14. validate the preferred provider info
15. Click cancel request and confirm
16. Observe the preferred provider change to "No provider selected"
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/157733536/a8747a64-e596-4aa4-af8b-b32116cbaef6)

**Comment by simiadebowale** [comment] 2024-05-24 20:20
It looks likes we are not getting the `preferredProviderName` field on cancelled cc requests. Can we check to confirm if this assumption is accurate? 
cc: @cferris32 @ajmagdub @ldelacosta

**Comment by jenniemc** [comment] 2024-06-24 17:12
@ldelacosta , this is the object returned from a CC request. FE relies on `preferredProviderName` to display the provider name. In this case, "WILLIAMS, CAROL" is the provider
```
{
    "id": "1a7918b7b7f1dceb5fcc2e149b2a578951bf2ea44e58338f2f9306c1793ad810",
    "type": "appointments",
    "attributes": {
        "id": "1a7918b7b7f1dceb5fcc2e149b2a578951bf2ea44e58338f2f9306c1793ad810",
        "identifier": [
            {
                "system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
                "value": "15884"
            }
        ],
        "kind": "cc",
        "status": "proposed",
        "serviceType": "foodAndNutrition",
        "serviceTypes": [
            {
                "text": "foodAndNutrition"
            }
        ],
        "reasonCode": {
            "text": "smoke test 2.39.2 fix"
        },
        "patientIcn": "1013124304V115761",
        "locationId": "984",
        "practitioners": [
            {
                "identifier": [
                    {
                        "system": "http://hl7.org/fhir/sid/us-npi",
                        "value": "1487085270"
                    }
                ],
                "address": {
                    "type": "physical",
                    "line": [
                        "1960 N Ogden St Ste 460"
                    ],
                    "city": "Denver",
                    "state": "CO",
                    "postalCode": "80218",
                    "text": "1960 N Ogden St Ste 460,Denver,CO,80218"
                }
            }
        ],
        "created": "2024-04-02T15:30:00Z",
        "requestedPeriods": [
            {
                "start": "2024-04-26T16:00:00Z",
                "localStartTime": "2024-04-26T12:00:00.000-04:00"
            }
        ],
        "contact": {
            "telecom": [
                {
                    "type": "phone",
                    "value": "7036753607"
                },
                {
                    "type": "email",
                    "value": "marcy.nadedau@va.gov"
                }
            ]
        },
        "preferredTimesForPhoneCall": [
            "Evening"
        ],
        "preferredLocation": {
            "city": "Denver",
            "state": "CO"
        },
        "preferredLanguage": "French",
        "cancellable": false,
        "extension": {
            "ccLocation": {
                "address": {}
            },
            "ccRequestedCancellation": false,
            "hsrmTaskId": "15884"
        },
        "preferredProviderName": "WILLIAMS, CAROL",
        "location": {
            "id": "984",
            "type": "appointments",
            "attributes": {
                "id": "984",
                "vistaSite": "984",
                "vastParent": "984",
                "type": "va_health_facility",
                "name": "Dayton VA Medical Center",
                "classification": "VA Medical Center (VAMC)",
                "timezone": {
                    "timeZoneId": "America/New_York"
                },
                "lat": 39.74935,
                "long": -84.2532,
                "website": "https://www.dayton.va.gov/locations/directions.asp",
                "phone": {
                    "main": "937-268-6511"
                },
                "physicalAddress": {
                    "type": "physical",
                    "line": [
                        "4100 West Third Street"
                    ],
                    "city": "Dayton",
                    "state": "OH",
                    "postalCode": "45428-9000"
                },
                "healthService": [
                    "Audiology",
                    "Cardiology",
                    "DentalServices",
                    "Dermatology",
                    "Gastroenterology",
                    "Gynecology",
                    "MentalHealthCare",
                    "Nutrition",
                    "Ophthalmology",
                    "Optometry",
                    "Orthopedics",
                    "Podiatry",
                    "PrimaryCare",
                    "SpecialtyCare",
                    "Urology",
                    "WomensHealth"
                ]
            }
        }
    }
}
```

**Comment by jenniemc** [comment] 2024-06-24 17:13
@ldelacosta 
Below is the object returned from the same CC request but is now cancelled. Notice the object is missing the `preferredProviderName`

```
{
    "id": null,
    "type": "appointments",
    "attributes": {
        "identifier": [
            {
                "system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
                "value": "15884"
            }
        ],
        "kind": "cc",
        "status": "cancelled",
        "serviceType": "foodAndNutrition",
        "serviceTypes": [
            {
                "text": "foodAndNutrition"
            }
        ],
        "reasonCode": {
            "text": "smoke test 2.39.2 fix"
        },
        "patientIcn": "1013124304V115761",
        "locationId": "984",
        "practitioners": [
            {
                "identifier": [
                    {
                        "system": "http://hl7.org/fhir/sid/us-npi",
                        "value": "1487085270"
                    }
                ],
                "address": {
                    "type": "physical",
                    "line": [
                        "1960 N Ogden St Ste 460"
                    ],
                    "city": "Denver",
                    "state": "CO",
                    "postalCode": "80218",
                    "text": "1960 N Ogden St Ste 460,Denver,CO,80218"
                }
            }
        ],
        "created": "2024-04-02T15:30:00Z",
        "requestedPeriods": [
            {
                "start": "2024-04-26T16:00:00Z",
                "localStartTime": "2024-04-26T12:00:00.000-04:00"
            }
        ],
        "contact": {
            "telecom": [
                {
                    "type": "phone",
                    "value": "7036753607"
                },
                {
                    "type": "email",
                    "value": "marcy.nadedau@va.gov"
                }
            ]
        },
        "preferredTimesForPhoneCall": [
            "Evening"
        ],
        "preferredLocation": {
            "city": "Denver",
            "state": "CO"
        },
        "cancelationReason": {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason",
                    "code": "pat",
                    "display": "The appointment was cancelled by the patient"
                }
            ]
        },
        "preferredLanguage": "French",
        "cancellable": false,
        "extension": {
            "ccLocation": {
                "address": {}
            },
            "ccRequestedCancellation": true,
            "hsrmTaskId": "15884"
        },
        "location": {
            "id": "984",
            "type": "appointments",
            "attributes": {
                "id": "984",
                "vistaSite": "984",
                "vastParent": "984",
                "type": "va_health_facility",
                "name": "Dayton VA Medical Center",
                "classification": "VA Medical Center (VAMC)",
                "timezone": {
                    "timeZoneId": "America/New_York"
                },
                "lat": 39.74935,
                "long": -84.2532,
                "website": "https://www.dayton.va.gov/locations/directions.asp",
                "phone": {
                    "main": "937-268-6511"
                },
                "physicalAddress": {
                    "type": "physical",
                    "line": [
                        "4100 West Third Street"
                    ],
                    "city": "Dayton",
                    "state": "OH",
                    "postalCode": "45428-9000"
                },
                "healthService": [
                    "Audiology",
                    "Cardiology",
                    "DentalServices",
                    "Dermatology",
                    "Gastroenterology",
                    "Gynecology",
                    "MentalHealthCare",
                    "Nutrition",
                    "Ophthalmology",
                    "Optometry",
                    "Orthopedics",
                    "Podiatry",
                    "PrimaryCare",
                    "SpecialtyCare",
                    "Urology",
                    "WomensHealth"
                ]
            }
        }
    }
}
```

**Comment by cferris32** [comment] 2024-06-25 18:42
The above PR has been merged. We have validated the behavior and are now seeing cancelled cc appts with provider info showing up in staging. Closing this ticket

**Closed by cferris32** 2024-06-25 18:42 UTC
Labels: bug, appointments, vets-api
