### ISSUE TITLE
Modify daily-deploy-production GHA Script to check Jenkins Build Status

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#29406] opened 2021-08-27 12:55 UTC
## Details

Currently, the daily-deploy-production GitHub action scripts in vets-website and content-build deploy to dev and check the GHA build status. In order to enable the scripts for testing production deploys, they first need to be able to check the Jenkins build status. This is because the continuous-integration workflow still lives in Jenkins.

Once the continuous-integration GHA workflow replaces the Jenkins equivalent, the daily-deploy-production script will need to point to the GHA build status again.

## Tasks

- [ ] Discover if it is possible to have the daily-deploy-production GHA scripts check the Jenkins builds status
- [ ] Change the daily-deploy-production GHA scripts to check the Jenkins build status

**Comment by oseasmoran73** [comment] 2021-08-31 20:24
Closing this ticket as PR has been merged both in `content-build` and `vets-website` and working as intended.

**Closed by oseasmoran73** 2021-08-31 20:24 UTC
Labels: tools-fe
