### ISSUE TITLE
Analytics Implementation or QA Support for Decision Tools - Yellow Ribbon Search Tips

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18470] opened 2021-01-13 14:33 UTC
# Google Analytics Implementation or QA Request

## What this form is for 
Tracking soon-to-be-added optional search tips events on the Yellow Ribbon Search product and replacing the data layer that recently was discovered to have gone missing.

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
GA analytics

- Who is this request for?

    - Decision Tools Team: John Hashimoto (PO), Marci McGuire (PM), Zach Morel (FE Engineer), Laurel Lawrence (Design/Research)
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    Decision Tools Team, Yellow Ribbon search
    
    
- Provide the Domain where Google Analytics needs to be implemented
   - staging.va.gov and va.gov
    
    _Identify if PII is passed in URL or title tag_
    - No PII

- Please provide any upcoming deadlines or important milestones
    - Anticipated launch date: *Feb 9, 2021*

- Typical Website Interactions to Track
    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
         - Clicks to *How to Apply* page 
                  - https://staging.va.gov/education/how-to-apply/
         - Clicks _from_ *How to Apply* page to *Education application page* following a Yellow Ribbon search https://staging.va.gov/education/apply-for-education-benefits/application/1990/applicant/information  *(GOAL)*
    
- *Other Interactions*    
      - **Page Views**, Search Landing Page: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
      - **Searches**, Search Landing Page: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
      - **Search Refinements**, Search Landing Page: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
      - **Conversions** (above) following searches on Search Landing Page: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
      - **Conversions** following search revisions on Search Landing Page: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
      - % Revisions/Session: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
     - % Conversions/Session: - https://staging.va.gov/education/yellow-ribbon-participating-schools/ 
     - Avg revisions / conversion
     - Outbound clicks to *Yellow Ribbon School web sites* from search results (see below example):
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/c0edd4c7-86bd-47d3-970f-f6333ecc7ffa)
    - *Other User Interactions*:  _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
        - Clicks on **Eligibility** link on Search Lading Page https://staging.va.gov/education/eligibility/
      - Clicks on **Find out if You Qualify...** link on Search Landing Page https://staging.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
     - Clicks on optional search tips object.  Mockup is shown here: 
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/07c8cc2e-1d0c-454a-858e-42e09d5d4797)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

 Unauth; no authentication required.

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

  N/A

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]
          - Is a separate request needed for a Domo dashboard?  
           - Can events that were being captured before the data layer disappeared be used to reconstruct the same events so the old data can be combined with the new?

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2021-01-13 16:22
@MarciMcGuireGCIO Thank you for your request here! A question that comes to mind initially if I may: 
- Would you consider the link clicks to the school pages as "search results"? For your awareness, we do have existing tracking on these as outbound link clicks, in other words, links that navigate the user away from VA.gov.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-13 16:58
@jonwehausen, great question!  I think we will want to have the ability to report on specific links to schools are clicked most often, whatever category that falls into (user behavior?).  Do you agree, @johnhashva ?

**Comment by johnhashva** [comment] 2021-01-13 17:12
Yes, and that info is important to share with VA program leads too..

**Comment by jonwehausen** [comment] 2021-01-13 20:30
## Data Layer Specification

### Context
- The specification provided is intended to be generic enough to be re-used for all of our search touchpoints on VA.gov
- While it looks like our legacy event tracking (event `edu-yellow-ribbon-search`) for yellow ribbon was recently re-instated, we would like to propose replacing these events and metadata with our standardized search structure outlined below
- You can find the full specification [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-search.md)
- Per note above ^^, we will consider clicks to the school URLs as search result clicks in this case


### On Search

Description/Screenshot of Interaction | DataLayer | Dev Notes
------------ | ------------- | -------------
_When the user has performed a search AND search results have been returned_ | `'event': 'view_search_results',`<br>`'search-page-path': '/education/yellow-ribbon-participating-schools/', //consistent for this page`<br>`'search-query': //dynamically populate with the user input in search box at time of click`<br>`'search-typeahead-enabled': false //no type ahead on this sear`<br>`'search-selection': 'Yellow Ribbon', //dynamically changed according to search application + scope`<br>`'search-filters-list': { stateOrTerritory: //state, city: //city name, contributionAmount: "unlimited" //or undefined if not used, numberOfStudents: "unlimited" //or undefined if not used}`<br>`'type-ahead-option-keyword-selected': undefined,`<br>`'type-ahead-option-position': undefined`<br>`'type-ahead-options-list': undefined` | - **Please be sure to push `undefined` for any variable that is not available from the system** <br> - **For all non-type ahead search, please push boolean value `false` for `search-typeahead-enabled`**

### On Search Results Click
Description/Screenshot of Interaction | DataLayer | Dev Notes
------------ | ------------- | -------------
_When the user has clicked on a search result from the search results list (school link)_ |  `'event': 'onsite-search-results-click',`<br>`'search-result-type': 'title' //dynamically populate with 'pdf', if pdf for 'cta' if a cta click`<br>`'search-filters-list': { stateOrTerritory: //state, city: //city name, contributionAmount: "unlimited" //or undefined if not used, numberOfStudents: "unlimited" //or undefined if not used}`<br>`'search-results-top-recommendation': false //populate boolean according to if result clicked was a top recommendation`<br>`'search-selection': 'Yellow Ribbon' //dynamically changed according to search application + scope`<br>`'search-result-chosen-page-url': 'https://www.harvard.edu/' //dynamically populate accoding to the url href`<br>`'search-result-chosen-title': Harvard University' //dynamically populate with the top level title` <br>`'search-query': //dynamically populate with text in "School Name" box`<br>`'search-total-results': 999,`<br>`'search-total-result-pages': <total_result_pages>,`<br>`'search-result-position': 4`<br>`'search-result-page': 1` | - The position number should reflect the position on the page -- For example, if 10 results are returned and the first result is clicked, `'search-result-position'` should populate with 1

**Comment by jonwehausen** [comment] 2021-01-13 22:26
@zacharymorel @MarciMcGuireGCIO the data layer specification above is ready for your implementation at your convenience. 

@zacharymorel When you have a moment, I wanted to briefly discuss with you if there was a way we could potentially incorporate the data layer into usability testing _(something we haven't done before, but would be interested in doing)_ Happy to setup a 10-15 meeting or discuss asynchronously, thanks in advancd

**Comment by MarciMcGuireGCIO** [comment] 2021-01-13 22:41
@jonwehausen thank you!!

**Comment by zacharymorel** [comment] 2021-01-14 14:42
Thank you @jonwehausen. 

Let's set up a meeting. My calendar: https://calendar.google.com/calendar/u/0?cid=em1vcmVsQGdvdmVybm1lbnRjaW8uY29t

**Comment by jonwehausen** [comment] 2021-01-20 17:03
Thanks @zacharymorel ! I have put a meeting on the calendar for next Tuesday with you and @srsuddath to discuss data layer testing opportunities with search.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-27 20:47
@zacharymorel - the Google Analytics data layer specification also needs to be added to the Yellow Ribbon search & QA'd with Analytics with the search tip.

**Comment by jonwehausen** [comment] 2021-02-16 23:56
@zacharymorel My mistake for not including in the original specification -- Could we also please add in the `'search-total-results'` and `'search-total-result-pages'` on the `view_search_results` event fire? Thanks so much in advance

**Comment by jonwehausen** [comment] 2021-02-17 00:16
@zacharymorel Secondary, I did some quick initial QA and one of the first stand out items appears to be `onsite-search-results-click` populates with incorrect values, see screenshot below for example


![image](https://user-images.githubusercontent.com/48527022/108138146-5bedac80-708b-11eb-9086-52c88ed5e3b8.png)

Thanks a bunch for your efforts here.

**Comment by zacharymorel** [comment] 2021-02-17 15:23
Thank you @jonwehausen , I'll ping you again when it is ready for another round of QA.

**Comment by jonwehausen** [comment] 2021-02-18 15:31
Shifting back to standby per dev changes

**Comment by zacharymorel** [comment] 2021-02-19 15:39
This is ready on staging @jonwehausen .
CC: @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment] 2021-02-24 17:42
@jonwehausen I know you are super busy. What is your next available time for an Analytics review? I'm happy to schedule something if you are able to share your calendar. Thank you! 
Cc @zacharymorel

**Comment by jonwehausen** [comment] 2021-03-09 17:03
Hi @zacharymorel, 

Thank you so much for your patience here. 

There are a few items further identified within the data layer that would be great to correct when available (see screenshot examples below): 
- On the `view_search_results` and the `onsite-search-results-click` event, adjust `search-total-results` to be **`search-results-total-count`**
- On the `view_search_results` and the `onsite-search-results-click` event, adjust `search-total-result-pages` to be **`search-results-total-pages`**
- On the `onsite-search-results-click` event fire, adjust the `search-result-chosen-page-url` variable to populate with the school university URL clicked on (currently is the yellow ribbon full address) 

### **view_search_results**
![image](https://user-images.githubusercontent.com/48527022/110507068-ae8c1880-80cd-11eb-9c0f-ded83ea0b70a.png)

### **onsite-search-results-click**
![image](https://user-images.githubusercontent.com/48527022/110506856-7b498980-80cd-11eb-8b72-29a7b6a053ca.png)

----------------------------

### GTM Testing

**view_search_results**
| Description/Screenshot of Interaction | Tag Screenshot | Test Status | Test notes
| -- | -- | -- | -- | 
Search in virginia with unlimited contribution amount filter checked (no query string) ![image](https://user-images.githubusercontent.com/48527022/110507460-0a56a180-80ce-11eb-9efa-026253656d37.png) | ![image](https://user-images.githubusercontent.com/48527022/110507591-265a4300-80ce-11eb-939b-e0dd975f99ee.png) | ✔️ **PASS** | Appropriate custom dimension values for search filters
Search in Maryland with both filters check (no query string) ![image](https://user-images.githubusercontent.com/48527022/110507755-4f7ad380-80ce-11eb-8dc8-4bb2a9000b84.png) | ![image](https://user-images.githubusercontent.com/48527022/110507806-5e618600-80ce-11eb-98c6-afed9abb351c.png) | ✔️ **PASS** | `(not set)` value passed for no city inputted

**onsite-search-results-click**
| Description/Screenshot of Interaction | Tag Screenshot | Test Status | Test Notes
| -- | -- | -- | -- |
Click on Adams State University website following search (no query string) ![image](https://user-images.githubusercontent.com/48527022/110508190-c0ba8680-80ce-11eb-8896-3a6bf1c9e0bf.png) | ![image](https://user-images.githubusercontent.com/48527022/110508238-cf08a280-80ce-11eb-8b20-7782742b8e41.png) | ✔️ **PASS** | Passed entire school attributes array into custom dimension 128 -- some individual values such as facilityCode and institutionId also reflected in CDs 126 + 127
Click on Boise State University following search (no query string) ![image](https://user-images.githubusercontent.com/48527022/110508431-fd867d80-80ce-11eb-8ff6-44187967fbca.png) | ![image](https://user-images.githubusercontent.com/48527022/110508543-1858f200-80cf-11eb-8658-8eecb7303c69.png) | ✔️ **PASS** | N/A

----------------

@zacharymorel For your awareness, I have published the appropriate tagging to begin collecting according to the updated implementation for yellow ribbon. Following the few data layer changes identified remaining at the top of this note, we should be ready to close this out. 



|

**Comment by jonwehausen** [comment] 2021-03-09 17:04
Hi @MarciMcGuireGCIO , 

Yes, can you tell me a bit more what you would be looking for out of an analytics review so we can include the right members of our team? Thanks so much and we appreciate your patience on this request. 

cc: @joanneesteban for visibility

**Comment by jonwehausen** [comment] 2021-03-09 17:16
Okay great, yes @MarciMcGuireGCIO . We are very close to closing this guy out following the few changes I identified for @zacharymorel above.

**Comment by zacharymorel** [comment] 2021-03-09 18:30
> Hi @zacharymorel,
> 
> Thank you so much for your patience here.
> 
> There are a few items further identified within the data layer that would be great to correct when available (see screenshot examples below):
> 
> * On the `view_search_results` and the `onsite-search-results-click` event, adjust `search-total-results` to be **`search-results-total-count`**
> * On the `view_search_results` and the `onsite-search-results-click` event, adjust `search-total-result-pages` to be **`search-results-total-pages`**
> * On the `onsite-search-results-click` event fire, adjust the `search-result-chosen-page-url` variable to populate with the school university URL clicked on (currently is the yellow ribbon full address)
> 
> ### **view_search_results**
> ![image](https://user-images.githubusercontent.com/48527022/110507068-ae8c1880-80cd-11eb-9c0f-ded83ea0b70a.png)
> 
> ### **onsite-search-results-click**
> ![image](https://user-images.githubusercontent.com/48527022/110506856-7b498980-80cd-11eb-8b72-29a7b6a053ca.png)
> 
> ### GTM Testing
> **view_search_results**
> 
> Description/Screenshot of Interaction	Tag Screenshot	Test Status	Test notes
> Search in virginia with unlimited contribution amount filter checked (no query string) ![image](https://user-images.githubusercontent.com/48527022/110507460-0a56a180-80ce-11eb-9efa-026253656d37.png)	![image](https://user-images.githubusercontent.com/48527022/110507591-265a4300-80ce-11eb-939b-e0dd975f99ee.png)	✔️ **PASS**	Appropriate custom dimension values for search filters
> Search in Maryland with both filters check (no query string) ![image](https://user-images.githubusercontent.com/48527022/110507755-4f7ad380-80ce-11eb-8dc8-4bb2a9000b84.png)	![image](https://user-images.githubusercontent.com/48527022/110507806-5e618600-80ce-11eb-98c6-afed9abb351c.png)	✔️ **PASS**	`(not set)` value passed for no city inputted
> **onsite-search-results-click**
> 
> Description/Screenshot of Interaction	Tag Screenshot	Test Status	Test Notes
> Click on Adams State University website following search (no query string) ![image](https://user-images.githubusercontent.com/48527022/110508190-c0ba8680-80ce-11eb-8896-3a6bf1c9e0bf.png)	![image](https://user-images.githubusercontent.com/48527022/110508238-cf08a280-80ce-11eb-8b20-7782742b8e41.png)	✔️ **PASS**	Passed entire school attributes array into custom dimension 128 -- some individual values such as facilityCode and institutionId also reflected in CDs 126 + 127
> Click on Boise State University following search (no query string) ![image](https://user-images.githubusercontent.com/48527022/110508431-fd867d80-80ce-11eb-8ff6-44187967fbca.png)	![image](https://user-images.githubusercontent.com/48527022/110508543-1858f200-80cf-11eb-8658-8eecb7303c69.png)	✔️ **PASS**	N/A
> @zacharymorel For your awareness, I have published the appropriate tagging to begin collecting according to the updated implementation for yellow ribbon. Following the few data layer changes identified remaining at the top of this note, we should be ready to close this out.
> 
> |

Hey Jon, thanks for getting back to this. 
Quick Q, did you test using https://staging.va.gov/find-forms/?q=caregiver or https://www.va.gov/find-forms/?q=caregiver ?

**Comment by zacharymorel** [comment] 2021-03-11 19:40
@jonwehausen Where you able to see my comment above?

**Comment by jonwehausen** [comment] 2021-03-12 19:28
Hi @zacharymorel,

Yes, thank you for your patience here. Yes you are correct that for `/find-forms` the datalayer looks to have the correct variable names, for yellow ribbon search however there remains the discrepancy.

**Comment by zacharymorel** [comment] 2021-03-12 19:42
Thank you @jonwehausen , I i'll let you know when the YR tool is updated!

**Comment by MarciMcGuireGCIO** [comment] 2021-03-16 13:41
@zacharymorel , @jonwehausen can I get a quick status update on this?  Thanks

**Comment by jonwehausen** [comment] 2021-03-16 14:18
Hi @MarciMcGuireGCIO , 

Sure, looks like the PR Zach referenced above contained the remaining items for us to QA prior to close-out. 

We'll do one more round of QA on our part, validate all the data looks good and close out. 

Certainly should have this closed out this week.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-16 14:25
Thanks, @jonwehausen !

**Comment by jonwehausen** [comment] 2021-03-18 14:05
### QA Testing Round 2

@zacharymorel Thank you for your work here, please find the latest QA results. Please don't hesitate to reach out for clarification on anything. 

Description of Interaction/Test Case | Data Layer Screenshot | Test Status | Dev Notes
| -- | -- | -- | -- |  
Performed a search for "California" with a return of 548 results | ![image](https://user-images.githubusercontent.com/48527022/111636397-d1ee4c00-87ce-11eb-81d7-a257d911017b.png) | ⚠️ **DOES NOT PASS** | @zacharymorel It looks like the taxonomy of `search-results-total-count` is now correct, however is populating with the wrong value, populated with 10 instead of 548, see below test case as well
On search results click of "www.academyart.edu" for the same search above | ![image](https://user-images.githubusercontent.com/48527022/111637014-66f14500-87cf-11eb-9147-74e44d4a8cb1.png) | ⚠️ **DOES NOT PASS** | @zacharymorel Here on the `onsite-search-results-click` value looks good 👍 , however we will want to make the variable name plural to `'search-results-total-pages'`
Performed a search for "California" with a return of 548 result | ![image](https://user-images.githubusercontent.com/48527022/111637190-94d68980-87cf-11eb-98d7-5f72029b7855.png) | ⚠️ **DOES NOT PASS** | @zacharymorel the variable highlighted should be adjusted to `search-results-total-pages` plural & value should be updated to be total number of pagination pages ![image](https://user-images.githubusercontent.com/48527022/111637462-d49d7100-87cf-11eb-9105-d0ea3321e21d.png) <br><br> **see below test case**
On search results click of "www.academyart.edu" for the same search above | ![image](https://user-images.githubusercontent.com/48527022/111638347-9e142600-87d0-11eb-8034-349a7c75b59b.png) | ⚠️ **DOES NOT PASS** | @zacharymorel the value is correct here of 55 pagination pages, however we will want to adjust the variable name to be `'search-results-total-pages'`
On search results click of "www.academyart.edu" for the same search above | ![image](https://user-images.githubusercontent.com/48527022/111638978-35797900-87d1-11eb-8c50-96709671ba00.png) | ✔️ **PASS** | Perfect here of `search-result-chosen-page-url`

**Comment by MarciMcGuireGCIO** [comment] 2021-03-18 14:57
Thank you for the update, @jonwehausen.  Quick question - what is the best way for me to coordinate further reviews of this on QA?  Since this is kind of outside the normal collab cycle (replacing previous data layer that went missing), not sure the best way to keep things moving.   I'm concerned that we've not capturing event data while we've been collaborating for two months.   Thanks!

**Comment by jonwehausen** [comment] 2021-03-19 13:45
Hi @MarciMcGuireGCIO , 

Great question, and I want to apologize in advance for this extended QA effort here. 

While Zach and I have been working together to make incremental / iterative improvements in the data collection depth, quality & consistency over this time -- We have in-fact been collecting search volume data for Yellow Ribbon under the new taxonomy since Feb 8, and began collecting search queries along with several pieces of the additional metadata you see bellow for yellow ribbon on Feb 12. We also have been collecting search result schools chosen since this time. 

I also was pleasantly surprised to see our **legacy/original** (before our search standardization) yellow ribbon search tracking was reinstated for Jan 1 2021 - Feb 12 2021 with some of the metadata such as [school city](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210212&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:edu-yellow-ribbon-search&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension83/), [school state](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210212&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:edu-yellow-ribbon-search&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension82/), and [school name](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210212&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:edu-yellow-ribbon-search&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension81/) also reinstated. 🎆 

Per round 3 QA results below, we can now confirm the data layer for yellow ribbon search has now been fully converted to our standardized taxonomy we have across other search products. 👍 

Lastly, the new yellow ribbon search events can be found [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210317&_u.date01=20210318&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:view_search_results&explorer-table.plotKeys=%5B%5D&explorer-table.filter=~~%20Yellow%20Ribbon/) with the capability to additional context/insight by using the custom dimensions + metrics below as well. 


------------------------------------------------------------------------------------

### QA Testing Round 3

Description of Interaction/Test Case | Data Layer Screenshot | Tag Screenshot | Test Status | Test Notes
| -- | -- | -- | -- | -- |
Performed a search for "California" with a return of 548 results | ![image](https://user-images.githubusercontent.com/48527022/111778888-c14fdb80-888b-11eb-8e19-388d6525b1c3.png) | ![image](https://user-images.githubusercontent.com/48527022/111779107-1390fc80-888c-11eb-8031-df07811cd8ca.png) ![image](https://user-images.githubusercontent.com/48527022/111784715-1bec3600-8892-11eb-834c-2fb73b6ca4d2.png) | ✔️ ✔️ **PASS** | • Confirmed data layer variables `'search-results-total-count` & `'search-results-total-pages'` now correct values and names 👍 <br> • Custom metrics 41 (Search Total Results Returned), 42 (Search Results Total Pages Returned), 43 (Search Results Pagination Page Number) 45 (Search Performed) also confirmed 👍 
On search results click of "www.academyart.edu" for the same search above | ![image](https://user-images.githubusercontent.com/48527022/111779810-eee95480-888c-11eb-9e34-7a19366de8ab.png) | ![image](https://user-images.githubusercontent.com/48527022/111779883-0d4f5000-888d-11eb-85ba-43e3fc09e3d5.png) ![image](https://user-images.githubusercontent.com/48527022/111785170-a3d24000-8892-11eb-9152-e3ff4fe7a051.png) | ✔️ ✔️ **PASS** | • Confirmed data layer variables `'search-results-total-count` & `'search-results-total-pages'`  now correct values and names 👍 <br> • Custom dimensions 79 (Education - YR - Filter - Contribution Amount), 80 (Education - YR - Filter - Number of Students), 82 (Education - School State) _abbr_, 83 (Education - School City), 120 (Search Results Type), 126 (Facility Code), 127 (Institution ID), 128 (Education - YR - School Search Result Details) 👍 <br> • Custom metrics 41 (Search Total Results Returned), 42 (Search Results Total Pages Returned), 43 (Search Results Pagination Page Number), 45 (Search Performed) also confirmed 👍

**Closed by jonwehausen** 2021-03-19 13:45 UTC
Labels: PR-open, analytics-insights, analytics-request, collab-cycle-review, collaboration-cycle, dt-yellow-ribbon-schools-search, gtm, vsa, vsa-decision-tools

**Comment by MarciMcGuireGCIO** [comment] 2021-03-19 13:49
@zacharymorel @jonwehausen thank you both for the excellent collaboration on this!  And @jonwehausen thank you for the additional info you provided above.  It is indeed wonderful news that some of the data has been reinstated, and I'm excited to start delving into it!
