### ISSUE TITLE
VoiceOver reads out loud Choose an appointment type when traversing text items in reverse in the cheetah MVP flow

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#21871] opened 2021-03-22 19:13 UTC
## AC

- [ ] Description copy reads "choose an appointment type"

- [ ] CTA is a button, not action link

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/851958d9-1098-485d-a295-d9385041050e)

- [ ] VSP Accessibility reviewed and approved
```
<!-- button[disabled] -->
<button
  aria-label="Choose an appointment type to start scheduling"
  id="schedule-button"
  type="submit"
  disabled
>Start scheduling >></button>
<!-- button with radio[checked] -->
<button
  aria-label="Start scheduling an appointment"
  id="schedule-button"
  type="submit"
  disabled
>Start scheduling >></button>
```

## Out of Scope
- Radio buttons and labels

---

Original Description

Discovery in #21342

When no radio button is selected, VoiceOver (tested in Chrome), skips over `Choose an appointment type` as expected when reading items moving forward. But VO reads `Choose an appointment type` when traversing in reverse order. Moreover, it does not indicate the link as “dimmed” or “disabled”
![image](https://user-images.githubusercontent.com/54327023/112046857-eca02800-8b22-11eb-90c0-b63e4d1d514b.png)

Steps to reproduce on a Mac

1. Bring up the cheetah flow in chrome
2. Launch VoiceOver by hitting the `Command` + `F5`
3. Hit `Control` + `Option` + `Command` + `H` at any point to have VO read the next heading. 
4. Continue hitting the same set of keys until you reach `Request an Express Care appointment`
5. Hit `Control` + `Option` + `left arrow` to read the previous item. 
6. The expected behavior is to read out loud `End of. Choose an appointment type to begin scheduling. You are currently in a group` Instead it read `Choose an appointment type`

[VO keyboard shortcuts](https://webaim.org/articles/voiceover/)

**Comment by jbalboni** [comment] 2021-03-23 14:51
@jenniemc @grossb1 It's not clear to me why this is an issue. In your steps you navigated forward by heading, and then backward by item, and the "Choose appointment type" text is the element before the express care header. That seems like expected behavior?

I could see us needing to add some explanatory text about it being a disabled link, but the order issue is confusing to me.

**Comment by jenniemc** [comment] 2021-03-23 22:02
@jbalboni, Sorry the explanation is unclear. Providing additional steps below for moving forward to demonstrate when navigating forward using VoiceOver, it skips over "Choose appointment type" when the link is greyed out. Thus, the link never gets read out loud. However, when moving backwards the screen reader does NOT skip over but proceeds to read "Choose appointment type". The behavior is not the same when traversing forward as would backwards. 

**Steps to have VO move forward:**
1. Bring up the cheetah flow in chrome
2. Launch VoiceOver by hitting the `Command` + `F5`
3. Hit `Control` + `Option` + `Command` + `H` to have VO read the h1 heading, "VA Appointments"
4. Hit `Control` + `Option` + `right arrow` to read the next item.
5. Continue hitting the same set of keys to read pass the radio buttons. 
6. Once passed the radio buttons, VO will skip over "Choose appointment type" and reads "Request an express care appointment" instead


**Steps to have VO move backwards:**
1. Bring up the cheetah flow in chrome
2. Launch VoiceOver by hitting the `Command` + `F5`
3. Hit `Control` + `Option` + `Command` + `H` at any point to have VO read the next heading.
4. Continue hitting the same set of keys until you reach "Request an Express Care appointment"
5. Hit `Control` + `Option` + `left arrow` to read the previous item
6. It reads out loud "Choose an appointment type" 

cc @grossb1

**Comment by 1Copenut** [comment] 2021-03-24 17:06
@jenniemc & @outerpress Can we chat about this one, maybe tomorrow morning? I'm a little uneasy with the primary CTA being a link, or maybe with it being disabled. Can't say for sure, but there feels like a rough edge for accessibility I think we could clear up with a quick conversation.

**Comment by jenniemc** [comment] 2021-03-24 17:23
@1Copenut @outerpress Sure, I'm available tomorrow morning anytime before 12:00pm EST.

**Comment by laurenernest** [comment] 2021-03-25 17:22
Moving to Icebox until we have the new CTA design. We'll validate this is no longer an issue once it's implemented.

**Comment by 1Copenut** [comment] 2021-03-25 17:26
Talking with Peter and Jennie this morning (3/25), we discussed removing the disabled action link and replacing it with a primary action button. There were a couple of challenges with using a disabled link:

* Links don't have attributes like `disabled` or `aria-disabled="true"` to describe the link is not clickable. The best we can do in these cases is use CSS to remove pointer events and retain the standard cursor. We also have to remove the `href` attribute so the link is not keyboard focusable. Screen readers still announce the link in the Links menu, but the default behavior is removed.
* The radio buttons to select an appointment type feel like a form to be submitted. A button is the right input for this job.

We also discussed a couple of A/B test flows for the primary call to action:
* Use a disabled submit button until users click one of the radio buttons
* Keep the button enabled and use error handling if users click the button without selecting a radio button for appointment type

/cc @rtwell for visibility

**Comment by outerpress** [comment] 2021-03-25 21:11
Thanks for running through this @1Copenut and @jenniemc !

I mocked up a version to address those issues, replacing the action link with a primary button as discussed. As I was working through this I think it does need to move the language "Choose an appointment type." from the action to a label, since the disabled button really doesn't communicate that information well.

For future explorations I'd like to look at a single CTA on home (and maybe the static landing page) that starts the scheduling experience, but that brings up a host of other questions beyond the scope of this ticket. For now, switching from action link to primary button should work. Mocks:

![VAOS-home-cta-states-allenabled](https://user-images.githubusercontent.com/2536801/112539044-be625880-8d6d-11eb-80f9-08f6e37e7876.png)

**Comment by 1Copenut** [comment] 2021-03-29 16:07
@outerpress I like this streamlined flow a lot. There's a clear call to action and I can focus on the next one thing. I'd like to see if the front-end devs can update the button's accessible label based on `[disabled]` state. Thinking:

```html
<!-- button[disabled] -->
<button
  aria-label="Choose an appointment type to start scheduling"
  id="schedule-button"
  type="submit"
  disabled
>Start scheduling >></button>
```

```html
<!-- button with radio[checked] -->
<button
  aria-label="Start scheduling an appointment"
  id="schedule-button"
  type="submit"
  disabled
>Start scheduling >></button>
```

**Closed** 2021-04-14 14:42 UTC
Labels: 508-defect-2, 508/Accessibility, design, frontend, vaos, vaos-needs-qa-prod, vaos-needs-qa-staging

**Comment by laurenernest** [comment] 2021-04-15 18:10
@1Copenut this is ready for your review.

**Comment by 1Copenut** [comment] 2021-04-20 13:21
@laurenernest This one is working as expected now. The button announces itself as "dimmed" when moving forward and backward through the DOM, until users make a radio button selection.
