### ISSUE TITLE
Logging of SSOe/MPI sourced IDs conflict

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35053] opened 2022-01-10 17:47 UTC
## Description
We want to create more logging/alerting around users who fail to login due to a mismatch between GCID and eAuth fields (such as IEN and GCID mismatches).

#### Authentication Blocked - Outbound Redirect Excepted
- :mhv_icn_mismatch - `va_eauth_icn` / `va_eauth_mhvicn`
- :multiple_corp_ids - GCIDs - `VBA_CORP_ID_REGEX`
- :multiple_mhv_ids - GCIDS - `MHV_IEN_REGEX` + `va_eauth_mhv_uuid`
#### Authentication Blocked - No Exceptions
- :multiple_edipis - GCIDs - `DOD_ROOT_OID`
- :uuid_missing - `va_eauth_uid` / GCIDs backup - `idme_uuid / logingov_uuid`
#### Info Only
- sec_id_mismatch? - `va_eauth_secid`
#### Disabled
- birls_id_mismatch? - `va_eauth_birlsfilenumber`

## Acceptance Criteria
Add `after_login_actions` UserIdentity/MPI validations for the following attributes:
- [x] SSN - move from `sessions_controller` to `after_login_actions`
~~- [ ] SecID - currently sourced only from `va_eauth_secid`~~
- [x] Edipi
- [x] corpid
- [x] icn
~~- [ ] mhv_correlation_id - currently source only from `mpi_profile`~~

**Comment by bramleyjl** [comment] 2023-01-20 18:36
@bosawt @joeniquette I came up with GCID/`va_eauth` comparison checks for SecID & SSN since they're both sourced directly from SSOe headers. The MHV IENs example is already covered through the existing code that was added roughly the time this story was created, can you think of any other validations in SSOe that need patching?

**Comment by bosawt** [comment] 2023-01-20 18:49
Hmm I dunno, I'm not sure if there's anything to do here, the SSN mismatch already occurs in sessions controller, and as for the sec_id one, 🤷 .

Generally I feel like instead of comparing SAML header with MPI and raising an error if they're different, we should just do the MPI query and ignore the SAML header fields. That way we don't even have to bother

**Comment by joeniquette** [comment] 2023-01-20 20:04
We wanted this log to prove how often it was different. What about the edipi and corp ids? Do we have a single log that shows the difference for all of these? I dont mind building a few queries together to get all the info, I'd just need to know what you end up calling the errors.

**Comment by bramleyjl** [comment] 2023-01-23 16:50
Trevor: So basically just keep doing the UserIdentity to MPI attributes refactors to prevent this from being a problem in the first place.

Joe: edipi & corp_id checks are both already in & synched with the same error message & error code for SSOe & SiS. In #51951 I'm cataloguing all of the ID & attribute validations that we might want to include in a script to periodically generate a report on for further action.

**Comment by bramleyjl** [comment] 2023-03-09 15:00
Two of the logs, MHV ID & SSN mismatches, are appearing through Datadog searching & in the [aggregated monitor in the Identity Logs Dashboard](https://vagov.ddog-gov.com/dashboard/3di-esj-7wy/identity-log-queries). The cause of the MHV ID mismatch is due to the Identity value being missing entirely, rather than due to any conflict. I'll close this now & continue to look for EDIPI & ICN mismatches in the future.

![image.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/40c2b9b4-725c-4dfb-a3be-586404c330eb)

**Closed by bramleyjl** 2023-03-09 15:00 UTC
Labels: Identity
