### ISSUE TITLE
Back-end: YR Search Results sorting functionality

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#5588] opened 2020-02-06 01:59 UTC
## User Story:
As a Veteran, I need to sort Yellow Ribbon search results so that I can easily explore potential programs.

## MVP Design Specs
Mobile: https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens
Desktop: https://vsateams.invisionapp.com/share/X5VOMBG2YP4#/screens/402038362

## Acceptance Criteria:
- [ ] Back-end component of sorting logic is complete for `Benefit Amount`, `School Name`, `City`, and `State`.

## Related
* #4808

**Comment by AkucherGCIO** [comment] 2020-03-04 18:56
03/04/20 PW Grooming
This issue is being closed as it is a duplicate of the sorting functionality.

**Closed by AkucherGCIO** 2020-03-04 18:56 UTC
Labels: vsa, vsa-public-websites
