### ISSUE TITLE
Remove getLongTermAppointmentHistory function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53088] opened 2023-02-03 21:12 UTC
In the var directory (`vets-website/src/applications/vaos/services/var/index.js`), we have a list of v0 calls we want to get rid of. 
This ticket focuses on getting rid of any usage of:
`getLongTermAppointmentHistory`.

---

## Acceptance Criteria
- [ ]  No reference to `getLongTermAppointmentHistory` anywhere in `vets-website`.
- [ ]  Remove all mocks associated with this api function (If any).
- [ ]  Remove unit test for this function (If any).
- [ ]  Remove e2e tests for this function (If any).

**Comment by jenniemc** [comment] 2023-06-05 22:55
Closing this ticket because the function `getLongTermAppointmentHistory` for v0  was also coincidentally removed in  #53080 "Remove `getConfirmedAppointments` function for v0". 

cc: @ldelacosta @simiadebowale

**Comment by ldelacosta** [comment] 2023-06-05 23:43
Thanks @jenniemc

**Closed by ldelacosta** 2023-06-05 23:43 UTC
Labels: frontend, appointments
