### ISSUE TITLE
CLP Vanity URL Request - VHA Digital Media for /healthconnect - Target date 9/25/24

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-team#93309] opened 2024-09-20 18:20 UTC
### Status
[2024-09-23] [Fran] Mikki approved Justin's vanity URL request: - [www.va.gov/healthconnect](http://www.va.gov/healthconnect) (Vanity URL request approved for implementation.)

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.

| POC | Github alias(es) |
--- | --- 
| Product team point(s) of contact: | @jilladams @TroyCMSSupport  |
| Content point of contact: | `CAIA will enter` |
| IA point of contact: | `IA will enter` |

### Type of request

- [x] We need a custom vanity URL (complete vanity URL section)

### Do you have a product technical team able to implement this redirect?

- [x] No - CAIA will need to make Public Websites aware of the ticket.

### Implementation date
When does this request need to be live? **NOTE:** Redirects in vsp-platform-revproxy auto-deploy M-Th. Friday launches should be avoided.
Choose one:
- [x] On a specific date, connected to a program or publishing requirement. **DATE: 9/25/2024 COB**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
www.va.gov/healthconnect | www.va.gov/initiatives/va-health-connect

**Link to campaign landing page request issue, if relevant:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

____

## related links
* Helpdesk slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1726847517611049
* CLP request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9169
* Prior redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9597
* JIRA service desk ticket with Justin: https://va-gov.atlassian.net/browse/VAHELP-8021

**Comment by jilladams** [comment] 2024-09-20 19:35
FYI @FranECross that I let Justin know we typically request 2 weeks' lead time on redirects, and have asked if 9/26 is a hard and fast date.
https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-8021

**Comment by jilladams** [comment] 2024-09-20 19:42
@kristinoletmuskat FYI that there was prior discussion about the IA on this vanity URL here in comments with @mnorthuis : https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9169#issuecomment-1136368754. tl;dr: 
* Original request = /healthconnect
* Mikki's proposal = [/va-health-connect/](http://www.va.gov/initiatives/va-health-connect/)

At the time, Abigail Harlow was running this CLP and agreed to that vanity URL. If y'all still feel strongly about /va-health-connect , we can let VHA DM know that's still the preference from IA, and run with that.

**Comment by jilladams** [comment] 2024-09-20 19:47
From Justin: 
> It is hard and fast. This is in conjunction with a SECVA initiative and announcement. Thank you for your partnership on this.


I've pushed back for /va-health-connect. If he has no problems with that, we can update `src` in ticket body and go ahead to implement, since that was previously signed off by IA.

**Comment by jilladams** [comment] 2024-09-20 19:49
Shared in Slack for CAIA awareness, given the timing: https://dsva.slack.com/archives/C01K37HRUAH/p1726861721042729

**Comment by jilladams** [comment] 2024-09-20 19:53
> Thanks for the update. We would prefer  /healthconnect.

We are going to need @mnorthuis 's sign off, I believe.

**Comment by mnorthuis** [comment] 2024-09-23 14:19
@jilladams I'm ok with with what Justin requested for this - www.va.gov/healthconnect

Vanity URL request approved for implementation.

**Comment by chriskim2311** [comment] 2024-09-23 21:26
@jilladams @mnorthuis Just want to clarify the landing page URL will be `/initiatives/va-health-connect` correct?

**Comment by mnorthuis** [comment] 2024-09-23 22:26
@chriskim2311 Yes!  Sorry, just updated the original request to the accurate destination URL.

**Comment by jilladams** [comment] 2024-09-23 22:34
@chriskim2311 Got a note from VHA DM that they'd like for us to get this deployed by Wed if possible. It's low risk to merge as soon as your PR is approved, since it'll go nowhere til the CLP is published anyway. 

cc @FranECross @TroyCMSSupport fysa

**Comment by jilladams** [comment] 2024-09-23 22:36
Also FYI: "The vanity URL is in support of a press conference, a monthly event hosted by the VA Secretary of Veterans Affairs. The vanity URL is planned to be referenced in spoken remarks and a press release as well."  That's on Thursday, so they're now trying to publish the CLP on Wednesday, in case they run into content-build problems, hence the earlier timing on the redirect.

**Comment by jilladams** [comment] 2024-09-24 18:46
Merged today, will deploy tomorrow, and I let Justin at VHA DM know that on our sync just now. 

Trying to reach http://www.va.gov/healthconnect should resolve correctly to http://www.va.gov/initiatives/va-health-connect in production, BUT http://www.va.gov/initiatives/va-health-connect will 404 in production until Justin publishes. That's ok. I

@FranECross FYI as this will be VERY high visibility tomorrow with VHA, while I am out. If we run into any issues with this deployment / redirect, we need to let Justin know via email and CC Michelle for awareness. HIs email = Justin.Warren@va.gov

**Comment by FranECross** [comment] 2024-09-25 15:45
Confirmed this morning that the redirect is working as expected, with the vanity URL resolving to the expected landing page.

**Comment by kristinoletmuskat** [comment] 2024-09-25 17:44
Hey @FranECross , I know I haven't been point person on this one so I could be making a mistake somewhere, but I am getting a 404 on the landing page:

http://www.va.gov/initiatives/va-health-connect

**Comment by TroyCMSSupport** [comment] 2024-09-25 18:02
@FranECross  I was just testing the vanity url as well - I see the same 404

**Comment by FranECross** [comment] 2024-09-25 18:27
@kristinoletmuskat That's my understanding, too (what Troy mentioned). The page was to be published ~ 1ish ET the build needs to pick it up. @TroyCMSSupport when is the next content release? Thanks!

**Comment by TroyCMSSupport** [comment] 2024-09-25 18:34
@kristinoletmuskat @FranECross  - The page is now published and publicly available - checking Vanity URL now

**Comment by TroyCMSSupport** [comment] 2024-09-25 18:35
@kristinoletmuskat @FranECross  - Looks like it is working now!

**Comment by FranECross** [comment] 2024-09-25 20:39
Closing; confirmed working.

**Closed by FranECross** 2024-09-25 20:39 UTC
Labels: Public Websites, sitewide, VA.gov frontend, sitewide CAIA, Redirect request
