### ISSUE TITLE
Tech Debt | Career Counseling | Refactor Veteran Information 

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#84601] opened 2024-06-04 16:41 UTC
# Tech Debt | Career Counseling | Refactor Veteran Information 
Follow on ticket to #84546

## Description
As a Veteran, I'd like to be able to logout after my claim is submitted, without causing an error that prevents my claim from being process

## Tasks
 - [ ] Add User, Veteran, and ITF information to Saved Claim at creation time
 - [ ] Migrate `veteranInformation` in SavedClaim.form_json from the sidekiq job to the controller
 - [ ] ??? Refactor sidekiq job to accept saved claim id instead of the entire form json ???

**Comment by steele-lm** [comment] 2024-07-23 20:21
Dupe of #84604

**Closed** 2024-07-23 20:21 UTC
Labels: backend, needs-refinement, Umbrella, non-disability-benefits, career-counseling
