### ISSUE TITLE
[bug spike] SC 422 error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#75213] opened 2024-02-02 17:39 UTC
## What happened? 

On Feb 2nd, at 11:22AM ET, we saw a 422 error for a failed SC submission. See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:36d3a46392494862bb9dac1f68a3e499/?environment=production&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AExceptions%3A%3ASchemaValidationErrors%3A+Validation+error+%28Common%3A%3AExceptions%3A%3ASchemaValidationErrors%29&project=3&query=controller_name%3Asupplemental_claims&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).  This would have blocked the Veteran from submitting, and shown the Veteran an error message. This is not a "silent failure" situation.

It is unclear what caused this error. IP ID is `10100269`. The Veteran started this SC on Jan 25, 2024. Their last update was Feb 2nd, 11:22AM ET (same time as the error). On first glance, their form data looks fine. 

FWIW, the error's response body contains the following:
```
tx_messages: [{
    code: ADDRVAL111, 
    key: addressBio.DualAddressError, 
    severity: ERROR, 
    text: [Filtered]
}], 
```
**Add the steps to reproduce the bug**:
1. _Add here_
2. _Add here_

**Add a screen recording or photo**:

## How severe is the problem?
- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. _When a user does X, the **visual** result is y._
2. _When a user does X, the **backend** result is y._
3. _When a user does X, the **event logging** result is y._

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by saderagsdale** [comment] 2024-02-07 19:40
- Figure out if there's a way to unblock the Veteran. 
- Time boxed spike into the root cause.

**Comment by anniebtran** [comment] 2024-07-30 22:02
Seems we may have missed a window for remediating this — I can't find the log in Sentry anymore (is there a way to pull old Sentry data? 🤔 ) and it was [never logged to DataDog](https://dsva.slack.com/archives/C05UPRR0HK3/p1706901775986459?thread_ts=1706891061.028509&cid=C05UPRR0HK3). The `InProgressForm` has likely expired and no longer exists in the database. So not sure if there's much we can do. 😞  @shaunburdick thoughts?

**Comment by shaunburdick** [comment] 2024-08-26 19:07
Close the issue, it hasn't repeated.

**Closed by shaunburdick** 2024-08-26 19:07 UTC
