### ISSUE TITLE
General Analytics Request for Caregiver Team (Health care application)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18249] opened 2021-01-07 18:31 UTC
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Alayna Abel

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    - Caregiver team (working on the health care application)

    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. after June 2020

## Analytics to Track Down
> Failures on the health care application, and how and where they are measured

## Which Product Questions are you trying to answer?
- How is the health of the health care application doing, and how has it changed over time?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
On the [Product Health Spreadsheet](https://docs.google.com/spreadsheets/d/1-1GYhR5RFItrYee2Yki_nuMW3XKYrWVzoZ8dppS3hb4/edit#gid=628587422&range=C28) there is a row for the online health care application. It lists a "Failed Submissions" rate of 0.05% and links to [this](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184318975/_u.date00=20201227&_u.date01=20210102&_.goalOption=1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=hca/) GA report.

1. 94.59%  (Successful submissions) and 0.05% (failed submissions) do not add up to 100%. Also, the GA report doesn't have a clear designation of what it means to have a failure, and I'm not sure what events are conclusive to other events. Where can I find a GA report for failed submissions on the online health care application?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment] 2021-01-07 19:05
Thanks for opening this, Alayna! Putting this on our queue to investigate.

**Comment by ala-yna** [comment] 2021-01-07 19:09
Thanks! Let me know if you have any questions :)

**Comment by joanneesteban** [comment] 2021-01-13 17:12
1. Start with the Healthcare Application

@joanneesteban add a flag to the #vfs-analytics channel that the numbers are being reviewed on this sheet.

- [ ] Check that successful + unsuccessful = 100%
- [ ] Check the links & numbers for unsuccessful
- [ ] Check the links & numbers for successful

**Comment by joanneesteban** [comment] 2021-01-13 17:13
First piece of work: technical discovery as to where the numbers are coming from & if the numbers are correct in Google Analytics.

**Comment by bmcgrady-ep** [comment] 2021-01-13 22:19
The Healthcare section of the Product Health MVP has been updated and numbers verified in GA.

**Comment by bmcgrady-ep** [comment] 2021-01-14 16:34
I have reviewed all of the links and updated each link to only include the relevant GA link. I also have reviewed the % of successful and in a few cases, the percentage is slightly over 100%.

Overall, the spreadsheet is ready to be shared out again.

**Comment by joanneesteban** [comment] 2021-01-14 17:54
Thanks for working on this, @bmcgrady-ep .

I'm not seeing that the data has been updated, and the links aren't going to the correct `failed` vs. `successful` events. 

![image](https://user-images.githubusercontent.com/48964695/104628616-6e2c9300-5666-11eb-9d48-1d0359653922.png)

Can you also share why some of the cases are still slightly over 100%?

**Comment by bmcgrady-ep** [comment] 2021-01-14 18:28
@joanneesteban - thanks for the call out, the percentage for Health Care is now updated.

Also, for the links to the GA dashboards show both the successful and failed events, like this, which I believe is how the report has always functioned:
![image](https://user-images.githubusercontent.com/66263904/104632786-358fb800-566c-11eb-9b6e-9fd7769c08e4.png)


As to why some of the cases are still slightly over 100%, it is when there are more submission-successful events coming into GA, than submission events.
Here is a screenshot in GA of this happening: 
![image](https://user-images.githubusercontent.com/66263904/104632564-e34e9700-566b-11eb-944e-0bc0776ebf1c.png)

**Comment by joanneesteban** [comment] 2021-01-14 19:50
@bmcgrady-ep got it, thanks for the clarification on the links. 

A few follow up questions:
- why would there more more successful events than total events? Or why doesn't successful + failed submissions = total submissions?
- I'm a bit confused on the percentage calculation. Should the failed calculation = ((failed submissions / total submissions)*100)?

**Comment by bmcgrady-ep** [comment] 2021-01-14 20:42
I'm not totally sure why there are more successful events than total events or why the successful + failed submissions don't always equal 100%. My best guess is that occasionally successful events are fired twice due to an error on the client-side. 

Here are the percentage calculations:
- Successful submissions percentage = submission-successful / unique total submissions
- Failed submissions percentage = submission-failed / unique total submissions

**Comment by bmcgrady-ep** [comment] 2021-01-20 17:33
@bsmartin-ep @jonwehausen Here are the reports that show the `submission-successful` events being greater than the `submission` events:
- [Edu 1990e Events](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20210103&_u.date01=20210109&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22edu-1990e--(submission%7Csubmission-failed)%22,0%5D%5D/)
- [HCA Events](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184318975/_u.date00=20210103&_u.date01=20210109&_.goalOption=1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=hca--submission/)

This is resulting in the [Product Health MVP](https://docs.google.com/spreadsheets/d/1-1GYhR5RFItrYee2Yki_nuMW3XKYrWVzoZ8dppS3hb4/edit#gid=628587422) to more than 100% for the Successful Submissions. Any thoughts as to why this would be happening would be appreciated!

**Comment by joanneesteban** [comment] 2021-02-24 16:59
@mandy-uxd & @ala-yna - moving to the backlog to clean our board for the sprint. We're looking to add a redesign of this dashboard back in when we have resources to prioritize this.

**Comment by jonwehausen** [comment] 2021-03-17 20:07
- Reassigning from Ben to Jon...

## Next Steps
- Attempt to reproduce a `--submission-successful` event with no `--submission` event to determine root cause

**Comment by laurensimpson14** [comment] 2021-05-18 21:01
Hi Alayna, 

Jon recently left the VA analytics team so I'm working through the few tickets in his backlog. I've gone through this ticket and tested the health care application 6 or 7 times. Below are my findings/recommendations/thoughts: 
* `hca--submission-failed` events can be caused by a form failing on the server-side. We have some documentation on it here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md
     * Some examples of a failure on the server-side would include outages with vets-api or a bug that has been introduced but not found in testing
* Occasionally there are more successful events than total events due to a glitch in the Google Analytics data collection. This isn't due to any tagging issues and is often not something we can eliminate altogether. We'd aim to have it close (< 5% off from total submissions = failed + successful). I went through the application 6 or 7 times, and only once was I able to get a submission that caused one and not the other - ironically it caused the `hca--submission` and not the `hca--submission-successful` (ironic because before you were seeing the `hca--submission-successful` event being higher than the `hca--submission` events. In my tests I was only able to recreate this by clicking submit & then immediately closing my browser so that the next page didn't have enough time to load. 
* Looking back at the last 5 months of data from Jan 1 to today the hca form has 83 `hca--submission-successful` events, 82 `hca--submission` events, and 0 `hca--submission-failed` events. Looking at that data and running my tests, I'd confidently say the tagging is all correctly set up and that it's as accurate as possible.
![image](https://user-images.githubusercontent.com/80417436/118722702-79512480-b7fa-11eb-8eae-fe7d0ceadb60.png)

I'm going to close out this ticket, but please open it back up if there is something I missed/didn't answer.

**Closed by laurensimpson14** 2021-05-18 21:01 UTC
Labels: analytics-insights, analytics-reporting-request, analytics-request, vsa-caregiver, vsa-hca
