### ISSUE TITLE
[Intake] Content and IA Support for Income Limits Web app from SW-Public Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#51132] opened 2022-12-22 01:05 UTC
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
We are designing a new experience that helps Veterans understand what income thresholds apply 
- for levels of free healthcare benefits
- for income-dependent priority groups (PG 5 and PG 7)

The most obvious existing content that might link to the Income Limits Web App are:
- [Cost of care](https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/)
- [Priority Groups](https://www.va.gov/health-care/eligibility/priority-groups/)

Types of content support needed:
- Possible modifications to pages that link to the new experience
- Copy for screens within the experience
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?  _Q2 2023_ (wild guess at this point, we have UX design/research and technical design ongoing)
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app)
- Link to or attach user flows: Our understanding of existing content that could flow into this is in this [Income limits Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1657807571797/ee2497db0a9c637538f51e38546ffe3eaea508c0?wid=0-1658156747937)
- Link to prototype or mockups: Latest (as of 1/6/23) is in the "Current" tab of [this sketch file](https://www.sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126)
- Link to any epics/issues that may be helpful: [Income limits epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Q2 2023
- Estimated staging review date: n/a
- Content and IA work needed by: Prototype usability testing will occur around Feb 1, 2023

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Wes Rowe
-	Designer: Jordan Wood
-	FE engineer: ?
-	Product/team Slack channel: sitewide-public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment] 2023-01-18 14:49
@wesrowe Just wanted to follow up from our call yesterday. We can work the IA and content work into this sprint, with the goal of completion by 2/1. We'll do our best to provide content feedback as we have it so you can be incorporating it into the designs as we go. Mikki will follow up on additional IA thoughts and I know you've set up a call with her. 

One thing to confirm now: We do want to include a wayfinding task in the research plan to help understand how people would navigate to this tool.

**Comment by wesrowe** [comment] 2023-01-18 17:18
@cindymerrill, FYI, see Randi's note above about a wayfinding task

**Comment by cindymerrill** [comment] 2023-01-18 17:26
@wesrowe Thanks for tagging me :).
@RLHecht I'm happy to include a wayfinding task in the user research, but I thought that @DanielleThierryUSDSVA said to not bother navigating from the VA.gov home page because how you get here is in the process of changing. Where do you recommend starting from? I believe we discussed starting at the Cost of Care page. Is there somewhere else that you have in mind?

**Comment by DanielleThierryUSDSVA** [comment] 2023-01-18 18:40
Thanks for following up to clarify, @cindymerrill! I had said that I wondered about the navigation task since we're doing a bunch of testing on navigation that will likely change the health hub a lot, but that I wanted to talk with @mnorthuis because that's her IA area of expertise/responsibility. She noted that a wayfinding task should be part of every usability test so the note above reflects our combined follow up.

**Comment by mnorthuis** [comment] 2023-01-18 19:54
Hi @cindymerrill,  as part of launching anything new on the site, we always want to include a findability task in research. That task can be framed up in whatever way works best for your research - it doesn't have to require the participant to start on the home page, they could start on an open browser tab, or another relevant starting point.  The goal is to learn what words do people use to describe or label the tool, and where do they look for or expect to find the new feature.  What we want to avoid, is placing them on the new tool with headings, breadcrumbs, and language already exposed.  Doing this as part of a task, also provides an opportunity to watch a visitor flow through the entire experience.   The governance team also looks for this task to be included as part of midpoint.

**Comment by cindymerrill** [comment] 2023-01-18 20:06
Thanks for clarifying, @DanielleThierryUSDSVA ! 
@mnorthuis I'm totally with you on the value of including a findability task. I was wondering _where_ you think might be an appropriate place to start participants from. Somewhere before the _Cost of Care_ page? The home page? By "an open browser tab", do you mean that they could proceed at first however they want--e.g., go to VA.gov, search in google?

**Comment by mnorthuis** [comment] 2023-01-18 20:44
@cindymerrill I don't know what the rest of your research looks like, so I don't want to prescribe what will work best, and I haven't had time to dig into this specific tool to understand what it even is.  Some have found it easiest to start participants on an open browser tab and let them freely go, others have found it best to start on va.gov home.  The benefit of starting at the home page is the task is focused on va.gov and avoids the wild west of google :-) .

**Comment by cindymerrill** [comment] 2023-01-18 22:05
@mnorthuis The problem with starting on the VA.gov home page is that it may be the old version of the page that's being replaced, and I'd prefer to see people interact with the new one, if it's on Production. Seems like letting people go where they want to (including google) will give us a sense for what words/phrases that Veterans come up with for this topic.

**Comment by mnorthuis** [comment] 2023-01-19 14:18
The home page redesign is a variable we can't control, just like there are other redesign efforts across the site that could eventually impact things. In the end we want to know where would they expect to find it on VA.gov, and what words do they use to describe or label it.

**Comment by kristinoletmuskat** [comment] 2023-01-26 23:24
Hey @wesrowe and @thejordanwood -- we are still finalizing the H1 with content (and thus the url, link labels, and breadcrumb), but wanted to send you what we had finalized: 

![Screen Shot 2023-01-26 at 4.23.03 PM.png](https://images.zenhubusercontent.com/63c829f1a7fcfd33a1b47c17/53871473-83c0-43b4-9b65-d26a55406538)

Let us know if you have any questions or need anything else for your testing next week.

**Comment by cindymerrill** [comment] 2023-01-26 23:51
@kristinoletmuskat Are you asking us to add an additional page to our income limits app? My understanding was that this app wouldn't screen out anyone based on income or anything else (i.e., 50% or greater service-connected disability) but will show the income limits that apply based on answers given by the user for their location, number of dependents, and whether/not they have Aid and Attendance or Housebound benefits. We don't ask people for their income and so can't screen people out based on that. 

Also, we're not testing next week but instead incorporating IA and Content feedback into the prototype so we can show it to Dave Conlon and have a Midpoint Review.

@wesrowe @thejordanwood

**Comment by kristinoletmuskat** [comment] 2023-01-27 16:58
Thanks for the update Cindy -- I think what we're proposing is that if a user's income falls above that last $90k threshhold in the prototype, that there is some content for them. 

Maybe something saying that they might still qualify for free healthcare pending disability % or those other factors you mention, or if they def don't qualify, maybe some content that links them to healthcare.gov or other resources for finding healthcare. 

Based on our current understanding of the flow (which we might have misunderstood, so pls let me know), it seems like the current prototype has a 'dead end' for the folks whose income falls above the listed thresholds. Does that make sense?

<img width="306" alt="Screenshot 2023-01-27 at 9 57 53 AM" src="https://user-images.githubusercontent.com/122126772/215147471-4001c49c-e6c7-4893-9806-e2efbfe5a453.png">

**Comment by wesrowe** [comment] 2023-01-27 18:22
@kristinoletmuskat, that makes complete sense. Can @thejordanwood expect content for that new section from your team?

**Comment by cindymerrill** [comment] 2023-01-27 18:43
@kristinoletmuskat Thank you for clarifying what you were thinking! Sounds like it could fit nicely into @thejordanwood 's results page.

**Comment by kristinoletmuskat** [comment] 2023-01-27 22:51
@wesrowe I think content will come from @aliyahblackmore on that!

**Comment by aliyahblackmore** [comment] 2023-01-30 14:46
Morning all! 

Yes, I included some suggestions, for the above $90k threshold, in my review of content.

My content suggestions for all of the screens are still with Danielle - she is doing her review!

@wesrowe @kristinoletmuskat (FYSA @DanielleThierryUSDSVA)

**Comment by mnorthuis** [comment] 2023-01-30 15:30
@wesrowe @thejordanwood @cindymerrill You should have what you need from an IA perspective for the purposes of research - the placement of this tool within the IA dictates the breadcrumb you should include in your test.  Please note that the "Your health care costs" page and this tool have different breadcrumbs because they will live in different places in the IA but link to each other in content.   We look forward to hearing results of your research, and then can refine and finalize the IA and the resulting URL for the tool, so please loop back around when that's complete.  Thanks!

**Comment by kristinoletmuskat** [comment] 2023-01-30 19:02
@cindymerrill I think we're interested in how the user navigates to this tool -- are they finding it from the costs of care and eligibility pages as we expect, or do we need to add the link to the tool somewhere else we aren't thinking?

**Comment by cindymerrill** [comment] 2023-01-30 20:01
Who from Sitewide Content and IA is interested in observing some of the research sessions? I will be sharing a spreadsheet with anyone interested that shows all the sessions, and you can sign up for the session(s) you want to observe. (I'm doing this because I need to limit the number of observers in each session.)

**Comment by aliyahblackmore** [comment] 2023-01-30 20:13
Hi @cindymerrill - I'd be happy to observe some of the research sessions!

**Comment by kristinoletmuskat** [comment] 2023-01-30 20:50
Jenny and I would love to observe too!

**Comment by cindymerrill** [comment] 2023-01-30 21:35
Jenny = Jenny Mayo?

**Comment by kristinoletmuskat** [comment] 2023-01-30 21:57
Yes!

**Comment by cindymerrill** [comment] 2023-01-30 22:14
Thank you, @kristinoletmuskat !

**Comment by wesrowe** [comment] 2023-01-31 17:16
@aliyahblackmore, checking in about @DanielleThierryUSDSVA's review of the prototype copy – we're waiting anxiously, as it will unlock our critical path. Any updates?

**Comment by DanielleThierryUSDSVA** [comment] 2023-01-31 17:27
Hi @wesrowe. We'll deliver the content recommendations on Feb 1 as promised. Thanks.

**Comment by DanielleThierryUSDSVA** [comment] 2023-02-02 04:19
Hi @wesrowe. [Here's a link to the content doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EV0sp7xc1jdEppRkPlPrn-sBv5R5Tn3GVSOtM9qV0FeCXA?e=HXuN95). Let me know if you and the team want to talk through the questions and notes. Happy to jump on a call. Thanks.

**Comment by cindymerrill** [comment] 2023-02-02 19:33
THANK YOU so much for your detailed feedback, @DanielleThierryUSDSVA and @aliyahblackmore ! With your super helpful revisions, I'll be excited to show the prototype to research participants :). 

I've responded to some of your questions in the comments and added a few of my own. I'll be discussing all the feedback with @wesrowe later today, and we may want to followup with you more after that.

**Comment by DanielleThierryUSDSVA** [comment] 2023-02-02 21:30
You're very welcome, @cindymerrill! Definitely feel free to follow up and let me know if a call would be helpful.

@wesrowe I think there's also one big open question around priority group 8. It was mentioned that priority group 8 no longer existed. But it looks like the prototype still has the use case that is equal to priority group 8 (VA health care with full copays). And we've had VHA SMEs review related pages multiple times recently and no one has said to remove priority group 8 info. So I want to just check in on that before I follow up with our SMEs in the VHA financial revenue office so we can make sure we have the latest, most accurate info across all content. If you have any additional info on that, let us know! Thanks.

**Comment by wesrowe** [comment] 2023-02-02 22:42
I second what Cindy said – this is really great work we get to lean on. I learned a ton from the copy and comments.

@DanielleThierryUSDSVA, re PG 8 – I am almost certain that nothing has changed and the existing content around PG8 is correct. I have a challenge that I'm trying to work through, in that I don't have a SME on speed dial who knows everything about income limits and eligibility. I've found one person who knows a lot, Lindsey Peace, but her day job is focused on evaluating income limits for only certain categories of Veterans. She is the person who I might have paraphrased as saying "PG 8 isn't a real thing," but also she freely acknowledges the boundaries of her expertise. It might also have been one of the tech/data-side folks on VistA.

So I have taken on a ticket in this sprint to identify VA SMEs/stakeholders who are knowledgeable enough to sign off on the Income Limits app as a whole, what questions it asks, and the results it yields for specific cases. I'd love your help with that! Add a name here, or I'll reach out to you in that other ticket.

**Comment by DanielleThierryUSDSVA** [comment] 2023-02-02 23:37
Thanks, @wesrowe! I would be more than happy to help find the right SMEs for this. I have some folks we can start with and can send an introductory email to connect you.

**Comment by DanielleThierryUSDSVA** [comment] 2023-02-03 23:26
Hi @wesrowe. I'm going to be traveling/leading some long meetings next week, so I wanted to document some thoughts and questions that are coming up for me based on the email thread with SMEs.

**Priority Group 4**
- SMEs seem to be saying that the A&A and Housebound income thresholds don't matter (as you stated in the thread). I think this maps to the question we'd raised in the content doc about the Veterans pension (which also shows in the original tool as "pension threshold" but not in the new prototype).

- Based on previously approved content, this has been my understanding of affected Veterans: If you get A&A or Housebound benefits, you get placed into Priority Group 4 automatically, regardless of your income. But your income level can still affect whether you'll pay copays for some types of care.
  - So the questions there for me are: 
    - Is that correct?
    - If yes, in those cases, does VA use the national means test threshold or the A&A or Housebound specific thresholds?
    - Is the way that the new tool is presenting the results going to be able to accurately present this?

**Priority Group 5**

- My understanding is that you could get placed into PG 5 based on income limits or if you receive VA pension benefits or if you're eligible for Medicaid programs. But again, your income level can then impact your copays.
  - So the questions there for me are: 
    - Is that correct?
    - If yes, in those cases, does VA use the national means test threshold or the Pension threshold?
    - If VA uses the Pension threshold, shouldn't we be including a question around "Do you get a Veterans Pension" in our new tool?
    - Is the way that the new tool is presenting the results going to be able to accurately present this?

- We recently received a PDF of copay requirements to audit against the previously approved copay rates information to make sure everything matches up. From my very brief review, I definitely have questions. I think before we go any further with this income limits tool, we need to get the right SMEs in the room to make sure that we have a thorough understanding of all of this so we can represent it accurately.

I'm sure I'll have more questions as we go, but wanted to capture these now. Thanks!

**Comment by kristinoletmuskat** [comment] 2023-02-06 20:56
Hello! From the IA side we were able to put out our recs (in the [IA Design Specs Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/income-limits.md)) for where this tool will live based on ya'lls updates and getting the H1 from content.

Let us know if you have any questions.

**Comment by cindymerrill** [comment] 2023-02-09 18:29
For when we resume working on the income limits app again, I added two new questions into the Word doc for Content to answer:

1. Should "Enter the zip code for where you live all or most of the year." REPLACE the field label "Zip code" that's currently right above the field in the design? Or should "Zip code" still be there, too? 
2. Similarly, should "Enter the total number of children or other family members you claim as dependents on your tax return." REPLACE the field label "Number of Dependents" that's currently right above the field in the design? Or should both lines be there?
@aliyahblackmore @DanielleThierryUSDSVA @thejordanwood

**Comment by wesrowe** [comment] 2023-03-10 17:11
@DanielleThierryUSDSVA @RLHecht, in Midpoint Review for Income Limits we got content feedback about the "feeder" pages that are already in prod – Cost of Care and Priority Groups. So I'm passing that along here in case you want to address it. It seems to me to be small style changes, and it's very clear. [Here's the ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54921).

**Comment by wesrowe** [comment] 2023-03-11 00:06
IA topic – so I think @kristinoletmuskat? I was just going over your original [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/income-limits.md). Having a lot more context now, I have questions that wouldn't have occurred to me earlier. Would this be a good place to discuss?

What I'm seeing in designs is that "Income limits" would be a link in menu-like link lists. Is the intention here? If so, I think we need to consider whether that proposed placement in the IA may make it _too easy_ for Veterans to find the Income Limits app itself. 

VHA SMEs as well as @DanielleThierryUSDSVA are concerned about the potential for the Income Limits tool to accidentally discourage Veterans from applying for benefits they would _automatically_ qualify for – e.g., a Veteran with 50% disability rating. We have been discussing internally that we want Veterans to link from content that makes it clear that income limits might not apply to them at all. If Veterans might find the tool more easily, i.e., from a menu, we might consider adding stronger content on the tool's first page indicating "this may not apply to you for these reasons..."

Don't worry @thejordanwood @cindymerrill, this would be post-research.

**Comment by kristinoletmuskat** [comment] 2023-03-13 14:36
? The health hub page and the left nav, where we recommended slotting this tool.
<img width="731" alt="Screenshot 2023-03-13 at 8 32 21 AM" src="https://user-images.githubusercontent.com/122126772/224732593-eff0dab6-23c6-4ea7-8b66-3fcc2c0900bd.png">
<img width="446" alt="Screenshot 2023-03-13 at 8 32 25 AM" src="https://user-images.githubusercontent.com/122126772/224732599-4fffd9af-0f06-4f7f-91be-09f6d467a616.png">

I think regardless of whether we decide to keep the tool in the hub or left nav, it might make sense to add stronger content to the beginning of the tool. A user might click the link after just scanning the content, or with an incomplete understanding of who the tool is for, and having that second 'this may not apply to you' could be helpful. 

And I see your point about making it too easy to find -- it makes sense to me. I'm going to tap @mnorthuis just to confirm there's not something I'm aware of that would prevent that. Mikki, do you think we could remove the link from the hub page and left nav? What downsides are we not considering?

**Comment by wesrowe** [comment] 2023-03-14 18:17
Thanks for the discussion and clarification! @DanielleThierryUSDSVA, we can discuss this further after research and as we finalize design and content for release.

**Comment by wesrowe** [comment] 2023-04-15 00:21
Hi @DanielleThierryUSDSVA @RLHecht - I want to give you the heads-up that there will definitely be a need for content changes in the Income Limits app based on the user research sessions. Cindy concluded user research on Wednesday and is working on synthesis during this sprint.

**Comment by cindymerrill** [comment] 2023-04-28 23:45
@RLHecht @aliyahblackmore As promised, here is my Income Limits research report with all the recommendations, many of which involve Content or IA: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/research-findings.md#recommendations

Feel free to reach out if you want any clarifications. 
FYI @wesrowe @thejordanwood

**Comment by kristinoletmuskat** [comment] 2023-05-01 20:08
Woo thanks so much @cindymerrill for sharing these detailed findings on income limits! Here are my comments on the recs that impact flow/IA:

**For the app design and functionality**
1. Clarify and sequence the two calls to action on the results page by focusing first on selecting an income range, and second on applying for VA health care. To do this, consider moving the "Note" text ("You'll still need to meet basic eligibility requirements to enroll. To find out if you're eligible, apply now") and the Apply for VA health care link to inside every income accordion, right after the benefits description.
- **Agree that the note is a little distracting from the main CTA, but not sure if putting the note in every accordion is the right move, because if ppl are exploring diff options for diff income levels it might be annoying or make the criteria seem extra confusing. Though granted, that is an edge case.**
- ![Income limit results page with Note section circled](https://user-images.githubusercontent.com/122126772/235521118-6d46b3d7-f9f6-4672-a41a-aa1495f7a42e.png)

2. Because Veteran participants didn't realize that they could deduct expenses from their income and didn't open How to estimate your income for this tool on the results page, remove the additional info component and change this into a heading or plain text to make the content below visible without requiring any user interaction. See Content recommendation #9 below.
- **Agree, but might want to make this section bulleted so users can scan what to deduct**
- ![Income limit results page with 'How to estimate your income' section circled](https://user-images.githubusercontent.com/122126772/235521377-ffe14b21-8cd0-479c-93ee-caafea812a60.png)

3. Consider making the Review the information you entered link into a breadcrumb at the top of the page where it won't separate the instructions and the CTA to select your income range. Maybe check how other VA.gov pages enable you to navigate to the review page. Need to discuss with the Sitewide Content/IA team.
- **Agree that this isn’t the best spot, but this suggestion does break the breadcrumb pattern. @mnorthuis do you have any guidance here about whether or not we can mess with the breadcrumb pattern?**
- ![Income limit results page with 'Review' section circled](https://user-images.githubusercontent.com/122126772/235521589-1c0be12b-3fd8-4277-8b90-8214aca2cfee.png)

4. If someone navigates from the Review Info page to another page, the Continue button should take you back to the Review Info page instead of to the next question (which was intended as the design but wasn't implemented in the click-through prototype).
- **Agree**

5. If we want the Get past income limits link to be easier to find, consider moving it up higher on the results page, or possibly add a year selector to the app flow right before asking any questions. Another approach would be to place the link on the intro page under the Get started CTA and instrument it for analytics so we will be able to track its usage in Production.

**- Do we want it to be easier to find? How common is this usecase?
- I think putting it on that first page could be helpful – but might need to customize the Get Started button to be like “get current income limits” or something. I’m not sure it’s clear why a veteran would want to see past income limits.** 
- ![Income limit results page with 'Past income limits' section circled](https://user-images.githubusercontent.com/122126772/235521820-948c59e1-339a-49e4-83a8-d2d7ffca495a.png)
- ![Income limit starting page with arrow pointing to potential location of past income limits section](https://user-images.githubusercontent.com/122126772/235521885-b5701112-e4c0-40b3-9140-c3ada627734b.png)

**Comment by cindymerrill** [comment] 2023-05-01 21:00
@kristinoletmuskat Thank you for your IA/flow thoughts! I'd like to respond to some of what you wrote... 

1. About moving the eligibility note (and Apply for VA health care) into every income accordion, @thejordanwood is planning to mock up a new version of the results page, so we can all see how that might look. In my research, all participants opened up multiple income accordions and compared them, and so we'll need to see if the note plus apply link might get in the way of that. Seems like we want both there for what to do next, but it's less helpful while first viewing the benefits.
2. Danielle already suggested a bulleted version of the expense deduction block of text [in slack here](**url**), which looked like this: 
![image](https://user-images.githubusercontent.com/69914583/235529017-e28e4d76-a402-48d3-8d37-fbf6fa612047.png)
3. About a potential breadcrumb with "Review the information you entered", we were thinking about potentially having the breadcrumb on every page in the app be the title of the _previous page in the app_, rather than all of them saying the same name of the page that launched the app in the first place ("Your health care costs" in the prototype), which wasn't used by any participants.
5. As far as we understand, getting past income limits isn't a common use case but one that Dave Conlon wants there for transparency. I agree with your suggestion about making the "Get started" link more specific to the current year if a way to get past income limits is directly below. 

FYI @wesrowe

**Comment by kristinoletmuskat** [comment] 2023-05-02 19:40
Thank you @cindymerrill! I'm gonna need to chat with Mikki about the breadcrumbs and she's out this week at an OCTO offsite. I can get back to you next week with our IA POV on that, but totally understand why you want to try it.

**Comment by kristinoletmuskat** [comment] 2023-05-09 19:45
Hey @cindymerrill , I just talked to Mikki and here's what we need to consider re:breadcrumb.

The breadcrumb is a standard component that links to a parent page, and we can't break the standard component by replacing the parent page with the individual workflow pages of the income limits app. Doing that would cause the income limits app to have a diff type of IA than the rest of the forms on VA.gov. Here is more info about [how to use the breadcrumb component within the guidelines](https://design.va.gov/components/breadcrumbs).

Here's an example from the Disability application -- you can see that regardless of the step in the workflow, the breadcrumbs stay the same "Home> Disability Benefits > File for disability compensation"
![Screenshot 2023-05-09 at 1 35 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/0832b19e-db6c-4e84-a2d2-526d3ad6d5e6)
![Screenshot 2023-05-09 at 1 36 10 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/d2e307cf-d50c-45be-ac3f-9b0001f44f1d)

However, I understand the problem ya'll are trying to solve, and why changing the breadcrumb seems like a good option! I don't think the initial recommendation will get approved in staging, but here are some other options that come to mind.

1. Could we add a 'back' button to the bottom of the page to go back to the workflow? 
2. Could we add the "Review the info you entered" link higher up on the page?
3. Ya'll could consider creating an [experimental component](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns) to solve for this issue -- I believe the navigation for our form flows is a known issue so that might be worth exploring! Maybe a version of the [progress bar](https://design.va.gov/components/progress-bar/) that is clickable could work.
4. Maybe chat with the design system folks and see if they have other ideas of components we could use, or guidance on creating an experimental component.

**Comment by cindymerrill** [comment] 2023-05-09 20:04
Thanks for your reply, @kristinoletmuskat ! I'll need to discuss this with @thejordanwood and @wesrowe .

**Comment by cindymerrill** [comment] 2023-05-09 20:19
@thejordanwood @wesrowe Do you want to meet to meet to discuss this?

**Comment by DanielleThierryUSDSVA** [comment] 2023-05-25 00:39
Hi @wesrowe @jilladams @cindymerrill @thejordanwood.

Adding link to the [Word doc with my recommendations and our collaboration notes](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EQkKAzpgy3NCoJceETaGz5wBplRB32omIVJagahQl0sBmQ?e=MoJIDI) for reference.

Also wanted to share a working [preview of the main entry point page](http://preview-prod.vfs.va.gov/preview?nodeId=672). As I noted in my recommendations, we're going to be rethinking this whole page as part of some broader IA/content strategy work. But in the meantime, it's a very old page that was due for a refresh. I'm going to do a bit more with this, but feel free to take a look if you'd like. And then we'll need a SME to review. Do we want to work with your SMEs for the income limits tool or would you like me to reach out to others in VHA?

**Comment by cindymerrill** [comment] 2023-05-25 16:38
@DanielleThierryUSDSVA Your revised **Your health care costs** page looks a LOT shorter! And it looks like income limits is now only one link: **Learn more about your income and VA health care**. I like how you moved some of the old long content into question accordions at the bottom.

**Comment by DanielleThierryUSDSVA** [comment] 2023-05-25 19:41
@cindymerrill Yeah, I did a bit more than I initially intended (once an editor, always an editor - ha!). :)

**Comment by thejordanwood** [comment] 2023-06-07 18:32
@DanielleThierryUSDSVA @wesrowe I started this in [a slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1685475663652649), but wanted to put it here so we can all keep up with it. We're in need of additional copy for a couple of spots. 

- Results screen: bullet points that give a brief income sources summary and a deductions summary 
- Year selector screen: this had an older version of copy that was very similar to the start screen. Now that the past income limits flow entry link has moved to the start screen, this probably needs to be updated. 

Here's a link to the [Income Limits Sketch](https://sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126) file that shows the flow. 

Results Screen
![results page](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104526584/42940f38-d835-443d-8434-d18fe63daee8)

Year Selector Screen
![year selector](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104526584/5ab27b27-bd60-442d-b2cf-afaa3aa7c258)

**Comment by wesrowe** [comment] 2023-06-14 00:19
@kristinoletmuskat, I have a draft of URLs for the sub-task screens for the income limits app. (These are obviously on top of the base URL for the app, which is TBD.) Lmk if these are adequate?
  - Year screen - /year
  - Zip code screen - /zip
  - Number of dependents screen - /dependents
  - Review Info screen - /review
  - Results screen - /results

**Comment by kristinoletmuskat** [comment] 2023-06-14 15:36
@wesrowe yes these look good to me! I can update our IA spec doc today with the URLs and final IA decisions for you to review.

**Comment by DanielleThierryUSDSVA** [comment] 2023-06-14 17:17
Hi @thejordanwood @wesrowe. Content for the results screen intro:

# Your income limits

We use your last year’s household income, minus deductions, to determine your VA health care eligibility and costs. First, estimate your household income for 2022. Then select your income range to find out how your income may affect your eligibility and costs. But remember, the only way to know for sure is to apply.

How to estimate your household income:

- Add up all the money your household earned in 2022 from jobs and other sources. Your household includes you and your spouse and dependents if you have them. 
- Then subtract any deductions you had in 2022. You can deduct some health care costs you didn’t get paid back for, expenses for your own college or vocational training, and any funeral or burial expenses for a spouse or dependent child.

Learn more about income limits and deductions [link to new R&S page - [preview link](http://preview-prod.vfs.va.gov/preview?nodeId=57286)]

**Comment by thejordanwood** [comment] 2023-06-16 20:16
Thanks @DanielleThierryUSDSVA! I've added that copy into [the Sketch file.](https://sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126) Let me know if there's anything I should do on my end to help with the copy on the year selector screen in the past income limits flow.

**Comment by wesrowe** [comment] 2023-06-17 00:32
Note: in a [slack discussion](https://dsva.slack.com/archives/C52CL1PKQ/p1686942540466519?thread_ts=1686155581.933409&cid=C52CL1PKQ) we cleared up that the first screen will have the path `/introduction`.

**Comment by wesrowe** [comment] 2023-07-03 19:54
@DanielleThierryUSDSVA @coforma-terry – I got a question from Randi H recently about whether we would be phasing the release of the Income Limits app. FYSA we decided not to phase, as the app is replacing missing functionality and it's relatively low-risk.

**Closed** 2023-07-25 22:37 UTC
Labels: Public Websites, sitewide content, sitewide CAIA-product support, Sitewide IA, sitewide CAIA

**Comment by wesrowe** [comment] 2023-08-16 23:26
@kristinoletmuskat, I noticed in the [IA design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/income-limits.md#redirects-) that a redirect is required for Income Limits. That redirect obviously shouldn't come before the app launches. But how closely is it required to follow? (hours/days)

**Comment by kristinoletmuskat** [comment] 2023-08-18 18:30
@wesrowe The redirect can happen any time after the new tool launches.  We'd only want to really time out the redirect if the launch was going to create a 404, which it won't in this case. So the only thing we are dealing with here is two duplicate pages, so the sooner we can get the redirect up, the sooner the old page goes away from search results -- there's no specific day/time requirement.
