### ISSUE TITLE
IA and Left Navigation for Decision Review Pages and Legacy Appeal Pages

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4141] opened 2019-12-11 17:50 UTC
Note:  this will be done AFTER February 19 AMA Updates go live.

@jenniferlee-dsva @Karak888 will fill in with details.

**Comment by Karak888** [comment] 2019-12-13 19:42
@kevinstachura Kevin is conducting user research sessions and gets better understanding of how they use the content - Looking at analytics for baseline - Websites team needs caseflow training.

**Comment by Karak888** [comment] 2020-01-02 19:44
@jenniferlee-dsva can we please pull up about this one to see what needs to happen next.  Thanks

**Comment by jenniferlee-dsva** [comment] 2020-01-03 15:46
@Karak888 Hello! Do you mean sync up? Yes. The convo w/Andrea and Kevin Satchura and Laura wrt nav was that we would circle up with Kevin once his user research was completed and get his input re labels and Veteran mental model for HLR, appeals and DRs in general. Then take another look at the previous IA recommendation (which was made several months ago prior to research) and implement as-is or with modifications if needed. We should include Mikki in that convo as well. But happy to sync up with you first.

**Comment by Karak888** [comment] 2020-01-07 15:05
@jenniferlee-dsva was just following up from sprint planning last week!  We are good :) thanks!

**Comment by jenniferlee-dsva** [comment] 2020-01-07 17:12
See slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1578416398453700 

Also adding related nav ticket that somehow got delinked: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3822

^ Mikki's original IA recommendation -- to review with her in context of Kevin's user research findings.

**Comment by lwalsh617** [comment] 2020-01-22 18:28
Adding Kevin Stachura's Slack post here for ease of tracking next steps:
![image](https://user-images.githubusercontent.com/53535663/72922476-17be9a00-3d1b-11ea-9d68-f394d36935be.png)

**Comment by kevinstachura** [comment] 2020-01-22 18:36
Thanks @lwalsh617 ! Also I will repost the GH link to the research folder:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/research/website-research

**Comment by MickinSahni** [comment] 2020-01-29 19:00
Not moving forward until we have user research from B&M 1 on IA/language

**Comment by mnorthuis** [comment] 2020-02-14 15:40
Original IA recommendation will need to be reviewed when this is picked back up.

**Comment by jenniferlee-dsva** [comment] 2020-02-25 22:30
Adding @AkucherGCIO and @mnorthuis - as this will need to be pulled into next sprint upon AMA Feb 19 updates going live (eta this week).

**Comment by AkucherGCIO** [comment] 2020-02-26 19:46
@AkucherGCIO  - It needs to be converted to an Epic because of the IA changes needed.

**Comment by kevinstachura** [comment] 2020-03-04 18:34
Thanks @lwalsh617 ! Also just wanted to add the website analytics that we ran late last year, that may also give some good insights!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/decision-review-va-gov-website-analytics.md

**Comment by mnorthuis** [comment] 2020-03-04 22:41
@lwalsh617 IA definitely needs to be reviewed based on recent AMA changes as well as learnings from the January research.  Happy to jump on a call to go over research findings and determine if additional research is needed.

**Comment by lwalsh617** [comment] 2020-03-05 16:57
^ Thanks, @mnorthuis. I'll set up a call. Also, Fred Somers emailed me asking for an ETA on IA recommendations. We can chat on our kick-off call today about timing. I told him I'd get back to him today, once I confirmed timing with the rest of the team. Thanks!

**Comment by AkucherGCIO** [comment] 2020-03-10 19:32
@lwalsh617 @mnorthuis - Is this ticket ready to be completed in this Sprint ?

**Comment by mnorthuis** [comment] 2020-03-10 23:17
A draft IA and wireframe has been created for review with Jen first, then Fred as appropriate.  
https://app.moqups.com/Rnc4BDEKrA/view/page/a5e3c0342

Once the proposed approach has been reviewed and approved, then I can document the full IA recommendation.

**Comment by AkucherGCIO** [comment] 2020-03-11 17:12
03/11/20 Sprint 17 Planning
- We have initial proposal from Mikki and so new ticket will be created for presenting to the stakeholders and implementation.

Closing this ticket as the new ticket will be created for next sprint.

**Closed** 2020-03-11 17:12 UTC
Labels: content-ia-team, vsa-public-websites
