### ISSUE TITLE
[CAIA Intake] Public Websites: Outreach events

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#98129] opened 2024-12-02 20:36 UTC
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Your team

- **Product name:** Outreach & events
- **Team name**: Sitewide Public Websites
- **OCTO product owner:** Michelle Middaugh
- **Product manager:** Fran Cross
- **Designer(s):** Dave Pickett
- **Slack channel:** [#sitewide-public-websites](https://dsva.slack.com/archives/C52CL1PKQ)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** Laura Flannery

## CAIA specialists involved
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  

### What's the nature of your initiative and desired outcomes?
`Tell us briefly about your work and the outcomes you’re aiming to achieve.`

We'd like to have content/text updated in the Outreach events page. On 10-27-2023, VHA DM emailed with feedback that some content on the “Outreach events” page seemed to be off or out of place. See below for details:

- On this page, https://www.va.gov/outreach-and-events/events/, the following paragraph appears, but it doesn't seem to fit with the purpose of the page. Was this content intentional?

  - ”VA benefits can help Veterans and their families buy homes, earn degrees, start careers, stay healthy, and more. Join an event for conversation and information.”

Per Danielle, this has been the content since 2021. This could be an opportunity for some quick tweaks (like "Find an event..." instead of "Join an event" since it's a search tool and maybe making a stronger connection between benefits and events). So maybe something like:

- VA benefits can help Veterans and their families buy homes, earn degrees, start careers, stay healthy, and get support throughout every stage of life. We hold events online and across the country to support Veterans and their families—and help Veterans and their families understand and apply for the benefits they've earned and deserve. Find an event to join to learn more.

(or maybe we don't even need that first sentence)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content. FOR FIGMA/MURAL: please tell us which screens/board/section to look at so we don't leave comments on old stuff. 
- [Supporting artifact<name>]

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We aren't currently working on an initiative - we'd just like to update the text to enhance the Veteran experience.

`Enter your description here`

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket N/A

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number:** 

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
- [ ] Please don't close this intake when work is complete - CAIA will close and track

**Comment by kristinoletmuskat** [comment] 2024-12-02 20:49
Confirmed no IA in this one!

**Comment by FranECross** [comment] 2024-12-02 21:02
> Confirmed no IA in this one!

@kristinoletmuskat Should we have our designer/ux person review and suggest updates? We were hoping for a CAIA review of the content they pointed out to suggest updates or let us know if we should leave it as is. Thanks!

**Comment by kristinoletmuskat** [comment] 2024-12-02 21:26
Hey @FranECross , sorry for the confusion! I just reviewed this ticket to see if there was any information architecture work, but it seems like it's just content. So it will get prioritized in our content backlog in the next few days. We have refinement tomorrow and can prob give you a better sense of priority then.

**Comment by FranECross** [comment] 2024-12-03 19:03
@kristinoletmuskat Oh! Now I totally understand. Thanks for the explanation! My brain didn't process you'd only referenced IA. :) Thank you!

**Comment by aprocik1** [comment] 2024-12-04 14:02
@FranECross, here's my recommendation:

> You can join our outreach events to learn about VA benefits, meet other Veterans, and more. Find in person and online events to join.

I think we need to broaden the scope of this content, since not all events are about benefits. What do you think?

**Comment by FranECross** [comment] 2024-12-09 19:04
> [@FranECross](https://github.com/FranECross), here's my recommendation:
> 
> > You can join our outreach events to learn about VA benefits, meet other Veterans, and more. Find in person and online events to join.
> 
> I think we need to broaden the scope of this content, since not all events are about benefits. What do you think?

@aprocik1 I agree! That's a great recommendation.

**Comment by aprocik1** [comment] 2024-12-16 14:20
Fran, I'm closing this ticket as complete. If there's more work left, I can reopen it. Thanks for your collaboration on this!

**Closed by aprocik1** 2024-12-16 14:20 UTC
Labels: Outreach Hub, sitewide content, sitewide CAIA
