### ISSUE TITLE
Readiness probe scripts for cert validation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#53468] opened 2023-02-10 14:01 UTC
## Description

Since we have had quite a few missing certs in staging EKS, for the prod rollout, we should create a readiness probe on container startup to verify that the expected certs exist before pod rollout. We can manually verify, but an automated solution is ideal.

**Comment by laineymajor** [comment] 2023-02-27 17:45
Duplicate of other ticket

**Closed by laineymajor** 2023-02-27 17:45 UTC
Labels: platform-tech-team-1
