### ISSUE TITLE
Update Access Documentation, so it is clearer for non technical readers 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#7044] opened 2020-03-20 12:28 UTC
## User Story or Problem Statement
As a member of VSP or VFS, I want to have clear documentation around how to access the tools I need, to that I can have more access to data from the site.

Ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7043#issuecomment-601476061

## Goal
_Work with the content team to update access docs so they are in more plain language_

## Acceptance Criteria
- [x] _Update docs so non-techincal users can follow the steps_
- [x] _Add section for Windows users_
- [x] _Test with a few users to see if they can follow along_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment] 2020-03-30 12:42
This was tested by @rroueche and confirmed the directions were easy to follow and worked as intended. All objectives for this have been met at this time. Closing.

**Closed by jbritt1** 2020-03-30 12:42 UTC
Labels: operations
