### ISSUE TITLE
[FE] Time selection inline validation error

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91914] opened 2024-08-30 16:26 UTC
## Tasks

- [x] Build out FE for time selection inline validation error. E.g., Veteran attempts to book an appointment at the exact date and time as another scheduled appts from VAOS Backend Service. 
- [ ] auto-format that phone to use the tel attribute
- [x] Remove `please`

[Figma design](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3713-15747&t=aTFq7GXGZD2emePW-4)

**Comment by brianseek** [comment] 2024-09-16 21:08
@benbrasso-agile6 would it make sense to just not have those slots as options instead of letting the patient click it then get an error?

**Comment by benbrasso-agile6** [comment] 2024-09-16 21:14
YES! However, my take was that this is work not required for MVP and/or higher level of effort. I know @cgednalske and @Cieramaddox would be happy if we could make this work (i.e., so long that we're sure we're catching all existing scheduled appts for all appt types and across VistA and EHR for a Veteran).

**Comment by brianseek** [comment] 2024-09-16 22:20
@benbrasso-agile6 Its not an inconsequential amount of work, so if its not MVP, lets move this ticket to the backlog. The ideal solution can then be evaluated when the work gets picked up after MVP. 

Other things to consider with this:

- appointment span
- appointments that are within x time frame of an existing appointment should maybe have a warning
- perhaps the patient would like choose to schedule with a specialist in a preferred slot and reschedule the existing VA appointment.

**Comment by brianseek** [comment] 2024-09-16 22:29
Just removing the dates as options is as easy as the inline error, and saves users from an error. Your call though.

**Comment by benbrasso-agile6** [comment] 2024-09-16 22:30
Although, all the BE logic sits with the BE VAOS Team, I believe. But, can show on staging the error page with alert, if needed.

**Comment by brianseek** [comment] 2024-09-16 22:30
I don't need to see it.

**Comment by benbrasso-agile6** [comment] 2024-09-16 22:31
The fallback here would be using that approach, e.g., error page with alert. But, not an awesome UX. But, doable for MVP.

**Comment by brianseek** [comment] 2024-09-16 22:33
yeah lets not do that. There is no blocker here. If this is within scope of MVP, we can do either an inline error when the patient selects a slot with an existing appointment. Or we can just remove those slots that conflict with existing appointments as options. Both are the same amount of work

**Comment by benbrasso-agile6** [comment] 2024-09-16 22:36
Go with the blank out of dates approach then. 

Then, your work can be used for oracle health scheduling potentially too. FYI @outerpress @melissa-lefevre

**Comment by brianseek** [comment] 2024-09-16 22:37
@benbrasso-agile6 Sounds good, I will do that and update the ticket details later! Thanks!

**Comment by cgednalske** [comment] 2024-09-16 22:54
Hello 👋 - jumping in because I believe a reason we didn't want to remove those slots (discussed in platform office hours) was because someone might really want that time for community care and deem it more important than their other overlapping appointment. So then if they wanted they could cancel that other appointment to get the time slot.

**Comment by cgednalske** [comment] 2024-09-16 22:55
I'm not sure where we landed in this ticket convo here but wanted to throw that out there 😄

**Comment by brianseek** [comment] 2024-09-16 23:05
@cgednalske that was a point I was making in my other considerations. So in that case should it just be a warning and not a blocking validation error?

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:06
We can't support that flow right now. I.e., too complex. 

I feel like not allowing them to select the day is more ideal than an inline error. But, I could be persuaded otherwise.

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:07
Oh, like the inline error tells them they have an appointment already. I can see that being more valuable than just not having the day selectable. 

Lol, sorry Brian. 

@cgednalske you want to go with the inline error then?

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:08
I don't think we have approvals or designs to support canceling an existing appointment. Keep it simple to start with.

**Comment by brianseek** [comment] 2024-09-16 23:11
We could just show a warning, but let them book the slot. The warning would let them know that they need to cancel/reschedule the other existing appointment with the VA.

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:16
Yeah, I believe that's what's documented in Figma.

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:17
The BE services won't allow them to double book to my knowledge.

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:17
Believe that would require working with BE VAOS Team.

**Comment by brianseek** [comment] 2024-09-16 23:19
oh right, I forgot about the backend validation. Ok lets go with the original plan. But you may want to give some information on how the patient can go about booking that slot, in absence of that information it feels like we are creating a frustration point by allowing them to select it at all.

**Comment by benbrasso-agile6** [comment] 2024-09-16 23:26
Yeah, I thought we addressed it in the error message. But, yeah, we can add something in the backlog to switch up the content.

**Comment by benbrasso-agile6** [comment] 2024-09-17 15:39
Agreed. I think Brian had some good suggestions though to maybe tweak it, if needed, after release.

**Comment by benbrasso-agile6** [comment] 2024-10-09 17:52
LGTM, cc @cgednalske @Cieramaddox

**Comment by benbrasso-agile6** [comment] 2024-10-09 20:42
Thx for jumping in Christina

**Comment by brianseek** [comment] 2024-10-09 21:10
@cgednalske that's not how the component works, I think in this case the figma should be updated to match who the error looks in the actual component.

**Comment by benbrasso-agile6** [comment] 2024-10-09 21:16
I was kinda thinking the same. Really depends what's feasible since it's not a DS component.

**Comment by cgednalske** [comment] 2024-10-09 21:18
I know :/ but when @Cieramaddox went to office hours, she and Brian D. (a11y) determined the text should be move/made custom for this calendar to be closer to the item the Veteran had actually selected - otherwise it'd be too far away and easy to miss. That's all I know, so I'll let @Cieramaddox weigh in on the decision.

**Comment by brianseek** [comment] 2024-10-09 21:21
@cgednalske that should be a new ticket then. This calendar picker component is used widely in VAOS and should maybe be done by that team to cover those use cases and regression

**Comment by benbrasso-agile6** [comment] 2024-10-09 22:44
Good convos. Keep MVP in mind :)

**Comment by loripusey** [comment] 2024-10-10 14:43
@benbrasso-agile6 @cgednalske @brianseek If we are happy with the FE work for now and any add-on work is NOT part of the MVP, can someone 

1. Create a ticket for any f/u work and add it to the Appts team's backlog
2. Close this ticket

**Comment by brianseek** [comment] 2024-10-15 17:35
Closing this ticket since the scope was just the error and the component changes have been passed to VAOS

**Closed by brianseek** 2024-10-15 17:35 UTC
Labels: frontend, HCE-Checkin, engineering, appointments-cc-direct
