### ISSUE TITLE
Copy and Enable scheduled content release to GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24193] opened 2021-05-04 19:35 UTC
## Description
There is a [content release schedule](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy#automated-deployment-schedule) in Jenkins that follows the schedule: `9am-12pm Hourly, 1:45pm, 4pm, 5pm ET M-F`.

This should be copied to a new GitHub Actions workflow that runs on the same schedule.

## Acceptance criteria
- [x] Content-only releases occur in GitHub Actions on the same schedule as its Jenkins counterpart.
- [x] The scheduled content release in Jenkins is deprecated.
- [x] The Slack notifications continue to notify the relevant stakeholders.

**Comment by oseasmoran73** [comment] 2021-08-18 17:28
Content-release follows scheduled outline (https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L11-L12)

Ticket will remain open once Jenkins ready to be deprecated

**Comment by oseasmoran73** [comment] 2021-10-29 21:32
Adding [slack](https://dsva.slack.com/archives/C01512KN35G/p1635529221019000) convo with CMS team

For this ticket, we want to make sure content-release and daily-deploy "communicating with one another -- mirror similar queue how Jenkins is.

E.x: if content-release is `in_progress` and daily-deploy kicks off, wait until `in_progress` is completed. Vice versa, if content-release is kick off and daily-deploy is `in_progress`, wait until it is completed. This only applies specifically for `prod` instance.

**Comment by oseasmoran73** [comment] 2021-10-29 21:33
[PR](https://github.com/department-of-veterans-affairs/content-build/pull/498/files) for daily-deploy configuration

**Comment by indytechcook** [comment] 2021-11-01 13:53
Linking the manual release from the CMS ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6354

**Comment by oseasmoran73** [comment] 2021-11-01 15:21
[PR](https://github.com/department-of-veterans-affairs/content-build/pull/715) recently merged to add concurrency to content-release. Testing out flow

**Comment by oseasmoran73** [comment] 2021-11-01 19:05
[PR](https://github.com/department-of-veterans-affairs/content-build/pull/720) recent;y merged to add content-release and daily-deploy (`prod` only) to be queued accordingly

**Comment by oseasmoran73** [comment] 2021-11-10 15:45
Closing this ticket as content-release has been transitions into Github Actions.

@indytechcook Please reopen this ticket if your team runs into any issues

**Comment by oseasmoran73** [comment] 2021-11-10 16:37
Reopening ticket due to edge case detected. See [Slack](https://dsva.slack.com/archives/C0MQ281DJ/p1636560794171100?thread_ts=1636560639.170300&cid=C0MQ281DJ)

**Comment by oseasmoran73** [comment] 2021-11-16 17:11
Closing ticket as production deploy is now live in Github Actions 🎉

**Comment by oseasmoran73** [comment] 2021-12-01 18:15
Reopening this ticket as there is issue with GovDelivery Callback

**Comment by oseasmoran73** [comment] 2021-12-01 22:19
Fix for GovDelivery Callback https://github.com/department-of-veterans-affairs/content-build/pull/802

Confirmed it is successful in this flow https://dsva.slack.com/archives/C0MQ281DJ/p1638394280430000

Closing out ticket

**Closed by oseasmoran73** 2021-12-01 22:19 UTC
Labels: tools-fe
