### ISSUE TITLE
Design Feedback - Staging Review VAOS - Homepage Refresh

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#26414] opened 2021-06-22 14:35 UTC
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I am sure users will appreciate all their appointments in one place.
- Making the whole card clickable is new in the VA design system. Can you please document and put it in the experimental tab?

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The screen shot shows a mix of the 2 link styles. Either bold the word “Details” ([active link style](https://design.va.gov/experimental-design/action_links#active-links)) or remove the chevron ([default text link style](https://design.va.gov/experimental-design/action_links#default-links)). 
- ![Screen Shot 2021-06-21 at 3.18.51 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/86d62889-487a-4749-a77a-b2946b9f301c)
- Start scheduling should be an [action link](https://design.va.gov/experimental-design/action_links). You could use the green one if you want.
- ![Screen Shot 2021-06-21 at 4.20.20 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/3f310883-4828-48e9-94b2-55bd3bd6425b)

**Should:**
- Use the standard alert styles. Background only alert styles are reserved for immediate feedback only.
- ![Screen Shot 2021-06-21 at 3.22.16 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ddf824d8-b171-45b8-8285-425184db92b0)

**Consider:**
- Moving the details text link below the content and left align on the card. The link is far away from the content when it is right aligned.
- There is too much spacing inside the content on the cards. You may want to consider using a 2 column layout or shortening your 1 column
- Check the focus state on the ‘Past’ drop down

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by outerpress** [comment] 2021-06-22 19:47
Thanks @allison0034! Notes below:

> The screen shot shows a mix of the 2 link styles. Either bold the word “Details” (active link style) or remove the chevron (default text link style).

Sounds good, we can use the active link style.

>  Start scheduling should be an action link. You could use the green one if you want.

We implemented the action link and removed it previously due to some accessibility concerns. For this work we’re going to stick with the primary/blue button, and after the home page refresh we’ll look at revisiting the action link with some user testing (possibly along with a broader UAT effort) to validate.  

> Use the standard alert styles. 

As discussed IRL we’ll leave as is and I'll document VAOS' needs for this kind of alert/notification/status message for the platform

> Moving the details text link below the content and left align on the card. The link is far away from the content when it is right aligned.

This design tested well during initial usability testing, though that was on mobile (and we’ve since moved the link under the text on mobile) We'll look at this pattern after release as we may identify additional issues we want to address with the cards.

> There is too much spacing inside the content on the cards. You may want to consider using a 2 column layout or shortening your 1 column

We’ll look at a different column layout and link to this ticket if we go that route before release. But similar to the above, we’ll likely keep an eye on this and make adjustments after.

> Check the focus state on the ‘Past’ drop down

Could you clarify the issue here, or is this captured elsewhere?

**Comment by allison0034** [comment] 2021-06-23 16:08
@outerpress when you select 'Past' in the drop down the focus state stays on that drop down even though another drop down for date range. We weren't sure if it should be on the date range drop down or not.

**Comment by laurenernest** [comment] 2021-06-23 17:28
@allison0034 I thought we weren't supposed to automatically shift focus on a user, but I could be misremembering or thinking of a specific scenario.

Can we get an accessibility ticket written up by @1Copenut @noahgelman with the expected behavior/implementation if we have to adjust?

cc @outerpress

**Comment by allison0034** [comment] 2021-06-23 19:37
@laurenernest Ryan and myself weren't sure that is why we said just check it : )

**Comment by outerpress** [comment] 2021-06-30 22:22
@allison0034 I created a rough draft of the clickable appointment card for review here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/483

**Comment by outerpress** [comment] 2021-08-06 23:34
Everything remaining from this one is captured in tickets/tasks, closing

**Closed by outerpress** 2021-08-06 23:34 UTC
Labels: collaboration-cycle, vsp-product-support, collab-cycle-feedback
