### ISSUE TITLE
[DATA] Submit platform analytics ticket request CG URL changes 

### ISSUE THREAD

**Issue by luis-simauchi** [department-of-veterans-affairs/va.gov-team#86923] opened 2024-06-25 19:38 UTC
when Matt Long submits the new URL changes to the Caregivers form, the GA & DOMO properties needs to be updated to reflect the new pages

**Comment by longmd** [comment] 2024-07-02 14:44
@luis-simauchi , just checking if this is a duplicate of #81886? If so, Id assume we can close one of them.

**Closed** 2024-07-03 19:03 UTC
Labels: 1010-team, 1010-analytics, 1010-cg
