### ISSUE TITLE
[Discovery] Search implementation steps for learning center folder structure

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11254] opened 2020-07-15 14:24 UTC
## What is the folder structure needed in order to implement product level search.gov in the learning center? 

>To validate our assumptions about implementation, we will need more details about Learning Center -- in particular the content and folder structure.

This ticket is related to the search.gov learning center discover ticket #9937 and the findings documented there.

1/
Q: What LC folder structure is needed in order to implement product level search.gov? 
A: All LC content will be nested in the LC sub-directory/folder.   (Note: On the face of it, we don't believe Search.gov folder search will work for tag-based search filtering -- but we will follow up on this.)

2/
Q:What URL structure is needed for the LC content in order for "search within sub-directory" to work?
A: va.gov/learning_center/article.html

{Please list other Q/As here that we need to determine about the LC to validate assumptions in ticket #9937.}

**References**
-------
Learning center search product folder: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/search-feature-inside-LC/README.md

Learning center product outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md

**Comment by kelsonic** [comment] 2020-10-27 17:35
Not sure what work is here for devs yet if any (or maybe this is a duplicate of an already implemented ticket? Not sure) CC @ncksllvn

**Comment by denisecoveyduc** [comment] 2020-10-27 18:22
@denisecoveyduc to chat with @brianalloyd - can we close this one now that we aren't planning to use search.gov for the learning center search?

**Comment by jenniferlee-dsva** [comment] 2020-10-27 18:25
I think this was a discovery issue and we can close it. Correct @johnhashva ?

**Comment by brianalloyd** [comment] 2020-10-27 18:42
This was a discovery ticket, in favor of closing pending @johnhashva  recommendation.

**Comment by johnhashva** [comment] 2020-10-27 19:00
Yes, let's close.

**Closed** 2020-10-27 19:16 UTC
Labels: needs-info, vsa-public-websites, vsa-search-discovery
