### ISSUE TITLE
Updates to home loan limits page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9270] opened 2020-05-19 17:24 UTC
As a Veteran, I want to learn and understand what benefits are available to me through the home loan program. This includes limits to the benefits. 

Current page: https://www.va.gov/housing-assistance/home-loans/loan-limits/
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=747

Tasks:
- [x] Sandy Tadeo input new copy and edits directly to page in Drupal. Sandy
- [x] Review the new page copy in Drupal and make edits and updates as needed. If changes are significant, notify Sandy and Raleigh so they can respond if desired. **6/22 - Additional background/blog posts from Raleigh, we'll use for background**
**background** https://www.military.com/money/va-loans/new-law-allows-you-get-bigger-va-home-loan-without-down-payment.html
- [x] Beth reviews Anne rewrite of page. Beth
- [x] Copy edit. Randi
- [x] Send preview/prod link to Sandy and Raleigh. Anne
- [x] Input any last changes, and notify Randi it's ready to go live. Anne
- [x] Publish. Randi

Stakeholders:
Raleigh Contreras
Maxine Henry
Sandy Tadeo

**Comment by AnneHurley** [comment] 2020-05-19 17:30
[Housing loan limits page updates]
(https://app.zenhub.com/files/133843125/ca887b6c-e956-4959-adb0-95f6b60860e9/download)

**Comment by AnneHurley** [comment] 2020-05-27 15:52
Questions sent 5/26 to Sandy/Raleigh:
https://www.va.gov/housing-assistance/home-loans/loan-limits/
 
1.	Is the status of “full entitlement” new this year? There’s no mention of it at all in our current page. I just wanted to clarify, and if it’s new, why was it created?
2.	Since we talk about full entitlement higher on the page, I’m wondering why lower down we talk about basic entitlement, and then additional entitlement, also known as bonus or Tier 2 entitlement. Will this additional entitlement then bring a Veteran’s status up to full entitlement? Or should we swap in the phrase “full entitlement” where we currently have “additional entitlement”?
Or should “full entitlement” be a third, new, category of entitlement? 
3.	I’m confused by this section:
**Without full entitlement, VA can only guarantee 25% of the county loan limit reduced by the amount of your entitlement previously used and not restored.** Your previously used entitlement is listed under the ‘Entitlement Charged’ column in the ‘Prior Loans charged to entitlement’ table of your updated COE.
 
Is there a simpler way to say that first sentence? Is that a new regulation? And if there’s not a simpler way to say it I would suggest we give a math example, using 25% of a county’s limit, the amount a Veteran might have used previously, and showing the subtraction, and the final amount the Veteran can have guaranteed.
 
I would also suggest condensing that second sentence, beginning with “Your previously used entitlement”, which I’m happy to do. Also, we avoid italics on Va.gov, but we can bold specific terms and words for emphasis, which we can do here.
 
4.	I have similar confusion over this wording: 
**If you don’t have full entitlement on your VA home loan benefit, VA can only guarantee a portion of your loan based on the property’s county location and reduced by the amount of entitlement previously used and not restored.** Find the VA home loan limit for the county your property (or future property) is in.
 
Wording on site now:
VA home loan limits change each year and are based on the property’s county location. Find the VA home loan limit for the county your property (or future property) is in.
 
In the highlighted sentence, does it align with the previous question, so should we add 25%, instead of “a portion of” your loan? If not how would a Veteran know what portion VA would guarantee?
 
When I go to the general FHFA URL it takes me a minute to realize I need to look up my county under “2020 Conforming Loan Limits”. I think it would be worth mentioning that in our copy so a Veteran knows where to go. 
@bethpotts  @DanielleThierryUSDSVA  @RLHecht  FYSA

**Comment by AnneHurley** [comment] 2020-06-16 16:15
@bethpottsVADEPO  I sent Sandy and Raleigh these suggested updates and we should follow up with them. Let's chat!

**Comment by AnneHurley** [comment] 2020-06-23 19:10
[Rough draft of edits to top of page in Drupal as of June 23](https://app.zenhub.com/files/133843125/ef799cd0-02e6-41ee-9bee-d43b43ccb189/download)
@bethpottsVADEPO  and @RLHecht  FYSA

Have also emailed this doc, and Raleigh's original word doc, above, to Beth.

**Comment by AnneHurley** [comment] 2020-06-24 19:29
[Draft of home loan limits revise - v2 for Beth]
(https://app.zenhub.com/files/133843125/bdbeadeb-077c-453f-9558-1ad3d360317b/download)

@bethpottsVADEPO @stephorkandatx FYSA

**Comment by bethpottsVADEPO** [comment] 2020-06-29 21:48
6/18: Anne and Beth met with Raleigh to go over questions Anne had regarding the original edits that came from stakeholders. Questions are listed above in Anne's comment on 5/27.

6/29: I emailed Raleigh about a potential reorganization of the page to address Veterans with full vs remaining entitlement. Requesting a meeting for Wednesday.

**Comment by bethpottsVADEPO** [comment] 2020-07-01 17:35
7/1: Anne and Beth met with SMEs Maxine and Raleigh to show a potential reorganization of the page to account for the significant changes to home loan limits. Confirmed that the reorg is a good approach for Veterans. Next step is to put those changes into drupal in draft form and share the edits/updates with SMEs.

**Comment by MickinSahni** [comment] 2020-07-01 17:54
Carry over to sprint 25

**Comment by bethpottsVADEPO** [comment] 2020-07-13 21:15
I'll update drupal with my edits then will share with SMEs. This will have to carry over to the next sprint. FYI @MickinSahni and @RLHecht

**Comment by bethpottsVADEPO** [comment] 2020-07-13 21:26
@RLHecht @MickinSahni Or if it's cleaner, we can start a new ticket for stakeholder approval of the new page. Either way works for me.

**Comment by MickinSahni** [comment] 2020-07-14 21:38
Eh, already carried over to next sprint. I think we have a good model going forward of separating tickets that'll need SME approval from our work e.g. https://github.com/department-of-veterans-affairs/va.gov-team/issues/11171

**Comment by bethpottsVADEPO** [comment] 2020-07-16 21:46
Received feedback from one of the two stakeholders today. Will incorporate this round of edits and ask if there will be any more (from the other stakeholder).

**Comment by bethpottsVADEPO** [comment] 2020-07-21 16:27
Updated the drupal page with Maxine's edits. Waiting to see if Raleigh gets back to me with any edits.  He may be OOO. 

Next steps once all stakeholder edits have been taken in and there's agreement that it's ready to publish:
- Randi does a full copyedit. This page is completely reworked, so it requires a copyedit as if it's a new page.
- Publish.

**Comment by bethpottsVADEPO** [comment] 2020-07-22 21:04
@RLHecht We got the SME thumbs up to proceed with publishing these edits. Thank you for copyediting and publishing! @mnorthuis for awareness

**Comment by RLHecht** [comment] 2020-07-23 01:16
This page is reviewed and published. Moving to validate and will close after tomorrow's deploy. FYSA @MickinSahni

**Comment by RLHecht** [comment] 2020-07-23 20:54
This has been validated on the live site. Closing ticket. FYSA @MickinSahni

**Closed by RLHecht** 2020-07-23 20:54 UTC
Labels: content, vsa-public-websites
