### ISSUE TITLE
Appointment Options

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#1300] opened 2019-08-26 15:25 UTC
## User Story
As a user I need to be able to specify certain options for my appointment 

## Goal
Build components that do not require data for appointment type step as seen in [mockup](https://projects.invisionapp.com/share/KSTFY798BU3#/screens/378826078).

## Screenshot
![Appointment detail options](https://user-images.githubusercontent.com/786704/63702033-03fa2080-c7db-11e9-98cd-bd873c47eb1b.png)

## Acceptance Criteria
- [ ] Radio button choices for purpose of visit
- [ ] Radio buttons for preferred type of visit

**Comment by jbalboni** [comment] 2019-08-29 15:37
Some additional background: VA.gov has a form system where you configure a full form application with a JSON config file. You can see a bunch of examples of this in the vets-website codebase (`src/applications/edu-benefits/1990e/config/form.js` is one example).

On VAOS, I don’t think we’re going to use that full config file approach, but a simpler subset of that functionality. You can see it in the `TypeOfAppointmentPage.jsx` file in the `vaos` folder, where form fields are defined in two different schema objects.

I would suggest reading through https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects to understand those two schema objects. Then https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-widgets and are https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms useful places to see how to do a variety of things with those config objects

**Comment by markgreenburg** [comment] 2019-09-06 03:09
Closing because the new prototypes have this UI split into two pages, so this is now a dupe of #1526 and #1574

**Closed by markgreenburg** 2019-09-06 03:09 UTC
Labels: frontend, vaos
