### ISSUE TITLE
Staging Review finding: Incorrect use of commas in "prepare for your appointment" list 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91567] opened 2024-08-27 14:08 UTC
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Appointments FE Team
**Product:** Appointments
**Feature:** Medication Review

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

In the video appointment details, under the header "prepare for your appointment", the text reads "bring your insurance cards and a list of your medications and other information to share with your provider." Since this list has three items, it should be comma-separated and include the oxford comma. 

## Recommended action

Change the list to read "bring your insurance cards, a list of your medications, and other information to share with your provider." 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Punctuation](https://design.va.gov/content-style-guide/punctuation)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [x] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [x] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [x] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by outerpress** [comment] 2024-08-27 21:39
FYI @laurwill this tweaks the previous tweak of the medication review language by adding commas. FYI @loripusey @benbrasso-agile6 for the same sentence in the CIE medication review section.

**Comment by benbrasso-agile6** [comment] 2024-08-27 21:47
Thanks. Lori, either Zack or I will prep this change in Figma tomorrow. Not that it's urgent, but just to get it moving.

**Comment by laurwill** [comment] 2024-08-28 11:40
Hey @benbrasso-agile6 @KKitagawa-Bosch , the intended meaning of the sentence was 2 items:
- insurance cards
- a list of medications and other information to share with your provider

But clearly that was not clear! What if instead of a 3-item comma-separated list, we do: "Bring your insurance cards. And bring a list of your medications and other information to share with your provider."

**Comment by KKitagawa-Bosch** [comment] 2024-08-29 18:19
Makes sense to me! @benbrasso-agile6 I would go with that. You can also replace "and" in the second sentence with "Also" if you prefer; whichever sounds best to your ear! (They're both technically correct)

**Comment by outerpress** [comment] 2024-08-29 18:44
Thanks @KKitagawa-Bosch ! @laurwill any strong preference for "Also" vs. "and" ?

**Comment by benbrasso-agile6** [comment] 2024-08-29 20:59
And "sounds" nice to me; take that with a grain of salt

**Comment by benbrasso-agile6** [comment] 2024-08-29 21:11
@loripusey paragraph/content changes for pre-check-in FE under the `Prepare for your appointment` heading need a new ticket:

Complete page - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=285-17139&t=DbMmFHqAEf70oinX-4

Appt detail page - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=285-14615&t=DbMmFHqAEf70oinX-4

**Comment by loripusey** [comment] 2024-08-30 16:39
@benbrasso-agile6 Let's just use this ticket, I'll assign it to frontend in the next sprint.

**Comment by outerpress** [comment] 2024-08-30 18:28
Confirmed with @laurwill that we'll go with "And" - @ldelacosta I'll get the designs and dev ticket updated this afternoon. Thanks all!

**Comment by loripusey** [comment] 2024-09-03 13:28
@benbrasso-agile6 do you need to update the CIE wireframes or are they ready for FE?

**Comment by loripusey** [comment] 2024-09-03 14:11
@benbrasso-agile6 no, based on this comment, is there additional work on our wireframes that need to be done?

> Confirmed with @laurwill that we'll go with "And" - @ldelacosta I'll get the designs and dev ticket updated this afternoon. Thanks all!

**Comment by benbrasso-agile6** [comment] 2024-09-03 14:33
The links I've provided have those updates. Unless you see something missing?

**Comment by loripusey** [comment] 2024-09-03 14:51
Nope, just checking before turning it over to FE.

**Comment by outerpress** [comment] 2024-09-05 21:49
@ldelacosta #91709 completed this work, so closing this one.

**Closed by outerpress** 2024-09-05 21:49 UTC
Labels: content, frontend, appointments, collab-cycle-feedback, appointments-fe-ux, Staging, CC-Dashboard, appointments-pm, content-punctuation, Credibility, exp-std-voice-tone
