### ISSUE TITLE
[bug] Certificate of Eligibility | Submission Failure

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#47435] opened 2022-09-22 19:55 UTC
## What happened?

![image003.png](https://images.zenhubusercontent.com/61438f9a4cc76e287dda36ce/f88e1786-fd4a-4cd9-91f3-2cb0c023d4a4)

## Specs:
- Device: TBD (e.g. iPhone 8, Macbook)
- Browser: TBD (e.g. Firefox, IE 11)
- Test User: Login info in snapshot

## Steps to Reproduce
- Info in snapshot

## Acceptance Criteria
- When a user submits they should not receive error messages

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by data-doge** [comment] 2022-09-23 14:47
@saderagsdale Jerek and I looked into this. The request here fails with a 404, though it does not always fail, and we have been receiving 404s since July. http://sentry.vfs.va.gov/organizations/vsp/issues/96494/events/?environment=staging&project=3&statsPeriod=14d. To figure out what is going on here, it would be helpful to see logs on LGY's end, or have LGY's team look into the logs on their end and let us know what they're seeing.

**Comment by saderagsdale** [comment] 2022-09-23 16:58
@data-doge I reached out in the email thread and requested this.

**Comment by data-doge** [comment] 2022-10-04 18:02
Merged two PRs adding additional logging/monitoring to help us diagnose this issue. https://github.com/department-of-veterans-affairs/vets-api/pull/10811; https://github.com/department-of-veterans-affairs/vets-api/pull/10826

**Comment by data-doge** [comment] 2022-10-05 20:09
An update after speaking with Kelli's tester and developer. There are at least two (and hopefully only two) separate causes for the error we're seeing on the frontend:

1. We're not sending an important query parameter (EDIPI) to LGY. This thread may be relevant to our issue: https://dsva.slack.com/archives/CBU0KDSB1/p1664553408929469.
2. For some reason, our auth tokens are expiring midway through completing the COE form. Unclear why this is happening, and given this is an auth issue, it's most likely an issue with the whole app. I'll reach out to platform-support for guidance on this.

**Comment by data-doge** [comment] 2022-10-17 20:25
Okay, I think I've wrapped my head around the expired auth token issue:

Auth tokens expire after 5 minutes. See [link](https://github.com/department-of-veterans-affairs/vets-api/blob/0f30e99bae5c4c15dcf5c2a18efe33e03d0d3098/app/models/sign_in/access_token.rb#L86), [link](https://github.com/department-of-veterans-affairs/vets-api/blob/0f30e99bae5c4c15dcf5c2a18efe33e03d0d3098/app/services/sign_in/constants/access_token.rb#L6). Interacting with the COE form (e.g. typing, navigating between steps) does not extend the life of the auth token. Neither do POST requests. Neither does reloading the page.

When the auth token expires, requests to the backend expectedly begin failing with a 403. An error is rendered (with no clear CTA), and the user is still allowed to proceed through the form, despite the 403s. The user is also allowed to attempt submitting the form, which expectedly fails. At no point is the user automatically signed out. See screenshot below:

<img width="1512" alt="403 error" src="https://user-images.githubusercontent.com/7520103/196270533-7cf9bb20-7d5a-4bfd-8f3d-563907218281.png">

Once the auth token expires, the user must reload the page twice. The first reload refreshes the auth token, but renders an infinite progress bar. See screenshot below:

<img width="1512" alt="403 error, after expiration and refresh" src="https://user-images.githubusercontent.com/7520103/196271022-99a6c17e-ced0-434d-a146-6d099aa082b2.png">

On the second reload, the page renders successfully, and the user is given five more minutes to interact with the form. See screenshot below:

<img width="1512" alt="403 error, after second refresh" src="https://user-images.githubusercontent.com/7520103/196271336-c6197639-d993-4c9a-b326-06193be53580.png">

This is a poor experience because: 1) the user has only five minutes to interact with the form before it becomes inoperable, 2) once the form becomes inoperable, the user is still allowed to interact with the form and even submit the form, even though these actions have no effect, 3) our error message does not help the user remedy this error, and 4) the user must know to refresh the page twice to remedy this error.

Ideally, the user should be able to interact with the form as long as they want, but be logged out after a certain period of inactivity. I see that we do something like this for the session ([link](https://github.com/department-of-veterans-affairs/vets-website/blob/7cd326dfab74eadb2131b7406e9fd97895ce3e9a/src/platform/user/authentication/components/SessionTimeoutModal.jsx#L38)) (which expires after 30 minutes) but I see no equivalent for the access token. Currently, the `/refresh` endpoint is consumed in only two places: [SessionTimeoutModal](https://github.com/department-of-veterans-affairs/vets-website/blob/7cd326dfab74eadb2131b7406e9fd97895ce3e9a/src/platform/user/authentication/components/SessionTimeoutModal.jsx#L72) (which displays after 30 minutes, not 5 minutes), and [a function that appears to be limited to the user profile](https://github.com/department-of-veterans-affairs/vets-website/blob/a463cb0bcb17c133a9cad4aee48f440dc8a6ef11/src/platform/user/profile/actions/index.js#L37).

For these reasons, I suspect that the issue I'm experiencing may be a site-wide issue.

I can think of a few ways to remedy this issue:
1. Refresh the auth token on every request, with the `/refresh` endpoint.
2. Make our auth tokens last as long as our session (30 minutes), so that the user see and use the `SessionTimeoutModal` to extend their session, or be automatically signed out if they take no action.
3. As an alternative to #2, show `SessionTimeoutModal` when an access token is about to expire.
4. Maybe something else?

A brief note on `#1`: at one point an `apiRequest` method was designed to automatically refresh expired auth tokens. See [link](https://github.com/department-of-veterans-affairs/vets-website/commit/2e660a693e30eeefc9e63b5aea7559592aa36dcb#diff-9215adbee4dab1c5995ad30eab3c2ccfd11452919f512a8725557076ef0c1774R122). However, in a later commit, this ability was removed. See [link](https://github.com/department-of-veterans-affairs/vets-website/commit/4be3ae91c50693261cb21de79c9dd926bf52592b).

Ultimately, I don't think this decision is up to me. I'll reach out to `#vsp-identity` to see if they can remedy this issue, or provide guidance around it.

**Comment by AGarcia-Clarity** [comment] 2022-10-17 21:39
Yes, I can provide some clarity on this situation.  Any part of vets-website that does not use our `apiRequest` utility function (i.e. `fetch`, `axios`, etc) will not work as intended when it comes to refreshing the Access + Refresh token.

@data-doge is correct in that there was a breakage in the `/refresh` endpoint being called automatically.  There was a PR that added the `type` query parameter to the `/refresh` endpoint that caused that call to not happen automatically on `401` and `403` status codes because of a syntax error in the `refreshProfile` Redux action. This issue has been [resolved by this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22391) that went in 5 days ago for all `apiRequest` calls.

There are 2 options
1. Replace your applications implementation of `fetch` with the `apiRequest` utility function (easier, might break tests)
2. Use your application's implementation of `fetch` but you'll need to account for session management. (harder, might break tests)

**Comment by data-doge** [comment] 2022-10-17 22:20
Thanks @AGarcia-Clarity! I'm trying to understand the resolution. I see that `apiRequest` handles 403s [by returning the data promise, rather than rejecting it](https://github.com/department-of-veterans-affairs/vets-website/blob/0a8692b443a29b5a6476256f4d075e1491e3fe83/src/platform/utilities/api/index.js#L114). But I don't see how calling `apiRequest` would cause the auth token to be refreshed.

I see that fixing the syntax error means that [`saveAndRefresh` will successfully call `refresh`](https://github.com/department-of-veterans-affairs/vets-website/blob/a463cb0bcb17c133a9cad4aee48f440dc8a6ef11/src/platform/user/profile/actions/index.js#L37). I also see that `saveAndRefresh` is called by [`refreshProfile`](https://github.com/department-of-veterans-affairs/vets-website/blob/a463cb0bcb17c133a9cad4aee48f440dc8a6ef11/src/platform/user/profile/actions/index.js#L51), which is called by [`initializeProfile`](https://github.com/department-of-veterans-affairs/vets-website/blob/a463cb0bcb17c133a9cad4aee48f440dc8a6ef11/src/platform/user/profile/actions/index.js#L82), which is called by [`checkLoggedInStatus`](https://github.com/department-of-veterans-affairs/vets-website/blob/a83bba9601ae342b826287f10537b7e4c3bc6dab/src/platform/site-wide/user-nav/containers/Main.jsx#L138), which is called on page load in the [`Main` component](https://github.com/department-of-veterans-affairs/vets-website/blob/a83bba9601ae342b826287f10537b7e4c3bc6dab/src/platform/site-wide/user-nav/containers/Main.jsx#L58).

Given that, I assume that the following happens:
- On sign in, the user receives an auth token which will expire in 5 minutes. 
- The `Main` component mounts and ensures that on `load`, the user's token will be refreshed.
- The page finishes loading, a `load` event is fired, and the user's token is refreshed.

Now, if the user navigates through our COE form for longer than 5 minutes, but does not reload the page, then I think the auth token will not be refreshed, and the user will experience the issues described above, unless they know to reload the page, and then reload the page. Is that right? I'm not getting how using `apiRequest` -- as opposed to `fetchAndUpdateSessionExpiration`, which we are currently using -- causes the auth token to be refreshed, either directly or indirectly. 

Sorry 😅, I think I'm missing something really obvious.

**Comment by saderagsdale** [comment] 2022-10-19 16:18
Status: Waiting for updates from LGY and the platform.

**Comment by AGarcia-Clarity** [comment] 2022-10-19 21:51
@data-doge Sure so in the `apiRequest` method we explicitly check for the existence of a specific cookie `vagov_info_token` to return data (rejecting it will kill the session).  In the `initializeProfile` we attempt to make a request to the `/v0/user` endpoint. The `saveAndRefresh` will call the `/refresh` endpoint (if there is a token and original response is a 403), then reattempts the original request.


An example:
1. User authenticates and is on the `/my-va` page, they get busy and let the 5 minute Access Token expire
2. They navigate to the `/profile` page
3. Like you mentioned the `Main` which is on each page runs it `load` event
4. The `componentDidMount` will run and check if `hasSession` is true and kicks the `initializeProfile` call off to the `refreshProfile` function
5. The `refreshProfile` attempts to call the `/v0/user` endpoint and because the AT is expired it's going to return a 403, that payload is then passed onto the `saveAndRefresh` which will check for the `vagov_info_token` existence and the 403 response (which is "Access token has expired")
6. If that's true the `refresh` to get new Access TOkens/Refresh Tokens is called and the original request is reattempted and returned. If it's false, it goes thru the process of continuing with the 403 error which ultimately tears down the session

The reason why `fetchAndUpdateSessionExpiration` will not work, is because it is SSOe based (as opposed to our new OAuth implementation).  This function effectively uses the `X-Session-Expiration` header as the sole basis as to whether a session is "alive" or not that is returned by vets-api (and when a 304 is encountered, it calls eAuth's `/keepalive` endpoint to maintain an active session)

**Comment by data-doge** [comment] 2022-10-21 19:41
@saderagsdale 

Just spoke with @AGarcia-Clarity, who is already planning on handling the 403 issues as part of an app-wide migration to `apiRequest`. Because Alex is handling the issue and because this issue is not COE-specific, it should not block COE launch. 

LGY is working on a bugfix for the 500 errors.

**Comment by saderagsdale** [comment] 2022-10-31 14:33
@data-doge Hey Eugene! Can you drop an update for this ticket in the comments?

**Comment by data-doge** [comment] 2022-10-31 15:15
Hey @saderagsdale! LGY has pushed a bugfix to their "SQB" environment. They've asked whether we can point our staging environment to SQB, rather than "SQA", where our staging environment is currently pointed. I'm going to see whether we can do this, and if we can, then we can see whether Jerek's 500 issues are resolved. I'll also be able to get more information on another (and hopefully, final) kind of 500 error I've seen. More on that soon.

**Comment by data-doge** [comment] 2022-11-10 16:08
Update: LGY has pushed their fixes to SQA, and we are now pointing to SQA again. Unfortunately, now I am noticing that users in staging no longer have EDIPIs or ICNs. This presents a problem for us because LGY requires these values in order to use their API. I've reached out to platform support for guidance here: https://dsva.slack.com/archives/CBU0KDSB1/p1668096387136999

**Comment by data-doge** [comment] 2022-11-14 19:14
Update:
1. The missing EDIPI and ICN issues are intermittent. Today, users who were previously missing an EDIPI and ICN now have these values. Platform team is unsure why this is the case. See https://dsva.slack.com/archives/CBU0KDSB1/p1668096387136999. 
2. Sue at LGY discovered that some users were not having their pre-existing information auto-populated in the COE form. This is the result of a non-COE-specific bug that I am addressing in this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/11145.

@saderagsdale Once https://github.com/department-of-veterans-affairs/vets-api/pull/11145 is deployed, I think we can close this ticket.

**Comment by data-doge** [comment] 2022-11-15 18:53
@saderagsdale @sortizsh I updated the story points on this ticket from 21 to 34 (the next number in the fibonacci sequence) in light of all the SQA/SQB work, the investigation into missing EDIPIs, and most recently, the bug described in https://github.com/department-of-veterans-affairs/vets-api/pull/11145. 34 is kind of a comically large complexity estimate, though it does encompass 9 PRs and two months of work 😅.

**Comment by data-doge** [comment] 2022-11-15 20:59
Update: https://github.com/department-of-veterans-affairs/vets-api/pull/11145 is merged and will be deployed tomorrow afternoon. Moving this ticket into validate. If the auto-population issue is resolved on staging tomorrow afternoon, then I believe we can close this ticket.

**Comment by data-doge** [comment] 2022-11-17 16:36
https://github.com/department-of-veterans-affairs/vets-api/pull/11145 is merged and deployed. Auto-population now works as expected. Closing this ticket.

**Closed by data-doge** 2022-11-17 16:36 UTC
Labels: high priority, benefits-team-1, squad-2, COE

**Comment by saderagsdale** [comment] 2023-01-03 15:33
@AGarcia-Clarity Hey Alex! Can you provide an update on when the unit tests for this issue will be completed and deployed?

**Comment by AGarcia-Clarity** [comment] 2023-01-03 19:05
@saderagsdale Yes, I have a PR that is ready for review https://github.com/department-of-veterans-affairs/vets-website/pull/23011 and would appreciate others testing this to confirm the expected functionality.

**Comment by saderagsdale** [comment] 2023-01-03 23:03
cc @data-doge

**Comment by saderagsdale** [comment] 2023-01-04 17:35
@AGarcia-Clarity Thanks for the update! I've tagged Eugene. Is the PR in code review or still waiting to be picked up?

**Comment by AGarcia-Clarity** [comment] 2023-01-04 17:36
@saderagsdale it's in review, I tagged him in the PR
