### ISSUE TITLE
Lighthouse 502 errors

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57008] opened 2023-04-18 12:41 UTC
## Description

After adjusting the readiness and preStop hooks for the vets-api EKS deployment (issue with scaling events), there is still a SMALL fraction of 502 errors that are seen for the `/internal/auth/v2/validation` endpoint, which is the endpoint that receives the second highest amount of traffic in vets-api. [See thread here with Lighthouse and Derek Brown](https://dsva.slack.com/archives/C04M7T1CZAS/p1681745509860519?thread_ts=1681143222.426519&cid=C04M7T1CZAS).

We should investigate the source of the 502 errors. The lighthouse/Kong logs show 33 errors per hour, but according to our calculation, there were 2.09M requests total over the span of 2 hours. 33 requests of that getting a 502, is a fraction of a percent.

The [revproxy logs show some 502 errors](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-12h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22revproxy%5C%22%7D%20%7C%3D%20%5C%22%2Finternal%2Fauth%2Fv2%2Fvalidation%20HTTP%2F1.1%5C%5C%5C%22%20502%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D&right=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Warden%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D), but this is a small fraction.

For an even larger window 52.41 million requests for 1 week with 5,300 502s on that endpoint. Which is .010%

We should circle back and investigate the cause.

**Comment by laineymajor** [comment] 2023-04-19 13:06
This might be a duplicate of #56968

**Comment by RachalCassity** [comment] 2023-04-21 18:43
502 errors have not been seen since we separated routes to independent bulk head deployments. Still monitoring logs next week.

**Comment by laineymajor** [comment] 2023-04-24 15:19
Combine with 56968 and move to monitoring epic after this sprint.
Can be closed upon completion of ^^^

**Comment by laineymajor** [comment] 2023-04-24 19:32
duplicate

**Closed by laineymajor** 2023-04-24 19:32 UTC
Labels: monitoring, platform-tech-team-1

**Comment by laineymajor** [comment] 2023-04-24 19:36
closing and moving to monitoring epic
