### ISSUE TITLE
MHV on VA.gov: Integration: Landing Page: Design Tweaks

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54684] opened 2023-03-07 15:37 UTC
## Design tweaks for landing page as of 3/7/2023
[Related Slack Thread](https://dsva.slack.com/archives/C04GDQSHD1R/p1678197227872079)
- [ ] Reduce logo size by 50%
- [ ] i would add a wee bit of space above the h2s in the gray boxes — maybe a [spacing unit](https://design.va.gov/foundation/spacing-units) or so
- [ ] "Your VA appointments" should be "Upcoming VA appointments"
- [ ] "My medications and allergies" should be "Medications and allergies"
- [ ] "Download my medical record" should be "Download medical record (Blue Button)"
- [ ] "Pay your copay bill" should be "Pay copay bills"
- [ ] "Update my health benefits info" should be "Update health benefits info (10-10EZR)"
- [ ] "My health information card" should be "Veteran health information card"

**Comment by dcloud** [comment] 2023-03-08 16:36
This looks like a duplicate of #54691

**Closed by dcloud** 2023-03-08 16:36 UTC
Labels: my-health, my-health-CTO-HEALTH-TEAM, my-health-INTEGRATION
