### ISSUE TITLE
Analytics Implementation or QA Support for Pre-Need Application

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/va.gov-team#60073] opened 2023-06-09 19:09 UTC
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary> The Pre-Need application is used by service members, Veterans, family members, and representatives to determine an applicant's eligibility for burial at a VA national cemetery.
</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - MBS Self-Service Team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
We would like for the following items to be tracked in Google Analytics:

    - How many users are selecting applicant name vs. “Someone else” options for preparer page question regarding who is filling out the application?
        - [Step 5 of 6: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)
        - [Step 6 of 7: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)

    - Total number of users per user status selected (Veteran / service member, spouse or surviving spouse, unmarried adult child, other) based on "Relationship to Veteran" field radio button question in Applicant Information step)
        - [Step 1 of 7: Applicant Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information).
    
- **When is the launch date?**
    - Pre-Need Pre-Integration - July-December 2023
    - Pre-Need Integration - June 2024

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment] 2023-06-13 12:52
Thank you for your submission.  We will review and get back to you with ETA.

**Comment by ccruzgra** [comment] 2023-07-14 16:51
Hi @michelle-dooley Is it possible to get an estimate on ETA for this? Thank you.

**Comment by jestutt** [comment] 2023-08-16 17:41
@ccruzgra To see those radio button events in GA you need to use the 'event': 'int-radio-button-option-click'

Here is the data layer code to use:
https://user-images.githubusercontent.com/93597659/237757966-63508e18-a4e1-4904-b4fe-7c932b181ed3.png

Note: for the label on the Contact Information on the Preparer page, you want to capture relationship -- e.g. self -- or some other label, not the name. 

After you implement the code let me know and I will test.

**Comment by jestutt** [comment] 2023-08-25 15:38
Hi @ccruzgra Checking to see i there's a status update on adding the radio button events.

**Comment by ccruzgra** [comment] 2023-09-06 15:06
@jestutt Our tech lead checked, and it appears the code is already implemented. Are you able to test?
cc: @ksantiagoBAH for awareness.

![Screenshot 2023-09-06 at 9 43 01 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41477797/c54d27dd-a6b9-4426-a6c3-2cff313e44d2)
![Screenshot 2023-09-06 at 9 44 27 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41477797/f9517ef2-3de9-4c1d-ac90-e2f790800f19)

**Comment by ccruzgra** [comment] 2023-09-14 12:47
@jestutt Touching base with you again to see if you were able to test. Thanks.

**Comment by jestutt** [comment] 2023-09-14 14:53
@ccruzgra  It's a little hard to explain but any events that you see in the inspect datalayer that start "gtm." are auto detect interactions that GTM adds, not the FE added datalayers events with specific variables that we want to collect like the one  below for radio button event

![237757966-63508e18-a4e1-4904-b4fe-7c932b181ed3](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/e6a23326-e8cb-433d-af33-25c12163e2e2)

**Comment by ccruzgra** [comment] 2023-09-14 15:09
@jestutt Gotcha. Thanks for the clarification.

@ksantiagoBAH Can you please assist with the above?

**Comment by ccruzgra** [comment] 2023-09-27 16:40
@jestuff wanted to follow up on this to make sure you saw Kenny's question above

**Comment by jestutt** [comment] 2023-09-29 16:06
@ccruzgra  I did miss Kenny's question. Thank you! 

@ksantiagoBAH  We want the Event Actions to looks like this when captured in GA: 
Radio Button - {question} - {selected answer] - [required}
![Screenshot 2023-09-29 at 11 52 24 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/f87cb787-5a1e-402d-a437-a695645e85e5)


For this question -- and any other radio button sets like it -- you want the legend label test for the question and the radio button label test for the selected answer. 
<img width="320" alt="Screenshot 2023-09-29 at 11 41 26 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/db921f4a-e9ff-4c35-a3f0-6ab1703dd9d1">
<img width="750" alt="Screenshot 2023-09-29 at 11 41 15 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/315a0784-29db-403e-b4cc-19adc0bd964e">


This question -- Who is filling out this appliction? -- is a special scenario in that we do not want to capture a name as that's PII. Instead, I would suggest using the values for radio buttons of "Self" and "Authorized Agent/Rep".
<img width="342" alt="Screenshot 2023-09-29 at 11 49 26 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/cd3aecf6-694c-448a-8b69-a55cc55b88fe">
<img width="872" alt="Screenshot 2023-09-29 at 11 49 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/e6aca115-929e-42af-b926-3dc1943ada46">

**Comment by ksantiagoBAH** [comment] 2023-09-29 16:13
Sounds good I have to modify it a little to get it to work like that, thanks.

**Comment by ccruzgra** [comment] 2023-10-12 14:27
@jestutt, @ksantiagoBAH confirmed his changes were merged. Are you able to test that everything looks good?

**Comment by ccruzgra** [comment] 2023-10-18 13:25
@jestutt bumping this again

**Comment by jestutt** [comment] 2023-10-20 17:15
@ksantiagoBAH  I don't see any datalayer events when I interact with the "Relationship to service member" radio buttons on https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-relationship-to-vet 

I do see it for the "Who is filling out this application?" radio button interactions and it looks right: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d9bec83eff21305d9f6f0672e24d9b450b6fb4d/Screenshot%202023-10-20%20at%201.09.59%E2%80%AFPM.png)

Interestingly, if there's already a selection and I change it, 2 datalayer events fire - one for each radio option. It should only be the one being selected. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3824cf45deace76ad4571e33ac97165f86729928/Screenshot%202023-10-20%20at%201.11.08%E2%80%AFPM.png)

cc @ccruzgra

**Comment by ksantiagoBAH** [comment] 2023-10-20 17:20
@jestutt Let me take a look

**Comment by AlexanderSherrow** [comment] 2023-10-25 14:06
Issue should be fixed and is ready for review.

**Comment by jestutt** [comment] 2023-10-30 23:03
@AlexanderSherrow @ksantiagoBAH @ccruzgra 

I think we are good. Datalayer event fires as intended and you can see the test events that were sent to staging GA in the screenshot.

![Screenshot 2023-10-30 at 6 54 10 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/92af836c-7af1-4e9e-86ed-28e94f666c47)
![Screenshot 2023-10-30 at 6 56 16 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/b25fa3f4-7f46-4123-b9dc-f6649b361aab)

**Closed** 2023-10-31 13:41 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle
