### ISSUE TITLE
Environment (and other) tags missing during revproxy deploys

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#75159] opened 2024-02-01 19:30 UTC
## Issue
Adrian Rollett had discovered some unusual behavior that occurs during revproxy deploys and requested a deeper investigation and resolution.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1580012/4791ff41-36bc-479a-b1e7-d71c3ff89642)

## Acceptance Criteria
- [ ] Confirm the issue
- [ ] Connect with OP (Adrian Rollett) on further details if necessary
- [ ] Communicate possible fix or reason why fix is not necessary 

## Additional information

Further information in this slack thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1706305882259029)

---
## How to configure this issue
- [ ] **Labeled with 'platform-cop'** 
- [ ] **Labeled with Practice Area** (`platform-cop-backend`, `platform-cop-frontend`, `platform-cop-devops`)

**Comment by hgbarreto** [comment] 2024-03-06 18:00
thread: https://dsva.slack.com/archives/CBU0KDSB1/p1706305882259029

**Comment by ph-One** [comment] 2024-06-28 11:28
The root cause is that the EC2's monitoring software is terminated during the shutdown process and gives produces a void in our logs for the reverse proxy itself during deployment. Looking at the logs for the ELB that fronts the reverse proxy we do not see the dip. We're still looking into ways to improve this, such as, delaying the cut-over between new and old deployments until after logging has had time to warm up and begin populating Datadog.

**Comment by ph-One** [comment] 2024-09-05 11:55
I've setup the Datadog Agent to start as early as possible (after `docker.service`), which as _helped_ this situation. The dip is still going to happen bc during shutdown the logging agent can be terminated before the application, but we have at least made it so that the logging agent is started as early as possible, and before the reverse proxy itself.

## Before

![image](https://github.com/user-attachments/assets/9bfd521d-1133-4bda-8d48-b9da7374c4ff)


## After

![image](https://github.com/user-attachments/assets/28b7e0d5-3992-4c69-b0bb-918483027468)

**Comment by ph-One** [comment] 2024-09-05 12:03
This is likely our best outcome while using a logging agent. We also have the reverse proxy ELB logs, which are continuous and do not suffer from this dip

![image](https://github.com/user-attachments/assets/d3f36361-1afc-4859-9081-31489614a2a6)

**Comment by ph-One** [comment] 2024-09-05 12:16
I do not believe there is any more work that can be done here. It is the nature of a local logging agent. Closing, but please reopen (or generate a new ticket) if a new approach is discovered.

**Closed by ph-One** 2024-09-05 12:16 UTC
Labels: discovery, Infrastructure-Services, platform-cop
