### ISSUE TITLE
Investigate using automated actions to require manual reviews in vets-website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2521] opened 2019-10-16 19:26 UTC
# Overview 

- generally code owner reviewers do not return to pull review requests after they are approved 
- it is possible that after receiving a code owner review for a contributor to push additional changes that may not pass manual review 
- investigate using GitHub actions to trigger additional reviews when the `/platform` folder is changed after a pull request review has received a code owner approval 

# Example 

- contributor requests a review on a PR that modifies their application code
- as a code owner, I approve a PR
- a contributor pushes a change that alters code in a folder that requires higher scrutiny (e.g. they change the build process)
- github action triggers a github workflow that uses the github api to alter the pull request review state to "needs changes" and tags the reviewer in a comment notifying them that a change was made to the platform folder after receiving approval 

# Notes 

- we can trigger github actions workflows off of edits to specific folders: https://help.github.com/en/articles/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
- we can use the github api to alter the state of a review https://developer.github.com/v3/pulls/reviews/#update-a-pull-request-review
- Not sure what the trade offs are for using this vs existing tooling in vets-website CI i.e. these triggers may be available to our current jenkins jobs. suggest reviewing approach / example with devops and to do clear trade off examination. if we decide to use this, would be good to clarify when to use GH Actions vs using our existing hooks / triggers

**Comment by brandonrapp** [comment] 2020-02-12 17:14
@bkjohnson - can you add your notes into this ticket. Feel free to change around some of the description above if it no longer matches what you are doing. Especially the pieces that specifically call out GH.

**Comment by bkjohnson** [comment] 2020-02-14 06:20
The emphasis now is not _specifically_ on Github Actions. It has been decided that our CI processes will be moving from Jenkins to CircleCI, so we are focusing on that more at the moment since it offers similar features to Github Actions. The goal of having automation trigger a manual review is just a part of a larger goal of utilizing more automation and tools to help provide a better experience for other engineers on the platform.

I will describe a typical current scenario that happens as well as an imagined future scenario where we use automated tooling to handle some workload and provide better and quicker feedback.

## Typical current scenario

An engineer creates a new feature branch and makes some local commits.  Our ESLint rules will prevent code that doesn't pass the linter from being committed, but let's say that the engineer forgets to run the local tests to see if their changes pass.

Eventually the engineer decides to push their branch up and open a PR.  Suddenly they see something like this:

![image](https://user-images.githubusercontent.com/2008881/74504190-3e9a6700-4ea8-11ea-9fd6-83b5de328514.png)

Something failed in Jenkins.  Maybe it was a change they made that broke an existing test, or maybe it was a flaky end-to-end test, or maybe something else went wrong.  The point is, **it isn't obvious what is "wrong"**.  In order for the engineer to view the Jenkins logs to discover what happened they must be connected to the SOCKS proxy.  This is a bit of friction, and for new teammates who don't have access yet it is even more frustrating.

The engineer manages to either figure out what went wrong in Jenkins, or they may run the tests locally to see if they can discover what the issue is.  Once it gets fixed, they ask a peer on their team to give it a thorough review to make sure it accomplishes the desired functionality.  After the peer reviews it the responsibility falls to the frontend-review-group on VSP to give it a final approving review after checking for things that could potentially disrupt the platform.

This is tedious, time-consuming, and not always informative, for all parties involved.


## A proposed future scenario

Our goal is to reduce the amount of manual intervention that is required.  We plan to remove the frontend-review-group as gatekeepers of application code, but we still want to prevent code from shipping that we feel shouldn't be on the platform.  To meet this end, **we want to have automated processes that will make it obvious to the review group _and_ the VFS engineer where any potential "issues" are in the code**. Some of this automation can have more of a blocking role than others.

For this particular piece, we want automation to identify areas where a manual review by the platform team is required.  We have ESLint rules set in place for a reason, so here is an example of an automated process alerting us to something requiring a manual review.

![image](https://user-images.githubusercontent.com/2008881/74505350-c59d0e80-4eab-11ea-93ed-f4f196b9cc17.png)

Currently this doesn't block a merge - it simply alerts the frontend-review-group to a potential issue.  This gives VFS teams the benefit of the doubt that they _won't_ merge a PR that is flagged for manual review.  If it becomes an issue then we can modify the bot so that it `requests changes`.

Once the comment is made and the review is requested, a member of the review group can come along and see if the situation warrants the offending piece of code.  Even if it does, this bit of automation **immediately makes it obvious** what the potential problem is.  This will help the VFS teams, but on the (hopefully) rare occasions where a review from VSP is required, it helps surface the issue without having to search through all of the lines of code.

In addition to the comments, the results of these process also appear towards the bottom of the PR:
![image](https://user-images.githubusercontent.com/2008881/74506479-891ee200-4eae-11ea-8fb8-b7f52e6f121c.png)


And also in the "Checks" tab with a bit more detail on the jobs that were part of the workflow:
![image](https://user-images.githubusercontent.com/2008881/74506421-6c82aa00-4eae-11ea-8a67-f3f0ff5b12ab.png)



The larger goal of improving the developer experience and making issues more obvious may evolve into a Github App that uses the Checks API.

**Comment by gunsch** [comment] 2020-02-17 22:39
Suggestion: can we make sure to emphasize in the wording posted by `va-vfs-bot` that the author _should_ wait for explicit approval from `frontend-review-group`?

**Comment by bkjohnson** [comment] 2020-02-17 23:50
Yes, we can make that change.

**Closed** 2020-03-20 16:33 UTC
Labels: frontend, tools-fe, tools-improvements
