### ISSUE TITLE
Use and display facility timezone on appointments list page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#3231] opened 2019-11-08 15:30 UTC
We need to use the facility timezone for the times on the appointment list page, which come back to us in UTC and are converted to the user's current timezone, currently.

We get timezones for all the VA systems in the `public/facility/timezone` endpoint. This isn't one we've mapped to vets-api, and it's static data, so I believe we can include it as a json file in vets-website and reference it as static data.

One note: we have timezones for systems, not individual facilities, so we'll need to just use the 3 digit code from the appointment data we have.

**Comment by markgreenburg** [comment] 2019-11-08 16:57
Dupe of #3235

**Closed by markgreenburg** 2019-11-08 16:57 UTC
Labels: frontend, vaos
