### ISSUE TITLE
Data to Datadog

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#32090] opened 2021-10-27 16:48 UTC
Determine what data should be moved to Datadog

**Comment by ewilson-adhoc** [comment] 2022-02-04 18:58
This seems like a duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/35928 closing as such. Please open if this is an incorrect assessment.

**Closed by ewilson-adhoc** 2022-02-04 18:58 UTC
Labels: integration-experience
