### ISSUE TITLE
GIDS: Add "POO Status" to institution file for download

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9524] opened 2020-05-27 15:47 UTC
As an Education Services team member, I need to have the "POO Status" added to the Institution file so that I can track the Closed/Withdrawn schools

## Assumptions
1. This column was previously included in the file generation.

## Acceptance Criteria: 
1. The data column "POO Status" from the WEAMS_SCHOOL_DATA file has been added to the Institution download file.
    - Note: The order of the columns matters; it should be re-added in the location that it was previously found.

# Supporting Artifacts: 
1. N/A

**Comment by dneel-bah** [comment] 2020-06-19 12:23
Closing as duplicate of #10358

**Closed by dneel-bah** 2020-06-19 12:23 UTC
Labels: bah-gids, technical
