### ISSUE TITLE
[Bug] VAMC Left Nav - A11y - Spacebar not triggering click on focused menu-option

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8946] opened 2020-05-09 00:04 UTC
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

## Specs:
- All major desktop browsers (Win Edge/IE11, Mac Safari, Win/Mac Chrome, Win/Mac Firefox)
- Unauthenticated experience

## Steps to Reproduce
1.  Go to https://staging.va.gov/pittsburgh-health-care/
1.  Tab to Left-Nav's **Locations** menu-option.
1.  Press **Spacebar**.
1.  Observe that the page scrolls down instead of triggering a click on the focused menu-option.

### GIF showing Spacebar & Shift-Spacebar behavior:
![ln-a11y-bug-2-spacebar-scrolls-200508](https://user-images.githubusercontent.com/587583/81452458-d3c19a80-913b-11ea-9d96-5cf91cd2c856.gif)

## Desired behavior
Spacebar should trigger menu-option click \[and thus navigation to Locations page].

## Acceptance Criteria
\[See **Desired behavior**]. see also #8145

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brangi** [comment] 2020-05-11 16:21
@tlei123 these are links, I have not found any other link on va.gov with the same behavior (so far), I think only buttons do need this behavior. Can you please provide an example where links open with spacebar?

**Comment by mmiddaugh** [comment] 2020-06-26 15:22
@tlei123 @jenstrickland can you label this with a defect level to help us with prioritization, please?

**Comment by jenstrickland** [comment] 2020-06-26 18:18
Because this bug prevents some users from accessing content I marked it as 508-defect-1, Launchblocker.

**Comment by brangi** [comment] 2020-06-26 19:01
> Because this bug prevents some users from accessing content I marked it as 508-defect-1, Launchblocker.

Well,  I did ask previously ^ but I can ask again, because I cannot find examples of the correct behavior `I have not found any other link on va.gov with the same behavior (so far), I think only buttons do need this behavior. Can you please provide an example where links open with spacebar?`

**Comment by jenstrickland** [comment] 2020-06-26 20:32
Generally, on VA.gov, control+option+space will open links, when using VoiceOver+Safari. Otherwise, I'm not familiar with the spacebar opening.

**Comment by brangi** [comment] 2020-06-29 15:58
thanks @jenstrickland for that information. So is this defect valid then?

**Comment by jenstrickland** [comment] 2020-06-29 17:57
@tlei123 — do you have more information on where the information regarding the space bar expected behavior comes from?

**Comment by tlei123** [comment] 2020-06-29 20:57
> do you have more information on where the information regarding the space bar expected behavior comes from?

Michelle's #8145, under ACs, item 9 \[you can search on 'space bar' when there].  I just took her word for all those ACs when I created my A11y test-cases -- didn't look for any real va.gov examples for them.

**Comment by jenstrickland** [comment] 2020-06-29 21:07
> User can select menu item using keyboard space bar or enter key.

That would only apply to the focusable items (the links) in the navigation list.

**Comment by jenstrickland** [comment] 2020-06-29 21:09
Since this isn't actually an accessibility issue I'm going to remove the severity labels.

**Comment by jenstrickland** [comment] 2020-06-29 21:15
Closing this issue, as this is not an issue.

**Closed by jenstrickland** 2020-06-29 21:15 UTC
Labels: bug, frontend, needs-grooming, vsa-facilities
