### ISSUE TITLE
Veterans able to direct schedule multiple COVID Appointments

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#22697] opened 2021-04-06 14:55 UTC
Not sure if this is a defect or not, but veterans are able to direct schedule multiple COVID appointments.  
This is actually true for all direct scheduling but might have more of an impact in COVID.

![MultipleCovidAppts.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/d4bd3ca9-9acb-4c04-81e3-33d30affc991)

**Comment by laurenernest** [comment] 2021-04-06 23:20
Correct, not a bug since we didn't initially have a way of knowing if a Veteran had a vaccine appointment scheduled. Now that we'll be getting some kind of indicator for a vaccine appointment, I'll take this back to see if this is a use case we need to handle.

**Comment by laurenernest** [comment] 2021-06-04 23:01
Based on latest supply and demand of the vaccine, and shift in operations at VAMC, this use case does not need to be covered. Closing ticket.

**Closed by laurenernest** 2021-06-04 23:01 UTC
Labels: product, vaos
