### ISSUE TITLE
Refactor Community Care detail page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#29450] opened 2021-08-30 14:24 UTC
Refactor the community care details page so that:

- There's no longer a separate CommunityCareDetailsPage component
- In ConfirmedAppointmentDetailsPage, there's a DetailsCommunityCare component for CC
- ConfirmedAppointmentDetailsPage is updated to handle CC as well as VA details pages
- There are still separate urls (/va and /cc) for VA and CC details pages

---
~~The review instance for testing: [http://2f5f1f9e81a557334b8277c8d5921eb4.review.vetsgov-internal/](http://2f5f1f9e81a557334b8277c8d5921eb4.review.vetsgov-internal/)~~

The review instance for testing: [http://6b4f28620dca302e77169534bf207dd6.review.vetsgov-internal/](http://6b4f28620dca302e77169534bf207dd6.review.vetsgov-internal/)

**Comment by ldelacosta** [comment] 2022-08-19 14:12
As discussed, we would like a QA resource to help validate the ticket. Once the ticket is almost complete, we can discuss the testing plan. 

cc: @simiadebowale @ryanshaw

**Comment by ldelacosta** [comment] 2022-08-25 19:59
- Add the review instance link to the ticket @ryanshaw 
- Add users that have Community Care booked appointments - Leah 
- Review the community care appointment details page 
- Request a Community Care appointment in VAOS

**Comment by ldelacosta** [comment] 2022-08-30 16:04
Here is Judy's Community Care Appointment on 09/06 in staging: ![Screen Shot 2022-08-30 at 12.03.31 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2cb1b6a9-fcbf-4213-a2be-42f3e053a878)

**Comment by ryanshaw** [comment] 2022-09-08 01:18
@tlei123 I've merged in the latest `main` and triggered a rebuild. The new review instance is here (although now I am getting gateway errors): [http://6b4f28620dca302e77169534bf207dd6.review.vetsgov-internal/](http://6b4f28620dca302e77169534bf207dd6.review.vetsgov-internal/)

**Comment by ryanshaw** [comment] 2022-09-08 16:33
@tlei123 It looks like the test user listed above does not have any more Community Care appointments. I went through a few test users and found that test user `patient999@id.me` has an appointment in the future: 

![image](https://user-images.githubusercontent.com/587812/189176439-eaabd5ef-8e02-48bd-875f-d16c529ec85b.png)

The new [review instance](http://6b4f28620dca302e77169534bf207dd6.review.vetsgov-internal) also looks to be behaving better.

**Comment by tlei123** [comment] 2022-09-08 23:03
@ryanshaw , this is now validated successfully* &mdash; the PR should be safe to merge.

For booked (confirmed) appointments, all detail-pages for both VA & CC look good and work fine.

The _appointment-request_ detail pages are not loading, so that might be worth looking into.  Ultimately, this loading issue looks like it's specific to the RI.

*I'd still like to re-check these changes in Staging, once deployed.  We're limited by SOCKS-proxy requirement to testing against only 2 platform-browser combos, not to mention often-unstable API/backend in the RIs making validation a kind of "hit-or-miss" affair.

**Comment by tlei123** [comment] 2022-09-10 01:50
Checked in Staging, and CC Detail-page is working fine.

Found one unrelated mobile-screen styling bug &mdash; #46877

**Comment by ldelacosta** [comment] 2022-09-12 18:04
@tlei123 -  The changes have been implemented in staging. Please re-check when you have a chance. Thanks!

**Comment by tlei123** [comment] 2022-09-12 20:07
@ldelacosta , successfully validated on Staging.  You've already seen the logged defect #46877 &mdash; that's the only bug I saw, and unrelated to our changes here.

cc @ryanshaw @simiadebowale

**Comment by ldelacosta** [comment] 2022-09-13 20:04
No new issues reported in this ticket. Closing out the ticket.

**Closed by ldelacosta** 2022-09-13 20:04 UTC
Labels: frontend, vaos, tech-debt
