### ISSUE TITLE
Treated disability names don't match disability names

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1536] opened 2019-09-04 16:44 UTC
@markgreenburg commented on [Mon Jul 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19246)

We continue to see error reports where veterans attempt to associate a treated disability from their list of `treatedDisabilities` to their VA medical records evidence, but the submission fails due to the treated disability name not matching any of the specified disability names. E.g., error key `form526.treatments[0].treatedDisabilityNames.isInvalidValue` here: http://jenkins.vetsgov-internal/job/rake_tasks/job/vets-api-form526-errors/29/console

**Comment by Mottie** [comment] 2019-09-18 18:06
Neither @ndsprinkle nor I are able to access the jenkins page without a PIV

**Comment by Mottie** [comment] 2019-09-20 20:13
Actually, I was wrong. I can check Jenkins, but not at the URL that was shared.

Use: http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-form526-errors/

But, I'm only seeing the last 3 reports? Currently 32-34; I can't get to 29 where the reported error occurred.

![Screen Shot 2019-09-20 at 2 49 12 PM](https://user-images.githubusercontent.com/136959/65355983-ec833d00-dbb8-11e9-962a-c509955ff6b3.png)

I'm not sure how to proceed. @SMLuthi any suggestions?

**Comment by ndsprinkle** [comment] 2019-09-23 14:53
@Mottie Were you ever able to get to report 29? I can't even hit the link at all (because of no PIV I'm sure).

**Comment by Mottie** [comment] 2019-09-23 17:56
I wasn't able to access that record. You should be able to get to that page without a PIV after [starting up the proxy](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/internal-tools/#starting-the-socks-proxy).

**Comment by aeltarhoni** [comment] 2019-09-25 18:24
@ndsprinkle will follow up

**Comment by ndsprinkle** [comment] 2019-09-25 21:14
I have followed up with Mark on this and will report back once I hear from him.

**Comment by ndsprinkle** [comment] 2019-09-26 16:14
According to Mark, this still happens frequently. He says this is another example: http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-form526-errors/35/console

And he said that any message that reads like "form526.treatments[0].treatedDisabilityNames.isInvalidValue: The disability name tinnitus does not match any disability name from your list of disabilities" is an example.

**Comment by ndsprinkle** [comment] 2019-11-18 22:37
Update after finally digging into this earlier today:

There are 25 examples of this error happening here: http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-form526-errors/35/console

So far, I haven't identified a common pattern to definitively say what the issue is. However, nearly all of the errors are from disabilities that are not on the predefined disability labels list, which means the veteran entered a custom disability for those. Again, I can't say for certain this is related to the issue yet as there are two examples where the veteran did select from the disabilities drop down (instead of entering a custom one) and is still getting the error. Using or not using a predefined disability shouldn't be causing this error, but it is something that I noticed about this particular sample of errors.

My next steps will be trying to replicate this error. I can see several scenarios that could potentially cause this to happen, but I'll have to investigate more into how the form is modifying these disabilities before submission and what changes we let the user make to their disabilities and their disabilities assigned to treatment centers to see if there is some disconnect where one value gets changed but the other doesn't.

**Comment by ndsprinkle** [comment] 2019-11-19 16:57
http://jenkins.vfs.va.gov/blue/organizations/jenkins/rake_tasks%2Fvets-api-form526-submission/detail/vets-api-form526-submission/278/pipeline/

Running that submission rake task on submission 42157 reveals the json from the veteran's submission attempt. The error that we are getting back from EVSS is basically saying "there is a disability assigned to a treatment facility that isn't in your list of disabilities." However, looking through the JSON, the disability that has thrown the error in this example does in fact exist both inside treatedDisabilityNames (disability assigned to a treatment center) and inside ratedDisabilities (list of your disabilities), so I'm not sure why the error is happening here. I will need to investigate more submission examples to see if this is always the case.

**Comment by ndsprinkle** [comment] 2019-11-19 17:38
http://jenkins.vfs.va.gov/blue/organizations/jenkins/rake_tasks%2Fvets-api-form526-submission/detail/vets-api-form526-submission/279/pipeline

Same situation for that submission, both disabilities attached to the treatment center are also within the veteran's list of disabilities. This leads me to believe this error message from EVSS is simply wrong. I am going to reach out to Silvio to see if this is a possibility.

**Comment by ndsprinkle** [comment] 2019-11-19 18:45
I met with Silvio and we discovered the error is occurring because there are disabilities for the treatment centers that have a disabilityActionType of "NONE". Disabilities with an action type of "NONE" are not sent to EVSS (stripped out by vets-api), which would explain why EVSS doesn't see the disability in the list. I confirmed this theory by running another rake task: http://jenkins.vfs.va.gov/blue/organizations/jenkins/rake_tasks%2Fvets-api-form526-submission/detail/vets-api-form526-submission/280/pipeline

After running through the form to test situations, it seems that the main way for this error to happen is if the veteran marks one or more rated disabilities as worsened, adds one or more of these worsened disabilities to a treatment center, and then, either on the Rated Disabilities page or the Review Page, removes the mark that signifies the disability is worsened. This causes the disability to lose its worsened flag, but it still remains attached to the treatment center, which ultimately causes the EVSS error. This lingering disability does not appear visually under the treatment center, so the veteran has no way of knowing that it's still going to be submitted as attached to the treatment center.

@YanaRoy I will go ahead and create another ticket for the work of fixing this situation and you can let me know if this ticket is good to be closed.

**Comment by ndsprinkle** [comment] 2019-11-19 21:03
@YanaRoy Ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3591

**Closed** 2019-11-20 16:37 UTC
Labels: 526, frontend, vsa-benefits
