### ISSUE TITLE
[Letters App] DataDog monitoring and alerts

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#70651] opened 2023-11-27 21:24 UTC
## Value Prop

Monitoring product performance so we can address issues quickly. 

## Background

In order to maintain confidence in the Letters App as well as to predict and respond to issues, the error rate should stay below a low water mark. Above the low watermark is a warning sign. Above a high watermark is a problem. Error rates should be measured for each error type on each endpoint.

Notes:
- We don't have DataDog write access so we can't directly create monitors and alerts. 2 ways around this are:
  - Build out a temporary chart with the information needed to complete this work and work with Steve Albers to create the monitor; Steve has write access.
  - Build out a temporary chart and translate that into Terraform. Make a pull request to the [devops repo](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog)
  
  Data Dog dashboard: https://vagov.ddog-gov.com/dashboard/86n-b39-hhn/benefits-management-tools-letters?refresh_mode=sliding&from_ts=1700515036918&to_ts=1701119836918&live=true
 
## Acceptance Criteria:
- [ ] Low watermark identified w/ appropriate alerts sent to alert channel
- [ ] High watermark identified w/ appropriate alerts sent to alert channel
- [ ] Set up quick dashboard in DD and document query used
- [ ] Document DD config (Alert created and routed to #benefits-management-tools-notifications Slack channel, Chart created and added to Datadog dashboard, etc.)

**Comment by HeatherWidmont** [comment] 2023-12-15 17:41
Engineers are meeting with @data-doge to discuss today

**Comment by HeatherWidmont** [comment] 2023-12-18 17:20
Jerek & Sam walked Eugene through the products. Eugene will put together a rough proposed plan (possibly tickets), then review with the team & go from there.

**Comment by HeatherWidmont** [comment] 2024-01-19 17:34
@samcoforma & @data-doge will be pairing on this after standup

**Comment by HeatherWidmont** [comment] 2024-02-02 17:45
Closing, duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/73634

**Closed by HeatherWidmont** 2024-02-02 17:45 UTC
Labels: benefits-team-1, benefits-management-tools
