### ISSUE TITLE
Header Injection CSS Issue on Benefits.VA.gov

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#1946] opened 2019-09-20 13:30 UTC
## What happened?
The CSS for the two bottom menu items, Service member benefits and Family member benefits, is not rendering correctly. Screenshot attached.
 
![benefits-va-gov](https://user-images.githubusercontent.com/50150810/65330622-fa20ce80-db88-11e9-85b9-ede2a507d0fa.png)

## Specs:
- Device: MacBook Pro (Retina, 13-inch, Early 2015)
- Browser: Google Chrome Version 75.0.3770.142 (Official Build) 

## Steps to Reproduce
- URL: benefits.va.gov

## Desired behavior
It's supposed to look like this
![va-gov](https://user-images.githubusercontent.com/50150810/65330705-2b010380-db89-11e9-9b1f-b25721e718a9.png)

## Acceptance Criteria
- [ ] Typefaces for those menu items render identically to how they render on VA.gov

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by KevinMHoffmanUSDS** [comment] 2019-09-20 13:31
@batemapf Like this... also, feel free to let me know who I might normally assign this sort of thing to.

**Comment by cvalarida** [comment] 2019-09-23 18:04
:thinking: This is interesting. I've outlined the problem in a little more detail, but don't know what the root cause is offhand. Looking into it, this might be a Global UX team issue?

## Problem
The `font-family` for the `Service member benefits` and `Family member benefits` links is wrong.

**Records link**

| Site | `font-family` | Source |
| --- | --- | --- |
| VA.gov | Source Sans Pro,Helvetica Neue,Helvetica,Roboto,Arial,sans-serif | `.usa-button, .usa-button-primary, .usa-button-primary:visited, .usa-button:visited, [type=button], [type=image], [type=reset], [type=submit], button` |
| benefits.va.gov | Source Sans Pro,Helvetica Neue,Helvetica,Roboto,Arial,sans-serif | `.consolidated .usa-button, .consolidated .usa-button-primary, .consolidated .usa-button-primary:visited, .consolidated .usa-button:visited, .consolidated [type=button], .consolidated [type=image], .consolidated [type=reset], .consolidated [type=submit], .consolidated button` |

**Service member benefits link**

| Site | `font-family` | Source |
| --- | --- | --- |
| VA.gov | inherit | `body.merger` |
| benefits.va.gov | Arial,Helvetica,sans-serif | `div` (not sure why) |

**Comment by alexpappasoddball** [comment] 2019-09-23 18:08
@Karak888 I have added your teams labels to this one.  Let me know when you have eyes on it and I will remove it from the Triage backlog once you confirm your team will take ownership.

**Comment by ncksllvn** [comment] 2019-11-18 16:50
This is done -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/0f20707b-b6e2-4ac6-8767-4328721f7f5c)

@Karak888 can you close?

**Comment by ncksllvn** [comment] 2019-11-18 16:52
Oof, nvm, it looks like benefits.va.gov has a special edge case and we need an additional patch -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/eb4635b0-1a0b-43eb-a3b9-d64b6978c8af)

Alrighty, well, moving this back to Ready...

**Comment by ncksllvn** [comment] 2019-11-19 20:27
@Karak888 Just merged this work - it'll go live tomorrow. Should we close?

**Comment by Karak888** [comment] 2019-11-19 21:10
@ncksllvn yes let's just make note to double check tomorrow! Moving to close now..

**Closed by Karak888** 2019-11-19 21:10 UTC
Labels: bug, vsa-public-websites
