### ISSUE TITLE
Back to top polish

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#16192] opened 2020-11-14 12:32 UTC
## 1. Ensure this code and behavior is accessible. 

pinging @jenstrickland  — see it in action [on this Resource page](https://www.va.gov/resources/signing-in-to-vagov/). 

## 2. Add white space at footer

currently the button is kiss-fit with the footer, but we should leave some space there:

![image](https://user-images.githubusercontent.com/12564977/99146877-2d0a0980-264a-11eb-9a99-dac3b406a5dd.png)

If the bottom-dead-center position could be visually centered between the top of the footer and the horizontal rule above "Last updated", that would do the trick. This goes for mobile and desktop.

## 3. Apologies—I did not include active or hover states

I think we can skip an **active** state (active meaning "on-click") as the action of jumping to the top is confirmation, but i can be dissuaded. double checking with @jenstrickland that i'm not violating anything.

For **hover**, let's keep it simple and use `$color-black #000000` from [our palette.](https://design.va.gov/utilities/color)

## 4. Mobile tweaks

1. The corner radius of the button is different on mobile—the top-right and bottom-right corners should have a radius of `0`
2. The button should be square, not rectangular. If there is a way we can ensure a 44x44 size, that would be wonderful, but if that breaks something, whatever our button default height (and consequently width since its square) is fine.
3. The up-arrow icon should be larger (in Sketch it is 24px if that helps)

Comp for clarity:

![image](https://user-images.githubusercontent.com/12564977/99146639-0945c400-2648-11eb-9cd4-900aaf2f2156.png)

**Comment by brianalloyd** [comment] 2020-11-16 20:54
@zacharymorel talked with @johnhashva who would like to make a clean break over to Decision Tools so I've assigned this to @youngfreezyVA to work.  Could you please collaborate with each other as a way of handoff in support?  Thank you in advance.

**Comment by zacharymorel** [comment] 2020-11-16 22:05
Afternoon @brianalloyd , I have the work and I will create a PR tomorrow morning with the work that fixes these listed issues.
I chatted with Fareez earlier and he said he would pick up any PR feed back given.

**Comment by youngfreezyVA** [comment] 2020-11-16 22:10
sounds good to me @zacharymorel 
since i'm not familiar with the ticket please provide steps to reproduce/dev workflow to see the issue locally, in your PR.
thank you!

**Comment by brianalloyd** [comment] 2020-11-16 22:43
Thanks @zacharymorel for the follow up and effort.  Appreciate it.

**Comment by zacharymorel** [comment] 2020-11-17 15:20
PR created for this work. 
Steps to run env: 

1. Once checked out to feature branch, make sure you've pulled today's drupal content if you haven not already. `yarn build:content --pull-drupal`
1.5 If you have pulled today's content and have a `.cache` dir within the root of the project, you can just run `yarn build`.
2. From there, run `yarn watch --env.entry=static-pages`
That's it, should be good.

**Comment by brianalloyd** [comment] 2020-11-17 22:53
Thanks @zacharymorel for the continued support.  @youngfreezyVA tag your it. Let me know once validated so we can close this out.  Thanks.

**Comment by youngfreezyVA** [comment] 2020-11-18 17:30
looks good... I just approved the PR. @zacharymorel can you please rebase with master before merging it in, and verify one last time? I was unable to get the feature branch working/running until i merged in the latest w/ master.

**Comment by zacharymorel** [comment] 2020-11-19 15:54
@rtwell @jenstrickland Button updates are not live.
https://staging.va.gov/resources/signing-in-to-vagov/

**Comment by jenstrickland** [comment] 2020-11-19 17:35
Thanks, @zacharymorel — I still need to write up the issue ticket for making this button accessible for assistive tech. I'm trying to track down the previous notes. 

There were a couple of approaches we discussed:

1. If the sticky button was the chosen direction, then it would need aria applied to announce it to screen readers, and then focus management to make it clear where the user is and what options are available.

1. If the Back to top link is provided at the bottom of individual sections it will be more accessible, as it will be part of the nature page flow. If there's a way to develop it so that it is within the page content, and positioned absolutely to match the design, that would work really well.

**Comment by rtwell** [comment] 2020-11-20 18:03
This issue should not be closed as it is not complete.

**Comment by rtwell** [comment] 2020-11-20 18:04
what's missing: **The corner radius of the button is different on mobile—the top-right and bottom-right corners should have a radius of `0`**

**Comment by jenstrickland** [comment] 2020-11-20 18:13
Additionally, the implementation must be 508-compliant and accessible. The options recommended were: 

1. If the sticky button is the chosen direction, it needs aria applied to announce it to screen readers, and then focus management to make it clear where the user is and what options are available.

1. If the Back to top link is provided at the bottom of individual sections it will be more accessible, as it will be part of the nature page flow. If there's a way to develop it so that it is within the page content, and positioned absolutely to match the design, that would work really well. 

Before launch to production it must have an accessibility review, so please create a ticket for the VSA accessibility specialist to review before launch. Teams can use the request ticket linked on this VSA accessibility review process page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-reviews

**Comment by rtwell** [comment] 2020-11-20 18:13
I would also like the logic of the full button/vs mobile button to work like this (and I apologize @zacharymorel if I am contradicting myself from our convo earlier, but now that I see this work, it's clearer to me). It would great if whenever the button would be right-aligned **against** the viewport (which is dependent on breakpoints) that it would be the square (mobile) incarnation, and the full version when it is NOT against the viewport.

**Comment by youngfreezyVA** [comment] 2020-11-20 18:34
ok understood! my bad for closing it out too early. i'll be working on this ticket moving forward and will carefully review the comments above. thank you.

**Comment by youngfreezyVA** [comment] 2020-11-20 23:25
@rtwell implemented your feedback. 
@jenstrickland my understanding is we are going with option #1. which aria labels would you recommend?
we can chat on Monday, and i will submit the accessibility specialist review.
cc: @brianalloyd

**Comment by rtwell** [comment] 2020-11-23 12:36
@youngfreezyVA looks like the corners are all round still, and the breakpoint behavior doesnt appear to have changed—
![image](https://user-images.githubusercontent.com/12564977/99962526-5586b780-2d5e-11eb-952c-5bbe3521b40d.png)

I'm using [https://staging.va.gov/resources/signing-in-to-vagov/](https://staging.va.gov/resources/signing-in-to-vagov/) to check changes

**Comment by jenstrickland** [comment] 2020-11-23 13:59
@youngfreezyVA I would recommend that the implementation be changed, and that the "back to top" button be inserted at the bottom of each section. That way, it is accessible by keyboard and announced to screen readers in the content flow. It could be persistently visible there. Aria-live behavior in screen readers can be erratic, so we tend to avoid it on VA.gov.

Relevant Section 508 requirement: [WCAG 2.0 Level AA - 3.2.3 Consistent Navigation](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-locations.html)

Here's a write-up from gov.uk on sticky functionality: https://technology.blog.gov.uk/2018/05/21/sticky-elements-functionality-and-accessibility-testing/ They opted to not implement sticky headers, for example, due to the challenges for a range of users, as well as accessibility issues.

**Comment by youngfreezyVA** [comment] 2020-11-23 16:19
hi @rtwell changes aren't reflected there just yet. i updated the breakpoint as you suggested. i'll let you know who when it's viewable at that link.
@jenstrickland I will get back to you regarding changing the implementation after discussing with @brianalloyd in standup.

**Comment by brianalloyd** [comment] 2020-11-23 16:49
@jenniferlee-dsva wanted to loop you into the discussion, what's the desired approach related to the comment:
> I would recommend that the implementation be changed, and that the "back to top" button be inserted at the bottom of each section. 

Let me know as this would change scope slightly and require a more targeted focus for implementation from the FE team.  Thoughts?

**Comment by jenstrickland** [comment] 2020-11-23 16:51
@brianalloyd The recommendation should be a simpler implementation, however it does require @rtwell to determine if a design change is desired here.

**Comment by rtwell** [comment] 2020-11-23 16:57
sorry—i don't think I'm following @jenstrickland 

Are you saying that instead of a single, fixed button (like it is now), you would prefer multiple static instances at the tail end of each section? or am i confusing something. sorry if i'm missing something!

**Comment by jenstrickland** [comment] 2020-11-23 17:04
@rtwell —That would be the most straightforward solution. If the team wants to retain the appearance of a sticky button, there are a few considerations to work through, that would require custom JavaScript and additional QA time with browsers and screen readers. The gov.uk decision to avoid implementing sticky components lists a few of the reasons. 

To implement the sticky button, how would we let non-sighted users know that the button is available throughout the screen?

**Comment by jenstrickland** [comment] 2020-11-23 18:59
Met with @rtwell. 

1. We have a sticky button that is located in the page source just above the footer. This works for sighted users, and is okay as-is, except rather than placing it just above the footer it should be the last item in the parent container (see sketch below). One caveat, I want to connect with @1Copenut — to learn if we should use aria-live to announce the button for assistive tech.

1. We do need an option for non-sighted users. We may accomplish this with a `<button>` that is screen reader only, so it announces to assistive tech users in the page flow. This should be positioned above every `h2` except the first one. The last one is the one that sighted users see. This behavior should not change any visual design.

```
<Parent container>

  <h2>Heading 2</h2>
  <p> Section content, may be multiple paragraphs</p>
  <button>Back to top</button>

  <h2>Heading 2</h2>
  <p> Section content, may be multiple paragraphs</p>
  <button>Back to top</button>

  <h2>Heading 2</h2>
  <p> Section content, may be multiple paragraphs</p>
  <button>Back to top</button>

  <h2>Heading 2</h2>
  <p> Section content, may be multiple paragraphs</p>

  <button>Back to top</button><!-- This is the one sighted users see -->
</Parent container>

<Complementary info>
  <p>Content</p>
</Complementary info>

<footer>
</footer>
```

Feel free to reach out to me if there are any questions, or if I may help.

**Comment by rtwell** [comment] 2020-11-23 19:00
awesome @jenstrickland thank you for clarifying! Very helpful.

**Comment by brianalloyd** [comment] 2020-11-23 19:22
Yes, thanks @jenstrickland for the update and support.  @youngfreezyVA can you review the details and let me know if you have any questions on implementation elements?  Thanks.

**Comment by kelsonic** [comment] 2020-11-23 19:57
@brianalloyd I think these markup changes are out of scope for this ticket as the AC seem to have changed a lot. Could we create a follow-up ticket to knock out this follow-up work?

**Comment by youngfreezyVA** [comment] 2020-11-23 19:58
@jenstrickland i understand the logic behind moving the back to top button to be the last element in the child container. not clear on why we need to repeat the non-visible button on the page that many times, i'm probably missing something. 

@brianalloyd since it seems like accessibility wasn't considered when developing this ticket from the beginning, i'd suggest reopening the original ticket, and we can go through the accessibility review process after I address the above comments.

**Comment by brianalloyd** [comment] 2020-11-23 20:12
@youngfreezyVA and @kelsonic I've created a new ticket as suggested that will point back to this ticket for clarity.  Let me know if you have any questions or if the new ticket needs to be clarified.

**Comment by jenstrickland** [comment] 2020-11-23 20:37
@youngfreezyVA  If a user is navigating the page with a screen reader, they will not know there is a "Back to top" link available to them on par with the sighted user's experience. The screen reader user will only hear the link after reading through **all of the page content** to just before the footer. If you navigate to the page and read the page with the screen reader only — don't look at the page, the issue becomes evident. It's an awful lot of content to have to sift through. We need to make sure that the component meets our Section 508 obligation for consistent navigation. We can reduce the burden on non-sighted users, and meet requirements of the initial design, by providing the button for non-sighted users. If `aria-live` were reliable, we could potentially use that, but we've had issues with it on VA.gov in the various screen readers we test with.

**Closed** 2020-11-24 17:56 UTC
Labels: bug, planned-work, vsa, vsa-public-websites
