### ISSUE TITLE
[BE] 10-10EZR: Discovery: what caused DD Issue from 1/22/24?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74228] opened 2024-01-23 14:45 UTC
- [ ] Determine what caused the error throw up on 1/22
- [ ] Explain issue to team
- [ ] Determine if we need to create a new ticket for fix or if it falls under something we're currently working on
- [ ] [Slack thread](https://dsva.slack.com/archives/C0310PNS7TQ/p1705953488920799)

**Comment by lihanli** [comment] 2024-01-26 17:48
the error was caused by a submission which was missing name and ssn, should be fixed now

**Closed by lihanli** 2024-01-26 17:48 UTC
Labels: backend, discovery, 1010-team, needs refinement, 1010-ezr

**Comment by alexseelig** [comment] 2024-01-26 17:57
Thanks @lihanli !
