### ISSUE TITLE
Direct Scheduling Error With Clinic Prohibit Access

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#22740] opened 2021-04-06 19:23 UTC
This may be a duplicate issue but I can't find the one I had logged previously.  So I am logging a new issue.  

Sites can limit access to a clinic to only certain users. 

If a site configures a direct schedule clinic with Prohibit Access **and** does not make viabapplication proxy user a privileged user  **and** a veteran tries to schedule into that clinic a 502 error is seen in dev tools.  

The error message tells the veteran to start over and try again but the same thing will happen again.  

- In VATS set up Dayton for Direct Schedule = Yes any for optometry.  
- In VAOS sign in as Ruben Moreno and try to direct schedule in Dayton VAMC, Optom/Contact Lens (which is a clinic configured for direct scheduling **and** has prohibit access **and** viabapplicationproxy is NOT a privileged user). 

- Actual response error modals display and tells user to try again. Which if they do the same thing will happen again.  ![VAOS_AppProxyNotPrivUser.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/a533a02d-7e2d-497d-8412-87e9cb1dd8e4)

**Comment by jbalboni** [comment] 2021-06-04 21:05
This is happening because we're getting a 500 error instead of a 400 error from the VAMF service. Not sure if they've fixed this. @saneshark @grossb1

**Comment by marcynadeau** [comment] 2021-08-13 13:36
@jbalboni @laurenernest Any update on this? confirmed this is still an issue in Staging.

**Comment by jbalboni** [comment] 2021-08-13 14:23
@marcynadeau I opened a backend ticket for it again the other day, since that's where the issue is: https://issues.mobilehealth.va.gov/browse/VAOSR-2288

**Comment by grossb1** [comment] 2021-09-14 16:32
This will be tracked in the backend Jira system, closing this ticket

**Closed by grossb1** 2021-09-14 16:32 UTC
Labels: backend, blocked, vaos, vaos-needs-qa-staging
