### ISSUE TITLE
Analytics Reporting Request for Beth Potts

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14213] opened 2020-09-30 18:17 UTC
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
We want to: determine if people are using 
1/ this page: https://www.va.gov/welcome-kit/
2/ the PDFs on this page

- [Christopher.Johnston2@va.gov Jennifer.Lee27@va.gov]

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - DEPO - Chris Johnston
    

## Timeframe for Analytics Requested
We'd like data that compares last year with this year.

## Analytics to Track Down

- Non-VA network traffic to this page: https://www.va.gov/welcome-kit/
- Organic search traffic
- PDF download rates - all the PDFs on this page
- Referrals (are ppl coming from emails, social media, other VA.gov pages?)

## Other Helpful Questions to think through
- Who is your audience? DEPO and VEO
- Why do you need this data? Is it worth the time spent/resources to create QSGs?
- What are you hoping to find? Are Veterans using QSGs?
- What is your hypothesis that you're hoping the data will support? We're not sure, really, how much Veterans are taking advantage of these QSGs.
- What area of the VA are you hoping to assess? VEO
- How frequently do you need this data? Can you make this data available as a 1/ dashboard and 2/automated quarterly report?
Please include Beth Potts, Danielle Thierry, Jen Lee, Chris Johnston, Tim Hudak, and Laura Prietula as members for the dashboard and reports: 
beth.potts@va.gov 
danielle.thierry@va.gov
jennifer.lee27@va.gov
christopher.johnston2@va.gov
timothy.hudak@va.gov
laura.prietula@va.gov

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2020-10-02 11:46
Hi @bethpotts, 

Thank you confirming receipt, will be in touch shortly!

**Comment by jonwehausen** [comment] 2020-10-02 13:21
@bmcgrady-ep Could you push forward on this request when you have capacity? 

Here's what I've gotten started: 
- Setup BigQuery view of all file downloads (shared with you)
- Setup [DOMO Config to query this view ](https://va-gov.domo.com/datasources/2054d92d-cb84-4448-a031-b4182eeaf8ab/details/overview)
- Setup [initial card](https://va-gov.domo.com/analyzer?cardid=362972950) of file downloads on `/welcome-kit` page

Next steps: 
- Setup query for attribution (source / medium, referrals, previous page path, etc) to `www.va.gov/welcome-kit`
- Setup new chart displaying this data
- Setup new dashboard and QA
- Setup query to execute daily
- Share out dashboard with stakeholders

**Comment by bmcgrady-ep** [comment] 2020-10-05 22:49
@jonwehausen This report is ready to be QA'd. I added two additional charts - one for organic search traffic and one for all source/medium traffic. Let me know if I need to add another chart.

**Comment by jonwehausen** [comment] 2020-10-07 01:31
## QA Notes
@bmcgrady-ep 

1) Download counts look good when compared with total events against GA plotted weekly ✔️ : 
![image](https://user-images.githubusercontent.com/48527022/95277098-fe16a180-081a-11eb-8a4d-45a0f69d877e.png)



2) Reviewed the query and primarily looks good with the count aggregation of users, however said the end user counts don't match GA as closely as we would like
  - As a next step, can we try to refactor the query such that the `SELECT` aggregation is the last calculation and the `GROUP BY` runs consecutively as `1,2,3,4...etc` and unit test against the full range

**Comment by jonwehausen** [comment] 2020-10-07 01:32
@amycesal As @bmcgrady-ep tweaks some of the data here, when you have a moment would you mind taking a pass at a few of these charts and working your magic. Thanks in advance

**Comment by bmcgrady-ep** [comment] 2020-10-07 18:24
Hi @bethpotts - We only have data going back to June 2019 in BigQuery. Do you need all of 2019 data or are you okay with the data being from June 2019 - Present?

**Comment by bmcgrady-ep** [comment] 2020-10-08 17:55
Confirmed with @bethpotts [here](https://dsva.slack.com/archives/D01BQSR12RM/p1602174196002800) that the June 2019 - Present data is fine. @jonwehausen can you QA again when you have the capacity?

**Comment by bsmartin-ep** [comment] 2020-11-21 19:13
@bmcgrady-ep -

It looks like the `BQ - All File Downloads` dataset is back-filling all data every day...

https://va-gov.domo.com/datasources/2054d92d-cb84-4448-a031-b4182eeaf8ab/details/settings

![image](https://user-images.githubusercontent.com/62304138/99885409-a97c8980-2c02-11eb-98ef-099850f1c1a1.png)

Thoughts on updating this to an APPEND and just loading the previous day's data?  I'm not sure this needs to be a BQ view either (though I will defer to Jason on that one).

-----------------

I also updated the two bar charts to have a date range in the summary.

![image](https://user-images.githubusercontent.com/62304138/99885543-a3d37380-2c03-11eb-93e4-c261aa6dcb3e.png)

**Comment by bmcgrady-ep** [comment] 2020-11-23 15:47
@bsmartin-ep - I agree this should be an APPEND, instead of a REPLACE. @jonwehausen - What are your thoughts on this - can we make this an APPEND? I don't what to change it, since it looks like you are the owner of the dataset.

**Comment by bsmartin-ep** [comment] 2020-11-25 05:13
Updated to append.  Maybe change the name of the view?

**Comment by bethpottsVADEPO** [comment] 2020-11-25 20:22
@chrisj-usds @jenniferlee-dsva This is the analytics you'd requested for the Welcome Kit page with all the PDFs.

**Comment by jenniferlee-dsva** [comment] 2020-11-25 21:51
Not sure if it's bc the dashboard is still unavailable or if someone needs to give me dashboard permission, but right now, I get this error message when I try to access the DOMO dashboard. 

![image](https://user-images.githubusercontent.com/43381063/100285206-7ad21c00-2f3e-11eb-870f-5b5ea93e1751.png)

**Comment by bmcgrady-ep** [comment] 2020-11-25 22:40
@jenniferlee-dsva - I added you to the DOMO dashboard, so you should now have access.

**Comment by joanneesteban** [comment] 2020-11-30 19:58
@bmcgrady-ep to link out dashboard

**Comment by bmcgrady-ep** [comment] 2020-11-30 20:06
Added each of the users linked above to the dashboard.

**Closed by bmcgrady-ep** 2020-11-30 20:06 UTC
Labels: analytics-insights, analytics-reporting-request, analytics-request
