### ISSUE TITLE
Logout all devices button

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37198] opened 2022-02-18 14:56 UTC
## Issue Description
This will track the body of work that includes adding a button for the user to easily log out all devices in the Sign in Service (OAuth).  Because this is a direct change/impact to the Information Architecture (IA) this might need to go through the Content/IA cycle of testing.

## Tasks
- [ ] Setup meeting with Content/IA team to go over proposed changes
- [ ] Add button to Sign out of all devices on the FE and ensure it removes appropriate cookies, application storage, and uses the BE revoke all endpoint

## Acceptance Criteria
- [ ] I can click **Sign out of all devices** which will force all devices to de-authenticated

**Comment by charlye-bluetiger** [comment] 2023-03-15 19:50
- Logout of all devices button needs to be included for a security requirement
- Envs: 
    - Staging - SiS exists on all 
    - Production - only flagship VA.gov only on mobile
- QUESTION to be answered: Where would users prefer to see “log out” (of everything)?
    - Potential placement:
￼
- SSOe users should not see this option
    - Eventual goal to deprecate IBM solution across the board
    - Staggered migration of user sessions to leverage Identity’s SiS
- Timing for logout
    - SSOe 15 minute increments for keep alive, logout after 30 minutes
    - SiS 5 minutes refresh, logout after 30 minutes
- Timing:
    - Single sign on to access all VA sites e.g. MyHealtheVet, eBenefits, VA.gov
    - Logout of all sessions

**Comment by aparsley** [comment] 2023-07-11 19:22
- Could be just a discovery.
- Who do we need for this Research?

**Comment by aparsley** [comment] 2023-07-11 19:35
Pushing back until other high priority items are completed.

**Comment by charlye-bluetiger** [comment] 2023-09-20 13:58
@asg5704 @kingbmike is this a dupe of #[65208](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/65208) and [62224](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/62224)  

Is there a FE ticket for the actual implementation?

**Comment by asg5704** [comment] 2023-09-20 14:27
@charlye-bluetiger I'm not sure if that's a dupe. As I'm reading it, it seems like 62224 is the preliminary research (competititor analysis) you just did before we start 65208 which would be getting ready for the prototype + start of collab cycle research. Maybe 🤔

**Comment by charlye-bluetiger** [comment] 2023-09-26 21:05
@kingbmike you differentiate and fill out this story so that it reflects what's supposed to be happening in this story vs [65208](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/65208), please?

**Closed** 2023-09-26 22:07 UTC
Labels: Identity, identity-frontend
