### ISSUE TITLE
[Congressional] V12126054 Due 10/7/24 Rep Comer 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#92472] opened 2024-09-09 19:33 UTC
## Issue Description
Veteran has been restricted from using ID.me and Login.gov because veteran is receiving an error code 106.
---
https://app.slack.com/client/T03FECE8V/C02BS78NYRM

## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment] 2024-09-10 22:07
9/10/24: Sent details to the EVSS team to review and resolve.  Jeremy is OOO, back up is Chris.  Dale was included on email.

**Comment by Kimberley2023-CSM** [comment] 2024-09-13 13:47
9/11/24:  Chris responded confirming the EVSS team is able to resolve this issue.
Awaiting status update.

**Comment by Kimberley2023-CSM** [comment] 2024-09-17 14:48
9/17/24: Reached out to Chris, from EVSS team for a status update on case.
Awaiting response.

**Comment by Kimberley2023-CSM** [comment] 2024-09-17 15:51
Update 9/17/24: The veteran had duplicate corporate records as well as duplicate BIRLS records. This was resolved as of yesterday, 9/16. EVSS has sent e-mail communication to the veteran informing them that the issue the veteran was experiencing should be resolved and requested confirmation. We have not received a response at this time. We will continue to reach out to the veteran in hopes they will provide confirmation that this issue is resolved for them.
Since the case isn’t due until October 7th, I will not close it out until we receive confirmation from the Veteran that it is resolved.
I will check in periodically for the confirmation unless you respond first.

**Comment by Kimberley2023-CSM** [comment] 2024-09-18 14:04
9/18/24:  Chris responded with an update:  Late yesterday the veteran confirmed via e-mail that their issue is resolved. I have attached that communication (in email).
(CC 
@Erica Robbins [GovCIO]
)

**Closed** 2024-09-18 14:05 UTC
Labels: VSP-contact-center
