### ISSUE TITLE
[Bug] Incorrect user data showing on My VA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#3271] opened 2019-11-12 15:37 UTC
We got in this report via email — **a veteran is saying that they are seeing someone else's prescription data on their My VA dashboard and they are not seeing this erroneous data in MyHealtheVet**. I am not sure how this is even possible based on how this is built, but we need to have a FE person look into this ASAP. 

Below is all the information I have. The person did include their email address in this complaint and said someone could reach out, so let me know if you want me to set up a call with this person.

Here is the content of the email:

> Good evening,
> 
> This is a screen shot of my va.gov “my va” page/tab. Over the last few days as I have accessed the site and chosen to select the “MY VA” tab when the page opens.  I am repeatedly observing prescriptions, in this case refills for other peoples medications being listed on my screen. Ironically I just signed up and was approved for VA health care on the 8th. I don’t have any history, doctors, medications etc as I have yet to establish even a first appointment. 
> 
> To help, if I choose the my health tab and either run a blue button report or select my medications (variety of tabs) I do not see this erroneous info translate to the my health web site. If I return to the VA site and select the “ My VA” tab I will continue to see the medications listed. If I log out and log back in its 50%/50% if it will happen again and I see different medications listed all the time so it is associating various/random data with me, not simply replicating the same thing.
> 
> So a potential issue for you to examine. Right now you can’t identify the “who” (as I stated this stuff isn’t for me) is associated with what I see but it could be that as you continue to migrate and link systems it could get out of hand.

**Comment by lkoenigsberg** [comment] 2019-11-12 15:44
@Justin-Pickett , consider this for grooming tomorrow.

**Comment by erikphansen** [comment] 2019-11-13 16:25
First guess is that for some reason the call to `GET v0/prescriptions/active` is sometimes returning the incorrect data for this user. We might need to find out what method they use to log in. @hinzed1127 Do you know if it would be possible to make API calls _as this user_ if we had enough of their info? I'm guessing not.

**Comment by annaswims** [comment] 2019-11-13 22:06
It's possible that the veteran has more than one active mhv_correlation_id associated with their identity.  If that's the case we would log it to sentry here:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/11420/events/?query=is%3Aunresolved%20Multiple%20active%20MHV%20correlation%20IDs%20present

And it looks like we arbitrarily pick the first here.
https://github.com/department-of-veterans-affairs/vets-api/blob/27e8132dfd1e125bcfe80661446229baa4743a8f/app/services/mhv_account_type_service.rb#L53

Also depending on how a user logs in, we may get their id from either the identity provider or MVI.  
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L103

**Comment by erikphansen** [comment] 2019-11-14 19:04
@jholton @omgitsbillryan Did you guys see Anna's post above?

**Comment by jholton** [comment] 2019-11-18 02:01
The issue appears to be resolved.

## Background

Requesting Prescription or Secure Message data is a two step process.
First, we take an MHV correlation ID that corresponds to an end user (veteran).  We use this MHV correlation ID to request a token from 

We start with an [`MHV correlation ID`, which is obtained from SAML data for MHV sign-in users OR MVI upon login](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/app/models/user.rb#L103).
We [instantiate an Rx client with this MHV correlation ID](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/app/controllers/rx_controller.rb#L12).
We [request a token from the MHV API for this MHV correlation ID](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/common/client/concerns/mhv_session_based_client.rb#L47).
We can now [use this token](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/common/client/concerns/mhv_session_based_client.rb#L72) to [request prescription info](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/rx/client.rb#L39).

## The problem

The problem was that the token we obtained from the MHV API did not correspond to the given MHV correlation ID.
Veteran A would request a token with Veteran A's MHV correlation ID, but would receive a token for Veteran B.
These [tokens are cached for 15 minutes](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/rx/client_session.rb#L8).
Therefore 15 minutes later, or with the initiation of a new va.gov session, Veteran A would again request a token with Veteran A's MHV correlation ID, but would receive a token for Veteran C or Veteran D or any other veteran.

**Comment by jholton** [comment] 2019-11-18 20:07
The issue appears to be resolved.

## Background

Requesting Prescription or Secure Message data is a two step process.

We start with an [`MHV correlation ID`, which is obtained from SAML data for MHV sign-in users OR MVI upon login](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/app/models/user.rb#L103).
We [instantiate an Rx client with this MHV correlation ID](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/app/controllers/rx_controller.rb#L12).
We [request an MHV session token from the MHV API for this MHV correlation ID](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/common/client/concerns/mhv_session_based_client.rb#L47).
We can now [use this token](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/common/client/concerns/mhv_session_based_client.rb#L72) to [request prescription info](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/rx/client.rb#L39).

## Problem Summary

The problem was that the token we obtained from the MHV API was not correct for the given MHV correlation ID.
Veteran A would request a token with Veteran A's MHV correlation ID, but would receive a token for Veteran B.
Thus subsequent reqeuests for prescription info would return Veteran B's prescription data to Veteran A.
These [tokens are cached for 15 minutes](https://github.com/department-of-veterans-affairs/vets-api/blob/6f1ceb946edb6fc7b568eb262c5d8ba8d34b317a/lib/rx/client_session.rb#L8).
Therefore 15 minutes later, or with the initiation of a new va.gov session, Veteran A would again request a token with Veteran A's MHV correlation ID, but could receive a token for a different veteran.

## Investigation

I used `curl` commands to test requesting MHV API tokens.
`curl https://essapi.myhealth.va.gov:443/mhv-api/patient/v1/session -A "Vets.gov Agent" -H "appToken: REDACTED" -H "mhvCorrelationId: REDACTED" -v`
Expected behavior is that I get back a different token for every valid request, including repeated requests for the same `mhvCorrelationid`
Expected behavior is that I get back a 400 response for an invalid `mhvCorrelationId`
This was not happening. I noticed that requests made in quick succession received the same token, no matter the `mhvCorrelationId` provided.  I tried with a known good `mhvCorrelationId` and also with random digits.  For a period of 5 minutes all requests received the same token in response. Then it would change and all requests would receive the new token for 5 minutes.  In fact, after the issue had been resolved, it became clear that all of my `curl` requests were malformed<sup>1</sup> and should have all received 400 responses when they all received 200 responses with tokens corresponding to random end users (veterans).

<sup>1</sup> I was making the `curl` requests with single-quotes around the `appToken` and `mhvCorrelationId` values. Quotes should not be used.

I was in communication with MHV API engineers.  They have the ability to decrypt the tokens and view the `mhvCorrelationId` associated with the token.  They confirmed that the tokens being returned did not correctly correspond with the given `mhvCorrelationId`

## Root cause

The MHV API engineers determined that there was a caching configuration issue in their system.  Tokens were cached, and due to the configuration bug, the same cached token was returned for all requests for a period of 5 minutes.  Then a new token was cached and returned for all requests for 5 minutes.  Repeat, ad infintum.


## Resolution

The MHV API engineers:
* confirmed the problem was present
* implemented a fix
* rolled back the fix and confirmed the problem returned
* re-implemented the fix

At this point I generated a token for my known good `mhvCorrelationId`.  MHV API engineers confirmed that token I received did indeed correspond to the give `mhvCorrelationId`.
I also now received 400 responses for bad/made-up `mhvCorrelationId`s, whereas before I was receiving MHV session tokens.

MHV API engineers plan to do further investigation in the coming week.

**Comment by erikphansen** [comment] 2019-11-19 01:36
It sounds like this caching issue was affecting _everyone_ who got these MHV tokens? And we only heard from one guy who was seeing the issue? 😱

**Comment by jholton** [comment] 2019-11-19 01:42
Correct. 

More info learned today: MHV engineers believe this issue started on Nov 2. 
Fixed on Nov 15.

**Comment by erikphansen** [comment] 2019-11-19 20:59
Closing this as it seems resolved.

**Closed by erikphansen** 2019-11-19 20:59 UTC
Labels: My VA, bug, frontend, vsa-authenticated-exp, vsa-triage
