### ISSUE TITLE
[Time-boxed research spike] - Investigate SiP Errors

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#20296] opened 2021-02-22 20:45 UTC
## User Story

As a Veteran with an SiP health care application
I want to be able to enter both a mailing and home address on the 10-10EZ

Note: Bug was discovered in Staging on 2/22. 

## Goal
Spend a day investigating the root cause of the SiP bug on the HCA (where the new button is missing)

## Acceptance Criteria 
Understand and document what the next steps are
Link to bug/reproduction tickets

**Comment by ala-yna** [comment] 2021-02-22 21:15
@LinnJS  - Who on VFS has the best understanding of SiP functionality and can help with this?

**Comment by kevinmirc** [comment] 2021-02-22 21:24
Summary of issue and reproduction steps can be found in the QA session results:

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/18969#issuecomment-783529416

> Save in progress:
> - User: 281
> - Expected: No prefill would happen, both addresses are collected in the EZ.
> - Actual: 🚫 users who discard a SiP are seeing the previous version of the form (no checkbox). That was true before this ticket was implemented.

- (Insert Previous QA session results)
> (Insert test of description of bug)

**Comment by LinnJS** [comment] 2021-02-23 17:27
Conversation with platform [here](https://dsva.slack.com/archives/CE4304QPK/p1614100991013800?thread_ts=1614100864.013000&cid=CE4304QPK)

**Comment by LinnJS** [comment] 2021-02-23 22:14
As per the finding in this [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614114990170500?thread_ts=1614098597.098900&cid=CBU0KDSB1) it turns out the feature was sent to prod but not staging and the feature that was merged on 2:23 PM on Friday was not in staging at 1130am on Monday the following week.

**Closed** 2021-02-23 22:15 UTC
Labels: frontend, vsa-caregiver

**Comment by LinnJS** [comment] 2021-02-25 16:11
This is the VSP [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16939) is what came of this issue so it can be resolved for the future
