### ISSUE TITLE
Missing Profile information blocking submission of dependent (686) claims in Staging

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#42110] opened 2022-06-01 15:28 UTC
## Expected behavior
The dependent benefits supplemental workflow, also know as the 686 or 686c allows users to submit claims for dependent benefits on VA.gov. When a user clicks the submit button, the form should be submitted to the VA and the user should see a confirmation message and number indicating success.
An example of a successful submission is available here: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/assets/686_successful%20submission.png)

## Current behavior
Currently, when certain logged-in users attempt to submit a 686c claim in staging at this URL (https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/introduction), they are receiving the following error message, indicating that their profile is missing some required information: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/assets/686_failed%20submission_profile%20error.png

This error is occurring in staging. It was encountered during the course of scheduled testing by the RBPS team, a downstream integration partner who receives and processes VA.gov's 686 form submissions.

This issue is inhibiting (but not totally blocking) the RBPS team's testing.

**Comment by Samara-Strauss** [comment] 2022-06-01 18:01
Actually, in a separate conversation for separate work today, someone mentioned that the file number might be someone's SSN. Someone else would have to confirm that, but if this error is showing for people who need an SSN on file, we **do not** support that in the VA.gov profile. My guess would be that someone would have to call to get that added to their records (MPI, maybe?).

**Comment by ajakabcin** [comment] 2022-11-16 17:49
hey @SKasimow I _think_ this belongs over on the profile side of the house

**Comment by Samara-Strauss** [comment] 2022-11-16 19:08
@ajakabcin I'm not sure this actually has anything to do with the profile since our team has nothing to do with the 686 form, and no information "lives" in the profile -- it all lives on our various backends, which everyone has access to whether they are on the profile team or not.

@mattpointzxer0 is there any update on this or any additional clarity you can provide?

**Comment by evansmith** [comment] 2023-07-10 14:54
@sortizsh @tblackwe Update: After looking into this it sounds like at the moment the VA File Number check passing on staging depends upon whether or not a file number for that veteran has been stored within BGS. This lines up with why in the DEV environment it has been harder to find a user that passes, and I've instead overridden the valid_va_file_number check inside "ValidVAFileNumberSerializer" to true instead of object[:file_nbr] to move along the form. 

From my understanding, after talking to @jerekshoe and @data-doge during this research process, it may be best to close this issue unless users begin to have issues on staging again. Perhaps we could comment within the serializer for DEV users to understand how to quickly bypass this issue locally, but that may be the extent to which this can be fixed at the moment, unless there is another recommended override for staging users.

**Comment by data-doge** [comment] 2023-07-13 23:27
@evansmith As to staging, I wonder if this might actually be something to bring up with BGS? I don't know what their staging environment is like, or to what extent our staging environment interacts with theirs, but maybe they can give us a list of staging users with file numbers. Or, if we needed a particular staging user to have a file number, I wonder if they would be able to add a file number to whatever user record they have on their end. 

As to local, a code comment in the serializer makes sense to me.

**Comment by evansmith** [comment] 2023-07-19 13:58
After reaching out to Cory Easley from the BIS team it sounds like file_nbr's could have been added in the past year to the users that had been tested. At the moment there is no maintained list of users in BGS that have file_nbrs, and generally if a file_nbr is not on a user it means they are not a veteran. 

@sortizsh I think we can close this issue. The DEV environment has more switches to flip than just the serializer depending on the way the app is running locally. I think if this occurs again on staging and the user is confirmed to be a veteran we can reopen it.

**Closed** 2023-07-19 17:33 UTC
Labels: bug, forms, 686, Tree, dependency-bug
