### ISSUE TITLE
[BE] 10-10EZ Short Form: Include submission count in DataDog

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44221] opened 2022-07-12 19:12 UTC
We want to be able to look at DataDog and determine how many total 10-10EZ successful submissions occurred and break it down to how many long forms + how many short forms were submitted.

**Comment by lihanli** [comment] 2022-07-18 15:31
duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/44219

**Closed by lihanli** 2022-07-18 15:31 UTC
Labels: needs-grooming, 1010-team, 1010-ez, 1010-short-form, story
