### ISSUE TITLE
AWS Staging: "undefined" displays at the beginning of the additional details field. 

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#37757] opened 2022-02-25 22:02 UTC
To Reproduce: 
In VAOS, make an appointment request. Examine the confirmation screen.

Expected: The additional information field is displays the information the user entered. 
Actual: The word "undefined: " appears at the beginning of the text. See screen shot. 

The same thing appears on the detail display when accessed from the Request list. 
Note: it works as expected on direct scheduling. 

Tested in SQA with patient Ola C. Edgecombe, chrome browser. ![undefined.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/f401612a-58b5-4379-856f-78379d652d5c)

**Comment by vbahinwillit** [comment] 2022-03-07 17:03
@beth-wodzinski - Hi Beth. What's the idme id for Ola C. Edgecombe? Thanks

**Comment by grossb1** [comment] 2022-03-09 20:47
@vbahinwillit Is this the issue that is related to the reasonCode not being returned?

**Comment by ldelacosta** [comment] 2022-03-10 17:20
@marcynadeau @beth-wodzinski - This is ready to be tested. Please let us know if the issue is still happening. Thanks.

**Comment by aarathi-poldass** [comment] 2022-03-10 21:47
Re-tested the defect and the issue still exists. Please find attached the screenshot from today's testing.  
![37757](https://user-images.githubusercontent.com/69315717/157760118-96ec9f24-954f-4b32-8980-3723411e1c55.PNG)

**Comment by marcynadeau** [comment] 2022-03-10 22:46
@grossb1 @ldelacosta This failed testing by Aarathi. Please see screenshot in previous comment.

**Comment by ldelacosta** [comment] 2022-03-10 22:57
Thanks. Re-assigning this back to @vbahinwillit

**Comment by vbahinwillit** [comment] 2022-03-11 02:41
@grossb1 - Yes, this is the one where the reason code is not being returned.

**Comment by ajmagdub** [comment] 2022-03-17 13:56
added code to the Requested Appointment Details Page to handle cases where the reasonCode -> coding element is not returned by VAOS Service.

**Comment by ldelacosta** [comment] 2022-03-23 13:35
@beth-wodzinski - This is ready for testing. Please let us know if you have any issues. Thanks.

**Comment by beth-wodzinski** [comment] 2022-03-23 14:05
Looks good to me!

**Comment by aarathi-poldass** [comment] 2022-03-23 16:32
Successfully validated and the passed testing, so please close the defect. cc @ldelacosta . Attached is a screenshot for reference.
![Capture](https://user-images.githubusercontent.com/69315717/159749520-55af835f-873a-4aa6-9c2f-610818d0cb95.PNG)

**Comment by ldelacosta** [comment] 2022-03-23 16:34
This has been passed. Closing out the ticket.

**Closed by ldelacosta** 2022-03-23 16:34 UTC
Labels: bug, frontend, vaos
