### ISSUE TITLE
Content updates to static Appointments page -- Community Care content

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9854] opened 2020-06-04 20:20 UTC
**UPDATE: Community Care request feature will now go live July 20.** ~June 25th Community Care appointment request feature will be re-enabled~

We need to bring back the previously removed community care content to the static VA.gov scheduling page. 

Self-schedule (direct schedule) feature _**is not**_ being re-enabled so content relating to this feature **_should not be re-added_**. 

Update content to include CC references on this page: https://www.va.gov/health-care/schedule-view-va-appointments/

**Comment by lenaecb** [comment] 2020-06-08 13:15
@peggygannon - we will be turning on CC again June 25th. We will need to make sure that content on the static VA.gov page is reenabled also for CC requests. 

Cc: @lalexanderson-dsva

**Comment by peggygannon** [comment] 2020-06-18 17:35
This content update is connected to this issue https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8020

**Comment by peggygannon** [comment] 2020-06-28 17:15
@lenaecb I'm going to close this issue as it's a duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8020

Let me know if you have any concerns.

**Comment by lenaecb** [comment] 2020-06-29 14:43
@peggygannon - no concerns, just wanted to make sure that as part of the static updates this gets added to the Community Care content given that it wasn't previously. So if it's easier to just make this a note in #8020 we can.

**Comment by peggygannon** [comment] 2020-06-30 21:03
Yes, @lenaecbYes,  I added this to ticket #8020, so I'm going to close this one.

**Closed by peggygannon** 2020-06-30 21:03 UTC
Labels: content, content-ia-team, vaos
