### ISSUE TITLE
Create confirmed appointment mocks for appointment list page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#1747] opened 2019-09-12 18:18 UTC
We need to create mocks for the different variations of confirmed appointments list and detail pages

The three main variations are VA facility appointments, video appointments, and CC appointments.

Facility appointment data:
- Facility id (just id, no name or anything)
- Clinic name
- Appointment time/length
- Booking note

Video appointment data:
- Facility name, id
- Video link
- Appointment time
- Provider name/contact info
- Various codes and statuses

CC appointment data:
- Provider name, phone, and address
- Veteran instructions
- Appointment time

Notably, we don't appear to have type of care for any of these cases. I'm also not sure if there are any express care differences.

**Comment by markgreenburg** [comment] 2019-10-04 04:34
Kind of rearranged this ticket but kept the info. Dupe of #2247 and #2248

**Closed by markgreenburg** 2019-10-04 04:34 UTC
Labels: design, vaos
