### ISSUE TITLE
[CST] [ENG] Improved 5103 waiver request page

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#84410] opened 2024-06-03 13:23 UTC
## Value Statement
**_As a_** veteran receiving a 5103 Notice first person request in CST
**_I want to_** understand why this request is being made and what actions I can take to improve my claim outcomes
**_So that_** I can make an informed decision about whether to provide additional evidence in support of my claim or submit a 5103 waiver

---
## Background Context

We need a new 5103 waiver submission experience, so we're updating the waiver request page. This ticket covers sections above the waiver submission form on the detail page. 

Current UI for this page 👇

<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--269dd022df1e1bbe9928c43c96d6d3d4a26ab7a8/Screenshot%202024-05-07%20at%203.00.37%E2%80%AFPM.png" alt="Screenshot 2024-05-07 at 3.00.37 PM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- More 5103 waivers submitted through CST
- More 5103 notices downloaded through claim letters section

## Design
- [Figma](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-and-5103-alert?node-id=1694-15979&t=vy5XQCafCsZPcmxO-4)
New Design
![Screenshot 2024-06-03 at 11 54 02 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/58017347-bb79-4d89-bcc8-341c078356f7)

### Enablement team (if needed)
@jstrothman

## Engineering 
Put behind feature flag `cst_5103_update_enabled`

- Assume we'll have to create unique fields for description used on alerts and document request pages for this use case. 
- Assume that we're building future-forward architecture that can be used for other evidence request use cases.

## Out of scope
- 1P alert on Status and Files tab
- Recent Activity update

## Open questions
- What does the 'Download letter link' do?
- Are we supposed to be going off of the V2 or V3 design @skylerschain ?

## Design Tasks
- [ ] Finalize Design

## Engineering Tasks

- [x] - Add new page header 'Review the list of evidence we need' 
- [x] - Add  new page description text
- [x] - Add link `Go to claim letters` that directs users to the Claim Letters Page
- [x] - Add paragraph text

**If you have more Evidence to Submit section:**
- [x] - Add sub-header 'If you have more evidence to submit'
- [x] - Add note text below the sub-header
- [x] - Add link `Upload your evidence here` that directs a user to the Files Tab

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Behind cst_5103_update_ feature flag
- [ ] At the top of the page, there is a header that makes clear we want the claimant to review their evidence
- [ ] Below top header, there's text that explains the VA has sent them a "5103 notice" letter that should make clear what kind of outstanding evidence is requested.
- [ ] There is a link that takes the user directly to the claim letters section of CST.
- [ ] There is informational text assuring the claimant that they don't need to do anything on the page and that the VA will wait until the suspense date of the tracked item.
- [ ] There is a "if you have more evidence to submit section, with a clear header
- [ ] Within "more evidence to submit" section there is informational text explaining that the claimant can submit additional evidence at any time, but what the consequences of doing so might be.
- [ ] Within the "more evidence to submit section" there is a link that takes them to the evidence submission form.
- [ ] Within the "more evidence to submit section" there is informational text explaining the potential value of submitting a 5103 waiver IF they are sure they have no additional evidence to submit.

**Comment by samcoforma** [comment] 2024-06-03 17:27
@jacobworrell is this ticket a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/82575

??

cc: @jerekshoe @pmclaren19

**Comment by samcoforma** [comment] 2024-06-03 17:47
@skylerschain is this a duplicate ticket of https://github.com/department-of-veterans-affairs/va.gov-team/issues/82575 ?

If not, the Figma link is probably incorrect on this.

**Comment by skylerschain** [comment] 2024-06-03 19:48
Updated the Figma link to link to the right mock - it's called "V2" in the Figma file and is focused specifically on the document request page. Doesn't include the addition of the waiver, which is "V3" in the file.

**Comment by pmclaren19** [comment] 2024-06-10 14:56
@skylerschain please review in Staging. You can test on user 23 and go to their 2nd claim; it has a 5103 notice and a submit buddy notice. The feature flag https://staging-api.va.gov/flipper/features/cst_5103_update_enabled has been enabled for everyone in staging. LMK if you have any questions!

**Comment by skylerschain** [comment] 2024-06-10 20:42
Discussed with Peri and LGTM 👍 

Note: The design for this page will be done once [this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82575) is also completed, at which point we should do another Design + Product QA.

**Closed by skylerschain** 2024-06-10 20:42 UTC
Labels: benefits-team-1, benefits-management-tools
