### ISSUE TITLE
DebtRes FSR .pdf of completed form not downloading 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#24402] opened 2021-05-07 20:39 UTC
As a Veteran I want the ability to download completed form 

Issue: Form not downloading 

Def. of Done: Veteran is able to download completed form

**Comment by craigwheeler** [comment] 2021-05-13 13:23
button has been removed from FE to follow up at a later time moving to backlog

**Comment by LinnJS** [comment] 2021-06-01 14:45
This is a backend fix frontend is waiting on this so we can re-enable download PDF button.

**Comment by kevinmirc** [comment] 2021-06-23 14:44
Discovery (so far):
- An error is occurring when in the HTTP req to DMC, to retrieve the PDF.
- The exception propagates to `Common::Exceptions::BaseError` where a type error occurs
```bash
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appender/async.rb:63:in `block in reopen'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appender/async.rb:121:in `process'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appender/async.rb:152:in `process_messages'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appenders.rb:34:in `log'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appenders.rb:34:in `each'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appenders.rb:35:in `block in log'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/appender/file.rb:99:in `log'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/formatters/json.rb:12:in `call'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/formatters/raw.rb:134:in `call'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/formatters/raw.rb:97:in `exception'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/log.rb:163:in `each_exception'
2021-06-23 09:09:25	
13:09:25 web.1       | /usr/local/bundle/gems/semantic_logger-4.8.0/lib/semantic_logger/formatters/raw.rb:101:in `block in exception'
2021-06-23 09:09:25	
13:09:25 web.1       | /srv/vets-api/src/lib/common/exceptions/base_error.rb:19:in `message'
2021-06-23 09:09:25	
13:09:25 web.1       | /srv/vets-api/src/lib/common/exceptions/base_error.rb:19:in `[]'
2021-06-23 09:09:25	
13:09:25 web.1       | 2021-06-23 13:09:25.687626 E [37:SemanticLogger::Appenders] SemanticLogger::Appenders -- Failed to log to appender: SemanticLogger::Appender::File -- Exception: TypeError: no implicit conversion of Symbol into Integer
```
- The type error is caused by `I18n#t` no finding the exception language in [/config/locales/exceptions.en.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/locales/exceptions.en.yml). When `:[:title]` in called on line `lib/common/exceptions/base_error.rb:19` it raises the type error.
- The type error is what gets propagated to the response and logs, so we don't have insights as to what the HTTP error with DMC was.
```json
{"host":"_","application":"vets-api-server","environment":"production","timestamp":"2021-06-23T13:09:25.567975Z","level":"info","level_index":2,"pid":37,"thread":"puma threadpool 007","duration_ms":1238.6490719945868,"duration":"1.239s","named_tags":{"request_id":"_","remote_ip":"_","user_agent":"_","ref":"_"},"name":"V0::FinancialStatusReportsController","message":"Completed #download_pdf","payload":{"controller":"V0::FinancialStatusReportsController","action":"download_pdf","format":"JSON","method":"GET","path":"/v0/financial_status_reports/download_pdf","view_runtime":0.0,"session":"_","user_uuid":"_","exception_object":"no implicit conversion of Symbol into Integer","status":500,"allocations":11295,"status_message":"Internal Server Error"}}
```

**Todo**:
- Resolve the type error occurring so the proper DMC error can propagate to Sentry, logs, and the response body.
- Once we know the actual DMC error, handle it from there.

**Other notes**
- I noticed in Staging there are a setting to mock requests related to FSR. So the PDF failing to be fetched would make sense if the submission never reached there in the first place.
```yml
dmc:
  mock_debts: true
  mock_fsr: true
```

**Comment by kevinmirc** [comment] 2021-06-28 20:19
I'm unable to submit a test FSR because any submission to DMC results in a 401 "Invalid Client".

Working on getting the latest credentials to DMC's lower env (in this case TEST). Once I have the credentials, I'll re configure vets-api and test from there.

**Comment by kevinmirc** [comment] 2021-06-29 14:41
Received the latest credentials for DMC's TEST env. Working updating vets-api config. Once the new config is in place I can send submissions and identify the exact error occurring.

**Comment by kevinmirc** [comment] 2021-06-29 21:22
DMC engineers confirmed that the credentials we had for their test and pre-prod environments were invalid/expired.

Working on getting our credentials updated in AWS parameter store, and will create a devops PR to update references.

**Comment by kevinmirc** [comment] 2021-07-07 18:57
The credstash (parameter store) values have been updated and this is ready for another FSR submission attempt to Pre-Prod in order to identify any additional errors occurring (including whether or not we can auth - this hasn't been tested with the new creds yet).

**Comment by kevinmirc** [comment] 2021-07-14 21:24
From a review instance (using DMC staging credentials) I was able to get a response from DMC using the health check endpoint (`{staging fwd proxy}/api/v1/digital-services/health`.

I will work on manually (from cli) submitting a valid form submission to see what type of response we get.

**Comment by denisecoveyduc** [comment] 2021-11-09 20:10
This was originally slated for Sprint 50 however there was a problem on the DMC side which blocked this issue. We have since resolved that issue and have a new BE Engineer on staff so this issue is now ready to resolve. @ScottyRJames @leahkeeler Let's discuss this tomorrow when we discuss next steps.

**Comment by denisecoveyduc** [comment] 2021-12-02 04:29
For tracking purposes adding a note that this will roll over from Sprint 61 to Sprint 62 because of ssh access in review instances

**Comment by denisecoveyduc** [comment] 2021-12-14 22:51
This will roll over into Sprint 63 due to higher priority MCP fixes.

**Comment by ScottyRJames** [comment] 2021-12-27 21:37
As the financial status report is submitted, the document is successfully up uploaded to filenet but the `filenet_id` is not available through the response object. Without the necessary id the document is not available through Redis and therefore not available to fetch the pdf object. Will followup with DMC to make this attribute available upon submission.

**Comment by denisecoveyduc** [comment] 2022-01-14 00:48
Hey @ScottyRJames did you ever hear back from DMC folks?

**Comment by ScottyRJames** [comment] 2022-01-14 01:13
@denisecoveyduc No I haven't, was planning on following up again with them tomorrow. I'll CC you on the email.

**Comment by ScottyRJames** [comment] 2022-03-07 21:28
Pavan handed over some updated credentials for the DMC preprod environment and was  able to successfully generate a PDF from a review instance using the following command

```
curl --insecure -i \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "client_id: {client_id}" \
-H "client_secret: {client_secret}" \
-X POST \
-d @payload.json \
https://{staging-fwd-proxy-uri}:{port}/api/v1/digital-services/financial-status-report/formtopdf
```

Using the returned filenet id I was able to successfully fetch PDF contents with

```
curl --insecure -i \
-H "Accept: application/pdf" \
-H "client_id: {client_id}" \
-H "client_secret: {client_secret}" \
https://{staging-fwd-proxy-uri}:{port}/api/v1/digital-services/financial-status-report/documentstream?objectId=<filenet id>
```

Next steps are to update credentials in parameter store, remove mocks and test workflow from staging environment.

**Closed** 2022-03-08 22:01 UTC
Labels: bug, backend, blocked, vsa-debt, high priority, planned-work, FSR, benefits-crew
