### ISSUE TITLE
Checkbox outlines disappear on zoom out

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#3739] opened 2019-11-26 18:57 UTC
## What happened?

[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/11187#pullrequestreview-323207017) and [issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19962) suggest that on Safari, checkboxes lose their outline/shadow when zoomed out to 75%:

![image](https://user-images.githubusercontent.com/2008881/69663241-b50e9200-103a-11ea-9a90-3c623981a0c9.png)

## Specs:
- Browser: Safari

## Desired behavior
Checkboxes retain their outline/shadow

## Acceptance Criteria
- [ ] Checkboxes retain their outline/shadow

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by cvalarida** [comment] 2019-11-26 19:09
Looks like this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/771. Closing.

**Closed by cvalarida** 2019-11-26 19:09 UTC
Labels: bug, frontend
