### ISSUE TITLE
[FE] Direct Deposit for Edu: Investigate why errors are not showing up in GA dashboard

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22629] opened 2021-04-05 15:15 UTC
## Background
Following the launch of direct deposit for edu last week (3/31/21) for some reason we're not seeing errors being captured in the GA dashboard.

As of morning of 4/5:
![image](https://user-images.githubusercontent.com/45603961/113589889-ee2c1e80-95ff-11eb-9b63-9d701e98c300.png)
https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/

## Tasks

- [ ] Investigate why this is happening
- [ ] Work with @ajakabcin to create issues to fix as needed if not a simple fix

**Comment by erikphansen** [comment] 2021-04-08 16:10
I've confirmed that we are sending the following data to GA when there is an error making an update to DD4EDU bank info:

```json
{
  "event": "profile-edit-failure",
  "profile-action": "save-failure",
  "profile-section": "edu-direct-deposit-information"
}
```

Compare this to the data that we send GA when there is an error making an update to DD4CNP bank info:

```json
{
  "event": "profile-edit-failure",
  "profile-action": "save-failure",
  "profile-section": "cnp-direct-deposit-information",
  "error-key": "a-type-of-error"
}
```

We are _not_ sending an `'error-key'` when recording DD4EDU update errors. That might be the reason the data is not showing up in [this Google Analytics dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/).

(The reason we are sending `error-key`s with CNP update errors is because we used to see so many errors we needed to track more info about each error to determine what was going on)

Next steps:
- Check with the analytics folks to see if the lack of the `error-key` could result in data missing from the GA dashboard
- And/or potentially pass in an `error-key` with the DD4EDU update errors

**Comment by ajakabcin** [comment] 2021-04-08 17:55
Opened #22941 with the analytics team

**Comment by erikphansen** [comment] 2021-04-08 21:41
[This PR will start passing an `error-key` with DD4EDU update errors](https://github.com/department-of-veterans-affairs/vets-website/pull/16719). That might result in errors showing up in GA. It's also entirely possible there just haven't been any errors yet. There have only been 104 successful updates made. I'd _hope_ the error rate was less than that. Although I guess the chance of someone accidentally entering an invalid routing number, which should result in an error, is fairly high.

**Comment by erikphansen** [comment] 2021-04-13 15:28
My PR was merged late yesterday so it should be on prod later today.

**Closed by erikphansen** 2021-04-13 15:28 UTC
Labels: analytics-insights, bug, direct deposit, frontend, planned-work, vsa-authenticated-exp
