### ISSUE TITLE
Investigate what is causing the variance in Direct Deposit data between GA views

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9605] opened 2020-05-28 17:56 UTC
## Background
On Thursday 5/28/20 we noticed a significant decrease in activity on the Direct Deposit Analytics dashboard for the prior week (~90% decrease). After further investigation of this issue, we realized that it could be related to GA.

[Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1590688328423600?thread_ts=1590683356.407300&cid=C909ZG2BB)

## Tasks
- [ ] Determine what is causing the variance in Direct Deposit data between views in GA

## Acceptance Criteria
- [ ] Issue has been resolved and data is appearing in GA correctly

**Comment by Samara-Strauss** [comment] 2020-05-28 17:59
I've unassigned everyone but Brian from this for now. We can pull in other folks if needed. Looks like we should all be subscribed to the conversation.

**Comment by Samara-Strauss** [comment] 2020-05-28 18:14
Adding additional context for documentation purposes. This is a very abbreviated version of what happened this morning.

We saw a weird drop, about 90%, in direct deposit usage this morning with our normal GA dashboard:

<img width="1280" alt="Screen Shot 2020-05-28 at 9 52 39 AM" src="https://user-images.githubusercontent.com/34068740/83177664-7b077100-a0ed-11ea-99df-7ba34a0c264f.png">
Erik and Lihan could not find any frontend or backend issues that were causing this significant drop. Kimberly had also confirmed that there had not been an increase in issues from the call centers re: direct deposit, so all of this pointed to the feature being fine but potentially there being an issue with GA.

We were able to confirm that DD is indeed working via Howie, who allowed us to investigate via screen share from his production account. On this call, Brian realized that the "view" for GA was set to the "Personalization tools mode" view instead of the "All VA.gov website data" view, and when we made that switch, the data and traffic appeared to be around the levels we'd normally expect. This is what we saw once we switched the view:

<img width="1279" alt="Screen Shot 2020-05-28 at 1 48 52 PM" src="https://user-images.githubusercontent.com/34068740/83177686-88246000-a0ed-11ea-8059-4a73dd52f2e6.png">

**Comment by mshea0606** [comment] 2020-05-28 19:19
slack convo 

https://dsva.slack.com/archives/C909ZG2BB/p1590690790428200

**Comment by bsmartin-ep** [comment] 2020-05-29 11:54
@Samara-Strauss -

I adjusted the filter order in these views yesterday May 28 and am seeing /profile/ page views and _profile-_ events.

[Production - Personalization Tools Modernized View](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p187673796/_u.date00=20200501&_u.date01=20200528&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=profile-)

[Non-Production](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p187683383/_u.date00=20200501&_u.date01=20200528&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=profile-/)

I double-checked the other filtered views and this was the only one with a forwards slash in the filter.

**Comment by bsmartin-ep** [comment] 2020-05-29 13:48
@jonwehausen -

The hot fix for the new Profile event action is ready to be QA'd and published...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000298

**Comment by Samara-Strauss** [comment] 2020-05-29 14:02
@bsmartin-ep thanks for your help with this!

**Comment by bsmartin-ep** [comment] 2020-05-30 18:07
View filters have been updated.  Other views have been reviewed and look OK.  Closing this and writing the post mortem.

**Closed by bsmartin-ep** 2020-05-30 18:07 UTC
Labels: analytics-insights, direct deposit, frontend, profile, vsa-authenticated-exp

**Comment by Samara-Strauss** [comment] 2020-06-01 14:21
Thank you for your help with this!! I really appreciate your attention to this on such short notice.

**Comment by mshea0606** [comment] 2020-06-01 16:20
Thanks @bsmartin-ep for your help with this issue!!
