### ISSUE TITLE
Standardize Analytics/Monitoring/Alerts for all MHV on VA.gov Tools

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58671] opened 2023-05-18 15:16 UTC
- [ ] How do we track users between products and outside of the portal - goal is to have insight into where people are getting lost.
- [ ] How do we know (before anyone else) that there are issues impacting users?
- [ ] How to treat MHV BE services (MHV to have its own monitoring suite and support team) - gently manage relationship with existing MHV team, not pointing fingers
- [ ] What standard tools will we use for monitoring/alerts and analytics (ex. Datadog, Google Analytics, others)?
- [ ] Need insight into how coordinators and contact centers see MHV National Portal statuses so we can try to replicate that process

**Comment by A6-toma** [comment] 2023-05-19 16:49
Need discovery on what's needed and how to make it happen

**Comment by A6-toma** [comment] 2023-05-31 16:18
Per @batemapf, closing as a duplicate of 58755

**Closed by A6-toma** 2023-05-31 16:18 UTC
Labels: my-health, my-health-CTO-HEALTH-TEAM, my-health-INTEGRATION
