### ISSUE TITLE
Explore Visual Testing Implementations and Product Offerings

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17293] opened 2020-12-10 17:15 UTC

**Comment by JoeTice** [comment] 2021-02-09 15:41
Closed as a duplicate of [157](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/157)

**Closed** 2021-02-09 15:40 UTC
Labels: QA, VSP-testing-team, testing
