### ISSUE TITLE
MDT- Review order page - edit contact details, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5273] opened 2020-01-29 17:08 UTC
## User story:
As a veteran, I need to be able
## Tasks:
-Create high fidelity mockup(s) showing how a Veteran might update their  address and contact details
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [ ] Mockup aligns with VA.gov’s design system
- [ ] Include a way for Veterans to edit their mailing and email addresses
- [ ] Include a way for Veterans to save or cancel their edits
- [ ] Initial focus point documented in Invision
- [ ] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by leahkeeler** [comment] 2020-02-19 23:46
this is duplicate of 5273

**Closed** 2020-02-19 23:46 UTC
Labels: design, vsa, vsa-benefits-2
