### ISSUE TITLE
Analytics Implementation or QA Support for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15757] opened 2020-11-03 22:20 UTC
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

    - Jason Wolf (@jason (Slack) & @jason-gcio (GH))
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - eBenefits Team, VRE CH31 feature
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Launching December 2020

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - Landing/entrance pages: https://staging.va.gov/careers-employment/vocational-rehabilitation/
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/eligibility
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/how-to-apply
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services
      - https://staging.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living
    - Intro (with wizard) page: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction
    - Veteran Info Review: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/veteran-information-review
    - Veteran Contact Info: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/veteran-contact-information
    - Additional Information: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/additional-information
    - Communication Preferences: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/communication-preferences
    - Review and Submit: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/review-and-submit

    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Review application has some accordion expansions but I don't think those need to be checked
    - There is some explanation text around what living on a military base means for the purposes of filling out the form (on claimant address for example) but that might already be tracked in the Form System

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Auth not needed

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Auth not needed

- Certain conditions/responses that need to be reviewed

    - None

- Additional Comments

    - Another piece of static content is being added between the wizard and the form but that will be forthcoming at a later date.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2020-11-04 19:35
Thanks @jason-gcio ! Confirming receipt

**Comment by bsmartin-ep** [comment] 2020-11-25 14:59
@jason-gcio -

1.  We look pretty good on pageviews.  Here's [everything we are recording on the non-prod GA](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p176884211/_u.date00=20200901&_u.date01=20201124&explorer-table.filter=staging.va.gov~2Fcareers-employment~2Fvocational-rehabilitation&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25) right now.

2. For good measure, here are [all the events on these pages on non-prod](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20200901&_u.date01=20201124&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22BW%22,%22staging.va.gov~2Fcareers-employment~2Fvocational-rehabilitation%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=50/).  A fair amount of script errors, but a few useful things in there.

3.   How do I trigger this text?

> There is some explanation text around what living on a military base means for the purposes of filling out the form (on claimant address for example) but that might already be tracked in the Form System

4. FYI - if I click _Yes_ then _No_, I am unable to progress when I click the continue button.  It looks like it tries to validate the (hidden) address change form.  (https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/additional-information)

![image](https://user-images.githubusercontent.com/62304138/100190250-d7402780-2ebb-11eb-90da-d6879fb67551.png)

5.  Any other interactions you would want to track?  Form controls?  Other components? I see a slight issue with the form system event prefix, which I'll ask Jon below :arrow_down_small: .
------

@jonwehausen -

These form events need a product prefix, correct?  Would this be `bam-`?

![image](https://user-images.githubusercontent.com/62304138/100190514-677e6c80-2ebc-11eb-988d-ab3140864614.png)

**Comment by jonwehausen** [comment] 2020-11-25 19:46
Thanks @bsmartin-ep , handing this ticket off to you here. 

A couple next steps: 
- Provide for Jason and his team the standard form system events and [wizard](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md)events...with the tracking prefix of `careers-employment`: make appropriate GTM update in {{Form - Action}}
- Take a read thru their product documentation for KPIs

**Comment by bsmartin-ep** [comment] 2020-11-25 20:15
@jason-gcio -

------
For reference:

**Tracking Form Events**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md

**Tracking How To Wizards**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md

-----

Please prefix all form events with: `careers-employment`

-----

Do you have any KPI documentation I should review for this product?

Thanks!

**Comment by bsmartin-ep** [comment] 2020-11-25 20:19
GTM workspace for new `careers-employment` product prefix:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000396

**Comment by jonwehausen** [comment] 2020-12-02 16:27
@cohnjesse To loop you in here, we will want the Wizard specification implemented here as well. 

Shifting back to VFS standby for now.

**Comment by joanneesteban** [comment] 2020-12-07 16:45
Reassigning to @bmcgrady-ep .

**Comment by joanneesteban** [comment] 2020-12-16 17:23
@jason-gcio Please let us know when you have work ready for us to review on our side here!

**Comment by jonwehausen** [comment] 2020-12-21 19:49
@cohnjesse Could I have you adjust the product prefix here to be `careers-employment` as well as for chapter 36? Thanks in advance

**Comment by jason-gcio** [comment] 2020-12-21 20:39
@cohnjesse and @micahchiang are out this week but I will make a note to be sure we look at this next week.  We don't anticipate CH36 getting any traffic until next week

**Comment by jonwehausen** [comment] 2020-12-30 22:57
## QA Testing of How To Wizard Data Layer 

### Context
- Testing was executed according to our latest [how to wizard data layer specification](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md) 

| Description / Screenshot of Interaction | Data Layer | GTM Screenshot | Test Status
| -- | -- | -- | -- |
Skip the form and go to start application page | ![image](https://user-images.githubusercontent.com/48527022/103384995-904ede80-4ac6-11eb-8a7c-572bfa212342.png) | ![image](https://user-images.githubusercontent.com/48527022/103385005-9ba20a00-4ac6-11eb-816b-a9123cc50b17.png) | ✔️ **PASS**
Click on radio button toggle | ![image](https://user-images.githubusercontent.com/48527022/103384735-7bbe1680-4ac5-11eb-8742-921a47776129.png) | ![image](https://user-images.githubusercontent.com/48527022/103384762-8ed0e680-4ac5-11eb-957d-5ce8af62580e.png) | ✔️ **PASS**
Alert displayed following radio button toggle | ![image](https://user-images.githubusercontent.com/48527022/103384783-aa3bf180-4ac5-11eb-8045-804e421eb262.png) | ![image](https://user-images.githubusercontent.com/48527022/103384798-ba53d100-4ac5-11eb-81af-a8ec13d848d0.png) | ✔️ **PASS**
Click on link inside of alert | ![image](https://user-images.githubusercontent.com/48527022/103384833-e1120780-4ac5-11eb-8db0-2bbeaaf75fc6.png) | ![image](https://user-images.githubusercontent.com/48527022/103384849-ee2ef680-4ac5-11eb-9ac2-51dd6f070809.png) | ✔️ **PASS**
CTA Displays to start form | N/A - No data layer | N/A - No data layer push | ⚠️ **DOES NOT PASS** - <br><br> _understand the video may be impacting some things here, we will still want this event to fire_ <br><br>![image](https://user-images.githubusercontent.com/48527022/103385111-15d28e80-4ac7-11eb-9228-675fc7020549.png). <br><br>**when the cta is embedded within a gray alert box, we can first push the `'event': 'howToWizard-alert-displayed', 'reason-for-alert': '<description>'` event followed by the `'howToWizard-cta-displayed'` event**
Click on CTA to begin form | N/A - No data layer | N/A - No data layer push | ⚠️ **DOES NOT PASS** - <br><br> _understand the video may be impacting some things here, we will still want this event to fire_ <br><br>![image](https://user-images.githubusercontent.com/48527022/103385090-04898200-4ac7-11eb-9a5a-247cdb846b66.png)
Click on go back and answer questions again ![image](https://user-images.githubusercontent.com/48527022/103357294-d4b78b80-4a80-11eb-86b3-1e5c68ebd319.png) | ![image](https://user-images.githubusercontent.com/48527022/103357336-e9941f00-4a80-11eb-862b-776e77c2d153.png) | ![image](https://user-images.githubusercontent.com/48527022/103385154-3ac70180-4ac7-11eb-922f-118f8e0bcfd0.png) | ✔️ **PASS**


@cohnjesse If you could make these remaining data layer adjustments, I will begin to take a look at the implementation needs for the video tracking. I am leaning towards our team handling the actual video tracking components entirely within GTM to include stops, starts, skips, etc, while also needing to have data layer events for our standard button tracking put in. I will update this ticket with those pieces in a separate note.

**Comment by jonwehausen** [comment] 2020-12-30 23:31
### Bug for Correction

@cohnjesse looks like the last question radio button is populating with the wrong question text...check out the attached video: 

https://user-images.githubusercontent.com/48527022/103386519-2dad1100-4acd-11eb-9c41-be0d0924192c.mp4

**Comment by cohnjesse** [comment] 2020-12-31 18:53
@jonwehausen good find! Just updated this in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15509)

**Comment by jonwehausen** [comment] 2020-12-31 19:29
## Data Layer Specification for Video Feature

### Script to Add to support built-in GTM YouTube video tracking
- @cohnjesse if we could add the below script to the FE instead of needing to load thru GTM that would be great, this will enable us to track video starts, stops, skips, progress, complete etcs levereaging GTM's built-in YouTube data layer without any additional changes on your part
```javascript
<script src="https://www.youtube.com/iframe_api">
```

#### Video Tracking - Progress Bar Change
- Fire the following event and metadata which each change from one video to the next as the progress bar changes
```javascript
'event': 'nav-progress-bar-change', //consistent event name for progress bar change
'progress-bar-type': 'segmented', //dynamic with type of progress bar, in this case 'segmented'
'progress-bar-value-current': //dynamically populate with an integer with each new change the current, 
'progress-bar-value-total': //consistently populate as an integer with the total number of segments, i.e 5,
'progress-bar-title': //dynamically populate as a string according to the bold title next to number, i.e 'Re-Employment',
'progress-bar-subtitle': //subtitle of video, i.e 'Veteran Readiness and Employment orientation',
'enable-analytics': true //consistently populate with boolean true
```

**Comment by jonwehausen** [comment] 2020-12-31 19:50
@cohnjesse As a reminder, when implementing the above events, we can also correct the items from [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15757#issuecomment-752782990). Thanks so much in advance!

**Comment by jonwehausen** [comment] 2021-01-13 13:26
@cohnjesse Could we connect on the remaining updates here? Thanks in advance

**Comment by jonwehausen** [comment] 2021-02-10 21:36
@cohnjesse just a reminder this is ready for implementation on the video how to wizard thanks in advance

**Comment by jonwehausen** [comment] 2021-02-10 21:40
@meganhkelley Do you think we could have someone from your team implement the YouTube iframe to assist our tracking here? We would need this rendered on page load prior to DOM ready. Thanks for your assistance here. 

```<script src="https://www.youtube.com/iframe_api">```

**Comment by meganhkelley** [comment] 2021-02-11 23:01
hey @jonwehausen ! possibly, but is there a reason that the eBenefits team wouldn't complete this work (or draft a PR for VSP to review)? cc @jason-gcio

**Comment by jonwehausen** [comment] 2021-02-17 00:33
Hi @meganhkelley , 

I had asked Jesse their developer if he would be able to add that src, and he then asked me if I could ask VSP FE, so was spinning my wheels for a bit on who should take that portion. 

Thanks for your assistance here.

**Comment by meganhkelley** [comment] 2021-02-17 14:10
Hey @cohnjesse ! Could you help me understand why the analytics implementation for this should be taken on by VSP FE instead of eBenefits? (Not necessarily disagreeing, just looking for additional context so that I can help my team prioritize this work). cc @timwright12

**Comment by joanneesteban** [comment] 2021-02-17 19:15
@RachaelMR @drorva @f1337 - Should Front End Tools implement this script in such as a way that any VFS team can leverage video tracking capabilities moving forward? Or should the eBenefits team implement the script specifically on the pages for which they want video tracking?

**Some background:**

The work is adding the above script to Page Load. This would allow us to leverage the GTM tracking on this particular page.

This is the URL it would be added to: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction

The need is currently just for this URL, but as this gets expanded throughout VA.gov, we'll need this added to the other pages that will need to be added to other pages on VA.gov, which could increase load time.

**Comment by drorva** [comment] 2021-02-22 16:53
My inclination is to have it start as a script for eBenefits and when we have 3 or more apps using it, make it a general purpose script.

**Comment by jonwehausen** [comment] 2021-02-23 15:31
Thanks here team! We have confirmed [this page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction) is the only case of YouTube tracking within the wizard(s) to-date. 

After further discovery this AM, it looks as though the UX for the YouTube video embed has changed since we last visited [this page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction) and has **created a further technical block.** 

## Description of Block
- The iframe `src` attribute is currently updated with the new embed YT page path when each new video is loaded
- However, the Google Tag Manager YouTube listener does not recognize the change in video due to current state iframe recycling.
- Subsequently, the listener and datalayer needed for tracking, does not fire for any videos after the 1st video

## Proposed Solution
- We would like to propose the FE program a removal of the `data-gtm-yt-inspected-XXXXXXX_XXX` attribute when the user clicks to navigate to the next video
![image](https://user-images.githubusercontent.com/48527022/108866526-482dd300-75c2-11eb-961e-daead3b3b1c8.png)

- This would then cause GTM to re-inject the attribute with each new video change

Please let us know if you have any further questions and who may be responsible for this work. Thank you in advance

cc: @RachaelMR @bsmartin-ep @joanneesteban @drorva

**Comment by jonwehausen** [comment] 2021-02-23 15:37
Also tagging VFS devs here for awareness: @micahchiang @cohnjesse

**Comment by jonwehausen** [comment] 2021-02-24 15:12
Spoke with @micahchiang [here](https://dsva.slack.com/archives/CLY6Q69RV/p1614023548002700) --> We will be taking the approach of removing the injection attribute with each new video navigation. 

@bsmartin-ep Would you be able to work with Micah on testing this locally when ready?

**Comment by cohnjesse** [comment] 2021-02-25 20:59
@meganhkelley @drorva @joanneesteban Sorry for the late reply, my thinking with wanting VSP to implement the youtube iFrame api script is two fold - 1. If we implement this as a team just on our page there is no way for us to do it without modifying the template that is used for React pages, this would be a template inside the platform and therefore should involve the platform team. 2. This is a script that will be used by other teams going forward and although the idea of "let's put it on one page until we need it on more" sounds like a good idea at first once teams start putting this in individual pages there is no simple way for VSP to monitor how many pages it is put on without doing an audit which will take more time and resources later on. If it is going to be the pattern used going forward it probably makes sense to get out in front of it and implement it on a platform level now.

**Comment by bsmartin-ep** [comment] 2021-02-26 18:20
Update:  @cohnjesse found a solution:

https://github.com/department-of-veterans-affairs/vets-website/pull/16203

> "...if we destroyed the video's iFrame instead of just rerendering it then Google Tag Manager registered it as a new video loading and now tracks submiquent videos as expected."

**Comment by bsmartin-ep** [comment] 2021-03-01 18:40
@jonwehausen / @bmcgrady-ep -

I made some changes to Jon's GTM workspace for video tracking so one of you should probably QA:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000433

Staging should be testable:
https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction

**Comment by bsmartin-ep** [comment] 2021-03-02 17:06
### QA

Interaction|dataLayer|tag
----|----|-----
First video played|![image](https://user-images.githubusercontent.com/62304138/109685346-2b0f7c00-7b4f-11eb-9b3c-6abe02077c09.png)|![image](https://user-images.githubusercontent.com/62304138/109685401-38c50180-7b4f-11eb-87d8-511b089985f5.png)
First video paused|![image](https://user-images.githubusercontent.com/62304138/109685460-48444a80-7b4f-11eb-83c7-2989958279c7.png)|![image](https://user-images.githubusercontent.com/62304138/109685511-52fedf80-7b4f-11eb-8dc4-d7d6b6fc0514.png)
Second video played|![image](https://user-images.githubusercontent.com/62304138/109685674-7a55ac80-7b4f-11eb-9358-dd8f947d0ba6.png)|![image](https://user-images.githubusercontent.com/62304138/109685713-86416e80-7b4f-11eb-8076-a869e703a39f.png)
Second video paused|![image](https://user-images.githubusercontent.com/62304138/109685747-93f6f400-7b4f-11eb-8772-2480b9b1a1a5.png)|![image](https://user-images.githubusercontent.com/62304138/109685860-ac670e80-7b4f-11eb-8515-c030d462267f.png)

LGTM.  Publishing.

**Comment by jonwehausen** [comment] 2021-03-12 20:20
Hi @cohnjesse , 

Prior to closing this out, would you mind adjusting the data layer on submission, submission failed, and submission successful to have 2 dashes prior to `submission` and one dash before `failed` or `successful`. See below example with 3 dashes prior to submission

![image](https://user-images.githubusercontent.com/48527022/110994088-42681980-8346-11eb-8b0c-b3f6d3380bca.png)


Each full event name should look like: 
- `careers-employment-28-1900--submission`
- `careers-employment-28-1900--submission-failed`
- `careers-employment-28-1900--submission-successful`

For your awareness, the same thing remains on [this ticket](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/helpers.jsx#L148) for final closure. 

We can close these guys out once we get these final updates made. 

Thanks so much in advance

**Comment by jonwehausen** [comment] 2021-03-30 20:57
Hi @jason-gcio , 

When you have a moment, I wanted to connect with you as we've had #13167 and #15757 opened for a bit for the same DL tweak needed. 

This should be a small change to the tracking prefix to ensure our `submission` events have a double dash (`--`) before `submission` rather than triple dash (`---`) as they mistakenly do now. This doesn't/hasn't inhibited any data collection, but it would be great to get that cleaned from a consistency standpoint. 

From there we can close both of these out for good. 

Thanks so much for your time here.

**Comment by jason-gcio** [comment] 2021-03-30 21:08
Hey @jonwehausen - so sorry about this, it totally fell off my radar.  I will bring these up with the team and see when we can get these straightened out.

**Comment by jason-gcio** [comment] 2021-03-30 21:30
@jonwehausen - we chatted real quick and it seems like we just need to remove a hyphen from these...can we confirm its that simple?

**Comment by jonwehausen** [comment] 2021-03-30 21:40
Hi @jason-gcio , 

It's no problem -- Thank you for your response here. Yes this should be just that simple.

**Comment by jonwehausen** [comment] 2021-04-14 19:05
Hi @jason-gcio , 

Could you provide an update on this work? Thanks so much

**Comment by jonwehausen** [comment] 2021-04-28 15:10
### QA Retest

| Description of Interaction | Data Layer | Test Status
| -- | -- | -- ||
_Submission_ of 28-1900_ | ![image](https://user-images.githubusercontent.com/48527022/116427679-3a8b0880-a812-11eb-9caf-7a2ccd04b9a1.png) | ✔️ **PASS**
_Failed submission_ of 28-1900 | ![image](https://user-images.githubusercontent.com/48527022/116427795-57bfd700-a812-11eb-8505-28e992b6e3a7.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment] 2021-04-28 15:11
Thanks so much for correcting this @cohnjesse, closing these issues

**Closed by jonwehausen** 2021-04-28 15:11 UTC
Labels: analytics-insights, analytics-request, gtm
