### ISSUE TITLE
[Reps][Initial Info] User interviews - Notetaking

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#72476] opened 2023-12-21 16:55 UTC
This is a placeholder ticket for everyone notetaking as part of the user interviews activity. The person assigned to this ticket is responsible for ensuring that all notetakers complete the sub-tasks associated with this ticket and that documentation is properly stored. 

### Output
**Before the study kicks off**
- [x] Create [note taking template](https://docs.google.com/document/d/12HpWVV_RPsPzZxqk3qFYCO_HiD4r-Dh5txTv0-uBHqU/edit#heading=h.j4tpfeq57mmt), save to study Google Folder
- [x] Make a copy of template and put in Template folder [See here](https://docs.google.com/document/d/19E1vKRVXT-DwqwuBl43I0PzYgwoAwGoyfQ5-CPrc4mU/edit#heading=h.ghh4lutlyrpj)
- [x] Create debrief document (Mural or Google doc) [Link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706548305852/cc0c080b86ef97bf8c6f252b676dbef807ce9013?sender=ucd326fb05b27d09e40350092)

**Before an interview**
- [x] Ensure notetaker has been identified for the session
- [x] Ensure the notetaker has made a clean copy of the note taking template and has updated the header information

**After an interview**
- [x] Confirm the notetaker has cleaned up their notes and uploaded it to the appropriate Sharepoint folder
- [x] Add notes to session within EnjoyHQ
- [x] Ensure debrief notes are captured (in a Mural, in a separate notes doc)

**End of study**
- [x] Confirmed all notes from the study are in the Sharepoint folder
- [x] Confirmed all notes are saved to the study within EnjoyHQ
- [x] Confirmed debrief documentation

### Resources
- [Research plan](https://docs.google.com/document/d/1xU70WIiN2CIiddpxkp1sV56H5J0gF9W4BVHbPkrq4_E/edit?usp=drive_link)
- [Conversation guide](https://docs.google.com/document/d/14xLcuD5Pq67qmnpiY8_r7t7x00bprE2xSviJUOreY5U/edit?usp=drive_link)
- [Note taking template](https://docs.google.com/document/d/1d4I9OqWO1MHy4ZMeULPXdzWnZ0JtgxI6ENKM3IDHu1o/edit?usp=drive_link)
- [Sharepoint folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/User%20Interviews?csf=1&web=1&e=Kc8Qow)
- [Enjoy HQ project file](https://app.enjoyhq.com/sh/pj/5e87c81f-1c56-496e-8181-6892b06fc9ea)

### Acceptance criteria
- Notes for all interview and debrief sessions are cleaned up and stored in the appropriate Sharepoint folder and EnjoyHQ

**Comment by RivkaCGates** [comment] 2024-01-03 18:20
@RenataKeck is this a dupe of 72476? If not can you explain the difference to me?

**Comment by RenataKeck** [comment] 2024-01-03 18:25
@RivkaCGates this is 72476, and I don't see a duplicate elsewhere on the board. I will check again to be sure, but there should only be 1 note taking issue for each open research study (user interviews and 21-22 testing).

**Comment by RivkaCGates** [comment] 2024-01-03 18:41
@RenataKeck sorry - 72475 https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72475

**Comment by RivkaCGates** [comment] 2024-01-03 21:01
@RenataKeck I'd appreciate that. I was confused on several of these tickets. Could we name the studies and maybe put the short name of the study on each ticket?

**Comment by karafaithsanchez** [comment] 2024-01-26 19:23
@RivkaCGates FYI we are pulling this ticket into this sprint. Going to do the first task on the list today, so the notetaking doc can be ready for the Pilot session on Monday.

**Comment by RenataKeck** [comment] 2024-02-06 16:16
@karafaithsanchez I added a link to the EnjoyHQ project file in the resources section of the issue.

**Comment by karafaithsanchez** [comment] 2024-02-20 16:59
Everything has been completed except for documenting in EnjoyHQ which @RenataKeck is going to take care of. Moving to Review.

**Closed** 2024-02-21 18:09 UTC
Labels: accredited-rep-facing, arf-des
