### ISSUE TITLE
[User flows and navigating] A user flow doesn’t have valid or appropriate closure, and results in a dead end where the user can't complete a task due to a functional issue (i.e. blank page, missing field or CTA, 404 error). (03.01.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52086] opened 2023-01-17 16:16 UTC
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
Enrollment verification

#### Point of Contact/Reviewers
Sara Sterkenburg - @sterkenburgsara - IA
Cheryl Evans - @CherylEvans - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
A user flow doesn’t have valid or appropriate closure, and results in a dead end where the user can't complete a task due to a functional issue (i.e. blank page, missing field or CTA, 404 error). 

**UPDATE:** This issue was discussed at staging, and the team verified the business logic is working as intended. Thus, the introductory content (text beneath H1) needs to be updated (not the form flow) to more accurately describe the intended user experience.

### Issue Details
The first page of the form describes "if you don't verify your enrollment for two months in a row, we will pause your monthly education payments." This should mean that any single month, in any order, could have an error. That one month alone would not cause payments to stop. There is an error in this logic in the following scenario: When user 301 selects "no" (enrollment details are not up to date) for November 2022, the form immediately bypasses December and doesn’t allow the user to indicate whether that month is correct (even if it is). This is a dead end - the user has no way to indicate that December is correct. The logic assumes any months following the first one in chronological order will also have "no" answers. 

### Link, screenshot or steps to recreate
Steps to reproduce:
1. See screenshot here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50480_Sara_030101.png 
2. Login as test user 301 
3. Select "no" for November and press "Continue" (The form will automatically bypass December) 
4. Blue box appears with explanatory text: "We skipped you ahead to the review step because you selected "No, this information isn't correct" for November 2022”

**UPDATE:** See these screenshots regarding intro text that needs updating (see [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50480_Sara_030101B.png) & [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50480_Sara_030101C.png))

### VA.gov Experience Standard
[Category Number 03, Issue Number 01](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
It could be possible that December is correct even if the prior month is incorrect. For instance, imagine the number of credit hours is wrong for one month, but not the other. Please fix this form logic to allow users to verify each month individually. If only one month is incorrect, the student should be able to receive payments.

**UPDATE:** Please work with Sitewide Content and IA team to work on verbiage that best describes the intended experience to users. Screenshot of the language in question is attached (see [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50480_Sara_030101B.png) & [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50480_Sara_030101C.png))

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by shiragoodman** [comment] 2023-01-17 16:48
Per Staging Review discussion, the content needs to be changed and the flow is correct.

**Comment by btruongafs** [comment] 2023-01-27 22:16
@TamGIBill confirmed and the business flow works as intended. Closing out.

**Comment by bethpottsVADEPO** [comment] 2023-01-30 17:56
@btruongafs and @TamGIBill I do think this needs clarification. I will post here today some plain language text for you to use. Please pause on implementing the above text until I have a chance to check in with @sterkenburgsara. Thanks!

**Comment by sterkenburgsara** [comment] 2023-01-30 21:56
@bethpottsVADEPO included updates to ticket above and added two screenshots to capture the introductory language (text under the H1) that needs some massaging to more accurately describe the user experience. Thanks! // cc @katherine-fung @btruongafs @TamGIBill @CherylEvans

**Comment by katherine-fung** [comment] 2023-01-30 22:51
Hi @btruongafs, 

Which of these is correct? 

"If it's been 2 months since you verified your enrollment, we'll pause your monthly education payments." 

OR 

"If it's been more than 2 months since you verified your enrollment, we'll pause your monthly education payments." 

Can you please tweak the intro to the enrollment verification tool page and replace the last sentence ("If you don't verify your enrollment for two months in a row, we will pause your monthly education payments."), with whichever sentence is correct above? Making that change should resolve this ticket. Thank you!

**Comment by btruongafs** [comment] 2023-01-31 05:07
@TamGIBill can you weigh in on which statement is correct?

**Comment by TamGIBill** [comment] 2023-01-31 14:24
@btruongafs 

This one:

"If it's been more than 2 months since you verified your enrollment, we'll pause your monthly education payments."

**Comment by btruongafs** [comment] 2023-02-06 22:34
Content changes have been implemented and deployed to staging. Closing out.

**Closed by btruongafs** 2023-02-06 22:34 UTC
Labels: content, design, ia, collab-cycle-feedback, Staging, CC-Dashboard, my-education-benefits, enrollment-verification, CCIssue03.01
