### ISSUE TITLE
[Components and pattern standards] Design components and patterns in use are outdated.  (04.08.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#72155] opened 2023-12-18 19:35 UTC
#### VFS team name
Veteran Facing Forms

#### VFS product name
20-10206

#### VFS feature name
FOIA / PA request

#### Point of Contact/Reviewers
Allison Christman - @allison0034 - Design

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Design components and patterns in use are outdated. 

### Issue Details
On the landing page there are 2 alerts. One is the v3 component and the other is styled as the v1 but not using the actual component.

### Link, screenshot or steps to recreate
![Screenshot of multiple alert styles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/65886-Allison-040801.png?raw=true)

### VA.gov Experience Standard
[Category Number 04, Issue Number 08](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Use the v3 component for the sign in alert to stay consistent with syling.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by tlei123** [comment] 2023-12-21 02:40
@jeana-adhoc @rachelshearerux , I've opened a Draft-PR and need some guidance re. the saved-form SIP-alerts \[last 2 rows of Screenshots &mdash; see [main description](https://github.com/department-of-veterans-affairs/vets-website/pull/27243#issue-2051573837)\]...

For those saved-form alerts, the previous versions didn't have left-borders or icons.  Our v3-web-component `<va-alert/>`, however, only has a `background-only` property to hide the left-border.  No property exists to hide the icon.

Let me know how to proceed.  Thanks much!

**Comment by allison0034** [comment] 2023-12-21 13:10
@tlei123 I was not aware our [v3 alerts](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--slim) had a no left border option. Can you share where you found this so I can make sure the design system is up to date?

**Comment by tlei123** [comment] 2023-12-21 17:49
> I was not aware our [v3 alerts](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--slim) had a no left border option. Can you share where you found this so I can make sure the design system is up to date?

@allison0034 , there actually is a left-border option, but it's called `background-only` \[hides left-border\] \[see [Alert USWDS Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default)\]: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/587583/4c5af14f-565f-4d02-9a41-7750469a67ae)

**Comment by tlei123** [comment] 2023-12-22 00:35
Per [this Slack thread](https://adhoc.slack.com/archives/C0433UTLHJA/p1703126980336009), we're keeping left-borders and icons in all USWDS alerts.  The saved-form alerts will be different on all Introduction pages.

**Comment by tlei123** [comment] 2023-12-22 01:02
@tbaker1026 , just to minimize regression risks, before I take our PR out of Draft-mode and request review & approval...

I'm thinking it might be prudent wait 'til January, then announce our v3-web-component alerts to all the form-app teams in DSVA Slack, and maybe wait a week for any team to react/refactor/fix.

What do you think?  Should we open it up for general discussion in a stand-up?

cc @nds

**Comment by tbaker1026** [comment] 2023-12-22 16:11
@jeana-adhoc @tlei123 yes we should probably wait - Jeana?

**Comment by jeana-adhoc** [comment] 2023-12-22 23:11
I think that makes sense - we can alert folks about alerts and [modals](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/856#issuecomment-1868050172) that also need to be updated to v3.

**Comment by tlei123** [comment] 2024-01-03 16:19
Planning to merge [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27243) end of next week (1/12)...

Announcements posted on Slack channels [#veteran-facing-forms](https://dsva.slack.com/archives/C044AGZFG2W/p1704297614954529) & [#vfs-change-announcements](https://dsva.slack.com/archives/C03R5SBELQM/p1704297322502879) to give VFS teams 'til Thu next week (1/11) to test and report any issues.

**Comment by tlei123** [comment] 2024-01-12 18:30
@tbaker1026 @jeana-adhoc @rachelshearerux [tagging you now just in case my power goes out again], [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27243) merged &mdash changes should be in Staging by ~4:45 PM ET.

cc @ndsprinkle

**Comment by jeana-adhoc** [comment] 2024-01-19 13:25
This form is now using the v3 version of the sign in alert. (Screenshot is different here as since the original post, we've made this form LOA3 only)

<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3f4c79855947af837b5a9f3881c52d61df8d1ae/image.png" alt="image.png" />

**Closed by jeana-adhoc** 2024-01-19 13:25 UTC
Labels: design, collab-cycle-feedback, Staging, CCIssue04.08, CC-Dashboard, forms-audit-digitize, 20-10206
