### ISSUE TITLE
[FE] Buggy Spokes on Education Page - Create a Post 9/11 GI Bill CTA widget

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6754] opened 2020-03-11 12:27 UTC
##Problem Statement
Clicking on Get Benefits on the Post 9/11 Statement of Benefits page reveals an empty accordion. The Manage and More spokes are showing only one or a couple child items each, and should actually be showing the content in the images below.
![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/b7d67525-b344-4223-8ecb-c2e551aff5e3)
![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/f7f2d543-335b-42d5-9792-f6c9d8caa41f)

Refer to the bug for additional information: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5396

## Acceptance Criteria
- [ ] _ Create a Post 9/11 GI Bill CTA widget
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment] 2020-03-11 13:56
After looking deeper at the code for this app, the CTA widget should actually be good to go already. Once we've started setting this page up in Drupal, we should already be able to create the CTA widget as a content model.

**Comment by AkucherGCIO** [comment] 2020-03-12 15:49
03/12/20 PW Standup
This effort has been accomplished already.

**Comment by AkucherGCIO** [comment] 2020-03-13 15:51
03/13/20 PW Standup
Nick is looking into the effort and needs to think through how it's implemented.

**Comment by MickinSahni** [comment] 2020-03-16 14:07
> After looking deeper at the code for this app, the CTA widget should actually be good to go already. Once we've started setting this page up in Drupal, we should already be able to create the CTA widget as a content model.

Hey @ncksllvn, is there any work required as part of this ticket, then? Can it be closed?

**Comment by ncksllvn** [comment] 2020-03-16 14:18
I think we can close this in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/6753, because after some thought, I think we're combining the CTA widget with the status-check widget, rather than simply separating out the widgets from the main React code

**Comment by MickinSahni** [comment] 2020-03-16 15:45
2020-03-16 PW Standup
* We can close this out as a Dupe assuming we update #6753 to reflect there that we're combining these two widgets into one cc @MickinSahni

**Comment by MickinSahni** [comment] 2020-03-17 20:56
Closing as dupe of #6753. Removing from sprint/estimate

**Closed by MickinSahni** 2020-03-17 20:56 UTC
Labels: frontend, vsa-public-websites
