### ISSUE TITLE
[BE] 10-10EZ - Facility Selection: Launch Facilities API functionality into Prod

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#75189] opened 2024-02-02 13:44 UTC
## Background
The static list used today is very outdated and causing issues for Veterans who are completing the 10-10EZ form.
We have connected to the Facilities API in lower level environments with success, and need to implement this functionality in Production.  This will allow a dynamic list of facilities to populate a dropdown menu, which will always be a current list and remove the manual maintenance from the 10-10 team.

Validations for EZ are handled through vets-json-schema. The validation checks the preferred facility against an enum (list) of facilities in the schema. Lighthouse supplies more facilities than we have in the enum, so any selected facility from lighthouse, that is not in the schema, will trigger a validation failure.

This is an interim fix of the static list issue.  We have plans to redesign the facilities selection page to include a more dynamic search functionality, also built for the 10-10cg form.

## Tasks

- [x] Update vets-api to override the expected schema value for preferredFacility if the facility API flag is checked

## Acceptance Criteria
- Facility selection page on the 10-10EZ will use the current Facilities API to display the facilities within the state selected by the Veteran.

**Comment by longmd** [comment] 2024-02-02 16:40
@hdjustice / @jadon1979 , here are some thoughts I have for a better, and much less risky, approach versus what we had discussed previously.

1. Copy the current schema with the enum values into the form config file for the JSON list. This takes the schema file out of play and we can run with this temporarily. 
2. Once this is merged in an we can regression test to ensure proper function, then we make the modifications to the `vets-json-schema` to remove the enum and just have it be a string value.
3. Leave all conditional logic in place and roll out with the feature flag. The feature will work since we still have the hardcoded enum values in the JSON config page. 
4. Once we roll out to 100%, remove the conditional logic and pull the feature flag from `vets-website` and `vets-api`

**Comment by jadon1979** [comment] 2024-02-02 20:19
https://github.com/department-of-veterans-affairs/vets-api/pull/15377

**Comment by jadon1979** [comment] 2024-02-02 21:33
@fbonds this should fix the issue you were having when testing Facilities.

**Comment by hdjustice** [comment] 2024-02-05 14:27
Tested a few submissions this morning. Pending resp from Josh F for confirmation of successful or failure.

**Closed** 2024-02-05 15:13 UTC
Labels: backend, 1010-team, 1010-ez, ez-facilities
