### ISSUE TITLE
Letters empty state UI 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#27587] opened 2021-07-20 14:19 UTC
# User Story
As a user, if the VA app can't find letters for me, I want to see a screen that says that and is clearly designed.

# Background 
This error message got long over time and is a lot of text center-aligned on a screen -- it feels hard to read. To be consistent with Claims and SM, change the UI to match those. Other than changing the copy, everything else is the same as the claims empty state, font, padding etc.

# Screenshot reference of the build now
![IMG_0057.PNG](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9fc8b726-85f6-409a-b752-61cf462cfefa)

# Screenshot of what we want to change it to
![Empty state.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/dc4f5455-c919-411f-b9c4-1827adf40a37)

# Acceptance Criteria
- [ ] Change copy to: 
We couldn’t find any letters for you.
We’re sorry, we can’t find any letters for you. If you think this is an error, please call the VA benefits hotline
- [ ] Change alignment to left aligned
- [ ] Keep the same hotline info as before (this should match Claims)
- [ ] Match padding to claims and Messages empty state UI

**Comment by ashley-matthews** [comment] 2021-07-20 19:57
@melissa-lefevre I'm closing this ticket because it is a duplicate of https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/27382

**Closed** 2021-07-20 19:57 UTC
Labels: frontend, va-mobile-app
