### ISSUE TITLE
Provide a mechanism for unit testing liquid templates

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19328] opened 2021-02-01 17:07 UTC
Currently, the only tool we have for testing our liquid templates is Cypress. The Cypress tests are slow, and since we don’t control the CMS data used to generate our HTML pages, we can’t easily test different scenarios.

We need a way to unit test our templates by providing JSON data fixtures as input, generating the HTML, and running assertions against the output. We could use something lightweight like Kent C. Dodd’s [DOM Testing Library](https://testing-library.com/docs/dom-testing-library/intro/) to run our assertions. This would be much faster than Cypress, and it would give us much better test coverage, since we would control the JSON data. This could take the place of tests like [this one](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/tests/vamc/location_home.cypress.spec.js) - or at least we could move all of the non-interactive bits into the template unit tests.

**Comment by JoeTice** [comment] 2021-02-09 15:36
Closed as duplicate of [19291](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19291)

**Closed** 2021-02-09 15:35 UTC
Labels: VSP-testing-team
