### ISSUE TITLE
IA request from Sitewide homepage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#48789] opened 2022-10-26 17:37 UTC
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
We plan to soft launch the redesigned homepage by publishing it to production in parallel with the existing homepage and allowing users to try it out as an "opt in". We need guidance on the appropriate URL for the redesigned page. The current implementation (for usability testing) is https://staging.va.gov/homepage-test/ (which isn't ideal for the live page in Production). 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
  - [x] Other - plan is for a soft launch allowing users to opt-in to use redesigned homepage
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
 approximately 1 month after initial release, pending analytics and feedback ~ early January 2023

Please provide an estimated date so our team can create other relevant tickets.*
  
## Other details 
the following per conversation with @mnorthuis and @davidconlon on 10/26
- the new page should not be indexed
- the new page should not be in the sitemap xml
- the new page should use the existing homepage URL as the canonical URL
- the new page will continue to live in prod post-cutover so that it can be used for the soft launch of future iterations (modal announcement will come down until needed)
- users will be able to return to existing homepage from redesigned page via back button, home breadcrumb, and VA logo

Pending
- Decision regarding tasks for robots file 

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: late November/early December
- Estimated staging review date:
- Content and IA work needed by: ~mid November

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Sitewide homepage
- OCTO-DE product owner: Dave Conlon
- Product manager: Michelle Middaugh
- Designer: Ryan Thurlwell
- FE engineer: Public Websites
- Product/team Slack channel: #sitewide-homepage-refresh

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment] 2022-11-02 18:00
@heyjoni per our discussion this morning...

**Comment by heyjoni** [comment] 2022-11-02 21:49
Recommendation: "va.gov/new-home-page"

"New" signals that it's a redesign, but still keeping "home page" in the URL signals that only the home page has changed and not the entire site. Please let me know your thoughts.

**Comment by jilladams** [comment] 2022-11-15 18:45
@heyjoni @mnorthuis Checking since ticket is still open - are we good to proceed with  "va.gov/new-home-page" and close this out? Or it needs some further consideration?  (cc @mmiddaugh @wesrowe )

**Comment by heyjoni** [comment] 2022-11-15 21:13
If the recommendation works for @mmiddaugh and @wesrowe, we can proceed.

**Comment by jilladams** [comment] 2022-11-15 21:22
Yep - we've confirmed in a meeting today that this path'll work if it's good by y'all. Thanks! Closing.

**Closed by jilladams** 2022-11-15 21:22 UTC
Labels: sitewide content, sitewide content-product support, Sitewide IA, VA.gov homepage
