### ISSUE TITLE
Review Update form button seeing issues

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#34408] opened 2021-12-21 15:46 UTC
Check on all forms “Update form” button – specifically Feedback Tool and 1990– Cinda is seeing the same problem as discovered on the 10203 (STEM) form Review screen.

**Comment by ERRonat0609** [comment] 2021-12-22 18:14
@rtwell This is related to Github ticket [#12185](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12185) where updates are being made to the form before the user clicks the "update" button. In that ticket, it was thought to be a platform issue but no final determination has been received. Now we are seeing similar issues on other forms. Please look into this and let us know if this is something that Platform needs to address.

**Comment by mrblanco1** [comment] 2022-01-02 20:34
Hi QA! Can you please do some testing around this issue and let us know what your findings are? We received feedback from EDU that the Update form button does not work across Feedback Tool and form 1990. EDU thinks this issue is happening all across.
"Check on all forms “Update form” button – specifically Feedback Tool and 1990– Cinda is seeing the same problem as discovered on the 10203 (STEM) form Review screen."
Thanks!

**Comment by jfinnern** [comment] 2022-01-06 15:10
QA has been unable to find issues as referenced in #12185 in either Feedback Tool or 1990 in regards to the Update button. Specific info on how to reproduce behavior that indicates a bug will be needed.

**Comment by hallihocine** [comment] 2022-01-19 17:16
- After doing some testing and investigation on the Feedback tool, 1990 and 10203 forms, we find out that the issue reside in auto saving changes without clicking on the "Update page" button. 
Once your are in the "Review application" step, if you expand any of the accordions and click the "Edit" button to update the data, it will auto-save the new data (the changes) without clicking the "Update page" button. The way how it should work is to save the change only after clicking the "Update page" button.

- As a solution to this problem, we can:
1. (Most Likely): Keep the "Update page" button and remove the auto-save mechanism, this way all the changes will saved only after clicking the "Update page" button. 
2. (Least Likely): Remove the "Update page" and keep the auto-save mechanism, this way all the changes will be auto-saved when editing.

**Comment by mrblanco1** [comment] 2022-01-19 17:55
Abe to demo this to Cinda/EDU tomorrow 1/20/2022.

**Comment by GnatalieH** [comment] 2022-01-20 23:11
@hallihocine can we on the Design System Team get a demo of this issue? Looping in @bkjohnson and @k80bowman because this feels like a bug. CC @andresriveratoro and @pdavies88.

**Comment by mrblanco1** [comment] 2022-01-21 19:54
Hello @GnatalieH  @bkjohnson and @k80bowman @andresriveratoro and @pdavies88 

Just to note AFS Comparison Tool submitted ticket github.com/department-of-veterans-affairs/va.gov-team/issues/35723

We expect to hear more from the design team sometime next week. Thanks!

**Comment by mrblanco1** [comment] 2022-01-21 19:55
Moved this ticket to Backlog until we hear back from OCTO/Platform with a recommendation. Abe B.

**Comment by mrblanco1** [comment] 2022-01-28 19:06
Latest from Platform:

Ticket #: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35723

Summary of the issue at hand:

On forms with Save in Progress enabled, Save in Progress works through the full form even the review-and-submit page
Due to Save in Progress working on the review-and-submit page when a user clicks the Accordion and Edit button when they make changes to a field those changes are saved without any indication to let the user know
Additionally a User is receiving conflicting feedback on how to make changes and save their information because we also have an Update Page button on those forms that will also save changes
If a User makes changes and wasn't intending on having those changes saved there is no way for user to undo their changes as Save In Progress would have already made the updates

**Comment by mrblanco1** [comment] 2022-02-08 14:54
Per OCTO's design team we are closing this ticket and track this issue on #35723. 
I would agree we probably don't need 2 tickets for the same issue we could probably just track it moving forward via this one and make sure the other ticket is notated that this ticket will be the one worked on to resolve whatever decision the Design System Council makes in the future about this situation

**Closed by mrblanco1** 2022-02-08 14:54 UTC
Labels: afs-education, afs-edu-form
