### ISSUE TITLE
Replace AskVAApi AMS serializers with JSONAPI serializers

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#84405] opened 2024-06-03 12:21 UTC
## Summary 

Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/ask_va_api`. 

## Epic 

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83609

## Tasks

- [ ] Replace serializer (1x)

## Acceptance Criteria

- [ ] Each serializer uses jsonapi-serializer 
- [ ] Each serializer has 100% coverage

**Comment by ericboehs** [comment] 2024-06-11 15:22
Closing as a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/83609

**Comment by stevenjcumming** [comment] 2024-06-12 13:11
Reopened because this is for a specific module, the title of the ticket is misleading

**Closed** 2024-06-24 14:43 UTC
Labels: platform-reliability-team
