### ISSUE TITLE
Discovery: Get local submit working

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#80399] opened 2024-04-09 23:52 UTC
## Overview
Submitting a claim is not working in our local dev environments, failing at multiple points 
- Investigate root causes for blocking failures
- Document fixes, workarounds
-- Create troubleshooting guide such as: "If you see this message, do this" 
- Discover and fix any bugs preventing submission

## Acceptance Criteria
- [ ] Submit a 526 claim from local vets-website to local vets-api
- [ ] Document findings and the fix
- [ ] Create a ticket to fix if it does not get completed within the time-box ticket

**Comment by christinec-fftc** [comment] 2024-04-10 16:49
[Patch](https://drive.google.com/file/d/1sdsJWuDKaNmcrW5WmSazFlW1UDl0ELWq/view?usp=drive_link) containing debugging changes

**Comment by christinec-fftc** [comment] 2024-04-26 16:12
Here's one example of a failure. As a front end engineer, it would be difficult to work on say a story for the confirmation page if we can't get a successful response back. But also, if we're adding FE changes to the form, ideally it would give us confidence in our work if we could do a successful submission locally to verify new form pages or fields do not cause a breakage to the flow.

It would be great to have documentation in a troubleshooting guide on how to fix these types of errors.
<img width="1550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed674162108840a26e4a99fbdcfef7aa016ece24/image.png" alt="image.png" />

**Comment by tblackwe** [comment] 2024-05-01 15:14
Is this because of the switch from dev data to mock data? 
Can we use dev authentication? do we need to build additional mock backend services?

Is this something Platform should assist with?

**Comment by tblackwe** [comment] 2024-05-01 15:15
From FE perspective: We want to get to confirmation page so we can validate the full Veteran experience from Create to Submit.

**Comment by freeheeling** [comment] 2024-05-02 17:43
The error response I receive, when attempting to submit a claim locally, is different than what Christine reported. When posting to `v0/disability_compensation_form/submit_all_claim`, a 500 status response os returned with the exception "uninitialized constant Sidekiq::Batch", from "app/models/form526_submission.rb:199:in `start_evss_submission_job'". This is different form the 404 status response in Christine's example, when attempting to get `v0/disability_compensation_form/submission_status/<job_id>`. My attempt at replicating the issue did not generate a job id with which to make a subsequent call to query the submission status.

I don't believe there is any issue with the BE receiving the posted claim to the `submit_all_claim` endpoint. The submission appears to be created from the saved claim submission. In my case, the job to submit the claim asynchronously to EVSS isn't able to be initiated because of the "uninitialized constant Sidekiq::Batch" exception. Whereas, in Christine's example, it appears that a job ID was assigned, but when the subsequent call to get submission_status was made, there was no record of a job status with that ID.

<img width="1816" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEt3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f031b66f48dc3261d0be0a5fbbb815fd23d09ceb/Screenshot%202024-05-02%20at%2011.31.19%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.31.19 AM.png" />

**Comment by SloopKoning** [comment] 2024-05-06 22:01
I also was getting the 500 error as was Scott.  We tracked this down to the root cause - our local environments did not have the proper creds to install and run `sidekiq-ent` (Sidekiq Enterprise.)  The proper system environment variable was export with the correct creds, `bundle install` added the `sidekiq-ent` system.  Now instead of getting the 500 error we are seeing a 404 error.

There is a configuration item for sidekiq enterprise that controlls the length of time that a sigekiq job's status is kept in redis.  Its possible - but not likely that this config item in the local development environment is too short.  I've forgotten where that config item is set.  I will look it up.

**Comment by freeheeling** [comment] 2024-05-07 15:44
After successfully submitting to `v0/disability_compensation_form/submit_all_claim` and receiving the corresponding job ID, the request to `v0/disability_compensation_form/submission_status/<job_id>` returns a 404. This occurs in staging as well, but appears to be successful on the second call to the same endpoint.

**Comment by SamStuckey** [comment] 2024-05-09 16:22
BLOCKED: In team of teams @aurora-a-k-a-lightning proposed using the new lighthouse flipper / sandbox to work around this issue.  That would allow us to avoid the error that @freeheeling and @SloopKoning identified

**Comment by sortizsh** [comment] 2024-06-06 15:18
@christinec-fftc  we're closing this, if you need further collab let us know.

**Closed by sortizsh** 2024-06-06 15:18 UTC
Labels: frontend, backend, disability-experience, DBEX-Carbs

**Comment by christinec-fftc** [comment] 2024-11-07 22:22
Paired with Aurora and Seth to fix my local (had annoying db issues), but we also came up with some small code changes that can help mock up a response for the submission_status api [Mock_up_submission_status_responses.patch](https://github.com/user-attachments/files/17670130/Mock_up_submission_status_responses.patch)
