### ISSUE TITLE
 [BUG] Find a VA Form: "Related to" information missing on some results

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19561] opened 2021-02-05 18:13 UTC
## What happened?
As reported by Jen Lee in [this thread](https://dsva.slack.com/archives/CUB5X5MGF/p1612547714059100), the "Related to" information is missing for some forms. 

"I’m seeing a minor bug on the forms search results listing: Missing Related to field on some forms. I wanted to see if this is already captured before submitting a bug ticket.
I suspect the Find a VA form FE or LH API is not pulling from the right CMS data. (The Related to field logic on the form detail landing page goes like this: 1/ Pull from the custom selected Related to meta data field; 2/If blank (none selected), pull from the  Administration VA form source db field.)
Ex:
https://www.va.gov/find-forms/?q=disability"
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/dec89d8f-60b1-45a0-820e-b5373a343c18)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:  https://www.va.gov/find-forms/?q=disability
- Test User _(if applicable)_: N/A

## Desired behavior
Every result should return "related to" information

## Acceptance Criteria
Every result displays "related to" information.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment] 2021-02-08 14:24
@MarciMcGuireGCIO per a Slack thread with Jen -- this issue appears to be rooted in FE logic that @zacharymorel will need to look at (he may want to get help from PW team since they implemented it).   Here is the thread:  _The FE logic is supposed to pull from a) Related to field, and if empty, THEN pull from b) Administration field.
^ This allows all forms in search results listings and the form detail page to always show some value for the Related to field, even if it is one of these lower traffic forms that we don’t manually select a custom Related to field value form._

**Comment by zacharymorel** [comment] 2021-02-08 14:46
Good morning! After looking in to this morning, it appears we need the lighthouse team to pass the **fieldVaFormAdministration** equivalent field to the front end. The FE is not receiving that property within the network response.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-08 18:19
Blocked until we receive the required data that needs to be added by Lighthouse team.

**Comment by NCHLiberty** [comment] 2021-02-10 21:28
Team Matsumoto (Lighthouse Forms API team) has created this jira issue corresponding to this github issue https://vajira.max.gov/browse/API-5082

**Comment by MarciMcGuireGCIO** [comment] 2021-02-16 21:08
@NCHLiberty - when your team gest to this issue, please let us know if we can assist in any way.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-24 19:03
Hi @NCHLiberty - doing my end-of-sprint check on open issues.  Any updates on this one?  Thanks!

**Comment by NCHLiberty** [comment] 2021-02-24 19:25
this ticket is prioritized into the sprint that is about to start tomorrow.

**Comment by mviterna** [comment] 2021-02-25 17:13
@zacharymorel  I'm not 100% sure, since I'm not a front end guy, but I think it is fieldHomePageHubLabel? Rather than fieldVaFormAdministration. I checked in Drupal a form where there was a related to and where there wasn't one. I spot checked a few of the forms and it seems the data isn't in Drupal. I'm going to slack you a copy queries to try. fieldVaFormAdministration is identical on both forms, so I don't think that is the right field, but I could be wrong.

(same on both 21-8764a and 29-357)
         "fieldVaFormAdministration": {
            "targetId": 1
          },

(29-357 has fieldHomePageHubLabel populated, 21-8764a fieldBenefitCategories is null)
          "fieldBenefitCategories": [
            {
              "targetId": 77,
              "entity": {
                "entityLabel": "VA life insurance",
                "fieldHomePageHubLabel": "Life insurance"
              }
            }
          ],

**Comment by zacharymorel** [comment] 2021-02-25 18:35
@mviterna You're on the right path I believe. As far as the FE template consumes on the details page, we consume the **fieldBenefitCategories.entity.fieldHomePageHubLabel** first if present. If it's not present, we consume **fieldVaFormAdministration.entity.entityLabel**. 

I.e.: http://localhost:3001/find-forms/about-form-21p-534ez/ you can see the **related to:** text. 

As far as the search results goes from the picture above, we map over the **benefitCategories** array y'all send back and pick show each **name**.

**Comment by mviterna** [comment] 2021-02-25 22:04
@zacharymorel So the bug is for the search result page right? So that is the benefitCategories  array? If so, are you also seeing form 21-8764a null for that in Drupal?

**Comment by mviterna** [comment] 2021-02-25 22:22
@zacharymorel I'm pretty new to Forms API, but here is how I think the workflow works. benefitCategories is populated from a table in a MariaDB Drupal implementation (which is populated by a MSSQL db somewhere?). My team's API grabs the data off that your forms Drupal table via a graphql query (which includes benefitCategories) every night at 2AM. The front end search page on va.gov find-a-form calls my team's Forms API and we send back what we have in our Postgres DB (which is populated from that 2AM job) for a jsonb column. So if you populate that array in your CMS system my team should be able to grab and it reflect it on the va.gov website. I can only access drupal via the https://prod.cms.va.gov/graphql/explorer GUI. So I don't know what the actual table looks like or what data it has. However, if that GUI is correct and benefitCategories is null. It won't show up on va.gov and the Related To field will be missing for that particular form. Does this sound accurate?

**Comment by zacharymorel** [comment] 2021-02-26 14:40
> @zacharymorel I'm pretty new to Forms API, but here is how I think the workflow works. benefitCategories is populated from a table in a MariaDB Drupal implementation (which is populated by a MSSQL db somewhere?). My team's API grabs the data off that forms Drupal table via a graphql query (which includes benefitCategories as a jsonb column) every night at 2AM. The front end search page on va.gov find-a-form calls my team's Forms API and we send back what we have in our Postgres DB (which is populated from that 2AM job). So if you populate that array in your CMS system my team should be able to grab and it reflect it on the va.gov website. I can only access drupal via the https://prod.cms.va.gov/graphql/explorer GUI. So I don't know what the actual table looks like or what data it has. However, if that GUI is correct and benefitCategories is null. It won't show up on va.gov and the Related To field will be missing for that particular form. Does this sound accurate?

Yes, @mviterna this is accurate description of the process.

**Comment by zacharymorel** [comment] 2021-02-26 14:48
@mviterna Looks like we'd need to add a column for **fieldVaFormAdministration** property on the VA Form node to our forms api db. Then the FE search results can mirror the behavior the form details page has. 
The Form Details Page shows that field value if the **fieldBenefitCategories** has a length of 0.

**Comment by mviterna** [comment] 2021-02-26 15:02
@zacharymorel Can you provide a query for 21-8764a that shows fieldVaFormAdministration.entityLabel ? I only see a targetid for that form, nothing about a label

**Comment by zacharymorel** [comment] 2021-02-26 15:04
> @zacharymorel Can you provide a query for 21-8764a that shows fieldVaFormAdministration.entityLabel ? I only see a targetid for that form, nothing about a label

I can try. Querying using Graphql has been tricky here.

**Comment by mviterna** [comment] 2021-02-26 15:06
@zacharymorel use the one I sent you in slack as a template. You can see where all I get back on fieldVaFormAdministration is target id. 

"fieldVaFormAdministration": {
"targetId": 1
},

**Comment by zacharymorel** [comment] 2021-02-26 16:12
@mviterna I have an updated query for you: 

`{
  nodeQuery(limit: 1000, offset: 0, filter: {conditions: [{field: "field_va_form_number", value: "21p-8768", operator: LIKE}]}) {
    entities {
      entityId
      entityBundle
      ... on NodeVaForm {
        changed
        fieldVaFormName
        fieldVaFormTitle
        fieldVaFormType
        fieldVaFormUrl {
          uri
          title
          options
        }
        fieldVaFormUsage {
          value
          format
          processed
        }
        fieldVaFormNumber
        fieldVaFormAdministration {
          targetId
          entity {
            entityLabel
          }
        }
        fieldVaFormToolIntro
        fieldVaFormToolUrl {
          uri
          title
          options
        }
        fieldBenefitCategories {
          targetId
          entity {
            ... on NodeLandingPage {
              fieldHomePageHubLabel
            }
          }
        }
        fieldVaFormRevisionDate {
          value
          date
        }
        fieldVaFormIssueDate {
          value
          date
        }
        fieldVaFormNumPages
        fieldVaFormRelatedForms {
          targetId
          entity {
            ... on NodeVaForm {
              fieldVaFormNumber
              fieldVaFormName
              fieldVaFormUsage {
                value
                format
                processed
              }
              fieldVaFormUrl {
                uri
              }
            }
          }
        }
        fieldVaFormLinkTeasers {
          entity {
            entityLabel
            parentFieldName
          }
        }
      }
    }
  }
}`

**Comment by mviterna** [comment] 2021-02-26 16:53
@zacharymorel So, going back to the original form (21-8764a), when I run your new query, fieldBenefitCategories is still null, so what you are proposing is that it fall back to "Veterans Benefits Administration" in the related to? Why wouldn't we just set that form's fieldBenefitCategories to "Disability" like 21-526EZ has?

I only ask, because I'm a veteran and I have used the VA website for person reasons and I think that is confusing. I think "related to disability" makes more sense than "related to VBA"....why don't we talk about this during our 3pm today

**Comment by zacharymorel** [comment] 2021-02-26 17:47
> @zacharymorel So, going back to the original form (21-8764a), when I run your new query, fieldBenefitCategories is still null, so what you are proposing is that it fall back to "Veterans Benefits Administration" in the related to? Why wouldn't we just set that form's fieldBenefitCategories to "Disability" like 21-526EZ has?
> 
> I only ask, because I'm a veteran and I have used the VA website for personal reasons and I think that is confusing. I think "related to disability" makes more sense than "related to VBA"....why don't we talk about this during our 3pm today

I don't know the exact reason why we fall back to the Administration Field. Something built, decided from the original crew who built this. 

@ncksllvn Do you have any context to that decision?

**Comment by ncksllvn** [comment] 2021-02-26 19:37
>So, going back to the original form (21-8764a), when I run your new query, fieldBenefitCategories is still null, so what you are proposing is that it fall back to "Veterans Benefits Administration" in the related to? Why wouldn't we just set that form's fieldBenefitCategories to "Disability" like 21-526EZ has?

@mviterna I think your question was already answered earlier in this thread, https://github.com/department-of-veterans-affairs/va.gov-team/issues/19561#issuecomment-775185065. What I am gathering is that by showing the administration we can at least tell the user _something_ about the form's relationship or owner if we have not been able to apply a benefit hub ourselves (this is a task performed by our team) or if none apply. Our product owner can provide you with more insight if you need it (although I am not really sure if this ticket is the right place to bring into question the business logic. Ultimately I think our team is just asking the `fieldVaFormAdministration.entity.entityLabel` value be made available for our app.)

The example query provided by @zacharymorel looks fine to me. Are you still having problems with getting this to work? 

```
fieldVaFormAdministration {
          targetId
          entity {
            entityLabel
          }
        }
```

**Comment by jenniferlee-dsva** [comment] 2021-02-26 19:45
@mviterna 

Answering the question:
>why we use the Administration for the Related To field when the Benefit Categories is empty

I have answered this elsewhere and on Slack. Re-replying here. 

1/ `Related to` info is to help provide information scent - some benefits or services or process is 'owned' by a particular administration. This corresponds to how each form has a prefix number like 10- or 20-, 21-, etc. 

2/ We use this field to provide better, more specific info scent - like `Disability`, `Pension`, whatever - for **high-value forms.** We define high-value forms as those that have a) an online web tool version and/or b) a lot of users look for it and use it. (Prior to 1.0 launch, we actually looked at the Google Analytics data of each form.) 

So, for high-value forms, we manually select the related benefit info with more helpful granular data - "Health care," "Education," whatever -- these are rigid data selects, not freeform.  

3/ When a form isn't a high-value form, it still automatically gets published in the search and as a detail page. In these situations, we still want to provide some info scent, even if it's not as helpful as "Disability" or what have you. 

But we can't manually look at all the non-high value forms before they go out in search and as a page. This is a modernized product - it's not manual and bespoke; at least we've tried to automate as much as possible to scale. That's why when the benefit data for this field is unspecified, we want to the FE to show -- by default -- the Administration data. 

4/ Even some high value forms sometimes use the Administration value at the request of the business owner. (For a variety of reasons, but a common one is that a form is used for something that isn't specifically for a benefit OR it is used for many different purposes.)

**Comment by mviterna** [comment] 2021-03-01 19:59
@jenniferlee-dsva  @ncksllvn @zacharymorel  Thanks for the background. Just wanting to make sure I understood the issue. I've created Jira item https://vajira.max.gov/browse/API-5481 and put it in the backlog. @NCHLiberty and @MarciMcGuireGCIO can prioritize accordingly. I don't think we can fit it in the current sprint (ends Tuesday) but I'm sure we can get it in afterward some time.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-02 14:02
@mviterna thank you.  @NCHLiberty pinged me yesterday afternoon, and I asked that this issue be a higher priority than https://github.com/department-of-veterans-affairs/va.gov-team/issues/17484 since this issue is omitting data that needs to be visible.

**Comment by mviterna** [comment] 2021-03-03 20:13
@MarciMcGuireGCIO  Yup, we are getting it added now. Should be visible in a day or two after I get it checked in

**Comment by zacharymorel** [comment] 2021-03-03 20:21
Awesome! Once we have the data returned on the FE xhr request, I can add the logic on the FE to account for the new field.

**Comment by mviterna** [comment] 2021-03-04 14:46
@zacharymorel  Do you want the JSON returned similar to how we are doing benefits categories?

Currently returned for benefits categories
[{"name": "Pension", "description": "VA pension benefits"}]

Proposed for va_form_administration:
{"entity": {"entityLabel": "Veterans Benefits Administration"}, "targetId": 1}

**Comment by zacharymorel** [comment] 2021-03-04 14:49
> @zacharymorel Do you want the JSON returned similar to how we are doing benefits categories?
> 
> Currently returned for benefits categories
> [{"name": "Pension", "description": "VA pension benefits"}]
> 
> Proposed for va_form_administration:
> {"entity": {"entityLabel": "Veterans Benefits Administration"}, "targetId": 1}

Yes, I would appreciate that!

**Comment by mviterna** [comment] 2021-03-04 14:52
@zacharymorel  Ok sir, I'll finish my testing and get it checked in. It will take a day or two for the DB changes to propagate in the build process. I'll let you know when it goes live

**Comment by mviterna** [comment] 2021-03-09 16:20
@zacharymorel  You can see the new field if you go into /services/va_forms/v0/forms?query=21-674 on staging.

I'm wondering though, if you really want the whole 
  "va_form_administration": {
                    "entity": {
                        "entity_label": "Veterans Benefits Administration"
                    },
                    "target_id": 1
                }
            }

Or if you want me to scrub it a little and show up more like this:

  "va_form_administration": "Veterans Benefits Administration"

either is fine with me

**Comment by zacharymorel** [comment] 2021-03-09 16:44
Yes, I am unsure if there's a case for more than just one administrative form, but scrubbing it down to an array of strings is perfect. If we don't need to worry on the that case, you can do it like above.

**Comment by mviterna** [comment] 2021-03-09 16:49
ok, will do

**Comment by mviterna** [comment] 2021-03-10 22:15
@zacharymorel @MarciMcGuireGCIO @johnhashva  The updates are ready to go out. We can coordinate a time that works for you. I would propose Tuesday morning at 10:30 AM ET. If all testing passes on Staging, the production release will go out at 2PM ET that same day.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-11 14:34
@mviterna we responded on GitHub, but also updating here.  This sounds good.  Please keep us posted so we can review as soon as it hits Production. Thank you!

**Comment by mviterna** [comment] 2021-03-18 17:35
@MarciMcGuireGCIO @zacharymorel We confirmed the new API field is in prod. Let me know if you need anything else from the API team

**Comment by MarciMcGuireGCIO** [comment] 2021-03-18 17:38
Thank you, @mviterna !

**Closed** 2021-03-18 17:39 UTC
Labels: Lighthouse, bug, dt-find-va-form, unplanned-work, vsa-decision-tools
