### ISSUE TITLE
Access for Cesar Santiago

### ISSUE THREAD

**Issue by cesaresantiago** [department-of-veterans-affairs/va.gov-team#26642] opened 2021-06-25 18:16 UTC
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Laura Ross
- Please provide your name.
   > Cesar Santiago
- Please Provide your email.
   > cesar.santiago@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   My Education Benefits Team. Company: Accenture Federal Services
   
   Note: I have an existing ssh entry, but seems I have my passphrase wrong, so need to re add.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzvGICIPjD9J5WTAkBhu2K0SA+fLtVUTDnR0FZjX/eOVOuWAhkqztYfKA3EQObE/ZdiwHkQ7RM+SzpFC5zkUvZyjjzMI6jzyj4qvRGDfvewF81yljR6qB7mGZUPpjf3aqH/hZpgoQBjaZ19Ec3T2L2oxGpY+LYc54NpJPYJDgqLpFr9TrzjqJ0N7g717H2LmnDSc98ci66gBKvKsTIilofmWa4p/4Q6LaeNZBJ7MNvSWjLeuf8H+WfuKhzGJSzDhTabIsLViDf3Z2nB9drlS0lpBEueXBBiurRAnmaFl6QyEPC5RQD68hTwEmgZ8vWWtA/webPUt+1aOC6K5K0g+gimTdGSfIDj3FhJoq1VvkSmlxkrUnHutWve/9oXeU7UpHzKPbTOVMs/GOF2PXOkaPdfdkVjcgDBIetnGqq22BzMdI+nFx5Kz3nRdIXTeK/lBn3w68aEfvfMNwyE8g21MszS0gWhnNAgZwLiskpK7OCwULkdmtIwqgfxc4YV0yhpDE= cesar.santiago@AFSMWSZH33VJBBW
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by mydesignrocks** [comment] 2021-06-28 04:52
hello @cesaresantiago - is this a duplicate of this?
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25926
or are you looking for a new key to be replaced with the previous one?

**Comment by cesaresantiago** [comment] 2021-06-28 11:46
Hi:

I want the existing key to be replaced with this new one.

Thanks

Cesar

**Comment by cesaresantiago** [comment] 2021-06-29 13:17
Hi @mydesignrocks :

Do you need more information about this? Please let me know if you need more to get this done.

Thanks

**Comment by mydesignrocks** [comment] 2021-06-29 13:31
My apologies for the delay, @cesaresantiago - getting to it now.

**Comment by mydesignrocks** [comment] 2021-06-29 14:25
this is complete now @cesaresantiago 
hope this works out for you.

**Closed by mydesignrocks** 2021-06-29 14:25 UTC
Labels: access-request, afs-dgib, external-request, operations
