### ISSUE TITLE
HLR Static Content Page and Tool (REACT)

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4139] opened 2019-12-11 17:43 UTC
## Status
[2024-04-24] Comment to R Hecht asking about viability of this old ticket.

## User Story or Problem Statement
Higher-Level Review static landing page needs to be updated to support launch of Higher-Level Review form

link to WIP invision mockup

https://vsateams.invisionapp.com/share/5RUP8V2TSHD#/screens

## Acceptance Criteria
- [x] Add green CTA button to take users to the HLR form
- [ ] Add left nav to page (to be approved by @mnorthuis) **[EDIT: @Karak888 pls break out left nav work as a separate ticket per call, to be worked on after Kevin S's user research learnings; also note in that ticket that the nav would need to be added to ALL decision review pages, not just this one. / jen]**
- [x] Additional content updates to address that only pension and compensation claims can file for HLR online (all other claims still need to be filed via mail, fax, in person)
- [ ] Heroku preview shared with SMEs and changes factually validated and approved (iterate if needed)
- [x] Reviewed by Peggy Gannon in Platform
- [x] Copy edited by Randi Hecht
- [ ] Email SMEs when change live

Related nav ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4141

**Comment by lwalsh617** [comment] 2020-01-03 13:34
@ncksllvn @kelsonic -- Hey Guys, not sure which one of you is taking this on, and there was confusion about the tix so am flagging you both.
- I made the necessary copy changes in Git Hub (with help from Kelson and Randi!)
- Original page is here: https://github.com/department-of-veterans-affairs/vagov-content/blob/master/pages/decision-reviews/higher-level-review.md
- Preview of edited page (which is where our widget needs to go) is here: https://vagov-content-pr-610.herokuapp.com/decision-reviews/higher-level-review/
- For clarity, I have attached a screenshot indicating the copy that the widget should replace. (It goes under the H2 "How do I request a Higher-Level Review" and then H3 "Online". You'll see the copy for the widget:
Please sign in to request a Higher-Level Review online
Try signing in with your DS Logon, My HealtheVet, or ID.me account. If you don't have any of those accounts, you can create one.
Sign in or create an account >
Thank you!![https://app.zenhub.com/files/133843125/a9890648-4f6b-49ac-9de3-3d352f05bffe/download](https://app.zenhub.com/files/133843125/a9890648-4f6b-49ac-9de3-3d352f05bffe/download)

**Comment by jenniferlee-dsva** [comment] 2020-01-03 17:23
@lwalsh617 - per convo, and attaching here as well.

![HLR-heroku-header-feedback-010320.gif](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c07e2db3-be3f-4e6c-a1b2-5cc733cdfd40)

**Comment by peggygannon** [comment] 2020-01-06 21:29
@lwalsh617 Here some feedback/content recommendations from me for this page. Let me know if you have any questions or want to discuss the feedback in a call. 

- General question: When I was editing the HLR form, it said that the online form could be used for disability comp and pension claims. But the static page only mentions using the online tool for disability comp claims. I wanted to raise this as an question we need to resolve with that team/the SMEs. 

---

- Under **Online** header
I suggest recasting sentence to the below to more closely align with *online*

You can use our online tool to request a Higher-Level Review for disability compensation claims. This online option is available for only disability claims at this time. 

---

- Subway Map under step 2
To schedule an informal conference, select times and list a phone number in Part II of the form. A reviewer will call 2 to 4 weeks after VA processes your request.

Please rewrite first sentence to to make it more conversational:
If you’d like to schedule an informal conference, please select the times you’re available for a call and list a phone number in Part II of the form. 

---

- Subway map under step 4
This sentence seems duplicative, as we mention the PDF at the beginning of the subway map 
Fill out the Decision Review Request: Higher-Level Review (VA Form 20-0996). 
Download VA Form 20-0996 (PDF)

I recommend that we remove this line and replace it with: 
Submit your form in one of the ways below. 

So number 4 it would look like this:
**Apply**
Submit your form in one of the ways below.*

---

- Fix odd spacing below By mail header

- Under By mail header add the below sentence (and remove it from under the Benefit office addresses header) 
Send your completed VA Form 20-0996 to the benefit office address that matches the benefit type you selected on the form. [Find my benefit office address](#benefit-office-addresses)
can we make this link a jump link?? 


- Please tweak/add the below sentence to under In person header (and remove it from under the By fax header

You can also ask a regional benefit office for a copy of this form to fill out. You can also request a form by calling the VA toll-free hotline at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.


- Benefit office addresses, bump up this header and remove the text next to it. 


cc @jenniferlee-dsva

**Comment by lwalsh617** [comment] 2020-01-06 22:01
@jenniferlee-dsva -- Could you please take a look at Peggy's feedback above? Just want to make sure we're all on the same page before I make the edits. Thank you!

**Comment by jenniferlee-dsva** [comment] 2020-01-06 23:40
@lwalsh617 - Do you want to sync on call? I can provide write ups, but this might warrant a convo first. CC @peggygannon also? 

RE most of ^ - looks fine; but some areas, not for various reasons due to changes we (I) previously made based on SME. (Went many cycles, had to let some things go; do not want to reopen those items up again.)

**Comment by jenniferlee-dsva** [comment] 2020-01-07 00:03
Added comments to Peggy's edits above. Thanks @peggygannon - these look great with just a few caveats below. We can regroup on call if needed.
 ---

- Under **Online** header
I suggest recasting sentence to the below to more closely align with *online*

You can use our online tool to request a Higher-Level Review for disability compensation claims. This online option is available for only disability claims at this time.   _**[jl: great edit! looks good.]**_

---

- Subway Map under step 2
To schedule an informal conference, select times and list a phone number in Part II of the form. A reviewer will call 2 to 4 weeks after VA processes your request.  

Please rewrite first sentence to to make it more conversational:
If you’d like to schedule an informal conference, please select the times you’re available for a call and list a phone number in Part II of the form. _**[jl: this looks good. I hesitate re-opening this up with SME, but... I'm comfortable with this change; if SME pushes back, please just revert.]**_

---

- Subway map under step 4
This sentence seems duplicative, as we mention the PDF at the beginning of the subway map _**[jl: see comment below]**_
Fill out the Decision Review Request: Higher-Level Review (VA Form 20-0996). 
Download VA Form 20-0996 (PDF)

I recommend that we remove this line and replace it with: 
Submit your form in one of the ways below. 

So number 4 it would look like this:
**Apply**  [jl: also changing "Apply" to "Submit your form in one of the ways below"] 
Submit your form in one of the ways below.*  _**[jl: I'd keep the original copy referencing the PDF form - I don't think it's a bad thing to re-link it here as well.]**_

---

- Fix odd spacing below By mail header

- Under By mail header add the below sentence (and remove it from under the Benefit office addresses header) 
Send your completed VA Form 20-0996 to the benefit office address that matches the benefit type you selected on the form. [Find my benefit office address](#benefit-office-addresses)
can we make this link a jump link??  _**[jl: great idea. looks good. only alert: per previous comments @lwalsh617, "benefit office address" should be "benefit claims intake center address" (or if we need to shorten: "claims intake center address.]**_ 


- Please tweak/add the below sentence to under In person header (and remove it from under the By fax header

You can also ask a regional benefit office for a copy of this form to fill out. You can also request a form by calling the VA toll-free hotline at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.  _**[jl: same note re prior comments - "a VA regional office" or just "regional office," not "benefit office," per style guide]**_


- Benefit office addresses, bump up this header and remove the text next to it. _**[jl: Please keep the text, but just move it to another line. RE previous comment to bump up header to H3 -- we might actually need to make it a new H2 section, if the H3 looks to close to strong text. Someday, when these decision review pages migrate to Drupal, it will need to be an H2 in order to anchor link to it, so I guess we should just use H2 now.]**_

**Comment by jenniferlee-dsva** [comment] 2020-01-07 14:15
@lwalsh617  @Peggygannon - Sorry for the back and forth. On further thought, let's keep to the original approach of minimizing non-factual changes in this ticket. This is in light of another ticket we'll need to do as part of a content scrub and update for the upcoming Feb 19 change, and to ensure that THIS effort doesn't get bogged down by numerous rounds of 'refinements.' I will modify my comments above.

**Comment by lwalsh617** [comment] 2020-01-13 18:32
@jenniferlee-dsva @peggygannon -- Content edits have been made. Randi added the jump links and Nick added the react widget. Here's the link: https://vagov-content-pr-612.herokuapp.com/decision-reviews/higher-level-review/#Benefit-claims-intake-center-addresses

**Comment by jenniferlee-dsva** [comment] 2020-01-13 23:02
Hi Laura - This looks really good! 

3 comments:

1/ I think the heading of step 4 ("Apply") isn't quite right, given the change of H2 text. Also because step 1 says to select a certain benefit type on the form. It would make more sense for step 4 to be more specific to sending the form. So maybe like this? 

**4. Mail, fax, or drop off the form**
Submit your form in one of the ways below.  [This text from Peggy's comment ^ ] 
Download VA Form 20-0996 (PDF)

2/The second comment is about the layout/UI of the benefit intake center addresses accordion. You may need FE engineering help or Liz in design - not sure. But see screenshot. Currently you have to use the horizontal scroll to see the rest of the addresses, which isn't a good experience, and I'd be concerned that many ppl wouldn't even notice the scroll function. Would be better to just have the addresses stack. 

![image](https://user-images.githubusercontent.com/43381063/72298112-5bcee200-362b-11ea-8930-2a3d5ee8b0ba.png)

3/ The last 3 questions should now become H2s, as they don't conceptually fit under "Steps for submitting the form by mail... " H2.

**Comment by lwalsh617** [comment] 2020-01-15 18:23
@ncksllvn @RLHecht -- Need a GH Markdown assist here on 2 changes, pretty please! 
https://vagov-content-pr-612.herokuapp.com/decision-reviews/higher-level-review/#Benefit-claims-intake-center-addresses
1) See Jen's note screenshot above about wanting addresses to stack? When I'm viewing it, it does stack/no scroll bar: 
![image](https://user-images.githubusercontent.com/53535663/72459883-c2720e00-3799-11ea-81f1-940f6dd50181.png)
2) Final three H2s will not display properly. (What happens next? What if I need help? What if I have more questions?) Tried copying other H2s and editing, to no avail. Thanks for your help.

**Comment by RLHecht** [comment] 2020-01-16 14:50
@lwalsh617 I fixed the H2s for you. There was a </ol> missing at the end of the subway map so it wasn't knowing to change to the H2. I am not sure what the issue is with the addresses though because I'm seeing it as a stacked list as well.

**Comment by ncksllvn** [comment] 2020-01-16 17:51
@jenniferlee-dsva That view with the horizontal scrollbar - I don't think we've been able to recreate it. It looks like your browser is Internet Explorer, maybe? Or is that Edge? I think it's something browser-specific

**Comment by lwalsh617** [comment] 2020-01-21 15:01
@ncksllvn @Karak888 -- This isn't a priority at the moment because the tool launch has been pushed out, but don't want to lose sight of it so we're ready if they suddenly decide to launch. 
I can't replicate the issue Jen had either. I tried Firefox and Chrome on a Mac FWIW.

**Comment by lwalsh617** [comment] 2020-01-24 14:46
Per Jen's Slack post, the addresses are now stacking properly:
![Screen Shot 2020-01-24 at 9.41.53 AM.png](https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/fc1de629-ced7-405a-b67b-90d1aa78c6e4)

**Comment by lwalsh617** [comment] 2020-01-24 14:52
FYI, this is marked as an "epic" but the epic for this is 3460. We've been using this (4139) for the discussion thread. There's also issue 4140 which is a duplicate I think we can delete.

**Comment by Karak888** [comment] 2020-01-24 16:09
Hi @lwalsh617 I thought we deleted 4140 but it somehow returned?! :) I propose we close that as well, and I can take care of that.

**Comment by FranECross** [comment] 2024-05-16 18:21
Closing this old ticket

**Closed by FranECross** 2024-05-16 18:21 UTC
Labels: content, Public Websites, blocked
