### ISSUE TITLE
Select supplies to reorder functionality

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#98209] opened 2024-12-03 18:24 UTC
## User Story
As a Veteran trying to reorder medical supplies, I want to be able to select supplies that are available to reorder.

## Possible Tasks/Actions

Veteran continues an existing order
           

- [ ] Prefill the fields with existing data and selections

Veteran starts a new order
      

- [ ]      Fields are empty

Veteran wants to finish the order later
      

- [ ]      Save off the form data (built-in to the form platform)

         
       

- [ ] Need to verify the in progress order is saved to the Veteran's profile Form selections are automatically saved

      

- [ ]   Verify forms are autosaved as data is filled in/changed

## Acceptance Criteria

**Comment by radavis** [comment] 2024-12-12 21:29
Duplicate of #96476

**Closed by radavis** 2024-12-12 21:29 UTC
