### ISSUE TITLE
Check Field Mappings for VnpPtcpntRlshp

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#29106] opened 2021-08-23 21:47 UTC
VNP tables might not be getting properly mapped given variances in what is being sent vs what is being populated in RBPS.

Use case had _several_ spouses coming and going and was re-adding a spouse that was also a Veteran.

**Comment by steele-lm** [comment] 2023-11-09 17:26
Cannot reproduce. Closing.

**Closed** 2023-11-09 17:27 UTC
Labels: backend, vsa, vsa-ebenefits, 686, needs-refinement, Tree
