### ISSUE TITLE
Access for Ray Messina

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#34715] opened 2022-01-04 07:19 UTC
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ray Messina

### Your Email

rmessina10@gmail.com

### Name of Your Team

FE Tools, Software Engineer Front End, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyqL3nHCkCrNxSsgC0ZDa2u0p+/1DqpGqOqPUgKEoiJaFC8vwCQGPZuKT/i2zibhi/63Ykq+b5+AWyFc+pW2SMzJ00LEKahWN1WoOhUYuPHxrVpBI0Kn68KjHHhRSyrFhjqP5szFnCyxp2PT3x0WQTOAS27TlPD6Eu+/6lKQ1nB44AgNBDAlAnCMkRP5b6Im9v6Jbf/Ek/XeYMK89D/p6Wjj52GwJ7gmjYk19mLY8oPtb39X2YcLkTYjBqp5sAGjst0y8xTGkRGzoClADFqtgpI4CDgpXhEdNniK9jMH799ETmQi4X0r+s5Tj5ZG/IexgF6rcmzrNPNkFTU1zyiV01prouM06ZED1ynpsD+TyTFzoGlYggNw4X61jNJGErfJvI3RFVyFVyjNokhEJ4Rf42ZQdkg8D3KKwfI9rRfXVbt856ScTLh3JOQJsW3cKdS8Eb4KNnWmTJrG1Rn3St5xXl9ac6S2iXxUbVDtHGWZaoX73oaiXeTWkw73xzCv0Oz0s= raymessina@Ray-Messina-MacBook-Pro.local

**Comment by mleclerc00** [comment] 2022-01-04 16:35
This ticket is a duplicate of 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34710

closing to keep all info in one place

**Closed by mleclerc00** 2022-01-04 16:35 UTC
Labels: operations, external-request, ops-access-request
