### ISSUE TITLE
Discovery: Google Cloud Storage

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#73802] opened 2024-01-17 15:15 UTC
### Description: 
https://cloud.google.com/blog/products/networking/eliminating-data-transfer-fees-when-migrating-off-google-cloud

### Findings

**Comment by johnny-jesensky-adhoc** [comment] 2024-01-25 14:16
Closing this as a duplicate of another ticket, https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/49506.

**Closed by johnny-jesensky-adhoc** 2024-01-25 14:16 UTC
Labels: analytics-insights, spike
