### ISSUE TITLE
Make 'download PDF form' links in the modern forms search initiate download

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7474] opened 2020-04-01 15:13 UTC
## Make 'download PDF form' links in the modern forms search initiate download (instead of opening in a browser as it does today)

**User story:** 
I want to be able to access a PDF form without getting a false error message that I don't have the right Acrobat Reader version (when I do). 

**Example of bad form error message:** 
`Please wait... If this message is not eventually replaced by the proper contents of the document, your PDF viewer may not be able to display this type of document. You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by visiting http://www.adobe.com/go/reader_download. For more assistance with Adobe Reader visit http://www.adobe.com/go/acrreader. Windows is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries. Mac is a trademark of Apple Inc., registered in the United States and other countries. Linux is the registered trademark of Linus Torvalds in the U.S. and other countries.`

**Problem:** 
Some VA forms won't open in the browser. Sometimes it's genuinely because the user has the wrong Reader version, but often this bad error message appears even when you do have the correct Reader. It seems to affect only Chrome and Firefox browsers. We know that it has something to do with how VA has configured some of these forms, and possibly the default or user set browser preferences as well. VA is aware of the problem but has no plans to address this issue with the forms themselves. They don't even have a complete list of which forms has this issue.

**Resolution:** Since this problem doesn't occur when the form is downloaded, we will make our "Download VA form xxxx (PDF)" link in our new Find a VA forms search results actually initiate a download. 

**Acceptance criteria:**
- [ ] PDF form download links initiate a download dialog, instead of opening in a browser.
- [ ] Is implemented with Ryan's new design prior to launch.
- [ ] The download file name is Form-Name.pdf

**Attached screenshot:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/f4210cdb-aaad-4e91-93a2-b993459c8ce4)

**Comment by MickinSahni** [comment] 2020-04-01 17:30
estimated and groomed - we can potentially pull it in alongside #7097/#7096

**Comment by MickinSahni** [comment] 2020-04-08 17:52
Validated, live!

**Comment by stephorkandatx** [comment] 2020-04-17 16:19
Reopening w/ a comment - We are seeing a different download behavior on IE, and request that we add the same download behavior onto IE browser. 

This is not a launch blocker but would be a follow-up item if it doesn't make it in before launch.

**Comment by kelsonic** [comment] 2020-04-20 16:00
Validated, the PDF links download just fine for me in IE 11:

![image (1)](https://user-images.githubusercontent.com/12773166/79772797-c5772000-82ed-11ea-8e66-0d36ab851d50.png)

**Comment by kelsonic** [comment] 2020-04-20 16:07
I've also confirmed that all of my "add-ons" are enabled, so not sure why it wasn't working for some IE 11 folks

**Comment by kelsonic** [comment] 2020-04-20 17:57
I don't think there's an easy way to achieve this since the downloads are cross-domain: https://github.com/department-of-veterans-affairs/vets-website/pull/12281#discussion_r411570560

**Comment by stephorkandatx** [comment] 2020-04-22 17:22
From sprint planning - 

The update has not gone live, will carry over into Sprint 20 and remain in Validate.

**Comment by stephorkandatx** [comment] 2020-04-22 22:05
@kelsonic has the change gone live? In my IE, I clicked to download a form from /find-forms . 
A new tab still opened, but my previous tab alerted me that *something* was happening there as well. When I clicked to my previous tab, a banner had appeared asking me what I wanted to do with the file (Open, Save, or Cancel).

**Comment by kelsonic** [comment] 2020-04-23 14:27
@stephorkandatx it has! I've confirmed it works as desired on Chrome now, I'll check IE here in a second... any chance you could open up the dev tools on va.gov/find-forms after you click a download link? It will only open it in a new tab if there's an error that's thrown, so there must be an error in the `console` somewhere 🤔

**Comment by stephorkandatx** [comment] 2020-04-27 15:26
@kelsonic there is one error that shows
SCRIPT7002: XMLHttpRequest: Network Error 0x2eff, Could not complete operation due to error 00002eff . 

Same behavior - opens a new tab, and a banner appears asking me what i want to do with the file.

**Comment by kelsonic** [comment] 2020-04-28 16:31
Hey! Going to check this out now, sorry for the delay 🙂

**Comment by kelsonic** [comment] 2020-04-28 17:10
Hey @stephorkandatx, so I am able to reproduce the error:

![image](https://user-images.githubusercontent.com/12773166/80516340-8f1a5000-8940-11ea-8440-467176f75529.png)

It also opened a new tab for me, but then it closed it. It opened it due to [this code here](https://github.com/department-of-veterans-affairs/vets-website/pull/12281/files#diff-54bd03c72745b961652d3af97bae35b7R22), but if it was still able to download the file even with an error then that means this is very confusing indeed... It basically means we can't choose a different download strategy if there's an error since it still may download successfully... Would love to get your thoughts @ncksllvn on how we could approach this problem.

**Comment by ncksllvn** [comment] 2020-04-28 17:21
The output suggests a CORS error to me. We should only be applying the download behavior to PDF whose locations match the domain `/find-forms` is executing under. So if we're on `staging.va.gov/find-forms` we shouldn't try to download _any_ of them, because no forms are hosted on `staging.va.gov`. However, if we're on `www.va.gov`, then most forms should be okay to attempt to download. Some forms are on `vba.va.gov` though, so we shouldn't be trying to download those or we'll  hit a CORS error even on production.

We should do the following -

1. Add back the `target="_blank"` attribute into the links to the PDFs
1. In `onDownloadClick`, confirm that the PDF's URL matches the `document.location.hostname` so we know CORS won't be an issue
1.  Make sure the name of the download is the `form.attributes.title`, not the [form's URL](https://github.com/department-of-veterans-affairs/vets-website/blob/8a9869af527512104bb1488019d18b7c0a6de143/src/applications/find-forms/components/SearchResult.jsx#L64).

**Comment by kelsonic** [comment] 2020-04-28 17:30
@ncksllvn 

1. I don't think we want to open the PDFs in a new tab, are you sure we want to add back `target="_blank"`? It seems like this was only a problem for IE since we have [this line](https://github.com/department-of-veterans-affairs/vets-website/pull/12281/files#diff-54bd03c72745b961652d3af97bae35b7R10).
2. ✅ 
3. ✅

**Comment by kelsonic** [comment] 2020-04-28 17:33
PR is up for this! 🙂

**Comment by ncksllvn** [comment] 2020-04-28 17:35
> I don't think we want to open the PDFs in a new tab, are you sure we want to add back target="_blank"? It seems like this was only a problem for IE since we have this line. Plus, I think 2 makes 1 moot

We _never_ want PDFs to open in the same tab, so `target="_blank"` should be there as a fallback if we can't download it. This case will be true for VBA domains.

For example, if I go to `https://www.va.gov/find-forms?q=disability`, the very first result is `21-0819 DoD Referral to Integrated Disability Evaluation System (IDES) (Fillable)` located at https://www.vba.va.gov/pubs/forms/VBA-21-0819-ARE.pdf. If I click the link `Download VA form 21-0819 (PDF)` using Chrome, the PDF opens in the same tab as Find Forms.

**Comment by kelsonic** [comment] 2020-04-28 17:59
Got it, I had misunderstood this ticket's original AC then as I had thought it was saying we never want to open the links in a separate tab, thanks for the clarification! 🙂 

![image](https://user-images.githubusercontent.com/12773166/80521142-bfb1b800-8947-11ea-843c-ebc6ca058475.png)

**Comment by stephorkandatx** [comment] 2020-04-29 15:53
If the PDF is not on www.va.gov , that specific domain, we cannot download it to the tray. It has to be opened in a tab. 
When it is the same domain, it downloads to the tray (Chrome). When it's not the same domain, Chrome follows the domain so then it would open in a new tab.

**Comment by stephorkandatx** [comment] 2020-04-29 16:26
Nick made this flow chart to illustrate expected behavior
![image](https://user-images.githubusercontent.com/63361321/80620926-3ca66580-8a0c-11ea-811d-418c087a193f.png)
@jenniferlee-dsva FYSA

**Comment by kelsonic** [comment] 2020-04-29 19:48
PR merged! 🎉 https://github.com/department-of-veterans-affairs/vets-website/pull/12398

**Comment by jenniferlee-dsva** [comment] 2020-04-29 20:06
Thank you for the diagram @ncksllvn . 

So if I understood correctly - it doesn't matter that all the forms are hosted in the VA forms database; if the form PDF URL is not va.gov/[whatever] the download function will not work and it will open in a new browser?  -- So it really has to do with the URL path, not the source database?

**Closed** 2020-05-04 22:45 UTC
Labels: frontend, vsa, vsa-public-websites
