### ISSUE TITLE
Account Creation API: draft implementation strategy & timeline

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#94126] opened 2024-10-02 16:31 UTC
## Description

Now that the code for the account creation API is available and our team has been able to look at it to assess our understanding of the API's architecture, we have validated how we will receive errors from the API (if they occur) and what alert messaging we generally need to create for users in those scenarios. This work is not only relevant on the MHV on VA.gov landing page - the affected tools may also need to serve these alerts on their end, depending on how we want to handle routing for users w/o access to tools. 

In the previous ticket we diagrammed & presented routing options to affected tool POs / stakeholders from medications, secure messages, & medical records. Now that they have made a decision on which approach to take for the MHV-API dependent applications, we can move forward in drafting an implementation strategy for those side-door entry points as well as alert implementation on the My HealtheVet page. 

This ticket is focused on drafting an implementation strategy & planned timeline to be approved by stakeholders. 

### User story
As a Cartography team member, I want to clarify the needs of the account creation API to all relevant My HealtheVet on VA.gov stakeholders, and explain and clarify a timeline and implementation strategy that will work for all affected teams, so that the API and the relevant error alerts can be launched into the UX synchronously. 

### Notes
- [ ] [Account Creation API architecture Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=uf94a77a19aaf687331c09367)
- [ ][ Draft alerts ](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=229-3&node-type=canvas&t=1QPIhuovDIGQq53y-0)(Figma)
- [ ] Diagram of routing options & alert placement for affected tool apps (side door entry points)
- [ ] Notes from stakeholder meeting (if applicable)
- @wesrowe is working on #97662 (Draft Delivery Rollout Plan)
Possible tasks:
- [ ] Draft implementation strategy & timeline

## Acceptance criteria
- [ ] An implementation strategy based on stakeholder input from the previous ticket has been drafted, and is sent out to those same stakeholders for feedback. 
- [ ] Follow-on ticket created to implement the strategy & any other tickets as needed

**Comment by wesrowe** [comment] 2024-12-04 21:38
@sterkenburgsara, I feel like this ticket has been eclipsed by a couple others, mainly the "stakeholders" ticket. Are you good with closing this as a no-op?

**Comment by fmccaf1** [comment] 2024-12-11 17:49
Dupe of other ticketed work, closing

**Closed by fmccaf1** 2024-12-11 17:49 UTC
Labels: ux, engineering, needs-refinement, Cartographers
