### ISSUE TITLE
Grammar issue on Review your appointment details page

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#60091] opened 2023-06-12 13:10 UTC
## Summary
The H2 reads "You’re requesting a amputation care appointment"

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** 
Judy 
1. Go to:https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_
![Screenshot 2023-06-12 at 8.59.20 AM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/f5e361ce-e7ad-4de4-8064-59f420a66622)

### Desired Result
The H2 should read "You’re requesting an amputation care appointment"

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [x] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment] 2023-06-23 13:31
@melissa-lefevre - Is this ticket 60091 a duplicate of ticket #60090? If yes, can you please close it out. #60090 is already in the Ready queue.

**Closed** 2023-06-23 13:36 UTC
Labels: bug, appointments-product-design, front end
