### ISSUE TITLE
Make decision on 'edit' buttons

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2153] opened 2019-10-01 16:54 UTC
The 'edit' buttons in the review page are a new forms pattern. Decisions made early in the form affect every other page greatly, so easiest / safest thing to do is to navigate veterans to the page that contains the info to be edited, then having them navigate through the rest of the flow again.

**Comment by lenaecb** [comment] 2020-03-04 14:30
@goldenmeanie - Hi! I am cleaning up our backlog. This little dude doesn't look like it's relevant any longer? Could you confirm that? If not relevant (or if we don't know if it's relevant) I am going to close this because I am not sure what it was intended for 5 months ago.

**Comment by goldenmeanie** [comment] 2020-03-04 14:51
I strongly suspect you can close this.

**Comment by lenaecb** [comment] 2020-03-04 14:55
Beautiful, thanks @goldenmeanie

**Closed by lenaecb** 2020-03-04 14:55 UTC
Labels: design
