### ISSUE TITLE
VSP-owned transformer discrepancies Graph QL <> CMS Export Build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#19314] opened 2021-02-01 15:29 UTC
## Details 

To reach parity - using JSON comparison tool - in VSP-owned transformers

### Transformers owned by VSP 
~~- [ ] `node-leadership_listing`~~
~~- [x] `node-va_form`~~
~~- [x] `node-publication_listing`~~
- [x] `node-page`

### Acceptance Criteria
- [ ] VSP-owned transformers do not show any discrepancies in JSON comparison tool

**Comment by theodur** [comment] 2021-02-01 16:54
This work has been blocked by the issues present in the CMS export relating to the change in format of data. On Friday a fix was pushed out for those but some issues with the CMS export are still present. I found a way around this to get the build workable, so I am able to continue working on the remaining `diffs` discovered by running a fresh CMS export build.
Related thread: https://dsva.slack.com/archives/C01512KN35G/p1611760815169800?thread_ts=1611760815.169800&cid=C01512KN35G

**Comment by theodur** [comment] 2021-02-03 19:36
All the descrepancies that can be fixed for `node-page` at the moment are in this PR.
The following discrepancies are not cause by the transformer itself:
- The url issue talked about [here](https://dsva.slack.com/archives/C01512KN35G/p1612208167277200) ([#19367](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19367))
- There is an unpublished field (`fieldAlert`) that is being pulled into the GraphQL build. Transformers do not transform unpublished entities, so the field is `null` in the CMS export. This is in `node.a9fecd1c-9da9-4d13-b7fe-ca846fb93f47.json`'s `field_alert`.
- An issue with the `tableValue` field. Further discussed [here](https://dsva.slack.com/archives/C01512KN35G/p1612290645314500?thread_ts=1612221890.297300&cid=C01512KN35G)

**Comment by theodur** [comment] 2021-02-03 23:15
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15930) for `node-publication_listing` discrepancies.

**Comment by theodur** [comment] 2021-02-04 22:31
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15951) for `node-va_form` discrepancies.

**Comment by theodur** [comment] 2021-02-04 22:33
`node-leadership_listing` discrepancies should be resolved when this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19367) is closed.

**Comment by theodur** [comment] 2021-02-10 19:44
CMS export issues relating to remaining discrepancies:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4198 (non-blocking)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4250 (blocking)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3573 (blocking)

**Comment by theodur** [comment] 2021-02-15 19:17
It turns out `node-va_form` is owned by Public Websites, and `node-leadership_listing` & `node-publication_listing` are owned by VAMC. I am crossing out the transformers we do not own.

**Comment by meganhkelley** [comment] 2021-02-15 19:42
@theodur does this mean VSP only owns `node-page`? 

If so could you please update the transformer readme in vets-website with that info? That is where we have asked other teams to keep track of their ownership

**Comment by theodur** [comment] 2021-02-15 21:00
@meganhkelley That's correct.

Earlier today I asked Nick if he could update the transformers `README.md` file. I'll ask Michael to do the same also when he's in tomorrow.

**Comment by theodur** [comment] 2021-02-16 22:02
Plot twist: it turns out we don't own any transformers. `node-page` is owned by public websites, I confirmed with Nick. I updated the transformer [README](https://github.com/department-of-veterans-affairs/vets-website/pull/16073) to reflect this. It looks like we can close this ticket.

**Closed** 2021-02-16 23:58 UTC
Labels: cms-transformer, tools-fe
