### ISSUE TITLE
Analytics Implementation or QA Support for Existing ChooseVA

### ISSUE THREAD

**Issue by SethNiman** [department-of-veterans-affairs/va.gov-team#23102] opened 2021-04-12 22:31 UTC
# Google Analytics Implementation or QA Request
Analytics and Tag Manager request for upcoming relaunch of our ChooseVA site. 
## What this form is for
Start up meeting to discuss our needs, what we hope to track, etc. Also interested in learning about access to current tag manager on VA.gov. 
New ChooseVA site is going to launch in May. We will want to track multiple events off the site, though we don't have the specifics yet. Likely would want to track through to some benefits pages and applications pages housed on other parts of VA.gov. Looking for additional thoughts in how best to implement conversions etc.
<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?

    - [Insert Name(s)]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - [Insert team and project]
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment] 2021-04-28 22:14
### Data Layer Specification 

| Description of Interaction | Data Layer Specification | Dev Notes 
| -- | -- | -- | 
**Click on link click within "COVID-19 vaccines at VA" banner** <br><br> ![image](https://user-images.githubusercontent.com/48527022/116478014-77272600-a84b-11eb-9c17-3e92388deaee.png) | `datalayer.push({`<br>`event: 'nav-alert-box-link-click'`<br>`'alert-box-status': 'info'`<br>`'alert-box-headline': //dynamically populate with the top level heading of the alert box, i.e 'COVID-19 vaccines at VA'`<br>`'alert-box-subheading': undefined`<br>`'alert-box-clickLabel': //dynamically populate with the click text label, i.e 'Get the latest updates on COVID-19 vaccines at VA'`<br>`});`
**_All_** submissions of the form (successful or failed) | `dataLayer.push({`<br>`'event': 'choose-va-learn-more--submission'});`
**_Successful_** submissions of the form | `dataLayer.push({`<br>`'event': 'choose-va-learn-more--submission-successful'`<br>`'health-care-benefit-interest': true\|false`<br>`'disability-compensation-benefit-interest': true\|false`<br>`'education-benefit-interest': true\|false`<br>`'other-benefit-interest': true\|false`<br>`});` | Populate `true` for when the box is checked and `false` when not
**_Failed_** submissions of the form | `dataLayer.push({`<br>`'event': 'choose-va-learn-more--submission-failed'`<br>`'health-care-benefit-interest': true\|false`<br>`'disability-compensation-benefit-interest': true\|false`<br>`'education-benefit-interest': true\|false`<br>`'other-benefit-interest': true\|false`<br>`});` | Populate `true` for when the box is checked and `false` when not
Welcome Kit Downloads | `dataLayer.push({`<br>`'event': 'cta-button-click',`<br>`'button-click-label': 'View your VA Welcome kit'`<br>`});` | ⚠️ We will want to remove the current `_ga` cookie that is embedded within the PDF url <br> ![image](https://user-images.githubusercontent.com/48527022/116478709-83f84980-a84c-11eb-9a8d-b1e5e3986a11.png)
Footer link clicks | `dataLayer.push({`<br>`'event': 'nav-footer'`<br>`});`

**Comment by jonwehausen** [comment] 2021-05-12 16:34
@SethNiman The specification above has been updated to include the data layer specification for tracking the clicks within the "Among the VA benefits you may be eligible for section"

![image](https://user-images.githubusercontent.com/48527022/118011722-603e0480-b31e-11eb-80b5-0c6852b428b5.png)

**Comment by laurensimpson14** [comment] 2021-05-19 14:59
@SethNiman I'm taking this request over for Jon. Is there anything ready to be tested? (And do you have a dev or staging environment?)

**Comment by SethNiman** [comment] 2021-06-22 21:58
Lauren,

We are getting closer to having a site ready for testing and pixel placements etc.

Can we connect on a call to discuss next steps?

Seth Niman

From: Lauren Simpson ***@***.***>
Sent: Wednesday, May 19, 2021 11:00 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Seth Niman ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [department-of-veterans-affairs/va.gov-team] Analytics Implementation or QA Support for Existing ChooseVA (#23102)

Caution: External sender; be careful with links and attachments.

@SethNiman<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSethNiman&data=04%7C01%7Cseth.niman%40aptiveresources.com%7Cb5b04ca6e4f2486d631a08d91ad6cec7%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637570332173145662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=klUAabaaajUQVF2dSJcY3NjPCil4klBSHl8UCNScq1w%3D&reserved=0> I'm taking this request over for Jon. Is there anything ready to be tested? (And do you have a dev or staging environment?)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F23102%23issuecomment-844189306&data=04%7C01%7Cseth.niman%40aptiveresources.com%7Cb5b04ca6e4f2486d631a08d91ad6cec7%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637570332173145662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K174se5FNXPUriOnZjswOFHBzRpXzeCrOQqWwyjnFl8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUZROAZB3YIFAI7VR7TBHDTOPG73ANCNFSM422FC2CA&data=04%7C01%7Cseth.niman%40aptiveresources.com%7Cb5b04ca6e4f2486d631a08d91ad6cec7%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637570332173155660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DGw3q6TfMAcqtLyKmVVHQ5ynVn6EOw8y0nJF2Z%2Ff0dc%3D&reserved=0>.

Confidentiality Notice: This email message and any attachments are for the sole use of the intended recipient(s) and may contain confidential information protected by law. If you have received this message in error, please notify the sender and delete it from your system.

**Comment by laurensimpson14** [comment] 2021-06-23 15:29
@SethNiman Not a problem. Would you have time to meet Friday (6/25) between 1:30 - 4:00 pm EDT? Or Tuesday (6/29) between 10:00 - 11:30 am EDT?

**Comment by SethNiman** [comment] 2021-06-23 15:31
Let's meet Friday at 3, if that works. In the meantime, I can start sending some site tags etc.


From: Lauren Simpson ***@***.***>
Sent: Wednesday, June 23, 2021 11:30 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Seth Niman ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [department-of-veterans-affairs/va.gov-team] Analytics Implementation or QA Support for Existing ChooseVA (#23102)

Caution: External sender; be careful with links and attachments.

@SethNiman<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSethNiman&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763102612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2wDajk5Qv0hW8NLtmkqn71Er54Jk7pHHgZLYC4SRUK4%3D&reserved=0> Not a problem. Would you have time to meet Friday (6/25) between 1:30 - 4:00 pm EDT? Or Tuesday (6/29) between 10:00 - 11:30 am EDT?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F23102%23issuecomment-866938122&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763112608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vhmbKXDhduJV0meyvsMeMymSGuqHI3b2kSaOLAR5evA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUZROD43XT4VJMZ2KHRZR3TUH4VZANCNFSM422FC2CA&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763112608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e%2BwPm%2BtZ1G2yu0oCYaWzmbn0ybxNMEbsPNtARQtsSgw%3D&reserved=0>.

Confidentiality Notice: This email message and any attachments are for the sole use of the intended recipient(s) and may contain confidential information protected by law. If you have received this message in error, please notify the sender and delete it from your system.

**Comment by SethNiman** [comment] 2021-06-23 18:20
I thought we were looking at Friday June 25th. But the invite was for July 2nd.

From: Lauren Simpson ***@***.***>
Sent: Wednesday, June 23, 2021 11:30 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Seth Niman ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [department-of-veterans-affairs/va.gov-team] Analytics Implementation or QA Support for Existing ChooseVA (#23102)

Caution: External sender; be careful with links and attachments.

@SethNiman<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSethNiman&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763102612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2wDajk5Qv0hW8NLtmkqn71Er54Jk7pHHgZLYC4SRUK4%3D&reserved=0> Not a problem. Would you have time to meet Friday (6/25) between 1:30 - 4:00 pm EDT? Or Tuesday (6/29) between 10:00 - 11:30 am EDT?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F23102%23issuecomment-866938122&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763112608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vhmbKXDhduJV0meyvsMeMymSGuqHI3b2kSaOLAR5evA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUZROD43XT4VJMZ2KHRZR3TUH4VZANCNFSM422FC2CA&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C1c5d9e54a82d4aef1b1508d9365bb3c6%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637600589763112608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e%2BwPm%2BtZ1G2yu0oCYaWzmbn0ybxNMEbsPNtARQtsSgw%3D&reserved=0>.

Confidentiality Notice: This email message and any attachments are for the sole use of the intended recipient(s) and may contain confidential information protected by law. If you have received this message in error, please notify the sender and delete it from your system.

**Comment by laurensimpson14** [comment] 2021-06-24 04:07
@SethNiman good catch - I've moved it to the correct date! Talk soon

**Comment by bsmartin-ep** [comment] 2021-06-28 14:57
@jennaouellet -

Can you please create two new views on the VA's **non-production** property?

![image](https://user-images.githubusercontent.com/62304138/123657471-d0391900-d7fe-11eb-84d7-116c1102eb49.png)

We'll need....

- <h3>An unfiltered view.</h3>  This should essentially be a duplicate of the _va.gov - Unfiltered_ view in the production property.  No filters (as you can imagine), but you'll want to make sure the view config settings (like time zone, Exclude URL Query Parameters, URL _etc_) match the production one
- <h3>A choose.va.gov view</h3>  This will be a dedicated view for just choose.va.gov hits.  Take a look at some of the other ones like eBenefits and MHV.  In fact, it may be easiest to copy one of those, remove the domain-specific filter, and <strong>create a new filter including only choose.va.gov hits</strong>.

Let me know if you have an questions.

**Comment by jennaouellet** [comment] 2021-06-28 21:26
Views have been created

**Comment by SethNiman** [comment] 2021-07-21 16:27
The staging version of choose.va.gov is going live some time in the next 24 hours. Can you help me with next steps to make sure the live version is covered by analytics? 
I also want to make sure I have access to the right analytics account and that the cross tracking works so if someone clicks on a link from choose.va.gov to another VA site, we have the tracking in place to follow.

**Comment by SethNiman** [comment] 2021-07-21 16:27
Also, as I get advertising up and running can I provide you with pixels for GTM?

**Comment by bsmartin-ep** [comment] 2021-07-21 16:31
@SethNiman -

> Can you help me with next steps to make sure the live version is covered by analytics?

From our end, we should just need to publish our GTM changes.

Here is our non-production GA property for ChooseVA:

https://analytics.google.com/analytics/web/#/report-home/a50123418w178298118p245735699

I'm not seeing any data.  Has the [non-production GTM snippet](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23102#issuecomment-822738795) been installed on every page?   Are our hostname filters OK?

```
vaww.choose.cfde.webdev.va.gov
dash.oit.webdev.va.gov
```

> Also, as I get advertising up and running can I provide you with pixels for GTM?

Sure thing - if you send us an issue with the code and pages it should run on, it would be a pretty quick update.

-------------

One more thing, you're still relying on us to insert the DAP script, correct?

**Comment by SethNiman** [comment] 2021-07-21 16:49
I will pass this information on to the VA person doing the site. I don't really know the answers here. I might need to get us on a call with the site person to make sure everyone is on the same page.

**Comment by SethNiman** [comment] 2021-07-21 17:12
From the web lead - 
You might be seeing “choose.cfde” in the production numbers. I forgot to update the script logic (fixed now). The dash numbers should be in the non-production.

**Comment by SethNiman** [comment] 2021-07-21 17:57
i set up a call for 4PM today

**Comment by bsmartin-ep** [comment] 2021-07-21 20:27
@SethNiman -

GTM workspace has been updated and published up to staging.

Seeing data in the realtime reports...

https://analytics.google.com/analytics/web/#/realtime/rt-location/a50123418w178298118p245735699/

**Comment by SethNiman** [comment] 2021-07-21 23:25
@bsmartin-ep Can you add me to that analytics account? Or show me where I am supposed to request that? 
Here is my VA.gov email - seth.niman@va.gov

**Comment by bsmartin-ep** [comment] 2021-07-22 01:08
Just added you @SethNiman.  If anyone else on your team needs access, you can [open an issue with this template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by SethNiman** [comment] 2021-07-22 13:31
Thanks! I have a question for you on this. I noticed this on other analytics accounts too. There seems to be an gov delivery email that goes out every so often and drives tons of traffic to the page. But I don't think it is accurate. The traffic is almost entirely from Wyoming. I am wondering if something is tagged incorrectly, or if a Wyoming visn page has the wrong analytics code on it. https://analytics.google.com/analytics/web/?authuser=2#/report/trafficsources-campaigns/a50123418w177519031p245919504/_u.date00=20210701&_u.date01=20210722

and

https://analytics.google.com/analytics/web/?authuser=2#/report/visitors-geo/a50123418w177519031p245919504/_u.date00=20210701&_u.date01=20210722&geo-table.plotKeys=%5B%5D&_r.drilldown=analytics.country:US

Not sure if you can look at that or is that out of your scope...

**Comment by SethNiman** [comment] 2021-07-22 21:55
@bsmartin-ep  Brian, I got this note from Steve, with whom we spoke yesterday -
Seth,

The site went live, but there seems to be an issue with the analytics script
Uncaught TypeError: Cannot read property ‘src’ of null
    at _updateConfig (Universal-Federated-Analytics.js:189)
    at _onEveryPage (Universal-Federated-Analytics.js:77)
    at Universal-Federated-Analytics.js:85

Could not load content for https://dap.digitalgov.gov/Universal-Federated-Analytics.js (HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

This is related to the DAP script that they injected.

It should be https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?ver=true&agency=VA&UA-123020795-1

Steve

**Comment by bsmartin-ep** [comment] 2021-07-23 05:44
@SethNiman -

I updated the script URL and was still seeing the error.  Updating it to asyncronous and enabling `document.write` seems to have fixed it. 

Can you confirm?

**Comment by bsmartin-ep** [comment] 2021-07-23 16:51
> Thanks! I have a question for you on this. I noticed this on other analytics accounts too. There seems to be an gov delivery email that goes out every so often and drives tons of traffic to the page. But I don't think it is accurate. The traffic is almost entirely from Wyoming. I am wondering if something is tagged incorrectly, or if a Wyoming visn page has the wrong analytics code on it. https://analytics.google.com/analytics/web/?authuser=2#/report/trafficsources-campaigns/a50123418w177519031p245919504/_u.date00=20210701&_u.date01=20210722
> 
> and
> 
> https://analytics.google.com/analytics/web/?authuser=2#/report/visitors-geo/a50123418w177519031p245919504/_u.date00=20210701&_u.date01=20210722&geo-table.plotKeys=%5B%5D&_r.drilldown=analytics.country:US
> 
> Not sure if you can look at that or is that out of your scope...

Let's put this in a new ticket @SethNiman.  I definitely see what you're talking about though....

https://analytics.google.com/analytics/web/?authuser=2#/report/trafficsources-all-traffic/a50123418w177519031p245919504/_u.date00=20210701&_u.date01=20210722&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.region&explorer-table.rowStart=0&explorer-table.rowCount=50&_r.drilldown=analytics.sourceMedium:govdelivery%20~2F%20email/

**Comment by bsmartin-ep** [comment] 2021-08-11 17:19
OK to close out this ticket @SethNiman?  Are you ready to re-visit form submission tracking?

https://github.com/department-of-veterans-affairs/va.gov-team/issues/23102#issuecomment-828816223

**Comment by joanneesteban** [comment] 2021-08-11 17:23
Hi @SethNiman ! The Analytics team is going to close out this ticket. Please feel free to reopen if you need additional support from us.

**Comment by SethNiman** [comment] 2021-08-11 17:24
Yes, I actually would like to reopen. I am working on a few tags and had some questions.



From: Joanne Esteban ***@***.***>
Sent: Wednesday, August 11, 2021 1:23 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Seth Niman ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [department-of-veterans-affairs/va.gov-team] Analytics Implementation or QA Support for Existing ChooseVA (#23102)

Caution: External sender; be careful with links and attachments.

Hi @SethNiman<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSethNiman&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C4752fa8a9fa94a01c7e108d95cecba81%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637642994076373842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rBqMSfBRiktWWrYS7ebnN0TbOa3FVufIvhjVNIWmDpE%3D&reserved=0> ! The Analytics team is going to close out this ticket. Please feel free to reopen if you need additional support from us.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F23102%23issuecomment-897009773&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C4752fa8a9fa94a01c7e108d95cecba81%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637642994076373842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aS8SREpEQVvo9EWRUqrH%2BKo5RO9ChGg0dkaHB3ZXX3w%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATUZROD5Z5ZHHDAMKW46TOTT4KWYNANCNFSM422FC2CA&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C4752fa8a9fa94a01c7e108d95cecba81%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637642994076383830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2rvHqozfxM7qbC5Ac0g%2Fscm5oCc8eqZCPUHyMaBnju0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C4752fa8a9fa94a01c7e108d95cecba81%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637642994076383830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uf%2FWqY40P5K2U9MFao3dazWa7BFy5tGZCDAk%2F49V39U%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cseth.niman%40aptiveresources.com%7C4752fa8a9fa94a01c7e108d95cecba81%7Cae5354d96fa5483194393fbd1fe66920%7C0%7C0%7C637642994076393830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sAdKIu%2BqYGtFqOQVsuMeA67K5nuRzyX3pEfrdZlM6Ks%3D&reserved=0>.

Confidentiality Notice: This email message and any attachments are for the sole use of the intended recipient(s) and may contain confidential information protected by law. If you have received this message in error, please notify the sender and delete it from your system.

**Comment by bsmartin-ep** [comment] 2021-08-28 01:21
Further choose.va.gov work will be covered by this ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/23982

**Closed by bsmartin-ep** 2021-08-28 01:21 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle, gtm, collab-cycle-review
