### ISSUE TITLE
[FE] The link from the direct deposit page should take the user directly to the profile/direct-deposit 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12032] opened 2020-08-04 19:58 UTC
## Background
See:  IA feedback from Staging review - Profile 2.0 #11968

**MUST** - Once signed in, the link from the [direct deposit page](https://staging.va.gov/change-direct-deposit/) should take the user directly to the profile/direct-deposit.

**Comment by sanlouise** [comment] 2020-08-06 17:07
@kelsonic Would the public websites team be responsible for this change?

**Comment by kelsonic** [comment] 2020-08-06 17:11
@sanlouise Yupp we can do that, just to confirm you want this button link to go to `/profile/direct-deposit`?

![image](https://user-images.githubusercontent.com/12773166/89561343-966db700-d7d5-11ea-927b-b634a819461e.png)

**Comment by sanlouise** [comment] 2020-08-06 17:15
@kelsonic That's correct. Thank you! 

For visibility: @Samara-Strauss @mshea0606

**Comment by kelsonic** [comment] 2020-08-06 17:21
Perfect, if that's indeed accurate this should be a relatively low LOE for our team to implement, though I do think we have an intake form process for this CC @MickinSahni

**Comment by kelsonic** [comment] 2020-08-06 17:22
Alternatively, if you want to update this line of code [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/cta-widget/helpers.js#L161) to be the desired URL you want, that would also do it 🙂

**Comment by Samara-Strauss** [comment] 2020-08-06 17:35
This looks like it is a duplicate of #8419, but I'm going to close that in favor of this ticket.

Just a note I don't want to get lost in the mix. Since we are doing a phased rollout, we need to make sure this link isn't updated in production until we are live to 100% of users, OR this needs to be coded conditionally that if someone has access to profile 2.0 in prod, the link goes directly to direct deposit, but if they don't, the link still goes to profile 1.0. I'll leave it up to you all to decide the best approach, but please document the direction you want to take in this ticket for visibility.

**Comment by Samara-Strauss** [comment] 2020-08-06 17:37
From @sanlouise [in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1596735181231000?thread_ts=1596734237.228100&cid=C909ZG2BB)

> So right now, when we change the link, it will change it for all users (regardless of whether they are in profile 1 or 2). When in profile 1, the new profile/direct-deposit link just redirects the user to Profile 1, so the desired normal page. The only thing is that the url stays profile/direct-deposit, but this does not change the actual user experience. 

This plan sounds good to me!

**Closed** 2020-08-06 18:19 UTC
Labels: design, frontend, high priority, ia, profile, vsa-authenticated-exp

**Comment by Samara-Strauss** [comment] 2020-08-06 18:47
Checked it out on staging — looks great!
