### ISSUE TITLE
Move debug info to end of build process

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#25100] opened 2021-05-21 21:33 UTC
Discussed in [#24022](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/24022).

### Details

Content build debugging information consists of the the entire stringified page object for a particular page. For some pages this can be >300kb of data. Stringification causes a substantial jump in memory use because the data is stored as text in a buffer as well as in the `pages` object.

Delaying stringification of debugging data until the last possible step in the build process will delay the memory use jump. 

We might even consider waiting until metalsmith finishes writing all the fully rendered HTML pages to disk. We'd keep a reference to metalsmith's `files` object and iterate over it. For each item we'd open the corresponding HTML file on disk, stringify the page object, write the stringified JSON to the file, and save the file. This approach would avoid having to keep all the stringified debugging info in memory at once.

Note that debugging data is unneeded in the production build. We should include it only in dev and staging builds.

### Acceptance Criteria

- [ ] Stringification of debugging data occurs at the last possible step in the build process
- [ ] Debugging information is present in dev and staging builds as before

**Comment by theodur** [comment] 2021-06-14 18:05
## Approach 1: Adding debug info right before layouts are applied
The last possible step in the build process where debug info can be added is a right before layouts are applied. This approach delays memory spikes of storing debug info in the Metalsmith `files` object.

**Local results:**
```
                                                              Step summary
  Step                          Description                           Time Elapsed   Heap Change   Total Heap   RSS Change   Total RSS

     0   Create symlink into vets-website for local development.      0ms            0.01mB        32.9mB       0mB          97.89mB
     1   Create React pages                                           8ms            0.21mB        33.13mB      0.13mB       98.31mB
     2   Get Drupal content                                           26202ms        234.56mB      267.71mB     382.73mB     481.05mB
     3   Add Drupal Prefix                                            51ms           -0.13mB       267.6mB      1.46mB       482.55mB
     4   Create Outreach Assets Data                                  57ms           2.51mB        270.12mB     0.41mB       482.98mB
     5   Create "Resources and support" section of the website        253ms          31.63mB       301.76mB     36.57mB      519.55mB
     6   Create environment filter                                    7ms            0.62mB        302.4mB      2.66mB       522.52mB
     7   Add filenames for debugging                                  7ms            0.71mB        303.12mB     0.8mB        523.42mB
     8   Check collections                                            12ms           0.94mB        304.08mB     0.38mB       523.82mB
     9   Group collections                                            2828ms         12.56mB       316.65mB     -18.53mB     505.34mB
    10   Reset left rail navigation menu levels                       8ms            2.09mB        318.76mB     0mB          505.34mB
    11   Add the date to filenames                                    96ms           1.97mB        320.74mB     2.82mB       508.16mB
    12   Add app assets                                               216ms          -17.55mB      303.2mB      1.89mB       510.05mB
    13   Add content assets                                           70ms           -6.57mB       296.64mB     60.84mB      570.89mB
    14   Plug the content into the templates                          285ms          10.75mB       307.4mB      -12mB        558.9mB
    15   Translate the markdown to html                               19ms           2.08mB        309.49mB     0.13mB       559.03mB
    16   Add permalinks and change foo.md to foo/index.html           9221ms         -3.44mB       306.07mB     1.08mB       560.11mB
    17   Create header and footer                                     82ms           4.25mB        310.33mB     0.11mB       560.22mB
    18   Generate navigation                                          2561ms         32.69mB       343.04mB     5.43mB       565.65mB
    19   Add debug info to Drupal pages                               104ms          -3.9mB        339.15mB     0.63mB       566.28mB
    20   Apply layouts A                                              9306ms         300.03mB      639.2mB      699.25mB     1265.53mB
    21   Apply layouts B                                              4320ms         -83.45mB      555.76mB     -351.28mB    914.25mB
    22   Apply layouts C                                              9178ms         52.84mB       608.62mB     385.18mB     1299.43mB
    23   Apply layouts D                                              4653ms         -31.35mB      577.29mB     -118.86mB    1180.57mB
    24   Apply layouts E                                              4150ms         -124.07mB     453.23mB     -96.46mB     1084.11mB
    25   Apply layouts F                                              3760ms         108.52mB      561.77mB     58.92mB      1143.04mB
    26   Apply layouts G                                              3485ms         -236.91mB     324.87mB     -39.93mB     1103.11mB
    27   Apply layouts H                                              8310ms         17.86mB       342.75mB     165.04mB     1268.14mB
    28   Apply layouts I                                              3521ms         89.01mB       431.78mB     50.23mB      1318.38mB
    29   Apply layouts J                                              5818ms         121.94mB      553.74mB     -54.96mB     1263.41mB
    30   Apply layouts K                                              4143ms         -257.68mB     296.07mB     -70.23mB     1193.19mB
    31   Apply layouts L                                              7756ms         27.93mB       324.03mB     122.51mB     1315.7mB
    32   Apply layouts M                                              10131ms        171.58mB      495.64mB     341.64mB     1657.34mB
    33   Apply layouts N                                              5215ms         -187.56mB     308.1mB      -188mB       1469.34mB
    34   Apply layouts O                                              4852ms         137.21mB      445.33mB     73.05mB      1542.39mB
    35   Apply layouts P                                              10190ms        9.52mB        454.87mB     230.89mB     1773.29mB
    36   Apply layouts Q                                              3813ms         12.38mB       467.27mB     2.84mB       1776.13mB
    37   Apply layouts R                                              7332ms         136.56mB      603.84mB     -82.43mB     1693.7mB
    38   Apply layouts S                                              10704ms        -211.73mB     392.12mB     125.95mB     1819.64mB
    39   Apply layouts T                                              6872ms         51.58mB       443.71mB     -26.41mB     1793.23mB
    40   Apply layouts U                                              4603ms         12.54mB       456.27mB     7.04mB       1800.27mB
    41   Apply layouts V                                              8463ms         213.45mB      669.73mB     148.36mB     1948.64mB
    42   Apply layouts W                                              9071ms         -109.39mB     560.36mB     -65.85mB     1882.79mB
    43   Apply layouts X                                              4962ms         4.61mB        564.99mB     0.94mB       1883.73mB
    44   Apply layouts Y                                              5460ms         -291.83mB     273.17mB     -139.1mB     1744.63mB
    45   Apply layouts Z                                              5002ms         3.97mB        277.16mB     0.67mB       1745.3mB
    46   Apply layouts 0-9.-_~!$&'()*+,;=:@                           5570ms         11.39mB       288.57mB     -32.51mB     1712.79mB
    47   Rewrite VA domains for the buildtype                         8696ms         0.91mB        289.5mB      65.41mB      1778.2mB
    48   Rewrite Drupal pages                                         0ms            0.01mB        289.54mB     0mB          1778.2mB
    49   Create Drupal debug page                                     5ms            2.89mB        292.44mB     2.59mB       1780.79mB
    50   Download Drupal assets                                       19ms           4.53mB        296.98mB     0.52mB       1781.31mB
    51   Download application assets                                  0ms            0.01mB        297mB        0mB          1781.31mB
    52   Create sitemap                                               228ms          -7.18mB       289.83mB     -3.88mB      1777.43mB
    53   Update robots.txt                                            0ms            0.01mB        289.85mB     0mB          1777.43mB
    54   Check for CMS URLs                                           4922ms         -5.57mB       284.3mB      -1.12mB      1776.32mB
    55   Parse a virtual DOM from every .html file and perform a...   143543ms       516.66mB      800.98mB     418.42mB     2194.73mB
    56   Ignore assets for build                                      11ms           3.14mB        804.14mB     0.49mB       2195.23mB

Peak RSS used: 1984.5mB
```
Up to the step before we add the debug info (Generate navigation), the memory usage is `565.65mB`. Which is almost 150 mB less memory than without the changes. Memory usage before the changes at this point tends to be around `706.17mB`. Total peak usage seemed to drop by `100 mB`.

**Results when tested on 48k nodes:**
Interestingly, the node process for staging ran out of heap when I kept `max-old-space-size` equal to `5000`, whereas the node process for the prod build succeeded. This is what happens in the builds without these changes as well. The memory increases didn't seem high after the plugin where debug info was added
```
Step 19 of 56 start: Add debug info to Drupal pages

[2021-06-14T17:12:52.959Z] Step 19 end [488ms]: Add debug info to Drupal pages

[2021-06-14T17:12:52.959Z] Starting memory: 2431.51mB heap, 5069.91mB rss

[2021-06-14T17:12:52.959Z] Ending memory: 2447.55mB heap, 5070.25mB rss

[2021-06-14T17:12:52.959Z] Deltas: 16.04mB heap, 0.34mB rss
```

Dev has similar memory stats for that plugin. I'm not sure if it's because staging is the last of the 3 builds that when memory usage gets too high, that node process is ended first to reserve memory. The good thing despite staging's node process ending is the memory usage up to the layouts are applied decreases with this approach. Heap and RSS usage decreased by 200 mB prior and even during applying layouts.

<details>
<summary>48k nodes before changes:</summary>

![Screen Shot 2021-06-14 at 10.54.00 AM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/590b37c3-5d9a-473d-a21d-8af0db5934fe)

</details>

<details>
<summary>48k nodes after changes:</summary>

![Screen Shot 2021-06-14 at 11.01.50 AM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/d45f39f3-c9ba-4848-98e1-2908c24ca814)

</details>

**Pros**
- Delays memory spike
- Keeps adding debug info in the Metalsmith build, so implementation is cleaner

**Cons**
- Still need to store debug info in the `files` object which still adds memory

**Comment by theodur** [comment] 2021-06-15 01:38
## Approach 2: Removing debug info after layouts are applied
Since we don’t need debug info after layouts are applied, we can try removing them from the files objects after the `Apply layouts` step. This can free up memory for later memory intensive steps like parsing the virtual DOM. 

**Local results:**
```

                                                              Step summary
  Step                          Description                           Time Elapsed   Heap Change   Total Heap   RSS Change   Total RSS

     0   Create symlink into vets-website for local development.      0ms            0.01mB        51.7mB       0mB          131.89mB
     1   Create React pages                                           2ms            0.2mB         51.93mB      0.04mB       131.94mB
     2   Get Drupal content                                           27998ms        216.9mB       268.84mB     547.55mB     679.49mB
     3   Add Drupal Prefix                                            50ms           0.37mB        269.23mB     1.63mB       681.12mB
     4   Create Outreach Assets Data                                  56ms           2.53mB        271.77mB     0.01mB       681.13mB
     5   Create "Resources and support" section of the website        342ms          74.96mB       346.74mB     3.18mB       684.31mB
     6   Create environment filter                                    6ms            0.56mB        347.31mB     0mB          684.32mB
     7   Add filenames for debugging                                  6ms            0.69mB        348.01mB     0.02mB       684.34mB
     8   Check collections                                            18ms           -5.44mB       342.58mB     0.05mB       684.39mB
     9   Group collections                                            3137ms         2.77mB        345.37mB     -59.7mB      624.69mB
    10   Reset left rail navigation menu levels                       10ms           2mB           347.38mB     0.01mB       624.7mB
    11   Add the date to filenames                                    90ms           13.04mB       360.43mB     1.04mB       625.75mB
    12   Add app assets                                               210ms          -16.49mB      343.95mB     -8.69mB      617.06mB
    13   Add content assets                                           65ms           -6.57mB       337.39mB     60.82mB      677.88mB
    14   Plug the content into the templates                          277ms          11.44mB       348.85mB     -10.85mB     667.03mB
    15   Translate the markdown to html                               20ms           2.08mB        350.94mB     0.13mB       667.16mB
    16   Add permalinks and change foo.md to foo/index.html           10065ms        -15.39mB      335.57mB     -4.93mB      662.24mB
    17   Create header and footer                                     73ms           4.16mB        339.75mB     0.03mB       656.27mB
    18   Generate navigation                                          2260ms         33.71mB       373.47mB     2.4mB        658.67mB
    19   Apply layouts A                                              8851ms         136.93mB      510.41mB     438.81mB     1097.48mB
    20   Apply layouts B                                              3989ms         -103.03mB     407.4mB      -105.53mB    991.96mB
    21   Apply layouts C                                              9129ms         163.4mB       570.83mB     294.09mB     1286.04mB
    22   Apply layouts D                                              4701ms         -72.65mB      498.2mB      -5.88mB      1280.16mB
    23   Apply layouts E                                              4076ms         19.37mB       517.59mB     -157.38mB    1122.78mB
    24   Apply layouts F                                              3356ms         124.37mB      641.97mB     91.93mB      1214.71mB
    25   Apply layouts G                                              3410ms         -262.44mB     379.55mB     -32.46mB     1182.24mB
    26   Apply layouts H                                              8153ms         5.7mB         385.26mB     149.62mB     1331.86mB
    27   Apply layouts I                                              3425ms         85.79mB       471.06mB     50.13mB      1382mB
    28   Apply layouts J                                              5641ms         122.3mB       593.38mB     -63.86mB     1318.13mB
    29   Apply layouts K                                              3862ms         -249.17mB     344.22mB     -50.75mB     1267.39mB
    30   Apply layouts L                                              7333ms         27.53mB       371.78mB     144.41mB     1411.8mB
    31   Apply layouts M                                              10669ms        253.97mB      625.77mB     322.16mB     1733.96mB
    32   Apply layouts N                                              5539ms         -244.57mB     381.21mB     -239.16mB    1494.8mB
    33   Apply layouts O                                              5012ms         138.43mB      519.65mB     79.83mB      1574.63mB
    34   Apply layouts P                                              10721ms        -8.56mB       511.1mB      287.94mB     1862.57mB
    35   Apply layouts Q                                              4228ms         -192.26mB     318.86mB     -254.31mB    1608.26mB
    36   Apply layouts R                                              7530ms         311.33mB      630.2mB      141.75mB     1750.01mB
    37   Apply layouts S                                              10563ms        -158.67mB     471.55mB     178.71mB     1928.72mB
    38   Apply layouts T                                              6558ms         67.03mB       538.6mB      -158.52mB    1770.2mB
    39   Apply layouts U                                              5067ms         6.67mB        545.28mB     -60.78mB     1709.42mB
    40   Apply layouts V                                              8576ms         162.36mB      707.66mB     234.66mB     1944.08mB
    41   Apply layouts W                                              8666ms         -125.26mB     582.42mB     -86.83mB     1857.25mB
    42   Apply layouts X                                              5389ms         4.55mB        586.98mB     0.85mB       1858.1mB
    43   Apply layouts Y                                              6055ms         -274.63mB     312.36mB     -128.98mB    1729.13mB
    44   Apply layouts Z                                              5028ms         3.92mB        316.29mB     0.88mB       1730.01mB
    45   Apply layouts 0-9.-_~!$&'()*+,;=:@                           5834ms         45.17mB       361.47mB     9.29mB       1739.29mB
    46   Remove Debug info                                            109ms          -144.32mB     217.17mB     -4.68mB      1734.61mB
    47   Rewrite VA domains for the buildtype                         9129ms         65.41mB       282.6mB      -12.84mB     1715.02mB
    48   Rewrite Drupal pages                                         0ms            0.01mB        282.64mB     0mB          1715.02mB
    49   Create Drupal debug page                                     6ms            2.96mB        285.61mB     2.59mB       1717.61mB
    50   Download Drupal assets                                       24ms           4.52mB        290.15mB     0.52mB       1718.14mB
    51   Download application assets                                  0ms            0.01mB        290.17mB     0mB          1718.14mB
    52   Create sitemap                                               247ms          -6.07mB       284.11mB     -3.14mB      1715mB
    53   Update robots.txt                                            0ms            0.01mB        284.13mB     0mB          1715mB
    54   Check for CMS URLs                                           4622ms         -52.94mB      231.2mB      -80.69mB     1634.3mB
    55   Parse a virtual DOM from every .html file and perform a...   144607ms       873.49mB      1104.7mB     163.59mB     1797.91mB
    56   Ignore assets for build                                      13ms           3.18mB        1107.9mB     0.48mB       1798.39mB

Peak RSS used: 1988.82mB
```

This seemed to decrease heap usage by nearly `150 mB` as seen in the `Remove Debug info` step in the build summary above. Although testing on 48k nodes with the current `max-old-space-size` of `5000`, I still ran out of memory during the `Apply layouts` step since the debug info is still stored in the `files` object.

**Pros**
- Decreases memory for later intensive steps in the build
- Minimal changes needed to the build

**Cons**
- Doesn't relieve memory used by storing debug info earlier in the build, which is still a problem with 48k nodes

**Comment by theodur** [comment] 2021-06-15 21:48
## Approach 3: Adding debug info to HTML pages on disk
This approach doesn’t store debug info in the files object, but rather directly modifies the HTML files on disk and stores them there after the Metalsmith build is finished. This avoids using memory for debug info during the build.

<details>
<summary>48k node results:</summary>

![Screen Shot 2021-06-15 at 1.50.11 PM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/700022d7-305c-46c3-a821-5c05af453047)
</details>

<details>
<summary>Local results after changes:</summary>

```
                                                              Step summary
  Step                          Description                           Time Elapsed   Heap Change   Total Heap   RSS Change   Total RSS

     0   Create symlink into vets-website for local development.      0ms            0.04mB        40.43mB      0.02mB       128.71mB
     1   Create React pages                                           2ms            0.18mB        40.63mB      0.02mB       128.75mB
     2   Get Drupal content                                           27799ms        227.6mB       268.24mB     415.93mB     544.68mB
     3   Add Drupal Prefix                                            36ms           0.09mB        268.35mB     2.02mB       546.7mB
     4   Create Outreach Assets Data                                  42ms           2.45mB        270.82mB     0.06mB       546.76mB
     5   Create "Resources and support" section of the website        193ms          31.63mB       302.45mB     16.57mB      563.33mB
     6   Create environment filter                                    4ms            0.56mB        303.02mB     0.01mB       563.34mB
     7   Add filenames for debugging                                  3ms            0.69mB        303.72mB     0mB          563.34mB
     8   Check collections                                            7ms            0.92mB        304.65mB     0.01mB       563.35mB
     9   Group collections                                            2823ms         13.56mB       318.23mB     1.71mB       565.05mB
    10   Reset left rail navigation menu levels                       7ms            -14.66mB      303.58mB     0.02mB       565.08mB
    11   Add the date to filenames                                    105ms          16.61mB       320.19mB     2.38mB       567.46mB
    12   Add app assets                                               244ms          -16.46mB      303.75mB     -5.2mB       562.27mB
    13   Add content assets                                           52ms           -6.55mB       297.22mB     60.82mB      623.1mB
    14   Plug the content into the templates                          295ms          11.17mB       308.4mB      -11.82mB     611.28mB
    15   Translate the markdown to html                               23ms           2.13mB        310.55mB     0.13mB       611.41mB
    16   Add permalinks and change foo.md to foo/index.html           9936ms         -15.33mB      295.24mB     -9.37mB      602.04mB
    17   Create header and footer                                     60ms           4.16mB        299.42mB     0.03mB       598.57mB
    18   Generate navigation                                          2099ms         33.67mB       333.11mB     5.23mB       603.8mB
    19   Apply layouts A                                              7205ms         591.84mB      924.96mB     557.59mB     1161.39mB
    20   Apply layouts B                                              3255ms         -422.91mB     502.07mB     -374.69mB    786.71mB
    21   Apply layouts C                                              6781ms         571.79mB      1073.88mB    582.28mB     1368.99mB
    22   Apply layouts D                                              3639ms         -534.32mB     539.58mB     -513.83mB    855.16mB
    23   Apply layouts E                                              2402ms         151.04mB      690.64mB     157.79mB     1012.95mB
    24   Apply layouts F                                              2039ms         84.18mB       774.83mB     91.31mB      1104.26mB
    25   Apply layouts G                                              1926ms         73.14mB       847.98mB     84.8mB       1189.06mB
    26   Apply layouts H                                              5934ms         -151.32mB     696.67mB     -126.2mB     1062.86mB
    27   Apply layouts I                                              1716ms         66.87mB       763.56mB     70.86mB      1133.73mB
    28   Apply layouts J                                              3465ms         -453.31mB     310.27mB     -168.88mB    964.85mB
    29   Apply layouts K                                              2001ms         94.65mB       404.94mB     11.09mB      975.94mB
    30   Apply layouts L                                              4714ms         348.08mB      753.04mB     179.71mB     1155.65mB
    31   Apply layouts M                                              7378ms         58.13mB       811.19mB     170.23mB     1325.89mB
    32   Apply layouts N                                              2562ms         121.58mB      932.78mB     57.17mB      1383.05mB
    33   Apply layouts O                                              2434ms         100.87mB      1033.66mB    105.8mB      1488.86mB
    34   Apply layouts P                                              6896ms         -238.86mB     794.82mB     -203.52mB    1285.34mB
    35   Apply layouts Q                                              1334ms         -2.56mB       792.28mB     1.33mB       1286.67mB
    36   Apply layouts R                                              4382ms         -302.14mB     490.15mB     -54.34mB     1232.34mB
    37   Apply layouts S                                              6770ms         466.92mB      957.09mB     269.58mB     1501.92mB
    38   Apply layouts T                                              3546ms         -506.51mB     450.6mB      -279.9mB     1222.02mB
    39   Apply layouts U                                              1497ms         2.58mB        453.19mB     1.51mB       1223.53mB
    40   Apply layouts V                                              4564ms         317.6mB       770.8mB      118.39mB     1341.91mB
    41   Apply layouts W                                              4751ms         -262.22mB     508.59mB     -11.74mB     1330.18mB
    42   Apply layouts X                                              1512ms         3.16mB        511.77mB     0.07mB       1330.25mB
    43   Apply layouts Y                                              1733ms         6.92mB        518.7mB      2.38mB       1332.63mB
    44   Apply layouts Z                                              1568ms         0.53mB        519.24mB     0.18mB       1332.8mB
    45   Apply layouts 0-9.-_~!$&'()*+,;=:@                           1808ms         48.72mB       567.98mB     48.11mB      1380.91mB
    46   Rewrite VA domains for the buildtype                         2758ms         -248.95mB     319.05mB     -334.67mB    1046.25mB
    47   Rewrite Drupal pages                                         0ms            0.01mB        319.07mB     0mB          1046.25mB
    48   Create Drupal debug page                                     8ms            2.89mB        321.98mB     2.59mB       1048.84mB
    49   Download Drupal assets                                       31ms           4.52mB        326.51mB     0.52mB       1049.36mB
    50   Download application assets                                  0ms            0.01mB        326.53mB     0mB          1049.36mB
    51   Create sitemap                                               349ms          -38.39mB      288.15mB     -43.42mB     1005.94mB
    52   Update robots.txt                                            0ms            0.01mB        288.18mB     0mB          1005.94mB
    53   Check for CMS URLs                                           1063ms         12.51mB       300.71mB     6.82mB       1012.77mB
    54   Parse a virtual DOM from every .html file and perform a...   64260ms        360.58mB      661.31mB     488.73mB     1501.49mB
    55   Ignore assets for build                                      12ms           3.18mB        664.51mB     0.48mB       1501.97mB

Peak RSS used: 1562.64mB

Adding debug info to Drupal pages...
The Metalsmith build has completed.
✨  Done in 239.91s.
```

</details>

<details>
<summary>Local results before changes</summary>

```
                                                              Step summary
  Step                          Description                           Time Elapsed   Heap Change   Total Heap   RSS Change   Total RSS

     0   Create symlink into vets-website for local development.      0ms            0.01mB        41.65mB      0mB          133.25mB
     1   Create React pages                                           2ms            0.18mB        41.86mB      0.03mB       133.29mB
     2   Get Drupal content                                           23399ms        226.67mB      268.54mB     472.26mB     605.55mB
     3   Add Drupal Prefix                                            37ms           0.36mB        268.92mB     1.32mB       606.87mB
     4   Create Outreach Assets Data                                  41ms           2.44mB        271.37mB     0mB          606.87mB
     5   Create "Resources and support" section of the website        264ms          74.96mB       346.34mB     10.16mB      617.04mB
     6   Create environment filter                                    6ms            0.56mB        346.91mB     0.02mB       617.06mB
     7   Add filenames for debugging                                  6ms            0.69mB        347.61mB     0mB          617.06mB
     8   Check collections                                            22ms           -5.48mB       342.15mB     8.54mB       625.6mB
     9   Group collections                                            3545ms         14.92mB       357.08mB     -33.76mB     591.84mB
    10   Reset left rail navigation menu levels                       11ms           1.98mB        359.08mB     0mB          591.84mB
    11   Add the date to filenames                                    102ms          1.9mB         360.99mB     0.43mB       592.27mB
    12   Add app assets                                               230ms          -17.07mB      343.93mB     3.2mB        595.48mB
    13   Add content assets                                           51ms           -6.57mB       337.38mB     60.82mB      656.3mB
    14   Plug the content into the templates                          247ms          1.77mB        339.16mB     -9.91mB      646.4mB
    15   Translate the markdown to html                               16ms           2.08mB        341.25mB     0.09mB       646.48mB
    16   Add permalinks and change foo.md to foo/index.html           9201ms         -3.7mB        337.57mB     0.84mB       647.32mB
    17   Create header and footer                                     53ms           4.16mB        341.74mB     0.02mB       647.35mB
    18   Generate navigation                                          1959ms         33.81mB       375.56mB     2.44mB       649.79mB
    19   Apply layouts A                                              9118ms         284.82mB      660.39mB     671.04mB     1320.83mB
    20   Apply layouts B                                              4073ms         -65.16mB      595.25mB     -321.27mB    999.56mB
    21   Apply layouts C                                              9403ms         0.18mB        595.45mB     371.99mB     1371.55mB
    22   Apply layouts D                                              4937ms         -67.43mB      528.03mB     -64mB        1307.56mB
    23   Apply layouts E                                              4085ms         -39.08mB      488.97mB     -64.61mB     1242.95mB
    24   Apply layouts F                                              3269ms         110.42mB      599.4mB      58.98mB      1301.93mB
    25   Apply layouts G                                              3549ms         -228.2mB      371.21mB     -127.01mB    1174.92mB
    26   Apply layouts H                                              7787ms         11.58mB       382.82mB     160.88mB     1335.8mB
    27   Apply layouts I                                              3065ms         82.6mB        465.44mB     50.14mB      1385.94mB
    28   Apply layouts J                                              5315ms         125.38mB      590.83mB     -65.85mB     1320.09mB
    29   Apply layouts K                                              3751ms         -256.5mB      334.35mB     -50.25mB     1269.84mB
    30   Apply layouts L                                              7621ms         13.56mB       347.93mB     120.3mB      1390.14mB
    31   Apply layouts M                                              10641ms        266.12mB      614.08mB     345.03mB     1735.17mB
    32   Apply layouts N                                              5287ms         -273.21mB     340.89mB     -245.91mB    1489.26mB
    33   Apply layouts O                                              4788ms         128.86mB      469.76mB     79.53mB      1568.79mB
    34   Apply layouts P                                              10000ms        30.57mB       500.34mB     244.87mB     1813.66mB
    35   Apply layouts Q                                              4076ms         -1.07mB       499.28mB     -78.58mB     1735.08mB
    36   Apply layouts R                                              7954ms         140.09mB      639.38mB     -70.76mB     1664.32mB
    37   Apply layouts S                                              10786ms        -195.77mB     443.63mB     119.34mB     1783.67mB
    38   Apply layouts T                                              6810ms         68.5mB        512.14mB     -31.87mB     1751.8mB
    39   Apply layouts U                                              4652ms         10.62mB       522.78mB     6.88mB       1758.68mB
    40   Apply layouts V                                              9633ms         187.8mB       710.59mB     164.38mB     1923.06mB
    41   Apply layouts W                                              8837ms         -99.65mB      610.96mB     -81.91mB     1841.14mB
    42   Apply layouts X                                              5156ms         4.46mB        615.43mB     0.35mB       1841.5mB
    43   Apply layouts Y                                              5632ms         -301.56mB     313.89mB     -154.65mB    1686.85mB
    44   Apply layouts Z                                              4966ms         3.48mB        317.39mB     0.68mB       1687.52mB
    45   Apply layouts 0-9.-_~!$&'()*+,;=:@                           5816ms         43.75mB       361.16mB     34.52mB      1722.04mB
    46   Rewrite VA domains for the buildtype                         8456ms         0.13mB        361.32mB     82.3mB       1804.34mB
    47   Rewrite Drupal pages                                         0ms            0.01mB        361.35mB     0mB          1804.34mB
    48   Create Drupal debug page                                     7ms            2.96mB        364.33mB     2.59mB       1806.93mB
    49   Download Drupal assets                                       22ms           4.53mB        368.87mB     0.53mB       1807.45mB
    50   Download application assets                                  0ms            0.01mB        368.89mB     0mB          1807.45mB
    51   Create sitemap                                               245ms          -6.18mB       362.72mB     -2.41mB      1805.04mB
    52   Update robots.txt                                            0ms            0.01mB        362.74mB     0mB          1805.04mB
    53   Check for CMS URLs                                           4806ms         -19.12mB      343.63mB     -14.73mB     1790.31mB
    54   Parse a virtual DOM from every .html file and perform a...   144577ms       439.38mB      783.03mB     332.96mB     2123.27mB
    55   Ignore assets for build                                      11ms           3.16mB        786.22mB     0.49mB       2123.76mB

Peak RSS used: 2144.55mB

The Metalsmith build has completed.
✨  Done in 373.85s.
```

</details>

This approach of course has the lowest memory usage out of the group since we aren't storing debug info in the `files` object. This decreased peak memory usage by `550mB-600mB` locally. Interestingly, this also reduced total time of the entire build which includes adding the debug info at the end of the Metalsmith build. Locally before the changes, the total build time was `373.85s`. As seen in the summary above, the total build time after the changes was `239.91s`. I believe this has to do with the `Apply layouts` steps being shorter since we aren't dealing with debug info.

When testing on 48k nodes, the build didn't run out of heap which is good. I was able to get a successful build with these changes. 

Also contributing to the shorter build time is the Metalsmith build modifies domain in the DOM, which includes debug info. So the domain names in the debug info are being updated from `www.va.gov` to whatever the environment is, i.e. `staging.va.gov`. This doesn't happen with the changes to add debug info to the HTML files on disk since domain rewriting isn't taking place because debug info isn't applied to the file DOMs during the Metalsmith build. Not sure if this is an issue, given the debug info is being stored on disk exactly how it comes from Drupal. It may not be worth modifying domain names in the debug info, especially if we want to keep consistency with the structure of data from Drupal in the debug info. I'm not sure if modifying domain names in the debug info was even desired behavior. It may have not been noticed up to this point.

**Pros:**
- Uses minimal memory for debug info since we aren't storing them in the `files` object
- 48k nodes is successful with just these changes.

**Cons:**
- Goes outside the Metalsmith build to add debug info to HTML files. Maybe not as clean as adding debug info in the Metalsmith build

**Comment by alexandec** [comment] 2021-06-15 23:47
Thanks for working on this Theo. Love the thorough benchmarking. Saving over 2 minutes on the current build is excellent!

One thing that's interesting about this finding is that one might think reading each file from disk, adding debug info, writing it back to disk, and copying it over the original would be slower than just keeping everything in memory. But as you mention, the Apply Layouts and Parse a Virtual DOM steps are both significantly faster without the debugging info in there. That overshadows any additional time required to read and write the files.

I agree that performing this task outside of Metalsmith adds a bit of complexity. But I'm not too concerned about it. If anything I'm happy to move tasks outside Metalsmith when they give us big wins in memory use or build time. This does both. @timwright12 do you agree? Any possible issues with this change?

There's the potential for even more speed by reading and writing files in parallel. How much potential probably depends on disk performance. But NodeJS should be able to handle it well. We'd have to check how long it takes to add all the debug info to see if it's worth optimizing. Might not matter much at the current node count, or even at 48k.

I'm guessing the URL differences in the debugging info won't be an issue. But I'd recommend checking in the #content-release-engineering channel just to be sure. If the engineers there don't care, there's no need to spend extra time modifying the URLs.

**Comment by theodur** [comment] 2021-06-17 16:22
After updating approach 3 to have the build script to read/write debug info in parallel, local time improvements were minimal compared to the non-parallel reading/writing. But testing in CI on our current node count seemed to shed off ~20 seconds, which saves even more time in the build. Testing parallelizing read/write debug info on 48k nodes seemed to save a couple of minutes as well.

Overall, approach 3 reduces the build time on our current node by over 2 minutes, and reduces peak memory usage by almost `500mB`. On 48k nodes, the build is able to finish without running out of memory with this approach, which is a good sign. I agree that this approach seems to be the best option. 

Also confirmed with content release engineers that the hostname not being rewritten in debug info isn't a problem. Slack thread: https://dsva.slack.com/archives/C01512KN35G/p1623865747147600

**Comment by theodur** [comment] 2021-06-17 16:25
Side note, something interesting happened when testing on 48k nodes during one instance. The pipeline ran out of memory at the Prearchive step. I wasn't able to reproduce this when re-running multiple times, so it may have been a fluke, but still something to keep an eye on if it shows up in the future.
![Screen Shot 2021-06-17 at 9.19.30 AM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/f5463af9-0684-40c8-877d-b4072bd0773d)

**Comment by theodur** [comment] 2021-06-22 16:39
The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/263) for this ticket has been merged. I'll monitor the dev and staging deploys to make sure everything looks good before closing this out.

**Comment by theodur** [comment] 2021-06-22 17:08
The dev and staging deploys were successful, and everything is running smoothly ✅.

**Closed by theodur** 2021-06-22 17:08 UTC
Labels: tools-fe
