### ISSUE TITLE
PW intake: Correct external link behavior based on updates to design standards

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#81506] opened 2024-04-24 14:11 UTC
### Describe your request

A decision was made to change the behavior for handling external links within the design system.  The change to the standards direction is documented in [issue #1680 within the design system repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1680). 
* New: All links open in same tab unless a user will lose progress on a form or lose a session
* Old: Links open in a new tab unless they'll lose progress / session, OR unless the link is from a specified VA subdomain 

Previously the content styleguide that required certain sub-domains to open in a new tab ((listed [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1680)):

Content example links point to CMS content search with Published nodes that link to these subdomains: 
- 'myhealth.va.gov', - [content examples](https://prod.cms.va.gov/admin/content/audit/search?search=myhealth.va.gov&title=&etype_op=or&etype=All&ms=All&published=1&section=)
- 'ebenefits.va.gov', - no content examples
- 'www.accesstocare.va.gov', - 1 example: https://www.va.gov/pacific-islands-health-care/stories/directors-message-july-22-2022/
- 'www.gibill.va.gov/wave', - no content examples
- 'www.blogs.va.gov', - [content examples](https://prod.cms.va.gov/admin/content/audit/search?search=blogs.va.gov&title=&etype_op=or&etype=All&ms=All&published=1&section=)
- 'www.data.va.gov',  - no content examples
- 'mobile.va.gov', - [content examples](https://prod.cms.va.gov/admin/content/audit/search?search=mobile.va.gov&title=&etype_op=or&etype=All&ms=All&published=1&section=)
- 'www.oit.va.gov'  - no content examples

There is code in content-build that says: for a specific set of subdomains, force any links to those subdomains to open in a new tab: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js

We need to remove the rule(s) / code that enable the new tab behavior, so links to these subdomains open in the same tab.

### Time constraints / launch deadlines

no hard timing

### Your OCTODE product owner

@davidconlon @mnorthuis

## Acceptance Criteria

- [x] Links follow [Design System guidance](https://design.va.gov/content-style-guide/links#va-sub-domain-exceptions-that-open-in-a-new-tab-or-window)
- [x] Take performance into consideration when making this change to ensure it doesn't degrade.

**Comment by jilladams** [comment] 2024-05-01 22:41
Updated ticket body: 
> There is code in content-build that says: for a specific set of subdomains, force any links to those subdomains to open in a new tab: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js

**Comment by FranECross** [comment] 2024-05-07 18:35
how to get to content audit: log into drupal (tabs or dropdown); click hamburger; click content audit tools; content search in next tab/dropdown.

**Comment by jilladams** [comment] 2024-05-08 21:37
While chasing a Facilities new tab issue, I randomly just saw that this subdomain/new tab logic was originally created within a commit labeled "reduce memory consumption on content-build": https://github.com/department-of-veterans-affairs/content-build/commit/29bfb339a0a40e9ed4190502cace4f02c5456411. (From Nick Sullivan in 2021)

Ticket ID was 15601, but that doesn't map to a relevant thing in either va.gov-cms or va.gov-team, so might go back to the vets-gov days?  Meaning: I can't find the history of why this kind of code change mattered for memory. 

That makes me nervous, though it's hard to image how opening things in same tab vs. new tab could affect memory consumption? Maybe just rolled into a different commit message / squashing or something. I feel inclined to add an AC to think about memory when we make this change, but I don't know how we would measure memory consumption.  Flagging for @dsasser / @randimays awareness, and re-adding Needs refining label just in case. (FYI @FranECross )

**Comment by jilladams** [comment] 2024-05-08 21:45
Also noting mostly for my own sake: I've been looking at that content-build file as _only_ applying to subdomains. But! further down in file, there's more logic that says: if `data-same-tab` isn't set, open in new tab. 

So: fixing this file to stop new tabs will very likely solve far more than just the subdomain list in ticket body: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js#L49

**Comment by FranECross** [comment] 2024-05-08 21:46
@jilladams Thanks so much for this history and suggestion of additional AC. I've added!

**Comment by jilladams** [comment] 2024-05-17 23:13
@FranECross we missed this in Sprint 4 planning. I'm going ahead and tagging into Sprint 5 so we don't lose it for next spring planning. Do you have a Draft sprint plan started for Sprint 5 that we could put it in for visibility?

**Comment by FranECross** [comment] 2024-05-20 17:12
@jilladams Thanks for catching this one! I just created a Sprint 5 Plan draft and added this to it. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18164

**Comment by randimays** [comment] 2024-05-28 21:07
Pulling in as stretch (at the verrry end of Sprint 4)

**Comment by randimays** [comment] 2024-05-28 22:05
I did some spelunking on the history of this code; my findings are below.

## PR that "created" the update-external-links file
https://github.com/department-of-veterans-affairs/vets-website/pull/15601

This PR appeared to create the [update-external-links.js](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js) file. But it didn't; it moved the file (Github visually treats moving a file like deleting it and creating a new file). The contents of the file were unchanged. `15601` is the number of the PR and doesn't correspond to a ticket.

**Note**: this work took place before `vets-website` and `content-build` were separate repositories. Notice the PR linked above is in `vets-website` but refers to code that is in `content-build` today. Spelunking got a little tricky.

The tickets related to this performance work are here:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/18396
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/13821

### Quick summary of the tickets
As the Drupal content grew, the PW team at the time proposed and implemented solutions for optimizing HTML-parsing per-template for some performance gains on the content build.

Here's what the content build used to do for HTML-parsing (before these performance enhancements):
- Grab all Drupal templates at once; store them in memory
- Use plugins to transform their contents (manipulate DOM, etc.)
- Remove all templates from memory

Here's what the PW team did to enhance performance:
- Grab one Drupal template at a time from the list; store it in memory
- Use plugins to transform its contents
- Remove it from memory, grab the next template
- Rinse/repeat

## So what you're trying to say is...
The external links file has a nominal impact on performance. We should be all clear to change or remove it for this ticket and not worry about that.

## When was this file created?
https://github.com/department-of-veterans-affairs/vets-website/pull/8906

Here's the PR where this file was created back in November 2018. Unfortunately, it links to a [ticket in the `vets.gov-team`](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13596) repository that now 404s.

Description in the PR:
> This is slightly different from the attached issue, but fixing the links in the build is easier than spitting out a ton of errors and forcing people to fix them manually. Plus, this makes it easier on people creating links in Markdown.

It seems like this PR was intended to more widely address specific editor-controlled issues with incoming links from external domains. I'm guessing the incoming links were inconsistent in their attributes (`target`, `rel`, etc.) and it caused build errors. 

## Phew, ok.
Given all of the above, I'm going to take a close look at the code and make the adjustments we need without worrying about performance impact.

**Comment by FranECross** [comment] 2024-05-28 22:34
### 🕵🏽‍♀️ You are an amazing sleuth, @randimays !!

**Comment by randimays** [comment] 2024-05-29 15:04
@mnorthuis @FranECross @jilladams This might be covered in conversations somewhere but I didn't see it here. We don't want to open in the same window if the user could lose progress or data. What if one of these links for a subdomain is on a page where a user would lose progress?

I'm not sure if there are any links coming from the CMS that would cause a user to lose progress or data. I guess my broader question is: how are we planning to handle those, if they exist?

**Comment by randimays** [comment] 2024-05-29 15:33
@FranECross @jilladams Is this ticket intended to address **all** links in Public Websites products on Drupal and React pages? Or do we have tickets for that work already?

**Comment by mnorthuis** [comment] 2024-05-29 17:53
@randimays in that scenario it really doesn't matter if its an internal link, subdomain link, or external link. Guidance is for teams to avoid placing links somewhere that creates a way for a user to leave a critical flow. If that cannot be avoided for some reason, then they can override and force a new tab with proper content/labeling.  

This should not be an issue inside CMS given it does not house any flows or dynamic pages, which is where this scenario would potentially happen.

**Comment by jilladams** [comment] 2024-05-30 16:43
@mnorthuis question: Just reread https://design.va.gov/content-style-guide/links#linking-to-external-sites and the guidance doesn't actually mention anything about either the new or the old guidance anymore: 
* New: All links open in same tab unless a user will lose progress on a form or lose a session
* Old: Links open in a new tab unless they'll lose progress / session, OR unless the link is from a specified VA subdomain

Is that wrong? Can you verify the "new" guidance is still what we're aiming for here, and/or clarify why it's not publicly listed any longer in the style guide?

**Comment by mnorthuis** [comment] 2024-05-30 16:47
The content team removed the behavior guidance from the content style guide and only refers to the content direction.  The link behavior is found with the [link component ](https://design.va.gov/components/link/) and references the new guidance. 

It might be helpful for them to link to the link component for implementation and behavior guidance.  I'll talk with them about that.

**Comment by randimays** [comment] 2024-05-30 17:18
We had a huddle this morning to be sure we understand the technical impact of making changes to this file. Confirmed understanding with @jtmst and posted a summary in this Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1717089115627859

**Comment by randimays** [comment] 2024-05-30 19:17
Draft PR posted: https://github.com/department-of-veterans-affairs/content-build/pull/2110 I have tested the affected links with prod content locally and they are behaving as expected (opening in the same tab).

We are giving VFS teams some time to ensure our changes will not adversely impact their applications; planning to merge this (barring no other issues) during the week of 6/3.

**Comment by FranECross** [comment] 2024-05-30 21:57
[Slack message](https://dsva.slack.com/archives/CE4304QPK/p1717097782458959) posted to VFS-all-teams asking folks to review the PR and determine if there will be any ill-effects to their features/products.

**Comment by randimays** [comment] 2024-06-03 19:28
@FranECross I did an audit of the links across PW products that **currently have new tab behavior**: https://docs.google.com/spreadsheets/d/1V8FVt8Kx2L0eNFIoiAqr1HWwH9DXqusVuskj9wEtyAU/edit?usp=sharing

In the "REMOVE new tab behavior" column, I made my best guess as to whether we should **remove** the new tab behavior or if it should stay. There are a couple on the Events tab that I'm not sure about. If I thought the new tab behavior should stay, I indicated whether the "(opens in a new tab)" text needs to be added to that link.

Could you please review the spreadsheet and see if my guesses are correct per the DST standards?

CC @laflannery @jilladams

**Comment by FranECross** [comment] 2024-06-03 21:14
@randimays Thanks so much for the audit and spreadsheet! I'll review and then comment back here when done.

**Comment by FranECross** [comment] 2024-06-07 18:08
@randimays I've completed review of the spreadsheet (thanks for the great info!), and as we chatted about, will create a new ticket for the actual changes to link behavior. I added notes to the Events tab, and changed the color of all other tabs to green, indicating I agree with your determinations.

**Comment by laflannery** [comment] 2024-06-07 18:19
@randimays and @FranECross I just looked at this and wanted to note that the assumption here is incorrect:

> [2024-06-07 - Fran] This should continue to open in a new tab so the user doesn't lose their search results. **Currently, Google maps opens in a new tab, which is the correct behavior going forward.**

Google maps will NOT be opening in a new tab going forward unless it is part of a process or flow. On Vet Center and VAMC pages ([for example](https://www.va.gov/boston-vet-center/)), these will need to be updated to open in the same tab to fit the new guidance.

I would say the links on events should act the same way.

Also, as a note for the future, if any link opens in a new tab it MUST have the `opens in a new tab` text indication.

**Comment by FranECross** [comment] 2024-06-07 18:33
@laflannery I'd love to double-check with Mikki about google maps. Doesn't that seem like it would be super annoying if someone is searching for events and wants to attend several, but google maps takes over the page and they lose their search, or close Google maps not realizing they're closing VA.gov as well?

**Comment by laflannery** [comment] 2024-06-07 18:35
Tbh I would say that's the case with any external link, that's typically why they do open in a new tab...

**Comment by FranECross** [comment] 2024-06-07 18:47
@mnorthuis Quick question about the link guidance - I'll give one example for my question. Currently, in [Events](https://www.va.gov/outreach-and-events/events/), when  user searches for events, finds one they're interested in, then clicks the 'Get directions on Google Maps' link, it opens in a new tab, which I think is great behavior so that they don't lose their search results. They also might not realize Google maps took over VA.gov, and instead of pressing the back browser button, they close Google and have to then reopen VA.gov, find Events, and redo their search. Shouldn't we continue to open in a new tab in cases like this? TIA! cc @randimays @laflannery

**Comment by FranECross** [comment] 2024-06-10 19:01
@mnorthuis Thank you for the explanation and guidance!

**Comment by FranECross** [comment] 2024-06-10 19:05
@randimays @laflannery Just closing the loop that I updated my note and the toggles on the spreadsheet for Events. 

[2024-06-10 - Fran] Confirmed with Mikki that the new tab behavior should be removed, and Google Maps should open in the same tab/browser window.

**Comment by randimays** [comment] 2024-06-11 19:12
Successfully validated the below URLs in production:

- `/northern-california-health-care/locations/mcclellan-va-clinic/` (myhealth.va.gov)
- `/pacific-islands-health-care/stories/directors-message-july-22-2022/` (accesstocare.va.gov)
- `/northport-health-care/stories/music-as-medicine-for-veterans/` (blogs.va.gov)
- `/central-iowa-health-care/programs/` (mobile.va.gov)

Reminder that the other URLs that were in the plugin do not have prod content examples:

- ebenefits.va.gov
- www.gibill.va.gov/wave
- www.data.va.gov
- www.oit.va.gov
- ethics.va.gov

Confirming this ticket was only for removing the content-build plugin that adds new tab behavior to specific domains. Any other "new tab removal" work will be part of this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18287

Closing as complete.

**Closed by randimays** 2024-06-11 19:12 UTC
Labels: Public Websites, VA.gov frontend, Sprint 5
