### ISSUE TITLE
[FE] Build 'Need more help' LC page component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14329] opened 2020-10-02 17:03 UTC
**Related CMS ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2970**

## Issue Description
_Place holder for FE build for "Need more Help" page component_

### Frontend
- [ ] Component built
### Content
- [ ] Sample content added

## Acceptance Criteria
TBD

## Planning Considerations
- Default is the MyVA 311 helpdesk
- Author can change to benefit hub if they choose
- FYI: Going into Google Analytics (GA)

**Comment by kelsonic** [comment] 2020-10-08 15:39
Design:

![image](https://user-images.githubusercontent.com/12773166/95481403-34067380-094a-11eb-91d3-619de99b991a.png)

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-About.png

**Comment by kelsonic** [comment] 2020-10-09 16:45
Hey @oksana-c I'm attempting to draft the graphql query for this `Need more help?` component. It seems like that info is coming from the benefit hubs:

![image](https://user-images.githubusercontent.com/12773166/95609366-cdea2100-0a1b-11eb-9653-b5db7e524054.png)

So, just to confirm, It looks like there can be more than 1 benefit hub per template, so we would iterate through each benefit hub and then subsequently iterate through each's support services, and for each support service show the following:

1) the fieldOffice's `fieldMetaTitle` for `National Cemetery Scheduling Office` in the [image above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14329#issuecomment-705654203)
2) the fieldPhoneNumber for `800-535-1117` in the image above
3) the fieldLink's `url.path` for `tel:8005351117` in the link

CC @ncksllvn

**Comment by kelsonic** [comment] 2020-10-13 18:10
Awaiting above comment's confirmation before implementation 🙂

**Comment by oksana-c** [comment] 2020-10-14 18:19
@kelsonic , here's some notes:

* fieldRelatedBenefitHubs cardinality is single. There can only be one hub per template. this requirement has changed about a week ago (was unlimited cardinality originally) and the work to switch to single was deployed last friday. So at the time of your writing the field still had unlimited cardinality, now it is single.
* fieldSupportServices under fieldRelatedBenefitHubs is unlimited cardinality, so yes, there can be multiple contacts.
* contact fields:
    * `title` - to generate the label for the contact
    * `fieldPhoneNumber` - for a number
    * `fieldLink` - for the link

`title` field seems empty now though. @kelsonic can you refresh the query and check if `title` is coming through?

**Comment by kelsonic** [comment] 2020-10-14 20:13
`title` seems to be empty still:

![Uploading image.png…]()

**Comment by oksana-c** [comment] 2020-10-15 10:43
@kelsonic sorry, I should have looked more closely. Support Service node title is available on the node root level, not thru the fieldLink. see screenshot below
<img width="716" alt="Screen Shot 2020-10-15 at 4 38 59 AM" src="https://user-images.githubusercontent.com/16477724/96113100-e1284100-0ea0-11eb-8791-25d93c484b2b.png">

**Comment by kelsonic** [comment] 2020-10-16 16:15
PR merged, following today's deployment it will be ready for validation at http://preview-prod.vfs.va.gov/preview?nodeId=6899

**Comment by jenniferlee-dsva** [comment] 2020-10-22 14:08
I've been commenting on this OTHER ticket which appears to be a duplicate of this one. @brianalloyd  can we consolidate or get rid of one? :-/  

@kelsonic - Oksana commented here. She thinks the bug I discovered is a FE issue: https://dsva.slack.com/archives/C0173CAJ7A6/p1603317885423900

**Comment by brianalloyd** [comment] 2020-10-22 14:49
@jenniferlee-dsva the other ticket is for 'content' add which is a supporting ticket to this FE Build ticket which are rolling up into the 'Need more help' EPIC.  The above ticket was created by Oksana in support of CMS build requirements and not on our LC board.  Let me know if I'm missing something, thanks.

**Comment by kelsonic** [comment] 2020-10-22 15:42
Need to filter for duplicate support service links for Need more help within each benefit hub that's associated with a template, you can read more here: https://dsva.slack.com/archives/C0173CAJ7A6/p1603376451439800?thread_ts=1603317885.423900&cid=C0173CAJ7A6 moved back into current sprint

**Comment by jenniferlee-dsva** [comment] 2020-10-29 14:27
Validated and closing.

**Closed by jenniferlee-dsva** 2020-10-29 14:27 UTC
Labels: frontend, planned-work, vsa, vsa-public-websites
