### ISSUE TITLE
AWS access for Patrick Arthur

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#41701] opened 2022-05-20 15:36 UTC
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Patrick Arthur

### Your Email

patrick.arthur@accenturefederal.com

### Your Team, Role, and Company

Ruby on Rails Dev legacy edu

### Product Manager (PM) name and email

Abe Blanco abelardo.blanco@accenturefederal.com

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Desired AWS Access

I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

### Access Expiration

10/01/2022

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by mrblanco1** [comment] 2022-05-23 20:31
Hello! Can we get an update on this request please?

Thanks!

**Comment by iriteshp** [comment] 2022-05-23 20:33
@PJart is in the VFS Team roster.

**Comment by iriteshp** [comment] 2022-05-23 20:34
For AWS Access
User: Patrick Arthur
COR: Other
VOR: Alexa Elliot
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no
Approvers will check with your VOR on your EQIP status.

**Comment by jbritt1** [comment] 2022-05-23 20:38
@td-usds, this is a request for production ssm access like we have loaned out in the past. Do you approve?

**Comment by ph-One** [comment] 2022-05-23 20:58
@PJart It looks like this is a reoccurring request. In the future, can you please note that in the ticket (and even link to previous requests.) It will help speed things up for all parties. Not every team/individual has that context. Thanks

Previous requests:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37086
https://github.com/department-of-veterans-affairs/va.gov-team/issues/36104

**Comment by td-usds** [comment] 2022-05-26 11:59
As per #36104, I'll use Doris Lin as COR, is that still accurate?

**Comment by td-usds** [comment] 2022-05-26 12:00
Reached out to VOR

**Comment by mrblanco1** [comment] 2022-05-26 13:59
COR is Matt Self.

**Comment by td-usds** [comment] 2022-05-31 13:01
VOR Confirmed eQIP;
Before I approve: @PJart: Is there a way to shorten the duration of your access elevation? It currently asks for elevation until 2022-OCT-01 which is rather long for just intermittent access. Can you advise?

**Comment by PJart** [comment] 2022-05-31 13:09
How long would you suggest?

**Comment by td-usds** [comment] 2022-05-31 13:20
> How long would you suggest?

Would starting with 90 days work?

**Comment by PJart** [comment] 2022-05-31 13:21
Sure

**Comment by td-usds** [comment] 2022-05-31 13:24
Approved for initial 90 days

**Comment by jbritt1** [comment] 2022-05-31 13:26
Pull request opened, will set a reminder once approved/applied/merged.

**Comment by jbritt1** [comment] 2022-05-31 14:27
Access granted, reminder set (see artifact below). Closing.

![image](https://user-images.githubusercontent.com/56260532/171197951-9a29a6f4-4ad6-4439-a982-03a50b0af821.png)

**Closed by jbritt1** 2022-05-31 14:27 UTC
Labels: operations, external-request, infrastructure, ops-access-request, infrastructure-request

**Comment by rmtolmach** [comment] 2022-08-29 13:34
@PJart do you still need the extra SSM prod access or can we revoke it?

**Comment by PJart** [comment] 2022-08-29 14:26
I still need it until the end of the month

**Comment by rmtolmach** [comment] 2022-08-29 15:45
@td-usds Access has been requested to be extended until the end of August. I will follow the new flow for alerting a PO, outlined here: https://dsva.slack.com/archives/CJRQ85PQB/p1660756788302119

**Comment by PJart** [comment] 2022-08-29 16:04
I need until the end of September

**Comment by td-usds** [comment] 2022-08-29 17:05
Extension until End-of-Day 2022-09-30 approved

**Comment by rmtolmach** [comment] 2022-08-29 17:14
Reminder set in the internal Infrastructure to remove access at EOD 9/30
<img width="603" alt="image" src="https://user-images.githubusercontent.com/10993987/187256741-6be15e71-c811-4fc4-baed-f33811523e5a.png">
