### ISSUE TITLE
Education Application: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52704] opened 2023-01-27 18:19 UTC
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [ ] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by cesaresantiago** [comment] 2023-02-01 20:07
@laineymajor : Per our Slack discussion, let's close this as a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/52707

**Closed by cesaresantiago** 2023-02-01 20:07 UTC
Labels: my-education-benefits, platform-tech-team-1
