### ISSUE TITLE
Technical Discovery: Make GitHub Actions source of truth/blocking

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#28968] opened 2021-08-19 17:09 UTC
## Details 

To complete our release of GitHub Actions, we must make it the source of truth for pipeline steps and make it blocking. 

Everything in the build pipeline for vets-website and content-build should be in GitHub Actions: 
* Except for Review Instances
* Up to the point of uploading to S3 — the deploy job itself should remain unchanged

This ticket is meant for discovering the technical steps to make the change, which will complete our release of GHA. 

## Definition of Done 

- [ ] Recommendation documented here
- [ ] New tickets created for completion of work

**Comment by ndsprinkle** [comment] 2021-08-23 15:19
Copying Eugene's original release plan from slack here:

1. Complete and release daily deploy workflow for dev.
   - Prepare the GHA build status check to be ready for replacing Jenkins daily deploy.
   - Maybe log GHA status for now for testing.
   - Monitor for a week in dev.

2. Switch the environment for daily deploy workflow to prod.
   - Turn off the schedule for Jenkins daily auto-deploy.
   - For failures related to GHA configuration, manually trigger deploy via Jenkins.
   - For failures related to failing commit statuses, manually trigger deploy via GHA dispatch.
   - Make sure GHA daily deploy uses the same build status that Jenkins uses.

3. Merge in consolidated GHA CI workflow (no archive or deploy).
   - Announcement few days ahead of this:
       - This will resemble most of the final pipeline.
       - This is being merged for testing before officially replacing Jenkins.
       - No impact to current workflow other than more content in commit and PR statuses.
   - Monitor for a week to identify any scaling issues with self-hosted runners.
   - Prepare separate PR to replace Jenkins with GHA:
       - Includes the archive, deploys to dev/staging, and Jenkins trigger (for review instances).
       - Removes everything from Jenkins pipeline except for review instances.

4. Write documentation and provide training.
   - Schedule training session.
   - Present both a week before replacing Jenkins.

5. Merge PR to replace Jenkins with GHA.
   - Wait until GHA daily deploy to prod is confirmed to be working.
   - Confirm that changes are getting deployed to dev/staging when merged to master.
   - Switch daily deploy workflow to check for GHA status.

**Comment by ndsprinkle** [comment] 2021-08-24 12:23
@meganhkelley @oseasmoran73 Sorry in advance for my confusion. I spoke to Eugene and he gave me a ton of information, but he is under the impression that the deploy to production functionality would still be moved to GHAs. What is the reason that the new plan is to leave the deploy to production functionality in Jenkins?

**Comment by ndsprinkle** [comment] 2021-08-24 12:29
In his own words: "I was still thinking GHA should deploy to prod. The script for deploying to any environment should already be available, so for prod, you’d just need to schedule a time for it to run regularly." And we have that `daily-deploy-production` GHA already, which further compounds my confusion.

**Comment by ndsprinkle** [comment] 2021-08-24 17:32
Ah okay, thanks for the clarification Oseas.

When talking with Eugene, he explained which steps were complete from the original plan I posted above. Steps 3 and 4 are complete, with the only caveat from step 3 being that `continuous-integration` in `content-build` needs to be verified that it is completely complete like it is in `vets-website` (minus the archive and deploy steps).

Here is the remaining plan as written by Eugene:

(From step 1) First wanted to confirm that the daily prod deploy is working correctly
   - Oseas has been having it test deploys to dev, I think?

(From step 2) Once daily deploys are ready, turn it off in Jenkins and have the GHA daily deploy push to the prod bucket

(From step 5) Then uncomment the archive and deploy in the CI workflow and confirm that it works
   - I think Oseas already has the daily deploy in GHA check the GHA workflow status
   - Actually, now that I think about it, the GHA daily deploy might only be checking the workflow status and not the Jenkins build status. If so, the daily deploy can’t be switched to GHA until after the CI workflow is switched from Jenkins to GHA


@oseasmoran73 How many of the things that Eugene has mentioned you on have been successes? Wondering if more of the steps can be crossed off.

**Comment by oseasmoran73** [comment] 2021-08-24 17:54
Not sure if this is the correct format, but will try to stay aligned with your steps:

1. The daily-deploy is currently in effect (it is pointing to s3 rather than prod) for testing purposes. It is working as intended. ✅ 
2. This is not in effect. The environment and buckets are there [commented out](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/daily-deploy-production.yml#L167-L168). This makes sense that can add as action item. _**Important: It is checking against current GHA status, and not the Jenkins one. So if we want to check against Jenkins we will need to add the snippet**_
3. With persistent/on-demand runners seem stable (it is only being used in `content-build` repo), it is the final workflow (minus archive, deploy, and review instance). What is pending is the merge, which PRs have already been created (will prob need to rebase w/ master).
4. This will need ongoing and part of other[ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/28969) Megan sent.
5. Correct. They are already checking against GHA workflow status, not Jenkins (also mentioned in step 2). It would be worth investigating if we can get call REST API to get the Jenkins associated with as I don't see why that would be not possible. ✅

**Closed** 2021-09-09 14:57 UTC
Labels: tools-fe
