### ISSUE TITLE
<"Need Help" Content> from <MOVE 1095-B>

### ISSUE THREAD

**Issue by graceerinhongfrog** [department-of-veterans-affairs/va.gov-team#37079] opened 2022-02-17 16:47 UTC
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

My team has a Need Help section we'd like to confirm are not going against any content / design best practices. We noticed several different styles and components being used across the VA for help and FAQ content and wanted to make sure our content is using the right style. The content we are looking to style is as below, and the style in which we'd like to put this help information is the one commonly seen on va.gov right now, the one with the header and blue line:
![Screen Shot 2022-02-16 at 5 00 45 PM](https://user-images.githubusercontent.com/94070881/154528163-b1ea81b5-5b0d-4e02-90e9-f447f38f69cc.png)

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: 
- Link to or attach user flows:
- Link to prototype or mockups: (https://sketch.com/s/0321ea04-f0f4-49bd-b160-c72b0f44721a) 
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No 

## When does this work need to be done?
- Estimated launch date: 
- Estimated staging review date: 
- Content and IA work needed by: February 22nd, 2022.

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: MOVE CEDAR 1095-B
-	OCTO-DE product owner: Tracey Mulrooney
-	Product manager: Ashley Castillo
-	Designer: Grace Hong
-	FE engineer: 
-	Product/team Slack channel:  cedar-1095b

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by SgardnerPMP** [comment] 2022-02-28 19:42
Still clarifying what the request is for.  Beth is reviewing.

**Comment by DanielleThierryUSDSVA** [comment] 2022-03-08 16:11
Hi @graceerinhongfrog. In looking at this full page as part of providing guidance on the IA/H1, it looks like this is a static landing page that our sitewide content team would build in Drupal.

The "need help?" component isn't available in Drupal, as that component is specific to online applications.

Is this the latest iteration of the page (from the Mural)? If yes, our team can review and provide edits and recommendations based on our approach to landing pages like this one.

![image](https://user-images.githubusercontent.com/62957278/157277720-4c64e847-8aa7-493d-90bf-046225ab48df.png)

**Comment by SgardnerPMP** [comment] 2022-03-08 16:35
If Grace confirms, SW-Content will add story to build page in next sprint.

**Comment by graceerinhongfrog** [comment] 2022-03-08 21:40
Thanks for getting back to us @DanielleThierryUSDSVA @SgardnerPMP - Linking our most recent landing page here!: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/3.8.2022_1095-b_Authenticated%20state_Desktop.jpg

**Comment by ashleycastillo** [comment] 2022-03-08 21:53
@SgardnerPMP The landing page is dynamic, as it has a Veteran log in before they can download their form. @nprimak and I can walk you through how it was designed and how we intend to build it in order to work together with you and your team

**Comment by ashleycastillo** [comment] 2022-03-11 14:56
@DanielleThierryUSDSVA Just to clarify, is your team reviewing to provide edits and recommendations? When can we expect to get feedback by?

**Comment by ashleycastillo** [comment] 2022-03-11 14:57
@SgardnerPMP We have already built out the react widget that has the login/logout and the download button. How can we get the react widget to you? When would you be able to build the page? We need the page back by Tuesday  March 15th so we can make our staging review timeline. Would this be possible? Happy to chat quickly if helpful!

**Comment by RLHecht** [comment] 2022-03-11 19:06
@ashleycastillo Since this page needs to be built in Drupal, our team can build this out for you by mid next week and will have our content edits in there as well. We will send you a preview link for you to review (you'll need to be on the VA network for it to work). If you give us the code for the react widget we will be able to place it into the Drupal page.

Unfortunately, Drupal doesn't go to staging, so you'll need to check with the collaboration cycle and public websites on how best to handle the staging review.

**Comment by SgardnerPMP** [comment] 2022-04-05 20:41
Moving this to Validate as all work on #38448.

**Closed by SgardnerPMP** 2022-04-05 20:41 UTC
Labels: sitewide content, sitewide content-product support
