### ISSUE TITLE
Adjust COE Dropdown

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37507] opened 2022-02-23 18:44 UTC
## Background
We need to make some adjustments to the COE dropdowns for military branches

## Considerations
Might be a schema change, and a key might be changed as well; coordinate with Kathleen if needed

## Tasks
- [ ] Remove `NOAA` and `Public Health Service` and replace them with `OTHER`
- [ ] Update schema file

## Acceptance Criteria
- [ ] Branches have been addressed
- [ ] A PR has been requested for merging

**Comment by jerekshoe** [comment] 2022-02-25 19:15
I think we can close this guy. Looks like a dupe of #37508

**Closed** 2022-03-02 22:42 UTC
Labels: duplicate, frontend, vsa, vsa-ebenefits, LGY
