### ISSUE TITLE
General Analytics Request for [Facilities] (following data scrub)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17597] opened 2020-12-16 20:27 UTC
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Facilities Team

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
   
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
- Scrubbed data reflected 10/12/20 - 12/2/20

## Analytics to Track Down
> Examples
> 

- Following the [data scrub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/decisions/google_analytics_data_scrub.md), we need to replace deleted location entries data on the Facility Locator DOMO dashboard with info that’s safe to collect 

## Which Product Questions are you trying to answer?

1. How can we assess location search parameters in a responsible, non-PII way? The original question we were trying to answer: what info do Veterans enter in the geographic search box (street address vs city, state vs zip), and how does this impact search results? 
2. We have been hoping to implement a geographic predictive search feature. Will this data concern impact our ability to deliver this functionality? 

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2021-01-04 12:14
Thanks for this @mmiddaugh , we will be in touch shortly here

**Comment by joanneesteban** [comment] 2021-01-27 17:44
@mmiddaugh is this a duplicate of #17683 ?

**Comment by mmiddaugh** [comment] 2021-01-27 18:24
@joanneesteban the intent for #17683 is to remove any leftover tracking on the location field. (an engineering task)

**Comment by joanneesteban** [comment] 2021-02-17 19:05
@JasonTheBearded we're moving this to QA. We think this can be closed, but double checking with you.

**Closed** 2021-04-22 19:51 UTC
Labels: analytics-insights, analytics-request, vsa, vsa-facilities
