### ISSUE TITLE
General Analytics Request for Search & Discovery - Typeahead Taxonomy Changes for zero suggestions 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20889] opened 2021-03-04 21:21 UTC
# Metrics Reporting Request

## Description
- Who is this request for?
Jon Wehausen, Sam Suddath, Search and Discovery, Analytics

- What team/project is this work for?
Search and Discovery - Typeahead POC
    
- What type of analytics support are you looking for?
Update to analytics tagging / KPI dashboard update pending reset
    
## Timeframe for Analytics Requested
Reset date TBD, but like around March 22 onward

S&D Action Items:
- [x] update view search results event logging with ```type-ahead-options-count``` data 
- [x] update event logging functionality to capture suggestions list on tab
- [x] change duplicate search results event to: ```onload_view_search_results``` but ensure that searches conducted from /search still fire the appropriate search event.

Analytics Action items:
- [ ] New view_search_results data used to clean up metrics
- [ ] graphs are fast-forwarded to new capture start date (tbd)

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2021-03-04 21:37
Thank you @denisecoveyduc and @srsuddath ! This is great, very much appreciate this!

**Comment by jonwehausen** [comment] 2021-03-12 19:35
Hi @srsuddath , 

When you have a moment, could you provide an update on your progress for making these changes? 

Thanks so much and look forward to QAing your work here.

**Comment by srsuddath** [comment] 2021-03-15 14:06
Hey @jonwehausen unfortunately I haven't started these changes yet. I was Out of Office all last week due to my wife having a baby, but this is top of my priority list now that I am back!

**Comment by srsuddath** [comment] 2021-03-22 13:23
PR has been merged, analytics should be updated by this afternoon with new event logging

**Comment by srsuddath** [comment] 2021-03-22 13:23
Sorry everyone, hit "close with comment" rather than "comment" my bad!

**Comment by jonwehausen** [comment] 2021-03-22 16:09
Thanks @srsuddath ! We will be testing this today

**Comment by jonwehausen** [comment] 2021-03-22 18:33
@srsuddath & @denisecoveyduc We are ready to begin on this testing -- We are currently not seeing any search results being returned and were curious if either of you could provide an update on that? Also curious when all of the new suggestions will be loaded in or if that's already happened?

**Comment by jonwehausen** [comment] 2021-03-22 19:01
### Edge Case QA Bug

@srsuddath There is a small bug within an edge case I just discovered -- an item we'll want to correct to ensure data integrity 

Steps to reproduce
1. Start typing "ebenefits" to show type ahead suggestions
2. Arrow down to a suggestion and press TAB on a suggestion, but **DO NOT SEARCH**
3. Click back into search box and resume typing
4. Select an option from type ahead and perform search 

**Description of Bug**: The type ahead options list will populate twice

![image](https://user-images.githubusercontent.com/48527022/112043591-36870f00-8b1f-11eb-9966-5b54c736f91b.png)

**Comment by jonwehausen** [comment] 2021-03-23 11:44
### QA Testing

@srsuddath Please see QA results below, thanks again for your work here. If we could visit the edge case bug above at some point that would be great. 

Description of Interaction | Data Layer | GTM Tagging | Test Status | Dev Notes 
| -- | -- | -- | -- | -- |
Searched with a query input of "form" with typeahead options "forms" populated ![image](https://user-images.githubusercontent.com/48527022/112038124-dd1be180-8b18-11eb-8c84-72f6cd15c39c.png) | ![image](https://user-images.githubusercontent.com/48527022/112038175-ec029400-8b18-11eb-8330-d25b01f8d959.png) **and `onload_view_search_results`** <br> ![image](https://user-images.githubusercontent.com/48527022/112137618-db98fa80-8ba6-11eb-825d-1f6906000896.png) | ![image](https://user-images.githubusercontent.com/48527022/112039977-03db1780-8b1b-11eb-9e04-c74e7d3967f8.png) **and `onload_view_search_results`** ![image](https://user-images.githubusercontent.com/48527022/112137185-54e41d80-8ba6-11eb-991b-5f15e296f7f3.png) | ✔️ **PASS** |  - Fired the secondary `onload_view_search_results` event with correct values for total pages & results 
Started typing a query of "ebe" with type ahead options and arrowed down 2 suggestions and pressed tab, final search was "ebe" with type ahead options NOT on screen at search time | ![image](https://user-images.githubusercontent.com/48527022/112138509-f881fd80-8ba7-11eb-96b0-f4f135ca0dfd.png) <br> **and `onload_view_search_results`** ![image](https://user-images.githubusercontent.com/48527022/112138614-1d767080-8ba8-11eb-8283-b7a3ad796399.png) | ![image](https://user-images.githubusercontent.com/48527022/112138721-3d0d9900-8ba8-11eb-9b9c-0047cc5243b3.png) <br> **and `onload_view_search_results`** ![image](https://user-images.githubusercontent.com/48527022/112138811-56164a00-8ba8-11eb-8723-04cd265954d2.png) | ✔️ **PASS** |  - Fired the secondary `onload_view_search_results` event with correct values for total pages & results

**Comment by jonwehausen** [comment] 2021-03-23 13:03
@JasonTheBearded In order to fulfill the teams request of pushing the charts forward to begin today, would you like to open a separate ticket or me shift this one to the dashboarding board? 

Thanks in advance

**Comment by JasonTheBearded** [comment] 2021-03-23 13:48
@jonwehausen I think shifting this ticket to the Dashboarding board will be fine. Thoughts @joanneesteban?

**Comment by jonwehausen** [comment] 2021-03-23 14:10
Okay thanks @JasonTheBearded , I'll do that

**Comment by srsuddath** [comment] 2021-03-23 17:02
Hey all, sorry for the delay in responding here, Search Results not loading yesterday was a bit of a 5-alarm fire. I am working on the bug fix and the duplicate search event fix now!

**Comment by srsuddath** [comment] 2021-03-24 18:17
PR for the edge case and bug fix has been merged, should be live on staging shortly

**Comment by jonwehausen** [comment] 2021-03-24 21:20
## QA Testing

@srsuddath Thanks so much for your work here. 

| Description of Test Case | Data Layer Screenshot | Test Status
| -- | -- | -- |
_Pagination following a search_ | N/A | • **Does not fire another `view_search_results` event as expected** 👍 
_Tab edge case_: 1) Start typing "ebenefits" to show type ahead suggestions <br> 2) Arrow down to a suggestion and press TAB on a suggestion, but DO NOT SEARCH <br> 3) Click back into search box and resume typing <br> 4) Select an option from type ahead and perform search | ![image](https://user-images.githubusercontent.com/48527022/112382746-a08be980-8cc2-11eb-8525-355899bda834.png) | We can consider the edge case identified [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20889#issuecomment-804316238) resolved 🎆

**Comment by jonwehausen** [comment] 2021-03-30 13:23
## QA

Hi @srsuddath -- here are the final QA results, thank you again for all of your collaboration and efforts here. 

| Description of Interaction | Data Layer | GTM Tagging | Test Status | Notes 
| -- | -- | -- | -- | -- | 
Repeat/duplicate/back-to-back search of "forms" from /search | ![image](https://user-images.githubusercontent.com/48527022/112994914-b8d38c80-9138-11eb-90f8-298a58cfd2f7.png) | ![image](https://user-images.githubusercontent.com/48527022/112994988-c721a880-9138-11eb-87b7-de433a44ff57.png) | ✔️ **PASS** | Refiring of `view_search_results` event as expected - retains our insight into duplicate searches 
Search from `/search` and pagination | N/A | N/A | ✔️ **PASS** | No refiring of ` view_search_results` event as expected

**Comment by srsuddath** [comment] 2021-04-05 18:09
Thanks @jonwehausen is there any other bugs or fixes you forsee needing prior to us locking things for a 2-4 week POC trial run?

**Comment by jonwehausen** [comment] 2021-04-05 23:13
Hi @srsuddath , 

Thanks for checking in -- Nope! I believe we've covered as many edge cases as we can touch here. Thank you for all of your assistance. 

@JasonTheBearded Could you confirm whether we have charts on the dashboard ready to go? Thanks in advance.

**Comment by JasonTheBearded** [comment] 2021-04-06 14:35
@jonwehausen Confirming the charts and dashboard are good to go. All data was pushed forward to 3/23 as previously discussed.

**Closed** 2021-04-19 13:44 UTC
Labels: analytics-insights, analytics-request, vsa-search-discovery
