### ISSUE TITLE
Content review of Discharge Upgrade Wizard changes

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#92611] opened 2024-09-10 20:15 UTC
## Issue description

Per Fran Cross: 

> Regarding Discharge Upgrade Wizard - updated content and updated to sub-task pattern... this work is almost completed, and we'll be moving into the Staging review, but we need to have someone in CAIA review and approve the content. As a reminder, we received 'Phase 1' content changes provided by CAIA, and "Phase 2' content changes are future-scoped after stakeholder(s) are identified. 

> It's review of the content changes originally provided by CAIA, and I noticed that there was a content review section on the old ticket, so wasn't sure that was applicable or not to this content review ... We hope to be ready for review in the next couple of weeks, so it will hopefully be before you're OOO.
One thing of note is that Joshua Gibbs (a stakeholder for Air Force info) reached out and provided updates to some production info that was outdated/incorrect, so I'll provide that information in the ticket, since it will be different than what was in the Word doc provided previously. 

Reopened the original intake to track this

## Artifacts: 

- Original [content changes](https://dvagov.sharepoint.com/:w:/s/SitewidePublicWebsites/EZ63meOuaOJBgq4EL1p9pvQB6TUrm_C5Asl9Es1fsgKGOQ?email=Laura.Flannery%40va.gov&e=c8OVtr) document from CAIA
- Staging URL: https://staging.va.gov/discharge-upgrade-instructions/introduction
- Note that there were changes introduced to PROD and to this new Discharge Upgrade Wizard on Staging via requests from stakeholders; reviewed and approved by Joshua Gibbs:

<details>
<summary>Steps to Reproduce getting to the results screen the changes are on</summary>

Go to the Discharge Upgrade Wizard here: https://www.va.gov/discharge-upgrade-instructions/
- Click the Get started link
- **Question**: In which branch of service did you serve? 
  - **Answer**: Air Force
- **Question**: What year were you discharged? 
  - **Answer**: (I don't think it matters, but I used 2012)
- **Question**: Which of the following best describes why you want to change your discharge paperwork? Choose the one that's closest to your situation. 
  - **Answer**: I suffered from an undiagnosed, misdiagnosed, or untreated mental health condition, including posttraumatic stress disorder (PTSD), while in the service. I was discharged for reasons related to this condition.
- **Question**: Do you want to change your name, discharge date, or anything written in the "other remarks" section of your DD214? 
  - **Answer**: No, I want to change only my characterization of discharge, re-enlistment code, separation code, and/or narrative reason for discharge.
- **Question**: Was your discharge the outcome of a general court-martial? 
  - **Answer**: I'm not sure.
- **Question**: Have you previously applied for and been denied a discharge upgrade for this period of service? 
  - **Answer**: No.
- **Question**: Did you complete a period of Service in which your character of service was Honorable or General Under Honorable Conditions? 
  - **Answer**: No, I did not complete an earlier prior of service.
- Click Get my result link

</details>

<details>
<summary>Changes Summarized (screenshots below)</summary>

- Changed instances of Form 149 to Form 293 for Air Force results screens ONLY
- Addition of verbiage telling Veterans they can fill out and submit Form 293 online
- The following text just under the title is deleted (it was specific to Form 149 and not applicable to Form 293)
  - Pay special attention to item 6, which asks for the reason for your change. Most Veterans attach additional pages to answer this question.

For discharges related to PTSD or other mental health conditions, be sure to answer these questions to make the strongest case:
Did you have a condition that may explain or contribute to the discharge?
Did that condition start or get worse during your military service?
Why does the condition directly explain or contribute to the discharge?
Why does the condition carry more weight than any other reasons you may have been discharged for?
Item 8 asks for the date when you discovered the error or injustice you’re asking the Board to address. If it’s been more than 3 years since you found this error or injustice, you’ll need to include a reason why the Board should consider your application. Examples of good reasons include new evidence you’ve found to support your claim, or recent changes in policy (like liberal consideration for PTSD, TBI, or military sexual assault or harassment). These kinds of reasons will make it more likely for the Board to decide in your favor. The 3-year time limit isn’t a strict rule, so don’t let it keep you from applying if you think you have a strong case.
- last bullet item under the text above that starts with "Item 10", should be changed to "Item 17"

</details>

<details>
<summary>Screenshots of the above changes on the results screen</summary>

![Image](https://github.com/user-attachments/assets/2b0affb7-6ec5-428f-835b-b62389a843d9)

![Image](https://github.com/user-attachments/assets/01a59314-b1d1-4e2e-a293-7a3c5bce767d)

</details>

## Tasks
- [x] AP: Draft recommendations
- [x] AP: Share recommendations with product team
- [x] AP: Finalize recommendations with product team

## Criteria
- [x] Content recommendations have been shared and finalized with the product team

**Comment by FranECross** [comment] 2024-09-25 20:50
@katherine-fung and @strelichl The Discharge Upgrade Wizard content and other changes have been completed, and it's on staging ready for your review. Please let me know if any info I've provided is unclear, or if you have any questions. Thanks! cc @chriskim2311

**Comment by FranECross** [comment] 2024-10-23 21:15
@strelichl Thanks for the note! I'll be scheduling the Staging Review Collab meeting in about two weeks. Is it possible to do the review between now and then? I know there's a lot to review because it's so convoluted. TIA! cc @jilladams

**Comment by aprocik1** [comment] 2024-10-24 15:26
@FranECross, thanks for your patience. I compiled my recommendations in this [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1729772236611/5d9e23746cad35f2f55e53c6cbf572e69dc33fd7?sender=u4218162a290fc373d4179020). I know some of them may not be in scope right now, but they're all very small. Feel free to implement them as you see fit.

Note: I think we need to make substantial edits to the accordions on the intro page. But, I didn't provide my recommendations for those edits in this review. If I'm remembering correctly, those edits are out of scope right now.

**Comment by FranECross** [comment] 2024-10-25 17:07
@aprocik1 Thanks so much! I'll review and either create tickets for the current iteration, or add them to the Phase 2 ticket. You're correct that the accordion change are out of scope currently. They (and other changes on the intro page) were going to be part of Phase 2. I do welcome any changes in a new document, though, that I can add to the Phase 2 ticket and project plan, and then work with @mmiddaugh for prioritization in 2025. Thanks again!

**Comment by aprocik1** [comment] 2024-11-05 13:57
Fran confirmed that we can close this ticket as complete. I'm moving it to validate for now.

**Closed** 2024-11-11 13:51 UTC
Labels: sitewide content, sitewide CAIA
