### ISSUE TITLE
[CAIA Intake] <Benefits Management Tools>: Update disability claim statuses list on static pages

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82302] opened 2024-05-03 20:34 UTC
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: `Benefits Management Tools`
- **OCTO product owner:** @amylai-va  
- **Product name:** `Claim Status Tool`
- **Product manager:**  @jacobworrell 
- **Slack channel:** [#benefits-management-tools](https://dsva.slack.com/archives/C04KHCT3ZMY)
- **Dedicated content writer on your team (if you have one):** @laurwill
- **Dedicated a11y specialist on your team (if you have one):** @davidakennedy
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Full context in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293).

We are updating the "Overview" tab of the Claim Status Tool so that Veterans can see more details about their claim as it's being processed. Most importantly, we are moving from 5 "phases" to 8, and we are changing the names of some of those phases.

We have already collaborated with @laurwill on the content in the design itself. **For this ticket, we specifically want to ensure that we track all changes to sitewide content where we currently mention the Claim Status Tool and the different phases.**

Examples include:
- https://www.va.gov/disability/after-you-file-claim/
- https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
- https://www.va.gov/resources/what-your-claim-status-means/

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We just completed a Midpoint Review for this work. OCTO leadership expects us to ship this in June.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [ ]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [x] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Mural showing links to known pages that may need to be updated](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697490182408/80d09fbace925f5b50a50232f66e90f773d68d00?wid=74-1697490261656)
- [Latest designs](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1835-8610&mode=design)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83972
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83973
```

**Comment by laurwill** [comment] 2024-05-27 22:44
Hi @skylerschain , 
Of these 3 pages, only the [After you file page](https://www.va.gov/disability/after-you-file-claim/) is specific to disability claims. 

Can you confirm that you're planning to update the status list only for disability claims in this release? If so, we'll need to decide how to adjust the other 2 pages, since those apply to all types of claims in the tool. 
- For the [What your claim status means page](https://www.va.gov/resources/what-your-claim-status-means/), we could create 2 sections, one for disability claims and one for all other types of claims. Can you confirm that the existing statuses on that page (the 5-step version) will continue to appear in the CST on all non-disability claims?
- The [How to check your claim status page](https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/) is very out of date, and most of the information is about how to sign in. I'd like to explore retiring and redirecting this page to the [Check your claim status page](https://www.va.gov/claim-or-appeal-status/). We could also move any information that's still relevant to that page. I'll check with OCTO about that possibility. Can you share if there's any feedback your team has received that would indicate that people need this type of "how to" for the CST?

**Comment by skylerschain** [comment] 2024-05-30 13:43
Hey @laurwill : 

Per [this Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1717072628289289?thread_ts=1716906440.140509&cid=C04KHCT3ZMY), yes we're only updating for disability compensation claims. That has been clarified in the [product initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Improved%20Claims%20Process%20Understanding%20Initiative.md#in-scope).

I think adding a new table to the [What your claim status means](https://www.va.gov/resources/what-your-claim-status-means/) showing the new 8 steps is a good idea. Perhaps we can label that first table "Disability compensation claims" and the other table "Other claims". 

I agree the "How to check your claim status" page feels unnecessary and doesn't feel worth keeping.

**Comment by laurwill** [comment] 2024-07-01 14:50
Hey @skylerschain and @uxgary ,
I audited the site to find any other pages with these claim statuses and didn't find any. 
Here's the work we'll need to do for this ticket, which I can pick up when I'm back from OOO on 7/8:
- Get SME approval to retire and redirect the "How to check your claim status" page and request redirect from Public Websites
- Draft updates to the 2 other pages to replace the old statuses with new statuses. On the "What your status means" page, we'll replace the table with 2 lists of statuses and definitions, one for disability and one for everything else. We're retiring content-heavy tables like this because they're not accessible.
- Get SME approval of updates to pages, copyedit, and publish

Let me know as soon as you have a more firm date when you plan to launch the new statuses, and we can try to align timing for these updates. Thanks!

**Comment by skylerschain** [comment] 2024-07-09 17:01
@jacobworrell Can you provide the latest on dates for Claim Phases launch?

**Comment by laurwill** [comment] 2024-07-18 14:07
Hi @jacobworrell @skylerschain @uxgary , I think you all are going to staging review with the claim statuses this week — do you have an update on dates for the launch?

**Comment by laurwill** [comment] 2024-07-18 15:11
@skylerschain I just [requested the redirect](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88728) of the "How to check your status" page so we can get that in PW's queue. Can you confirm which VA partners need to approve content changes related to the claim phases? We'll need to get their approval of the redirect before PW can implement.

**Comment by skylerschain** [comment] 2024-07-19 14:02
@laurwill Thanks for submitting that request. For content changes, it'd be good to keep @jstrothman in the loop. Aside from that, it depends on the content and in this case, I think it's all stuff that has been approved for the Overview tab itself. Julie can comment here if she disagrees.

I'm not sure how people were getting to this page primarily before: https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/. But it seems more informational and more similar to this resources page: https://www.va.gov/resources/what-your-claim-status-means. Would it not be better to redirect to that?

**Comment by jstrothman** [comment] 2024-07-22 21:05
@laurwill For approval of the content regarding claim phase changes, we've been working most closely with @AndrewGrayVBA -- the Office of Benefits Automation liaison for benefits management team work.

**Comment by jstrothman** [comment] 2024-08-05 13:58
@laurwill The Claim Status Tool claim phase expansion was released to 50% on 7/31--do you need anything from us re updates to the sitewide pages listed in this issue?

**Comment by laurwill** [comment] 2024-08-05 16:22
Hi @jstrothman and @andrewgrayVBA , 

I have draft updates to the [After you file your claim](https://www.va.gov/disability/after-you-file-claim/) and [What your claim status means ](https://www.va.gov/resources/what-your-claim-status-means/)pages for your approval.

@andrewgrayVBA we're also planning to redirect the [How to check your claim status page](https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/) to the [Check your claim status page](https://www.va.gov/claim-or-appeal-status/). That "how to check" page is outdated and difficult to keep current, and we don't think this kind of how-to is needed for the claim status tool. So we'll send people straight to the the tool itself instead. Let me know if you have concerns about this redirect.

A few notes about the page updates:
- I've matched the verb tenses we're using in the online tool — people would use the After you file page and the Overview tab to understand all future steps in the process, so that's in future tense "we'll." The use case for the What your status means page and the Status tab in the tool is to understand the step your claim is currently on, so that's in present tense "we're."
- After you file page applies to both mail and online claim filing, so the first step has different content here than in the tool. The variation is appropriate in this context.
- The What your status means page applies to both disability and non-disability claims, so I've split the page into two H2 sections by claim type. 
- The What your status means page previously presented the status definitions in a table, but we're deprecating this kind of content-heavy table on all our VA.gov pages because it causes accessibility issues. To correct this, I've made the status terms H3 headers with the definitions under those headers. 

Let me know if you have any questions or concerns with these pages! Otherwise we'll get them ready to publish when the tool updates go live to 100%. 

### After you file page updates
![image](https://github.com/user-attachments/assets/66078d0a-17dc-4bae-9742-8747ddb8ea62)

### What your status means updates
![image](https://github.com/user-attachments/assets/0a497f8b-26d5-4ab9-8c44-4b16c6432e79)

**Comment by jstrothman** [comment] 2024-08-06 17:11
@laurwill Looks great to me!

**Comment by laurwill** [comment] 2024-08-07 19:40
Andrew confirmed via Teams that he reviewed and approves the changes, so I'll go ahead and publish, and also confirm that PW can move ahead with the redirect of the "how to" page.

Just one last Q @jstrothman @skylerschain — in the tool, do the non-disability 5-step statuses also say "Step 1:" "Step 2:"? If so I can add that to the status terms on the "what your status means" page.

**Comment by jstrothman** [comment] 2024-08-08 18:07
Yes they do have the "Step n:" prefix
![IMG_0137](https://github.com/user-attachments/assets/602fcf39-da80-4bba-b227-be26a8b70cdc)
![IMG_0140](https://github.com/user-attachments/assets/7af8166e-66cd-4e1b-a308-ecda7ed25dfe)
![IMG_0139](https://github.com/user-attachments/assets/a22bedab-1e60-4d88-aad2-8ff83c29e983)

**Comment by laurwill** [comment] 2024-08-12 15:48
Thanks @jstrothman ! I updated to add the step numbers to that set of definitions and republished. Closing this out!

**Closed by laurwill** 2024-08-12 15:48 UTC
Labels: sitewide CAIA
