### ISSUE TITLE
Determine strategy for Salesforce data fields

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6465] opened 2020-03-04 16:19 UTC
## User Story or Problem Statement
How might we configure the Salesforce data fields to better pull on Platform to inform teams of veteran issues?

## Goal
Configure Salesforce data fields

## Acceptance Criteria
- [x] Contact the Salesforce stakeholders
- [x] Determine strategy as contact center leads
- [x] Discuss with team
- [x] Present to VEO call center stakeholders

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment] 2020-03-13 18:55
3/13/2020 - Held a meeting about the strategy for how we want data to be tracked in Salesforce for VA.gov issues with Joanne, Amy, Kimberley and Chante. The consensus is that it would be best to track issues by VA.gov product versus tracking by broad issue type category. These are the reasons we have concern about the issue based approach:

- Prioritizing tracking the ISSUE over the TOOL where the issue is happening might mean the data quality is not sufficient at the sub-category level. This means it might be hard to determine which team to direct issues to or that general reports might not be as helpful.
- As new products and tools are developed, it will be hard to add them in and track initial user problems.
- Fitting a square peg into a round hole – the issue category is broad and so the definition of what is happening is different depending on where the issue is occurring. This might be confusing for the agent.

At the end of the day, we have very little control over what gets implemented because we aren't the owners of the system. I am attaching a spreadsheet that provides three different options for tracking. The issue base v. 2 is the cleaned up version of the one proposed by the VEO Tier 1 Call Center. The Product based tab is our preferred set up. We will discuss with Rebecca and her team today and see if we can agree on a path forward for beginning the tracking process.

**Comment by clantosswett** [comment] 2020-03-13 18:57
[SF-CRM-Tracking-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4331196/SF-CRM-Tracking-Fields.xlsx)

**Comment by clantosswett** [comment] 2020-03-17 23:45
Created the attached updated data fields document and sent over to VEO Call Center for review. 
[SF-CRM-Tracking-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4346267/SF-CRM-Tracking-Fields.xlsx)

**Comment by joanneesteban** [comment] 2020-03-25 14:39
Waiting (on COVID) to talk to Rebecca about the proposed Salesforce fields.

**Comment by joanneesteban** [comment] 2020-04-08 14:21
Waiting on VEO.

**Comment by clantosswett** [comment] 2020-04-28 13:50
On 4/24, we had a meeting with the VEO contact center group. Right now Salesforce updates are delayed because of COVID-19 related work. But this is on their radar for an issue that needs to be completed. I think we can close this particular issue and open a new one to follow up and push through to completion.

**Closed** 2020-04-28 13:54 UTC
Labels: analytics-insights, blocked, contact-center
