### ISSUE TITLE
QA Testing for Address Validation Modal

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3616] opened 2019-11-20 17:27 UTC
## Info 
Add the vsa-qa label  [Yana, Michelle: this is a change from qa to vsa-qa]
Select the Milestone sprint, or otherwise provide due-date for testing results.

Provide the following info to support testing (via links if documented elsewhere):

## Test-accounts** (usernames) for all UX scenarios/flows.

**Comment by Samara-Strauss** [comment] 2020-01-21 16:27
Closing. Duplicate of #3948.

**Closed** 2020-01-28 15:36 UTC
