### ISSUE TITLE
Verify cost/benefit of changing 'virtus'

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#814] opened 2019-08-05 20:40 UTC
As an engineer I want to verify IF we should change 'virtus' in all models` so that we don't make changes that result in issues which far outweigh the benefits of the change.

## Background
[`dry-types` documentation](https://dry-rb.org/gems/dry-types/)
[`Virtus`](https://github.com/solnic/virtus) is no longer under development.  It's last update was over 2 years ago.
`dry-types` is the successor to `virtus`.  It is actively being developed and recently reached version `1.0.0`.

It claims  that it is
>Roughly 6-10 x faster than Virtus

## Approach
Given how closely the concerns track, this should _not_ be worked on while #465 is actively being worked on.

Given the large number of `virtus` models in our codebase, this work should be completed cautiously across multiple pull requests.

## Acceptance Criteria
- [ ] Validate model by model if we should make changes based on the researched value
- [ ] Begin to implement changes

**Comment by annaswims** [comment] 2019-11-15 13:56
conclusion: we should move to dry-types because there will likely come a point when viturs prevents us from making a ruby/rails upgrade.

Next steps:
1) ensure proper test coverage of model attributes
2) convert virtus to dry-types.

**Comment by johnpaulashenfelter** [comment] 2020-05-26 16:43
Duplicate of #466

**Closed by johnpaulashenfelter** 2020-05-26 16:43 UTC
Labels: tools-be, tools-improvements
