### ISSUE TITLE
Create a Betamocks Recording

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2932] opened 2019-10-30 15:16 UTC
## Story
As a backend engineer, I want to be able to understand how betamocks are configured and recorded so that I can better test and call endpoints within the applicable environment.

## Considerations
- From the [vets-api README.md](https://github.com/department-of-veterans-affairs/vets-api) there are [instructions](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md) on how to set up betamocks.
- Needs access to the VA network

## Acceptance Criteria
- [x] Create a betamocks recording for the `FindRatingInfo` Service
- [ ] Push the recording to the betamocks repo

**Comment by steve-gov** [comment] 2019-11-19 23:31
Duplicate of #3237 ?

**Comment by kathleencrawford** [comment] 2019-11-22 00:16
submitted PR https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/107 to merge betamocks files into vets-api-mockdata repo

**Closed** 2019-11-22 21:40 UTC
Labels: backend, vsa, vsa-ebenefits
