### ISSUE TITLE
EMIS deprecation: migrate pre-fill military_information

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44861] opened 2022-07-26 12:58 UTC
## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. 

**This isn't necessarily a breaking change for pre-fill but will degrade the veteran experience**

Pre-fill uses EMIS for `military_information`. We should be sure that `military_information` is no longer pulled from EMIS. See Main App Responsibilities ([in code- search for user.military_information](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation#Main-App-Responsibilities)). The User model utilizes EMIS via [delegation methods](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L326-L327). There’s some [metaprogramming](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L406-L416) used to initialize the methods used to obtain the EMIS related information/ Some of the underlying base methods may have the ability to be reused, but we will need to be sure that `military_information` is no longer being pulled from EMIS. 

### Notes:
1. military_information for pre-fill is [initialized here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L204-L225).
2. [FormProfile attributes are here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L24-L47)
3. [These methods are used ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/emis_redis/military_information.rb#L37-L56)to populate the `FormMilitaryInformation` pre-fill class

All calls to EMIS should be removed and code should be migrated to use VaProfile

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

This entails reviewing the high level [external integrations doc found here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) along with the child docs for each individual service.

## Acceptance Criteria
- [ ] Investigate if we can use anything that the auth experience team has already done
- [ ] Migrate military_information to VaProfile
- [ ] Tests are passing
- [ ] Update documentation
- [ ] Generate Additional Tickets as necessary

**Comment by rmtolmach** [comment] 2023-08-21 19:43
Duplicate of:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61657

**Closed by rmtolmach** 2023-08-21 19:43 UTC
Labels: vets-api, low-user-impact, platform-tech-team-1, platform-cop-backend, platform-cop
