### ISSUE TITLE
AMA/Decision Review pages: Create a new Hub Page

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6799] opened 2020-03-11 22:06 UTC
This is follow on work that should happen _after_ ticket #5541 is completed. It is interrelated to other tickets to updating the DR/AMA pages (like adding left nav; determining any updates to the IA). 

__Problem description:__
The current IA structure of the Decision Review and appeals page is not optimal for the number of links it needs to accommodate or as an effective entry point to the individual lane pages. The volume of content would potentially overwhelm users looking to choose one lane to learn about rather than absorb details on all three. 

__Action:__ 
By making the it a hub page, the Decision Review and appeals page will become an effective overview of user options, allowing users to more easily compare the three lanes, and choose one at a time to learn more about. 

__Checklist:__

- [x] Gain approval internally
- [x] Share this solution with SMEs
- [x] Build this new hub page in Drupal
- [x] Update individual lane pages as needed (ensuring all details on the current decision reviews and appeal page are not lost in the move)

__Pages:__

- [ ] 1. VA decisions reviews and appeals https://www.va.gov/decision-reviews/
- [ ] 3. File a Supplemental Claim with new evidence  https://www.va.gov/decision-reviews/supplemental-claim/
- [ ] 4. Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
- [ ] 5. Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/

**Comment by lwalsh617** [comment] 2020-03-13 13:24
@AkucherGCIO - Per your request, I added detail to top of ticket.

**Comment by MickinSahni** [comment] 2020-03-16 15:53
2020-03-16 PW Standup
* We have the content from the old page
* Essentially turning the DR into a new page
* Content is approved
* Be on the lookout for a doc from Laura

**Comment by MickinSahni** [comment] 2020-03-18 15:48
2020-03-18 PW Standup
* Laura working on copy for this page
* Will share copy deck with Mikki 
* Note: ultimately this will head to Randi to build out the page in Drupal

**Comment by MickinSahni** [comment] 2020-03-19 15:51
2020-03-19 PW Standup
- Copy nearly complete. Have a question for Jen/Mikki
- Do we need to add a note for node_id to this ticket? Nope, there's a separate ticket to handle all of those!

**Comment by lwalsh617** [comment] 2020-03-19 18:04
@mnorthuis @jenniferlee-dsva -- Here is the copy deck for this page. Let me know if you have any questions. Once I have your approval, I will share it with Randi to build in Drupal. Thank you!
[decision-reviews-hub-page_copy-v1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4356210/decision-reviews-hub-page_copy-v1.docx)

**Comment by mnorthuis** [comment] 2020-03-19 21:28
Couple questions
1) I'm wondering if we should stay away from using action words in the link labels for the 3 decision review types in the "Request" spoke.  Those links are not going to the specific forms, they are going to pages that describe the process.  I know I had that language in my mockup as well, but we typically only use action words on pages where you can execute on the action. 
2) it is missing the 3 other claim types in the "Request" spoke: the After a review request, Insurance claims, Contested claims, Fiduciary claims
3) The "After you request a review" page is not represented in the spokes.  In other benefits, this page is usually in the "Get benefits" spoke - if the content is general to ANY kind of decision review, we could move this to the Manage spoke. 
4) For the "Manage your legacy appeal" page, when reading through the content, its not clear to me about what is being "managed".  Will this content be changing, or is this really still about requesting an appeal?  I'm not sure its a manage task. 
5) I think the link label and content for the promo spot will need to be shortened, there isn't much space there, not sure what the character count is.

**Comment by MickinSahni** [comment] 2020-03-20 15:42
2020-03-20 PW Standup
- Pulling this into sprint 18 as we need to talk through a few more questions, Mikki x Laura

**Comment by lwalsh617** [comment] 2020-03-20 20:18
@jenniferlee-dsva @mnorthuis @RLHecht -- Here's a new copy deck, revised per my call with Mikki today. @jenniferlee-dsva, one quick copy note. Under the board appeal link, I put the following copy:
![image](https://user-images.githubusercontent.com/53535663/77203040-e9183200-6ac5-11ea-942e-2b99b6490a0e.png)
I don't know if we can get away with positioning it this way or not, but if we can, it helps to differentiate board appeal from Higher-Level Review and it helps to steer Veterans toward HLR and SC first, which I know is the concern of the SMEs. LMK WYT. Thanks!
[decision-reviews-hub-page_copy-v1.2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4361653/decision-reviews-hub-page_copy-v1.2.docx)

**Comment by jenniferlee-dsva** [comment] 2020-03-20 20:35
^ I would use the currently approved text for BVA -- I think the above will appease Fred's concerns, but not nec meet Elizabeth's. And technically, a Veteran can use BVA from the beginning - they don't have to FIRST go through Supplemental/HLR, and I think there's some legal ramifications to suggesting or making it sound like you can only use BVA option after exhausting Supp/HLR. 

Def would need business verification either way.

**Comment by jenniferlee-dsva** [comment] 2020-03-20 20:37
Nope - NVMD ^ comment! You're right - they CAN only use BVA after exhausting Supp/HLR. Looks great! @lwalsh617

**Comment by jenniferlee-dsva** [comment] 2020-03-20 20:42
One copy note on the hub page - could you think of a way to make the 'learn more' language on the On this page links more in line with our 'get' benefits concept? I know you're not really 'getting' a decision review but maybe` "request" `or `"file"` -- to stay parallel with our other hub and spoke (get/manage/more) concept. (Though I realize everything here is technically 'manage'.)

**Comment by lwalsh617** [comment] 2020-03-20 20:44
@mnorthuis would you mind addressing Jen's comment ^ ? This is related to what we discussed about the HLR page. Thanks!

**Comment by mnorthuis** [comment] 2020-03-20 22:16
@lwalsh617 The feedback I had was removing the action words from the H1s of the main review pages.  The hub/spoke structure can and should still be focused on get/manage/more - so the first spoke would be "Request a VA decision review" and would include all content that revolves around doing that initial request.  The manage spoke would be something like "Manage your VA decision reviews and appeals"  and include task-based content that helps users take action after they've requested a review.  The last spoke is all tier 2 content that are just general resources and info.

**Comment by lwalsh617** [comment] 2020-03-24 13:46
@jenniferlee-dsva @mnorthuis -- It's tough because this page isn't a benefits page so it doesn't fit the hub template H2s as well. What do you think about "**Get information about the decision review process**" as the H2? That way, we don't throw an action (like "file" or "request") at users before they have the basic facts, and we don't end up with an H2 that doesn't clearly set up the links below it. I dropped my proposed H2 into the attached deck, p. 3, for context. LMK WYT. Thanks much!

**Comment by RLHecht** [comment] 2020-03-24 16:33
@lwalsh617 This page is built in Drupal but still awaiting final edits on several things. Preview link:
preview-prod.vfs.va.gov/preview?nodeId=3071

**Comment by lwalsh617** [comment] 2020-03-24 16:43
@jenniferlee-dsva @mnorthuis -- Randi just reminded me that the promo box on the new hub page will need an icon. Thoughts on what icon to show? Red frame shows where it goes on the page.
![Screen Shot 2020-03-24 at 12 33 25 PM](https://user-images.githubusercontent.com/53535663/77453048-18cc8000-6dcd-11ea-8530-4cfdc3eda8c1.png)

**Comment by jenniferlee-dsva** [comment] 2020-03-24 17:00
@lwalsh617  - It is tricky!  As you point out, these are all technically 'learn about' content -- even the other spokes in DR.

However, thinking long-term, most if not all of these DR options will get digitized into an online app. We're starting soon with HLR, and over time, others will follow. And thinking in terms of our overall IA and taxonomy pattern, this spoke is the place where all apply actions and information about applying live. 

So I still think the 'get' DR spoke should more closely align w/our other 'get' spokes conceptually, and not be about getting information. I still think we should go with "Request a decision review or appeal" for that spoke H2 and link. 

- it's as close to 'applying' concept, while using their "request" terminology.
- it also lets us embed the more Veteran familiar and SEO term "appeal" on this page. (Since Board Appeal is technically an appeal, I think it's accurate.)

Would like @mnorthuis's thoughts too.

**Comment by RLHecht** [comment] 2020-03-24 17:19
@jenniferlee-dsva @lwalsh617 The Drupal folks are currently fixing a bug that doesn't allow users to add those stored images to the promo so I'm going to hold off on setting it up for now (I can't save the promo without an image). I'll let you know when it's fixed. I'll work on the right rail components though.

**Comment by mnorthuis** [comment] 2020-03-24 20:52
@lwalsh617 I agree with @jenniferlee-dsva in above feedback...we have some benefits that don't necessarily have online applications, but the "Get" spoke is still where all the information is on how to apply as well as access to PDFs - that is the same as here.  So I think the same approach/model works and helps us to keep some level of consistency in approach for now until we can test this further.   The consistency also helps with stakeholder conversations so we have a solid approach avoiding customizations to begin with and can test and learn as we move forward.

**Comment by lwalsh617** [comment] 2020-03-25 14:45
@RLHecht - per feedback from Jen and Mikki, can we change one H2 on this page? The correct H2 is:  
**Request a decision review or appeal**
It should replace "**Get information about the decision review process**" (just below the "Mark your calendar" alert box). Thank you!

**Comment by RLHecht** [comment] 2020-03-25 14:51
@lwalsh617 That H2 has been changed.

**Comment by lwalsh617** [comment] 2020-03-25 15:53
^ Thanks, Randi! 
Here's the latest copy deck, just so we have it on the ticket. 
[decision-reviews-hub-page_copy-v1.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4381922/decision-reviews-hub-page_copy-v1.5.docx)

**Comment by MickinSahni** [comment] 2020-03-25 17:51
2020-03-25 PW Planning
- built in Drupal
- confirming that the copy deck and Drupal are consistent
- note: this is separate from a new Launch ticket we'd need to launch this new page as well as the other Decision Review pages we migrated to Drupal

**Comment by RLHecht** [comment] 2020-03-25 18:36
@lwalsh617 This page now reflects the newest copy deck and is ready minus the promo.

**Comment by MickinSahni** [comment] 2020-03-27 16:08
- All the latest content updates are complete 
- @lwalsh617 to confirm: 
  -  Update individual lane pages as needed (ensuring all details on the current decision reviews and appeal page are not lost in the move)

**Comment by MickinSahni** [comment] 2020-03-30 15:53
2020-03-30 PW Standup
- Confirmed and closing

**Closed** 2020-04-01 15:57 UTC
Labels: cms, content, vsa-public-websites
