### ISSUE TITLE
STEM: Update Google Analytics for the 22-10203 - Submission

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11708] opened 2020-07-28 15:38 UTC
## Assumptions: 
1. This work is completed behind the feature flag #7271.
2. Values in the table in AC 1 separated by | indicate 1 of possible values
3. The Yes or No question variables in the table in AC 1 should populate with Yes or No

## Acceptance Criteria
1. The following additional context DL variables are added to the `--submission-successful` and `--submission-failure` events:  

dataLayer Variable | Description of Form Submission Variable | Screenshot 
-- | -- | -- 
`'edu-benefits-currently-used'` | Populates with a **concatenated string** seperated by a space for each of the checkboxes checked from `/eligibility` page | ![image](https://user-images.githubusercontent.com/48527022/88176055-bd809200-cbf4-11ea-95ed-462c2cfb72ec.png) 
`'edu-currently-enrolled'` | Populates with 'Yes' or 'No' based on answer to "Are you enrolled in a science, technology, engineering, or math (STEM) undergraduate degree?" | ![image](https://user-images.githubusercontent.com/48527022/88176336-19e3b180-cbf5-11ea-9735-2c238dea0c75.png)
`'edu-benefits-remaining'` | Populates with answer to "About how much of your education benefit do you have left?" | ![image](https://user-images.githubusercontent.com/48527022/88176616-8d85be80-cbf5-11ea-9486-507a09d3d3e4.png)
`'edu-name-of-degree'` | Populates with answer to "Whats the name of your stem degree" |![image](https://user-images.githubusercontent.com/48527022/88176683-a3937f00-cbf5-11ea-8608-2b12dce43e71.png)
`'edu-stem-scholarship-school'` | Populates with answer to "Whats the name of the school where you plan on using the Rogers STEM Scholarship?" | ![image](https://user-images.githubusercontent.com/48527022/88176748-be65f380-cbf5-11ea-82fb-0604995d47d1.png)
`'edu-school-city'` | Populates with answer to school city | ![image](https://user-images.githubusercontent.com/48527022/88176966-143a9b80-cbf6-11ea-9dc7-e38fd9f50a14.png)
`'edu-school-state'` | Populates with answer to school state | ![image](https://user-images.githubusercontent.com/48527022/88177019-2b798900-cbf6-11ea-846a-b7e205580910.png)
`'active-duty'` | Populates with answer to "Are you currently on active duty or will you be going on active duty while receiving the Rogers STEM Scholarship?" | ![image](https://user-images.githubusercontent.com/48527022/88177069-421fe000-cbf6-11ea-8c2c-3bf8bd0ee28a.png)
`'contact-method-preference'` | Populates with answer to "How should we contact you if we have questions about your application?" | ![image](https://user-images.githubusercontent.com/48527022/88177146-611e7200-cbf6-11ea-8b40-60c7e638722d.png)
`'direct-deposit-account-type'` | Populates with answer to "Account type" | ![image](https://user-images.githubusercontent.com/48527022/88177226-81e6c780-cbf6-11ea-9a5e-ecc5f5eff063.png)

2. The dataLayer variables listed above with 'edu' are there to indicate education specific, 
3. The dataLayer variables listed above without edu are intentional to keep generic for re-use in other parts of the app

## Supporting Artifacts
1. Feedback from the analytics team that informed these changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-662429290

**Comment by dneel-bah** [comment] 2021-07-08 13:10
Duplicate of #11706, closing as OBE.  Work validated with OCTO in #10780.

**Closed by dneel-bah** 2021-07-08 13:10 UTC
