### ISSUE TITLE
Create a consent page for eligible users

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35630] opened 2022-01-20 05:33 UTC

**Comment by AGarcia-Clarity** [comment] 2022-02-23 21:34
@nsoutouras This can be closed in favor of #34945 (as we are combining the consent & information page)

**Comment by AGarcia-Clarity** [comment] 2022-04-13 14:11
@nsoutouras This can be closed. Duplicate of https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/34945

**Closed** 2022-04-14 15:47 UTC
Labels: Identity, Identity-Frontend
