### ISSUE TITLE
Business intake form for [VAIU] - CareCentra

### ISSUE THREAD

**Issue by matthewcollins5** [department-of-veterans-affairs/va.gov-team#56808] opened 2023-04-12 22:55 UTC
## Your Details
1.  Matthew Collins
​
2.  Innovations
    (ex., claims, health, etc.)
​
## Notification Details
1.  both
    (email, text/SMS, or both)
​
2.  I support Angela Gant-Curtis for the VA Innovation Unit (VAIU). The VAIU owns the Arches environment which serves as a common data science platform to develop and test models, tools, and software in a cloud environment (AWS and Azure). One of the current projects that we have deploying into Arches is CareCentra. CareCentra is an application that does a lot of things, but in the context of this conversation, it nudges participating Veterans with information, tips, reminders, and a range of tiny health actions that collectively lead them towards improved health status. The current COTS CareCentra system uses Twilio. We need a VA alternative to commercial Twilio for doing the communication with the participating Veterans. 

    (This is your chance to tell us an overview of your plans.)
​
3.  View secure messages and respond to prompts from the software.
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​
4.  The CareCentra software will use nudge enrolled veterans on key areas such as heart health and medication adherence.              (ex., fewer skipped appointments, less call center volume, etc.)
​
5.  The CareCentra software will kick off nudges to the veterans that choose to enroll in the software. 
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
6.  The CareCentra software running in Arches.
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​
7.  I am a representative of the VAIU platform and operations team. I can get this information from the CareCentra vendor. 
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
8.  I am a contractor for the VAIU. I believe a PO has approved, but Angela Gant Curtis will need to confirm. angela.gant-curtis@va.gov
    (ex., PO has seen the content but it is not approved)
​
9.  I believe we will provide the contact ID, but I will need to confirm with the CareCentra team.
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​
10.  I will need to defer to the CareCentra team. 
    (ex., opt in for claim status updates via email or text)
​
11.  I will need to defer to the CareCentra team. 
​
12.  If we can just get test accounts first, that would be great. We will not be going into production for several months.

**Comment by matthewcollins5** [comment] 2023-04-12 22:55
My email is matthew.collins5@va.gov

**Comment by bevnobev** [comment] 2023-04-14 16:46
Hi @matthewcollins5 I'm attaching our playbook to get you started.  I'm also attaching the VA SMS Guideline since you mentioned sending text message[https://app.zenhub.com/files/133843125/2858c0e1-ed99-47e5-83e6-29bd4adf276a/download](https://app.zenhub.com/files/133843125/2858c0e1-ed99-47e5-83e6-29bd4adf276a/download)[https://app.zenhub.com/files/133843125/7e762932-7717-4c63-b379-0d60ff1ae76d/download](https://app.zenhub.com/files/133843125/7e762932-7717-4c63-b379-0d60ff1ae76d/download)s

**Comment by matthewcollins5** [comment] 2023-04-28 17:12
Hi Beverly,
Can you resend these two links? I'm unable to view them.

Thanks,
Matthew

**Comment by bevnobev** [comment] 2023-04-28 17:19
Our playbook is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)

The VA SMS SOP is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20SOP%20for%20Delivering%20SMS%20Messages%20v1.0.pdf)

I'll email them as well, just in case.

**Comment by mjones-oddball** [comment] 2023-08-04 20:18
Duplicate of - https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/issues/gh/department-of-veterans-affairs/va.gov-team/61742

**Closed** 2023-08-04 20:17 UTC
Labels: vanotify-intake
