### ISSUE TITLE
Deploy "Missing ID" messages (aka "Need More Info")

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#86464] opened 2024-06-20 16:38 UTC
### Description
Based one the work completed here
https://github.com/department-of-veterans-affairs/va.gov-team/issues/61419
https://github.com/department-of-veterans-affairs/va.gov-team/issues/56676

and this documentation
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_entry_error_discovery.md

we have decided to move forward with deploying this work. 

Can you please test, or re-test since the work was completed a ways ago? @tblackwe to confirm that we will push this work out. 

## Acceptance Criteria
- [x] Retest this behavior on current `master`
- [x] Create an alert monitor that will catch any problems on the endpoint for this change
- [ ] Notify Jerek Shoemaker when this is released

**Comment by NB28VT** [comment] 2024-07-10 18:44
There is an existing monitor for this I'll plan to keep an eye on post release https://vagov.ddog-gov.com/dashboard/ygg-v6d-nza/benefits---form-526-disability-compensation?fromUser=false&fullscreen_end_ts=1720637008524&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1720633408524&fullscreen_widget=2602575858876322&refresh_mode=sliding&view=spans&from_ts=1720633048314&to_ts=1720636648314&live=true

**Comment by NB28VT** [comment] 2024-07-15 13:52
This is blocked until I can test it locally but I'm having problems with the mock data repo again, I've opened a support ticket here: https://dsva.slack.com/archives/CBU0KDSB1/p1721051385035229

**Comment by NB28VT** [comment] 2024-07-17 14:41
I was unable to test this with mock data again, however I was able to load the page with a user in staging and toggle on and off the flipper without issue and confirmed the identifiers mapping appeared in the user metadata. I have also confirmed there were no major changes around my code in the time since I last tested this.

I'm not aware of any way to test every situation in the front end reliably, however, the back end is well tested and we have a monitor for the back end behavior. If there are issues reported to us on the front end in production, we would be able to shut this off immediately (via the Flipper) and investigate.

**Comment by NB28VT** [comment] 2024-07-18 13:52
FYI @jerekshoe reached out to me in May regarding leveraging this functionality: 


"Ok cool, I’m interested in using those fields to determine if users going to CST have a participant ID or not so that we can show an error message to them letting them know to contact the call center"

I made sure to ping him when this launched so closing this ticket.

**Closed** 2024-07-31 13:42 UTC
Labels: disability-experience, DBEX-Carbs
