### ISSUE TITLE
Helm Chart Template: Service

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59963] opened 2023-06-08 17:31 UTC
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for Service created in the new child repo.

## Acceptance Criteria
- [ ] Helm chart template created for service in new child repo
- [ ] Verify the Chart is working as intended
- [ ] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by rileyanderson** [comment] 2023-06-08 18:36
Duplicate of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59920

**Closed by rileyanderson** 2023-06-08 18:36 UTC
Labels: Identity, identity-devops
