### ISSUE TITLE
[Support Slackbot] Deploy Support Slackbot to Utility VPC

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30090] opened 2021-09-17 15:41 UTC
@dginther commented on [Fri May 14 2021](https://github.com/department-of-veterans-affairs/devops/issues/9162)

Description:
The support slackbot will run in the dsva-vagov-utility EKS cluster. Deploy the manifest to this cluster via ArgoCD.

Tasks:
- [x] Add the support slackbot manifest to the relevant configuration in the Utility ArgoCD configuration
- [ ] Verify that the slackbot deploys and runs in the relevant cluster and namespace
- [ ] Verify that the slackbot is functioning as expected

---

@dginther commented on [Mon May 24 2021](https://github.com/department-of-veterans-affairs/devops/issues/9162#issuecomment-847414522)

@f1337 Will need your assistance in figuring out how to test and launch the bot in the presence of the heroku-based one.

**Comment by rmtolmach** [comment] 2022-03-04 17:22
Duplicate of #15142. Closing.

**Closed by rmtolmach** 2022-03-04 17:22 UTC
Labels: operations
