### ISSUE TITLE
Midpoint Review - Content Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#61219] opened 2023-06-29 22:32 UTC
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Condition add new > "back pain" is missing a comma after it. > I recommend adding a comma.
- Claim Type > Sentences after checkboxes are missing periods. > I recommend adding periods.
- Evidence Overview, Exposure Herbicide expanded, and Exposure gulf expanded all contain [bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists). All of these bulleted lists have first words after the bullets in lowercase. I recommend capitalizing the first word after a bullet. There are bullets that contain periods after sentence fragments, and other sentence fragments that don't have periods. Refer to guidance on [bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists).
![60140_Comma after Back Pain_Screenshot 2023-06-28 at 5.59.40 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/93149eff-e66f-4fb3-aa3f-77f83577ae7e)![60140_Claim Type_Periods after sentence_Checkbox_Screenshot 2023-06-28 at 5.53.34 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/6bfa6298-92ef-4f5f-9583-2256c479c8e8)![60140_Bullet Capitalization_1_Evidence Overview_Screenshot 2023-06-28 at 6.04.37 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/34214679-bf13-4a60-b59b-bb98800febe8)![60140_Exposure Gulf Expanded_Capitalization:Bullets_Screenshot 2023-06-28 at 5.48.40 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/d0ad663d-bd79-44cb-bcd6-b6a0819f14c5)![60140_Exposure Hebicide Expanded_"aboard" should be capitalized as the first word after a bullet_Screenshot 2023-06-28 at 5.50.04 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/e49a2348-bc26-4698-8b96-76335f547bd9)

**Comment by alatempa24** [comment] 2023-06-30 17:22
@CherylEvans this looks like a duplicate of 61218 - are both needed? Thank you!

**Comment by CherylEvans** [comment] 2023-06-30 17:50
@alatempa24 Yes, this can be deleted.  For some reason, when I create a ZH ticket and submit it, it tells me that an error occurred and didn't save my information, so I create another ticket, and then the first ticket shows back up AFTER I create the new one.  It happened twice yesterday.  Sorry for the confusion.

**Comment by alatempa24** [comment] 2023-06-30 17:57
No problem - thanks for confirming @CherylEvans ! 

Closing this ticket as it's a duplicate of 61218

**Closed by alatempa24** 2023-06-30 17:57 UTC
Labels: collaboration-cycle, collab-cycle-feedback, disability-experience
