### ISSUE TITLE
A timed out user is able to submit a request and receive a confirmation

### ISSUE THREAD

**Issue by mshatalov-va** [department-of-veterans-affairs/va.gov-team#90730] opened 2024-08-14 18:39 UTC
## Summary
A timed out test user is able to submit a request and receive a confirmation that the request was successful.  However, a user token error is show in devtools.  The "submitted" request is NOT listed on Pending Request page.  

## Specs
- Device: 
- Browser: 

## Steps to Reproduce

1. Log into VAOS.  https://staging.va.gov/my-health/appointments/?postLogin=true
2. Select Amputation, select Cheyenne.  
3. Time out.  Pause for about 15 minutes or so before submitting the request.    
4. Complete the request, validate devtool for errors  
 https://staging.va.gov/my-health/appointments/pending/0950c69a382867008fbd7478ad5f2522bf0dd67743e3508337b0c99ff3b04d3a?confirmMsg=true

### Actual Result
VAOS seemingly allows submission of a timed out request and shows "We received your request" confirmation screen.   However, devtools shows a 403 error and no request was actually submitted. 

### Desired Result
VAOS should time the user out completely and not allow to submit a request and/or show a successful submission message screen.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

![image](https://github.com/user-attachments/assets/2be979fa-1055-4c4e-8a68-f8fd4e117639)

**Comment by ldelacosta** [comment] 2024-08-21 15:31
@simiadebowale - please provide your comment here.

**Comment by simiadebowale** [comment] 2024-08-21 16:02
Looks like token expired and a refresh token was fetched with `refresh?type=idme`. Once token is refreshed appointments call is made again and it's successful. This is the expected behavior so we don't consider it a bug.

**Comment by ldelacosta** [comment] 2024-08-21 21:22
@mshatalov-va - this is not an issue on the FE. Let us know if you have any questions.

**Comment by ldelacosta** [comment] 2024-09-18 13:43
No issues to report. Closing out the ticket.

**Closed by ldelacosta** 2024-09-18 13:43 UTC
Labels: appointments, not-a-bug
