### ISSUE TITLE
Research Timestamp issues on the 10-10EZ

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16876] opened 2020-12-03 14:53 UTC
## User Story

As a stakeholder on the 10-10EZ
I want to understand why the backend timestamps do not align with when the forms were submitted
So that we can fix this behavior.

## Expected Behavior

-The goal of this ticket is to spend time understanding the root cause of the issue, and to propose a solution for how we might address it. 

## Acceptance Criteria

- [ ] Research documented in ticket
- [ ] Next steps (including LOE estimate) are propossed

**Comment by kevinmirc** [comment] 2021-01-14 16:22
RE:
> the backend timestamps do not align with when the forms were submitted

@mlighdc Can you please provide extra context on this issue?  Do we have any steps to reproduce this?

**Comment by mlighdc** [comment] 2021-01-15 04:37
Hi @kevinmirc, below is what Josh said. We can also hop on a call wit him.

************************************************
![image](https://user-images.githubusercontent.com/35788031/104681895-7108a180-56c1-11eb-93c5-f3935ce4a759.png)

**Comment by kevinmirc** [comment] 2021-01-15 15:07
Thank you, @mlighdc. Looking at [the code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/hca/enrollment_system.rb#L750), this `appDate` property is being set as a date in UTC, making it appear a day ahead of the timestamp.

```rb
# lib/hca/enrollment_system.rb:750
Time.zone.now.utc.strftime('%Y-%m-%d'),
```

We should clarify with Josh what timezone this date should be in. Our options are to:
1) use the timezone of the system of record (ES)
2) use the timezone of the applicant
3) select a timezone based on another property of the form (VA facility, applicant city, etc.)

**Comment by mlighdc** [comment] 2021-01-16 02:10
Sounds good @kevinmirc. I will start an email string with Josh.

**Comment by ala-yna** [comment] 2021-01-21 15:34
@kevinmirc, not sure if you saw Josh's response (was sent to your VA email).

![Screen Shot 2021-01-21 at 10.34.43 AM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/7d705aac-cd5a-42a4-8d67-01250e4af287)

**Comment by kevinmirc** [comment] 2021-01-21 16:39
Perfect. Thanks, @mlighdc! Will get started on updating this.

**Comment by kevinmirc** [comment] 2021-01-22 00:38
Closing this ticket since research is done. Here's the implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18856

**Closed by kevinmirc** 2021-01-22 00:38 UTC
Labels: backend, needs-grooming, vsa, vsa-caregiver
