### ISSUE TITLE
FE/BE Pair - Discovery - getCalculatedMonthlyIncomeApi failed in helper:

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#87486] opened 2024-07-02 17:27 UTC
### Discovery FE/BE pair investigation
[
Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/266691/?project=4&query=is%3Aunresolved+5655&statsPeriod=14d)

We're seeing an error in sentry that originates from the [Additional Income List](https://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist)

```getCalculatedMonthlyIncomeApi failed in helper: Error: No value destructured in response from getCalculatedMonthlyIncomeApi calculateTotalAnnualIncome```

## Acceptance Criteria

 - [x] **Scenario: Successful calculation of monthly income**
  - Given the input data is valid and complete
  - When the API call is made to calculate the monthly income
  - Then the response should contain a calculated monthly income value without any errors

**Comment by OptionSelect** [comment] 2024-07-10 17:28
Ongoing discussion in debt-devs-internal [here](https://governmentcio-fed.slack.com/archives/C04KC6YMDC0/p1720630071869739) in which suggested solution is BE null check added to the total_monthly_net_income variable calculation in income_calculator.rb in API section.

**Comment by OptionSelect** [comment] 2024-07-12 16:38
BE PR was merged [here](https://github.com/department-of-veterans-affairs/vets-api/pull/17475). Still testing on our end and monitoring sentry but this should fix this.

**Comment by OptionSelect** [comment] 2024-07-15 15:21
FYI the BE PR has yet to be deployed. Still monitoring. No luck reproducing in staging or locally still. I'd like to think we're ok.

**Comment by Tom-Davis** [comment] 2024-07-15 17:53
@OptionSelect can you move this to the proper column state (Maybe closed?)

**Comment by OptionSelect** [comment] 2024-07-16 17:12
Sorry, still not closed. Rolling due to not having a backend deployment by our devops team since last week. The code change has yet to reach production for us to verify we no longer see the error.

**Comment by OptionSelect** [comment] 2024-07-19 14:40
Cant tell if this has been deployed correctly as we are still seeing issues in sentry. Andrew raised concern about calculation so are back to diving in on this as!

**Comment by Dr-Pongo** [comment] 2024-07-22 16:15
Heyoo, just wanted to drop some updates on this ticket! 
A portion of these errors may be false positives being caused by a falsy check when destructuring the response from the endpoint. We included a fix that got merged today and should take effect after the deploy. The error message text has changed so we'll need to keep an eye out for the new error:
> No value destructured in response from getCalculatedMonthlyIncomeApi in checkIncomeGmt

Going to move to validate until the end of the week as we monitor Sentry

**Comment by Dr-Pongo** [comment] 2024-07-30 14:12
New error handling and income api calls seems to be clear in sentry. Saw a small single error pop, but does not appear to be indicative of a larger problem we can address. Closing out now that error handling is more robust!

**Closed by Dr-Pongo** 2024-07-30 14:12 UTC
Labels: bug, frontend, backend, discovery, vsa-debt
