### ISSUE TITLE
[BUG] Find a VA Form: Form link error message repeats in IE

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17941] opened 2020-12-30 15:31 UTC
## What happened?
As reported by Jen Lee:
"There appears to be a wee bit of unintended behavior on this error message experience on the Internet Explorer version of the form detail page. The error message does show -- correctly. But it also -- incorrectly -- continues to show the original 'download pdf' link. (On Firefox and Chrome, that download link is -- correctly -- replaced by the error message.)
So when you click on the download link again, you keep getting more of the same error message block repeatedly. Like this:"

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/53f316f6-fc7e-4d05-bf0c-a18dc5ef548e)

## Specs:
- Device: VA Government-issued equipment
- Browser: IE 11
- Test User: N/A
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/93f00c45-3ed5-4957-ae40-215492e04999)

## Steps to Reproduce

1. Log into VA network
2. Open 1VA-General Desktop (Citrix desktop)
3. Open IE 11
4. Go to https://www.va.gov/find-forms/about-form-21-0790/
5. Click on the _Download VA Form 21-0970 (PDF)_ link
6. Observe the "This form link isn't working" error message and see that the _Download VA Form 21-0970 (PDF)_ link remains visible immediately below.  
7. Click again on the _Download VA Form 21-0970 (PDF)_ link
8. Observe that the error message is rendered a second time, again with the _Download VA Form 21-0970 (PDF)_ link visible

## Desired behavior
The desired behavior, is for the error message to be rendered without the _Download VA Form 21-0970 (PDF)_ link below it, as shown below in Chrome 
![image (1).png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/fd61862b-6f0f-4b49-a554-1afc74317975)

## Acceptance Criteria
- [ ] User experience in IE 11 is the same as in Chrome

**Comment by zacharymorel** [comment] 2020-12-30 18:21
I need a VM for debugging purposes as a reminder:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by MarciMcGuireGCIO** [comment] 2020-12-30 18:23
@zacharymorel this may need to be requested on vfs-platform-support.  I was able to access the VA's Citrix desktop once I got my temporary PIV password.

**Comment by zacharymorel** [comment] 2021-01-15 17:15
Hopefully this will be fixed with the 400 error fix. 
See [14525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14525)

**Comment by MarciMcGuireGCIO** [comment] 2021-01-15 17:25
@zacharymorel that's great!  Let me know when it's on Staging and I'll give it a spin from a VM.

**Comment by zacharymorel** [comment] 2021-01-19 15:58
Test using: https://staging.va.gov/find-forms/about-form-10-0388/

**Comment by MarciMcGuireGCIO** [comment] 2021-01-19 16:02
@zacharymorel hmmm I'm seeing the same behavior as before.

**Comment by zacharymorel** [comment] 2021-01-19 16:04
> @zacharymorel hmmm I'm seeing the same behavior as before.

Oh sorry, that was a note to self haha.

**Comment by zacharymorel** [comment] 2021-01-22 17:04
Looking more at this. The error appears to be happing in the Google Tag manger script.

**Comment by zacharymorel** [comment] 2021-01-22 19:54
@MarciMcGuireGCIO for https://www.va.gov/find-forms/about-form-10-0388/ I have figured out that IE does not interpret % characters in the URL correctly like it's modern counterparts.

Currently, https://www.va.gov/find-forms/about-form-10-0388/ download PDF link is: **https://www.va.gov/vaforms/medical/pdf/10-0388%cover.pdf**. The URL needs to be corrected here in the CMS. 
What we are seeing with IE is the browsers native behavior. When the user hovers over the link, the browser reads the link to be invalid. Therefore, no link is shown in the  bottom left of the browser.

**Comment by jenniferlee-dsva** [comment] 2021-01-22 20:27
RE Zach's comment above for the bad 10-0388 PDF url - I see the same behavior in Edge, too. 

FWIW - The PDF url is not controled in the CMS. That comes directly from the source VA forms Microsoft database. 

The only way that PDF url can be fixed is by the form manager upstream. @MarciMcGuireGCIO or @johnhashva would need to contact the form managers and tell them what the issue is (you can't use % symbol in your file name) so they can change that at the source.

**Comment by jenniferlee-dsva** [comment] 2021-01-22 20:30
But in terms of this bug - the duplicative error message - that's resolved! So that looks great! Thx y'all.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-22 20:30
Thank you, @jenniferlee-dsva .  We'll get in touch with the form managers and bring this to their attention.   Oddly enough, in Edge on my Windows 10 machine, I do not see the behavior; the message appears saying that the link isn't working.

**Comment by jenniferlee-dsva** [comment] 2021-01-22 20:38
yes, that would be the correct behavior now, with Zach's error message fixed. :-) 

p.s. I can't tell if they're literally including the % symbol in the PDF file name or if they're using a blank space and just expecting it to resolve okay. but either way, they could probably fix this issue easily just by re-uploading the darn pdf file using hyphens - instead of blank spaces and weird symbols, lol.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-22 20:40
hard to say.  A space would typically render as an ASCII %20, so perhaps someone mistakenly entered a literal % in there.

**Closed** 2021-01-25 15:28 UTC
Labels: bug, dt-find-va-form, unplanned-work, vsa, vsa-decision-tools
