### ISSUE TITLE
Troubleshoot artifact uploads in GitHub Actions content-build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27680] opened 2021-07-21 17:16 UTC
## Details 

Artifact uploads to pass the build between jobs is taking too much time (and will make scaling impossible). Current idea is to try passing between jobs using persistent workspace

## Acceptance Criteria 

- [ ] GHA workflow retains its functionality without a delay introduced by artifact uploads

**Comment by dginther** [comment] 2021-08-02 15:45
https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/test-on-demand-runner.yml

On Demand Runner example workflow

**Comment by oseasmoran73** [comment] 2021-08-06 16:10
Due to the on-demand runner not able to use `matrix` from github action, creating a dockerfile to parallelize

**Comment by oseasmoran73** [comment] 2021-08-13 16:09
After doing investigation, while `matrix` from github action does not work well as intended for on-demand runners, we were able to spin up three on-demand runners to match our build for CI.

Daily deploy and content-release have been implemented and now in observation phase.

**Comment by oseasmoran73** [comment] 2021-08-17 16:18
Persistent/on-demand runners have been merged into content-build repository and have been performing well!

**Closed** 2021-09-09 14:58 UTC
Labels: tools-fe
