### ISSUE TITLE
[Spike] Investigate form526.disabilities[].ratedDisability.isInvalid

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#64394] opened 2023-08-28 17:11 UTC
This error has occurred 2005 in the last six months and as part of kicking off a larger effort to mitigate backend submission errors we want to pilot this error and land on a process of investigation, documentation and handoff to engineering. 

Refer to notes for process: https://docs.google.com/document/d/1GLkkwE5Ptk77dyC8m9sM0wnLQr6_5EIP0JmRo13DSlY/edit

Acceptance criteria:

- [x] Engineering to follow documented process for investigating error and provide context to how the error occurs, and what is the down stream system expects 
- [x] Engineering to update process as determined in this pilot
- [x]  Get approval to implement fix from VBA and VBMS

**Comment by NB28VT** [comment] 2023-09-06 16:35
May be related: discussion about contention classifications https://dsva.slack.com/archives/C04KW0B46N5/p1694017581240129

**Comment by nnicholas7** [comment] 2023-09-07 14:59
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEY1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8cf1be39aa39f2ebdd69b0a6fb1210ada0552829/Screenshot%202023-09-07%20at%2010.58.57%20AM.png)

Summary of Attempt at gathering recent 6 months data: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/black_hole_form_validation_research.md

**Comment by austinjprice** [comment] 2023-09-14 14:59
@micahaspyr for hand off

**Comment by SamStuckey** [comment] 2023-09-18 19:36
Just observing / noting this while poking this relative to some other work.  There is a nice summary of the cause of this issue from Slack.  

```
This issue happens because we query and store the result, of the veterans rated disabilities, and then never re-check or requery that before submitting, This CURRENTLY causes an error in auto-establishment submission AND the backup paper submission. HOWEVER soon (in a few sprints) this will not cause an error in the backup paper submission path.
Example situation that causes this error:
01/20/2023 - Vet starts filing 526 claims
01/20/2023 - During that filling out of the form, we query for rated disabilities for them to select, they select "Leg Pain"
01/20/2023 - We save the in-progress form for the vet so they can come back later to fill it out if they dont go the whole way to submission in this session, including the rated disability, "Leg Pain"
01/20/2023 - Vet abandons form half way
06/01/2023 - Vet comes back to complete the form, previously saved in-progress values populate so they can pickup where they left-off
06/01/2023 - Vet completes form and presses "Submit", the value for the rated disabilty string is "Leg Pain", however, in the time from when they started (01/20/2023), to now (06/01/2023), their rated disability was changed from "Leg Pain" to "Lower Leg Pain",  IN THE VA's system, so it gives that error (edited) 
```

Also of note, Kyle mentions that this will be fixed (6 months ago, so probably fixed now) in the back up path.  Might be worth checking with him if that happened as well.

cc @micahaspyr

**Comment by micahaspyr** [comment] 2023-10-03 16:38
Link to conversation with EVSS.  They are validating diagnosticCode and ratedDisabilityId.  Removing these validations should clear up the error from being seen.

https://dsva.slack.com/archives/C05UY68D22E/p1696343755744819

**Comment by micahaspyr** [comment] 2023-10-03 17:42
EVSS has created a ticket (EVSS-12713) to implement removing isInvalid values validation from.

**Comment by micahaspyr** [comment] 2023-10-03 19:55
Approval given by VBA and VBMS.  We'll proceed by 

Sending the Form
- if rated disability is success, proceed as normal
- if error returned
  - replace values of failing rated disabillities that have the isInvalid error
  - resubmit form

**Comment by micahaspyr** [comment] 2023-10-09 22:55
If EVSS is going to go the route of removing all validations on rateDisabilityId and diagnosticCode, options are:

1. EVSS sends warning back to vets-api, we log the warning and/or send an event to Datadog
2. EVSS logs the warning and maybe sets up a monitor on their end
3. We do nothing as the submission no longer errors for us

**Comment by SamStuckey** [comment] 2023-10-12 18:52
Removing myself from this, as I think my portion of the investigation is closed

**Closed** 2024-01-31 18:28 UTC
Labels: disability-experience, DBEX-Carbs
