### ISSUE TITLE
Onboard VFS users to Datadog

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50378] opened 2022-12-05 19:45 UTC
## Problem Statement 
Currently VFS teams have to use Loki for their logging and Grafana for their monitoring. This solution is cumbersome and doesnt provide the best solution to view logs to assist engineers with development efforts. 

How might we provide VFS engineers with a world class logging and monitoring solution.

## User Impact
This impacts VFS engineers and teams. Slow log queries, inconsistent experience.

## Where was this problem reported?
This is a step in the process of deprecating the old logging and monitoring solution. https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/issues/department-of-veterans-affairs/va.gov-team/49798

## What do we not know about the problem space?
The solution that likely will be selected here, onboard VFS engineers into Loki, has been working for Platform engineers for over 6 months.

## What (if any) research or discovery has been done?
None

## What is the acceptance criteria?
1. All VFS teams have been migrated off of Loki and onto an acceptable logging and monitoring solution

## How should we measure success?
We should aim for 100% of VFS teams to be moved off of Loki and into a better logging solution

## TODOs
- [ ] Convert this issue to an epic

**Comment by andreahewitt-odd** [comment] 2022-12-21 16:10
Closing because this is a duplicate of https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/issues/gh/department-of-veterans-affairs/va.gov-team/49798

**Closed** 2022-12-21 16:19 UTC
Labels: platform-project
