### ISSUE TITLE
[CDP] Review the 'Check details' link text 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#41052] opened 2022-05-06 19:00 UTC
## Issue Description
During the Combined Debt Portal's midpoint review, we received the following feedback:

- On the Current VA Debt page when there are current debts (eg. the No copays on record view), the "Check details" link text for current debts may be a little ambiguous. Two big potential impacts here are screen reader users (harder to differentiate which link goes where) and voice command users (speaking the command `Click check details link `will match with both links). Consider adding some extra text to make the link purpose a little clearer across every possible use case, eg. "Check details" becomes "Check compensation and pension debt details." If that's not a practical option, then when this goes to code we may still need some helping `aria-label` text for screen reader users.

---
## Tasks
- [ ] Sync up with Angela Fowler and our FE teammates to check how the 'Check details' link currently works in MCP 
- [ ] Document any adjustments to the `aria-label` text

## Acceptance Criteria
- [ ] The 'Check details' link has been reviewed and any changes have been documented in this ticket
- [ ] Follow-up ticket(s) are created as needed and linked in this ticket

**Comment by denisecoveyduc** [comment] 2022-05-13 16:32
This is a duplicate of work covered in #40927

**Closed by denisecoveyduc** 2022-05-13 16:32 UTC
Labels: design, vsa-debt, PTEMS, CombinedVADebt
