### ISSUE TITLE
Vanity URL Request: http://www.va.gov/verify-dependents

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#18638] opened 2021-01-15 17:49 UTC
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
As part of Dependency Verification, a special project for the Office of the CFO, we are reserving an easy-to-communicate URL which we can publish in outgoing messaging. The URL will resolve or redirect users to the Dependency Verification product, which will at minimum be a content page and maximally will redirect to the appropriate tool.

URL requested: http://www.va.gov/verify-dependents

### Requestor team info
steve-gov on behalf of Dependency Verification team

### Implementation date
Feb 1 2021

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : ASAP

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/verify-dependents | TEMPORARY REDIRECT TO <br> www.va.gov/view-change-dependents/view/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment] 2021-01-19 20:02
Notes and open issues to discuss:

Info per Steve K:
- Right now we are working under the assumption that the place a Veteran would verify their dependents is on the "view my dependents" authenticated tool page.  So MVP is to redirect the user from that vanity URL to the view my dependents tool page
- At some point the business might like to put an intervening landing page with some additional information at the vanity URL though. 

Open questions:
- Is the vanity URL to "Verify dependents" intended to direct users to the tool at  `/view-change-dependents/view` or if this is a new tool?
- If the vanity URL destination is an authenticated tool, what happens to users who are not authenticated?
- If the destination of the vanity URL could change over time, determine what impacts this has to the redirect implementation

 ![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/4845502c-835b-41c5-9c66-4651121c449f)

**Comment by mnorthuis** [comment] 2021-01-20 14:53
@steve-gov Here is what we have discussed:

User clicks or types in the vanity URL www.va.gov/verify-dependents/ which will redirect to url www.va.gov/view-change-dependents/view/
- If the user is authenticated, the user is taken to the View dependents tool at www.va.gov/view-change-dependents/view/ where they can complete their task
- If the user is not authenticated, the user is taken to the View/change dependents static landing page at www.va.gov/view-change-dependents/ where they will find a CTA to login to get to the View dependents tool and complete their task.

For the unauthenticated flow, that will need to be confirmed with the team developing the tool to make sure this is how the flow is being built.

In addition, it seems as though the redirect placed on the vanity URL may need to be a temporary redirect in case traffic needs to be routed to a different destination (i.e. different landing page) in the future.

**Comment by steve-gov** [comment] 2021-02-04 19:22
This is correct and confirmed.

**Comment by mnorthuis** [comment] 2021-02-04 20:25
@lunascoop @DanielleThierryUSDSVA This is a request for a vanity URL.  This redirect should be established as a TEMPORARY REDIRECT, not a 301, as it may change over time as the dependents experience evolves.

**Comment by lunascoop** [comment] 2021-02-04 20:29
@kelsonic @ncksllvn this redirect can be implemented now. Please see Mikki's last comment.

**Comment by lunascoop** [comment] 2021-02-05 16:34
Redirect has been implemented. Closing ticket.

**Closed by lunascoop** 2021-02-05 16:34 UTC
Labels: frontend, ia, vsa, vsa-public-websites, vsp-product-support
