### ISSUE TITLE
[FE] - Create a generic error state for when direct deposit is down

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10732] opened 2020-06-29 17:45 UTC
## Background
We need to create an error state for when direct deposit is down

Related Design Ticket: #5959

## Specs/Copy

**We can't access your direct deposit information right now**

We're sorry. Something went wrong on our end. Please refresh this page or try again later.

![Screen Shot 2020-06-29 at 11.35.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ea467e9d-740a-4611-b1ab-90d16f607d8f)

## Tasks
- [ ] Create error state

## Acceptance Criteria
 - [ ] Has been built and reviewed by Matt or Tressa

**Comment by erikphansen** [comment] 2020-06-29 18:27
I'm going to close this one as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/9819. I already have [a PR open](https://github.com/department-of-veterans-affairs/vets-website/pull/13295) that addresses this new ticket and https://github.com/department-of-veterans-affairs/va.gov-team/issues/9819.

**Closed by erikphansen** 2020-06-29 18:27 UTC
Labels: direct deposit, frontend, needs-grooming, profile, vsa-authenticated-exp
