### ISSUE TITLE
Add incident response documentation for application teams 

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#72087] opened 2023-12-15 21:11 UTC
### Description

As part of the on-going VA.gov Code Yellow effort, we have developed documentation to application teams to help provide guidance and context when a watch officer contacts them about an incident. We'd like to get this documentation added to the platform site in an appropriate location. I've added it to the body of this issue, but can also provide it in word format if that's easier for your workflow. Please feel free to edit for clarity/presentation and send any questions my way.

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO (Code Yellow)

- - - - - - - - - - - - - - - - - - - - - - - - - - 
New document
- - - - - - - - - - - - - - - - - - - - - - - - - - 

# I just got an incident notification or reliability alert, now what?

### Determine the incident priority using this matrix:

<table>
<thead>
<tr class="header">
<th>Service<br />
Type</th>
<th>&gt; 1000 Users Affected/day</th>
<th>&gt; 100 Users Affected/day</th>
<th>&gt; 0 Users Affected/day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tier 1</td>
<td>P1</td>
<td>P2</td>
<td>P3</td>
</tr>
<tr class="even">
<td>Tier 2</td>
<td>P2</td>
<td>P3</td>
<td>P4</td>
</tr>
<tr class="odd">
<td>Tier 3</td>
<td>P3</td>
<td>P4</td>
<td>P4</td>
</tr>
</tbody>
</table>

For incidents rated P1:

  - Determine whether the incident priority is correct. If the priority should be downgraded, adjust the incident priority level and
    document your reasoning on the incident. Some reasons it might be downgraded are:
      - The alert is a false positive
      - The number of affected users does not reach the P1 severity level
- Declare an incident in Datadog if one has not already been created and rate it with severity level 1. This will:
      - Communicate to your team that the issue needs to be resolved ASAP.
      - Allow others who might reach out to notify you of an incident to see that you are already aware of it and actively working to resolve it.
      - Create a record that your team can use later - i.e., as part of a retrospective
  - Identify the person that will serve as the **Incident Commander** (note – this is not the person that does all the work to resolve the incident, but the person that coordinates communications with stakeholders and reports progress) and ensure that that person is listed on the Datadog incident.
  - Identify the **Lead Engineer** for resolving the incident (note – this is the person that will lead the investigation into the root cause of the issue) and ensure that person is listed as a responder of type SME on the Datadog incident.

## Resolution timeline

Use this matrix as a guideline to prioritize your team’s time and actions:

| Incident Priority | Resolution Timeline | Updates to reporter and VA Product Owner | Temporary monitoring adjustments |
| ----------------- | ---------------------- | ---------------------------------------- | ------------------------------------------------ |
| P1                | ASAP - please dedicate any team member’s time who can fruitfully work on the issue, including off-hours | Every 3 hours until resolved             | N/A                                                                                              |
| P2                | Within the current week/sprint                                                                          | Every business day until resolved        | N/A                                                                                                                                                                                         |
| P3/P4             | Within the next 2 sprints                                                                               | Upon resolution                          | If the triggered monitor can be adjusted to ignore only the specific issue, do so and add an issue or acceptance criteria to restore the monitoring before the issue is considered resolved |

### To Veterans

Use appropriate tooling and communication channels to ensure Veterans are aware of the issue as necessary and do not spend time doing work that will be lost. This may include:

  - Adding a [downtime notification](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications)
  - Disabling a given app or feature
  - Direct communications such as emails, other alerting, etc.

### To Stakeholders

Ensure that your VA points of contact are informed and aware of the issue, its impact and expected resolution timeline. Please include a link to issues and/or slack conversations so that they may keep up to date on progress.

### Determine the root cause

The incident commander should create a document to capture notes, discussion and other items (screenshots, log messages, etc.) that can act as a part of the record of the incident for later reporting to stakeholders, and to assist the team when a retrospective is conducted.

Don’t be afraid to enlist help from Platform support and/or OCTO engineering points of contact.

Once you’ve determined a cause, proceed with resolution according to the general category of cause:

### Resolve the issue

<table>
<thead>
<tr class="header">
<th>Cause category</th>
<th>This might look like</th>
<th>How to resolve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>External service bug/outage</td>
<td><ul>
<li>Greatly increased latency, particularly when many requests time out</li>
<li>Failing http.request spans in APM</li>
<li>Logs of the form: Outage detected on &lt;service&gt; beginning at &lt;timestamp&gt;</li>
</ul></td>
<td>For P1 incidents: work with your OCTO point of contact to ensure that the Major Incident Management process has been triggered. In general, communicate with the service owners and work together to ensure that the root cause is addressed or has a plausible plan &amp; timeline to be addressed.</td>
</tr>
<tr class="even">
<td>App bug or design issue</td>
<td><ul>
<li>Other apps &amp; services working normally</li>
<li>RUM/Sentry errors</li>
<li>Failing rack/rails spans in APM</li>
</ul></td>
<td>Darn, can’t blame it on something else! Work to resolve the root cause. Ensure that all changes are tested with unit and end to end tests that will detect re-occurrence. Be sure to consider whether UI changes are necessary or could aid in preventing the issue in the future.</td>
</tr>
<tr class="odd">
<td>Internal service outage</td>
<td><ul>
<li>Failing rack/rails spans in APM</li>
<li>Many other apps &amp; services experiencing issues</li>
</ul></td>
<td>Create a support request with category “VA.gov incident” in #vfs-platform-support – trigger Pagerduty if necessary.</td>
</tr>
<tr class="even">
<td>Improperly configured monitor</td>
<td></td>
<td>Sometimes an incident just ain’t an incident. Adjust the triggered monitor in a manner that will prevent re-notification for <em>only this specific issue</em>. Ensure that another engineer reviews the changes and confirms their specificity.</td>
</tr>
<tr class="odd">
<td>Cosmic rays / Karmic justice / other incidents without clear causes or resolution</td>
<td></td>
<td>Ensure that any affected Veterans are made whole. This might include manual resubmission of applications or reaching out via approved communications channels to explain the incident and how they can re-start the task they were trying to complete.</td>
</tr>
</tbody>
</table>

## Wrap things up

  - Post-mortem:
      - For P1 & P2 incidents, ensure that a formal [post-mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems#postmortems) is created and shared with all relevant stakeholders.
      - For P3/4 incidents, an informal post-mortem shared via email or Slack is sufficient. Include the following information:
          - what happened
          - why it happened
          - what we’re doing to prevent it from happening again
  - Ensure that the reporting watch officer and your team’s VA points of contact are aware of the incident resolution and given a chance to review the post-mortem

**Comment by acrollet** [comment] 2023-12-18 15:07
Thanks @johnny-jesensky-adhoc , any feedback is welcome!

**Comment by BSmolensky** [comment] 2023-12-21 01:26
@acrollet - In the "First follow this checklist section" it appears as though there are only steps for incidents rated P1. Can you please provide the steps **For Incidents Rated P2**, **For Incidents Rated P3**, and **For Incidents Rated P4**? If, in fact, all the steps are the same as P1's steps, let us know and we can edit the heading to reflect that. We are all working hard to get this done asap. Thanks for your help!

**Comment by BSmolensky** [comment] 2023-12-21 15:01
@acrollet - I am not sure I am seeing the update. Can you add steps for P2-P4 below?
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Determine the incident priority using this matrix:</h3>
ServiceType | > 1000 Users Affected/day | > 100 Users Affected/day | > 0 Users Affected/day
-- | -- | -- | --
Tier 1 | P1 | P2 | P3
Tier 2 | P2 | P3 | P4
Tier 3 | P3 | P4 | P4

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Declare an incident in Datadog if one has not already been created and rate it with the incident's severity level. If one already exists, determine whether the incident priority is correct. If the priority should be downgraded, adjust the incident priority level and document your reasoning on the incident. Some reasons it might be downgraded are:<br style="box-sizing: border-box;">- The alert is a false positive<br style="box-sizing: border-box;">- The number of affected users does not reach the given severity level</p><h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 14px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Why use Datadog Incidents?</h4><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">incidents allow others who might reach out to notify you of an incident to see that you are already aware of it and actively working to resolve it.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">incidents help keep a single, public record of events &amp; actions that your team can use later - i.e., as part of a retrospective</li></ul><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For incidents rated P1</h3><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Communicate to your team that the issue needs to be resolved ASAP.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Identify the person that will serve as the<span> </span><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Incident Commander</strong><span> </span>(note – this is not the person that does all the work to resolve the incident, but the person that coordinates communications with stakeholders and reports progress) and ensure that that person is listed on the Datadog incident.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Identify the<span> </span><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Lead Engineer</strong><span> </span>for resolving the incident (note – this is the person that will lead the investigation into the root cause of the issue) and ensure that person is listed as a responder of type SME on the Datadog incident.</li></ul>

**What are the steps for incidents rated P2, P3, and P4?**

**Comment by johnny-jesensky-adhoc** [comment] 2023-12-28 17:04
Hi @acrollet, thank you so much for your help creating the content for this page, and working with us for final refinements and validation. This page is now live [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/incident-response-documentation-for-application-te). Moving this to _Done_.

Let me know if you have any final questions!

FYI @BSmolensky

**Closed** 2024-01-09 14:20 UTC
Labels: platform-content-team, documentation-support, pw-footer-feedback
