### ISSUE TITLE
Analytics Implementation or QA Support for [Health Care Experience - Check In]

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#27983] opened 2021-07-28 14:52 UTC
# Google Analytics Implementation or QA Request

## Description
- Is this request for Google Analytics implementation or QA?

We are a new product and have not been set up for GA yet. We are tracking events, but they not getting logged yet. This is a request for implementation. This is for a new Health Care Product called `Check-in`

- Who is this request for?

    Mark Dewey, FE Engineer on the Health Care Experience Team, 

    
- What team/project is this work for?

- Health Care Experience Team
- Check-In Application
    
- Provide the Domain where Google Analytics needs to be implemented
    www.staging.va.gov
    www.va.gov

    
    Identify if PII is passed in URL or title tag - No PII or PHI is being tracked
    
- Please provide any upcoming deadlines or important milestones
    Unknown

- Please provide website interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
```
/health-care/appointment-check-in/?id=xxxxxx
/health-care/appointment-check-in/update-information
/health-care/appointment-check-in/details
/health-care/appointment-check-in/see-staff
/health-care/appointment-check-in/complete
/health-care/appointment-check-in/error
```
    

    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
 - The user selecting each of these buttons
 - Loads the app with a invalid token
 - Update information Selection
 - Clicked the button to "Check In"

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Unauthenticated, but needs a user needs an appointment to go through the flow. We are currently in the process of creating testing docs and processes

- Additional Comments

    - We should already be tracking these events with the prefix `check-in-`. Not sure what prefix I should be using. 

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by joanneesteban** [comment] 2021-07-28 17:43
@mdewey Hi there! Thanks for filling this out. Do you have a launch date ready for this initiative?

**Comment by mdewey** [comment] 2021-07-28 20:04
I know we are looking at an early August release, but our PM @jparker0425  would know more.

**Comment by jparker0425** [comment] 2021-07-29 16:57
Hey @joanneesteban and @mdewey, as of right now we are looking to launch sometime during the week of 8/9 - 8/13. We are still coordinating the launch timeline with the pilot site, so I will hopefully have a more solidified date as we get closer.

**Comment by jennaouellet** [comment] 2021-08-04 14:30
Hi @mdewey! In the ticket it is mentioned that you are currently in the process of creating testing docs and processes - is that ready or is there a specific testing procedure I should be following to create an appointment?

**Comment by mdewey** [comment] 2021-08-04 19:54
Hey @jennaouellet! We do have testing docs now, but the testing process is a bit involved. It depends on how much you will be testing. 

If you only need a few appointments, I can create appointments (and links) for you for when you are ready to test and validate. For this. Just reach out in slack for a quicker response. 

The long answer is that we can set you up as a test user in our system, you will need a valid phone number and you need to run some `curl` statements on the VA network to create your appointments. If you are doing tons tests this might be the better route and I can put you in contact with the right team members to get you set up. Here is the full [testing document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-data-setup.md) if you want to check it out

Let me know how you want to proceed :-)

**Comment by jennaouellet** [comment] 2021-08-06 16:19
@mdewey would this be considered a form or are you looking for tracking it as an application? Only the form events should have prefixes. If this is indeed a form event we have dataLayer events outlined here:  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md  Also, if you are using the forms system, some of these events may be baked in.

For button clicks you can reference global tags here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/ga-events-data-dictionaries.md#:~:text=Data%20Layer%20Specification-,Buttons,-Global%20event%20listener

We also have generic API events now and will update shortly with those.  It would look like these (with an optional latency parameter):

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26703#issuecomment-876037933

Are there any additional items you are trying to track? Also can you set up a few test appointments and provide the entry link? I don't believe we will need to create additional appointments.

Thanks!

**Comment by mdewey** [comment] 2021-08-09 14:47
Great questions @jennaouellet, let me try to shed some light

1. I do not think this is a traditional form. We are not using the forms system, so we will be tracking this as an application. 
2. I will update our API calls to match the comment you link. Thank you! 
3. The main items we are trying to track are: 

- Every button click. We have a total of 3 buttons. We want to know when a user clicks on any of those buttons. **question** what `event` should I use here? The example is `cta-button-click`, is there a standard list or can that be custom per app / per button?
- We have a `Back to previous page` Link that functions like bread crumbs that we want to track when a user clicks the link. **question**. Should I use the breadcrumb event since this behaves like a bread crumb?
- Every page load and the user's page flow through the app
- If/Where/when users drop off. 

Based on your answers to the few questions, I will make the updates and get it into staging and then I can create a few appointments for you to test :-)

**Comment by stephenBarrs** [comment] 2021-08-16 16:03
@joanneesteban Thanks for all your help with this!  Something we have concerns with as we pilot this app is the cellular and wifi connectivity the users will have inside the VAMC where they will be using the app.  I am wondering what connectivity data we will get 'for free' from GA and/or if there is additional connectivity data we could capture specifically in the frontend. If there is a doc somewhere that describes that I am happy to read through if you can link it!  Initial thoughts would be collecting: 

- Cellular or WiFi connection
- Cellular Carrier
- Connection speed or related metric

@mdewey @batemapf @jparker0425  what other metrics might we want to know related to device connectivity?

**Comment by jennaouellet** [comment] 2021-08-16 18:53
Hi @stephenBarrs ! We are looking into this and I will update with additional details. Right now page load is tracked in GA out of the box, but the network connection would need to be passed in as a datalayer variable. It doesn't appear that any other applications are doing so currently, so I'm doing more digging into the best practice to take. Thanks!

**Comment by jennaouellet** [comment] 2021-08-17 15:17
@stephenBarrs To give an update - the built-in GA data of page load time and user browser/OS will be the only capturable data in GA relating to connectivity. These are tracked automatically and won't require additional configuration. Unfortunately network and service provider are not trackable in GA due to privacy concerns.

**Comment by mdewey** [comment] 2021-08-20 20:20
Hey @jennaouellet, Moving our conversation  to this ticket (https://dsva.slack.com/archives/CBU0KDSB1/p1629402733207100). We would like to track the time it takes our API calls to complete. How can we store those in GA? 

Can you advise?

**Comment by mdewey** [comment] 2021-08-25 14:35
So, it appears we are tracking events (yay!) 

I still have a few outstanding questions:

- On one of our pages we have two buttons, both are being tracked using the same `cta-button-click` event. Is there a way to differentiate between which button was clicked?
- We are currently logging API calls and their success and failure. We want to track two more pieces of information on the success/failure of an API. We want to track the time the call took and a unique id for the call. How can we track this using GA? 
- We also are trying to track when a user drops off the app and the user flow through our app. How can we see this in the GA dashboard?

**Comment by jennaouellet** [comment] 2021-08-30 15:39
@mdewey the new custom dimension for the API call ID is api-request-id. This can be used in addition to the api_latency_ms dimension mentioned above

**Comment by stephenBarrs** [comment] 2021-08-31 14:32
Hi @jennaouellet!  Should I be able to see the custom dimensions defined above when building a GA Dashboard or digging into events in GA?  So far I have not been able to see how I can see them.  Our [draft dashboard is here](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/LLQpw2NQR-Wlnjz0-KX6PQ/a50123418w177519031p176188361/_u.date00=20210826&_u.date01=20210831/) for reference.

**Comment by mdewey** [comment] 2021-08-31 14:52
Thanks for the responses @jennaouellet! 

For the buttons, the text is different, they are `yes/no` buttons (UI: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/agzELqr/play), each with their own event. 

And for the API, that all makes sense, so the API event will look like: 

``` json 
{
event: 'api_call',
api-name: 'My awesome API ',
api-status: 'success'
api_latency_ms: 34524,
api-request-id: "0431b67f-b40f-4820-9ca2-05f931045c28"
}
```

Does that look right? Even the underscores vs hyphens?

**Comment by mdewey** [comment] 2021-08-31 20:27
I am logging these events 

@stephenBarrs  and @joanneesteban  How does this look? 

![Screen Shot 2021-08-31 at 4 26 51 PM](https://user-images.githubusercontent.com/1793923/131571256-7ba35bd9-e038-454f-9768-0a87837da37b.png)

**Comment by stephenBarrs** [comment] 2021-09-03 18:19
@jennaouellet Hello!  Wondering if someone can take a look at the widgets I am setting up to display the data from the `api_call` events.  I am trying to model what the Claims team did, but using a table.  Substituting the Claims team event in the RegEx does display that data, but I am not able to display the Check In data.  I am using the same RegEx in another widget so I am confident in that, but there is a good possibility I am messing something up, or not understanding exactly how we can use this data.  [Here is the dashboard in Staging](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/XVsFdHWbTSaz8L18Vj8ZHQ/a50123418w178298118p176884211/_u.date00=20210903&_u.date01=20210903/) and screenshots of the two widgets.  Thanks! 

Average API Latency
![image](https://user-images.githubusercontent.com/2481110/132049902-daba98a2-2a7b-4492-b9c3-9c3985ffbc87.png)

API Latency
![image](https://user-images.githubusercontent.com/2481110/132049979-86f75a8f-69d2-4506-9abf-ad9fdbdda094.png)

**Comment by jennaouellet** [comment] 2021-09-08 14:43
@stephenBarrs your dashboard looks good to me - the issue is just that the API latency update hadn't been published yet in GTM when the data was being collected. I'll be on the lookout for data flowing in and will monitor the dashboard.

**Comment by jennaouellet** [comment] 2021-09-13 18:36
@mdewey the latency custom metric has been updated to be consistent with the dashes in the API request ID and will not be using underscores, see below for formatting:

{
     event: 'api_call',
     api-name: 'Name of API',
     api-status: 'started',
     api-latency-ms: 20000,
     api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
}

**Comment by joanneesteban** [comment] 2021-09-22 17:30
@stephenBarrs hello! The Analytics team would like to check in on this ticket. Do you need additional support for your report?

**Comment by stephenBarrs** [comment] 2021-09-23 13:05
Hi @joanneesteban thanks for checking in!  I have not been able to figure out how to access the data fields within the event in our dashboard, but have not had time to look back into it for the last week or so.  I also opened a support ticket due to what appeared to be anomalies with our data but @bsmartin-ep is thinking it is related to the sampling of the currently small data set.  I will prioritize time to look and see if I can see the `api-latency-ms` data field in the check in experience data now.

**Comment by bsmartin-ep** [comment] 2021-10-06 17:22
I think you said we are OK to close this one @stephenBarrs but let me know if that is not the case.

**Closed by bsmartin-ep** 2021-10-06 17:22 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle, gtm, collab-cycle-review
