### ISSUE TITLE
E2E 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#66228] opened 2023-09-25 15:29 UTC
- medallia research
-  perigean research/what's realistic 
-  @austinjprice  please figure this out

**Comment by austinjprice** [comment] 2023-09-25 20:42
closing as duplicate of https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/65939

**Closed by austinjprice** 2023-09-25 20:42 UTC
Labels: Epic, disability-experience, DBEX-Carbs
