### ISSUE TITLE
[Bug] Notice of Disagreement - Review page section-header persistent edit-caution

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#25061] opened 2021-05-21 02:30 UTC
## What happened?
On Staging **[Request a Board Appeal form](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)**, **Review** page, **Issues for review** section, after adding an issue, the _main_ section-header's edit-caution persisted even after all relevant subsections' required fields had been completed.

**NOTES**: 
- You'll notice in the video below that selecting a "recent" Decision date (after 2/19/2019) for the added issue still displays an Opt-in subsection -- this is related to #24993.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [use any of the following]
  - `vetsgov+test239@id.me` (Medge)
  - `vetsgov+test233@id.me` (Cara)
  - `vetsgov+test238@id.me` (Nerea)

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Issues for review** [add y/n] page, completing required fields and clicking **Continue** on the way.
- On  **Issues for review** [add y/n] page, choose **No**, then **Continue**.
- Advance to **Review** page, completing req'd fields and clicking **Continue** on the way.
- On **Review** page, expand **Issues for review** section, then add an issue:
  - In **Additional issues for review** sub-section, click **Edit**, choose **Yes**, then **Update page**.
  - In **Add issues for review** subsection, click **Edit**, complete **req'd fields**, then **Update page**.
  - In your **<added issue>** subsection, click **Edit**, choose an **area of disagreement**, then **Update page**.
- Observe that, although subheaders' edit-cautions have returned to normal, the **main header**'s edit-caution persists despite all required fields having been completed.
- Click **...privacy policy** checkbox, then **Submit**.
- Observe error-message citing missing/invalid information.

**Video capture**:

https://user-images.githubusercontent.com/587583/119072009-a12dbd00-b99f-11eb-9995-08d0ff0f716b.mp4
  

## Desired behavior
**Issues for review** main section-header's edit-caution should return to normal after adding an issue [i.e., all subsections' req'd fields have been completed].

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by Mottie** [comment] 2021-05-25 14:42
I don't think this can be fixed with our current form system. The header is displaying the error state because modifying selections or adding a new issues adds or removes an area of disagreement page which is required. The subheader for the area of disagreement page isn't consistently being highlighted.

The validation library we use doesn't appear to properly validate errors across multiple pages. I'll bring up this issue with the design system team to see if there is a possibility of a work around.

**Comment by tlei123** [comment] 2021-05-26 00:02
hi @Mottie !  i just did a quick check on Staging w/ Mac Chrome, and this wasn't replicable anymore...

I doubt if it fixed itself...  Do you think it might be related to your fix for #24990 ?

**Comment by Mottie** [comment] 2021-05-26 12:26
I did merge in a fix that maintains the area of disagreement selections for previously checked items (https://github.com/department-of-veterans-affairs/vets-website/pull/17336). Before this fix, the area of disagreements would _all_ be cleared when toggling a selected item. It also included a change to the schema that will show the error alert message if no issues are selected, but if I recall correctly, it won't highlight the header/sub-headers showing where the issue is located. This is related to a problem in the form-system, and I'm not sure if there is a way to fix it.

**Comment by tlei123** [comment] 2021-05-26 16:21
> This is related to a problem in the form-system, and I'm not sure if there is a way to fix it.

@pjhill , it sounds like @Mottie 's kinda blocked here.  Would you say Adding an issue on the Review page [as opposed to Adding it upstream on the form-page] an edge case?

**Comment by tlei123** [comment] 2021-05-26 16:25
@Mottie , per Peter, you can start w/ VSP F/E Tools team re. Form System.  I'll keep watching this thread, but pls. cc-tag me on any Slack convos w/ them.  Thx much!

BTW @vhenry07, FWIW, we have no **Must** (launch-blocker) items in the [QA-Feedback tic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25212), BUT this bug DOES block form-submission.

**Comment by Mottie** [comment] 2021-06-02 20:02
Ok, just to clarify. The problem shown in the video has been fixed... hearing loss will retain it's previous settings. The thing I can't fix without a platform code change is highlighting the headers when there is an error. Please see steps to reproduce this problem in https://github.com/department-of-veterans-affairs/va.gov-team/issues/25573

**Closed** 2021-06-08 19:04 UTC
Labels: NOD, bug, frontend, vsa-claims-appeals
