### ISSUE TITLE
SSOe login repeats when visiting some pages

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#15351] opened 2020-10-27 17:23 UTC
Reproduction steps:
1. Go to https://www.va.gov/sign-in 
2. Click "Sign in with My Healthevet"
3. Login using credentials mhvtestvet01 ; pw in slack in **#vagov-cerner-launch-coordination** 
4. Go to https://www.va.gov/health-care/schedule-view-va-appointments/
5. Click on go to the blue "Go to My VA Health" button. 
6. User is prompted to login again. 

Expected behavior: user should be taken into My VA Health directly without reauthentication. 

Reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/VAgovSSOBrainDump.md

**Comment by joeniquette** [comment] 2020-10-27 18:29
the source code clear-session is. redirect: `curl https://patientportal.myhealth.va.gov/clear-session --output page.html`

which results in
`<html><body>You are being <a href="https://patientportal.myhealth.va.gov/local-logout">redirected</a>.</body></html>`

that `redirect` button goes to https://patientportal.myhealth.va.gov/local-logout

which when followed, is a session activity pause:

![Screen Shot 2020-10-27 at 12 18 16 PM](https://user-images.githubusercontent.com/71290526/97345347-5102d800-1860-11eb-8aaf-74fa4a2507b4.png)

Also to note, I am seeing a CORS issue in the screen capture:
![Uploading Screen Shot 2020-10-27 at 12.44.36 PM.png…]()

**Comment by mchelen-gov** [comment] 2020-10-27 18:41
@joeniquette interesting, how are people ending up at https://patientportal.myhealth.va.gov/clear-session ?

**Comment by lalexanderson-dsva** [comment] 2020-10-27 19:15
"clear-session" is in there to protect against the use case we saw in Columbus whereby a session might persist in the My VA Health Portal after a user has signed out from VA.gov. It ensures that there is a new clean session when you go to my va health. We've been using that url for months without issue.

**Comment by lalexanderson-dsva** [comment] 2020-10-27 19:18
We hypothesize that the issue is either related to: 
1. How the front end is generating the keepalive request 
2. How IAM is accepting or not accepting it. 

<img width="1440" alt="Screen Shot 2020-10-27 at 2 42 51 PM" src="https://user-images.githubusercontent.com/32132681/97351048-a098d200-1867-11eb-9b67-4ab7a992fbb4.png">

**Comment by lalexanderson-dsva** [comment] 2020-10-27 19:35
@boris-ning-usds & Damien are investigating if last night's DNS issues ( 8:45-11:30pm) had any impact.

**Comment by mchelen-gov** [comment] 2020-10-27 19:40
@lalexanderson-dsva can you confirm what steps got you to that page?

**Comment by joeniquette** [comment] 2020-10-27 19:45
Another Example of failure to fetch due to CORS:
![Screen Shot 2020-10-27 at 2 46 42 PM](https://user-images.githubusercontent.com/71290526/97354151-5c0f3580-186b-11eb-88e0-8c5d165cdfbf.png)

**Comment by lalexanderson-dsva** [comment] 2020-10-27 19:55
> @lalexanderson-dsva can you confirm what steps got you to that page?

@mchelen, the steps are outlined at the top of the issue.

**Comment by mchelen-gov** [comment] 2020-10-27 21:09
sounds like the CORS errors have gone away, potentially due to caching. root cause is believed to have been CORS response headers coming from eauth preventing browser from loading resource
slack thread: https://dsva.slack.com/archives/C0190MTGNUE/p1603825027304000

**Comment by patrickvinograd** [comment] 2020-10-28 03:42
We saw the CORS issue reoccur, for some users/some browsers. Specifically it was still an issue for the mhvtestvet01 account on Chrome this evening.

**Comment by patrickvinograd** [comment] 2020-10-28 03:54
## Background:

VA.gov sends a `fetch` request to eauth.va.gov/keepalive. That request is subject to browser CORS policy. Normally this works fine. We see the expected pattern of an OPTIONS preflight request, followed by the GET request, and the response includes all the expected `Access-Control-Allow-*` headers, as well as the expected headers that tell us the state of the SSOe session - a `session-alive` header and some `va_eauth_xyz` headers.

## Problem Behavior:
We are seeing sporadic but frequent cases where one of the `/keepalive` requests fails. There are a couple interesting things:
- It shows as a CORS error in the console, due to no `Access-Control-Allow-Origin` header.
- The "Timing" tab for the failed request only shows any timing information for the request in the "Stalled" state - no DNS lookup, no SSL negotiation, just Stalled.
- However, we do see some response headers. Just incomplete ones. Damien from the IAM team indicated that their WebSEAL proxy may be generating a partial response without passing the request on to the application server, because the request is missing some expected headers. But that indicates that the request seems like it is getting at least as far as that proxy server, despite what the Timing tab says.
- The failed "GET" shows up in the dev tools network tab list before the "OPTIONS" preflight request, which doesn't make much sense - it should be preflighting then doing the GET.
- There is an "Access-Control-Max-Age" header which could cause either the CORS information to be cached but we don't really have a good handle on where/when that's being cached.
- A given browser session will exhibit this failure, frequently immediately after logging in, or after triggering a sign-in to Cerner, which bounces through www.va.gov/sign-in as part of its authentication process. But we have seen subsequent keepalive requests in the same session (either triggered by code or in the JS console) succeed. 
- We have seen this in Chrome and Firefox.

## Theories:
- The request could somehow be in the "Stalled" state due to hitting a max number of connections. But our understanding is that the max connections are per-server and there shouldn't be a ton of code hitting the eauth.va.gov domain at the point in time when the keepalive is issued.
- Something something caching. Very anecdotal evidence suggests that clearing browser caches could improve the behavior but we don't have a firm grasp on that.

## Reproduction Steps:
1. Open browser dev tools, make sure "preserve log" is checked in network tab.
2. Go to www.va.gov/sign-in. Sign in.
3. Check console for CORS error, and/or observe the `keepalive` requests that happen after the sign in process is complete. You should see one failed request.

**Comment by patrickvinograd** [comment] 2020-10-28 03:59
<img width="684" alt="Screen Shot 2020-10-27 at 8 33 15 PM" src="https://user-images.githubusercontent.com/20694532/97389123-e5882d00-1896-11eb-8acb-3a9b3e216156.png">

Stalled GET request:
<img width="699" alt="Screen Shot 2020-10-27 at 8 32 49 PM" src="https://user-images.githubusercontent.com/20694532/97389184-02bcfb80-1897-11eb-84d1-3880c0c6d100.png">

Failed GET request headers - note request doesn't even display a "Remote Address" IP:
<img width="687" alt="Screen Shot 2020-10-27 at 8 32 34 PM" src="https://user-images.githubusercontent.com/20694532/97389245-1bc5ac80-1897-11eb-962d-86f27d0b24fc.png">

Successful keepalive GET request for comparison:
<img width="680" alt="Screen Shot 2020-10-27 at 8 32 01 PM" src="https://user-images.githubusercontent.com/20694532/97389307-3ac43e80-1897-11eb-97b2-cbded3cf395e.png">

**Comment by annaswims** [comment] 2020-10-28 14:25
Try postman -[ I saw something similar recently ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14427#issuecomment-704285824) 

In my case most requests were getting through, but some were being rejected by the load balancer. The requests that were being rejected by the load balancer lacked the `Access-Control-Allow-Origin` header. The response was useful (http 418, with an html body), but in chrome it appeared as `net::ERR_FAILED`.  It was only when I started using postman I saw the actual response.

**Comment by lalexanderson-dsva** [comment] 2020-10-28 14:36
This morning i have tested: 
- Chrome (without success) 
- Safari (successful)
- Edge (successful)

**Comment by joeniquette** [comment] 2020-10-28 14:38
I also tested this morning with my dslogon account:

- chrome (without success) logs to follow
- Firefox (successful)

**Comment by mchelen-gov** [comment] 2020-10-30 15:38
Proposed solution:
https://www.ibm.com/support/pages/webseal-error-hpdac0977e-unexpected-xalan-processor-exception-was-caught-during-rule-processing-error-message-result-truncated-increase-xslt-buffer-size-was-returned-exception


increase `xslt-buffer-size` from `4096` to `8192` in WebSEAL

**Comment by lalexanderson-dsva** [comment] 2020-10-30 15:46
Summary from last night via @patrickvinograd 

[6:32 PM] Vinograd, Patrick A. (Liberty IT Solutions)
We were able to get a decrypted TLS trace of successful and failed keepalive requests from the client side and view them in wireshark, and it shows that Chrome is being fairly accurate in what it's telling us - there is a well-formed HTTP request, with a method and all expected headers, but sometimes ISAM is generating a response that is lacking the session-alive as well as all the access-control-allow-* headers

Shawn did some digging in IAM Splunk but doesn't see any apparent difference between a successful and failed request being logged there. 

Which is the same as what Damien and Marat experienced earlier in the week, except now we know pretty definitively that there's nothing malformed about the keepalive request, since we see the reconstructed HTTP stream in wireshark.  
Shawn will file a separate ticket with IBM, although we have some due diligence to do about the implementation of the keepalive endpoint since it's custom behavior. My hunch is that there's some exception code path that is getting triggered, e.g. when looking up the session to decide how to respond, and the "catch" behavior is to send this partial response with some of the headers missing. But that's just a theory. 
It would be good to understand exactly how this keepalive is implemented - is it a hunk of Java code, or is it just some ISAM templating language, or what? 

It would be really nice if ISAM was logging a big fat stack trace but unfortunately there's no evidence that it's doing so. (edited) 

Marat just came back online - and stated that he sees the error in the iSAMs.
How the iSAM server applies CORS / http header logic:
The Keepalive itself is implemented as a resource file on ISAM root. However the CORS logic is implemented using the xslt based HTTPTransformation rules, which is triggered on the response being sent back to the client
What Marat is finding out: I just looked through the logs and I see errors related to the xslt processing
PDAC0977E  An unexpected Xalan processor exception was caught during rule processing. Error message "Result truncated - increase xslt-buffer-size" was returned with the exception.
It sounds like occasionally, our http response headers are blowing up the iSAM's response buffer size, perhaps causing it to lose some of the parameters.
By default, the parameter size is probably 4096 bytes - based on this page.
[https://www.ibm.com/support/pages/webseal-error-hpdac0977e-unexpected-xalan-processor-exception-was-caught-during-rule-processing-error-message-result-truncated-increase-xslt-buffer-size-was-returned-exception](https://www.ibm.com/support/pages/webseal-error-hpdac0977e-unexpected-xalan-processor-exception-was-caught-during-rule-processing-error-message-result-truncated-increase-xslt-buffer-size-was-returned-exception)


Boris Ning  19:03
Marat thinks he sees the problem - and they'll probably address the xslt size processing limitation as the next step.

**Comment by lalexanderson-dsva** [comment] 2020-10-30 15:49
Today: increased xslt-buffer-size from 4096 to 8192 and tested on 150/151 using @lalexanderson-dsva ability to repro. I was able to get through reliably every time in prod with the fix in place. Deploying this fix today. 

Planning to do change to TCP RST next week. Do not want to do 2 major changes in prod on a friday, and we do want to test this one in pre-prod first. H/e the keepalive issue seems to be more affected by xslt-buffer-size.

**Comment by christine-dillman** [comment] 2020-12-07 18:49
The IAM team resolved this issue by increasing their request header size in the ISAM.

**Closed** 2020-12-07 18:49 UTC
Labels: Cerner-MHV-patient, Cerner-patient, bug, identity
