### ISSUE TITLE
CHIP - Add clinic to the pre-approved list

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#28829] opened 2021-08-17 12:42 UTC
In order to allow a team member to easily add a clinic to the pre-approved list, CHIP must provide a `/POST` endpoint which will add a single clinic to the list

We'll know it's done when:
1. A user can call `POST /clinics` with the body `{ien: someClinicIEN123, name: clinic name}`, then call `GET /clinics` and see that the newly added clinic is in the whitelist

**Comment by aschulhof** [comment] 2021-09-23 13:17
duplicate of https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/56

**Closed by aschulhof** 2021-09-23 13:17 UTC
Labels: VEText vt, CHIP vt
