### ISSUE TITLE
Update "Downshift" NPM module site-wide

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#2418] opened 2019-10-14 15:52 UTC
An accessibility audit revealed that the Facility Locator's `Facility Type` dropdown has some issues which resulted in this ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/1056. However, after picking that ticket up, it was discovered that the dropdown component used there is a module from NPM called Downshift. vets-website uses Downshift in various areas throughout the site, specifically the Facility Locator and the forms library. 

The Downshift version used by vets-website is very old and the more up-to-date version include accessibility improvements. We should update it site-wide to receive these updates. The work for the Facility Locator to use the most recent Downshift version was started here, https://github.com/department-of-veterans-affairs/vets-website/pull/10829.

**Comment by 1Copenut** [comment] 2019-10-14 17:31
Bringing my comment over from #1056 because it will weigh on the difficulty of this issue ticket:

The WAI-ARIA 1.1 specification ( https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html ) for comboboxes creates a lot of challenges for screen readers. I have previously upgraded an Autocomplete component to Downshift V3, but had to manually re-write it to use the better supported 1.0 specification ( https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html )

The 1.0 specification with listbox is well supported, and I'm hearing discussion that the 1.1 spec might be deprecated. I think the right answer is to update Downshift, but be prepared to refactor the component so it abides the 1.0 spec so we don't introduce a usability regression.

**Comment by timwright12** [comment] 2021-05-25 13:44
https://www.npmjs.com/package/downshift

**Comment by meganhkelley** [comment] 2021-07-15 18:58
Closing in favor of #27348

**Closed by meganhkelley** 2021-07-15 18:58 UTC
Labels: frontend, sitewide, tools-fe, tools-improvements
