### ISSUE TITLE
Wrap generator command with Toolkit

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#17220] opened 2020-12-09 19:52 UTC
## Description

The new rails generator should be able to be invoked by the toolkit with one command

## Acceptance Criteria
- [ ] Rails generator is invoked by the toolkit with one command

**Comment by erluti** [comment] 2020-12-17 19:28
Duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17527

**Closed by erluti** 2020-12-17 19:28 UTC
Labels: tools-be, tools-be-review, vsp-toolkit
