### ISSUE TITLE
Create the MHV Transition Prototype

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35627] opened 2022-01-20 05:32 UTC

**Comment by AGarcia-Clarity** [comment] 2022-04-13 14:14
Closing this one @nsoutouras
Reason: Duplicate of https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/34906

**Closed by AGarcia-Clarity** 2022-04-13 14:14 UTC
Labels: Identity
