### ISSUE TITLE
EKS upgrade

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#50681] opened 2022-12-13 18:09 UTC
## LOE
Medium

## Problem Statement 
*What is the current problem VFS teams, Veterans, or Platform teams are facing? Try starting this statement with “Currently,” to drive it toward a problem people are facing and not a solution. Make sure you’ve fully answered what the problem is and why solving it is important.*

*Follow your problem description up with a "How might we... _______" statement re-framing that challenge as an opportunity. Don't hint too much at what the solution might be, you should have enough of a focal point here to guide your ideas, but plenty of freedom to think laterally and innovatively as you experiment and prototype later.*

## User Impact
*How many users are being affected? What kind of user (VFS engineer vs. VFS designer)? What is this blocking those people from doing? What would fixing this problem allow the impacted users to do faster/better?*

## Where was this problem reported?
*Is it something that came to light because it was mentioned in many support requests? Was it found in research? Was it a theme of the satisfaction survey?*

## What do we not know about the problem space?
*What areas do we need more information about so that we can accurately solve the problem? What discovery is needed?*

## What (if any) research or discovery has been done?
*Link to any relevent research that has been completed that is either relevant to this problem or the problem came as a secondary finding. Link to the outcome of any discovery efforts.*

## What is the acceptance criteria?
*This should be written in a way that no one can interpret it differently. It should be written from a user impact perspective. A good acceptance criteria isn’t “We built a new service to allow VFS teams to deploy on their own” it’s “A VFS team member is provided with all the information and resources needed to deploy their code without Platform intervention.” Above all else, acceptance criteria should be testable, simple/straightforward, written in the perspective of the user and specific to the item they are supporting with no outside dependencies.*

- Lay the foundation for it to upgrade automagically.

## How should we measure success?
*What are the key performance indicators? What do we expect solving this problem to impact? How should we measure the impact (both where should we pull the data from and what should the calculation be)? Do we need to start the project by defining baselines or do they exist somewhere?* 

## TODOs
- [ ] Convert this issue to an epic

**Comment by mchelen-gov** [comment] 2022-12-13 19:29
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/47909

**Closed** 2023-01-11 21:28 UTC
Labels: platform-project
