### ISSUE TITLE
[Build] 'Back to top' link LC MVP 1.0 [N2H] - 1.1 [Required]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14347] opened 2020-10-02 17:51 UTC
## Description 
_Build out 'Back to top' link for LC 1.1_

## Tasks
- [ ] Build 'Back to top' link for LC 1.1 (We only need to build the FE logic)

## Planning Considerations
Nice to have for 1.0; required for 1.1.

## See og ticket with AC and requirements: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13646

## Ryan Thurlwell's design and UX interaction documentation
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/298  

{NOTE: Correcting something I said on grooming - the interaction is NOT sticky at the bottom of the display port. I believe Ryan's intended ux is sticky to the side margin. So that as you are scrolling, the back to top is always visible - and only shows after a certain page length - 2,000 pixels. But please work directly with @rtwell for exact specifications. / Jen}

**Comment by jenniferlee-dsva** [comment] 2020-10-14 13:29
Could we combine these 2 epics? The design and FE are so married, it's hard to track them when they're separated out. 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14340
And
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14347

**Comment by brianalloyd** [comment] 2020-10-15 21:46
@jenniferlee-dsva I think we can, perhaps we can just close out #14340, and nest everything under #14347 forward.  Any objections on that approach?  LMK.

**Comment by kelsonic** [comment] 2020-10-27 17:46
This might be a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/13646

**Comment by ncksllvn** [comment] 2020-10-30 20:35
Does this button show only on the Multiple FAQ pages of the LC, or on _all_ pages of the LC?

**Comment by jenniferlee-dsva** [comment] 2020-10-30 21:06
@rtwell says - just articles (all of the articles though regardless of template type). 

So exclude the RS home; RS search results; tagged landing page; category landing page

**Comment by zacharymorel** [comment] 2020-10-30 21:09
Is there a list of articles templates I could use so I know what to add?

**Comment by ncksllvn** [comment] 2020-11-02 17:02
- [Here is the layout](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/faq_multiple_q_a.drupal.liquid.) you could work with while implementing this. This template represents the "Multiple FAQ" article-type in Resources and Support (AKA Learning Center.) 
- I would advise you to add a new component into the ["includes" template directory](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/includes), which you can include from the layout file, so that it is easily reusable in other templates.
- While developing, you have multiple options for testing. Here is my suggestion.
    - You could run the CMS preview server. First, `yarn build` to compile JS/CSS via Webpack. Then, `yarn preview`. Then navigate to `http://localhost:3001/preview?nodeId=6898`. This node is an example of a Multiple FAQ article. You can verify this in your browser's developer console - at the top, there is an object outputted which should contain an `entityBundle` property with a value of `faq_multiple_q_a`. Each time you change the template, stop the preview task and re-run it.
    - You could also run the watch tasks that the vets-website README describes.
- A project pattern is to use the VA Design System, especially leveraging the [utility classes](https://design.va.gov/utilities/). Be sure to take advantage of the [responsive utilities](https://design.va.gov/utilities/visibility). Hopefully, you will be able to get away without any SCSS.
- Font Awesome is included in our project. Search for `fa ` in the project to find examples. I think you will need that for that arrow icon.
- If you absolutely have to, you can write SCSS. [Here is the SCSS file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/sass/static-pages.scss) used for content pages. If you change it and are using the preview server to test your template changes, you will need to run `yarn build` again.
- When you open a PR, please include a screenshot for each screen size in your PR description.

**Comment by zacharymorel** [comment] 2020-11-02 17:35
@ncksllvn Thank you so much for the write up. This either cements assumptions I had or informs me of things I didn't know!
The only question I have is just file placement. I initially thought sites/components/ dir would be good placement for the small button component. Reason being, the sites/inclues/* dir looked at glance like larger blocks of code rather than a small button?

**Comment by ncksllvn** [comment] 2020-11-02 18:39
The `components/` directory is perfectly fine too. If there is a distinction between `includes/` and `components/`, it predates me. I just see `includes/` used more often these days.

**Comment by jenniferlee-dsva** [comment] 2020-11-03 15:46
From one of @rtwell 's design tickets - This Australian gov site shows a dynamic back to top behavior he intended: https://www.vic.gov.au/digital-guides

**Comment by zacharymorel** [comment] 2020-11-03 20:34
Thanks, @jenniferlee-dsva . Much appreciated!

**Comment by zacharymorel** [comment] 2020-11-13 14:14
Validated!
![Screen Shot 2020-11-13 at 9 13 05 AM](https://user-images.githubusercontent.com/26075258/99081273-8f9ecf00-2590-11eb-8f30-765b30975c48.png)
![Screen Shot 2020-11-13 at 9 13 13 AM](https://user-images.githubusercontent.com/26075258/99081274-90376580-2590-11eb-8cec-379005a16968.png)

**Closed** 2020-11-13 14:14 UTC
Labels: frontend, planned-work, vsa, vsa-public-websites
