### ISSUE TITLE
[FE] Notification prefs: Focus should be sent to label from alert link

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#30812] opened 2021-10-01 16:44 UTC
Currently the `select your notification options` link in our warning alert sends users to the first fieldset, but it doesn't seem that focus is being sent when a user is sent down the page.  As a SR user, when I click the link, nothing is announced even though I'm visually moved down the page

We need to make sure SR users know where they've been sent after clicking the link in the alert

https://user-images.githubusercontent.com/55992116/135657805-5829508a-ce19-42c9-9119-e1b83a61b22a.mov

**AC**
- [ ] Manage focus so that when a user clicks the link in the alert, the focus goes to the label of the first notification group.
- [ ] No focus ring is expected on the label since that is not an interactive element
- [ ] SR should announce the label after the user clicks the link

**Comment by erikphansen** [comment] 2021-10-04 17:15
The `select your notification options` link is a plain old standard same-page link which functions exactly any other "on this page" link (such as those on https://www.va.gov/coronavirus-veteran-frequently-asked-questions/).

As far as screenreaders are concerned, focus is managed correctly when using control-option-space to click the link. That is to say that the screenreader will read the h3 that the user just "jumped" to. See video:

https://user-images.githubusercontent.com/20728956/135894698-512bbefb-0237-4e5a-b563-32ab811c7554.mp4

Angela tested this a couple of weeks ago, without any guidance from me, and it was clear to her.

We can talk more about this but I do not think we should be adding any additional javascript functionality to manually set focus or do anything else. I think that this should function exactly like a plain old JS-free same-page link, which has been a feature of HTML since the dawn of HTML.

**Comment by erikphansen** [comment] 2021-10-15 15:42
Closing. Angela just confirmed that focus is handled well after clicking the jump link.

**Closed by erikphansen** 2021-10-15 15:42 UTC
Labels: bug, frontend, vsa-authenticated-exp, profile, 508-issue-focus-mgmt, notifications, planned-work, 508-issue-screenreader
