### ISSUE TITLE
Bug: Find a VA form search is showing duplicate listing of VA Form 10182

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17484] opened 2020-12-15 16:40 UTC
### There is only one record of this form in the CMS. The CMS shows the following VA forms database data: 
https://prod.cms.va.gov/find-forms/about-form-10182

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3ef55ea7-f63b-4b58-a735-a03d7bae366f)

### Screenshot of search - the listing in green box is the right listing. The 2 PDF forms in the listing are identical, but for some reason, the search is listing it twice (with different meta data). 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/b080a7f9-1186-4b6a-8566-d1c403c4ceba)

**Comment by jenniferlee-dsva** [comment] 2020-12-15 16:50
When this is resolved, please let the form manager Missie Vaccaro-Palamaki, know.

**Comment by johnhashva** [comment] 2020-12-15 16:56
Got it -- thanks @jenniferlee-dsva

**Comment by MarciMcGuireGCIO** [comment] 2020-12-15 17:14
Based on [this thread ](https://dsva.slack.com/archives/CUB5X5MGF/p1608051923270900?thread_ts=1608051083.270100&cid=CUB5X5MGF) an off-schedule migration may correct the issue.

**Comment by MarciMcGuireGCIO** [comment] 2020-12-15 17:19
I posted an off-schedule migration request and link to this issue in #vfs-platform-support.

**Comment by MarciMcGuireGCIO** [comment] 2020-12-15 17:31
@ncksllvn mentioned that there are two different IDs - one with a VA prefix and one without.

**Comment by jenniferlee-dsva** [comment] 2020-12-15 18:38
FWIW - I don't think this bug warrants an off schedule migration. As I mentioned in the email to Missie, this isn't a critical bug as the PDF forms being linked to are actually identical (i.e., we're not giving veterans an outdated or invalid form.)

**Comment by MarciMcGuireGCIO** [comment] 2020-12-16 16:08
See related slack thread for more details:  https://dsva.slack.com/archives/CUB5X5MGF/p1608134793280600?thread_ts=1608051083.270100&cid=CUB5X5MGF

**Comment by MarciMcGuireGCIO** [comment] 2021-01-25 20:48
Tagged Lydia Vian into Slack thread started in Dec.  https://dsva.slack.com/archives/CUB5X5MGF/p1608134793280600?thread_ts=1608051083.270100&cid=CUB5X5MGF

**Comment by swirtSJW** [comment] 2021-01-26 15:19
Looking into this on the CMS side.   There is only one entry for `10182` in the data from the forms db and only one in the CMS.  They match.  

The FormNum in the FormsDB changed from `VA10182` to `10182` the  on 8/11/2020   the CMS updated that data for the same node since we key off the rowid  which stayed 10554
![image](https://user-images.githubusercontent.com/5752113/105864111-99e13e80-5fbf-11eb-918e-d3176b7d2ceb.png)


My guess is that lighthouse is keying off our form number instead of the Row ID so when they form  number changed in the FormsDB it did not get renamed in lighthouse.  Looks like lighthouse created a new entry rather than updating the original.

**Comment by NCHLiberty** [comment] 2021-02-10 21:36
this issue corresponds to jira ticket https://vajira.max.gov/browse/API-5085 on the lighthouse forms api team backlog

**Comment by MarciMcGuireGCIO** [comment] 2021-02-16 21:07
@NCHLiberty, please let us know if there is anything we can do to help facilitate when your team gets to this - testing, etc.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-24 19:03
Hi @NCHLiberty - doing my end-of-sprint check on the status of open issues.  Any updates on this?  Thanks!

**Comment by mviterna** [comment] 2021-02-24 19:07
@swirtSJW So, I'm wondering why we would select rowid for the PK? I remember the concept of rowid back in my Oracle days, but I don't know what DB implementation the CMS is using. Is it MSSQL? 

When I used to be involved with Oracle DB, we would never use rowid for a PK, because if you dropped the table and reimported it (or just removed the row and readded it), or something to that extent, you would get a new rowid for the same data. So it acted more like a physical memory address for the row, rather than an actual 'id' like an ssn or edipi key. Our postgres DB that we import the data into on our side has an ID column for our PK constraint however it probably isn't tied to anything on your end, but perhaps we could repurpose it? Do you have the equivalent to a form id that is an integer? I don't think using like a form name (VA-1010EZ) that is a string would be a very good PK. Maybe we should have another meeting? We are open to ideas.

**Comment by mviterna** [comment] 2021-02-24 19:08
@MarciMcGuireGCIO Let's set up a meeting and discuss. I have a decent understanding of Forms now and think I can try to set up a plan of attach. It is really going to be more of getting a solution satisfactory to both sides. I know our customers on our side need to preserve form history, so whatever we do with a migration we need to make sure we retain that data.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-24 19:10
@mviterna Sounds good.  Who would you like included in that, and can you provide a few possible time slots?

**Comment by mviterna** [comment] 2021-02-24 19:14
@MarciMcGuireGCIO We need Greg Bowman in on it and he is out today. I'll get with him and propose a time later in the week.

**Comment by mviterna** [comment] 2021-02-24 19:15
@MarciMcGuireGCIO Just need one technical person on your end, probably @swirtSJW or @zacharymorel

**Comment by NCHLiberty** [comment] 2021-02-24 19:20
@MarciMcGuireGCIO please include me too as optional for learning purposes / to stay up to speed. Thanks

**Comment by MarciMcGuireGCIO** [comment] 2021-02-24 19:21
@mviterna Sounds good; thanks! @NCHLiberty - will do!

**Comment by mviterna** [comment] 2021-02-25 16:37
@MarciMcGuireGCIO  We have tomorrow at 2:30 PM ET open, is that too short of notice or does that time work?

**Comment by MarciMcGuireGCIO** [comment] 2021-02-25 17:37
@mviterna, @swirtSJW has a conflict at that time, and I think he will be key to the discussion.  Are you available at 1:30 or 3:00 PM ET tomorrow?

**Comment by mviterna** [comment] 2021-02-25 17:55
@MarciMcGuireGCIO  Invite sent for 3PM, please forward to whoever needs it

**Comment by MarciMcGuireGCIO** [comment] 2021-02-25 17:57
@mviterna -- got it.  Thanks!  I forwarded to @zacharymorel

**Comment by mviterna** [comment] 2021-02-26 00:31
@MarciMcGuireGCIO What team owns the MSSQL "Source of Truth" database for Forms? It would be best if someone from that team was present also. Or is that something your team owns as well?

**Comment by MarciMcGuireGCIO** [comment] 2021-02-26 00:42
@mviterna, there are actually two data sources that are merged together nightly to create one dataset. One is the VA forms database (managed by the VA's form managers) and the other is the Drupal CMS, where the forms data derived from the VA database gets appended with additional metadata. 

@johnhashva -- is there anyone in particular from the VA who you'd recommend to participate in a discussion with the Lighthouse team?

**Comment by swirtSJW** [comment] 2021-02-26 02:38
> @swirtSJW So, I'm wondering why we would select rowid for the PK? I remember the concept of rowid back in my Oracle days, but I don't know what DB implementation the CMS is using. Is it MSSQL?
> 
> When I used to be involved with Oracle DB, we would never use rowid for a PK, because if you dropped the table and reimported it (or just removed the row and readded it), or something to that extent, you would get a new rowid for the same data. So it acted more like a physical memory address for the row, rather than an actual 'id' like an ssn or edipi key. Our postgres DB that we import the data into on our side has an ID column for our PK constraint however it probably isn't tied to anything on your end, but perhaps we could repurpose it? Do you have the equivalent to a form id that is an integer? I don't think using like a form name (VA-1010EZ) that is a string would be a very good PK. Maybe we should have another meeting? We are open to ideas.

The reason is not based on the CMS, the reason is that is the only unique identifier in the forms db.  The forms db is loosely structured at best and the only thing they could guarantee was that.  Multiple rows can have the same form id so that can not be used.   The CMS is simply carrying forward the primary key from the forms db to allow data parity.  If they treat it as the primary key, the CMS has to treat it as the primary key, which means the find forms api  has to do the same.   Otherwise we have the case where there is integrity between the forms DB and the CMS but the forms API is out of sync (like is happening now).

**Comment by mviterna** [comment] 2021-02-26 13:47
@swirtSJW Thanks for working with us on this, I know it has been a pain point for some time now. The developer who left us with the Forms API (Michael Bastos) had similar concerns that I have. So, I wanted to clarify a couple of things. In the Forms DB (not Drupal), is this an underlying system column or is it a user specified one? For example, if someone on the Forms DB (the MSSQL one, not Drupal) decides to "make a copy" of a form, does a new rowid automatically get generated or does a human set that field manually? I guess it is just the naming of the field that had me concerned, like I said, rowid, row_number and other fields with those sorts of names are sometimes system fields tied to a sequence or a trigger that autogenerates it, rather than a human specifying the number. And while they are unique, they make for bad primary keys. 

I also agree that Forms API using the Form Number as a driving force for the nightly job is bad practice. Although it technically isn't our PK on our table. We have an ID column that isn't tied to any specific data, which we will either need to repurpose for rowid or create a new PK and remove that one.

I'm not trying to be difficult or push back, just trying to prevent either of us having to do duplicate removals if the Forms DB isn't involved in this either. I'm hoping we can involve them as well, since it should be equally fair to ask them how they generate rowid (manual or automatic) if Forms API is asked to change their unique identifier (which I'm agreeing with).

**Comment by MarciMcGuireGCIO** [comment] 2021-02-26 14:12
@mviterna @swirtSJW l -- if I'm tracking, the idea being proposed is to introduce an immutable GUID as a primary key so that CRUD  operations have no impact on the PK.  That GUID would then become part of the API response, and Zach would modify his code accordingly. 

If that is the case, it may not  be necessary to involve the VA form managers, apart from testing CRUD operations.  Ideally, this change would be completely transparent to them.  
 
 cc @johnhashva @zacharymore

**Comment by mviterna** [comment] 2021-03-03 13:36
@MarciMcGuireGCIO I'm going through the "duplicates" now and will be posting screenshots, perhaps someone on the team can let us know which is the one we keep and the one we remove. 

![image.png](https://images.zenhubusercontent.com/5f7e41bdb1b941672ba84d4b/0abb9858-82ec-4b6e-a7a9-822ff8550ee9)

**Comment by mviterna** [comment] 2021-03-03 13:44
Keep 10091 and remove VA10091?

![image.png](https://images.zenhubusercontent.com/5f7e41bdb1b941672ba84d4b/4efd2d92-f350-46b2-add2-5f1a59b0c4b2)

**Comment by MarciMcGuireGCIO** [comment] 2021-03-03 13:46
I believe we will want to keep the ones with that newer date.  We are meeting with stakeholders today and will ask.

**Comment by jenniferlee-dsva** [comment] 2021-03-03 14:25
RE ^ - there is only one record in the CMS for this form, the one updated on Feb 2021. So that first one shown in the search results is the real form to keep. The other one already appears to have been deprecated (it is not in the CMS).  It is showing up ONLY in the search because the API is incorrectly using the form number instead of the rowID as the unique form identifier. 


![image](https://user-images.githubusercontent.com/43381063/109819671-51422400-7c02-11eb-8f8b-da4b543fbac7.png)

**Comment by MarciMcGuireGCIO** [comment] 2021-03-03 14:30
Thank you, @jenniferlee-dsva!

**Comment by MarciMcGuireGCIO** [comment] 2021-03-03 17:48
> @MarciMcGuireGCIO I'm going through the "duplicates" now and will be posting screenshots, perhaps someone on the team can let us know which is the one we keep and the one we remove.
> 
> Looks like we probably need to keep 22-8979 and remove VA Form 22-8979, correct?
> 
> ![image.png](https://camo.githubusercontent.com/ac6bbdfa226fb0c14d6df460d569ad62711ccbb92b863d82148f40528abf3510/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566376534316264623162393431363732626138346434622f30616262393835382d383265632d346236652d613761392d383232666638353530656539)

@mviterna - since you are working on cleaning up duplicates, have you moved closer to being able to resolve the root cause by reference the row ID?

**Comment by mviterna** [comment] 2021-03-04 14:00
@MarciMcGuireGCIO , Yes we have an internal meeting about it today. I'm just making sure what I'm about to remove is correct. I've also confirmed the duplicates are not in CMS, but I'm just being cautious, as this is client/veteran facing data I'll be removing.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-04 14:03
@mviterna our meeting with the VA has been moved to Mar 25, so I believe that removing records not found in the CMS is a safe course of action.  @johnhashva are you also good with this approach?

**Comment by mviterna** [comment] 2021-03-05 01:11
@zacharymorel Can you explain the logic behind this page?  Is it the validPdf flag? The API returns this for the form
{"data":[{"id":"21-0960M-10","type":"va_form","attributes":{"formName":"21-0960M-10","url":"https://www.vba.va.gov/pubs/forms/VBA-21-0960M-10-ARE.pdf","title":"Muscle Injuries Disability Benefits Questionnaire (Fillable)","firstIssuedOn":null,"lastRevisionOn":"2018-03-01","pages":6,"sha256":"842f4984c6d3a2285e692f6a09ddf5b352a72e067a338d4375eed2a6ea24c61f","validPdf":false,"formUsage":null,"formToolIntro":null,"formToolUrl":null,"formDetailsUrl":null,"formType":null,"language":null,"deletedAt":null,"relatedForms":null,"benefitCategories":null}}]}

![image](https://user-images.githubusercontent.com/45046188/110052511-b04c8980-7d25-11eb-9212-3fe43151a696.png)

**Comment by mviterna** [comment] 2021-03-05 01:49
@zacharymorel Ok, I dug into the front end code a little more, It looks like maybe it uses that validPdf attribute along with dateDeleted. 

If that is the case, I think this form is in our Forms API db, but I was thinking this might not be in CMS. I need to check on that in the morning. If this is the case, where we have "retired" forms in our postgres db but not in drupal, then this is going to make filtering duplicates a little interesting and I'll probably have to change up the logic in our form migration worker to include these two somehow. I might need to give you a call next week.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-05 13:15
Thank you both so much for working through this together. I appreciate the excellent teamwork!

**Comment by zacharymorel** [comment] 2021-03-05 17:29
You can reach out to me anytime @mviterna ?

**Comment by mviterna** [comment] 2021-03-05 20:58
@zacharymorel I propose some time on your calendar next week, @MarciMcGuireGCIO I'll put you as optional in case you want to give any input or care to be there

**Comment by mviterna** [comment] 2021-03-05 21:04
@MarciMcGuireGCIO Do you know if the plan is to eventually rename all forms by removing the "VA" from the form name? I noticed that is where all our duplicates come from. I see a little kink in that plan. For example VA9 has had its form ID changed to just "9". I noticed VA.gov services other forms from different agencies, like OPM and GSA. They also have SF-xx forms. Our API has a call that references the form name by form id. So I could easily see overlap if we remove the "VA" prefix. Is  there a way to keep the original form name in drupal (like VA9) and have one of the other columns use the prettified form name? I noticed in drupal there are two columns for form ID, maybe we could keep one the original name. Or do you know if the VA is actually renaming all their forms by removing the prefix?

**Comment by MarciMcGuireGCIO** [comment] 2021-03-05 21:12
@mviterna I don’t know if there’s a plan to rename all of the forms, but I will ask when we discuss roadmap. 

I understand what you are saying, and will need to find out how those two fields get populated in the CMS. From what I see, they are currently both identical, but we may be able to do what you are recommending if it doesn’t create issues elsewhere and we know it won’t be overwritten the next time the VA modifies metadata in their DB.

**Comment by mviterna** [comment] 2021-03-09 16:37
@MarciMcGuireGCIO So, I was wrong on their being two form name fields. However, that still leaves us with a problem on something with a form name of just "9".  If you do find out anything on the roadmap of removing the prefix on all of the forms, please let me know and I can check for other forms that could cause collisions in the future

**Comment by mviterna** [comment] 2021-03-10 17:29
@swirtSJW Is there a way we can take a look at the most recent CSV Forms DB dump and compare it to an archived one like a year ago? I'm wanting to take a look at some trends. But I don't think I have access to those files. Is there a way to get that? Do we retain any of the CSV dumps from previous months?

**Comment by mviterna** [comment] 2021-03-10 22:54
@MarciMcGuireGCIO @johnhashva @zacharymorel  Here is a list of search terms you can use on prod that show the duplicates. I did an export on both systems and did a diff. Can you please take a look and let me know which ones are getting removed? It looks like the ones with the VA prefix are the duplicates (based on them not showing up in Drupal). If there are others I missed, please let me know.

Search Term:
10091
va9
5655
40-1330 (two sets)
3288
10182
8979

**Comment by mviterna** [comment] 2021-03-10 22:54
Also, please see if any of the "revision" or "issued on" dates need to be merged or updated.

**Comment by mviterna** [comment] 2021-03-11 00:55
> @swirtSJW Is there a way we can take a look at the most recent CSV Forms DB dump and compare it to an archived one like a year ago? I'm wanting to take a look at some trends. But I don't think I have access to those files. Is there a way to get that? Do we retain any of the CSV dumps from previous months?

@swirtSJW You can disregard this request.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-11 14:27
> @MarciMcGuireGCIO @johnhashva @zacharymorel Here is a list of search terms you can use on prod that show the duplicates. I did an export on both systems and did a diff. Can you please take a look and let me know which ones are getting removed? It looks like the ones with the VA prefix are the duplicates (based on them not showing up in Drupal). If there are others I missed, please let me know.
> 
> Search Term:
> 10091
> va9
> 5655
> 40-1330 (two sets)
> 3288
> 10182
> 8979

Hi @mviterna,

For clarity, 40-1330 and 40-1330M are two separate forms, and there were duplicates of each.  

I have verified that the following records are **not** currently found in the production CMS, and likewise should not be part of the dataset returned by the API.  

VA10091
VA9
VA5655
VA40-1330 
VA40-1330M
VA10091
VA3288
VA10182
VA Form 22-8979 (literal name; 22-8979 should stay)
VA40-10007 (not in your list, but was in mine)

Rather than delete those rows, can you instead insert the current date into the Deleted At field to form a logical delete?  The presence of a date will enable Zach to exclude the record from the presentation layer.

RE: issue and revision dates --  the records that are kept should retain the dates that came from the VA forms DB.  Modifications to those should be made by the VA Forms managers at the data source.  We plan to share our data review findings with them when we meet next.

Thanks!  

cc @johnhashva @zacharymorel

**Comment by mviterna** [comment] 2021-03-16 00:51
@MarciMcGuireGCIO On  40-1330 and 40-1330M, yes, I meant there are 4 returned and there should be two. Two separate forms with a dupe each. 

The only problem I see with the "deleted at", would be we would then have a handful of orphaned records that don't have a RowID. If we update the RowID on these orphans, then it would conflict with the RowID with the "real" form. Do you want to assign them a reserved RowID? Such as 9999 or 0000 that indicates a deleted entry (in addition to deleted at column)?

**Comment by MarciMcGuireGCIO** [comment] 2021-03-16 13:51
@mviterna thank you.  

Re "deleted at" - maybe we need  a quick chat to walk through what will occur when a form is deleted from the forms DB.  

In my mind, if every record is assigned a unique ID, and then a form is marked as deleted, it should still retain its original RowID, just now it has a value in the "deleted at" field which tells Zach not to surface it on the FE.  If a new form of the same name is added, it should have its own unique RowID, and not have a value in "deleted at", which tells us that it is the "real" (valid) form.

This approach allows us to know which forms have been deleted (so we can show a message to that effect, vs. a "not found" message), and so we can determine why a form is not showing up if there's a question.

**Comment by mviterna** [comment] 2021-03-18 17:49
@MarciMcGuireGCIO That won't work. Here is the problem. If there are two records in the Postgres db with RowID 1234 and one has a deleted_at (the duplicate) and the other does not, the next time the reload process runs, it will set both to deleted_date = null and show them both again. Is there any reason we can't clean the existing records (like remove the duplicates)? I think the deleted_at should only be used if the form was deleted from Forms DB side. A duplicate, isn't really "deleted"

**Comment by mviterna** [comment] 2021-03-18 18:07
@MarciMcGuireGCIO Here is a practical example: We have two records for VA9 / 9. I don't have a rowid assigned to them yet. I need to assign a RowID to both of them. But I only have one RowID to give it: 4176.  I don't really want to have RowID a nullable field and it needs to be unique. To make this work, it needs to be treated as a PK

**Comment by MarciMcGuireGCIO** [comment] 2021-03-18 22:03
@mviterna that makes sense.  I was confusing _deleted_ vs. _duplicate_ forms.  I also did not realize that the RowID was derived from the VA Forms Database (thought you were populating that), so I get that you would only have one row ID.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-19 18:31
> I have verified that the following records are **not** currently found in the production CMS, and likewise should not be part of the dataset returned by the API.
> 
> VA10091
> VA9
> VA5655
> VA40-1330
> VA40-1330M
> VA10091
> VA3288
> VA10182
> VA Form 22-8979 (literal name; 22-8979 should stay)
> VA40-10007 (not in your list, but was in mine)

@johnhashva Lighthouse team needs someone to give them approval to remove the duplicate records listed above.  Who would be our best contact person to ask for that?  Thanks!

**Comment by johnhashva** [comment] 2021-03-19 19:35
@MarciMcGuireGCIO unfortunately, we don't have a single POC for decisioning here.   That said, I will put an email out to some of the key, more engaged stakeholders about this next week to see if we can get a response.  One thing that would help: Can you associate the VA Admin to each form -- e.g. which one is a VHA vs. a VBA form?    That will help me target the email.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-19 19:41
Thank you @johnhashva.  Yes, I can do that.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-19 20:20
@johnhashva, please see below.  This is based on the list of forms on Sharepoint, the list of forms in the MVP, and/or looking at the form itself and taking my best guess.

VA10091  **VA-FSC**
VA9 **VBA**
VA5655 **F&P**
VA40-1330  **VBA**
VA40-1330M  **VBA**
VA3288 **F&P**
VA10182 **VBA**
VA Form 22-8979 (literal name; 22-8979 should stay) **VBA**
VA40-10007 (not in your list, but was in mine) **VBA**

**Comment by johnhashva** [comment] 2021-03-22 12:59
@MarciMcGuireGCIO just cc'ed you on an email I sent to the VA Forms managers and stakeholders.  If we hear nothing back by Wednesday, we can move ahead with deletion of these duplicates.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-24 14:12
@mviterna we just received verbal approval from Missie Vaccaro at the VA to remove the duplicate records.  To clarify, these would be the records we discussed above; those not currently in the CMS.

**Comment by mviterna** [comment] 2021-03-24 14:15
@MarciMcGuireGCIO Thank you, the following will be removed from the API response:

VA10091 VA-FSC
VA9 VBA
VA5655 F&P
VA40-1330 VBA
VA40-1330M VBA
VA3288 F&P
VA10182 VBA
VA Form 22-8979 VBA
VA40-10007 VBA

I'll start with dev and staging, have you confirm all looks good, then remove in prod and sandbox

**Comment by MarciMcGuireGCIO** [comment] 2021-03-24 14:19
Thanks, @mviterna!  Just ping me when you're ready for us to have a look.

**Comment by mviterna** [comment] 2021-03-24 19:00
@MarciMcGuireGCIO We discovered that someone has renamed the "official" forms to now include the VA prefix on some of these. So now the the forms we thought were duplicates, are actually the record to keep. Per our Slack conversation https://app.slack.com/client/T03FECE8V/CUB5X5MGF/thread/CUB5X5MGF-1616608434.087300 please provide a new list of forms that you want deleted

**Comment by MarciMcGuireGCIO** [comment] 2021-03-24 19:25
@mviterna I have verified today that the below records are duplicates being returned by the Forms API that do not currently exist in the CMS.  We have been given verbal approval from Missie Vaccaro at the VA to remove these records so they won't appear on VA.gov.

10091
9
5655
40-1330
40-1330M
10091
3288
10182
VA Form 22-8979 <-- literal name; **22-8979** should stay
40-10007

**Comment by mviterna** [comment] 2021-03-24 19:35
@MarciMcGuireGCIO I'm going to send you an Excel worksheet I created with two columns highlighting differences. I see more than this list, so I want to get your input on these duplicates / missing forms

**Comment by MarciMcGuireGCIO** [comment] 2021-03-25 12:54
Spreadsheet received from Mark - 
[FormDuplicates.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6204749/FormDuplicates.xlsx)

**Comment by MarciMcGuireGCIO** [comment] 2021-03-25 14:15
@NCHLiberty @mviterna, there is some significant back story here that I'm just learning of (and documenting), and there are two different things going on:

1. Initially, no "deleted" flag existed in the VA database, CMS or Postgres.  The VA would delete defunct records in their DB, and they would subsequently be deleted in the CMS.   In late 2019, due to fraud issues, the VA removed a large swath of forms from their database, which cascaded to CMS, but evidently became orphaned in Postgres.  This accounts for most of the forms Mark identified that start with _21-xxx._  Since the records remained in Postgres, those forms appeared in search results, but the PDF link threw a 404 because it had been removed.  At that point, logic was added to flag records with invalid PDF links so that they could be suppressed from the search results.  Following this event, the team that manages the Find a VA Form product also asked the VA's forms DBA to add the 'deleted' field so they would know a form was purposely deleted/retired - and so that we could display a message letting users know that the record was indeed deleted or no longer valid, vs. just showing a "not found" message.

2. The other issue involves forms that were renamed by the VA, but whose records got duplicated in Postgres because the name was used as the unique ID.

**Comment by NCHLiberty** [comment] 2021-03-25 15:45
ok thanks! 

We are digging in deeper on our end to confirm whether other api users are **really** using the historic metadata and if they are not we will just delete anything which does not have a row ID including these leftovers from prior to the deleted_at change, (and of course the duplicates as well.)

Question - Marks change to populate the rowid is teed up for today but is contingent upon VSP platform deployment and there are problems with the builds (and have been lately). If the PR does not deploy successfully prior to 2pm, we can avoid retrying tomorrow, but would you agree we can go ahead on Monday? What is the reason for avoiding Mondays? We want to get this in as quickly as possible and then get the third change to begin using RowID implemented. IF today's build is not successful, ok with skipping Friday but and I'd rather not wait till Tuesday.   Everyone ok with that?

**Comment by johnhashva** [comment] 2021-03-25 16:53
@NCHLiberty + @mviterna + @MarciMcGuireGCIO  (+ @jenniferlee-dsva FYSA)  -- we are going to give VA Stakeholders until end of day Monday to respond to our email (going out today) notifying them of the duplicate form deletions we plan to make as part of this process -- so let's plan to deploy on Tuesday.

**Comment by mviterna** [comment] 2021-03-25 16:57
@johnhashva The push I just did was only to populate rowid on existing forms in postgres. Not delete any orphaned / duplicated records. Are we still good to roll that out today? Delaying the rowid import will push out the final fix towards the end of next week and risk not going in on this sprint. I don't want any confusion around what is currently in the pipeline for deployment.

**Comment by mviterna** [comment] 2021-03-31 14:18
We had many discussions with various stakeholders on this issue. We have completed all code change over to row_id. There are several 21-9060 DBQ forms that are no longer "Forms". These are also present in the local postgres DB, but not Drupal. Per our conversation with the VA, we will be removing these, along with the handful of records that were duplicated as a result of changing the VA From Number. I'm attaching a list of all Forms that will be removed. These have been confirmed not to have a corresponding row_id in the Drupal CMS, and therefore will be removed from postgres.

**Comment by mviterna** [comment] 2021-03-31 14:18
"10-10EZ (pdf)"
"VA4637"
"10-0484"
"VA0927a"
"VA0927b"
"VA0927d"
"VA0927e"
"VA10002"
"VA0927c"
"10-0485"
"10-0137B"
"VA4670"
"VA8"
"VA0880b"
"VA3215"
"VA646"
"VA4667c"
"VA0862"
"VA Form 22-8979"
"VA0880a"
"21-0960J-3"
"21-0960M-9"
"21-0960N-2"
"21-0960P-2"
"21-0960A-3"
"21-0960C-9"
"21-0960E-1"
"21-0960G-1"
"21-0960G-2"
"21-0960K-2"
"21-0960C-4"
"21-0960I-5"
"21-0960C-10"
"21-0960J-1"
"21-0960C-8"
"21-0960G-5"
"21-0960G-6"
"21-0960I-6"
"21-0960M-2"
"21-0960M-14"
"21-0960N-1"
"21-0960C-5"
"21-0960M-4"
"21-0960M-11"
"21-0960M-13"
"21-0960P-1"
"21-0960E-2"
"21-0960E-3"
"21-0960C-3"
"21-0960C-6"
"21-0960C-7"
"21-0960I-2"
"21-0960I-4"
"21-0960D-1"
"21-0960N-4"
"21-0960L-1"
"21-0960Q-1"
"21-0960F-2"
"21-0960M-15"
"21-0960G-3"
"21-0960M-16"
"21-0960F-1"
"21-0960I-1"
"21-0960M-12"
"21-0960M-3"
"21-0960G-7"
"21-0960H-2"
"21-0960C-11"
"21-0960L-2"
"21-0960M-1"
"21-0960M-7"
"21-0960M-10"
"21-0960H-1"
"21-0960I-3"
"21-0960N-3"
"21-0958"
"21-0960A-2"
"9"
"21-0960C-2"
"21-0960G-4"
"21-0960K-1"
"VA4667b"
"21-0960A-1"
"21-0960B-1"
"21-0960C-1"
"21-0960A-4"
"21-0960G-8"
"21-0960J-2"
"21-0960B-2"
"21-0960M-6"
"21-0960P-3"
"21-0960M-8"
"21-0960J-4"
"26-1844"
"40-1330"
"10091"
"40-1330M"
"3288"
"5655"
"10182"
"40-10007"

**Comment by MarciMcGuireGCIO** [comment] 2021-03-31 14:40
I've compared the list above and those specific form names do not currently appear in the CMS.

**Comment by mviterna** [comment] 2021-03-31 15:08
@MarciMcGuireGCIO  Please confirm staging

**Comment by MarciMcGuireGCIO** [comment] 2021-03-31 15:19
@mviterna confirmed on Staging.

**Comment by MarciMcGuireGCIO** [comment] 2021-03-31 15:45
@mviterna cc @johnhashva @zacharymorel @NCHLiberty confirmed that the duplicates are no longer visible on Production! 🎉

**Closed by MarciMcGuireGCIO** 2021-03-31 15:45 UTC
Labels: Lighthouse, bug, dt-find-va-form, frontend, vsa, vsa-decision-tools
