### ISSUE TITLE
[Bug] Profile - Contact Info - Bad Address Indicator - Update Saved alert missing after Updating w/o changes

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#46036] opened 2022-08-22 19:03 UTC
## What happened?
On **Staging Profile > Contact Information** page, after Updating **Mailing** address _without_ any changes, the **Update saved** alert is missing.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: 121-126 [see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords]

## Steps to Reproduce
- URL: https://staging.va.gov/profile/contact-information
- Test User _(if applicable)_: [see **Specs** above]
- Under **Addresses > Mailing**, click **Edit** button, then click **Update** button immediately without making any changes.
- Observe that **Update saved** alert is missing.

### Screenshot
[Example from MacOS Safari]
![image](https://user-images.githubusercontent.com/587583/185996935-60f25ef9-db36-49d7-b709-ad158f364043.png)

## Desired behavior
- [ ] **Update saved** alert should be displayed below unchanged mailing address after Updating w/o changes. [See [this test-case](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-use-cases-profile-contact-bai.md#caseC2) provided by App-team.]

### Screenshot
From [this mockup](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/GmlvPr8):
![image](https://user-images.githubusercontent.com/587583/185996763-fcc5d2d6-13b8-482d-8237-3a9a7ea83e9d.png)

## Acceptance Criteria
[see **Desired Behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Samara-Strauss** [comment] 2022-08-23 13:06
This is actually desired functionality and not a bug. There is a rare edge case where someone has the bad address indicator but the address actually is correct (think moving out of your parent's house and then eventually moving back in).

**Comment by SKasimow** [comment] 2022-08-23 14:27
Closing...WAD.

**Closed by SKasimow** 2022-08-23 14:27 UTC
Labels: bug, frontend, vsa-authenticated-exp, profile, bad-address-indicator
