### ISSUE TITLE
[FE] Profile: Update alert for successfully updated DD info in profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31404] opened 2021-10-13 21:43 UTC
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user successfully updates their Direct Deposit info in profile.

This ticket is for [**Updates to alerts item 3**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#3-successfully-updated-direct-deposit-information-in-profile-31404) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears when a user successfully updates their Direct Deposit info in profile per the copy and specs in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#3-successfully-updated-direct-deposit-information-in-profile-31404)
- [ ] Test

## Acceptance Criteria
- [ ] The alert that appears when a user successfully updates their Direct Deposit info in profile is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#3-successfully-updated-direct-deposit-information-in-profile-31404)

**Comment by zacharymorel** [comment] 2021-11-01 14:23
SEE => https://github.com/department-of-veterans-affairs/va.gov-team/issues/31192

**Comment by andaleliz** [comment] 2022-05-18 16:23
Closing this as it is now a duplicate of the more details #41527

**Closed by andaleliz** 2022-05-18 16:23 UTC
Labels: frontend, vsa-authenticated-exp, profile
