### ISSUE TITLE
Possibly Rescue More BGS Exceptions and Reschedule Job

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#30784] opened 2021-09-30 21:51 UTC
## User Story
As a BE developer I would like dependency claims not to fail when BGS returns errors due to an outage. I would like the errors rescued and the job rescheduled for an hour later

## Expected Behavior
When BGS returns errors via `BGS::FormXXX.new(user).submit(claim_data)` (such as the two below), we reschedule the job

1. `HTTP error (504): upstream request timeout`
2. `TUX-20306 - An unexpected error was encountered`

## Acceptance Criteria
- [ ] Errors, outlined above, will be rescheduled
- [ ] A PR has been requested for merging

**Comment by tblackwe** [comment] 2023-08-15 21:37
Duplicate of #56290

**Closed by tblackwe** 2023-08-15 21:37 UTC
Labels: backend, vsa, vsa-ebenefits, 686, Tree
