### ISSUE TITLE
Review Content ROE with Get Care Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1438] opened 2019-08-29 19:23 UTC
### User story
As the new Get Care VFS Team, I need to know what's expected of my team in terms of the content that wee create for our tool, and what we can expect from VSP, so that we can move fwd efficiently and so that Veterans can easily find and interact with our tool.

### Goal
Collaborate with the Product Support team, and do whatever's necessary to proactively incorporate "content" into Get Care onboarding experience effectively, so they come away achieving the user story above.

### Definition of done

- [ ] Meet with appropriate Get Care team members to go over content best practices
- [ ] Meet with Get Care PM(s) to go over Content Review ROE (Rules of Engagement)
- [ ] Document findings and feedback from that meeting to recommend for doc iteration

**Comment by rroueche** [comment] 2019-08-29 19:25
@andreahewitt-odd do Epics exist yet for Onboarding Get Care and for Onboarding Care Giver? Trying to make sure have the content & IA team's tasks for those epics connected appropriately!

**Comment by peggygannon** [comment] 2019-09-24 21:38
Closing. this is a dupe of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/1440

We are now combining IA and Content intros meetings.

**Closed by peggygannon** 2019-09-24 21:38 UTC
Labels: content-ia-team
