### ISSUE TITLE
[FE] 10-10CG - Technical Discovery for Facility Selection update

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45497] opened 2022-08-09 19:20 UTC
Placeholder ticket for technical discovery for the amount of work and complexity to update the facility selector on the 10-10CG application to use the new Facilities API from Lighthouse instead of the internal list that it currently does.

**Comment by longmd** [comment] 2022-08-09 19:26
Duplicate of #45498

**Closed by longmd** 2022-08-09 19:26 UTC
Labels: 1010-team, 1010-cg, story
