### ISSUE TITLE
[Frontend] Add "preferred name" field to 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#32824] opened 2021-11-15 14:22 UTC
## User Story

**As a** veteran, **I want to** specify my preferred name on the 10-10EZ form **in order to** have my health care team address me by it.

## Expected Behavior

This the FRONTEND story to allow the veteran to provide their preferred name.

This does NOT need to be added for Spouse. Only for the veteran.

UX Design Ticket: #31552

## Acceptance Criteria

- [ ] UX Design is confirmed
- [ ] Frontend is updated based on UX design
- [ ] Functionality is tested in staging
- [ ] Critical Accessibility issues are addressed
- [ ] Validated via Review Instance
- [ ] **Turned off in prod (via toggle) until ES can accept!** (tied to SIGI)

## Additional information
- HEC team has not confirmed if this is a required question or not.
  - Update: HEC confirmed this is **not** required

- **Authenticated** (after MPI lock update) this question should appear first- see PDF page 1
- **Unauthenticated** this question should appear on the name page- see PDF page 2

### [Design PDF](https://app.zenhub.com/files/133843125/25aa40d0-929a-4918-b96c-e8fa34632df3/download)

**Comment by MickinSahni** [comment] 2021-11-29 18:23
@Dene-human can you remind me if HEC folks confirmed whether this is required?

**Comment by Dene-human** [comment] 2021-11-29 18:47
> @Dene-human can you remind me if HEC folks confirmed whether this is required?

Confirmed on last HEC call (11/23) that it will NOT be a required field.

**Comment by SKasimow** [comment] 2022-02-02 17:38
Discussed at Grooming: this needs a BE ticket, however the ES needs to be able to accept this before we do the work. We think it may be part of the SIGI effort.

**Comment by markfallows** [comment] 2022-09-23 18:18
Should this still be in the Icebox?

**Comment by markfallows** [comment] 2022-09-28 19:32
- [ ] Is this field on the paper form?
- [ ] Are we asking this on the VA Profile?
- [ ] Is this in the Enrollment System?

**Comment by markfallows** [comment] 2022-10-05 17:54
Updated with new information.

A *Preferred Name* field exists in the VA Profile, and an email has been sent to Joshua Faulkner to confirm whether the Enrollment System can accept such.

**Comment by markfallows** [comment] 2022-10-05 19:39
Response from Joshua Faulkner:

> No, we have not had a request to add preferred name to that service; but I suspect it will be coming at some point from the business.

**Comment by markfallows** [comment] 2022-10-05 19:40
@hdjustice With the confirmation that the Enrollment System does not support this field at this time, do you see any problem with me moving this feature into the Icebox until such a time that the ES can support it?

**Comment by hdjustice** [comment] 2022-10-05 20:48
@markfallows we can either move it or close it, since it isnt on our 'roadmap' yet.. either way is fine for me

**Comment by markfallows** [comment] 2022-10-06 19:24
Closing since this improvement is not on the roadmap at this time.

**Closed by markfallows** 2022-10-06 19:24 UTC
Labels: frontend, 1010-team, 1010-ez, sigi, story
