### ISSUE TITLE
Identity Dashboard (FE) - Create a middleware

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60791] opened 2023-06-23 15:11 UTC
## Description
Create a `middleware` file to reroute authenticated and unauthenticated pages

## Tasks
- [ ] I should be redirected back to the homepage instead of hitting a 404 (when I am unauthenticated trying to see an authenticated page)
- [ ] I should stay on the same page (when I am authenticated and try to see an unauthenticated page)

**Comment by ianmagenta** [comment] 2023-06-26 19:48
Looks like I made a ticket for this just a day before you created this one. The one I made is currently in review. Not sure if you want to close this one or have me close the other. Here's the link: https://github.com/department-of-veterans-affairs/va.gov-team/issues/60742. Feel free to let me know what you think!

**Comment by ianmagenta** [comment] 2023-06-28 16:45
Closing this one as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/60742.

**Closed by ianmagenta** 2023-06-28 16:45 UTC
Labels: Identity, identity-frontend
