### ISSUE TITLE
Appointment request message missing or too long

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#8113] opened 2020-04-17 13:31 UTC
Sentry error: http://sentry.vfs.va.gov/vets-gov/website-production/issues/110089

Looks like someone submitted a request where the message POSTed to the message endpoint was either missing or was too long. Only happened once in the last week.

**Comment by lenaecb** [comment] 2020-04-22 17:41
I think this is going to keep happening. I have a ticket to extend the character count for that message. Steven B is supposed to be looking into that on the VAMF side.

**Comment by jbalboni** [comment] 2020-04-22 17:52
@lenaecb We should be matching their limit on our side, so it's a bug if we're getting this error message. That's separate from whether the limit should be changed or not.

**Comment by vbahinwillit** [comment] 2020-04-29 20:31
Moving this issue back to the backlog due to the following:

- Error is occurring for a small number of users
- Unable to reproduce the error in staging

The error was traced to var-resources service, however it was not determined why the exception was thrown (was the message null or was the message character count > 0 characters). The error occurs for different users using different browsers.

**Comment by jbalboni** [comment] 2020-05-19 14:10
Moving this back into ready. It looks like this may be due to line breaks being converted from `LF` to `CRLF` after the front end length check, but before the var-resources check. We can follow what var-web does and convert line breaks to two characters for the purpose of our length check.

https://coderepo.mobilehealth.va.gov/projects/VAR/repos/var-web/browse/veteran-appointment-requests/app/modules/appointments/requested/request-new-message-form-view.js#96

**Comment by jbalboni** [comment] 2020-05-22 18:11
Moving this back again. I'm still unable to reproduce this issue in staging, so I've added more logging and we can reevaluate when that logging is in place.

**Comment by narin** [comment] 2020-06-03 15:59
Error hasn't popped up in Sentry since @jbalboni added logging.  Moving this back into Ready for now.

**Comment by lenaecb** [comment] 2020-10-09 18:03
This hasn't popped up in past few months. Closing.

**Closed by lenaecb** 2020-10-09 18:03 UTC
Labels: bug, frontend, vaos
