### ISSUE TITLE
Add billing tags on EBS snapshots

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2384] opened 2019-10-10 21:50 UTC

**Comment by jbritt1** [comment] 2021-05-03 13:18
@jhouse-solvd any way to check if this is still a priority? If it is not, can we close?

**Comment by jbritt1** [comment] 2021-05-03 13:39
Actually, this is a duplicate of #2385. Since 2385 has more info, closing this one and continuing the conversation on that one.

**Comment by jhouse-solvd** [comment] 2021-05-10 18:48
Hmmm, so there are tickets for billing tags on EBS volumes, and billing tags on EBS snapshots. I don't believe this is a duplicate. See comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1475#issuecomment-733282931)

Unfortunately, GH doesn't show the parent Epic very well, but see the graphic below: 

![Screen Shot 2021-05-10 at 11 47 10](https://user-images.githubusercontent.com/46828900/117709283-985e0f80-b185-11eb-82d6-3dc383d91252.png)


re-opening

**Closed** 2021-07-29 13:02 UTC
Labels: infrastructure, maintenance, operations
