### ISSUE TITLE
Staging:  Edit 'How Seen' on a Request Removes the Preferred Date and Time - 400 Bad Request Error

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#74123] opened 2024-01-22 16:15 UTC
Steps to Recreate:
1.  In CCM test Cheyenne Optometry to Yes Any.  Validate royal.tester@id.me does not have any pending/submitted Optometry request.  If there are any requests, cancel them.
2.  Log in as royal.tester@id.me.  Select start schedule, select Eye, Select Optometry.  Select Cheyenne.  you may need to select I need a different clinic if Direct Scheduling flow is enabled.
3.  Go through all the steps to create a request.  Stop at Review your appointment details.  DO NOT SELECT  'REQUEST APPOOINTMENT'  button.  
3.  Select to edit the How to be seen and change the value.  
4.  Select continue to return back to Review your appointment details.  
5.  Expected Response:  Request has been edited and the only thing changed was the How to be seen value. Request can be submitted. No errors in dev tools
6.  Actual Response:  Request has been edited and the the how to be seen value and Preferred Date and time has been removed. When veteran submits a response there is an error because Preferred Dates have been removed.    Dev tools shows as 400 Bad Request error.  
7.  
<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--682789a42c0f2f958ead0ac9a0b86ff0f3a7cae0/image.png" alt="image.png" />

**Comment by simiadebowale** [comment] 2024-01-31 17:23
@ldelacosta - was unable to reproduce this defect, can we move this to validate and ask the SQA to retest?

**Comment by marcynadeau** [comment] 2024-01-31 22:11
@ldelacosta I just retested and got the same issue. You must edit the how to be seen button for this defect to present.

**Comment by simiadebowale** [comment] 2024-01-31 22:24
okay, will retest.

**Comment by simiadebowale** [comment] 2024-02-07 16:56
@ldelacosta - this is ready for validation

**Comment by mshatalov-va** [comment] 2024-02-07 22:28
Testing was not able to reproduce the issue, it appears to have been fixed.  
Testing validated that user is able to go back on described screens/steps and change the values in the fields.  "How to be seen", "Preferred date/time" are being displayed as expected. User is able to submit the request. There are no errors in Dev tools.  @ldelacosta - FYI

**Comment by ldelacosta** [comment] 2024-02-07 22:33
No issues to report. Closing out the ticket.

**Closed by ldelacosta** 2024-02-07 22:33 UTC
Labels: bug, frontend, appointments
