### ISSUE TITLE
[CONSIDER] User support for "add to calendar" link

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10884] opened 2020-07-02 20:28 UTC
This is a placeholder issue based on feedback from Pittsburgh PAO

## Issue Description

> The add to calendar link – it is not clear what calendar this adds to.  It just says that you need to download an app.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment] 2023-05-16 18:54
Dupe of Public Websites bugs in CMS repo. CLosing.

**Closed by jilladams** 2023-05-16 18:54 UTC
Labels: cms, vsa, Facilities-v1, frontend-vamc, Pittsburgh MC, vamc-pages
