### ISSUE TITLE
PEGA reporting API - prod connection setup

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94284] opened 2024-10-03 18:12 UTC
As a member of the IVC forms team, I need the ability to pull PEGA status updates for an occasional audit against our records.

For the staging environment, there is a postman workspace that can be used to pull a report. Reach out to a member of the IVC forms team for a copy of the workspace. We need a comparable process so that we can pull similar reports in production with appropriate security.

### Acceptance criteria
- We can make a connection to the PEGA reporting API programmatically and all security prereqs are satisfied
- A member of the IVC Forms team can manually pull a batch of records from the prod version of vaGovReport-Stage

**Comment by andrea-merrill** [comment] 2024-10-16 20:19
Notes from Cindy:
* Keys are in Postman, put in our param store (they are access keys for us)
* Must be in VA network

**Comment by andrea-merrill** [comment] 2024-12-04 18:22
Blocking this story: [#95912](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95912) - Check most recent status  prior to sending most recent ZSF email

**Comment by stevelong00** [comment] 2024-12-06 21:11
It looks like the postman collection that Cindy provided is already configured with everything we need to query Prod.

Since Postman is not installed on GAC and will regularly get removed, here's how to set this up:
1. Download the postman collection that was provided via email
2. Download the postman app from postman.com/downloads
3. Install the app
4. Launch the app and sign in with your postman account
5. Drag and drop the collection onto the app to import it
6. Select the vaGovReport-Prod endpoint and modify the start and end date headers before using it to run your query
7. When you're done, delete the modified endpoint and the imported collection so that our keys are no longer stored within postman's cloud environment

**Comment by stevelong00** [comment] 2024-12-18 20:43
I just pushed my code for 94284 into a draft PR so that it's easier to share.

To run it locally:
- Save the Pega API key into an environment variable like so `export PEGA_API_KEY=insert1the2api3key4here`.  The API key can be found in the postman collection that Pega sent us.  If it's easier, I'd be happy to hop on a call and dictate it.
- Uncomment line 119 in `modules/ivc_champva/spec/lib/pega_api_client_spec.rb` to be able to see a non-error response.
- Run the new test suite like so `bundle exec rspec modules/ivc_champva/spec/lib`

Right now it's not working.  As best I can tell, it's configured to hit the prod API with the same headers that are used in the postman collection that we were provided.  Yet for some reason the API is responding with `{ "statusCode":500, "body", "'date_start'" }` when I hit it locally.  In CAG, I am able to get the same response via postman by omitting the `date_start` header.  I quadruple-checked that my code is sending this header, so I'm very puzzled as to what the problem is.  Maybe it's something obvious and I just don't see it.  If you can spot it, I've got a shiny quarter for you!

I asked Cindy if anything other than a missing `date_start` header could cause the API to give this response.  She replied that the API was modified last month for a daily report, which she will correct and let me know when ready.  So, it sounds like there may be a problem on the API side and not with this client code.  That was yesterday (12/17) and I have not heard back yet.

**Comment by michaelclement** [comment] 2024-12-23 20:36
As of today this is working. There was a capitalization issue with the post request headers that was causing the request to fail. After a small change on the Pega side, we're able to hit the API programmatically as described in the AC.

**Comment by michaelclement** [comment] 2024-12-26 16:39
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19951)

**Comment by stevelong00** [comment] 2024-12-31 18:25
Merged.  @baltes Nothing is using this client code yet, so there's nothing to review.  Moving this to closed.

**Closed** 2024-12-31 19:44 UTC
Labels: backend, ivc-forms, zero-silent-failures, ZSF:CodeReliability
