### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by pscruz** [department-of-veterans-affairs/va.gov-team#49976] opened 2022-11-22 21:51 UTC
# Product Outline

## High Level User Story/ies
As a technologist, I need to understand users' needs so I can develop solutions that meet them.

## Hypothesis
**If** we do research with users **then** we will build solutions that meet their needs well.

## Definition of done
This epic is complete when we have completed all user research studies with users and staff who deliver these services – and we feel confident that the solutions were proposing, building and implementing meet people's needs without causing issues, confusion or drop offs.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by tygindraux** [comment] 2022-11-23 13:37
@elizabethkochBT – Here's the epic Pablo and I created. Please let me know what template you'd like me to use for this epic; but for now we have this.

**Comment by tygindraux** [comment] 2023-01-30 19:22
@elizabethkochBT – Happy for you to keep this epic if it's useful for you, but I know we've talked about removing it. I'm happy for it to be removed.

**Comment by elizabethkochBT** [comment] 2023-03-17 14:12
canceled as duplicate of other tickets

**Closed** 2023-03-17 14:12 UTC
Labels: Epic, research, needs-refinement, login.gov-adoption
