### ISSUE TITLE
ces-643

### ISSUE THREAD

**Issue by BrittanySFowler** [department-of-veterans-affairs/va.gov-team#88506] opened 2024-07-16 18:03 UTC

**Comment by drewconnelly** [comment] 2024-07-17 11:58
Duplicate of [#463](https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/zh/463)

**Closed** 2024-07-17 11:58 UTC
Labels: apps-oracle-health-integration

**Comment by BrittanySFowler** [comment] 2024-07-17 17:18
This was created as a duplicate
