### ISSUE TITLE
[CAIA Intake] ARM: New link in VA.gov footer

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84354] opened 2024-05-31 17:23 UTC
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Accredited Representation Management
- **OCTO product owner:** Jennifer Bertsch
- **Product name:** The ARM team has three products: Find a Representative, Representative Status Widget, and Appoint a Representative.  This request is for the landing page that contains the Widget and entry points to Find and (future) Appoint.
- **Product manager:** Lindsay Li-Smith
- **Slack channel:** benefits-representation-management
- **Dedicated content writer on your team (if you have one):** No one on our team, we've been partnering with A Procik in CAIA.
- **Dedicated a11y specialist on your team (if you have one):** No one on our team, we've been partnering with Jamie Klenetsky Fay in CAIA.

 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else:  We would like to add a "**Get help filing a claim**" link to the footer, under the "Veteran programs and services" section.  This would point to our landing page: https://www.va.gov/get-help-from-accredited-representative/

### What's the nature of your initiative and desired outcomes?

Our goal is to increase awareness and traffic to Accredited Representation Management products.  We are looking to include our [landing page](https://www.va.gov/get-help-from-accredited-representative/) in the footer, as it is a hub for all of our products -- Find a Representative, Representative Status Widget and (coming soon) Appoint a Representative.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

ASAP

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [ ] I’m not sure

This update would support the following policy and initiative:

- [Section 5901](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title38-section5901&num=0&edition=prelim) - specifically (C)
- [Predatory Practice Initiative](https://www.va.gov/initiatives/protecting-veterans-from-fraud/)

### Where are you at in your timeline?

The [landing page](https://www.va.gov/get-help-from-accredited-representative/) is live in production.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

This request is related to a [landing page](https://www.va.gov/get-help-from-accredited-representative/) owned and managed by CAIA, and exists in Production today.

## Collaboration cycle 

This is independent of our collaboration cycle work.

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Veterans would like to search for representation, but are unsure where to go to do this.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-04-ARM-veteran-representative-experience-interviews/research-findings.md#search-challenges)
- [In a navigation task, users went to the VA.gov footer to find the Find a Representative tool.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-03-ARM-findarep-live-usertest/research-findings.md#task-1-navigate-to-the-find-a-representative-landing-page-or-tool)
- [Post-launch traffic reveals](https://docs.google.com/spreadsheets/d/1Ne8H_hywzWcL5007MWY0ExpoCBJ0SjHRlkPHVtm7cJU/edit#gid=158811065) our landing page is comparable to va.gov/disability/eligibility/ which currently exists in the Disability top navigation 
- A marketing email went out to Veterans on 5/2, which included a link to our landing page and resulted in a [large spike in traffic](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240310&_u.date01=20240529&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fget-help-from-accredited-representative~2F/).  This indicates desirability for this information.
- This is a universal tool that impacts Veterans at all points in their journey, so placing it in the footer would be a more universal option.  Other teams (Profile, MyVA and Claims Status Tool) have encountered the desire for accredited representative information to be easily accessed.
- [This is how our Accredited Representation Management work relates to the Homepage Rubric](https://docs.google.com/document/d/1p0h5yN9Hd9Zuh8MMvgCTvfLnnYMsarIkJvdsh2Pp3Z8/edit?usp=sharing)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [x] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by mnorthuis** [comment] 2024-06-03 15:45
@oddball-lindsay The first column is for specific audiences and programs and a link cannot be added there.  

We had planned to replace the existing accredited claims rep link in the "More VA resources" column - that column is intended to be Veteran resources, not for non-Veteran audiences, so having a link to accreditation info was not the long term plan.  When we launched, it was the only access point to the existing tool to find a rep, so that is why it was placed there.  

The link text needs to coincide with the destination page's H1 - "filing a claim" is not part of that H1.  I would suggest something along the lines of "Get help from an accredited rep", but please work with content to finalize that link text. 

I would also recommend that on your Get help from an accredited rep page, that you add a link in the ["More information" section ](https://www.va.gov/get-help-from-accredited-representative/#how-to-contact-us-if-you-have-)that goes to the [OGC page](https://www.va.gov/ogc/accreditation.asp) for "Accreditation".  That will ensure a loop back to the OGC for that audience.  

Is there also a plan to redirect the old accreditation search tool?

**Comment by oddball-lindsay** [comment] 2024-06-03 21:56
> Is there also a plan to redirect the old accreditation search tool?

We do plan to redirect the old accreditation search tool from OGC, but there are a few to-dos before that happens:
1. Our Find a Representative product should support searching for an entire Veteran Service Organization, not just individual representatives (currently in design/research for a future iteration)
2. The URL https://www.va.gov/ogc/apps/accreditation/index.asp is tied to a daily job that houses accredited representative data and we're using this right now to power the search results in Find a Representative.  We will soon move off of that daily job for a direct API integration (the endpoints are being built now), but we're not sure if others are referencing this daily job for other products.  Redirecting will affect that daily job's functionality, so we should first identify if any other parties will be affected by the redirect.

------------

> The link text needs to coincide with the destination page's H1 - "filing a claim" is not part of that H1.  I would suggest something along the lines of "Get help from an accredited rep", but please work with content to finalize that link text.

The "Get help filing a claim" link request was from a [research recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-03-ARM-findarep-live-usertest/research-findings.md#quicker-fixes), as the entry point within the [Survivors Pension](http://va.gov/pension/survivors-pension/) page titled "Get help filing a claim" shows 11% of users who see the page come to the ARM experience. Verses other top sources of traffic for the ARM experience, only 2% or less of users click through.  Survivors Pension does not mention accredited representative in their link ‘Get help filing your claim’ and is higher on the ‘How do I apply for a VA Survivors Pension?’ list.

The suggestion "Get help from an accredited rep" likely won't hit address our goal of increasing awareness and traffic, as "accredited representative" is not a commonly recognized term by Veterans.  

Users in testing gravitated to the terms "VSO" or "VSO Rep", so we could do "Get help from a VSO" or "Get help from a VSO representative".  It's not fully accurate because there are other types of representatives mentioned on the page, but for find-ability purposes perhaps this is the best we can do with the restriction.  @aprocik1 @jfinnerty13 thoughts?

**Comment by kristinoletmuskat** [comment] 2024-06-03 22:11
Just noting that we'll need to figure out the following as well:

1) who updates the footer -- is it public websites?
2) how much notice they need

@mnorthuis we can chat about the link label at our sync on Wednesday!

**Comment by mnorthuis** [comment] 2024-06-04 14:38
Thank you for the background on the OGC tool, that is helpful to know!  

For the footer link - These reps do more than help you file a claim, and that needs to be represented in the link - filing a claim, applying for benefits, requesting decision reviews/appeals all need to be represented.  Also, per content and link standards, the link needs to utilize the same terminology as the H1 of the page to avoid a cognitive disconnect.   

The link on the pension page actually needs to be updated to follow these same standards - @aprocik1 I believe the rolling content audit should catch this, or it could be updated at any time.

**Comment by aprocik1** [comment] 2024-06-04 16:52
@bethpotts, you and I discussed link labels for the accredited rep page a few weeks ago. As a reminder, I did some research into the analytics for various link labels. The analytics show that "get help from an accredited representative" performs worse than these action-oriented link labels:
- Get help filing a claiming
- Get help filling out an application
- Get help requesting a decision review

You approved us to use the action-oriented link labels, instead of the link label with "accredited representative" included. As a result, we published updated link labels on about 45 pages.

Can you discuss this with @mnorthuis to determine if we need to undo that work?

**Comment by mnorthuis** [comment] 2024-06-05 18:17
@aprocik1 stepping back my comment on the link on the pension page - those links are in context with the rest of the page, and also have additional content surrounding them that provide more information.  In that case (very contextual placement) the "Get help" language at the beginning of the link and the H1 helps make the cognitive connection to the landing page.  My apologies for causing any churn on that, I did not look close enough at the page. 

The direction on the footer link still stands.  It is in a global position and needs to encompass the full context and purpose of that landing page - which is about finding/getting help from an accredited rep - so it does not exclude a use case.   Filing a claim is only one use case.  

You could work in the VSO term to help, just be conscious of link length.  The existing link label is 33 characters long and the longest link in the column.

**Comment by kristinoletmuskat** [comment] 2024-06-06 16:05
Hello! Some updates:
1. We confirmed that CAIA has ability to change the footer link in Drupal, so we don't need to coordinate or wait on any other team
2. The only thing holding us back right now is communicating with OGC -- Mikki said she was going to talk to Leslie about chatting with them, so waiting to see when that convo might happen. @oddball-lindsay feel free to chat with Leslie about that timing. We don't officially need OGC approval, but want to respect your relationship with them if you would rather inform them in a certain way!
3. Given that our user research on the link label indicates that action-oriented CTAa works best (get help WITH vs get help FROM), we want to pursue doing the same in the footer. We want to make sure the label doesn't just refer to filing a claim, so were proposing something like 'Get help applying for benefits' or 'Get help applying for benefits or requesting a decision review' -- @aprocik1 can you chat with Beth to finalize what ya'll think that label should be?

@oddball-lindsay

**Comment by oddball-lindsay** [comment] 2024-06-06 20:49
@kristinoletmuskat I checked in with Lesley and she said there was a "behind the scenes" conversation and are all for changing that link to point to ARM's work.  So we have the green light from an OGC perspective :) but do we still need to seek VBA approval for this change?

**Comment by kristinoletmuskat** [comment] 2024-06-06 21:57
Woo great @oddball-lindsay ! We do not need to get VBA approval, but we can send them an email notifying them of the change. Do you have a contact there you want me to email?

**Comment by bethpottsVADEPO** [comment] 2024-06-06 22:12
Mikki and I have been discussing the link label and have come to a decision. We'd like to go with the approach of matching the H1 (almost--we don't want to include "VA"). So it would be: **Get help from an accredited representative or VSO**

**Comment by oddball-lindsay** [comment] 2024-06-06 22:47
@kristinoletmuskat our VBA stakeholders are kevin.schneider1@va.gov, Brandi.Traylor@va.gov and Martin.Caraway@va.gov.  Please also cc Jennifer.Bertsch@va.gov and lesley.ropp@va.gov 🙏

**Comment by kristinoletmuskat** [comment] 2024-06-11 21:01
Great! Just emailed the stakeholders so we are good to go to make this change.

**Comment by kristinoletmuskat** [comment] 2024-06-11 21:03
Just made the change, waiting to verify in prod (can take 1-2 hours)

**Comment by kristinoletmuskat** [comment] 2024-06-12 16:45
Verified in prod! Closing this ticket

**Closed by kristinoletmuskat** 2024-06-12 16:45 UTC
Labels: sitewide IA, sitewide CAIA, accredited-representation-management-team
