### ISSUE TITLE
Update link in Change your VA direct deposit information section

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#8419] opened 2020-04-24 20:37 UTC
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional Information

Epic #8395 
Related to ticket #5525 

https://staging.va.gov/change-direct-deposit/

![Screen Shot 2020-04-24 at 10.27.45 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/079014c0-1f3a-49d3-b168-4390a3989d4a)

## Tasks

- [ ] Update 'Go to your profile link' to updated url

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by tressaellen** [comment] 2020-04-24 20:38
@mshea0606 please review

**Comment by erikphansen** [comment] 2020-05-01 15:47
@tressaellen what page/URL is the screenshot from? It seems like it's from a Drupal page. Which means:
1) someone on the content team (or maybe public website team?) would need to change it; we don't have access to the Drupal CMS.
2) we _likely_ can't update the link to go to `profile/direct-deposit` until after Profile 2.0 is live to 100% of users. So this change will be blocked until then.

**Comment by tressaellen** [comment] 2020-05-01 16:12
@erikphansen it's from https://staging.va.gov/change-direct-deposit/
That's okay, we can hold off until profile 2.0 is live.

**Comment by mshea0606** [comment] 2020-06-24 18:47
@erikphansen investigate if these widgets have access to feature flags

**Comment by Samara-Strauss** [comment] 2020-07-13 15:20
Do we have a status update on this? I thought we determined we aren't updating content pages until we are at 100%. Want to see if (1) I am remembering that correctly and if (2) that means we can close out this ticket.

**Comment by tressaellen** [comment] 2020-07-13 15:30
@Samara-Strauss you are remembering correctly! Would we need to make another ticket to update the links when everything is 100%? Or how do you recommend tracking that this gets done?

**Comment by Samara-Strauss** [comment] 2020-07-13 15:47
@tressaellen good question! My initial thought is that it would be super helpful if we had an epic for post-launch that outlined all the content URL updates that needed to happen. Could you work with @mshea0606 to consolidate those and create a ticket?

**Comment by tressaellen** [comment] 2020-07-13 15:54
@Samara-Strauss will do!

**Comment by Samara-Strauss** [comment] 2020-08-06 17:35
Closing since #12032 was created and is a duplicate of this one.

**Closed by Samara-Strauss** 2020-08-06 17:35 UTC
Labels: blocked, design, frontend, ia, profile, vsa-authenticated-exp

**Comment by mshea0606** [comment] 2020-08-06 18:01
@Samara-Strauss @tressaellen [Post Launch] Profile 2.0 Post Launch content/URL Updates #12175 has been created
