### ISSUE TITLE
[Bug] Find VA Forms - Results styling not matching design specs

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8200] opened 2020-04-21 02:49 UTC
## What happened?
During VSA-QA testing (#6900) of live [**Find a VA form**](https://www.va.gov/find-forms/) page, search results styling do not match design specifications:

1.  **Showing...results** subhead numerals are not displayed in bold.
2.  **Result-titles** that aren't detail-links are not displayed in black.
3.  **Bottom border** is missing from bottom-result \[for searches returning <9 results].
4.  **Bottom border** is different for the 10th/20th/30th... results \[for searches returning 10+ results].
5.  **Pagination controls** are not left-aligned.

## Specs:
- Bug is browser-/device-agnostic
- Test User _(if applicable)_: **veterans** \(ID for basic HTML-auth) -- request password from @stephorkandatx

## Steps to Reproduce
1.  Go to https://www.va.gov/find-forms/ \[obtain access credentials from team-PM]
1.  In **Keyword...** text-field, input **caregiver**
1.  Observe that:
  - The numerals in **Showing... results...** subhead are displayed in normal font-weight
  - The result-title is displayed in blue (but it's not a form-detail link)
  - There's no bottom gray border below the single-result
1.  In **Keyword...** text-field, input **medical** \[replacing "caregiver"]
1.  Observe that:
  - the last result's bottom gray border is different from those of results above
  - pagination text-alignment is not left.

### Screenshots

**1. Showing...results subhead numerals not in bold**:
![ff-styling-bug-01](https://user-images.githubusercontent.com/587583/79826070-9abdb380-834f-11ea-82cd-e9475ad5ff7e.png)

**2. Non-detail-link result-titles not in black**:
![ff-styling-bug-02](https://user-images.githubusercontent.com/587583/79826152-cf316f80-834f-11ea-8818-5ea87c856856.png)

**3. Bottom border missing from bottom result \[searches returning <9 results]**:
![ff-styling-bug-03](https://user-images.githubusercontent.com/587583/79826320-3f3ff580-8350-11ea-869f-0bba0b68ceab.png)

**4. Bottom border different for bottom result \[searches returning 10+ results]**:
![ff-styling-bug-04](https://user-images.githubusercontent.com/587583/79826389-70202a80-8350-11ea-9afc-1ccd273217d8.png)

**5. Pagination not left-aligned**:
![ff-styling-bug-05](https://user-images.githubusercontent.com/587583/79826404-7c0bec80-8350-11ea-8c87-931742a3eff0.png)

## Desired styling
Refer to [this design PDF](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/design/VA-Form-search-landing-results.pdf):

**1. Showing...results subhead numerals in bold**:
![ff-styling-spec-01](https://user-images.githubusercontent.com/587583/79827350-ed4c9f00-8352-11ea-8822-1b2bdf7cf765.png)

**2. Non-detail-link results-titles in black**:
![ff-styling-spec-02](https://user-images.githubusercontent.com/587583/79827385-02293280-8353-11ea-8788-62a14eb82128.png)

**3-5. Result bottom border present & same as result above, Pagination left-aligned**:
![ff-styling-spec-03-05](https://user-images.githubusercontent.com/587583/79827604-a3b08400-8353-11ea-81ba-758af2ec2dfc.png)

## Acceptance Criteria
\[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by tlei123** [comment] 2020-04-21 17:56
@stephorkandatx , assigning this Bug to you for planning/grooming -- I haven't set the Pipeline(s) or Miilestone here yet.

FYI, I was tempted to add **design-system** label here.  Some items called out \[e.g., the pagination numerals and alignment] may be deviations from our standard design-system widget defaults.  cc @lwalsh617

**Comment by jenniferlee-dsva** [comment] 2020-10-07 15:24
Most of this looks like a duplicate of https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1145

**Comment by zacharymorel** [comment] 2020-11-25 17:05
@tlei123 , @MarciMcGuireGCIO , @johnhashva I've fixed locally everything side of #5 on the list above. After digging in to #5, I've come to realize that this component is from the site wide [Pagination component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/pagination/) VA design library which is maintained by VSP. 

We'd have to request VSP to build the functionality for allowing the left aligning of the pagination text when the consumer is on the 1st page of results.

**Comment by MarciMcGuireGCIO** [comment] 2020-11-25 17:19
I'll check with Jennifer.  On VA.gov the Facility search is centered vs. left-aligned.  It may be as simple as the design PDF didn't reflect the positioning that is included in the component spec.

**Comment by jenniferlee-dsva** [comment] 2020-11-25 20:16
I would not take the left-aligned pagination on Ryan's design as intentionally different from the design system, if it is different. 

> It may be as simple as the design PDF didn't reflect the positioning that is included in the component spec.

Exactly so,  @MarciMcGuireGCIO

**Comment by zacharymorel** [comment] 2020-11-25 20:17
Thank you @MarciMcGuireGCIO @jenniferlee-dsva

**Comment by sshein** [comment] 2020-11-25 21:10
Probably don't need me here, but just in case: I agree with @MarciMcGuireGCIO and @jenniferlee-dsva we should go with the design system here and not do a one-off customization

**Comment by zacharymorel** [comment] 2020-11-27 22:21
@tlei123 , @MarciMcGuireGCIO , @johnhashva this is ready for validation!

**Comment by MarciMcGuireGCIO** [comment] 2020-11-30 13:08
Thanks, Zach!  I reviewed on Dev and everything checks out apart from #5, which Jennifer agreed above should follow the design system guidance, so therefore does not require a change.

**Comment by johnhashva** [comment] 2020-11-30 13:42
@zacharymorel Looks good to me.

**Comment by zacharymorel** [comment] 2020-11-30 14:03
Okay, not sure on the process for this one, I think @tlei123 might still need to verify?

**Comment by MarciMcGuireGCIO** [comment] 2020-11-30 14:05
I'm not either, but since he did the initial review, I imagine that is the
case.

**Comment by jenniferlee-dsva** [comment] 2020-11-30 14:08
Please be sure to pull myself and @rtwell in for validation of design implementation. We'll be able to answer a lot of your questions.

**Comment by MarciMcGuireGCIO** [comment] 2020-11-30 14:15
> Please be sure to pull myself and @rtwell in for validation of design implementation. We'll be able to answer a lot of your questions.

@jenniferlee-dsva @rtwell -- Zach had made all of the prescribed changes with the exception of item 5 related to pagination alignment.  On other VA.gov pages we reviewed, pagination is centered; however, the design for this page shows it left-aligned.  Can you confirm that this search result page should follow the pattern established in the design system (centered), or was it intentionally left-aligned in the design?  Thank you!

cc: @zacharymorel @johnhashva @tlei123

**Comment by zacharymorel** [comment] 2020-11-30 14:15
Oh thank you @jenniferlee-dsva , do you mind having a look at these?

**Comment by jenniferlee-dsva** [comment] 2020-11-30 15:29
1/ 

>  Can you confirm that this search result page should follow the pattern established in the design system (centered), or was it intentionally left-aligned in the design? 
 Not intentional - please use the design system centered pagination. 

2/ As you can see, there are several small things in the mockup above that are outdated. (Example, we're not showing "Revision date" anymore, we are using "Form last updated" text, and so on.) 
Because this ticket was created so long ago, and prior to iterations on the form landing pages, just pull me and Ryan in when implementation can be visually validated, either in preview, staging, or screenshot of implementation.  Nothing bad on you guys - it's just that this is a very old ticket and somethings stayed the same, ,some things are slightly different.

**Comment by zacharymorel** [comment] 2020-11-30 16:25
Thanks @jenniferlee-dsva !

**Comment by MarciMcGuireGCIO** [comment] 2020-11-30 17:37
@tlei123 this issue is ready for QA validation.

**Comment by MarciMcGuireGCIO** [comment] 2020-12-01 13:37
@jenniferlee-dsva, @rtwell This ticket is ready to be visually validated on Dev https://dev.va.gov/find-forms/?q=10.  Thank you!

**Comment by rtwell** [comment] 2020-12-01 14:02
Looking good and thank you everyone for your work on this! Question: I have a couple small items, but they are not part of the acceptance criteria of this ticket. Should I make a new ticket? Document them here? 

As far as the edits marked on this ticket, I don't see any glaring errors and it looks fantastic!

**Comment by zacharymorel** [comment] 2020-12-01 14:24
Thank you @rtwell . Could you please write up a new user story and link it here so we can groom it?

**Comment by jenniferlee-dsva** [comment] 2020-12-01 15:14
@MarciMcGuireGCIO @zacharymorel  - I was able to validate using the dev environment link provided ^. 

I was able to validate only that the bolding and the "Form last updated" label text change had been updated. I was not able to see and validate any updates showing the online tool button and link to the form detail landing page however. Are those updates being addressed separately? (I ask because the list of items in Tze's og ticket above includes these updates as well.)

CC @johnhashva @rtwell

**Comment by zacharymorel** [comment] 2020-12-01 15:21
Morning! The online tool button and blue link to the form will be addressed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453.

**Comment by MarciMcGuireGCIO** [comment] 2020-12-01 15:22
@jenniferlee-dsva links to detail pages will be addressed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453.   If I'm reading correctly, [Tze's enumerated comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8200#issue-603665220) are calling out that non-detail links should be in black, not blue.

**Comment by tlei123** [comment] 2020-12-01 16:37
@MarciMcGuireGCIO , all styling mismatches on THIS defect has been validated fixed on Staging.

Barring convo above re. #11453, this can be Closed.

cc @zacharymorel @jenniferlee-dsva

**Comment by MarciMcGuireGCIO** [comment] 2020-12-01 16:42
Thanks, @tlei123 ! @jenniferlee-dsva, @johnhashva please let me know if I can close this issue with the expectation that the links to details pages will be added in #[11453](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453).

**Comment by jenniferlee-dsva** [comment] 2020-12-01 18:09
awesome, thx for the clarification!

**Closed** 2020-12-01 18:48 UTC
Labels: Awaiting Merge, bug, dt-find-va-form, frontend, vsa-decision-tools
