### ISSUE TITLE
[CONSIDER] Vet Center new client intake form

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32200] opened 2021-10-29 17:18 UTC
## Issue Description
Field staff at Vet Centers use a new client intake form during the first visit. 
Suggestion: make form available on Vet Center pages so clients could print it out and bring in OR fill out online

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by davidmpickett** [comment] 2024-08-13 23:42
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18863

**Closed by davidmpickett** 2024-08-13 23:42 UTC
Labels: vsa, Facilities-v1, Vet Center, feature request/Vet Center
