### ISSUE TITLE
[a11y Support] Accessibility Fix Request from Benefits Team 1

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#50215] opened 2022-12-01 13:39 UTC
## Status

**[2024-02-27]** 
- Laura Flannery verified the list of pages to see if any others need H2; refer to [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50215#issuecomment-1966695750) for the results.
- Laura's conclusion: Based on this list (and not including the ones where I couldn't find a Drupal page), H3 does look like it is the correct default heading level - there being 11 H3's and only 9 H2's - there is not an overwhelming majority though. I had to ask Megan Zehnder a question about a page and she mentioned they have been putting more content into widgets so I asked her what she thought would be the more common pattern going forward and she said she would get back to me.

**[2024-02-21]** 
- Jill Adams reported that the CTA widget is used across several health apps pages (e.g. test results, refill rx, schedule an appt, etc.), and Chris Kim (PW FE Engineer) confirmed this is the same CTA widget code used on our other pages (e.g. Rx refill, secure messaging, etc.). The header level was set to default H3 when this converted to the [va-alert DS component:](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13860). To use H2 instead, you have to override and pass that in. 

## CAIA Assignees
- CAIA Team Member 1
- CAIA Team Member 2 (if needed)

## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
    
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We found in an accessibility audit that the organization of headings was not ordered logically for users with screen readers. We're looking for someone to change the heading levels on the `<SignIn/>` CTA Widget and the `va-detailpage-sidebar` to be more accessible to folks using screen readers. I've attached a screenshot of the Headings Map tool output: 
![image](https://user-images.githubusercontent.com/462039/204887395-5eff4650-75d5-40d0-9f1e-7259c3afb406.png). Please also see the linked ticket under the *Supporting Artifacts* section

Specifically:
1. The "Sign in" CTAWidget heading should be an `<h2/>` instead of an `<h3/>`.
2. "Download your VA letters on your mobile device..." should be an `<h3/>`, not a `<h2/>`

Please feel free to reach out if y'all need more info. Thank you!

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 (Not a new product)

**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45636

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: n/a
- Estimated staging review date: n/a
- Content and IA work needed by: No date specified, but this has been flagged as a "serious accessibility issue"

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Kevin Duensing
-	Product/team Slack channel: https://dsva.slack.com/archives/C5AGLBNRK
-       Accessibility Lead: Josh Kim

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by kjduensing** [comment] 2023-01-12 20:25
@RLHecht I know y'all are busy, would you mind sharing a quick status update when you get the chance? Thanks!

**Comment by RLHecht** [comment] 2023-01-13 16:23
Hi @kjduensing the sign-in widget is not something our team manages. I believe this is in the design system as an H3 so would need to be changed universally. 

We also didn't create the mobile device alert in drupal. It was created by the mobile team and we added it to the static page. So we wouldn't be able to fix this one either unfortunately.

**Comment by RLHecht** [comment] 2023-01-25 15:27
@kjduensing Let me know if i should close this out or take it off our board. Thanks!

**Comment by joshkimux** [comment] 2023-03-13 12:10
@RLHecht got it! I'll write up a bug ticket for the DST

**Comment by joshkimux** [comment] 2023-04-27 11:41
@kjduensing @RLHecht small bump on this; would y'all or anyone y'all know have an answer to the prior question? I can also try to ask in the design system channel.

**Comment by RLHecht** [comment] 2023-04-27 13:27
That sounds right to me, but also not an engineer so I'm not sure how this gets fixed! We can put in a new sign-in widget if someone can tell us the app code we'll need. Though I don't know if that's what's needed.

**Comment by kjduensing** [comment] 2023-04-27 13:37
So small caveat - I'm not real familiar with the design system components. That said, looking at the docs, it appears you can specify the html tag of your choosing for the headline ([Stories -> "View code" on any of the examples](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt#sign-in-or-tool-prompt)):

```jsx
<va-alert>
  <h2 slot="headline">
    Track your claim or appeal on your mobile device
  </h2>
  
  // ...

</va-alert>
```

My take on this is whoever owns the sign in widget has rendered this `va-alert` with an `h2` instead of an `h3`.

Hope it helps!

**Comment by kjduensing** [comment] 2023-04-27 13:55
Actually, it might go deeper than that. The hierarchy of components is extremely customizable all the way down, which is great in some ways, but makes it difficult to track down exactly where the `headingLevel` property is set.

**Comment by joshkimux** [comment] 2023-04-27 14:53
> My take on this is whoever owns the sign in widget has rendered this va-alert with an h2 instead of an h3.

This is fantastic @kjduensing ! [Dumb question here on the download letters page
](https://www.va.gov/records/download-va-letters/)

1. given that the sign in widget should be rendered as a `h2`, is there a reason why it's showing up as a `h3` on this page?
2. and if we can fix it, who would be able to track down where it is and adjust it on this page specifically?

<img width="1688" alt="Screenshot 2023-04-27 at 10 51 03 AM" src="https://user-images.githubusercontent.com/14154792/234900821-8b9f6ac1-7336-42e6-b4b7-2482486dd406.png">

**Comment by kjduensing** [comment] 2023-04-27 15:08
1. Ah I see where I was unclear, thanks for the redirect. What we're seeing here isn't a bug. The sign in widget allows anyone who uses it to make the title whatever header level they want. So it isn't that the title is being rendered incorrectly due to a bug, it's that the title is _actually_ an `h3` in the code.
2. What we'd need to do to fix this is find the code that is setting the header level to an `h3` and simply change it to an `h2`. The change is trivial, but there are some challenges:
   * Finding where this code is is harder than I thought
   * When I do find the code, is it localized or would changing the code have a broader impact across the site?
   * If changes have a broad impact, who should be responsible for fixing this?

**Comment by joshkimux** [comment] 2023-04-27 15:17
@jamigibbs and @Mottie this might be a long shot, but by any chance do either of you have answers to Kevin's second question?

**Comment by jamigibbs** [comment] 2023-04-27 15:40
@joshkimux If this is the [va-alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--heading-level) component, then the way to change the header element for the "Sign in to get your...." text would be to use the `headline` slot with whichever header size needed.

This is wha @kjduensing  mentioned above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50215#issuecomment-1525711712

If we're unsure if this is va-alert, can you provide a link to where this is located? I'll be happy to inspect and confirm.

**Comment by kjduensing** [comment] 2023-04-27 15:41
I can confirm this is a va-alert :)

**Comment by Mottie** [comment] 2023-04-27 16:13
That page looks like it's a static content page, so you'd have to report the problem to the sitewide content people. I remember someone mentioned that they reported the `H4` placed before the `H1`, but I can't find the reference

**Comment by joshkimux** [comment] 2023-04-27 16:16
@RLHecht do you know of any engineers on the sitewide content team this could be assigned to?

**Comment by kjduensing** [comment] 2023-04-27 16:34
Right, @Mottie, but what's calling the CTA widget? I wasn't able to tell what sets the actual `headerLevel` prop..

**Comment by sara-amanda** [comment] 2023-09-12 02:30
@RLHecht or @SarahKay8 , do you know who we should best route this to? 
cc: @coforma-terry

**Comment by eli-oat** [comment] 2023-09-14 17:48
Uncertain who owns this code. Not sure about the next steps.

CAIA to check in with DST on Slack.

**Comment by coforma-terry** [comment] 2023-12-11 21:06
Hey @eli-oat - did DST shed any light on who owns this code?

**Comment by eli-oat** [comment] 2023-12-11 21:29
@coforma-terry followed back up for further info in the DST channel

**Comment by eli-oat** [comment] 2023-12-11 23:17
@coforma-terry -- per DST, this is owned by the [public websites/sitewide team](https://github.com/department-of-veterans-affairs/vets-website/blob/1ce416dd8dd8f725c139cf04fcf4aefaf0b938e7/src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx#L5).

**Comment by coforma-terry** [comment] 2024-02-14 22:28
@strelichl - we need to transfer this to public websites to implement 👍

**Comment by FranECross** [comment] 2024-02-16 18:21
@coforma-terry @strelichl Added to our next refinement to review. Thanks!

**Comment by jilladams** [comment] 2024-02-20 20:28
@laflannery FYSA, since this is about header levels. The CTA widget is used across several health apps pages (e.g. test results, refill rx, schedule an appt, etc.). I'm not certain if the header levels are set per page where it's called, or once and for all. We'll need to think about that during this ticket.

**Comment by jilladams** [comment] 2024-02-21 19:40
From FE refinement:
* @chriskim2311 confirmed this is the same CTA widget code used on our other pages (e.g. Rx refill, secure messaging, etc.)
* The header level was set to default H3 when this convered to the `va-alert` DS component: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13860. To use H2 instead, you have to override and pass that in.

### Qs: 
* Does the heading level change when authed vs. unauthed? (After auth, the contents of the widget will change.)
* Header by default is an H3. This would apply to any place the CTA Widget is used and a different header level isn't passed in. List of all uses of this widget: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/ctaWidgets.js#L16 @laflannery  would like to verify this list of pages, to see if any others need H2. She'll do that within this ticket and add notes.

**Comment by laflannery** [comment] 2024-02-27 14:37
Un-auth heading levels:

- [ADD_REMOVE_DEPENDENTS](https://www.va.gov/view-change-dependents): H3 > Correct
- [CHANGE_ADDRESS](https://www.va.gov/change-address/): H3 > Correct
- [CLAIMS_AND_APPEALS](https://www.va.gov/claim-or-appeal-status/): H3 > INCORRECT
- [COMBINED_DEBT_PORTAL](https://www.va.gov/manage-va-debt/): H3 > Correct
- [DIRECT_DEPOSIT](https://www.va.gov/change-direct-deposit/): H3 > Correct
- [DISABILITY_RATINGS](https://www.va.gov/disability/view-disability-rating/): H3 > INCORRECT
- [EDUCATION_LETTERS](https://www.va.gov/education/download-letters/): No Heading > INCORRECT
- [ENROLLMENT_VERIFICATION](https://www.va.gov/education/verify-school-enrollment/): H3 > Correct
- [GI_BILL_BENEFITS](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/): H3 > INCORRECT
- [HEALTH_RECORDS](https://www.va.gov/health-care/get-medical-records/): H3 > Correct
- [HOME_LOAN_COE_STATUS](https://www.va.gov/housing-assistance/home-loans/check-coe-status/): H3 > INCORRECT
- [LAB_AND_TEST_RESULTS](https://www.va.gov/health-care/view-test-and-lab-results/): H2 > Correct
- [LETTERS](https://www.va.gov/records/download-va-letters/): H3 > Correct
- [MANAGE_VA_DEBT](https://www.va.gov/manage-va-debt/): H3 > Correct
- [MESSAGING](https://www.va.gov/health-care/secure-messaging/): H2 > Correct
- [RX](https://www.va.gov/health-care/refill-track-prescriptions/): H2 > Correct
- [SCHEDULE_APPOINTMENTS](https://www.va.gov/health-care/schedule-view-va-appointments/): H2 > Correct
- [UPDATE_HEALTH_BENEFITS_INFO](https://www.va.gov/health-care/update-health-information/): This widget is being rolled out in an incremental launch, I can't see it currently but CAIA said possibly next week it will be at 100%.
- [VETERAN_ID_CARD](https://www.va.gov/records/get-veteran-id-cards/vic/): H3 > Correct
- [VIEW_APPOINTMENTS](https://www.va.gov/health-care/schedule-view-va-appointments/): H2 > Correct
- [VIEW_DEPENDENTS](https://www.va.gov/view-change-dependents): H3 > Correct (Is this different from the Add dependents, the first item on this list? I couldn't find 2 different pages)
- [VIEW_PAYMENT_HISTORY](https://www.va.gov/va-payment-history/): H3 > INCORRECT
- VRRAP: I can't find this

I can't find Drupal Pages for the below. The only pages I can find that have the widget aren't in Drupal so I might have the wrong page or maybe these got moved away from PW, maybe?:
- [DISABILITY_BENEFITS](https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction): H2 > Correct
- [HEARING_AID_SUPPLIES](https://www.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction): H3 > INCORRECT
- [HIGHER_LEVEL_REVIEW](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start): There isn't a traditional widget on this page
- [VET_TEC](/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction): H3 > INCORRECT

**Comment by FranECross** [comment] 2024-03-06 19:19
- Per Jill we own the disability rating tool.
- Need to look at the list to see which we own and which we don't.

**Comment by FranECross** [comment] 2024-08-14 15:31
@laflannery Based on your last comment and research, is there work for the PW team (or a different team) to do on this ticket, or may it be closed? cc @strelichl @jilladams

**Comment by laflannery** [comment] 2024-08-15 20:08
@FranECross It would depend on if the headings are correct on all the widgets we own

**Comment by laflannery** [comment] 2024-11-25 15:54
Talked to Michelle, I'm going to make individual tickets for all the headings that need changing so they can easily be pulled into sprints

**Comment by laflannery** [comment] 2024-11-25 16:44
Closing in favor of the new, separate tickets:
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19956
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19957
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19958
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19959
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19960

**Closed** 2024-11-25 16:45 UTC
Labels: Public Websites, accessibility, sitewide, sitewide content, sitewide CAIA-product support, VA.gov frontend, Needs refining, sitewide CAIA, sitewide accessibility, ghp-admin
