### ISSUE TITLE
[SW-IA]  IA design for 1095-B form

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37639] opened 2022-02-24 21:31 UTC
Creating an online version of IRS form 1095-B that will allow authenticated users to view and download.  Will also have a feature to opt-out of receiving physical form in the mail. 

## Resources

- Epic: #37393
- Product manager: Jordan White and Ashley Castillo
- Designer: Kit Casey
- Supporting Artifacts
  - Link to product outline: [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/1095B-Tax-Form-Product-Outline.md)
  - Link to or attach user flows: [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/VA%201095-B_user%20flow-records-V2_2-4-22.jpg)
  - Link to prototype or mockups: [Here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/1095b-tax-form/design/wireframes)
  - Link to any epics/issues that may be helpful:

**Comment by tmulrooney-va** [comment] 2022-02-28 15:49
Hi!  I am the PO and am following up on next steps for this ticket.  Is there anything we can do to help move this forward?  Thank you

**Comment by mnorthuis** [comment] 2022-02-28 19:32
Hi @tmulrooney-va!  I apologize for the delay, I had a number of requests come in at the same time and am working to prioritize them.  I will be in touch very soon!

**Comment by mnorthuis** [comment] 2022-02-28 22:04
@JordanSWhite I have a couple of clarifying questions from when I last saw this work at the design intent meeting.

1) In looking at the new wireframes and flows, it looks like the unauth and auth views will be on the same page.  Is the intent to have static content managed in Drupal with a widget handling the dynamic download content? 
2) New flow shows placement within the Records hub.  In the design intent meeting, there were lots of questions about placement and entry point options - i.e.  Download VA letters, profile, Find VA forms search.   Is the Records hub the placement that your team is recommending based on some additional feedback, or is placement still a question?

**Comment by JordanSWhite** [comment] 2022-03-01 14:42
@mnorthuis 
1. Let me get back to you on that a little later today. I don't want to give you wrong info.
2. During our usability tests, users have consistently said they expected to find the form in Records, so that's our "soft" recommendation, but we're also open to other points.

**Comment by JordanSWhite** [comment] 2022-03-01 16:15
@mnorthuis Update: Yes, auth and unauth are the same page, and the widget changes depending on whether the user is signed in or not.

**Comment by mnorthuis** [comment] 2022-03-01 20:28
Thank you @JordanSWhite! 

I did a quick draft of the IA elements, [documented in this github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-1095-b.md) for you to review.   Once research and content is complete, we can revisit and then finalize the URL for the page.  So please reach back out once that is done. 

For the purposes of upcoming research, you'll want to update your prototype/mocks for these elements
- Breadcrumb 
- Records hub left nav ([this page can be used as an example](https://www.va.gov/records/download-va-letters/), highlight appropriate option)

For research, please let me know any additional feedback you get on where users expect to find this.  For now, there are only entry points within the Records hub.  A few notes about some of the other requested entry points:
- The [health care hub page](https://www.va.gov/health-care/) (all hub pages) have a maximum of 10 options shown in each spoke/section, and unfortunately health care is overflowing and this form will likelly not be considered more important than the other options listed. 
- The health care left nav should technically not have a link to this form if it does not live within the health care section of the site - the left nav is intended to represent the pages in the section.  
- The Records top nav flyout could accomodate 1 more link in the left column, which this would be a fit for, however, the top nav is intended to be high profile top tasks, and I'm not sure this fits that description.  This is something that would need to have OCTO-DE approval. 
- The Records square on the the home page ("Top tasks") is at it's limit of 5 top tasks items as well, and again, I don't believe this would outperform some of the other options.  If you disagree, this would also need OCTO-DE approval. 
- Search best bets - We could add a best bet to the VA.gov search.  There are currently already 2 pages listed as best bets, and preferably we would have a max of 2, so maybe one of those could be swapped out?
- You can work with the content side on any other crosslinking opportunities from within existing content pages or resources and support articles.

**Comment by kit-casey** [comment] 2022-03-01 21:32
Thank you @mnorthuis - chiming in here as well.

**Confirmed**: Our next round of user research will have it reflected in the breadcrumb and shown as a spoke on the left column of Records. We also have close to final content and only expect minor, if any, changes out of the next round of testing.

**Based on our first round of testing**, most participants expected it to be within **Records**, but explicitly see it as different than VA benefit letters (validating our hypothesis) so we are recommending that it **live as its own spoke**.

Also note:
- A few participants did look in health care first, at this time our recommendation is to crosslink via the [Affordable Care Act](https://www.va.gov/health-care/about-affordable-care-act/) landing page 
- A few participants went to search immediately (or secondarily), so it's great to know about suggesting a 'best bets' (especially since the current search term 1095-B links users to the legacy site with outdated content) **Is there a process we need to go through to submit this suggestion?**

As you mentioned, we also don't think the 1095-B would outrank the "top 5 tasks" on Homepage » Records square nor the Records top nav flight out.

**Comment by JordanSWhite** [comment] 2022-03-01 22:16
@mnorthuis As Kit said, we don't foresee this round of research changing anything regarding the location recommendation, so would we be able to get our URL Friday after Midpoint Review?

**Comment by mnorthuis** [comment] 2022-03-01 23:09
Do you have final content?  I utilize the H1 of the page as input in the URL.  The H1 in the mocks don't match our general approach or standards for this type of page.  Once that is finalized I can provide a URL.

**Comment by mnorthuis** [comment] 2022-03-02 14:59
Our approach for task-based features that live within the "Manage benefits" spoke of the hubs, is to use a action oriented H1.  You should work with the sitewide content  team (@DanielleThierryUSDSVA ) for more information on that.  This applies to the hub page link label, the left nav, the H1 and the URL.   So, for this page, the H1 may be something like "Download your 1095-B tax form".  Again, @DanielleThierryUSDSVA would provide final.   If you look at the other hubs and the rest of the Records hub, you'll see this pattern in play.

**Comment by kit-casey** [comment] 2022-03-02 21:12
Thanks, that's was my assumption (action-oriented), but wasn't sure if that was all, we've made that copy tweak in the H1, breadcrumb and left column. 

Question for @DanielleThierryUSDSVA - In our H1 we are using 'your' so it feels personal like we've seen elsewhere, but we did not use it in breadcrumb and left rail (it feels more streamlined for the nav). We saw instances on the site where this was done...e.g. https://www.va.gov/va-payment-history/ and we saw other where this was not https://www.va.gov/change-address/

Any guidance would be much appreciated.

**Comment by mnorthuis** [comment] 2022-03-02 23:17
I'll let @DanielleThierryUSDSVA answer the question about the use of "your" in the H1, however the breadcrumb and left nav should match the H1 of the page exactly.  That isn't strictly followed across the site, but that is how it should be.   The only place we may stray slightly from the H1, is the URL.

**Comment by DanielleThierryUSDSVA** [comment] 2022-03-03 22:13
Yes, we should keep "your" in here since this is about downloading your personal 1095-B. We should also add in "IRS" so that it's clear that this is not a VA form.

H1: Download your IRS 1095-B tax form

And a question: Mikki mentioned that this page may evolve at some point in the future to be more than just downloading the form...for example, it might include a way to opt out of getting the print form. Is that correct? If yes, we'll want to consider that in the H1/URL.

**Comment by kit-casey** [comment] 2022-03-04 14:49
Thanks for taking a look @DanielleThierryUSDSVA. Also just to be clear, this is a "document" as it's pre-filled out for Veterans and is proof of their health care (different than the usage of "forms" or "letters" as we understand it w/in the VA).

Re: Opt-in, this will be likely a profile-level feature and will not be part of the MVP launch. Ideally, it will be something designed and implemented before next tax season, but the roadmap is still being determined cc: @ashleycastillo @JordanSWhite

**Comment by DanielleThierryUSDSVA** [comment] 2022-03-04 18:55
Hi @kit-casey. Yes, I'm aware of the purpose of the 1095-B and that it's prefilled. That's why I recommended having "your" so it's clear it's your prefilled 1095-B. Did you have a question related to the word "form"? I didn't change that from the original. But are you wanting to change the H1 to "Download your IRS 1095-B tax document" instead?

**Comment by kit-casey** [comment] 2022-03-04 19:27
@DanielleThierryUSDSVA yes, please see the designs here under [Collab Cycle | Midpoint review](https://app.mural.co/invitation/mural/innovationboards1199/1644011260898?sender=ucbf569a3d5c571f73bec2539&key=5edcb01e-0b93-4e91-b5eb-453019bdff46). 

We'd also like to keep the word "IRS" out of the H1 since we do mention it in the first sentence on the landing page and have not found "IRS" to be a plain-language term users are looking for when search or when referring to the document. cc: @jamesldesign

**Comment by DanielleThierryUSDSVA** [comment] 2022-03-04 21:37
Hi @kit-casey. Okay, I see the H1 in the designs. I was referencing the ticket comments, which had "form."

@mnorthuis and I connected further on this. Here are our additional thoughts for follow-up:

- We don't have a personal preference for "form" vs. "document." But "form" is what's used on the form itself. And a review of SEO data shows multiple instances of "form" in keyword phrases around this topic and no instances of "document." This indicates that people are searching for "form." Attaching Semrush data for reference. Does your SEO data or usability research show the opposite?
- Our style for forms is to include the VA agency name in the H1 (ex. "[About VA Form 10-10EZ](https://www.va.gov/find-forms/about-form-10-10ez/)"). So it follows that we would use "IRS" in this H1 to make it clear that this isn't a VA form. Clarity is part of plain language. We do also see instances of "irs form 1095-b" coming up in SEO data. Have you specifically found negative reactions to or confusion around "IRS" in the H1?
- Either way, given the H1 is a critical piece to SEO and drives navigation/link labels, we want to make sure we include the right keywords, even if we repeat those keywords in the intro. The H1 also drives the make-up of the URL segment, so if we are not using certain words in the H1, those words would also be excluded from link labels and the URL.

**Comment by kit-casey** [comment] 2022-03-07 18:26
Thanks, @DanielleThierryUSDSVA and @mnorthuis for the context. 

Give your context and additional proofing, our recommendation is to proceed with  “**Download your 1095-B tax form**” for the H1.

This might be a time where we’ve gotten caught up in an instance of a VA pattern that should _not_ be followed (when in consideration of SEO, the document itself still uses “form” when filled in, and in consideration of comparative experiences). 

Looking back at our research of health insurance companies:

- United Health: “IRS tax forms”
- Medicare “IRS Form 1095-B”
- Cigna: “1095-B Tax Forms”
- PreferredOne: “IRS Form 1095-B”
- Blue Cross Blue Shield of Illinois: “Tax Form 1095-B”


We are not seeing any examples where both words (IRS & tax) are used—and when using the same tool you mentioned mentions [SEMRUSH](https://www.semrush.com/)
“1095b” = 1,125 variations
“1095b tax” = 83 variations (“form” in 34 of those instances, no “document”)
“1095b IRS” 53 variations (“form” in 26 of those instances, no “document”)

Given the above, and knowing that we will also utilize IRS in the copy (1st line as well), we do feel that the page will be findable & indexable with keywords used throughout.  

Let us know if you are good to move forward with  “**Download your 1095-B tax form**” for the H1 and we'll communicate the form vs document verbiage with the Midpoint team for visibility.

**Comment by mnorthuis** [comment] 2022-03-07 23:50
Final IA is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-1095-b.md

If there is additional research that results in feedback that impacts any IA components, please let me know, and I will revisit the documented decisions.   Otherwise, this IA should be final.  Please feel free to close this issue when you have the information you need.  Reach out with any questions!

**Comment by jamesldesign** [comment] 2022-03-11 17:21
@mnorthuis comment and question regarding the URL

I'm concerned about  the URL: [www.va.gov/records/download-your-irs-1095-b](http://www.va.gov/records/download-your-irs-1095-b)

If we are referencing the URL in a printed letter that goes out with the paper copy of the 1095-B form, would it make sense to shorten it so as to produce fewer errors?

Perhaps something like /irs-1095 or /download-irs-1095b

When looking at examples below, it looks like they shorten the URLs from the H1 tags for simplicity and clarity. In your experience is that a valuable solution? Perhaps my concerns are overblown, but I would appreciate your feedback so I can better understand the process

H1: View your VA payment history
URL: https://www.va.gov/va-payment-history/

H1: Get your VA medical records online
URL: https://www.va.gov/health-care/get-medical-records/

H1: VA decision reviews and appeals
URL: https://www.va.gov/decision-reviews/

**Comment by mnorthuis** [comment] 2022-03-11 18:54
Hi @jamesldesign!  The actual (canonical) URL represents the placement within the IA of VA.gov, changing it or shortening it actually changes the location of the page in the site, so that cannot be done.

**Comment by mnorthuis** [comment] 2022-03-11 19:02
To elaborate a bit more...The URL also impacts search results, so we need to maintain appropriate keywords. We have already shortened the URL compared to the actual page H1, and maintained the critical keywords.  

Based on our standards, this is how all elements play out:
H1: Download your IRS 1095-B tax form
Breadcrumb: Download your IRS 1095-B tax form (must match H1)
Title tag: Download your IRS 1095-B tax form | [VA.gov](http://va.gov/) (pulls H1)
Left nav: Download your IRS 1095-B (matches shortened version used in URL)
URL: /records/download-your-irs-1095-b
Why the URL is structured the way it is...
- The word "download" is kept to clearly articulate the purpose of the page - it is to download something
- The word "your" is kept to reinforce that it is a form specific to the user, not generic - we don't always keep this word, sometimes it is dropped if the fact that it is personalized is not as important  (i.e. we wouldn't have /your-profile, it is understood that the profile is yours) - in this case, we heard that the fact that it is personalized is important.
- On pages for VA forms, we do not repeat "va" because it is already part of the URL (in the domain) and does not need to be repeated.  For this form, we keep "irs" because it clarifies that the content referenced is not VA content.
- The form number "1095-b" stays because it is the most critical keyword
- The words "tax" and "form" are less critical to the URL, and are dropped to keep character count down. The H1 carries the weight for Veteran clarity, accessibility, and for SEO, so these words are not as critical for the URL.

**Comment by jamesldesign** [comment] 2022-03-11 21:50
Thank you for the explanation - much appreciated

**Closed** 2022-03-11 21:51 UTC
Labels: sitewide content, sitewide content-product support, sw-content-ia, sw-content-compose, sw-content-editing, Sitewide IA
