### ISSUE TITLE
Update breadcrumbs component documentation on design.va.gov

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#35805] opened 2022-01-24 16:14 UTC
## Issue Description
Our documentation on design.va.gov for Breadcrumbs component needs to be updated to point to the new `va-breadcrumbs` web component Storybook story and remove the mobile story.

---
## Tasks
- [ ] Update desktop story to point to `va-breadcrumbs` story
- [ ] Remove mobile story

## Acceptance Criteria
- [ ] Update Breadcrumbs component documentation on design.va.gov to point to va-breadcrumbs story and remove mobile story
---

**Comment by k80bowman** [comment] 2022-01-25 17:57
Closed as duplicate of #35806

**Closed by k80bowman** 2022-01-25 17:57 UTC
Labels: vsp-design-system-team
