### ISSUE TITLE
Product Guide Build for Learning Center MVP 1.0

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14785] opened 2020-10-13 21:44 UTC
# Product Guide Build for LC MVP 1.0

## Description
As a Veteran or beneficiary, I need to search for LC articles so I can find answers to questions I have about the site or about VA services or benefits. As a non-beneficiary who works with Veterans (like VSOs, fiduciaries), I want to find answers to questions I have about what I need to do in order to do my job (e.g., how to apply to become a fiduciary)

### Launch Date
- Beta launch LC 1.0 - DRUPAL DEMO SITE - DATE: Oct 23 -28
- Beta launch LC 1.0 - PROD VA.GOV - DATE: Oct 29 - Nov. 5

### Product Guide
TBD - Building .md document now in LC repository. 

## Tasks
- [x] Update existing guide
- [x] Share with Contact Center liaison team

## Acceptance Criteria
- Updated product guide for Learning Center MVP 1.0 beta launch.

**Comment by jenniferlee-dsva** [comment] 2020-10-19 18:20
I think this is a duplicate of [Ticket 14966]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/14966). That has been completed so we can close this one, too.

**Closed by jenniferlee-dsva** 2020-10-19 18:20 UTC
Labels: planned-work, vsa, vsa-public-websites
