### ISSUE TITLE
[eFSR] Collab cycle staging review Single-click destructive action. (00.00.1) Post Launch

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#60303] opened 2023-06-14 17:06 UTC
During our 6/9 Staging Review, this issue was brought up and noted here: department-of-veterans-affairs/va.gov-team#60037 

In the parts of the workflow where cards of items are added there is a delete button, which is a single-click destructive action. When clicking delete, the item is removed without any user confirmation. Additionally, there's nothing announced by screen readers to indicate that a change has occurred --- focus just moves to the next focusable element.

It's easy to imagine some scenarios where a user might accidentally trigger the delete button and not realize that they did it. Screen reader users may hit the wrong key but think they hit [Tab]. A low-vision user on a touch device might pinch-to-zoom and accidentally tap the delete button in the process, and not see the issue disappear.

Since users get an opportunity to review everything prior to submission, this is probably not a violation of experience standard 03.09 or WCAG 3.3.4. But I do think it's in the spirit of WCAG 3.3.4.

Another team used a modal, but that was not the best solution. This can be investigated in the post launch refinement window.

**Comment by HeatherRienks** [comment] 2023-06-21 17:44
Let's utilize Robin Garrison's fix for this effort. See ticket below:
 https://github.com/department-of-veterans-affairs/va.gov-team/issues/56082

**Comment by HeatherRienks** [comment] 2023-07-26 17:44
We will plan to address post SW MVP launch.

**Comment by HeatherRienks** [comment] 2023-09-20 17:22
Per FE, this is a dupe of #64425. Closing.

**Comment by HeatherRienks** [comment] 2023-09-20 19:12
#60303 is actually a duplicate ticket. Work is being addressed in #64425. Closing!

**Comment by HeatherRienks** [comment] 2023-09-20 19:12
#60303 is actually a duplicate ticket. Work is being addressed in #64425. Closing!

**Comment by HeatherRienks** [comment] 2023-09-20 19:12
#60303 is actually a duplicate ticket. Work is being addressed in #64425. Closing!

**Comment by HeatherRienks** [comment] 2023-09-20 19:14
#60303 is actually a duplicate ticket. Work is being addressed in #64425. Closing!

**Comment by HeatherRienks** [comment] 2023-09-20 19:15
#60303 is actually a duplicate ticket. Work is being addressed in #64425. Closing!

**Comment by HeatherRienks** [comment] 2023-09-20 19:17
test

**Closed by HeatherRienks** 2023-09-20 19:17 UTC
Labels: frontend, vsa-debt, Design -> Frontend, FSR Enhancements
