### ISSUE TITLE
[Build] 'Need more help' 1.0 / Chatbot for LC 1.1 FE Only

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14348] opened 2020-10-02 17:56 UTC
## Description 
_Build out 'Need more help' 1.0 / Chatbot for LC 1.1_

## Tasks
- [ ] Build 'Need more help' link for LC ~1.1~ 1.0
- [ ] Build 'Need more help' Chatbot for LC 1.1

## Planning Considerations
- Not sure when this will be available (Need to validate timeline)
- **The Chatbot is a FE only work** - the rest of the Need more help content is CMS + FE.

**Comment by jenniferlee-dsva** [comment] 2020-10-14 13:14
The AC above is not quite right. 

It is the chatbot link we don't need for 1.0. (And possibly not 1.1, depending on the team that's working on the chatbot itself.) 

We do however need the 'Need more help`  component on the FE. The CMS backend is built. We just need the FE to pull it on to the page.

**Comment by jenniferlee-dsva** [comment] 2020-10-22 14:08
This appears to be a duplicate of [#14329](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14329)

**Comment by kelsonic** [comment] 2020-10-22 15:40
Agreed, I think this is a duplicate and can be closed

**Closed by kelsonic** 2020-10-22 15:40 UTC
Labels: frontend, vsa, vsa-public-websites

**Comment by brianalloyd** [comment] 2020-10-23 16:10
Thanks @kelsonic this was a duplicate, thanks for closing.  We'll need to discuss future of Chatbot need in future planning to ensure we capture that requirement in a future ticket (if required for 1.1).
