### ISSUE TITLE
[UX draft] Add key "jobs" to Datadog dash (for Cartographer use)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88056] opened 2024-07-10 18:31 UTC
### User story

As a Cartography team member, I want
As a Veteran, I want

### Notes
- 

Possible tasks:
- 

## Acceptance criteria

- 
- QA review
- A11y review

**Comment by sterkenburgsara** [comment] 2024-07-31 15:56
This is a dupe of #89217, closing.

**Closed by sterkenburgsara** 2024-07-31 15:56 UTC
Labels: my-health, needs-refinement, Cartographers
