### ISSUE TITLE
External Integrations page - Confusion with VA Profile listed twice?

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/va.gov-team#72206] opened 2023-12-19 15:17 UTC
### Description
My team member sent [this Slack message](https://dsva.slack.com/archives/C05A2F6DEAE/p1702998025119299), since they were confused on why VA Profile is listed twice:
> I'm looking at this [va platform doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations) that details external integrations and I noticed that VA Profile is listed twice.  Once as "formerly known as Vets360" and another as just VA Profile.  I'm not sure how to make sense of that.  There aren't 2 VA Profile systems, so is one a deprecated version of it?

I'm assuming this is because: 
>this is calling out that formerly, only Vets360 provided contact information. Now VA Profile provides contact information in addition to health benefits + military personnel data

Is this the right interpretation of this page? Could you please update the content, so it's clearer? Thank you!

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations

### Which type of team are you on? (Platform team, VFS team, or Leadership)
OCTO leadership

**Comment by johnny-jesensky-adhoc** [comment] 2023-12-19 15:54
Hi @beckyphung, thanks for flagging this. It looks like one of the Platform Engineers added a row to that table last month, so we'll connect with them, and get back to you with more information on this. Additionally, we will work to update this page to make it a bit clearer.

We'll provide further updates in this ticket. Thanks!

**Comment by johnny-jesensky-adhoc** [comment] 2024-01-02 14:29
Hi @beckyphung - following up on this, I was able to connect with the engineer, and was advised to indeed combine the two rows together. 

We will be making some edits to this page, and will respond with a comment once they are live. Let me know if you have any questions!

**Comment by beckyphung** [comment] 2024-01-02 14:57
Thank you for the update @johnny-jesensky-adhoc !

**Comment by taylojill** [comment] 2024-01-03 19:10
Hi @beckyphung I combined the two rows into one and included all content. Page will be published 1/3/24 by 5pm EST.

cc @LindseySaari 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/4c3e6925-0eab-4dd5-b072-e24d3d7a835e)

**Comment by johnny-jesensky-adhoc** [comment] 2024-01-03 20:52
Confirmed the edits are live - moving this to _Done_. Thanks all!

FYI @taylojill, @beckyphung

**Closed by johnny-jesensky-adhoc** 2024-01-03 20:52 UTC
Labels: platform-content-team, documentation-support, pw-footer-feedback
