### ISSUE TITLE
 [Epic] MyVA copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18989] opened 2021-01-25 23:50 UTC
## Background
This is a ticket to track copy for MyVA 2.0 

## Tasks
- [ ] Matt creates tickets for each case below
- [ ] Tressa/Cassandra add info to tickets
- [ ] Peggy reviews each ticket

LOA1 user

LOA3 First-time user experience

LOA3 user who has everything

LOA3 user who has things but has no updates

**Comment by Samara-Strauss** [comment] 2021-01-26 15:44
This appears to be a duplicate of #18991. Closing, but feel free to reopen if there is a meaningful difference I'm unaware of.

**Closed by Samara-Strauss** 2021-01-26 15:44 UTC
Labels: content, design, my-va-dashboard, vsa-authenticated-exp, vsp-product-support

**Comment by mshea0606** [comment] 2021-01-26 15:51
Nope, forgot to delete this one. Thanks!
