### ISSUE TITLE
[DISCOVERY FE] Modify *authenticated* 10-10ez to be uneditable

### ISSUE THREAD

**Issue by charCodelet** [department-of-veterans-affairs/va.gov-team#32137] opened 2021-10-28 15:17 UTC
## Background

**If the user is authenticated,** we pre-populate some of the 10-10ez fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

We'd like to make these fields uneditable to avoid inappropriate modifications to MPI so that data remains accurate.

## User Story

As an engineer, I need to understand what work will be required and the loe to make the 10-10ez pre-populated forms uneditable.

## Expected Behavior

The purpose of this story is to ensure that veterans are unable to edit fields based on the values per the MPI. At present, despite their pre-population, these fields are editable. They should not be.

Design Ticket: #31989

## Acceptance Criteria

For the *authenticated/logged-in experience*:

- [ ] Documented discovery notes:

## Resources
- [Design PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/7539409/Personal.info-locked.11.3.pdf)

- **_NOTE LINK:_** Find a VA location tool link: https://www.va.gov/find-locations 

- Flow for authenticated & unauthenticated experience (click to make bigger)

![flow.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/7705d24a-079c-4248-9dd3-a3309544f125)

**Comment by MickinSahni** [comment] 2021-11-03 02:52
@charCodelet this seems like a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/30670. Was there something else we need capture as part of the SIGI work?

**Comment by charCodelet** [comment] 2021-11-03 03:54
Hey Mickin...re your comment about the duplicate...that was just a placeholder that I made with Dene...the actual epic task has been updated. Sorry about the confusion!

**Comment by Dene-human** [comment] 2021-11-03 18:39
[Design PDF](https://app.zenhub.com/files/133843125/f044ebb4-465f-4438-81bd-3718c67bb823/download)

Find a VA location tool link: https://www.va.gov/find-locations

**Comment by Dene-human** [comment] 2021-12-01 19:20
@jchilders @mdewey  I have updated the flows to reflect what we talked about. As you dive deeper into it, please let me know if these flows cause any major development heavy lifting and we can talk through options together.

**Comment by MickinSahni** [comment] 2021-12-13 16:12
Have structure in place to do if/else. But, unclear on a) where to get the data and b) getting the existing page to work via the schema-less route.

**Comment by MickinSahni** [comment] 2021-12-13 20:36
@jchilders to drop discovery notes here

**Comment by jchilders** [comment] 2021-12-14 17:22
### Discovery

more complicated than anticipated.

The recommended path forward was to provide [bypass the SchemaForm](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform/) and provide a custom React component via the `CustomPage` and `CustomPageReview` attributes for the Vet Info page in `config/form.js` for HCA. A branch -- 32137_cg_read_only_name_dob_auth_users` -- that implements this in a "hello, world" fashion. 

The outstanding question is how to use both a custom React component ("bypass the SchemaForm") and reuse the existing code at the same time? For example: in the branch given above there is a `VeteranNameDobPage` component provided. When a logged in user goes to the info page, this page is rendered. See `veteranInformation.pages.veteranInformation` page definition in `form.js`. On master, however, this points to the usual `uiSchema`/`schema` that pages typically do. Somehow that React component needs to include the `veteranInformation.uiSchema` in it.

One possible solution to the above would be to update `HealthCareApp.jsx`. Currently it provides custom logic around various feature toggles (e.g.: `hcaAmericanIndianEnabled `). Using the `setFormData()` function here should allow for the customized behavior needed.

**Closed** 2021-12-15 00:03 UTC
Labels: frontend, vsa-caregiver, planned-work, vsa-hca, Sprint 62
