### ISSUE TITLE
[Bug] MhvSecondaryNav can render before features have loaded

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#98927] opened 2024-12-11 20:40 UTC
## Description

This issue was discovered when [Katlin F. reported](https://dsva.slack.com/archives/C0581MN69TJ/p1733939701689249) that sometimes clicking "Records" in the MhvSecondaryNav would take her to `/health-care/get-medical-records/`.

## Acceptance Criteria

- MhvSecondaryNav changes the "Records" link based on feature toggle settings

## QA Steps/Instructions

Verify the following feature toggle settings

feature toggle | Records href
--- | ---
mhvTransitionalMedicalRecordsLandingPage | /my-health/records
mhvIntegrationMedicalRecordsToPhase1 | /my-health/medical-records
both | /my-health/medical-records
neither | /my-health/medical-records

**Comment by allanto-ah** [comment] 2024-12-18 20:30
Environment: Staging

No regression issues and haven't been able to reproduce the bug since the fix was merged

**Closed by allanto-ah** 2024-12-18 20:30 UTC
Labels: my-health, Cartographers
