### ISSUE TITLE
Look up Veteran ICN number

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#8869] opened 2020-05-07 12:04 UTC
Given that only verified veterans can submit the 10-10CG
I want to take the information provided by the Veteran on the form
And use it to lookup an ICN number.

**Comment by kevinmirc** [comment] 2020-05-08 19:50
Duplicate of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8870

**Comment by kevinmirc** [comment] 2020-05-08 19:53
Closed in favor of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5894

**Comment by kevinmirc** [comment] 2020-05-08 19:54
Closed in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/5894

**Closed by kevinmirc** 2020-05-08 19:54 UTC
Labels: backend, vsa-caregiver
