### ISSUE TITLE
Create a SuperUser for Argo

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#41720] opened 2022-05-20 16:28 UTC
### Why are we doing this

An access token is used to make API calls to Argo in order to view deployments in Platform Console API.   Dex, an OIDC provider, allows users to login to Argo via Github. Github access tokens cannot be used to make API calls since Dex becomes the Issuer in Argo. 

### Tasks

- [x] Attempted to use a Github token to make calls to Argo. **This was unsuccessful** :(
- [ ] Notify Infrastructure to create a SuperUser account in Argo, with apikey permissions, if there is not one already.

**Comment by npeterson54** [comment] 2022-06-29 19:15
Duplicate of #41656

**Closed by npeterson54** 2022-06-29 19:15 UTC
Labels: console-services
