### ISSUE TITLE
DISCOVERY: What happened with the degraded pods?

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61927] opened 2023-07-13 15:53 UTC
### ACCEPTANCE CRITERIA

**Comment by LindseySaari** [comment] 2023-07-14 16:15
## Degraded Pods Incident Analysis

During an off-cycle deployment around 9 PM ET, some pods were observed in a degraded state. A few potential reasons and debugging steps for such occurrences are as follows:

**Limited Node Availability or Disk Space:** A lack of available nodes or disk space could lead to scheduling issues. If a node exhausts its storage capacity, new pods cannot be scheduled onto it. Terms like "Pending" are indicative of scheduling challenges related to resource scarcity, while "CrashLoopBackOff" points towards application-related or configuration-related issues inside the pod.

**Resource Constraints:** If the container is unable to secure the required resources (such as CPU or memory) for running, it might be terminated by the Kubernetes node. This situation might have occurred during the surge when multiple sync operations were in progress during off hours. With the node count being potentially low at this time, waiting for node scaling could help alleviate the problem.

In our case, the issue was resolved by deleting the degraded pod, which subsequently spun up successfully on another node. This resolution suggests:

The original node might have lacked sufficient resources (CPU, memory) to run the pod, while the new node did not face such constraints.

There could have been internal issues with the original node, such as network connectivity or disk pressure, which affected the pod.

A transient issue in the cluster might have led to pod degradation, but it was resolved by the time the pod was rescheduled.

#### During debugging, it was found that:

A pod could enter the "CrashLoopBackOff" state if it consistently surpasses its resource limits, leading to process termination and subsequent pod restart. If this event recurs, the pod could remain in the "CrashLoopBackOff" state.

At the time of the incident, several pods were observed in the "CrashLoopBackOff" state, signaling an issue. Examination of logs revealed numerous 503 errors, indicative of unavailability of service. This issue could potentially be linked to Sentry, our error logging service, being unavailable.

It's crucial to note that the pods were not terminated due to out-of-memory (OOM) issues, ruling out memory exhaustion as the cause.

#### Future Actions:

For future incidents of a similar nature, debugging can be categorized into two areas:
Pending Pods: These relate to scheduling issues due to insufficient resources. In such cases, verify if a node scaling event is occurring to accommodate the required resources. ArgoCD logs might show messages like "0/12 nodes are available: 12 Insufficient cpu.".

CrashLoopBackOff Pods: These point towards issues with the application or configuration inside the pod. In such scenarios, the logs for the affected pod should be reviewed.

Remember, if a pod exceeds its memory limits, it may be terminated due to OOM, and if it exceeds its CPU threshold, CPU throttling may occur.

**Closed** 2023-07-17 16:01 UTC
Labels: platform-tech-team-1
