### ISSUE TITLE
Analytics QA Support for Rated Disabilities

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#3527] opened 2019-11-18 15:08 UTC
# Analytics Implementation or QA Request

## What this form is for
As an eBen Product Team member, I want to understand how many users are reaching the Rated Disabilities page and what content and actions they are seeing before and after reaching this page. I also want to see the impact of errors on the user's behavior. 

This is a follow-up of Analytics-Insights QA to issues #2072 and #2859 for Rated Disabilities. Requirements have been provided within these two issues, and we are in final QA. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?
eBenefits
    
- Provide the Domain where Google Analytics needs to be implemented: https://staging.va.gov/disability/check-disability-rating/rating/ using test user +1
- New Tags and Triggers for QA with Events:
   - Rated Disabilities Viewed Tag [Event Schema - ec: Transactions, ea: Rated Disabilities - Viewed Status, el: disability-ratings-viewed] - Should trigger on page load
   - Form Events Tag should load with either a successful load or failed load on any of these triggers: `disability-ratings-list-load-success`, `disability-ratings-combined-load-success`, `disability-ratings-list-load-failed`, `disability-ratings-combined-load-failed`; an error key passed as a custom dimension should pass as failures

> Please leave the following blank

## Acceptance Criteria
- [x] Analytics goal incremented in Non-Production for Goal 5
- [x] Update custom dimension table in GTM to reflect new IA `/disability/view-disability-rating/rating`
- [x] All Tags firing as expected in above list
- [x] Goal and custom dimensions applied to Production
- [x] Container published to Production
- [x] Annotate launch in Google Analytics

## Definition of Done
- [x] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment] 2019-11-18 15:51
@micahchiang I opened this issue to do our final QA on Staging. I logged in with the test user from Row 3 and reached this:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/522119ba-a88b-4cd0-a950-bfcb08d69eff)

I expected to see both a dataLayer event for the `success` of the load of the ratings and also a `failed` event for the error message. Within Staging, I didn't see either fire to the console. I will QA again with @jonwehausen but wanted to see if anything had been updated.

**Comment by micahchiang** [comment] 2019-11-18 17:15
@nedierecel - thanks for the heads up. I'll investigate as well to see if I can find anything.

**Comment by micahchiang** [comment] 2019-11-18 17:31
@nedierecel - I did a test with another user (vets.gov.user+23@gmail.com, row 25) and was able to see both dataLayer events fire. Can you try with that user? I forgot that local testing responds with data different than what's on staging, so the first user I suggested doesn't have any rated disability data associated with them at all.

**Comment by nedierecel** [comment] 2019-11-18 18:07
@micahchiang Thanks! I'll check with this user and will send some feedback once I look at user 23.

**Comment by nedierecel** [comment] 2019-11-19 16:43
@micahchiang Providing a status update that I saw user23's ratings. I'd like to perform a second check and will close this out.

**Comment by jonwehausen** [comment] 2019-11-20 14:43
@micahchiang Also receiving a 404 for a couple different users.

**Comment by micahchiang** [comment] 2019-11-20 16:20
@nedierecel, @jonwehausen - I _think_ rated disabilities on staging might currently be broken due to a recent PR we did. Standby and I'll let you know what that piece is resolved. In the meantime, a couple of other things I wanted to talk about with you:

1. Heads up, the URL is changing / could be changed already, to /disability/view-disability-rating/rating.

2. The 404s you bring up remind me of a thought I had a little while ago: Currently the only fail events sent to GA for rated disabilities are for 500 errors and 401s. I'm wondering if we want to amend the values for the `error-key` property to be more inclusive of other errors in those ranges. We could potentially pass the actual code value as part of the event.

**Comment by nedierecel** [comment] 2019-11-21 14:29
Thanks @micahchiang - we'll keep the blocked label on until Staging is resolved.

1. Appreciate the heads-up on IA change. That does impact one of our settings, so I will update the AC to reflect that.
2. I think that would be a great idea. Google Analytics and Google Tag Manager are set up to catch the events, so long as the pattern follows `disability` and ends with `failed`. The `error-key` can receive additional values as well.

**Comment by nedierecel** [comment] 2019-11-22 21:52
@micahchiang Happy early Thanksgiving week. Please ping us when the new link structure is up, and we can QA.

**Comment by micahchiang** [comment] 2019-11-22 22:05
@nedierecel - Hey! The new link structure is up, and you should be able to access the page via staging.va.gov/disability/view-disability-rating/rating. I don't believe my newest changes to the GA event structures have been deployed to staging yet (they were just merged into master this morning), so those might be up by next Monday.

**Comment by nedierecel** [comment] 2019-11-26 03:55
Thanks @micahchiang - I was able to see the new IA and see the success events. I pushed some changes to Staging to allow us to see the failed events+error key. I'll review this data to ensure I see the error keys as expected. 

I also tried to access the unauthenticated view, which was previously listed in #2072. I tried `/disability/check-disability-rating/` and `/disability/view-disability-rating` but hit 404s. I would like to use this page to build a funnel for reaching the goal. Please let me know if this has also changed.

**Comment by nedierecel** [comment] 2019-12-02 14:37
@micahchiang I see a new error key event, though I only see 1 error on Staging so far after I pushed the error key tracking to Staging.

https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w178298118p184081396/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension57&_r.drilldown=analytics.eventCategory:API%20Calls&explorer-segmentExplorer.segmentId=analytics.eventLabel

I believe the remaining item is to button up if the landing page has changed, so I can update the Goal funnel.

**Comment by micahchiang** [comment] 2019-12-02 17:11
Hey @nedierecel - Great to hear that the new error key events are working. As far as testing to try and get more than one error, it's unfortunately a matter of trying different test accounts and seeing which ones trigger different errors 😬. _However_, I think, for at least the total combined rating api call, it _might_ still be querying dummy data from vets-api. Let me confirm this and get back to you. If it is, then it will only ever return the one error. 

With regards to the unauthenticated view, as far as I know, that page isn't stood up yet. I believe the vsa-public-websites (formerly global-ux), is in charge of building that. Looping in @Karak888 in case she can provide some insight on that.

**Comment by micahchiang** [comment] 2019-12-02 19:21
@nedierecel - I just confirmed that the api call for total combined rating is still fetching dummy data. A PR was just merged that should update the call, so I think by tomorrow it should be working properly in staging.

**Comment by nedierecel** [comment] 2019-12-04 15:01
Thanks @micahchiang I'll check in non-production that things are looking okay. 

@Karak888 - Please also let me know when the unauthenticated content for Rated Disabilities is up on staging. I'll use this page to build the goal funnel for the tool.

**Comment by nedierecel** [comment] 2019-12-10 15:47
@Karak888 Hope you're well! Wanted to bump this request to see if the unauthenticated content URL has been finalized for Rated Disabilities. Thanks!

**Comment by nedierecel** [comment] 2019-12-17 16:17
@jenniferlee-dsva Do you have the new unauthenticated URL for Rated Disabilities? I will need this for building out the conversion funnel in Google Analytics. Thanks!

**Comment by mnorthuis** [comment] 2019-12-18 13:26
URLs for this work:  

Static page URL: www.va.gov/disability/view-disability-rating/
Report/dynamic page URL: www.va.gov/disability/view-disability-rating/rating

All IA is documented in #2584 for reference

**Comment by Karak888** [comment] 2019-12-18 14:45
sorry @nedierecel I must have missed your message.  Please let me know if you still need anything.  Thanks

**Comment by nedierecel** [comment] 2019-12-18 21:33
Thanks all for the updates and reference materials - @mnorthuis I am reaching a 404 for the static page. I've updated it within the Google Analytics backend, but I'll also check again when the static page is ready.

**Comment by nedierecel** [comment] 2019-12-30 15:55
@jason-gcio @micahchiang Do you know when the static page might be placed onto staging: 

`/disability/view-disability-rating/`

I am trying to reach it but hitting a 404. Is the launch plan to redirect it once it is live? I wanted to do a test to ensure it's getting captured in Google Analytics. Thanks!

**Comment by jason-gcio** [comment] 2019-12-30 16:45
@nedierecel That page is being created by Public Websites - I think they are wrapping it up so I will follow up with them next chance I get.

Yes, I believe that is the plan, but will also confirm that with Steve.  We definitely want to track that as well.

**Comment by nedierecel** [comment] 2019-12-30 17:58
Thanks @jason-gcio!

**Comment by nedierecel** [comment] 2020-01-21 17:46
Hello @jason-gcio @jenniferlee-dsva - Friendly reminder please: when the static page for `/disability/view-disability-rating/` is available on staging, can you please tag me for QA? This will be part of the form funnel for Rated Disabilities.

**Comment by jason-gcio** [comment] 2020-01-21 17:55
@nedierecel - you bet!

**Comment by nedierecel** [comment] 2020-02-04 20:03
@jason-gcio @micahchiang Confirming that the [new goal for "Viewing Rated Disabilities" is reporting in Google Analytics within the Production View.](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-overview/a50123418w177519031p184341898/_u.date00=20200201&_u.date01=20200203&_.goalOption=5/)

I also wanted to confirm the final behavior in production, which we discussed in an earlier thread in Staging. Can you confirm that it *is* okay for these events to both happen simultaneously: 

- disability-ratings-combined-load-success
- disability-ratings-list-load-success

cc: @jonwehausen

**Comment by jason-gcio** [comment] 2020-02-04 23:00
@nedierecel - yes, this behavior is confirmed as ok.  Thanks!

cc: @jonwehausen, @micahchiang, @cohnjesse

**Comment by jason-gcio** [comment] 2020-02-04 23:01
PS @nedierecel - My apologies, I meant to tag you earlier today when the basic auth came off for QA.  Do you have what you need?

**Comment by nedierecel** [comment] 2020-02-10 15:23
Thanks @jason-gcio - The Goal is now recording in the Disability and Claims Modernized View. For reference:

- [Goal Funnel - Tracks unauthenticated page to the veteran viewing their Rated Disability](https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184341898/_.goalOption=5/) 

**Follow-up:**
1. There is a small group of users entering the funnel directly at the Rated Disabilities page, which should be unlikely since the user would need to be authenticated (See screenshot, with pink box highlighting the entrances). 

I don't have a definitive answer, but one hypothesis is the Google Analytics session might be timing out and then the veteran is then hitting the page again before their authenticated session times out. This might be an oddity though since the VA.gov authenticated session and Google Analytics session both time out after 30 minutes of inactivity. 

Action Items:
   - The eBen and Analytics-Insights teams should continue to monitor to make sure it's a minimal amount.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/8d743e65-02b5-4645-9f7c-9bf2867e5269)

**Comment by jason-gcio** [comment] 2020-02-10 15:48
@nedierecel - Thanks, this is helpful!  It looks like the left nav is contributing some traffic as well.  Is it possible this is pulling from staging or some other test environment?  We will keep this page close by and monitor it.
cc: @steve-gov

**Comment by nedierecel** [comment] 2020-02-10 17:28
Hello @jason-gcio - I believe those are redirects from an unauthenticated page prompting a login to the authenticated page.

**Closed** 2020-02-10 19:57 UTC
Labels: analytics-insights, analytics-request
