### ISSUE TITLE
User Survey Request for Debt Resolution Team (Debt Management Portal)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23366] opened 2021-04-16 19:20 UTC
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
The debt management portal allows authenticated Veterans to view certain types of education and disability compensation + pension debts owed to VA. The portal provides a summary of each debt, including next steps, and a detailed view containing a history of the notification letters sent out. Additionally, there's a page that contains all the debt letters available for download. 

### Launch Date
The tool has launched as of January 2021

### Staging URLs
https://staging.va.gov/manage-va-debt/
You can sign in using user+1

### Production URLs
https://va.gov/manage-va-debt/

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment] 2021-04-20 22:25
Thanks for submitting this ticket, @rileyorr. Can you please confirm if you want the feedback survey _only_ on va.gov/manage-va-debt or if you want it on all of the details pages in that directory as well? Thanks.

**Comment by rileyorr** [comment] 2021-04-21 19:21
No problem! We'd like the feedback survey on all the details pages in the directory as well. These should be the corresponding URLS:

- va.gov/manage-va-debt/
- va.gov/manage-va-debt/your-debt/
- va.gov/manage-va-debt/your-debt/debt-detail
- va.gov/manage-va-debt/your-debt/debt-letters

**Comment by jwoodman5** [comment] 2021-04-21 20:27
Thank you! This request has been submitted and I will confirm when the survey is live.

**Comment by jwoodman5** [comment] 2021-05-27 15:04
Looks like I never confirmed the survey was live on these pages, but we have been since late April. Closing. Thanks.

**Closed by jwoodman5** 2021-05-27 15:04 UTC
Labels: VSP-contact-center, medallia
