### ISSUE TITLE
Design - Profile -  Direct Deposit - Document Front-end Design

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40195] opened 2022-04-20 00:08 UTC
Background

### Tasks

- [ ]  Document Front-End design
- [ ]  Add link to documentation to FE build ticket

### Acceptance Criteria

- [ ] Document Front-End design
- [ ] Add link to documentation to FE build ticket

**Comment by andaleliz** [comment] 2022-05-03 15:58
this is a duplicate of 40196

**Closed by andaleliz** 2022-05-03 15:58 UTC
Labels: vsa, vsa-authenticated-exp, profile, direct deposit
