### ISSUE TITLE
QA Standards - Veteran Facing Forms - 21P-0847

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#63060] opened 2023-08-03 14:39 UTC
#### VFS team name
Veteran Facing Forms

#### VFS product name
21P-0847

#### VFS feature name
21P-0847

#### Point of Contact/Reviewers
---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####

Traceability Reports not included
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####

Test coverage data was not provided but looking at the frontend support dashboard the product does not meet the 75% threshold.

---

### Bugs found
The following bugs were found by Governance team members during testing. They do not fall under the Experience Standards or the QA artifacts and are being reported here.

1. In Step 9 of 9 Review Application if user enters the name incorrectly they can't go back and correct the name and submit the form. This is launch-blocking:
![58945_Can't submit Statement of Truth if I first do it incorrectly_ 2023-08-01 at 4 58 36 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/ce268c4c-10bd-401b-9354-35f16ade3ce6)
2. The validation on the Date of Death date select on Step 6 of 9 shows a regex that is not helpful to users. (note: the validation on Date of Birth input on Step 7 does not exhibit the same issue):
<img width="505" alt="Screenshot 2023-08-03 at 9 30 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/2fd33a9e-b1b4-49e5-a18b-c0ec91c71765">

### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by erinrwhite** [comment] 2023-08-03 17:38
I was able to reproduce the first bug only when signed in and only when using my mouse to access the field - I was able to edit the contents of the field using my keyboard controls.

**Comment by tbaker1026** [comment] 2023-08-09 20:27
@erinrwhite @it-harrison - I tested this again logged in and not able to reproduce.  The only thing I was able to reproduce was by adding a space at the end of my name.  On the Review & Submit page it, the name does not show a space so I would not have known that there was a space - can you provide further details to re-produce this bug?  Thank you

**Comment by it-harrison** [comment] 2023-08-09 21:00
> @erinrwhite @it-harrison - I tested this again logged in and not able to reproduce. The only thing I was able to reproduce was by adding a space at the end of my name. On the Review & Submit page it, the name does not show a space so I would not have known that there was a space - can you provide further details to re-produce this bug? Thank you

@tbaker1026: To quote @erinrwhite :

> I was able to reproduce the first bug only when signed in and only when using my mouse to access the field - I was able to edit the contents of the field using my keyboard controls.
Beyond that, I'm not sure - I do know that this bug has come up before with at least one other team and that they too had trouble reproducing it.

**Comment by tbaker1026** [comment] 2023-08-09 21:24
@it-harrison I did use the steps provided by @erinrwhite - are you able to reproduce it again?

**Comment by tbaker1026** [comment] 2023-08-09 21:24
@it-harrison I did use the steps provided by @erinrwhite - are you able to reproduce it again?

**Comment by erinrwhite** [comment] 2023-08-10 12:57
I am no longer able to reproduce this myself using the same browser (Chrome) and same method as before. Also tried in Safari like in the screenshot and did not have an issue. @it-harrison @tbaker1026

**Comment by tbaker1026** [comment] 2023-08-10 20:13
@it-harrison - can you reproduce this again?

**Comment by it-harrison** [comment] 2023-08-10 20:59
@tbaker1026 I can't. I think it's either resolved or _very_ subtle.

**Comment by tbaker1026** [comment] 2023-08-10 21:22
Closing since it can't be reproduced

**Closed by tbaker1026** 2023-08-10 21:22 UTC
Labels: QA, collab-cycle-feedback, qa-standards, Staging, launch-blocking, forms-audit-digitize

**Comment by tbaker1026** [comment] 2023-08-14 19:21
@it-harrison - we are going to add some additional unit tests to the signature panel to see if we can reproduce it
