### ISSUE TITLE
[Bug] Online tool button missing on some forms detail pages in Staging

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18728] opened 2021-01-19 18:11 UTC
## What happened?
John Hashimoto added online tools URLs to some VA forms in the CMS last week, but the button for the tool does not appear in the form search results, although it *does* appear on the form detail pages.  We are unsure if this is a Lighthouse or CMS issue, so I am labeling as both.  Please work with @zacharymorel for details on how the code consumes the API, and please work with @johnhashva on any questions about how the data was entered in the CMS.

## Specs:
- Device: Any
- Browser: Any
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL:  https://staging.va.gov/find-forms/?q=21-674
- Test User _(if applicable)_: N/A

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
The button shown in the screen shot below should have appeared in the search result.   Example:  https://staging.va.gov/find-forms/?q=10-10ez

The button *does* appear on the same form's detail page as expected, so it would appear that the URL is being imported in some fashion when the data is merged.  

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/6fd18ad7-77ce-41e9-bf4d-e022ae31db2b)

## Acceptance Criteria
- [ ] Any form with an online tool URL in the CMS should display a "Go to Online Tool" button in the search result.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zacharymorel** [comment] 2021-01-21 19:27
So I have worked through the issue above on my end (FE).
I have determined that the GraphQL API returns the **fieldVaFormToolUrl** correctly when querying: **21-674**; however, there’s a possible discrepancy between the Lighthouse API and the Drupal Database.

On the front end visiting, https://staging.va.gov/find-forms/?q=21-674 , you’ll see **formToolUrl** property have a value of _null_ within the network response from the lighthouse API.

 If one goes to the cms graphql explorer: https://prod.cms.va.gov/graphql/explorer , and runs this query, 
```
{
  nodeQuery(limit: 1000, offset: 0, filter: {conditions: [{ field: "field_va_form_number", value: "21-674", operator: LIKE }]}) {
    entities {
      entityId
      entityBundle
      ... on NodeVaForm {
        fieldVaFormNumber
        fieldVaFormName
        fieldVaFormTitle
        fieldVaFormDeleted
        fieldVaFormToolUrl {
          uri
          title
          options
        }
      }
    }
  }
}   
```
Well see the from come back with the fieldVaFormToolUrl populated. 
I believe we have to move this to lighthouse now. Posting my notes here for them to use if needed during debugging.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-21 22:55
Something to note - this only seems to be happening on Staging.   The online tool button was behind a feature flag in Prod until today, but as soon as it went in, we could see the button there.   https://www.va.gov/find-forms/?q=21-674

Still missing on Staging.  https://staging.va.gov/find-forms/?q=21-674

**Comment by johnhashva** [comment] 2021-01-22 14:29
@MarciMcGuireGCIO and @zacharymorel in a perfect world, we would be able to see these in staging.  if you think this won't require a lot of cycles, can we keep this ticket open and try to figure this out when opportunity arises in next few sprints?

**Comment by MarciMcGuireGCIO** [comment] 2021-01-22 14:30
@johnhashva agree 100%. We need to be able to see in staging.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-22 14:52
Per this Slack thread, Lydia Vian has added to their backlog https://dsva.slack.com/archives/CUB5X5MGF/p1611272410002100?thread_ts=1611080137.007500&cid=CUB5X5MGF

**Comment by zacharymorel** [comment] 2021-01-22 21:54
I guess we move this to closed or Icebox since they use a different scrum board. We can't link the lighthouse user story to her as a blocker?

**Comment by MarciMcGuireGCIO** [comment] 2021-01-22 21:57
I messaged VSP earlier to find out if they can access our repo but don’t have that information yet.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-25 17:53
This will need to be reviewed by the team now supporting the Lighthouse API.  I've messaged on slack and will schedule a meeting.  Marking as blocked and removing milestone.

**Comment by mviterna** [comment] 2021-01-25 20:23
FYI, I'm the developer who has been assigned this issue on Lighthouse. I'm new to the team and to the Forms API, so you will need to bear with me. We had to push this out to our next sprint, which starts tomorrow, because we were still getting our dev environments up. I'll have a chance to look at it in more depth this week.

**Comment by MarciMcGuireGCIO** [comment] 2021-01-25 21:44
@mviterna thank you for the update.  Please let us know if you have any questions once you dig into this.

**Comment by swirtSJW** [comment] 2021-01-29 23:00
On the form detail page in the CMS
https://prod.cms.va.gov/find-forms/about-form-21-674
 the  page the tool is linking to seems to be broken
![image](https://user-images.githubusercontent.com/5752113/106335761-6f131680-625b-11eb-8df9-824f0b686d00.png)
https://www.ebenefits.va.gov/ebenefits/dependents


I believe lighthouse does some prescanning of links and will not return something with a broken link .  I know they do that with the pdf files.... not sure if they do it with links to online tool.


Either way the data is in the CMS and is being passed to lighthouse via their graphQL pulls.   What happens to it after that I am not sure.

**Comment by johnhashva** [comment] 2021-02-01 13:18
@MarciMcGuireGCIO + @jason-gcio + @swirtSJW Added a working and validated ebenefits online tool link -- https://www.ebenefits.va.gov/ebenefits/about/feature?feature=dependent-compensation -- per Jason.

**Comment by mviterna** [comment] 2021-02-01 13:56
@johnhashva How long does it typically take for these changes to propagate through the system? Steve was saying something about possibly a nightly pull that happens, but I'm not sure.

If the updated link does not fix it, we will have to look into whether or not we have possibly a data caching issue or something along those lines.

**Comment by johnhashva** [comment] 2021-02-01 14:46
@mviterna any updates I make to the Find a Form detail pages via CMS -- including adding links to Online Tools -- are deployed with a daily CMS content release M-F at 2pm EST.   We can also invoke a manual content release at any time.

**Comment by mviterna** [comment] 2021-02-01 15:01
@johnhashva  Thanks John. I see the URL is updated in the details page, but still not the search page, I'm going to reach out to a few people and see what I can find out.

**Comment by johnhashva** [comment] 2021-02-01 15:23
That's right @mviterna -- just put a note about this in Slack (and we are getting you added to our #va-forms channel today).   I've added the new ebenefits link to 21-674 and 21-686c and while the link is showing correctly on the Form Details page -- it is not showing up on the Forms Search page.

**Comment by mviterna** [comment] 2021-02-10 15:07
@johnhashva @MarciMcGuireGCIO  We've been digging into this issue and we added some logging around the job that kicks off at night. We are trying to see if there is an issue there and if we can capture some additional logging in CloudWatch. We'll keep you updated on our findings.

**Comment by mviterna** [comment] 2021-02-15 19:29
@zacharymorel  @swirtSJW  Does anyone know the history on the difference between these routes? /v0/forms?query=21-674 and /services/va_forms/v0/forms?query=21-674 ?

One pulls back                 "form_tool_url": "https://www.ebenefits.va.gov/ebenefits/about/feature?feature=dependent-compensation",
and the other it is null (same environment: staging)

**Comment by zacharymorel** [comment] 2021-02-16 15:13
@mviterna I do not. I did not even know the latter existed.

**Comment by mviterna** [comment] 2021-02-16 20:58
I think we have identified the root cause, but I'm going to talk with a couple of the devs tomorrow after scrum and come up with our final analysis.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-16 21:05
@mviterna thank you for the update.  Please let us know if we can help in validating.

**Comment by mviterna** [comment] 2021-02-17 18:15
@MarciMcGuireGCIO @johnhashva It looks like the Staging Forms page is pointing to Sandbox instead of Staging. Is there any reason why you would want the forms data coming from the Sandbox database instead of Staging? Having just taken over Forms API, I'm not sure if there is any reason that would be, other than an error. It seems maybe it was a config mistake that was checked in before and not caught until now. Can we set up a call with you two and maybe @swirtSJW or @zacharymorel

**Comment by zacharymorel** [comment] 2021-02-17 18:21
@mviterna  Sounds like a debugging piece left over accidentally.

**Comment by mviterna** [comment] 2021-02-17 18:26
@zacharymorel  Probably...it is specifically the https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2 line 160.  I think we need to update it to Staging. I don't need a call if you are sure you want me to update it. I just didn't want to point Staging to the wrong dataset. This setting only affects Staging, not Prod. Just let me know if you need/want a call for me to explain or if we are good to go ahead and set the flag. I confirmed it is working in my local testing for the form that had the missing button.

**Comment by zacharymorel** [comment] 2021-02-17 18:42
@mviterna yes, since dev and prod are isolated using different settings.yml files, I think we're gtg to update the staging-settings.local.yml configuration.

**Comment by mviterna** [comment] 2021-02-17 19:00
@zacharymorel Ok, I'll put the PR in. Since builds go out at 2PM ET, this won't go into the system until tomorrow or Monday before we see the change.

**Comment by zacharymorel** [comment] 2021-02-22 15:57
@mviterna https://staging.va.gov/find-forms/?q=21-674 _form to url_ on the result is still not populating today. 
Any word is vets api staging env deployed your commit?

**Comment by mviterna** [comment] 2021-02-22 22:31
@MarciMcGuireGCIO @zacharymorel @swirtSJW @johnhashva  Hey all, I apologies the length of time it took to get this resolved. Being new to the workflow, our team had several hurdles and processes to get over to get set up. Once we were, it took some time getting familiar with the code. I think I have it fixed. The problem was we were hitting a timeout on Sandbox (which is where staging points, for whatever reason) and not on prod. My guess is that we were right on the threshold and Sandbox is probably just a tad slower than prod, connection wise, that it put it over the edge. I bumped up the timeout a good 3x, so we shouldn't see it again, unless there is another problem with the job. Can someone please confirm that the button is now showing in staging for form 21-674?

**Comment by johnhashva** [comment] 2021-02-22 22:45
@mviterna I just validated 21-674 Online Tool link is now showing up in staging.va.gov.    @MarciMcGuireGCIO may as well take a look yourself in the AM so we can close.    Thanks for the fix @mviterna !

**Comment by MarciMcGuireGCIO** [comment] 2021-02-22 22:47
I just validated too. Thank you @mviterna and @zacharymorel!

**Comment by mviterna** [comment] 2021-02-22 22:57
Great. I'll close the Jira item if someone here wants to close GH

**Comment by MarciMcGuireGCIO** [comment] 2021-02-22 23:00
Closed!

**Closed** 2021-02-22 22:59 UTC
Labels: Lighthouse, blocked, bug, cms, dt-find-va-form, unplanned-work, vsa, vsa-decision-tools
