### ISSUE TITLE
QA Standards -Debt Resolution - Debt Portal

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#92505] opened 2024-09-10 02:00 UTC
#### VFS team name
Debt Resolution

#### VFS product name
Debt Portal

#### VFS feature name
Payment History (VBA) MVP

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
The [listing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92381) for regression test plan (1.) does not include an executed regression test plan; there is mention of manual testing but not a link to a set of manual tests that cover the product's functions and the result of executing those tests.
#### Test Plan
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
The [listing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92381) for test plan (2.) does not include an executed test plan; there is mention of manual testing but not a link to a set of manual tests that cover the product's functions (ie tests that map to user stories) and the result of executing those tests.
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
This artifact has not yet been generated
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 46.32

- Functions %: 59.09

- Statements %: 46.76

- Branches %:  14.07

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
I generated these numbers by running `yarn test:coverage-app combined-debt-portal/debt-letters` on `main`. The value of each category needs to be at least 80%. One thing to keep in mind is that these values are always evaluated for the whole app, not just files that were added or changed for a particular initiative, meaning that legacy deficiencies in code coverage can bring down the scores.
#### Endpoint Monitoring (Completed Playbook)
- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by Tom-Davis** [comment] 2024-09-18 17:49
We are addressing the 3 launch blocking issues here:

Supporting 92505 - [CDP] QA Standards - Regression test plan #[92530](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92530)
Supporting 92505 - [CDP] QA Standards - Test Plan #[92531](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92531)
Supporting 92505 - [CDP] QA Standards - Traceability Reports #[92533](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92533)

**Comment by OptionSelect** [comment] 2024-09-19 17:32
@denisecoveyduc Tom wanted us to ping ya here because we've gone to 25% and are looking for your confirmation that we're good. Still working on some of Ian's test comments in the other thread but reaching out!

**Comment by denisecoveyduc** [comment] 2024-09-19 20:02
@Tom-Davis Are the above ticket numbers correct? All 3 are closed but #92530 and #92533 appear to be placeholders?

**Comment by Dr-Pongo** [comment] 2024-09-19 21:44
Heyo @denisecoveyduc & @Tom-Davis! I added a little more detail to those tickets! We made the tickets right after staging review and they were addressed pretty quickly so we didn't cross all the t's and dot the i's, but hopefully they're solid now! 🚀

**Comment by denisecoveyduc** [comment] 2024-09-19 22:56
Thanks to everyone for addressing so quickly! Appreciate the follow up to circle back on the documentation. I wasn't sure if I was looking at the right tickets so that helps a ton.

**Comment by Tom-Davis** [comment] 2024-10-07 20:06
@denisecoveyduc if you are satisfied that the standards are not accounted for can this be closed per the instructions above?

**Comment by denisecoveyduc** [comment] 2024-10-08 14:54
Yes, given the three tickets below are completed and closed we can close this. 

- Supporting 92505 - [CDP] QA Standards - Regression test plan #[92530](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92530)
- Supporting 92505 - [CDP] QA Standards - Test Plan #[92531](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92531)
- Supporting 92505 - [CDP] QA Standards - Traceability Reports #[92533](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/92533)

**Closed by denisecoveyduc** 2024-10-08 14:54 UTC
Labels: QA, vsa-debt, collab-cycle-feedback, qa-standards, Staging, launch-blocking
