### ISSUE TITLE
Create a virtual hearing coordinators R&S page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#51747] opened 2023-01-11 15:55 UTC
## Veteran story
As a Veteran with a BVA hearing, I need quick access to my hearing coordinator for last-minute questions about the hearing.

## What's needed
We need to create an accessible R&S page with information from the [legacy TeamSite page on virtual hearing coordinators](https://www.bva.va.gov/hearing-coordinators.asp).

**Note:** We'll then need to onboard a member of the BVA team to serve as the main POC for managing updates to this page.

**Comment by DanielleThierryUSDSVA** [comment] 2023-01-11 15:57
Hi @RLHecht. This is another page for the BVA migration effort. Let's talk about whether this can fit into this sprint or next sprint. Thanks!

**Comment by katherine-fung** [comment] 2023-02-01 16:04
I reached out to SMEs with some questions about the hearing coordinators. They got back to me with the information, and say they will also have an updated list of coordinators today. Once I have that list, I'll continue building the page.

**Comment by katherine-fung** [comment] 2023-02-01 22:07
I have the updated list of coordinators. 

I'm working on the draft page: 
http://preview-prod.vfs.va.gov/preview?nodeId=53136 

Working from this source file: [https://app.zenhub.com/files/133843125/404ee80c-4c4d-4e9c-953b-e6871fef6000/download](https://app.zenhub.com/files/133843125/404ee80c-4c4d-4e9c-953b-e6871fef6000/download)

**Comment by katherine-fung** [comment] 2023-02-10 22:08
Awaiting more info from SME re: questions about whether to include the team leaders/supervisors, and multiple coordinators on the page

**Comment by katherine-fung** [comment] 2023-02-28 14:17
Laura and I moved forward with building this page based on SME's answers to our questions. @bethpottsVADEPO and I will review it today, but she's hoping to get more clear information in a call with SMEs tomorrow. 

Page preview: http://preview-prod.vfs.va.gov/preview?nodeId=53136

**Comment by katherine-fung** [comment] 2023-03-14 16:16
Update on this page: 

I've made styling changes throughout. I'll present this page to stakeholders tomorrow on Wed. 3/15. 

A few notes: 
- Stakeholders didn't want to offer a single email address/shared inbox for each office. Instead, we're using a mailto:link for the entire coordinator team for each office, as well as providing individual email addresses for each person on the team. 
- Sara Smith reviewed this approach for accessibility issues. Per her feedback, I styled this page using <p> for hard line breaks, instead of <br> which can create an issue with screenreaders.

**Comment by katherine-fung** [comment] 2023-03-15 22:56
Hi @bethpottsVADEPO, I've updated the email addresses linked on this page to point to shared inboxes for the regional teams: 

http://preview-prod.vfs.va.gov/preview?nodeId=53136

**Comment by bethpottsVADEPO** [comment] 2023-10-11 20:51
@katherine-fung When you can turn back to this, we need to reimagine the entire page (so sorry, I know it was a lot of work to get it to this point):

- Remove all the accordions
- Restructure the page to answer some basic questions or use cases for contacting hearing coordinators (these don't have to be in the form of questions for the H2s, i.e., Reasons you might want to contact a hearing coordinator)
- Link to the existing legacy page (the main CTA at the top) until we figure out whether we can get the coordinators onboarded to AVA.

Raeed's answers to my questions--for content you might consider working up for this page:
**What are some common questions Veterans reach out to hearing coordinators with? (doesn’t have to be a comprehensive list, but just some common examples)**
- I’m scheduled for a virtual hearing but I never received a link to join Before the hearing
- I want to convert my upcoming videoconference, Central Office, or Travel Board hearing to a virtual hearing
- My hearing is today but I cannot get into the virtual hearing room

**How quickly do hearing coordinators respond? (approximate is ok or a range, like 4-5 days)**
- Usually within 24 hours, but I would rather not set an expectation for a number of reasons

**Are there any questions you don’t want Veterans to ask when directly emailing a HC or information you don’t want them to share?**
- While hearing coordinators are Board employees, their role is limited to the scheduled and coordinating of hearings before Veterans Law Judges. For questions on anything other than Board hearings, please email BoardCustomerService@va.gov.

**Is there any cutoff at which point it’s too late to contact a hearing coordinator before the hearing and the Veteran should call instead? (not sure if this is even an option—just trying to think about all the scenarios)**
- Calling is not an option unless the coordinator has previously called them and gave them their number. I would not mention a cut-off.

**Is it just as often a VSO or other accredited rep who is contacting you? If so, we can work in that language (“you or your accredited representative”)**
- Yes, it can be either

**Comment by bethpottsVADEPO** [comment] 2023-10-12 13:15
@katherine-fung I have a thought about the above changes. Since this is a bit of a moving target with what we want to do with the page and what the hearing coordinators want, how about we keep this existing node in Drupal intact as is with all the accordions and create a new page for this scaled-back version. Then if we ever need to go back to the previous approach there's not lots of work. And we'll archive whichever node we don't end up going with.

**Comment by katherine-fung** [comment] 2023-12-11 23:42
Hi @bethpottsVADEPO, thanks for getting this info from Raeed. Here's a draft of the FAQs for your review: 

http://preview-prod.vfs.va.gov/preview?nodeId=53136

I kept the H1 the same as our other hearing coordinators draft. Let me know if you have any questions. Thanks!

**Comment by katherine-fung** [comment] 2023-12-20 15:25
Noting that Beth reviewed the draft, and sent it to the SME on 12/13/23 to review.

**Comment by katherine-fung** [comment] 2024-01-02 16:43
The SMEs responded on 12/29, and gave us their approval to publish this page. 

@chelsealevinson, could you copy edit this page, go through the pre-pub checklist, and let me know when it's live? http://preview-prod.vfs.va.gov/preview?nodeId=53136 

I forwarded you the email thread about the page. Let me know if you have any questions. Thanks! 

cc @bethpottsVADEPO for awareness

**Comment by bethpottsVADEPO** [comment] 2024-01-02 17:52
Finally going to get this up! Thanks for the quick creation of this page @katherine-fung and the quick copyedit @chelsealevinson. Very exciting.

**Comment by chelsealevinson** [comment] 2024-01-03 16:27
Confirming this page has been copy edited and published! 

A few questions: 

1. Should this page be added as a related link on any live articles @katherine-fung ? 

2. Should this page replace any of the links on the R&S hub page under Decision reviews and appeals? @bethpottsVADEPO and @DanielleThierryUSDSVA

**Comment by katherine-fung** [comment] 2024-01-15 14:17
Thanks so much @chelsealevinson! 

An update: there are 2 versions of this page. We originally wanted to publish the version you published, Chelsea. Now, stakeholders say that they're going to launch group inboxes for each of the hearing coordinator teams. That would allow us to update and publish the other version of this page (the one that lists contact info for all the teams - node 53136), and fully migrate this page over from the legacy site. 

For now, I'll confirm with Beth that we should hold off on linking to the published R&S page [node 64063](http://preview-prod.vfs.va.gov/preview?nodeId=64063), and we should wait for more updates on the group inboxes so we can update the other draft R&S page [node 53136]. 

@chelsealevinson I can explain this one more clearly in a meeting or over Slack!

**Comment by katherine-fung** [comment] 2024-01-26 14:55
Waiting for updates from SMEs about the contact info for hearing coordinators.

**Comment by katherine-fung** [comment] 2024-08-22 14:43
I've followed up with Raeed about the status of the group inboxes, and CC'ed you @strelichl, @aprocik1 and @bethpottsVADEPO.

**Comment by katherine-fung** [comment] 2024-09-19 15:55
Raeed let us know that his team is going to proceed with creating group inbox email addresses. When the email addresses are ready, he's going to send them to us to publish. 

I've walked @hermonica through this work. 

I've CC'ed @aprocik1 @strelichl @bethpottsVADEPO on the Outlook thread with Raeed.

**Comment by aprocik1** [comment] 2024-10-21 16:58
Update: We received the information we need to move this ticket forward. Beth and I spoke about striving to publish this page before the end of the year. Here's what I'll do next:

- Add the list of hearing coordinator email addresses to this VA.gov page: [Hearing coordinators for the Board of Veterans’ Appeals](https://preview-prod.vfs.va.gov/preview?nodeId=64063) (Drupal preview) 
- Redirect this TeamSite page to the new VA.gov page: [Hearing Coordinators List](https://www.bva.va.gov/hearing-coordinators.asp)
- Update all the crosslinks to the TeamSite page to direct to the VA.gov page

Note: We have this outstanding question for the business line:

> The list of hearing coordinator email addresses from Raeed has two regional offices for PA. Every other state has one regional office. How does someone who doesn't live in Pitt or Philly know if they should send their form to the Pitt regional office or the Philly regional office? Should we provide a list of PA counties or zip codes to clarify the regional offices' jurisdictions?

**Comment by aprocik1** [comment] 2024-10-24 16:59
Update: Salvador Ambriz approved this page for publish: [Hearing coordinators for the Board of Veterans’ Appeals](https://prod.cms.va.gov/resources/hearing-coordinators-for-the-board-of-veterans-appeals) (Drupal node)

@megzehn, can you copyedit and publish this page? Thanks!

**Comment by megzehn** [comment] 2024-10-28 22:02
@aprocik1 confirming that I reviewed and published this page. Thank you!!

**Comment by aprocik1** [comment] 2024-10-29 13:03
Thanks, Megan!

I sent the live page to SMEs and asked them to confirm that we're ready for this redirect:

- bva.va.gov/hearing-coordinators.asp
- va.gov/resources/hearing-coordinators-for-the-board-of-veterans-appeals/

After we implement this redirect, we'll need to update crosslinks on VA.gov. I'll keep this ticket open and updated on our progress.

**Comment by aprocik1** [comment] 2024-10-31 15:08
The business line implemented the redirect on their TeamSite, instead of Public Websites implementing it on VA.gov. The only remaining work left on this ticket is to identify and update crosslinks. This ticket should remain open and in progress for now.

**Comment by aprocik1** [comment] 2024-11-08 15:56
@d-beyer, this is the ticket we discussed earlier this week. Can you identify and update the crosslinks for this page?

- This is the legacy URL we need to remove links to on VA.gov: https://www.bva.va.gov/hearing-coordinators.asp
- This is the modern URL we need to update links to on VA.gov: https://www.va.gov/resources/hearing-coordinators-for-the-board-of-veterans-appeals/

Thanks for your support on this!

P.S. It's likely that we'll publish an update to the new page next week. You don't have to wait for us to do that before publishing updated crosslinks.

**Comment by aprocik1** [comment] 2024-11-14 18:45
@saratorres2, I updated this page to align with our new standards for the Philippines and Washington, DC. Can you publish this page next week with Triana? 

Here's the Drupal page: [Hearing coordinators for the Board of Veterans’ Appeals](https://prod.cms.va.gov/resources/hearing-coordinators-for-the-board-of-veterans-appeals)

Thanks in advance!

**Comment by aprocik1** [comment] 2024-11-21 19:55
Beth and I just spoke to Raeed Tayeh about this page. Theses are the remaining accuracy updates we discussed:

- A Veteran can't reschedule their appointment. They have to write a request to the judge and the judge has to accept the request.
- A hearing coordinate can't help a Veteran before their hearing is scheduled. On average, the Veteran waits for three to three and a half years before their hearing occurs.
  - We can say something like this: "After you're scheduled for a hearing and you need assistance, contact a hearing coordinator."
- Consider removing the "keep reading" sentence in the intro
- Update the accredited representative content in the intro to match other patterns on the site
  - "...you or your accredited representative can..."
- The second bullet point: Replace the parenthesis with "an in person hearing at a VA facility"
-  Under the bullet points, crosslink to this page: [Requesting a virtual hearing for a Board Appeal](https://www.va.gov/resources/requesting-a-virtual-hearing-for-a-board-appeal/)
- We need to change the note: Hearing coordinators can't help a Veteran schedule their hearing. Hearings are scheduled in a specific order.
  - Make this update: "Hearing coordinators can only help you access and make changes to your scheduled Board of Veterans Appeals hearing..."
  - Add this sentence: "If you have a question about a pre-determination hearing on a claim you filed at your local VA regional benefits office..." With a crosslink to VBA.
  - Edit this sentence: "If you have other questions about your appeal (but it doesn't have to do with your hearing), you can email [email]."
- We'll consider changing "Washing, DC" to "District of Columbia" or adding "(state)" to the Washington row, since "Washington" followed by "Washington, DC" may be confusing.
- We'll add these other US territories to the table:
  - American Samoa, Gaum, Mariana Islands: Northwest
  - US Virgin Islands: South

I'll align on next steps with Beth and we'll update this page.

**Comment by saratorres2** [comment] 2024-11-30 00:28
@aprocik1 I published updates to this page on 11/29, and am waiting for changes to go live.

**Comment by aprocik1** [comment] 2024-12-03 16:25
I've confirmed that the changes to this page are live on VA.gov and I've wrapped up communication with SMEs via email. I'm closing this ticket as complete.

**Closed by aprocik1** 2024-12-03 16:25 UTC
Labels: sitewide content, sitewide CAIA

**Comment by aprocik1** [comment] 2024-12-04 18:00
@saratorres2, can you copyedit and publish the crosslinks I added to these pages?

- [Board hearings with a Veterans Law Judge](https://prod.cms.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing)--added "related information" section
- [Board of Veterans’ Appeals (BVA) hearing](https://prod.cms.va.gov/decision-reviews/legacy-appeals/board-of-veterans-appeals)--added "related information" section
- [Requesting a virtual hearing for a Board Appeal](https://prod.cms.va.gov/resources/requesting-a-virtual-hearing-for-a-board-appeal)--added crosslink in "related information" section

Thanks in advance!

**Comment by saratorres2** [comment] 2024-12-19 20:57
@aprocik1 I've published updates to the three pages listed above. (12/19)
