### ISSUE TITLE
[Bug] Google Analytics Not Capturing Location of Profile Save Failures

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#1740] opened 2019-09-12 14:58 UTC
## What happened?
The Call Center is receiving feedback that veterans are not able to save their mailing address. Analytics-Insights wants to research how often this is occurring in order to determine the impact and resolution for the error.  

Currently, the `Profile Save Failure` is being tracked in [Google Analytics](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22BW%22,%22Profile%20Save%20Failure%22,0%5D%5D&explorer-table.rowCount=100/) but needs the `Profile Section` that is generating the error.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- \[Developer debug]: Open browser dev-tools and Watch window.dataLayer for GA/GTM events being pushed to the data-array.
- URL: [**https://staging.va.gov/profile**](https://staging.va.gov/profile)
- Login via **ID.me** as test-user 150 (**vets.gov.user+150<span>@</span>gmail.com**) \[find credentials [here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/Testing/TestAccounts.md) \(under ID.me, click Staing Users link)]. 
- On Profile page, under Contact Information, next to Mailing Address, click **Edit**.
- In the edit dialogue, change address\*.
- Observe the error-message displayed in the dialogue box.

\*Contact @clantosswett for addresses that will trigger a failure.
Here are 2 addresses that triggered save-failures on Staging via test-user 150 \[find credentials [here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/Testing/TestAccounts.md) \(under ID.me, click Staing Users link)]:
  * 1109 E 5th St. APT 1207, Austin, TX 78702
  * 4111 W Philomena Dr, Meridian, MD 83646

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mojaray2k** [comment] 2019-09-16 15:19
@tlei123 How do I reproduce this?

**Comment by tlei123** [comment] 2019-09-17 15:24
@clantosswett , would you mind helping @mojaray2k find more addresses to trigger this Mailing Address profile-save-failure please?

For some reason test-user 150 and both the TX & MD addresses \[see Steps to Reproduce section above] are no longer triggering any error on [Staging Profile](https://staging.va.gov/profile/#contact-information).

Thanks much!

**Comment by clantosswett** [comment] 2019-09-18 13:03
@tlei123 Here are a few more addresses that I tested and produced the error. I tested on staging with the user vets.gov.user+0@gmail.com. 

5201 Kingston Pike, Suite 1-169, Knoxville, TN 37919 

227 Sandy Springs Place, Suite D457 , Atlanta, Georgia 30328 

Let me know if these don't work for you.

**Comment by mojaray2k** [comment] 2019-09-25 15:01
@tlei123 and @clantosswett I am not able to reproduce this error with the addresses you provided me. No Dialog box popped up. 

![Your_Profile___Veterans_Affairs](https://user-images.githubusercontent.com/875558/65613261-b3194b80-df83-11e9-8e55-02de93fb4012.png)

**Comment by tlei123** [comment] 2019-09-26 16:16
@mojaray2k , IF this is replicable on Staging (i.e., only not replicable on your Local), then pls. try to temporarily tweak the relevant Redux action/reducer code to force a local error condition.  Just make sure your temp tweak doesn't get commited.

Not sure if Erik/Lihan has told you but, while Staging returns actual API-endpoint responses, Local mostly returns mocked (from vets-api-mockdata).  Feel free to ping them for further details.

Hope this helps!  Ping me as needed on Slack if you'd like more help hunting down the Redux code.

**Comment by erikphansen** [comment] 2019-10-02 19:24
I'm trying to figure out how or why GA would be showing so many occurrences of the `Profile Save Failure -` even action without anything after the dash. I'm looking at the code and we only record this event if the `profile-section` is also set:

https://github.com/department-of-veterans-affairs/vets-website/blob/be2b5615b7f64531cfac75b4f916948491dcc5b4/src/platform/user/profile/vet360/actions/transactions.js#L112-L118

And I'm seeing places where we are likely _not_ recording this event because the `profile-section` isn't set, but in those cases GA should show no traces of it. I'm still looking into this but so far I'm not understanding why GA would be showing what it shows...

**Comment by nedierecel** [comment] 2019-10-02 20:42
@erikphansen Thanks for the information on the logic. In Google Tag Manager, it concatenates the `Profile Save Failure - ` with the `profile-section` and sends this data to GA.

However, that is mysterious that it is sending blank `profile-section`. Are there any places where the `profile-edit-failure` might not be related to a specific section?

**Comment by erikphansen** [comment] 2019-10-02 20:56
There are only two places where we send the an object with `event: profile-edit-failure` and `profile-action: save-failure`: one for Direct Deposit update/save failures and then this more general case where the specific `profile-section` is set dynamically. but like I mentioned, if we don't pass in something to use for the `profile-section` we shouldn't be calling GA at all. I'll see what else I can come up with.

**Comment by erikphansen** [comment] 2019-10-04 15:34
Still not sure why or how events are getting reported to GA without the profile section, but we should soon be properly reporting which profile section the user was trying to update when they got an error.

**Comment by nedierecel** [comment] 2019-10-05 01:50
Thanks @erikphansen - Please let me know when that goes live, and I'll continue to monitor.

**Comment by mojaray2k** [comment] 2019-10-07 13:56
@erikphansen I cannot find the branch that you created for this. Con you provide that please.

**Comment by erikphansen** [comment] 2019-10-07 14:08
@mojaray2k https://github.com/department-of-veterans-affairs/vets-website/tree/profile-fixes

**Comment by Justin-Pickett** [comment] 2019-10-10 14:25
@tlei123 can you validate this bug so we can have it closed out if its ready?

**Comment by nedierecel** [comment] 2019-10-11 14:01
@tlei123 Please let me know if you need my help. I might need guidance to force a save failure.

**Comment by erikphansen** [comment] 2019-10-11 14:24
If you check out https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,"analytics.eventAction","BW","Profile%20Save%20Failure",0%5D%5D&explorer-table.rowCount=100/ 

Now we need to figure out how/where the plain ol' `Profile Save Failure -` errors are getting recorded. As I said I couldn't see anything in our code that would be doing this 🤔

**Comment by nedierecel** [comment] 2019-10-11 14:52
@erikphansen Good to see it is populating. Within Google Tag Manager, I have a lookup table that matches the `profile-section` and outputs a cleaner version. 

I suspect there is a mismatch in one of the `profile-section` values where GTM might have an older value that doesn't match something in the code. I'll export that list for you and see where we can clean up the null value.

**Comment by erikphansen** [comment] 2019-10-11 15:03
@nedierecel oooohhh... that totally makes sense. but also kinda lame that Google wouldn't save the bad ID we are sending that doesn't match anything? let me know what you can find!

**Comment by erikphansen** [comment] 2019-10-11 15:42
@nedierecel any of these stand out as looking wrong? https://github.com/department-of-veterans-affairs/vets-website/blob/42d254ca558f1a4179ec45b906665a79ce97e1ac/src/platform/user/profile/vet360/constants/index.js#L65-L76

**Comment by erikphansen** [comment] 2019-10-11 17:53
@nedierecel GOT IT! I see a place where instead of a valid `profile-section` value that GA would understand we are accidentally sending numbers, like `0` or `1`. D'oh. I'll see if I can make that act more sensibly.

Just to leave a paper trail, the offending line is https://github.com/department-of-veterans-affairs/vets-website/blob/c53dec3228216b8cc58d12d44a91e2fff2ea3309/src/platform/user/profile/vet360/containers/PendingTransactionCategory.jsx#L29. The intended behavior is to just call `dispatchRefreshTransaction()` passing in the relevant transaction, but because it's using a `forEach` we are accidentally passing in the index of the transaction as the second arg to `dispatchRefreshTransaction()`

**Comment by nedierecel** [comment] 2019-10-11 18:10
@erikphansen Great sleuthing - I also found another inconsistency - looks like `primaryTelephone` doesn't match what is set in Google Tag Manager as `primary-telephone` and similarly for `alternateTelephone` doesn't match `alternative-telephone`.

I'll update the GTM settings to match what you have in code. I suspect your find + this one _should_ clear that up.

**Comment by erikphansen** [comment] 2019-10-11 18:14
@nedierecel so GTM is expecting `primaryTelephone` and `alternativeTelephone`?

**Comment by nedierecel** [comment] 2019-10-11 18:21
@erikphansen Sorry - I was zeroing my attention only on the camelCase version and failed to see the hyphen strings right next to it. Your find is the possible culprit then, and not what I had commented.

**Comment by erikphansen** [comment] 2019-10-16 18:29
moving back to In Progress as I should handle the issue I mentioned in this comment https://github.com/department-of-veterans-affairs/va.gov-team/issues/1740#issuecomment-541161987

**Comment by erikphansen** [comment] 2019-10-29 19:28
@nedierecel A PR was merged today that should prevent GA from getting the section-less profile save errors that look like this in the GA dashboard: `Profile Save Failure - `

Can you validate that in the next couple of days?

**Comment by nedierecel** [comment] 2019-10-30 14:11
@erikphansen Thank you, I'll review over the next few days that `Profile Save Failure - ` is declining.

While we're working on Profile Save Failures, I'm assisting with SMS Opt-in and Opt-out tracking for #2317. Is the issue below within your realm to fix?

>For Profile Save Success and Failure events when a user selects or deselects SMS, the `profile-section` is still pulling a value of `mobile-telephone` but _should_ push `sms-optin` or `sms-optout`.

**Comment by erikphansen** [comment] 2019-10-30 16:01
@nedierecel That sounds like something for the By Light team to handle. Specifically @elwoodva

**Comment by elwoodva** [comment] 2019-10-30 16:33
I am asking because the work for 2317 is in to use sms-optin and sms-optout when the user selects/deselects the checkbox and I was pretty sure @nedierecel tested that and confirmed that was happening.  Just not on the edit modal which it should remain "mobile-telephone".

**Comment by Justin-Pickett** [comment] 2019-11-05 16:41
@nedierecel and @erikphansen can this ticket be closed out?

**Comment by nedierecel** [comment] 2019-11-05 16:47
@Justin-Pickett Thanks for checking in.

@erikphansen I double-checked and still see [Profile Save Failures sneaking in without a `profile-section`](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p187673796/_u.date00=20190901&_u.date01=20191105&_.useg=&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&_r.drilldown=analytics.eventCategory:API%20Calls,analytics.eventAction:Profile%20Save%20Failure%20-/)

Follow-ups:
1. Are `primary-telephone` or `alternative-telephone` used anywhere? I have these in my lookup table, but these might be remnants from the Profile MVP in 2018. 
2. Is it possible that there is a general save failure that is not associated with a particular profile-section?

**Comment by Justin-Pickett** [comment] 2019-11-06 19:21
We can close this ticket.

**Closed by Justin-Pickett** 2019-11-06 19:21 UTC
Labels: analytics-insights, bug, profile, vsa-authenticated-exp
