### ISSUE TITLE
Restore links deleted in migration

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#6492] opened 2020-03-04 17:55 UTC
https://github.com/department-of-veterans-affairs/va.gov-team/commit/32577000c75b68c1b1a26ee7e07edeac647345e1#diff-4c1624daf6b176b7156ffe62827cebff

It looks like most of the links on this page were just... deleted? instead of being migrated over. Not sure why this happened. Can you take a look at this page (and others) to see if this happened more widely?

if I run a quick search over the repo, I see a *ton* of links that are empty (by searching for "]()" in the files):

$ ack --md -w '\]\(\)' -l
products/office-administration/vba/sco-migration/design/content/archive/SCO-migration-content-v0.0.md
products/decision-reviews/research/website-research/research-plan.md
products/decision-reviews/higher-level-review/research/research-plan.md
products/README.md
products/claim-appeal-status/research/discovery-SEP-2019/README.md
products/claim-appeal-status/research/discovery-SEP-2019/research-plan.md
products/claim-appeal-status/appeals-status/v2/content/appeals-overview-static.md
products/claim-appeal-status/appeals-status/appeals-status-content.md
products/claim-appeal-status/claim-status-api/discovery/README.md
products/caregivers/design-content specifications.md
products/caregivers/discovery/research/discovery-aug-2019/README.md
products/disability/526ez/research/sep-2017/what-we-want-to-know.md
products/disability/526ez/research/sep-2017/recruiting-language.md
products/disability/526ez/research/aug-2017/documents/081517-research-plan.md
products/disability/526ez/research/apr-2018/research-kickoff-document-live-data.md
products/disability/526ez/design/all-claims/chapter-outlines/5-review.md
products/disability/526ez/design/all-claims/chapter-outlines/1-veteran-basic-info.md
products/disability/526ez/design/all-claims/chapter-outlines/3-supporting-evidence.md
products/disability/526ez/design/all-claims/chapter-outlines/4-additional-info.md
products/disability/526ez/design/all-claims/chapter-outlines/2-disabilities.md
products/disability/526ez/design/all-claims/chapter-outlines/0-intro.md
products/disability/526ez/design/8940-4192-unemployability/content/8940-content.md
products/disability/526ez/design/8940-4192-unemployability/4192-content.md
products/disability/526ez/design/781-781a-ptsd/content/781a-content-newtech.md
products/disability/526ez/design/781-781a-ptsd/content/781a-content-old.md
products/disability/526ez/design/781-781a-ptsd/content/781-content-newtech.md
products/disability/526ez/design/781-781a-ptsd/content/781-content-old.md
products/disability/526ez/discovery/drc/readme.md
products/disability/disability-compensation-claim/blue-water-navy-veterans/product-outline.md
products/identity-personalization/profile/Combine Profile and Account/Research/Research Plan.md
products/identity-personalization/change-address/bad-address-indicator/product-outline.md
products/identity-personalization/personalization 2.0/discovery-research/card-sort/research-summary.md
products/identity-personalization/personalization 2.0/discovery-research/README.md
products/identity-personalization/personalization 2.0/discovery-research/dashboard-interviews/research-summary.md
products/identity-personalization/personalization 2.0/README.md
products/identity-personalization/personalization 2.0/analytics/analytics.md
products/identity-personalization/login/design/readme.md
products/identity-personalization/login/error-messages/readme.md
products/identity-personalization/login/reference-documents/login/fe-components.md
products/identity-personalization/login/reference-documents/login/fe-login-and-logout.md
products/identity-personalization/login/discovery/2016-solution/mhv-integration/2016-mhv-identity-background.md
products/identity-personalization/login/README.md
products/identity-personalization/login/gettingstartedidentity.md
products/identity-personalization/login/sso/design/readme.md
products/identity-personalization/login/user-login/research/readme.md
products/identity-personalization/login/user-login/design/PI7/readme.md
products/identity-personalization/login/user-login/design/readme.md
products/identity-personalization/login/user-login/previous-references.md
products/identity-personalization/login/user-login/successmetrics.md
products/identity-personalization/login/user-login/discovery/readme.md
products/identity-personalization/login/user-login/loginproductoutline.md
products/education-careers/stem/design/stem-simple-solution.md
products/education-careers/stem/design/stem-content-doc.md
products/education-careers/stem/design/22-1995-stem-content-doc.md
products/education-careers/school-comparison-tool/feedback-messaging.md
products/education-careers/school-comparison-tool/colmery-act-2019/design/content/profile-accordion-va-programs.md
products/education-careers/school-comparison-tool/colmery-act-2019/design/content/107-controls.md
products/education-careers/school-comparison-tool/colmery-act-2019/design/content/sec-116-vet-tec.md
products/education-careers/application/vettec-0994/design/0994-content.md
products/education-careers/application/vettec-0994/design/0994-post-mvp.md
products/education-careers/application/family-of-forms/readme.md
products/va-gov-relaunch-2018/design/content/content-approvals.md
products/va-gov-relaunch-2018/design/content/rewriting-page-tracker.md
products/va-gov-relaunch-2018/redirects-approach.md
products/va-gov-relaunch-2018/rollout/launch-checklist.md
products/va-gov-relaunch-2018/rollout/smoketest-launch.md
products/va-gov-relaunch-2018/rollout/kanban-roe.md
products/va-gov-relaunch-2018/wbc-decisions.md
products/facilities/medical-centers/Project_Plan_Outline_2019.md
products/health-care/appointments/appointment-reminders/vetext/README2.md
products/health-care/appointments/appointment-reminders/vetext/working-drafts/outdated-plan-for-2017.md
products/health-care/appointments/appointment-reminders/vetext/calls-with-mark-bulson.md
products/health-care/community-care/urgent-care/research/jun-2017/readme.md
products/health-care/prescription-refills/vets-prescriptions/research/rx-gap-analysis-2.md
products/health-care/prescription-refills/vets-prescriptions/product/feedback-messaging.md
products/health-care/prescription-refills/vets-prescriptions/product/ranking-options.md
platform/research/research-history.md
platform/design/design-resources/background-from-va-partners/ve-products/surveys/readme.md
platform/working-with-vsp/documentation-general.md
platform/cms/README.md
platform/product-management/phase-template-discover.md
platform/product-management/README.md
platform/product-management/overall-process.md
platform/quality-assurance/philosophy/qa-best-practices.md
platform/information-architecture/site-maps.md
platform/engineering/backend/README.md
platform/engineering/backend/engineeringonboarding.md
platform/engineering/backend/continuous-integration-process.md
platform/engineering/backend/tutorials/endpoint-punch-list-presentation.md
platform/engineering/backend/vets-api/development.md
platform/engineering/request-for-comment/uswds-foundation.md
platform/engineering/request-for-comment/1361-interim-content-management-system.md
platform/engineering/request-for-comment/switchingtojest.md
platform/engineering/request-for-comment/using-unmount-in-front-end-unit-tests.md
platform/engineering/infrastructure/readme.md
platform/engineering/development.md
docs/index.md
teams/health-products/README.md
teams/vsa/design/topline-summary-template.md
teams/vsa/design/spec-template-confirmationpage.md
teams/vsa/design/spec-template-mainpage.md
teams/vsa/design/spec-template-contentpage.md
teams/vsa/design/spec-template-intropage.md
teams/vsa/design/research-pilot-participant-guidelines.md
teams/vsa/teams/vamc/Project_Plan_Outline.md
teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-study/disabilities-dependents-usability-research-plan.md
teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-analysis.md
teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-research-plan.md
teams/vsa/accessibility/learning-sessions/abc02-getting-started-with-keyboard-navigation-and-screen-readers/README.md
teams/vsa/accessibility/learning-sessions/README.md
teams/vsa/accessibility/learning-sessions/abc03-cognitive-considerations/abc03-cognitive-considerations.md
teams/vsa/accessibility/learning-sessions/abc01-inclusive-design-best-practices/README.md
teams/vsa/onboarding/vsa-slack-guidance.md
teams/agile6/README.md
teams/by-light/README.md
teams/team-readme-template.md
teams/booz-allen/README.md
teams/vsp/README.md
teams/vsp/teams/tools/backend/triage/README.md
teams/vsp/teams/operations/README.md
teams/vsp/teams/operations/onboarding.md
teams/vsp/teams/insights-analytics/experiments.md
teams/vsp/teams/content-ia/template-team-folder-readme.md
teams/vsp/teams/product-dev-support/research/onboarding-mvp/research plan.md
teams/vsp/teams/product-dev-support/research/onboarding-vsa/results-summary.md
teams/vsp/teams/product-dev-support/research/onboarding-vsa/research-plan.md
teams/vsp/teams/product-dev-support/planning/planning-meeting-July-12-2019.md

**Comment by meganhkelley** [comment] 2020-03-05 14:50
From some initial poking at this, it looks like yes, the file you first identified should have been fixed during link fixing after the repo migration. 

I've spot checked some other files in the list you provided and found: 

*Some were created with blank links on purpose by the author (seemingly as placeholders):*
- products/claim-appeal-status/research/discovery-SEP-2019/README.md
- products/claim-appeal-status/research/discovery-SEP-2019/research-plan.md
- products/caregivers/design-content specifications.md
- teams/vsa/design/spec-template-mainpage.md
- teams/vsa/teams/vamc/Project_Plan_Outline.md
- teams/vsa/accessibility/learning-sessions/README.md
- teams/team-readme-template.md _(and therefore presumably most of the other team README files that have this issue)_

*Some have empty links but I can't see the history to determine why:*
_The reason I can't identify why these links are empty is that the folder names have been changed — GitHub sees that as the creation of a new doc, which is where the history starts. I'm sure we could identify the cause of the empty links with further digging but it is not worth the time._
- products/health-care/appointments/appointment-reminders/vetext/working-drafts/outdated-plan-for-2017.md
- platform/engineering/request-for-comment/uswds-foundation.md
- teams/vsp/teams/product-dev-support/research/onboarding-vsa/results-summary.md

*Some seem related to link migration and in fact seem to have had links (deliberately? accidentally?) deleted in post-migration link fixing* 
- products/va-gov-relaunch-2018/wbc-decisions.md (edited in [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/9ee845a5ac8c987b758fc93fd6957e3d314bbdc8#diff-f81bb8a7054e9d0b0168b1373a076f80))
- products/va-gov-relaunch-2018/rollout/kanban-roe.md (edited in [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/3ae376d5cf5898953788383bce3e15751b64d6b7#diff-6e42f630a7b878b52e5bf1862e35bdb3))
- platform/research/research-history.md (edited in [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/96638ec495083b6d01700fc2a5cd197696288a8e#diff-0fdbc610eb18aed3fb00fa1808a72884))
- platform/engineering/development.md (edited in [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/88dd77938c6a47607828c0b1d8a10918d4db835f#diff-0615d122f735ec810b0c7d4f1cff8f9a))

We'll need to prioritize fixing the doc you first identified, @gunsch and can try to slot that in within the next couple of weeks. Beyond that, in the short term we won't be able to dig into every single one of these files, and we will likely just need to treat missing links on a case-by-case basis (with the assumption that if they're files people reference often, the issue will get to us again). Let's plan to check in (you and I) on that approach and what to do here.

**Comment by gmaciolek** [comment] 2020-07-23 22:04
@meganhkelley and @gunsch 👋 Is this still a priority?

**Comment by gunsch** [comment] 2020-07-23 23:26
my take: I don't think we need this for _all_ the docs I found with problems, but we should should probably check some of them. my shortlist would be all the READMEs + docs under `platform/`.

**Comment by gmaciolek** [comment] 2020-07-28 19:19
@gunsch I'm going to move this to our backlog, but I'll revisit it soon because doing an audit of all the empty/broken links in READMEs and docs under platform for broken links might be a good task for our new writer once she has access to everything and is settled in.

**Comment by lianilychee** [comment] 2022-02-17 15:57
Closing, no longer relevant.

**Closed by lianilychee** 2022-02-17 15:57 UTC
Labels: documentation-support
