### ISSUE TITLE
Content Dataset Page Title Formatting

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#39661] opened 2022-04-06 14:56 UTC
## What happened?
We are seeing duplicate line items with the same "event action" - "page title" .  See slack link below for additional details.

https://oddball.slack.com/archives/C01EUNU6W1Z/p1648828604397489

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by michelle-dooley** [comment] 2022-04-06 14:59
Creating a ticket for this work per our slack thread above.  Also included latest updates here ..

from @chloedotbrown - Think I've narrowed the issue down to the page_title field, but I can't for the life of me figure out why. The titles look exactly the same, and when I paste them in text comparison apps, they also come up as identical.
Still, I've tried adding every other field involved in any of the associated Beast Modes, but they all look the same! It's just when I remove the page_title that everything resolves into one row.
I'll keep looking into it, but if anyone else has any title-ideas, lmk!

![image](https://user-images.githubusercontent.com/93597659/162004664-31662374-9901-4e07-9a65-6dbca674da80.png)

![image](https://user-images.githubusercontent.com/93597659/162004724-ff09bb05-4749-4cd5-8214-721d3f3fb31e.png)

from @obrienjulie  - I've seen this issue before. Testing out some changes now and will let you know once it's been corrected.

**Comment by chloedotbrown** [comment] 2022-04-27 17:52
Here's the [link](**url**) to our most recent conversation on this issue, so that it's easier to convene around once higher priority work is complete.

**Comment by chloedotbrown** [comment] 2022-06-08 23:29
Hi @kaipyroami ! I'm still seeing double-piped variations of the page titles in both BigQuery and Domo. However, I spent some time this afternoon digging into the issue and found some interesting patterns in the date range that make me think this may have been caused by a team/teams titling pages outside of the normal style guidelines and fixing them later.

### Finding double-pipes
First, here's a look at the top pages with "| |" in their title, along with the first and last date they appear in the data and the unique users who interacted with them. Most of the double-pipes titles appear on or around 6/24/2021 and end between mid-July and September (though there's more variation in the end date).

```sql 
with double_pipes as (
  select distinct
    page_title,
    site_url,
    user,
    date,
  from `vsp-analytics-and-insights.vsp_sites.vw_content_engagement`
  where page_title like '%| |%'
)

select page_title,
  site_url,
  min(date) as min_date,
  max(date) as max_date,
  count(distinct user) as users
from double_pipes
group by page_title, site_url
order by users desc
limit 1000
```
<img width="1322" alt="doublepipe titles by date" src="https://user-images.githubusercontent.com/45518242/172732095-06469c89-ff6e-4ca3-8e56-5c0c599d5636.png">

### Confirming both versions exist
Most of these pages have single-piped equivalents that show up in the data before and after the double-piped version. For example, I ran a version of the query above ☝🏻  filtered by `where page_title like 'Veteran Trust In Va |%'` instead of the pipe condition. The date range for the correct version goes up to the most recent week of data and starts about a month before the incorrect version.

<img width="1238" alt="title date range comp" src="https://user-images.githubusercontent.com/45518242/172732719-2f2008fa-926b-43ec-8080-4e64f4144e05.png">

### Original GA issue?
I was also curious to see if this was something that showed up in the original data or something that occurred in our data processing, so I tested a specific url I knew was affected from the GA tables, instead of our content views. Sure enough, the original version has the double piping (though less white space before it?). There are single-pipes in the title until 6/23, both versions 6/24, and only the double-piped version in the days immediately afterwards.
```sql
select distinct
   date,
   hits.page.pageTitle as page_title_ga,
   trim(regexp_replace(hits.page.pageTitle, r'[^a-zA-Z,0-9,-,|]', ' ')) AS page_title_content
from
    `vsp-analytics-and-insights.176188361.ga_sessions_*` AS ga,
    unnest (ga.hits) as hits
  where
    hits.page.pagePath like 'www.va.gov/resources/what-does-burial-in-a-va-national-cemetery-include%'
    and _table_suffix between '20210620' and '20210630'
  order by date, page_title_ga
```
<img width="929" alt="Screen Shot 2022-06-08 at 4 22 05 PM" src="https://user-images.githubusercontent.com/45518242/172733477-a4ee7b6d-761e-4c32-aceb-a8f462f4079d.png">

### Next steps
I feel solid about our understanding of what is was _causing_ this issue - past versions of page titles didn't follow VA style guidelines, but the issue has since been corrected.

As for what to **do** about it - we usually wouldn't consider correcting page titles in the underlying data, especially since they've now been corrected. However, since this one was fairly wide-spread and may cause confusion for folks looking at our data products, I'd recommend we consider adding a replacement function in our Content views so that we correct for double-piping errors in the old data.

@michelle-dooley - what do you think?

**Comment by kaipyroami** [comment] 2022-06-08 23:55
@chloedotbrown I see the double piped versions as well but isn't the concern of this issue the two identical page titles being grouped independently?

**Comment by chloedotbrown** [comment] 2022-06-09 00:40
@kaipyroami Aha got it! Yes, as far as the duplicate page titles, I'm only seeing them for the piping issue, but not for the identical text issue that was appearing before. Thanks for clarifying!

**Comment by kaipyroami** [comment] 2022-06-09 01:27
So I think this ticket can be closed unless anyone else has anything to add.

**Comment by chloedotbrown** [comment] 2022-06-09 17:30
Great! Currently running backfill of Content data to fix piping and white space issues (tested in BQ and Domo ahead of time). Backfills usually take 7-8 hours, so I'll close out ticket tomorrow morning once it's finished updating.

**Comment by chloedotbrown** [comment] 2022-06-10 18:15
Confirming content backfill is complete. Page duplication issue has been resolved and historical double-piping error has been corrected for. Domo datasource is now reset to append last week's data on Sundays moving forward.

Closing out this ticket - thanks again for all your help, Kyle!

**Closed by chloedotbrown** 2022-06-10 18:15 UTC
Labels: bug, analytics-insights
