### ISSUE TITLE
Redirect Request: 10-10EZ Form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#80756] opened 2024-04-15 20:53 UTC
### Status
**[2024-04-16]** Noting that this isn't ready for implementation yet; but moved to Next Refinement in the PW backlog so it'll be poised to implement when ready.

### Instructions

**_Redirects are only done Mon through Thursday. Don't merge/request a deploy on Friday._**

- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

| POC | Github alias(es) |
--- | --- 
| Product team point(s) of contact: | @hdjustice  @longmd |
| Content point of contact: | @aliyahblackmore  |
| IA point of contact: | @kristinoletmuskat  |

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)
- [ ] We are removing a temporary redirect  (add relevant background and link to original redirect request)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
http://va.gov/health-care/apply/application/ **and all subsequent child pages** (JM 4/15/24) |  http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/ **and all subsequent child pages** (JM 4/15/24)

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [x] Requesting team: Validates everything is correct in production and closes ticket

**Comment by longmd** [comment] 2024-04-15 21:04
Adding a note in that initial implementation has been done on the redirect front to update this URL: 

1. [Duplicate entry has been created in `content-build`](https://github.com/department-of-veterans-affairs/content-build/pull/2006) to allow the app to co-exist at both URL points
2. [React route has been reserved in the reverse proxy](https://github.com/department-of-veterans-affairs/devops/pull/14201) for the new URL
3. [Redirects have been added to the reverse proxy](https://github.com/department-of-veterans-affairs/devops/pull/14205)
4. [Redirects have been added to the new reverse proxy repo](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/264)

For me, the only places I don't see the redirects happening on staging is when clicking from a Hub page, or from the mega menu. All other links and hitting the current URL directly invoke the redirect.

**Comment by jennymayoco** [comment] 2024-04-15 21:23
Hi @hdjustice thank you for submitting this ticket! @kristinoletmuskat will do an IA review on this and vet the URLs. Just to confirm, when I click http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/, I still get this URL www.va.gov/health-care/apply/application/ - has the URL change been pushed to prod?

I've also updated the above URLs to include all child pages so they all have the same base URL, `/apply-for-health-care-form-10-10ez/`

**Comment by hdjustice** [comment] 2024-04-16 13:00
Thank you @jennymayoco .  The URLs are not live in Prod yet.  We wanted to be sure of all the steps and coordination before pushing to prod.

**Comment by kristinoletmuskat** [comment] 2024-04-16 20:11
Hey @hdjustice and @longmd  when you're ready you can push your new URL to prod. After the new URL is live, we can implement the redirect. I'm not sure Matt which team are you on -- are you on PW getting the redirect ready, or are you on the health team doing a redirect?

**Comment by aliyahblackmore** [comment] 2024-04-16 20:19
Hi @kristinoletmuskat does this redirect require any content support?
If so, can you let me know?

**Comment by kristinoletmuskat** [comment] 2024-04-16 21:42
No! I think we were just asked to start putting the content person in the
ticket. I'll see if maybe we don't need to do that if it tags you on
something you don't actually need to look at. Or would you want to be in
the loop about the redirect?

**Comment by aliyahblackmore** [comment] 2024-04-16 21:59
Ah okay got it.  I wasn't looped in on that convo.

I'm happy to remain tagged here and will just note for myself that there aren't any content needs @kristinoletmuskat!

**Comment by longmd** [comment] 2024-04-17 16:07
@kristinoletmuskat , I'm on the team doing the work for this update, not PW. If you reference my comment above with the work already done, you'll see there have been steps already completed for this to date. 

We have the URL set up and it is available in prod already. I actually added the redirects into the reverse proxy, too, which those went to prod this morning. So, we have the steps completed, minus actually changing the URL in our application. This is a React app page, and not a traditional static content page.

**Comment by jilladams** [comment] 2024-04-25 18:18
Thanks for clarifying @longmd . Removing public websites based on that note, but holler if you all need consult on anything.

**Comment by kristinoletmuskat** [comment] 2024-05-01 18:44
Hey @longmd -- to clarify, can we close this ticket now? DId ya'll change the URL in your application, or are you waiting for a certain date to do that?

**Comment by longmd** [comment] 2024-05-02 14:38
@kristinoletmuskat , if y'all are good, we can close. I will do the final swapover on Monday (May 6).

**Comment by longmd** [comment] 2024-05-02 16:59
@jilladams , I'm only seeing one redirect that doesn't appear to work in my [current RI with the updated root URL](http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001). If you search for "10ez" and select the [2nd recommended option](http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/apply/application/introduction). It 404s. 

Links from other pages that have that same link redirect as intended, but hitting that route directly with the subroute 404s. Any advise? [Here is the PR for the updated redirects.](https://github.com/department-of-veterans-affairs/devops/pull/14258).

**Comment by FranECross** [comment] 2024-05-03 14:32
@longmd Will you please share specifically which URL you're getting the 404 on? When I search 10ez, the first several displayed open without error for me.  Thanks! cc @jilladams 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147188767/448d672e-a443-48bd-950d-142e535f9f9c)

**Comment by longmd** [comment] 2024-05-03 16:21
@FranECross , its the second recommendation there.. with this URL: 
http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/apply/application/introduction.

**Comment by jilladams** [comment] 2024-05-03 19:57
I can repro that. 
If I click this result, I get a 404: 
![Screenshot 2024-05-03 at 12 52 46 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/10d3c57d-cd5f-49ad-a2ab-12c0ad118395)

I land on http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/apply/application/introduction with the 404.

If I remove `/introduction` and go to http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/apply/application, I get successfully redirected to http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/apply-for-health-care-form-10-10ez/introduction. 

If this were a standard redirect, usually that would mean we're missing some regex that handles child paths. I _think_ your PR should already be handling that: https://github.com/department-of-veterans-affairs/devops/pull/14258/files, so sort of mysterious to me, but I'm not an engineer. @randimays or @dsasser could you take a quick look here and see if you see anything obvious about Matt's redirect implementation that would account for a child page that isn't redirecting successfully?

**Comment by randimays** [comment] 2024-05-06 13:42
@jilladams I think this is review instance weirdness. If I go to http://d5a6827eac9e9c6ed11b24f48cccbf80.review.vetsgov-internal:3001/health-care/income-limits/introduction (or any other income limits route like `/zip`), I get a 404. This also happens to me running locally if I'm running content-build and vets-website together. We know that Income Limits prevents deep dives in other environments, and reroutes to `/health-care/income-limits`, which redirects on the client side to `/health-care/income-limits/introduction`.

All that said, this is normal review instance behavior. I can't be 100% sure why this is happening (might be worth a Platform ticket to confirm), but it happens across all applications.

**Comment by longmd** [comment] 2024-05-06 15:17
@randimays , thanks for the reassurance on that behavior. I have gone ahead and merged the update for the rootUrl in our React application and can confirm that same link does not 404 in prod! 🎉  

@kristinoletmuskat , this update completes all the steps necessary for this ticket!

**Closed** 2024-05-06 15:19 UTC
Labels: 1010-team, sitewide IA, VA.gov frontend, sitewide CAIA, Redirect request

**Comment by mnorthuis** [comment] 2024-05-13 20:12
Looping back around to this issue.  It was discovered that child pages of the old URL were not responding to the redirect.  So basically what was seen in the review instance is what happened in production.   Wondering if anyone on this issue verified that behavior  once the change was pushed to production. Also trying to understand timing for how long this may have been broken.  I see a merge on April 29th on the PR, but the above conversation was as recent as May 6.   When was this redirect fully implemented?

**Comment by longmd** [comment] 2024-05-14 01:39
@mnorthuis , we certainly did verify per my last comment on the 6th of May. The redirects were put into the rev proxy on the 29th, in which case a draft PR was put up with the root URL change in the React app. There was testing done there on the redirects, which prompted the note to the PW folks asking the question on the behavior. After that conversation resolved, the root URL of the React app took effect May 6 and was verified by multiple folks utilizing multiple links across VA.gov.

**Comment by mnorthuis** [comment] 2024-05-14 17:08
Thank you @longmd!  I'm trying to figure out at what point this redirect stopped working correctly so we can identify if process changes are needed here.  Do we have any indication as to what may have broken the redirect?

**Comment by hdjustice** [comment] 2024-05-15 14:59
@mnorthuis That is a great question, since it seemed to have worked and then it didn't.  Adrian said it was a regex update that needed to be done (like what Jill mentioned above on 5/3 could be the issue)
