### ISSUE TITLE
[SCREENREADER]: 526 V2 - Date fields are firing error messages too soon on unit assignment page

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#1086] opened 2019-08-19 20:29 UTC
Migrated from vets.gov issue [#16354](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16354)

## Issue
The date input fields are firing error messages when the input still has focus. This is confusing to screen readers because the error interrupts what the user was typing. It would be better to wait until the input fields had lost focus before letting users know they had entered something incorrectly. Screenshot attached below.

## Acceptance Criteria
* As a screen reader user, I want to hear the To and From date input errors after I have navigated away from the input fields

## Environment
* Win10
* IE11, Firefox
* NVDA, JAWS

## Affected Pages
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/disabilities/ptsd-secondary-incident-unit-assignment-0

## WCAG or Vendor Guidance (optional)
* [Error Identification: Understanding SC 3.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-identified.html)

---
![screen shot 2019-01-17 at 4 09 01 pm](https://user-images.githubusercontent.com/934879/51352561-94b59480-1a73-11e9-89fc-b69e4ff9f4f0.png)

**Comment by peterhill-oddball** [comment] 2019-08-19 20:30
Prior to migration, this issue was part of an epic [https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15434](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15434)

**Comment by ndsprinkle** [comment] 2020-01-21 14:31
This ticket is quite old now, so some things may have been changed in the code to affect this situation, but I am having issues replicating this exact scenario.

No matter which date field I am filling out, including the precise date field in the screenshot above, upon first entering information into the field, the validation does not fire. In fact, no validation is fired at all until the continue/save button is pressed, which is exactly as expected and intended. 

However, after the continue/save button has been pressed and the validation has fired for the first time, then the fields will continuously be validated as the veteran types/changes information. It is unclear to me if this is intentional or not, but overall it seems like expected behavior. Before closing this ticket or making anymore judgments, I'm going to bring in a designer from our team to shed some light on the expected behavior of the validations.

**Comment by 1Copenut** [comment] 2020-01-21 14:43
@ndsprinkle I've added @emilywaggoner && @CrystabelReiter from VSP design to the assignees list for visibility.

To my thinking, the date fields should never validate while users are typing. That's being overly presumptive about what is and is not an error. Error handling should wait until the user exits the field, then validate what the user inputted.

That's just my opinion; I'll defer to design for the final call and help the team with accessibility considerations.

**Comment by ndsprinkle** [comment] 2020-01-21 16:31
Thank you @1Copenut I think you are correct, but the result I am getting is that **all** the fields validate when typing/modifying after the user has hit done/save/continue, so it doesn't seem to be exclusive to the date field. This seems to be mostly true across all forms (only have tested a couple), though sometimes I get mixed behavior where it will work as you say and the field has to lose focus, but consistently it does seem that the validation while typing won't happen unless the user has already clicked done/save/continue.

**Comment by ndsprinkle** [comment] 2020-01-21 17:56
After testing a few more scenarios, it is now apparent that all the fields within the forms do fire their validations when losing focus **except** the date fields. This still is a bit different than what the ticket specifies and my comment above explains the only way I can get the validating to happen while typing. 

The issue with the not validating when losing focus needs to be fixed though, and I think a second ticket will probably be created for this. Also, as I mentioned above, this seems to be a global form issue with the date field, so our team can work on the solution or it can be handed off to another team. I will update in here once the new ticket is created and the assignee is decided.

**Comment by ndsprinkle** [comment] 2020-01-21 20:27
Spin off ticket has been created for the date fields not validating on focus loss: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5031

I would still like some insight on the other issue from a designer :) Again, the situation is that once the user has clicked continue/save/done and has validation issues with some field, then all fields will continuously validate as the user types or selects. I can demo this if necessary, but it seems to apply to all forms. Is this behavior okay/expected? Should this be addressed? It's almost as if the form enters a validation state where every field validates constantly.

**Comment by 1Copenut** [comment] 2020-01-21 20:58
This does seem a bit unusual, to be kicking into a secondary validation flow where once the user has pressed Continue, any input changes are triggering the client-side validation checks on every keypress.

**Comment by ndsprinkle** [comment] 2020-01-24 15:30
@emilywaggoner @CrystabelReiter Any thoughts on the situation described in my most recent comment?

**Comment by CrystabelReiter** [comment] 2020-01-24 15:57
So from what I'm gathering the concern is the form is firing off error mode
when a person types in the field AFTER someone has clicked
saved/done/continue?

**Comment by ndsprinkle** [comment] 2020-01-24 16:05
@CrystabelReiter That is correct, and of course there has to be validation errors when save/done/continue is pressed.

**Comment by CrystabelReiter** [comment] 2020-01-24 16:59
I feel as though that's a frustrating experience for the user, I agree with
Trevor that validation mode should not set off until the user has exited
the field

**Comment by ndsprinkle** [comment] 2020-01-24 20:23
Okay, thank you for your feedback. I will create a spin off ticket to take care of this!

**Comment by ndsprinkle** [comment] 2020-01-27 20:58
Spin off ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5190

**Closed** 2020-01-27 20:58 UTC
Labels: 508-defect-3, 508-issue-focus-mgmt, 508/Accessibility, 526, frontend, vsa-benefits
