### ISSUE TITLE
Enable option chaining in VFST repo

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#11832] opened 2020-07-29 19:21 UTC
**Is your feature request related to a problem? Please describe.**

Optional chaining is supported in almost all modern browsers - https://caniuse.com/#search=optional%20chaining - but it currently not enabled in babel

> veteran-facing-services-tools/node_modules/@babel/core/lib/transformation/normalize-file.js:209
>    throw err;
>    ^
> SyntaxError: unknown: Support for the experimental syntax 'optionalChaining' isn't currently enabled

**Describe the solution you'd like**

Tell babel we want optional chaining!

**Describe alternatives you've considered**

Hypnotize babel into submission <img alt="ghe-emoji" title=":_tuzki_psychedelic:" src="https://cloud.githubusercontent.com/assets/136959/13371051/80906bc8-dce2-11e5-84ff-6d91f4cf82c2.gif">

**Comment by rianfowler** [comment] 2020-07-29 19:32
duplicate of #11705

**Closed by rianfowler** 2020-07-29 19:32 UTC
Labels: VFS Tools Repo, tools-fe
