### ISSUE TITLE
Burial | Audit DataDog dashboard to show # and %

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#90212] opened 2024-08-07 20:28 UTC
## Issue Description
_OCTO has outlined a [standard set of form analytics](https://dsva.slack.com/archives/C055573C508/p1721768647619279) that need to be collected for each form on VA.gov. Part of the requirement is that each metric show both the number AND % of submissions._

---
## Tasks
- [ ] Audit existing DataDog dashboards to ensure both # and % of submissions are included for:
   - [ ] Submission total failure error (# and % of submissions that are submitted on VA.gov (user receives a successful confirmation message) but never reach the next system
   - [ ] Backup path usage (# and $ of submissions that are submitted on VA.gov (user receives a successful confirmation message) and fail automatic establishment but succeed using a backup path of a document
   - [ ] Separate ticket to track evidence upload submissions and errors is #90213

## Acceptance Criteria
- [ ] All burial form dashboards include % and # for submission total failure error
- [ ] All burial form dashboards include % and # for backup path usage
---

**Comment by mjknight50** [comment] 2024-08-23 16:58
@sanjabaj2 will review this and confirm if the scope if a one-time or ongoing widget.

**Comment by steele-lm** [comment] 2024-08-23 19:02
@mjknight50 The general request is to add percentages to existing and new datadog metrics (where appropriate) to make it easier to determine if error volume is significant.

**Comment by balexandr** [comment] 2024-09-25 19:34
Yes, I believe it is unless you require some additional widgets?
![Image](https://github.com/user-attachments/assets/5cce98fc-8b87-49d2-86a7-3cb87e639d65)

**Comment by wayne-weibel** [comment] 2024-09-27 17:17
duplicate of [#90226](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90226) - few additional widgets being added as part of that ticket

**Closed by wayne-weibel** 2024-09-27 17:17 UTC
Labels: Burial, engineering, ENG:Excellence, zero-silent-failures
