### ISSUE TITLE
[DNS] Manual Review Instance Deploy Brings Down Access to Internal Tools

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#20495] opened 2021-02-25 18:14 UTC
## The Problem
When manually executing the review instance deploy jenkins job, it's possible for a duplicate DNS server entry to get created in the `vetsgov.utility.internal.zone` named config. As a result, **named fails to start up and access to internal tools through socks fails**.

### Steps to Reproduce

1. Created a branch in vets-api
2. Start a draft PR in vets-api using said branch
3. Wait for review instance to get auto-deployed
4. Navigate to the [jenkins review instance deploy job](http://jenkins.vfs.va.gov/job/deploys/job/vets-review-instance-deploy/)
5. Click “build with parameters”
6. Modify the `api_branch` text field to be the vets-api branch from step 1 

## Extra Context
- Slack link to where this happened - [link](https://dsva.slack.com/archives/CBU0KDSB1/p1613518905235900?thread_ts=1613517544.229900&cid=CBU0KDSB1)

## Work to be Done
- [x] Root cause why a duplicate entry is created in the `named` config when the job gets run manually V.S. when new commits are made to the `vets-api` branch
- [x] Implement solution to prevent an invalid `named` zone config from being deployed

## Potential Solutions
Modify the script that adds these things to make sure that duplicates aren't created

**Comment by jbritt1** [comment] 2021-06-11 20:24
From what little I know about these, [it appears the slug which is used to build the URL is made from the branches](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/review-instance-configure.yml#L21) being piped to `md5` so it makes sense it would try to make the exact same entry in `named`. I wonder if simply adding a timestamp portion to the slug would help alleviate?

**Comment by jhouse-solvd** [comment] 2021-08-09 19:48
@jbritt1 - That's a great thought. @omgitsbillryan - could you confirm if Jeremy's suggestion would be useful and help address this concern for the time being?

**Comment by rmtolmach** [comment] 2022-03-01 17:46
Steps to resolve SOCKS problem manually: https://vfs.atlassian.net/wiki/spaces/OT/pages/2104262859/Fix+SOCKS+error+administratively+prohibited+open+failed

This is not a long-term solution, but we wanted to get the steps written down for future occurrence, so anyone could resolve it.

**Comment by jbritt1** [comment] 2022-03-02 19:32
Upon the digging we did in the above pull request, it was discovered that it was in fact not manual redeploys causing the issue. The internal zone is built on a conditional statement on whether an instance has a `slug:` tag defined and uses that tag value to make an entry. When two instances with the same slug tag exist, the entry was being duplicated for each additional EC2 instance (config file with conditional statement: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jumpbox/templates/vetsgov.utility.internal.zone.j2#L32-L37)

**Comment by jbritt1** [comment] 2022-03-03 14:37
Pretty confident this issue was resolved by the above linked pull request, but will leave this issue open a bit longer as we monitor for any new occurrences.

**Comment by jbritt1** [comment] 2022-03-04 13:08
Plan is to continue to monitor today and if the issue is not observed to close this Monday 3/7.

**Comment by jhouse-solvd** [comment] 2022-03-04 17:07
Let's close this and either re-open or create a new issue as needed. 

Closing.

**Closed by jhouse-solvd** 2022-03-04 17:07 UTC
Labels: operations, infrastructure
