### ISSUE TITLE
Feature/Add SMOC capability in VAHB Mobile app

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#91554] opened 2024-08-27 13:15 UTC
## Description
Frontend work for adding SMOC to VAHB Mobile App

## User Story
As a Veteran or Caregiver, I want to submit a Mileage-only Claim in the Mobile App, so that I can be reimbursed for travel expenses.

## Risks
Requires #91552 (API) and #91570 (React Query integration) and #91573 (remote config feature flag)

## Acceptance Criteria
- [ ] Users are able to submit a SMOC through the VAHB Mobile App

## Definition of Done
- [ ] Users can submit a SMOC for an appointment at a VAMC for mileage-only travel reimbursement
- [ ] Documentation is updated

---
## How to configure this issue
- [x] **Attached to an Epic**

**Comment by ayush-chak** [comment] 2024-09-27 15:58
Closing as dupe of epic.

**Closed by ayush-chak** 2024-09-27 15:58 UTC
Labels: beneficiary-travel
