### ISSUE TITLE
[Development] 526: Banking Info in 526 Not displaying in review step

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2345] opened 2019-10-09 17:41 UTC
## What happened?
_Banking information does not show up on the review step of 526 after having had completed the banking info in a prior step. If the banking info is not valid, no error messaging is displayed._

Update 8/25: Banking info is still empty when going to the review page.  @annaswims was right.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Acceptance Criteria
- [ ] Banking info populates correctly

**Comment by Mottie** [comment] 2019-10-23 16:28
The data is present (in Redux), but it is not being displayed in the review card. I didn't get a chance to spend too much time digging into this issue.

**Comment by Mottie** [comment] 2019-12-04 22:08
I think this might be an issue with the preloaded mock data being used.

If I log into to user 228 and go through the entire form (526) in my local environment, I see the banking info

![](https://user-images.githubusercontent.com/136959/70182485-897a5000-16a9-11ea-82f8-780de6af3b70.png)

But when I enter the same steps on staging.va.gov, the review entry shows empty fields

![](https://user-images.githubusercontent.com/136959/70182534-9e56e380-16a9-11ea-9240-a399fec73705.png)

I'll create a PR that I think will fix the problem, but we won't know until it's pushed to staging and tested.

**Comment by ndsprinkle** [comment] 2019-12-09 14:11
This PR has been merged and will be tested in staging to see if the issues is resolved.

**Comment by ndsprinkle** [comment] 2019-12-13 20:24
Unfortunately, the issue still exists. Upon looking into this issue more, I'm not sure if it's even possible for us to solve this issue the way we want to. The bank account information that we get back that lives in redux is pre-masked, meaning that the data has "******" in the account and routing numbers. Since this is the case, there's no way for us let the user "edit" that information. Here's an example of what it looks like in the JSON:
`'view:bankAccountType': 'Checking',`
`'view:bankAccountNumber': '*******5123',`
`'view:bankRoutingNumber': '*****4974',`
`'view:bankName': 'NAVY FEDERAL CREDIT UNION'`

However, the reason the bank account info is showing up blank on the review screen is because the review screen isn't using this information. The review screen is trying to display a "new banking information object" as if the user had added a new bank account earlier in the form. This kind of makes sense because, as I said, the user can't edit the masked information and one of the review page's purposes is for editing the previously entered information. Therefore, if a user goes through the form and enters new banking information, then the banking information entered will appear on the review page. 

Hopefully this summarizes things: the review page is trying to show editable banking information, so if the user adds new banking information during the form, then it will show up on the review page and be editable, but if the user does not add new banking information (and simply confirms that the existing banking information on file is correct), then nothing will appear on the review page because there is no editable banking information. 

What further complicates things is that the blank banking information on the review page IS editable and I think if the user edits it and adds banking information then it will override the previously "confirmed" banking information. 

@YanaRoy  There definitely needs to be some design discussion around this as there isn't a clear path to move forward. It also will be easier to explain the situation with a demonstration rather than me trying to put it into words. Basically, what needs to be determined is what should be displayed on the review page.

**Comment by YanaRoy** [comment] 2019-12-17 19:32
The outcome of the research for this issue has caused the need to include design team members to identify how this should be handled. Closing ticket. Will open new design ticket with link to this ticket.

**Comment by Mottie** [comment] 2020-09-08 20:36
I stated investigating this issue again today. It appears that the review page data (`view:bankAccount`) isn't connected to the preloaded banking info (`view:originalBankAccount`), and that the data passed into the rendering component is only coming directly from the `view:bankAccount` (unfilled) with no way to access the preloaded info. I will look into modifying platform code to test if it is possible.

**Comment by Mottie** [comment] 2020-09-08 22:16
Ok, I figured out how to get this fixed, but it requires merging in the work from https://github.com/department-of-veterans-affairs/vets-website/pull/14091

**Comment by Mottie** [comment] 2020-09-14 15:14
No progress on this work; but it can be updated and available quickly once 14091 is merged.

**Closed** 2020-09-23 16:19 UTC
Labels: 526, bug, frontend, vsa-benefits
