### ISSUE TITLE
[VAMC] Please review and create redirects from General VAMC - to main medical center - Campus Maps 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34644] opened 2021-12-29 23:21 UTC
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live:  In next 14 days.

### Redirects   - 25 total redirect corrections
Current URL  |  Redirect Destination or New URL
** Updating

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment] 2022-01-11 18:24
URL corrections needed for the destination pages per core VAMC IA. This issue is blocked until those changes are made, and then we will evaluate whether redirects are needed.

**Comment by mnorthuis** [comment] 2022-01-11 18:24
@SgardnerPMP is this a duplicate of #34645?

**Comment by SgardnerPMP** [comment] 2022-01-28 16:43
I have updated list per meeting with IA and Dave Conlon.  This will require redirect list for a lot more of the systems.  I will load and also attach a file for ease of use by IA and PW.  Coming soon.

**Closed** 2022-02-09 05:30 UTC
Labels: blocked, VAMC-Upgrade, vamc-production-QA, Sitewide IA
