### ISSUE TITLE
AVS MVP May, 2023 Error State Documentation

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#58808] opened 2023-05-22 14:31 UTC
# Description
An error state report of all the possible errors in the AVS MVP May 2023 Prototype.

# Tasks
- [ ] Document all possible error states.

# Acceptance Criteria

**Comment by kristenmcconnell** [comment] 2023-07-03 20:41
Duplicate of 59064

**Closed** 2023-07-03 20:47 UTC
Labels: my-health, AVS, my-health-APPOINTMENTS
