### ISSUE TITLE
 3 Implement monitoring for DSLogon identity dependency

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#500] opened 2019-07-05 16:56 UTC
While we don't connect to DSLogon directly, it will be a transitive dependency for vets.gov users and so we'd like to know when it is down. In the future we can consider things like disabling the dslogon button if we know it is broken. For now, just monitoring.

POC to determine a good URL to monitor is Eric Gruye. CC Kam.

While at it, ask if there is an incident or downtime notification mechanism other than ANR, and if so ask for the devops maintenance list to get added to it.

**Comment by annaswims** [comment] 2019-07-18 13:55
closing as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/573

**Closed** 2019-07-18 14:02 UTC
Labels: tools-improvements
