### ISSUE TITLE
4142 Implement Migration from CentralMail to Benefits Intake

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#74810] opened 2024-01-29 21:14 UTC
As a Veteran
When I create a 526 disability claim
And I indicate that my medical information should be obtained by my medical provider
An ancillary 21-4142 claim should be submitted on my behalf

Currently we meet this requirement by generating a PDF and submitting it to the CentralMail API. This ticket will migrate that to the Benefits Intake Service `app/sidekiq/lighthouse/submit_benefits_intake_claim.rb`

This API has been implemented previously (see issue #69108) 

Because 4142 does not have a `SavedClaim` the service will need to be updated to support the 4142 use case

Documentation for the API: https://developer.va.gov/explore/api/benefits-intake/docs?version=current

**Comment by MadBomber** [comment] 2024-03-25 17:06
This statement "Because 4142 does not have a SavedClaim the service will need to be updated to support the 4142 use case" is too vague.  
- by "the service". I assume that the reference is to:  the Benefits Intake Service app/sidekiq/lighthouse/submit_benefits_intake_claim.rb
- by "support the 4142 use case" I assume that there must be a value for "SavedClaim" that is associated with the 4142 form.   What should that value be?

I also assume that the "old" path using central mail should be deactivated.  Where is that process located?

**Comment by MadBomber** [comment] 2024-03-25 17:53
The `master` branch does not contain this file:  app/sidekiq/lighthouse/submit_benefits_intake_claim.rb

**Comment by tblackwe** [comment] 2024-03-26 14:29
@SloopKoning 

from this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/69108
The `submit_beneits_intake_claim` code was merged in last week
https://github.com/department-of-veterans-affairs/vets-api/pull/15967/files

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/lighthouse/submit_benefits_intake_claim.rb

**Comment by SloopKoning** [comment] 2024-03-26 18:04
Thank you @tblackwe  I now see the file within my workstations `master` branch.  The root cause was that my working directory had become polluted with junk that demanded that I merged before `git` would updated.  I blew that mess away and cloned a new working directory.

I do not know what branch naming convention if any is being used.  I created a branch `issue_74810` off of master to work this problem.

**Comment by tblackwe** [comment] 2024-03-26 20:31
@SloopKoning in regards to your questions about `SavedClaim` and `the service`:

your assumption about 'the service' is correct. I am refering to `app/sidekiq/lighthouse/submit_benefits_intake_claim.rb`

4142 claims are created as a secondary form submission out of a 526 Claim. That means there is a 526 SavedClaim, and inside of the form json there is the information for the 4142. it is located at `claim.parsed_form['form4142']`
This means that `submit_beneits_intake_claim` will need to be updated to support 4142.
I have some ideas on how to accomplish this if you'd like them, but I intend to leave design/implementation details up to the engineer.

**Comment by MadBomber** [comment] 2024-03-27 18:29
@tblackwe   It looks to me like what we need is a `lighthouse` equivalent to this file `app/sidekiq/central_mail/submit_form4142_job.rb`

then a modification to `app/models/form526_submission.rb` to use the new lighthouse-based submission job instead of the centralMail job.

**Comment by SamStuckey** [comment] 2024-04-01 15:51
I think we should consider updating the CentralMail worker to be API agnostic, then adding the API switch over behind a flipper.  This would most closely model how we are doing other migrations of this sort.  The naming convention is unfortunate, but I think having the flipper in the worker (not the model) is best practice.  We can always update the name of the file / object later when the migration is complete.

**Comment by NB28VT** [comment] 2024-04-01 18:05
@SloopKoning had asked me to take a look at the above since Sam mentioned I had a lot of experience migrating over to the Lighthouse API (assuming he means the document upload migration that was started but is now blocked by the polling release [here](https://github.com/department-of-veterans-affairs/vets-api/pull/13835))

As far as the approach to take here I don't have any specific insight from my work unfortunately, as this is a different use case and the API is a different part of the Lighthouse system.

However, I agree with what @SamStuckey said above: we should branch within the worker. Although it's not ideal it's namespaced under `CentralMail`, it's still called `SubmitForm4142Job` and that is agnostic enough.

I would probably branch within the job [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/central_mail/submit_form4142_job.rb#L93), that's more or less what I did with the document jobs.

**Comment by SloopKoning** [comment] 2024-04-02 18:23
@tblackwe   I just pushed a checkpoint commit to the branch `issue_74810`. Still trying to figer out the protocol for lighthouse vs central mail.

**Comment by tblackwe** [comment] 2024-04-03 15:11
@SloopKoning can you create a draft PR on the `issue_74810` branch so we can track comments and questions there?

I am uncertain what you need on the lighthouse vs. central mail protocol

**Comment by tblackwe** [comment] 2024-04-03 15:11
@SloopKoning can you create a draft PR on the `issue_74810` branch so we can track comments and questions there?

I am uncertain what you need on the lighthouse vs. central mail protocol

**Comment by SloopKoning** [comment] 2024-04-23 14:04
@tblackwe   I created a [DRAFT PR. ](https://github.com/department-of-veterans-affairs/vets-api/pull/16457)

After being sick, out of town, trying to resolve a nasty SSH problem, I look at this PR and wonder "What was I doing?"

**Comment by SamStuckey** [comment] 2024-04-24 19:52
## PR:
[Dewayne and I paired today to create this alternate solution](https://github.com/department-of-veterans-affairs/vets-api/pull/16483)

### Notes:
The advantages of this solutions are:
1. simplicity
2. follows an established pattern of splitting workers and punting on namespace
3. address the issue of flipper change / job execution delays by flipping internally to the sidekiq job
4. leverages the best bits of the existing `app/sidekiq/lighthouse/submit_benefits_intake_claim.rb` code

## Next steps:
1. Get in a staging console, paste in this object, and start testing calls to the API.  This may require setting up a staging flipper OR just commenting the code to only run the bits we want to test.
2. Create a RSpec tests
3. Figure out rollout.  @tblackwe (and probably many other people) seem to have a firmer grasp than I on what is required to rollout flippable code

**Closed** 2024-05-08 15:50 UTC
Labels: needs refinement, disability-experience, DBEX-Carbs
