### ISSUE TITLE
[FE] My VA: Add error state for appointments

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#21846] opened 2021-03-22 16:41 UTC
## Background
When we cannot connect to the endpoint to fetch appointments or facilities, we need to show an AlertBox.

## Screenshots
![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/19832013-573c-46d5-8c32-ada37ba1cd46)

## Tasks
- [ ] Show the error when _either_ the va or cc appointments endpoint fails. Check if this also applies for facilities endpoint.
- [ ] Add test coverage

**Comment by tressaellen** [comment] 2021-04-01 20:40
Here's the updated copy :)

**We can’t access your appointment information**

We’re sorry. Something went wrong on our end, and we can’t access your appointment information. Please try again later or go to the appointments tool:

[Schedule and view your appointments]

<img width="1061" alt="Screen Shot 2021-04-01 at 4 39 19 PM" src="https://user-images.githubusercontent.com/58752772/113351467-64bada80-92e7-11eb-8e80-247d28d39efc.png">

**Comment by erikphansen** [comment] 2021-04-27 15:17
@ajakabcin @Samara-Strauss Can you validate the the Health Care section is still looking good in staging? Thanks!

**Comment by Samara-Strauss** [comment] 2021-04-27 15:54
Checked with users 226, 377 (messages), and Judy.Morrison (appointments), and everything still looks as expected.

**Comment by ajakabcin** [comment] 2021-04-28 14:42
I tested these as well and they look good. I did notice that for user 369, our test cases indicate they're supposed to be an example of someone who is NOT enrolled in health care, but on staging it looks like they are. Can we confirm if that's working as designed? 

If it's WAD then we'll need to update the test case documentation with another user example to show not enrolled. cc @tressaellen

**Comment by Samara-Strauss** [comment] 2021-04-28 15:35
You can use user 272 for a user who is NOT enrolled in health care and has not applied. [Here is a list of people who have not applied for health care](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-duplicate-healthcare-applications.md#users-not-enrolled-in-health-care-so-you-can-see-the-health-care-application). I had this info sitting in a DM from Kevin Mircovich, so I added it to Github so everyone can access it.

**Comment by tressaellen** [comment] 2021-04-28 15:40
I've updated the test case doc for Tze. :)

**Comment by ajakabcin** [comment] 2021-04-28 16:10
Looks great - thanks all! Closing

**Closed by ajakabcin** 2021-04-28 16:10 UTC
Labels: frontend, my-va-dashboard, planned-work, vsa-authenticated-exp
