### ISSUE TITLE
[Development] BDD: Remove Text Descriptions/Follow Up Questions for BDD

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14398] opened 2020-10-05 17:49 UTC
## Issue Description
Barry states that most of the text descriptions in condition detail screens will be determined or established during an exam - meaning they are not really applicable to SMs. We may want to skip this step entirely for BDD. Does it make a difference whether they are saying it was a disability that occurred during service, etc.

## Acceptance Criteria
- [x] Talk to Barry and see if this is truly the case - Barry has responded that he would like this
- [x] Remove the requirement for descriptions if we can skip them for BDD - Barry said we can avoid the question entirely as well as the question about when the disability "started" (in service, before, due to stay at hospital)
- [x] Update page flow with design without those questions for BDD.
- [ ] Remove the screen(s) when it is BDD
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment] 2020-10-06 17:10
I will be OOO on Friday when we meet with Barry and Co. - @luke-gcio I am also adding you to this ticket as a reminder to bring it up during that meeting so we can get this answered. :) Also would recommend moving this to next sprint since it looks like it's in the current sprint.

**Comment by barrettc81** [comment] 2020-10-13 20:37
We would prefer to remove this question entirely from the BDD flow since it is not necessary, because the SM is on active duty when they submit their BDD or BDD-Excluded claim.  We also don’t need the other questions that appear on that page asking the SM if the claimed condition is due to service, secondary to another claimed or service-connected condition, caused by exposure in service, etc. 

If you need to send language to EVSS it could simply state, “condition treated in service” or something like that.  If that is not possible, then could we do a list of possible options that the SM could select from such as the below?

•	Condition treated in service
•	Condition diagnosed in service
•	Condition caused by exposure in service 

However, again, we would prefer to remove these questions from the BDD flow.

**Comment by kevinstachura** [comment] 2020-10-15 14:02
Thanks @barrycooper727 ! These screens have been removed from the design; the user will simply go from the new condition addition screen straight to the 'additional disability benefits' screen as shown here:

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421401845_BDD_New_Conditions_9

**Comment by barrycooper727** [comment] 2020-10-15 14:23
@kevinstachura Thank you!!

**Comment by ndsprinkle** [comment] 2020-10-16 13:33
Beginning work on this today.

**Comment by ndsprinkle** [comment] 2020-10-19 19:48
After digging into this a bit, I have several thoughts that will ultimately require an internal engineering meeting with the team to see if any of them will pan out. From what I've learned, this change is possible, but in the current state of the form it will require so modification of logic. 

Right now, both our back end and the EVSS endpoint we submit to require a disability cause for each condition entered by the user. Additionally, depending on that cause, other fields are required. Because of this, there isn't an easy path forward where we simply remove the page that Kevin removed in his design as that page is where the user selects the disability cause along with supplying the other required fields. That being said, there are a couple options to handle this.

There are four different disability causes that the user can assign to a disability: new, secondary, worsened, and VA. One change of logic option for the BDD flow is that the front end simply defaults all disabilities to a cause of "new". If this is how we handle it, then we will also need to provide some default string for the "primary description", which is a field that is required if the cause is "new". This is probably the best solution as it will require no changes on the back end and everything should theoretically be accepted upstream. 

Another option with more changes required would be to adjust the back end schema to not require a cause or primary description if a BDD separation date is supplied. That way the front end could submit to the back end blank fields for those disabilities if in the BDD flow. If this is done, then it would be the responsibility of the back end to add a cause of new and primary description.

I suppose another option would be to talk to EVSS about lifting the requirement for a disability cause when in the BDD flow. The back end already supplies a boolean value to the EVSS endpoint when in the BDD flow, so I'm sure there is a way that EVSS could conditionally require the disability cause.

The last solution I thought of would be to still show the disability follow up page, but only allow "new" to be selected, either by removing all the other options or disabling them. That would still allow the user to enter a disability description, but if they choose not to then we could default the description to some string as proposed above. This would at least remove any confusion about the other disability cause options.

The only other question I had was around the disability cause of "worsened". Would it not be possible for this to be a cause? Or is it just that it doesn't really matter the cause in this situation? I guess my question also applies to "secondary" as that seems to potentially be possible for a BDD claimant too. Removing the "VA" cause makes perfect sense to me though.

**Comment by barrycooper727** [comment] 2020-10-19 22:20
@ndsprinkle @kevinstachura @luke-gcio I talked with Karla and the team.  We prefer to keep the, "What caused this service-connected disability?" screen.  However, please include the below pre-populated responses for the description box.  The SM may edit the response in the description box, but should not be required.  Please let me know if you have any questions or want to meet before Friday to discuss.  Thank you!

New:  My disability was caused by military service.
Secondary:  My disability was caused by another condition. 
Aggravation (Worsened):  My pre-existing disability was worsened by military service.
1151 (VA):  My disability was caused by an injury or event that happened when I was receiving VA care.

![What caused this SC disab Screenshot](https://user-images.githubusercontent.com/72471137/96517523-13d29080-1237-11eb-8f6d-d281b916f5eb.jpg)

**Comment by barrycooper727** [comment] 2020-10-20 16:48
I apologize I just received some edits to the pre-populated descriptions which i updated in the above comment and are also included below.

New:  This disability/symptom is related to my military service.
Secondary:   This disability/symptom was caused by another condition. 
Aggravation (Worsened):  This pre-existing disability/symptom was worsened by military service.
1151 (VA):  This disability/symptom was caused by an injury or event that happened while I was receiving VA care.

**Comment by kevinstachura** [comment] 2020-10-20 17:21
Hey @barrycooper727 ! Thanks for providing this feedback. I would love to chat about the radio button label changes - I'll see if we can get something set up before Friday. 

I'm currently looking through my UAT notes to see if we observed any trends on confusion around radio button labels, but I'm not finding it just yet...I also reached out to our team members to understand if that was a particular point of confusion (and if they had any notes to affirm that). I do have notes that indicate a trend around participants experiencing confusion with the text description field ("please briefly describe the injury.."). Do you or Karla have notes that indicate a trending difficulty in comprehending the radio button labels? I just want to make sure we are creating our solutions based upon the data we received from UAT or previous usability testing initiatives. 

I would definitely be interested in seeing if we could improve that text description field as it seemed to provide the most friction in the process (at least in my observations). But would be very interested in chatting further! Also am still trying to gain insights from the team to indicate this confusion so I'm still working on this.

I did find that [this ticket specifically calls out one of the labels](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14403), but I initially assumed the ticket was about general 526 content changes. I'll follow up with Luke and the team to see if we can get some concrete observational data around this. Thanks for bearing with me!

**Comment by barrycooper727** [comment] 2020-10-20 17:43
Hey @kevinstachura, I'm free to meet this week.  I noticed that both UAT participants had trouble figuring out what to write in the description box.  Both of the participants spent a long time looking in their STRs/medical records to find specifics on when the condition began in service and when they were treated.  That information is not necessary for BDD or BDD-Excluded claims.  It is more for Veterans who are filing their claim after discharge to help the claims processor locate the in-service event in the Veteran's STRs.  Since BDD and BDD-Excluded claims are submitted while the SM is on active duty, the claim itself is the in-service event.  Also, the BDD exams will be conducted while the SM is on active duty, which will include a diagnosis during active duty.  Therefore, we don't need an description of when the condition started in service or how it's related to service.  Karla and the BDD team also noticed all the UAT participants did not know what to write and prefer to have the response pre-populated.  Per Nick's above response, @ndsprinkle, it will be easier to implement these changes with a response in the description box.  Thus, why we decided to go with a pre-populated response with the option where the SM can change or add to the response but it's not required.  The instructions could indicate the pre-populated response is all that is necessary to submit their claim, but if they would like to add more information they can.  However, it is not required.  Let me know when you would like to meet and if you need any further information.

**Comment by kevinstachura** [comment] 2020-10-21 15:03
Hey @barrycooper727 - Ah, I think I may have misunderstood your 'ask' here...it seemed to me that you were asking to change the radio button label text, but instead it looks like you were mapping the different radio button select options to pre-populating something in the description field. Therefore:

- IF user selects 'My disability was caused by an injury or exposure during my military service' THEN the description field is pre-populated with 'This disability/symptom is related to my military service.'
- IF user selects 'My disability was caused by another service-connected disability that I already have (for example, I have a limp that causes lower back problems)' THEN the description field is pre-populated with 'This disability/symptom was caused by another condition.'
- IF user selects 'My disability or condition existed before I served in the military, but it got worse because of my military service' THEN the description field is pre-populated with 'This pre-existing disability/symptom was worsened by military service.'
- IF user selects 'My disability was caused by an injury or event that happened while I was receiving VA care' THEN the description field is pre-populated with 'This disability/symptom was caused by an injury or event that happened while I was receiving VA care.'

Let me know if this understanding is correct. I'd still like to ask - would you be okay with exploring other options? I still worry about potential confusion with this pattern. If there is no understanding that selecting a radio button changes what text ends up in a visually separate box, then it may serve to confuse users (also might wonder 'should I change this to be more specific? Will it hurt my chances if I don't?'). It may be as simple as changing the description field label to "If you would like to, you can briefly describe the injury or exposure that caused your service-connected disability. This field is optional for active service members." Was planning on chatting with Christian about this today to see if we can come up with some potential solutions. Let me know, Barry - thanks!

**Comment by barrycooper727** [comment] 2020-10-21 17:00
Hey @kevinstachura yes, exactly that is our 'ask'!  Yes, we are open to exploring more options.  We want to ensure that this screen doesn't cause any confusion for the SM.  As I mentioned, we don't need a description since they are on active duty.  However, as Nick mentioned above 2 days ago, "Right now, both our back end and the EVSS endpoint we submit to require a disability cause for each condition entered by the user."  Therefore, we tried to come up with the easiest solution.  Our goal is that the SM won't worry at all about entering anything into the description box.

Is it possible for the back end system (not sure what the exact term is for the system) could just send the pre-populated causes i.e. IF user selects 'My disability was caused by an injury or exposure during my military service' THEN the "cause" of 'This disability/symptom is related to my military service.' is sent to EVSS endpoint.  Then, the SM wouldn't see the description box at all?  I would assume that would take more effort and delay the phased rollout?  Luke just sent a meeting invite for 4pm EDT today that I assume is about this issue? @luke-gcio

**Comment by kevinstachura** [comment] 2020-10-22 15:16
Good morning @barrycooper727 ! Thanks so much for meeting with us yesterday. As Nick and I were going through some of the interaction states, we encountered a couple conditional fields/boxes for when a SM selects 'existing condition worsened' as shown here:

<img width="559" alt="Screen Shot 2020-10-22 at 10 11 19 AM" src="https://user-images.githubusercontent.com/54544300/96891125-558d5200-1456-11eb-872e-69026448d74b.png">

Questions:

**1. To confirm: Do we _need_ either of the boxes?**


**2. What do we want to say for the first box that says 'please briefly describe the injury...' (to send to EVSS)?**

_NOTE: For box 1, the limit is 50 characters. I might suggest we go with 'This disability was worsened by military service.' which is 49 characters long._


**3. What do we want to say for the second box that says 'please tell us how the disability affected you...' (to send to EVSS)?**

_NOTE: For box 2, the character limit is 350 characters._


Any guidance you could provide would be very helpful. Thank you, Barry!

**Comment by barrycooper727** [comment] 2020-10-22 17:31
@kevinstachura and @ndsprinkle please see below:

1. No we don't need those boxes since we never ask SMs for aggravation info.  We also don't need to ask the SMs for any descriptions for any of the radio buttons including the last one, "My disability was caused by an injury or event that happened when I was receiving VA care."

2. That's fine, "This disability was worsened by military service".  For the last radio button, "My disability was caused by an injury or event that happened when I was receiving VA care."  You can send to EVSS, "Further information regarding the VA care incident will be gathered by the examiner" or anything like that.

3. You can put for the 2nd aggravation box, "If the condition is found on the entrance exam or in STRs prior to service, order aggravation medical opinion."  If that is too many characters, you can use, "will be determined by examiner, order aggravation medical opinion"

Lastly, the SM won't see any of these descriptions boxes for any of the radio buttons right?  You all will just send this info to EVSS, correct?

**Comment by kevinstachura** [comment] 2020-10-22 18:31
Thanks @barrycooper727 ! That is correct - Nick has already removed the description boxes for each of those radio button options. This is simply the "default" text we would be sending to EVSS because it requires something to be sent, but it will be unbeknownst to the user (as they won't be seeing the description boxes). To be more specific:

**1. If a user chooses the first radio button option:**

<img width="579" alt="Screen Shot 2020-10-22 at 2 06 06 PM" src="https://user-images.githubusercontent.com/54544300/96912700-bfb2f080-1470-11eb-9943-7340e6cf7af3.png">

This description box will not show.

**2. If a user chooses the second radio button option:**

<img width="573" alt="Screen Shot 2020-10-22 at 2 06 00 PM" src="https://user-images.githubusercontent.com/54544300/96912888-f983f700-1470-11eb-96af-b32bdd2e4d6d.png">

They will still see the dropdown box that says "please choose the disability that caused..." but will not see the description box below it that asks "please briefly describe how the disability..."

**3. If a user chooses the third radio button option:**

<img width="559" alt="Screen Shot 2020-10-22 at 10 11 19 AM" src="https://user-images.githubusercontent.com/54544300/96913170-48319100-1471-11eb-8881-fe609b4bb7ff.png">

They will see neither of these boxes.

**3. If a user chooses the fourth radio button option:**

<img width="548" alt="Screen Shot 2020-10-22 at 2 19 12 PM" src="https://user-images.githubusercontent.com/54544300/96913432-9cd50c00-1471-11eb-9969-19a4c65b5757.png">

They will only see the bottom 2 boxes, asking "when" and "where". They will not see the first "Please briefly describe the injury or event..." box.

Please let us know if this is how you intended it to work! Thanks Barry.

**Closed** 2020-10-26 11:24 UTC
Labels: BDD, design, development, frontend, vsa-benefits

**Comment by barrycooper727** [comment] 2020-10-27 15:57
I'm sorry I'm late on replying.  I was getting Karla's concurrence.  Yes, that is exactly how we intended it to work.  Thank you all!  I appreciate it!
