### ISSUE TITLE
Fix deployment of documentation site

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4217] opened 2019-12-12 22:12 UTC
# User Story

As an engineer, I need to be able to view up to date FE engineering docs, so that I can build successful products on and in support of VA.gov. 

# Details/Notes

The [Client Application Documentation site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/) cannot currently be updated because the deployment process is broken. 

In December 2019, @ncksllvn tried to fix this: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/196

**Comment by meganhkelley** [comment] 2020-01-23 19:55
Per Nick in Slack: 
I figured out the bad config file in that PR, but evidently the plugin we use for processing Markdown chokes on <hr> elements 

I couldn’t figure out how to strip out the <hr> elements

**Comment by erikphansen** [comment] 2020-01-23 22:07
Funny you should mention it choking on `<hr>` elements and other tags that aren't self-closing. I have a PR to fix that https://github.com/department-of-veterans-affairs/va.gov-team/pull/5089

**Comment by ncksllvn** [comment] 2020-01-23 22:26
@erikphansen Thank you for doing that! Once that's merged, I think you can restart https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/196, and then it should be mergeable. 

Long term, we'll need some sort of sanitizing though on those `<hr>` or a more robust MDX processor so that our build doesn't just break anytime some adds an `<hr>`.

**Comment by LinnJS** [comment] 2020-01-29 21:22
Just throwing another idea in the hat, I am not sure how much value a <hr> might provide but we could try adding a custom lint rule or something like that along with a commit hook and request devs to remove it before push up or something like that... just an idea to skirt around it in the meantime.

**Comment by LinnJS** [comment] 2020-02-04 17:05
So after digging in more over the weekend it looks like `gatsby-mdx` was deprecated in-favor of `gatsby-plugin-mdx` this is probably one of the largest issues with the brittle build at the moment.

**Comment by billfienberg** [comment] 2020-03-02 18:27
What are the stages of a build in the `veteran-facing-services-tools` repo?

1. [`setup`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/Jenkinsfile#L14)
2.  [`test, and build`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/Jenkinsfile#L21)
    - In the past, linting was included in the `test, and build` stage
3. [`deploy`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/Jenkinsfile#L47)

How do we define a successful build for the `veteran-facing-services-tools` repo?
- All three of the stages succeed

What was the result of the most recent build?
- The most [recent build failed on 2020-02-19 during the `deploy` stage](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fveteran-facing-services-tools/detail/master/182/).

When was the last successful build?

**Comment by billfienberg** [comment] 2020-03-04 15:08
PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/215

___

Before solving the root problem, I had to solve two other problems. 

1. There was a bad glob used in the `packages` array in the `lerna.json` config file.
2. There was a unit test that was failing because a component was changed to render a `<button>` instead of an `<a>`. 

### Lerna and `packages`

[`Lerna`](https://github.com/lerna/lerna) repos typically have a root `package.json` and a `packages` folder. 

- [What does a Lerna repo look like?](https://github.com/lerna/lerna#what-does-a-lerna-repo-look-like)

The [`lerna` config file](https://github.com/lerna/lerna#lernajson) should have a `packages` key with a value that is an array of globs to use as package locations.

In https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/43ffd6bf579559543369c16b3e250c0f838136e2, a new package was added, and the `packages` array was changed from `["packages/*"]` to `["packages/documentation/*", "packages/formation/*", "packages/formation-react/*", "packages/vagov-eslint/*"]`. 

The `name` key inside the child `package.json`'s matched the folder name for 3/4 of the packages. 

```
// packages/formation-react/package.json
{ ..., name: "@department-of-veterans-affairs/formation-react" }

// packages/formation/package.json
{ ..., name: "@department-of-veterans-affairs/formation-react" }

// packages/vagov-eslint/package.json
{ ..., name: "vagov-eslint" }
```

However, the `name` key and folder name for one package didn't match. 
```
// packages/documentation/package.json
{ ..., name: "vagov-documentation" }
```

The `"packages/documentation/*"` failed to match the `"vagov-documentation"` package, and produced the following error in the build:

> `lerna ERR! EFILTER No packages remain after filtering [ 'vagov-documentation' ]`

After changing the glob from `"packages/documentation/*"` to `"packages/documentation"`, `lerna` started finding the `'vagov-documentation'` package again. 

```
- "packages/documentation/*"
+ "packages/documentation"
```

### Failing unit test

In https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/855b6227d118d7ef3c3a0f3edbf6b3bbc24af827, the component was changed to render a `<button>` instead of an `<a>`. However, the corresponding unit test was never updated. 

I updated that failing unit test, and then the `test` step of the `test, and build` phase of the Jenkins pipeline started passing. 

```
- .find('a')
+ .find('button')
```

### Root cause

The [Gatsby site currently uses the `gatsby-source-git`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/gatsby-config.js#L13) [plugin](https://www.gatsbyjs.org/packages/gatsby-source-git/) to pull `*.md` files from the [`platform/working-with-vsp` sub-tree](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp) of the [`va.gov-team` repo](https://github.com/department-of-veterans-affairs/va.gov-team/). 

When the build Gatsby build was trying to sync the `*.md` files from the `va.gov-team` repo, it was failing, with the following error:

```
error "gatsby-mdx" threw an error while running the onCreateNode lifecycle 
unknown: Expected corresponding JSX closing tag for <MDXTag>
```

I wasn't able to find where the error was coming from in the source code inside the `documentation` package. So then I checked the built code in the `public` folder, and I found something that looked related. 

Then I realized that the error wasn't coming from source code inside the `veteran-facing-services-tools` repo, so I started checking other repos. 

Once I checked the `va.gov-team` repo, I found a [file with invalid HTML](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e56c9b374a9cdd24bc7d50f993bafbf36ce4eda9/platform/working-with-vsp/policies-work-norms/how-to-write-your-slos.md). 

I fixed the HTML, and re-ran the CI pipeline for the `veteran-facing-services-tools` repo, and the error went away. 

#### ⚠️ Invalid HTML in the `va.gov-team` repo can break the `veteran-facing-services-tools` build ⚠️

**Closed** 2020-03-04 15:17 UTC
Labels: content-ia-team, documentation, tools-fe
