### ISSUE TITLE
<Household Information Section Content Review> from <1010Team>

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#52920] opened 2023-02-01 16:56 UTC
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
Mid to end of May
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Household%20section%20redesign#measuring-success)
- [Link to or attach user flows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/AE225764-D5BB-4CE6-9577-38E8F570392B/canvas)
- [Link to prototype or mockups](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- [Link to recent research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Findings.md)
- [Link to any epics/issues that may be helpful](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41403)
- [Collaboration Cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47766)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: End of April
- Estimated staging review date: End of March
- Content and IA work needed by: Beginning of March

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 10-10 Health Apps
-	OCTO-DE product owner: Patrick Bateman
-	Product manager: Heather Justice
-	Designer: Jessica Stump / Nick Osmanski
-	FE engineer: Matt Long
-	Product/team Slack channel: 1010-health-apps

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by jessicastump** [comment] 2023-02-01 16:58
@RLHecht 
cc @DanielleThierryUSDSVA 
Opening this ticket per our discussion at the last week's health content hours. We will use this space so we can work through the content review async as needed. 
Will refine this ticket and complete next steps after the next 1010 team's backlog refinement meeting.

**Comment by jessicastump** [comment] 2023-02-01 19:24
[Link to old running content ticket that will be closing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25350)

**Comment by jessicastump** [comment] 2023-02-02 19:31
For content review/updates needed, the following sections are in the household information ask:
1. Financial disclosure
2. Spouse information
3. Dependents
4. Income
5. Deductibles

Content/Sketch file for **Financial Disclosure** section
- [Financial disclosure page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/KjRV9g/a/ygvYdEq/)
- [Financial disclosure select](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Omgq0Kq#Comment)

In the Sketch file comments are findings and quotes from the recent research study. 

@DanielleThierryUSDSVA Please let me know if there is another way you would like me to add this information here and if it would be useful at all to see what is in production. I will add additional comments for the remaining sections.

**Comment by jessicastump** [comment] 2023-02-02 22:30
Section 2. Spouse Information:

- [Marital Status](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxdZeEe)
- [Spouse Information](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/qe30p0V)
- [Spouse live with you / same address](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/9Pzj9AP)
- [Spouse residence conditional](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/AxmGM4m)
- [Spouse address conditional](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/g0eDkkx)

**Comment by jessicastump** [comment] 2023-02-02 23:08
Section 3. Dependents:

- [Dependents 1st page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kaJ9m2R)
- [Dependent information](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/1Kd3avO)
- [Dependent additional info](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgwqgl7)
- [Dependent didn't live with you conditional page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DPgxQm2)
- [Dependent list](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4a1LYqx)
- [Dependent - cancel edit modal](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/09wJL2j)
- [Dependent - remove modal](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/m145KEg)

**Comment by jessicastump** [comment] 2023-02-02 23:14
Section 4: Income:

- [Income main page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L0yqdk5)
- [Spouse income conditional](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygRLq0E)
- [Dependent income conditional](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DP7M5Rn)

**Comment by jessicastump** [comment] 2023-02-02 23:14
Section 5: Deductibles

- [Deductibles page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/8yKwlVO)

**Comment by aliyahblackmore** [comment] 2023-02-22 01:29
Hi @jessicastump - 

I plan to start my review of these screens this week and have one question so far: 

Has Brian taken a look at these screens from an accessibility perspective? 

Looking forward to collaborating on this

**Comment by jessicastump** [comment] 2023-02-22 15:59
Hi @aliyahblackmore - to get to here, this work has gone through the [Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47766) and there was an initial accessibility review at midpoint review [(feedback ticket here)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50068), but I think it would be great to plan for another review as we go through this process. Looking forward to collaborating too and let me know if you think of any other questions or want to meet and chat at all!

**Comment by aliyahblackmore** [comment] 2023-02-22 19:07
Hi @jessicastump - thanks so much for linking the feedback ticket from the midpoint review! I'll take a look at this while I'm doing my review, gather questions, and consider where accessibility can be looped in (i.e. to do a higher level review).

FYSA @DanielleThierryUSDSVA

**Comment by jessicastump** [comment] 2023-03-01 21:36
Adding a [link to the recent research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research/research-findings.md) from the baseline study on the 10-10EZ for reference. 

For impact to this content: there were some mentions around clarification to the IRS process/verification (added comments to Sketch file too) when that was brought up on the financial disclosure or income pages.

**Comment by aliyahblackmore** [comment] 2023-03-01 21:49
Thanks so much for adding this @jessicastump!

I'll take a closer look at this tomorrow and include some additional comments in my review document.

Looking forward to meeting on Friday.

FYSA @DanielleThierryUSDSVA

**Comment by jessicastump** [comment] 2023-03-13 20:11
@aliyahblackmore Here are two revised onboarding page changes to discuss during our next content sync:

Option A: Pages per content edits
[Page 1](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/g1QzZzr#Comment) - Onboarding Intro
Page 2 - Question / Selection
[Page 2 with no alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/8Vx2p2w#Comment) - Shows when "no" is selected before clicking continue. [Version with expandable alert component](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/GoO2xPY#Comment). 
[Page 3](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/elrjDRz#Comment) - Financial Docs 

Option B: Flow with question/selection on first page
[Page 1](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/3o5ve3j#Comment) - Onboarding intro & question
[Page 1 with no alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/mPoak0z#Comment) - Shows when "no" is selected, using content from page 2 in option A
[Page 2](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DEov19q#Comment) - Financial Docs

**Comment by jessicastump** [comment] 2023-03-17 20:18
A recap of our bi-weekly meeting today, @aliyahblackmore @DanielleThierryUSDSVA @davidakennedy 

Below are links to the revised onboarding page flow including the conditional pages for both answering no or yes:

- [Page 1 - Onboarding content](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/g1QzZzr)
- [Page 2 - Question](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bL0P2Vj)
- [Page 3a - Conditional if answered NO](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/WdR1ymk)
- [Page 3b - Conditional if answered YES](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/3o5RQ4m)

**Comment by longmd** [comment] 2023-03-20 18:14
Can I ask about the formatting for the question page... Why are we asking the question in the form title location, instead of asking it on the field itself. We don't do that for any other questions. I think for visual consistency, it should do it all one way, or all the other?

**Comment by jessicastump** [comment] 2023-03-20 18:38
@longmd  Thanks for calling this out! As content was revised/removed, this is what remained, but it is inconsistent with the rest of the form visually. I think for now, removing the question headline "Do you want to share your household financial information?" and only ask on the radio title field would be the route to go. I will update the Sketch links. 

...I wonder if down the line adding a headline question/title could help on the accessibility side. Knowing overall design system changes with the h1/progress bar could be a ways out, this could provide a more accessible solution in the meantime. cc @davidakennedy

**Comment by davidakennedy** [comment] 2023-03-27 16:50
Yeah, possibly! Josh has some potential [interim solutions laid out in this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1538). The one we could control would be adding h3s to the pages. But before we do that, I'd love to get a sense as to where this sits for the design system team.

**Comment by aliyahblackmore** [comment] 2023-03-31 16:17
Hey @jessicastump - ahead of our meeting today, **just tracking a few updates here:** 

-A few of the screens in the dependents section have comments with feedback on content. 
- We have a suggestions based on your response to our questions on the spouse information section - we can review those and I can post the feedback after our call!

**Comment by aliyahblackmore** [comment] 2023-03-31 19:07
**Just tracking some updates here after our call:** 

- As mentioned, after our call I dropped some feedback for the spouse info section in the sketch screens.
- We chatted about my questions about the Month and Day drop down. Action item for @davidakennedy is to double check with design system team. If this changes at all, this will need to be consistent across all screens. 
- Danielle and I will connect to review my suggestions on the remaining screens and I'll post those in sketch.

**Comment by jessicastump** [comment] 2023-04-14 20:06
Hi @aliyahblackmore -

**Comment by jessicastump** [comment] 2023-04-24 21:47
@aliyahblackmore - Just adding a note that the [Sketch QA page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas) is updated with all changes minus the income and deductible pages.

**Comment by jessicastump** [comment] 2023-05-05 21:23
Circling back to the the latest comments in the [Sketch QA file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas). A couple are marked as resolved, but the remaining comments and any other changes to the income and deductible pages I would like to list here to keep organized :)

Just to note, we are getting ready to kick-off the first round of QA on this in development and content changes received to date were captured and made but anything else and the income/deductible pages will be captured in a new ticket for development to complete post-QA.

Remaining content updates to note: 

#### Page - Dependent’s additional information

Questions re-worded: 
NEW: If your dependent is between 18 and 23 years old, were they enrolled as a full time student in 2022?
CURRENT: If your dependent is between 18 and 23 years of age, did they attend school during the last calendar year?

NEW: Enter the total amount of money your dependent paid for college, vocational rehabilitation, or training (like tuition, book, or supplies)
CURRENT: Expenses your dependent paid for college, vocational rehabilitation, or training (e.g., tuition, books, materials)


NEW: Did your dependent live with you in 2022?
OLD: Did your dependent live with you last year?

NEW: Did your dependent earn income in 2022?
OLD: Did your dependent earn income last year?



#### Page - Dependent’s support


NEW: Financial support for [dependent's name]
OLD: [First Last]’s support

NEW: If your dependent didn’t live with you last year, did you provide financial support?
OLD: If your dependent didn’t live with you last year, did you provide support?

OLD: Hint text
NEW: Additional info component
Label: What we consider financial support
Content: Please count all support contributions even if they weren’t paid in regular and set amounts. Support can include tuition or medical bill payments.

**Comment by aliyahblackmore** [comment] 2023-05-05 22:11
Hi @jessicastump - thanks so much for these updates. 

Tagging @DanielleThierryUSDSVA for awareness while I'm out!

Thanks for tracking the suggested changes here.

Just to clarify, the content that you all are moving to QA in development -  is that user testing or an internal QA by development?

Just want to be sure in case there is any sort of conversation guide or research plan we'd need to review - if this is user testing.

**Comment by jessicastump** [comment] 2023-05-12 20:13
Just tracking additional content changes/discussions here after meeting:

**Dependent's support page**

New: 
[headline] Financial support for [dependent's name]
[label] If your dependent didn’t live with you last year, did you provide financial support?

[additional info component] 
What we consider financial support 
  
We consider any payments, even if they aren’t regular or the same amount, to be financial support. 
This includes payments for these types of expenses: 
- Tuition or medical bills 
- Monthly child or spousal support 
- One time payment financial support

**Spouse's support page**
- Confirm with SMEs the list used for dependents applies here as well or if adjustments are needed

**Income content**
Discussed using additional info component for list of examples via a bulleted list so it is easy to scan. Will surface the most common examples outside of the additional info components so they are not hidden.

**Comment by aliyahblackmore** [comment] 2023-05-15 14:30
Hi @jessicastump - Yes, your above reply answers my questions - thanks so much for clarifying!

**Comment by jessicastump** [comment] 2023-05-17 16:56
A summary of changes discussed during bi-weekly content meeting 5/12:
- Updates to dependents financial support page, [summarized here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959#issuecomment-1546242340) and [design file updated](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/mPPqJ2L)
- [Veteran income screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/3oKK9zd) (and [add info closed version](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4ognGMJ)), incorporated the content changes we chatted through last Friday into that design.

**Comment by aliyahblackmore** [comment] 2023-05-26 19:28
**Tracking some updates here following our meeting:** 

- As discussed, I updated a comment on the [deductible expenses screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/JA88E27) to reflect that we'd want to remove the Note and add in this content from [the financial information screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L40m0nd) - "These deductible expenses will lower the amount of money we count as your income"

- I just sent a message to our copy editor to get looped in on content she has for the "certify" check box, from other forms. I'll update content once she gets back to me.

- Since our content suggestions adjusted income information applicants will need, I think we'd want to track the update on this [Introduction screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ELo9WzO). Right now there's just gross annual income and deductibles - but I think we'd include net and other income here as well - similar to content on [this screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L40m0nd). Flagged this your Jessica and Danielle.

- Once we have answers from SMEs on a few content questions - I can adjust those pieces of accordingly.

**Comment by jessicastump** [comment] 2023-05-26 20:09
Thank you @aliyahblackmore! 
The [Sketch QA](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas) page and the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959) have been updated with the content updates. We are just pending some answers from SMEs.
We will track the certify agreement changes with a new ticket on the 1010 team side and I will check with the team during planning if we want to loop in the introduction page as part of the household optimization collab cycle effort or have a new ticket :)

**Comment by jessicastump** [comment] 2023-06-28 17:53
Hi @aliyahblackmore (cc @DanielleThierryUSDSVA) the content updates that we have been working through for the household financial section are all [in staging](https://staging.va.gov/health-care/apply/application/introduction) and reflected in the [Sketch file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas). I added comments/replies to the various notes for outstanding SME questions, none of the answers we received need content changes.
This work will be going through Staging Review soon (cc @hdjustice)

**Comment by aliyahblackmore** [comment] 2023-06-28 18:06
Hi @jessicastump thanks for this update! I'll take a look at those comments and content that's in staging this week. 

Do you all have the staging review date?

**Comment by hdjustice** [comment] 2023-06-28 18:41
I am working on scheduling that now, probably 2 weeks out.  thanks @aliyahblackmore

**Comment by aliyahblackmore** [comment] 2023-06-28 21:28
Thanks for the update @hdjustice ! Once you have the date, could you let me know? 

I have some open time on Friday, so I'll take a look at content in staging. 

@jessicastump FYSA

**Comment by hdjustice** [comment] 2023-06-29 19:25
We are scheduled for Staging Review on 7/13 at 1:30p ET.

**Comment by aliyahblackmore** [comment] 2023-06-29 19:29
Thanks for confirming @hdjustice ! 

I have heads down time set aside for tomorrow to go through the content in staging, just to confirm that all of the content suggestions are accurately reflected.

@jessicastump I'll send you a message if there are any additional content updates I catch!

**Comment by jessicastump** [comment] 2023-06-29 19:39
Thank you @aliyahblackmore - we have gone through the Sketch QA page/comments too (of course :)  and please let us know if anything was missed!

**Comment by aliyahblackmore** [comment] 2023-06-30 20:58
**Staging adjustments:** 

Using this comment to track any changes to content while I review in staging!

1. https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/aMgPxyA
Comment on the Need help? footer

2. https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/GomvmqL
Change "provide" to "share." And adjust "Confirm" content.

**Comment by aliyahblackmore** [comment] 2023-07-07 19:19
**Tracking notes here post our bi-weekly meeting:** 

- The footer, confirmation screen, and drop down list content/questions will be addressed in a future ticket/work. We documented this on the corresponding sketch screens. And there are tickets that'll be opened for these things.
- All of the other content adjustments on the sketch screens will be added/changes and then engineers will get those through to staging, in time for the staging review artifact deadline.
- Re: the artifact deadline - it's my understanding that the content in staging needs to be ready for the governance folks 4 business days before the staging review (so I think EOD today or Monday morning). 

cc: @jessicastump

**Comment by aliyahblackmore** [comment] 2023-07-08 01:11
Tracking an update here that all changes have been reviewed by me and I updated the design, FE ticket! 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/61632#issuecomment-1626403018

**Comment by jessicastump** [comment] 2023-07-10 21:04
@aliyahblackmore Ticket 61632 is completed and closed. All content must/should updates are in staging and the Sketch file is also updated but comments have been left unresolved for now.

**Comment by aliyahblackmore** [comment] 2023-07-18 21:20
Hi @jessicastump - now that staging review is done, should we leave this ticket open to continue to track some of the additional changes we'll explore in the future or should we close this out?

**Comment by jessicastump** [comment] 2023-07-19 19:08
Hi @aliyahblackmore - I think with staging review we are good to close...but maybe confirm in the collab cycle ticket.  We have opened other tickets on the 1010 board for the future items mentioned and we can discuss during a bi-weekly content sync next steps/other tickets needed.

**Comment by aliyahblackmore** [comment] 2023-07-21 19:19
Hi @jessicastump - just tracking some of the items we discussed in our bi weekly call here for the household section: 

- Phased launch to start next week 
- [Confirm screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/GomvmqL?annotation=7bddc1d5-4a4d-4845-8163-16f0fb6eee01#Comment) – we chatted more about this not being a destructive action but more so a fork in the road in terms of the direction user would like to go. We confirmed we'll leave the content as is here. 
- Footer change - "form/application" was adjusted to "application"
- Drop down on dependent screen - Heather is in further conversation about getting this updated and confirming this adjustment won't impact anything on the back end. 1010 team has the content updates for this in the sketch screen.

**Comment by jessicastump** [comment] 2023-07-21 19:39
Hi - follow up additional notes below and I think we can close this ticket officially :) 

- [Confirm screen ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61779) As we chatted about, the "." needs to be removed on the current production short form confirmation screen. I noted that in this ticket but otherwise this can be closed.
- [Footer change ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61574) in progress here, ready for development.
- [Drop-down dependent relationship options](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61780)

**Comment by aliyahblackmore** [comment] 2023-07-25 14:49
Amazing @jessicastump  - thank you all so much for the collaboration on this work!

I'll check back in on any updates on the the drop-down dependent options ticket. 

@coforma-terry you can close out this ticket!

**Closed** 2023-07-25 15:55 UTC
Labels: 1010-team, 1010-ez, sitewide content, sitewide CAIA-product support, household-info-optimization, sitewide CAIA
