### ISSUE TITLE
Build burials landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#77992] opened 2024-03-08 22:27 UTC
## Issue description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Burials: http://preview-prod.vfs.va.gov/preview?nodeId=65328

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [x] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The landing page is live on VA.gov

**Comment by laurwill** [comment] 2024-05-19 23:19
@d-beyer please go ahead and build out this burials subhub landing page as well. Thank you!

**Comment by d-beyer** [comment] 2024-05-29 15:55
@laurwill -- I've finished drafting this page. It's ready for your review.

**Comment by laurwill** [comment] 2024-06-04 03:32
Thanks Derek! I was confused by the blurb about bereavement counseling because it didn't mention counseling after the death of a Veteran, which is definitely included. And then I saw you pulled it from the live burials hub page! So we should fix that.

@strelichl could you open a backlog ticket to fix the blurb about bereavement counseling in the main burials hub? Should we track fixes like this that surface as part of FMB migration in this epic?

**Comment by saratorres2** [comment] 2024-06-11 16:00
@laurwill Copy edits made! One follow-up question that I didn't capture in my notes: Should pre-need eligibility blurb include "service members"?

**Open queries** captured in [backlog ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85640#issuecomment-2161101966): 

- Pre-need eligibility - We'll need to update the pre-need eligibility on the subhub page to include another category (surviving parents of a service member) when we update it on the linked page.
- Capturing that we're leaving "Veterans burial allowance" when referring to the benefit (perhaps add to style guide?), but we use apostrophe for "a Veteran's burial or grave."
- Look into updating both blurbs under "Find a Veteran's grave" to include territorial cemeteries.

**Comment by laurwill** [comment] 2024-06-12 18:09
@d-beyer new related links to add, but please wait till Danielle is finished updating this page and it's unlocked in Drupal
Mental health care
VA home loan programs for surviving spouses
Beneficiary financial counseling and online will prep
Survivors compensation benefits

**Comment by d-beyer** [comment] 2024-06-13 20:37
@laurwill I added the related links. I went by what's currently in the Mural since I know there have been some updates.

**Comment by d-beyer** [comment] 2024-06-14 15:35
@saratorres2 I've added the related links and they're ready for copyedit. Screenshot attached.
![Burial-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/d167e2c8-8566-478c-9ebc-21f4107d0f39)

**Comment by saratorres2** [comment] 2024-06-14 18:50
@laurwill Copy edits of new related links section complete.

**Comment by kristinoletmuskat** [comment] 2024-07-10 19:15
Confirmed live in prod, closing this out.

**Closed by kristinoletmuskat** 2024-07-10 19:15 UTC
Labels: sitewide content, sitewide IA, sitewide CAIA
