### ISSUE TITLE
Analytics Reporting Request for [Facilities]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14969] opened 2020-10-16 19:35 UTC
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
- Facilities team
    
What team/project is this work for?
- Facilities Team Map enhancements work, beginning with Phase 1- Limit searches to 250 miles)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._

What timeframes are you looking to analyze (e.g. before vs. after)? 
- October 8 to date (since data layer implemented in Prod) to establish baselines, validate bets 
- 1 month post-release to assess impact

## Which Product Questions are you trying to answer?

Primary goals for the first phase of our map enhancements:

- Remove the undesirable auto search behavior
- Create accessible ways to give Veterans control over panning/zooming the search area/results

### Question 1
Our objectives for this work: 
1. Decrease the total number of search requests (in general) which are impacted by auto-firing of search due to map/zoom interaction  
2. Decrease the total number of Community care search requests (within same care type) which are impacted by auto-firing of search due to map/zoom interaction 

**What is our baseline metric?** 
**What percentage of the time does this behavior occur?**
**Is this behavior more frequent for one facility type than another?** 

There are several scenarios in which this auto-search occurs:
_For any facility type_
1. if the Veteran pans map after results are delivered
2. if the Veteran zooms map after results are delivered. 

_The following scenario happens more often when facility type = Community providers and service type = highly specialized or niche care_
  3. Map continues to zoom out and autosearch until a match is found or the search times out.

<details>
<summary> Demo of all three scenarios </summary>

https://www.loom.com/share/f1b646d3460647dc8a704e179514c73e

</details>

---

### Question 2
The initial bounding box uses an 80 mile default radius. We're considering an iteration from a standard "one-size-fits-all" default to a facility-type default and would like some analytics to guide this decision-making. 

**What is the average closest result by facility type?**
- VA health
- VA benefits
- Vet Center
- VA cemeteries
- Urgent care (all urgent care)
- Urgent care + VA urgent care
- Urgent care + Community providers (in VA's network)
- Community providers (in VA's network)
- Community pharmacies (in VA's network)

**Density of search results** (We assume this is related to facility type in part, but there is also likely a geographic component -> how can we assess this?)
**What is the average number of results by facility type?**
- VA health
- VA benefits
- Vet Center
- VA cemeteries
- Urgent care (all urgent care)
- Urgent care + VA urgent care
- Urgent care + Community providers (in VA's network)
- Community providers (in VA's network)
- Community pharmacies (in VA's network)

**Average miles panned/zoomed (for Veteran initiated panning/zooming...to exclude the autosearch mentioned above).** 

**What is the average number of miles a Veteran pans the map after searching? (across all facility types)**
**What is the average change in zoom initiated by a Veteran after searching? (across all facility types)**
**How does the average differ by facility type searched?**
**What percent of searches result in the closest location being farther than 250 miles away?**

 

---

### Question 3
To support decision making for mobile design: 
**How often does a Veteran view the map tab in mobile?** (by facility type so we can see if it is more pertinent for one search type over another)

---

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment] 2020-11-24 16:25
@mmiddaugh -

I wanted to get some movement on this before EOM and transition some of this over to our new data engineer @JasonTheBearded.

----------

> Decrease the total number of search requests (in general) which are impacted by auto-firing of search due to map/zoom interaction

So I believe you already made the decision to fix the auto-firing issue, but if you're looking for historical data on this behavior, we can try to query it in our GA data.

You can see the rapid fire zoom events when someone does this search:

<table><tr><td width="66%">
<img src="https://user-images.githubusercontent.com/62304138/100116402-b2a76980-2e41-11eb-8c70-f99cbe97d026.png" /></td><td><img src="https://user-images.githubusercontent.com/62304138/100116447-c0f58580-2e41-11eb-9bcd-63a88b2e3538.png" /></td></tr></table>

I would defer to Jason's expertise, but I believe we are looking for:

How many `fl-search` events have a `fl-map-zoom-out` event before we see a `fl-search-results` event? Keeping in mind, searches with 0 returned locations do not have a `fl-search-results` event.

I think it would be interesting to get a COUNT and AVG of these zoom events.  And facility type is in this CD...

```sql
        -- facility_type
        (
            SELECT
                hcd.value
            FROM
                hits.customdimensions AS hcd
            WHERE
                hcd.index = 110
        ) AS facility_type
``` 

----------

> What is the average closest result by facility type?

I created a dataset for this a little while ago.  Here's a basic card I created from the data (also in the appendix of the Facility Locator dashboard:

https://va-gov.domo.com/page/1129885232/kpis/details/42170882

Some weirdness with the field I had to regex around:  https://va-gov.domo.com/datasources/850002a0-995e-455b-9ff2-4e8e96911838/details/settings

----------

> How often does a Veteran view the map tab in mobile?

@jonwehausen  - it doesn't look like we are tracking these tabs, nor do I see them in the design system:

![image](https://user-images.githubusercontent.com/62304138/100122265-2ac45e00-2e47-11eb-993a-3d04416f8399.png)

And it appears this particular package is only used in facility locator:

![image](https://user-images.githubusercontent.com/62304138/100122106-141e0700-2e47-11eb-849d-d5602543c5ce.png)

What do you think?  Map out a taxonomy for tab components?  Check with the design system team to see if they are planning on using them more?

**Comment by JasonTheBearded** [comment] 2020-11-24 20:53
@mmiddaugh we've noticed in the results for these facility searches that a NULL facility type is returning with distances way higher than our other averages. We have results for all the listed facility types in the dropdown so we're not sure where the NULL is coming from.  Would you happen to know?

**Comment by JasonTheBearded** [comment] 2020-12-01 14:07
@mmiddaugh Have you had a chance to look into that NULL facility type? Thanks!

**Comment by joanneesteban** [comment] 2020-12-01 16:30
Moving this to 'blocked' until we've completed the [bug issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16643)

**Comment by mmiddaugh** [comment] 2020-12-01 18:24
@JasonTheBearded I'm not sure what Facility type is "null" - it's a required field so every search should map to a facility type from the drop down. 
The analytics team once mentioned we might have users leveraging the URL...could this be creating the null data?

**Comment by JasonTheBearded** [comment] 2021-03-29 15:18
@mmiddaugh apologies for the delay on this ticket and thank you for your patience. Since reinstating our 'fl-search-results' event, due to privacy and security concerns, all distance and location based values were stripped out. So we are no longer capable of tracking or reporting on any related metrics. 

I also confirmed that there is no tracking on the tabs, as the particular code running those tabs is not using any design system or site component. 

Based on these findings I'm recommending we close this ticket. 

In order to get tracking on the tabs to report on Question 3, a tracking request needs to be submitted or if you prefer, our GTM team can provide the dataLayer code and one of the developers on your team can implement it.

Again my apologies for this long delay and I really appreciate your patience. Thanks!

**Closed** 2021-04-06 21:39 UTC
Labels: analytics-insights, analytics-reporting-request, analytics-request, vsa, vsa-facilities
