### ISSUE TITLE
Onboard VFS teams to Datadog

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#49798] opened 2022-11-17 21:45 UTC
(original content at bottom of project template)

## Problem Statement 
Datadog has been a huge success for the Platform teams, enabling faster troubleshooting, onboarding of monitoring, and significantly easier to maintain than cloudwatch and Loki. We would like to open up DD for VFS teams so we can stop maintaining cloudwatch and Loki. 
VFS teams are very excited to leverage datadog too. See examples of VFS requests under "Where was this problem reported?"

Concerns:
- Budget doesn't allow for VFS teams to use datadog under platform
- Question: Can we work with DOTS to pay for this or find out if they can?
- Live logs only last 30 days, archived after this. Logs can be rehydrated if required. 
- We need a model for permissions - [We don't want a situation where one VFS team could accidentally change or delete critical monitors and alerts used by other teams.](https://dsva.slack.com/archives/CBU0KDSB1/p1671038074707239?thread_ts=1671035569.956649&cid=CBU0KDSB1)
- We need to coordinate with DOTS for access

*How might we enable VFS teams with faster troubleshooting, onboarding of monitoring, and significantly easier maintenance than cloudwatch and Loki. How might we onboard VFS teams to Datadog to achieve these benefits.*

## User Impact
All VFS teams -- roster of VFS users as of 12/21/22 is 358

## Where was this problem reported?
Patrick has been pushing for [VAOS to implement it](https://dsva.slack.com/archives/CBU0KDSB1/p1671035569956649).
[10-10 Team has requested it](https://dsva.slack.com/archives/CBU0KDSB1/p1670437083391479)
[Chatbot team has requested it](https://dsva.slack.com/archives/CBU0KDSB1/p1670348801482499)
[Benefits squad 1 requested it  ](https://dsva.slack.com/archives/CBU0KDSB1/p1667843683267589)

## What do we not know about the problem space?
We know the concerns floating around that are listed above

## What (if any) research or discovery has been done?
None

## What is the acceptance criteria?
VFS teams can request read or write access to DD
VFS teams can be given the correct permissions so they can accomplish what they need but can't take down critical monitors

## How should we measure success?
# of folks migrated from Loki to DD
# of folks migrated from cloudwatch to DD

## TODOs
- [ ] Convert this issue to an epic

*Original content from when issue was submitted:*
Datadog has been a huge success for the Platform teams, enabling faster troubleshooting, onboarding of monitoring, and significantly easier to maintain than cloudwatch and Loki. This request is get the approval from OCTODE to allow the Platform to start onboarding all VFS teams into Datadog.

Previous concerns:
- Budget doesnt allow for VFS teams to use datadog under platform
  - Question: Can we work with DOTS to pay for this or find out if they can?
- Live logs only last 30 days, archived after this. Logs can be rehydrated if required. 

Other options:
- Keep VFS teams in Loki
- Move VFS teams back to Cloudwatch

**Comment by jwoodman5** [comment] 2022-12-14 01:36
I added the project template so we can start building this out for project consideration by VA.

**Comment by andreahewitt-odd** [comment] 2022-12-21 16:10
https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/issues/gh/department-of-veterans-affairs/va.gov-team/50378 <- closed duplicate

**Comment by mchelen-gov** [comment] 2023-01-27 15:45
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081

**Closed by mchelen-gov** 2023-01-27 15:45 UTC
Labels: Epic, platform-crew-octo-de, platform-leadership, platform-po-escalations, platform-project, platform-sev-s1
