### ISSUE TITLE
Apply group labeling to /vaos/v1/locations/xxxxx/clinics endpoints

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#50958] opened 2022-12-20 17:02 UTC
Similar to some previous VAOS Alerts logging enhancements, we've identified that the '/vaos/v1/locations/xxxxx/clinics' endpoint could benefit from group labeling to match the clinic entries together. Example screenshot of current dashboard, showing the individual clinics:

![Screen Shot 2022-12-20 at 11.56.24 AM.png](https://images.zenhubusercontent.com/5fcfbc1c239ebd98b2acfe6c/dd78c405-aec4-4db6-b2e7-aea435bc4c39)

We should be able to utilize the StringHelpers class like before to group these endpoints together in Grafana.

**Comment by ajmagdub** [comment] 2023-01-11 16:20
Code merged into the master branch. Once it's in production, we will check the VAOS Alerts Dashboard and verify it's working as intended.

**Closed** 2023-01-11 16:22 UTC
Labels: backend, vaos, monitoring, vaos-v2
