### ISSUE TITLE
0781 Research Readout and Closing

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#87160] opened 2024-06-27 20:04 UTC
This ticket is to create a readout document from the ongoing 0781 Concept test research.  

Task:
- [x] Select how you want to present the findings (Slides or Doc)
- [x] [Use the VA Template Research Findings ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md) to frame findings
- [x] Creating the full report
- [ ] Creating a deck specifically for the Monday VA syncs using their template (https://docs.google.com/presentation/d/19l8281cENnUmdz0qIsyPcVIeoyB8uw_kzoHYWbuYlwA/edit#slide=id.g892adcb623_0_141).
- [x] Shannon will review the report before the readout

Acceptance Criteria:
- [x] Full findings report for internal team
- [x] Veteran Digital User Experience Weekly Design Sync Deck
- [ ] Github findings in our research folding following template
- [x] Research ticket updated
- [ ] Schedule team readout
- [x] Schedule Monday VA sync
- [x] Post research findings to [GitHub folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2024-06%200781%20Research)
- [x] Update the [research ticket ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/580)with  key findings
- [x] Schedule a time to present Veteran Digital User Experience Weekly Design Sync

**Comment by lisacapaccioli** [comment] 2024-08-29 17:51
Duplicate of work done in a couple of other tickets

**Closed by lisacapaccioli** 2024-08-29 17:51 UTC
Labels: disability-experience, DBEX-Carbs
