### ISSUE TITLE
Add join appointment button to redesigned at home video appointments detail page

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#88731] opened 2024-07-18 15:59 UTC
## Description
In the new appointment details redesign, the _Join appointment_ button and functionality is not present. This functionality needs to be added.

- There is existing functionality and logic within the `src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/VideoLink.jsx` component that can be ported over to the resigned appointment details view for at home video appointments. 
- The component for the at home video appointments detail view is located here: `src/applications/vaos/components/layout/VideoLayout.jsx`

### Developer Notes
- We may want to determine how we might organize child components for the new appointment redesign code and whether or not we should create a new `VideoLink` component for the new code.
- Additionally, there is some opportunity for refactoring some repeated code (the facility location logic) into a child component. While not related to this issue specifically, I've mentioned it for context around how we might want to organize new child components.
---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on
- [x] Given when it is 30 minutes before an at home video appointment or 4 hours after the start time
- [x] Then the front end will display the _Join appointment_ button
- [x] And page design matches the [design spec](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=756-20952&t=IjUEbMHzkxesIHMX-4)

### Design Assets
- [Figma](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=756-20952&t=IjUEbMHzkxesIHMX-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated
- [ ] Update unit tests
- [ ] Update e2e test

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment] 2024-08-02 15:56
Product and UX will validate in staging. cc: @outerpress 

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6aab7a2d2af2644df2db13686d7e7e017b37157d/Screenshot%202024-08-02%20at%2011.52.38%E2%80%AFAM.png" alt="Screenshot 2024-08-02 at 11.52.38 AM.png" />

**Comment by outerpress** [comment] 2024-08-02 20:35
Notes from testing:
- I tested with Judy Morrison at about 1:25 PM PT (2:25 MT). The appointment I tested was scheduled for 1 PM MT
- I clicked the Join link and it didn't respond
- I right-clicked the Join link and used the open in new tab option. It did open, but displayed an error
- I was able to tab to the link, but it didn't respond when I clicked Enter
- VoiceOver announced the link, but I couldn't active it with VO commands.

See video for more deets:


https://github.com/user-attachments/assets/36f97c96-da00-425a-9911-bc91864aed54

@ryanshaw @ldelacosta

**Comment by outerpress** [comment] 2024-08-02 20:50
Also a couple of spacing issues:
- With join link active: Can you remove the margin below the link? It's adding more space than is between the rest of the sections
- With join link inactive: Similar issue here, but I think it's caused by one of the two <br>'s with the text block


<img width="405" alt="Screenshot 2024-08-02 at 1 45 12 PM" src="https://github.com/user-attachments/assets/663525a8-e850-499e-b04d-54e07c1ef683">

<img width="645" alt="Screenshot 2024-08-02 at 1 49 40 PM" src="https://github.com/user-attachments/assets/a8b74e13-b9d6-4565-994f-eea4325eacc5">

**Comment by ryanshaw** [comment] 2024-08-06 13:29
@outerpress I have a fix for the spacing issue awaiting code review [here](https://github.com/department-of-veterans-affairs/vets-website/pull/31216), will let you know when merged into staging.

**Comment by outerpress** [comment] 2024-08-06 18:10
Spacing fixes look great, thanks @ryanshaw fyi @ldelacosta 

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzQzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e48aed6daf974c9dc52f6d8af05a558746fb5c2/Screenshot%202024-08-06%20at%2011.09.56%E2%80%AFAM.png" alt="Screenshot 2024-08-06 at 11.09.56 AM.png" />

<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzgzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a7f49bcb7f85f35bb8ff1af6ac087d3ac13ac98/Screenshot%202024-08-06%20at%2011.10.06%E2%80%AFAM.png" alt="Screenshot 2024-08-06 at 11.10.06 AM.png" />

**Comment by outerpress** [comment] 2024-08-06 19:55
Ran through it together using @ryanshaw 's environment and the changes are good to go! @ldelacosta

**Comment by ldelacosta** [comment] 2024-08-06 19:56
No issues to report. Closing out the ticket.

**Closed by ldelacosta** 2024-08-06 19:56 UTC
Labels: frontend, appointments, appointments-fe-ux, feature
