### ISSUE TITLE
[Bug] BDD: Rated Disabilities Page Showed Up During UAT

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14396] opened 2020-10-05 17:28 UTC
## Issue Description
While we were doing UAT, the service member saw the rated disabilities page with a blank rated disabilities.  This should not be happening.  The odd thing was, he went back and did it again and it worked.

## Acceptance Criteria
- [ ] Figure out why/how he was able to see rated disabilities
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment] 2020-10-07 18:06
@annaswims has the SIP data! Anna fact of the day, she taught swimming lessons in Korea!

**Comment by annaswims** [comment] 2020-10-07 20:04
sip data sent to @Mottie in Keybase

**Comment by ndsprinkle** [comment] 2020-10-21 19:32
My initial thought after looking through the code is that we just need to add the `isBDD` check to all locations that shouldn't show up during the BDD flow. When initially setting up the BDD flow in 526, we left a lot of the conditional pages as-is because they theoretically wouldn't show up in the BDD flow anyway. A prime example of this is rated disabilities, because theoretically the user would not rated disabilities in the BDD flow. That being said, even if this isn't the solution, it's still probably a good bet to add the `isBDD` check to this and other pages that shouldn't ever show up in the flow.

Now, the fact that the user saw the page but had blank rated disabilities could invalidate everything I just said. Still need to do some tests around that.

**Comment by ndsprinkle** [comment] 2020-10-26 13:17
@luke-gcio @Mottie @annaswims One question about the user mentioned above: when going through the form, before the rated disabilities page, did the user see this page:
![image](https://user-images.githubusercontent.com/53942725/97176895-fb4d0380-176b-11eb-9463-c612229debec.png)
And if so, did they check the box that says "One or more of my rated conditions that have gotten worse"?

**Comment by Mottie** [comment] 2020-10-26 13:21
Nope

**Comment by ndsprinkle** [comment] 2020-10-26 21:58
I'm not going to close this ticket just yet. I want to do one more evaluation of logic locally to see if there's a way I can refactor all the logic I detail below to where it is both more clear and consistently correct. That may be worth a separate ticket, though. Regardless, here is a massive list of my findings that can be used for future reference in case this issue ever pops up again. 

I'll start with the rated disabilities page specifically since that is what the creation of this ticket is based on. The rated disabilities page is defined here in the form config: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/config/form.js#L282-L290

As shown in the code, the depends function checks this logic: `DISABILITY_SHARED_CONFIG.ratedDisabilities.depends(formData) && !isBDD(formData)`

Following the trail of `DISABILITY_SHARED_CONFIG.ratedDisabilities.depends`, we find this line: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L852-L853

That references a couple other functions that we need to follow, `hasRatedDisabilities` and `newConditionsOnly`. 

The first is defined here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L740-L741

And the second here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L757-L758

`hasRatedDisabilities` simply breaks down to `formData.ratedDisabilities && formData.ratedDisabilities.length`, effectively just checking if the array has any elements. Theoretically, this would never be true for a BDD claim anyway, but we still have the `isBDD` check, as referenced above, as a backup. But besides that, we clearly would not want to show this page if that array were empty as the contents of the page are based on the contents of the array.

`newConditionsOnly` breaks down into two other functions, `(!isClaimingIncrease(formData) && isClaimingNew(formData)) || false`. I believe the `|| false` here is simply converting this function into a `boolean` as it shouldn't modify any logic.

The first function is defined here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L751-L753

And the second here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L743-L749

`isClaimingIncrease` is defined as `hasRatedDisabilities(formData) && _.get('view:claimType.view:claimingIncrease', formData, false)`, which is checking `hasRatedDisabilities` again but more importantly checking that the "One or more of my rated conditions that have gotten worse" checkbox is checked on the `claimType` page and defaulting the value to `false` if `null`. Both of these conditions need to be true for this function to be true.

`isClaimingNew` is defined as `_.get('view:claimType.view:claimingNew', formData, !hasRatedDisabilities(formData),) || _.get('view:newDisabilities', formData, false)` which is checking that the checkbox labeled "A new condition" on the `claimType` page is marked as true (and defaulting the value to the opposite of `hasRatedDisabilities`) and is also checking the redundant Yes/No "Do you have any new conditions you want to add to your claim?" question on the `newDisabilities` page. In this function, only one of these has to be true. 

Now, to fully break down the `depends` function for the rated disabilities page, it would look like this: `formData.ratedDisabilities && formData.ratedDisabilities.length && !(!(formData.ratedDisabilities && formData.ratedDisabilities.length && _.get('view:claimType.view:claimingIncrease', formData, false)) && (_.get('view:claimType.view:claimingNew', formData, !hasRatedDisabilities(formData)) || _.get('view:newDisabilities', formData, false))) && !isBDD`

That's a whole lot of logic, but if we just look at a few important places I think it will help illustrate how strange this issue is. Looking at the outside of the logic, at least `formData.ratedDisabilities` has to both exist and have a length greater than 0 AND `isBDD` has to be false. Assuming somehow the user has some garbage data that got thrown into the `ratedDisabilities` array that causes the first two conditions to be true, the `isBDD` flag will also need to evaluate to false.

This is where other pages start to come into play, because if `isBDD` was somehow evaluating to false, then there would be quite a few issues throughout the form. Pages would appear (or hide) that shouldn't and various texts and logics would vary, but as far as I know the only strange page was the rated disabilities page. I say this because there are some 18 pages that reference this `isBDD` function just to determine if they should appear. I could make a list of these pages and we could talk about if any of them also behaved strangely, but they would've been fairly obvious. The service treatment record page would've been skipped, there would've been questions about service pay and separation pay, and the `claimType` page would've show, but Robin confirmed above that this did not show, plus many other differences.

However, for the sake of continuing this logic journey, let's assume that somehow `isBDD` was also evaluating true, so we can look deeper into the logic statement. Removing the parts we're already saying are true, we're left with: `!(!(_.get('view:claimType.view:claimingIncrease', formData, false)) && (_.get('view:claimType.view:claimingNew', formData, false) || _.get('view:newDisabilities', formData, false)))`

`viewClaimingIncrease`, `view:claimingNew`, and `view:newDisabilities` are all `boolean` values that the user would need to manipulate. None of these values are modified based on prefill data. As confirmed by the `claimType` page not appearing, the user did not manipulate the first two values, the checkboxes, so they would default to `false` in our example. This further simplifies the logic to: `!(true && (false || _.get('view:newDisabilities', formData, false)))`

Here's where things get exciting. The last `boolean` value `view:newDisabilities` is a Yes/No field that appears on the `newDisabilities` page. However, that page appears _after_ the rated disabilities page, meaning this value would've been false, as it defaults to this, when the user was on the rated disabilities page. This leaves us with this: `!(true && (false || false))` or `!(true && false)` or `!false` or simply `true`

So, unless there's an issue with my logic breakdown somewhere, which is entirely possible, it is possible for this page to appear to the user naturally based on our logic. However, as mentioned, the primary problem with this theory is that `isBDD` was assumed to be false, which I find highly unlikely based on the pages that did and didn't appear before and after the rated disabilities page.

**Comment by ndsprinkle** [comment] 2020-10-27 18:13
I think the best immediate course of action is to rework this logic. The depends logic for the rated disabilities page is so crazy convoluted. At the end of the day, all that needs to be checked is `view:claimType.view:claimingIncrease`. That is the checkbox that is checked by the user to indicate that one or more of their rated disabilities have gotten worse. Beyond that, logic can be (and already is) in place to show or not show that checkbox. 

I will create a secondary ticket to do this work. Not sure how much it will help functionality, but it will definitely be cleaner and ensure there's no other funky logic somehow showing the page.

**Comment by ndsprinkle** [comment] 2020-10-27 19:21
Ticket created: #15377

**Closed** 2020-10-27 19:23 UTC
Labels: BDD, bug, development, frontend, vsa-benefits
