### ISSUE TITLE
Add stickiness to user based feature toggles 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1763] opened 2019-09-13 13:18 UTC
# Overview 

- Users who receive a variant should stay in that variant across devices when they are logged in 

# Examples 

- after logging in on my home computer, a new feature is enabled for me use
- later that day, I log in with my phone and see the same feature enabled 

# Notes 

- Some UX work might be required for this- there may be other use cases to work through 
- Team wish to ramp up % during rollout but do not want users who are already receiving a variant to be removed from it. Stickiness for a user should end when the following conditions are met: 
  - when the feature is enabled or disabled for _all users_ 
  - when the feature is disabled for all logged in users (set to 0%)

**Comment by annaswims** [comment] 2019-11-25 14:45
If you use the "Percentage of Logged in Users" conditional toggle it will always be the same x % of users.
<img width="358" alt="Screen Shot 2019-11-25 at 9 41 03 AM" src="https://user-images.githubusercontent.com/19188/69549712-ccc91600-0f67-11ea-886b-7cd9332408bb.png">

The algorithm works by converting the user's email address into a number between 0-100 and comparing it to the value of "Percentage of Logged in Users", so as long as the value of "Percentage of Logged in Users" doesn't decrease the feature will remain enabled for those who have had the feature enabled in the past.

**Comment by alexpappasoddball** [comment] 2020-03-03 19:36
@annaswims is this is the same thing as #5997?  If so we should close this one in favor of that one.

**Comment by annaswims** [comment] 2020-03-17 20:53
It's not a duplicate of #5997, but it is complete.  Closing.

**Closed by annaswims** 2020-03-17 20:53 UTC
Labels: backend, feature toggles, tools-be
