### ISSUE TITLE
Discovery: Recommend approach for scheduled test of production functionality

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#32871] opened 2021-11-15 20:34 UTC
## Details 

Follow up item from partial frontend app outage in VA.gov production on 11/9/21. [Postmortem here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-11-09-dynamic-imported-modules-not-loading.md)

One issue that contributed to that incident was that there was no automated alert to tell the team that certain apps were failing to load. If there was an automated alert, it was not noticed. 

This ticket is to investigate and recommend an approach for testing that frontend functionality on VA.gov is loading (& basic functionality?). 

## Questions to answer
- [ ] Could the synthetic monitoring initiative that Ops team worked on help here? 
- [ ] What other testing tool might we use for this? Cypress? 
- [ ] What areas of functionality do we need to test? (In the case of the 11/9 incident, the static pages app apps were down — perhaps testing one app from each group? Or just one react app and one static pages app? What is our minimum set of tests required?) 

## Definition of done 
- [ ] Recommend approach for improved error detection of frontend apps loading on VA.gov in production
- [ ] Create tickets for implementation and prioritize appropriately

**Comment by mchelen-gov** [comment] 2021-11-16 14:43
it sounds like the root cause was incorrect deployment to s3, so that is the appropriate status to monitor

**Comment by rmessina1010** [comment] 2023-01-05 20:50
Old ticket,  should close?

**Comment by jhonnyoddball** [comment] 2023-01-19 20:08
Expired. Closing

**Closed by jhonnyoddball** 2023-01-19 20:08 UTC
Labels: platform-cop-frontend, platform-cop
