### ISSUE TITLE
Redirect Request for R&S article about EDU benefits and natural disasters

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#94971] opened 2024-10-15 16:30 UTC
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.

| POC | Github alias(es) |
--- | --- 
| Product team point(s) of contact: | [bethpottsVADEPO](https://github.com/bethpottsVADEPO) |
| Content point of contact: | [bethpottsVADEPO](https://github.com/bethpottsVADEPO) |
| IA point of contact: | `IA will enter` |

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)
- [ ] We are removing a temporary redirect  (add relevant background and link to original redirect request)

### Do you have a product technical team able to implement this redirect?
- [ ] Yes - Please note: Redirect still needs approval from IA.
  - [ ] Please verify your team has reviewed [Redirect governance](https://design.va.gov/components/url-standards/redirects) and [Redirect technical implementation information
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md) 
- [x] No - CAIA will need to make Public Websites aware of the ticket.

### Implementation date
When does this request need to be live? **NOTE:** Redirects in vsp-platform-revproxy auto-deploy M-Th. Friday launches should be avoided.
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [x] During a specific date range: ***EARLIEST DATE TO LATEST DATE:*** 10-15 (today) - 10-18 (if possible, since we now have more up-to-date info available in the new disaster help article)
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/resources/what-if-my-school-closes-temporarily-because-of-a-natural-disaster/ |https://www.va.gov/resources/disaster-help/
### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue, if relevant:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [x] Requesting team: Validates everything is correct in production and closes ticket

**Comment by scjwalker** [comment] 2024-10-15 18:17
Checking with Beth in Slack about notifying stakeholders.

**Comment by scjwalker** [comment] 2024-10-15 18:18
@FranECross This one's ready for the PW team.

**Comment by scjwalker** [comment] 2024-10-16 16:00
Beth [confirmed on slack](https://dsva.slack.com/archives/C03MP8MEPCN/p1729016207340499) that stakeholders have already been notified.

**Comment by FranECross** [comment] 2024-10-18 18:36
@scjwalker Will you please provide the redirect URLs? Thanks! The ticket indicates a preferred implementation of today, but this hasn't been refined and our sprint has already started. Do you and stakeholders wish this to be an injection, since it has to do with natural disasters? Thanks! cc @jilladams

**Comment by bethpottsVADEPO** [comment] 2024-10-18 18:47
@FranECross 
Redirect this page: https://www.va.gov/resources/what-if-my-school-closes-temporarily-because-of-a-natural-disaster/
To this page: https://www.va.gov/resources/disaster-help/

Can this be worked into your sprint (doesn't have to happen today)?

**Comment by FranECross** [comment] 2024-10-18 18:53
@bethpottsVADEPO Thanks for that info! Yes, I'll pull it in for early next week and let the team know.

**Comment by FranECross** [comment] 2024-10-18 18:57
Notified the FE engineers via Slack about this item, and requested a Monday implementation (which will probably then release on Tuesday after 10 am). https://dsva.slack.com/archives/C52CL1PKQ/p1729277794591719

**Comment by jilladams** [comment] 2024-10-21 19:04
Chris is out today but has a PR up. I've nudged it to see if we can get approvals. We'll make a note here once it merges, to let you all know timing for deployment.

**Comment by randimays** [comment] 2024-10-21 20:32
Code has merged. The redirect can be validated in production shortly after 9am CST tomorrow morning.

**Comment by scjwalker** [comment] 2024-10-22 20:35
I just checked - the redirect is working as intended. Once the other checkboxes are done I'll validate and close the ticket.

**Comment by jilladams** [comment] 2024-10-23 22:14
@scjwalker double checking which checkboxes? I think the work for this ticket is done from Sitewide's side, but want to make sure we aren't overlooking a list somewhere that I'm not seeing.

**Comment by scjwalker** [comment] 2024-10-24 16:02
@jilladams The ones for the implementation team. Looks like they're checked now!

**Closed** 2024-10-24 16:02 UTC
Labels: Public Websites, sitewide, Unplanned work, current sprint, VA.gov frontend, sitewide CAIA, Redirect request, ghp-sprint, points-1
