### ISSUE TITLE
[Discovery] Updating email on VA.gov does not update email in VAOS

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8684] opened 2020-05-04 14:26 UTC
## What happened?
In legacy VAOS a 'user profile' exists where a Veteran can change their email address and it updates on all requests as shown in Scheduler Manager to these new/updated email. These preferences exist specifically to VAOS/SM/var-resources. 

In new VAOS, that profile exists at a global level via VA Profile / Vet360. Like other VA application, new VAOS pulls from this standard profile data to populate emails. Additionally, per the standard design practices on VA.gov, most forms require user to provide their desired contact email (and adding email to form doesn't not change email on VA Profile). We do this as part of new VAOS. It is this field that we send back to var-resources that populated Schedule Manager. 
- When the new VAOS UI submits a request, we update the var-resources preferences data which should also update/show in Schedule Manager
- We can't detect when VA Profile data changes (which can happen outside va.gov, too)

## Open questions about Desired behavior
- Is the expectation that when a Veteran updates their VA.gov profile, that all request in VAOS also update to that email? If so, then it doesn't make sense to allow users to update email during the scheduling process
- For var-resources & SM web - these should sync with VA Profile - should they not?

**Comment by jbalboni** [comment] 2020-05-04 14:45
If this is a bug, it's a bug in SM, not VAOS. The va.gov profile is using the standard VA Profile data, which is used by multiple systems and is the expected place for VA tools to pull profile information from (to my knowledge). The new VAOS UI pulls the email from the va.gov profile.

SM and var-resources have their own internal preferences system which, as far as I know, does not sync with VA Profile. When the new VAOS UI submits a request, we update the var-resources preferences data, but we can't detect when VA Profile data changes (which can happen outside va.gov, too).

It's also not really clear to me that this would be the expected behavior from a user. We ask for their email address, we also list the email on the request cards. If the expectation is that this email is always in sync with the va.gov profile, it wouldn't make sense for us to allow them to choose a different email. The pattern in most forms on va.gov is that putting your email in a form doesn't update your profile info, since that is not what is user is trying to do (they're trying to fill out a specific form).

If the desire is for SM to stay in sync with VA Profile, then that work needs to be evaluated by the VAOS backend team.

**Comment by lenaecb** [comment] 2020-05-04 14:51
@jbalboni - Just a heads up, I added this to start the discovery process on what we want. It was submitted as a 'bug' by Marcy, but we need to sync between groups for how we're handling email addresses across. Specifically from SM with new VAOS.

**Comment by lenaecb** [comment] 2020-05-05 19:59
@lalexanderson-dsva @rtwell - this was marked as a 'bug' from Marcy's regression, but it's more of a bug for VAOS BE/ Schedule Manager. 

Nonetheless, I need your input on the "Open questions about Desired behavior." Our assumption is that we should continue handling the emails as we currently due since that's in line with other forms/approaches on VA.gov for VA profile data. 

We believe the update needed here is for var-resources to use VA profile.

**Comment by laurenernest** [comment] 2021-05-13 20:38
we'll be exploring emails in our notifications discovery. closing ticket

**Closed by laurenernest** 2021-05-13 20:38 UTC
Labels: VAMF, discovery, vaos
