### ISSUE TITLE
[FE/BE/Data] 10-10EZR: Discovery for SOAP error from 3/4

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77623] opened 2024-03-05 15:10 UTC
As a Veteran, I would like to be able to submit the 10-10EZR online so that I can update my data and not have to do it again.

- [ ] Figure out if this is the same issue that Matt L fixed ([Pull Request](https://github.com/department-of-veterans-affairs/vets-website/pull/28445/files))

- [ ] Work with Luis to investigate error

- [ ] Determine cause of error
- [ ] Propose fix for error (implementing fix will be a different tory)
- [ ] **Success: We know what caused the SOAP error on 3/4**

**Comment by luis-simauchi** [comment] 2024-03-05 19:13
Luis Simauchi
  1 day ago
looking at the EZR pops first on Saturday, they look to be 3 instances from the same person (same IP / location) and a couple of minutes apart. These look to be the same  Common::Exceptions::SchemaValidationErrors: Validation error we often see


Luis Simauchi
  1 day ago
but I will get you particulars shortly from Sentry


Luis Simauchi
  1 day ago
DD view from the APM trace: https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%2A%20AND%20env%[…]iz=stream&start=1709361000000&end=1709363160000&paused=true


Luis Simauchi
  1 day ago
yep error message returned in the sentry log:
code: 109,
detail: The property '#/' did not contain a required property of 'veteranDateOfBirth' in schema 2edc0620-c958-5b22-9d66-dd28cf11cb5d,
status: 422,
title: Validation error (edited) 


Luis Simauchi
  1 day ago
senrty log of one of the attempts here: http://sentry.vfs.va.gov/organizations/vsp/issues/245028/events/f1e3fc3007f14c97a2aa[…]roduction&project=3&query=is%3Aunresolved+ezr&statsPeriod=7d


Luis Simauchi
  1 day ago
[10:05 AM]
different error than the Saturday instance,  different user got a HCA::SOAPParser::ValidationError: HCA::SOAPParser::ValidationError
Luis Simauchi
  [10:21 AM]
DD APM trace: https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%2A%20AND%20env%[…]iz=stream&start=1709511000000&end=1709511300000&paused=true
Luis Simauchi  [10:23 AM]
errors message in Snetry is a little sparse...
code: LIGHTHOUSE_FACILITIES404,
detail: Record not found,
source: Lighthouse Facilities,
status: 404,
Luis Simauchi  [10:27 AM]
body message in ADDITIONAL DATA
xmlns:ns0="http://jaxws.webservices.esr.med.va.gov/schemas"><faultExceptions><faultException><code>VOA_0059</code><message>Missing Required Field: Name of Insurance Company.</message></faultException><faultException><code>VOA_0065</code><message>Missing Required Field:  Name of Insurance policy holder.</message></faultException>

**Comment by luis-simauchi** [comment] 2024-03-05 19:14
Luis Simauchi
  1 day ago
sentry log: http://sentry.vfs.va.gov/organizations/vsp/issues/249630/?environment=production&project=3&query=is%3Aunresolved+ezr&statsPeriod=7d#extra

**Comment by hdjustice** [comment] 2024-04-01 15:28
This issue was caused by "spaces" being entered on the Insurance name field, causing "whitespace" which is not recognized or validated.  This issue was fixed in ticket #77689

**Closed** 2024-10-28 20:14 UTC
Labels: frontend, backend, discovery, 1010-team, 1010-analytics, 1010-bug, needs refinement, 1010-ezr
