### ISSUE TITLE
FSR - FSR signature value missing

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#26608] opened 2021-06-24 22:42 UTC
Issue: DMC is not receiving veteran's signature along with the FSR they submitted. 
Def. of Done: DMC is able to receive veteran's signature along with the FSR they submitted

**Comment by kevinmirc** [comment] 2021-06-30 18:08
DMC does not currently accept a signature value in the payload. There are a few items the DMC team will need to do in order for us to send the signature value:
- [ ] They need to update their base PDF to allow input on the signature section (which only allow ink right now)
- [ ] They need to update their PDF generation code to populate the signature field in the PDF
- [ ] Tell us what property in the payload should have a signature value (what's the data type accepted)

At this point in time, they are currently working on turning the signature field into a text field.

**Comment by LinnJS** [comment] 2021-07-15 13:21
This is not a bug but actually a feature since the signatures were never intended to be send but just to be used a user validation before submitting.

**Comment by craigwheeler** [comment] 2021-08-18 21:18
Work has been completed (tickets [27132](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27132) and [28444](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/28444)) and verified by the DMC closing ticket

**Closed by craigwheeler** 2021-08-18 21:18 UTC
Labels: bug, frontend, backend, vsa-benefits-2, DebtRes FSR Iteration 2
