### ISSUE TITLE
AWS access for Mary Goodhart

### ISSUE THREAD

**Issue by mgoodhart5** [department-of-veterans-affairs/va.gov-team#70743] opened 2023-11-28 20:05 UTC
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Mary McCormick-Goodhart

### Your Email

mary.goodhart@docme360.com

### Team, Role, and Company of the target individual

VES Developer Experience, DevOps Engineer, Oddball/DocMe360

### Product Manager (PM) name and email

Danielle Baranowski - danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Patrick Vinograd - patrick.vinograd@va.gov

### Desired AWS Access

EC2 Read for fwd-proxy, 
Read/Write for Secrets Manager Parameter Store for our deployments sensitive values. Similar to this https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Stepstocreateanewsecretvalue:
Permissions needed to accomplish this https://github.com/department-of-veterans-affairs/devops/tree/master/terraform#making-changes on behalf of VES Developer Experience-

### Access Expiration

8-31-2025

### E-QIP Transmittal Confirmation

<img width="889" alt="Screenshot 2023-11-28 at 1 02 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/40919519/68fd54c1-495d-4ed8-bb43-513783e2bf9a">

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment] 2023-12-04 14:15
User found in VFS Team Roster.

**Comment by ph-One** [comment] 2023-12-07 14:05
> EC2 Read for fwd-proxy

Help me understand what this means -- what are you trying to do with the forward proxy? SSM? @mgoodhart5

**Comment by mgoodhart5** [comment] 2023-12-07 15:00
@ph-One We need to use it to tunnel into to hit live VA services for local development - so just would like the permissions to grab that IP when it changes.

**Comment by ph-One** [comment] 2023-12-12 18:48
Because there is not an established DevOps presence for VES on Platform, I'm going to start out with VFS Developer access, and go from there. We may need to build out all new policies and groups for VES

**Comment by ph-One** [comment] 2023-12-12 19:23
I've provided VFS Developer privileges. Unless I hear from @mgoodhart5 that the privs are _not_ working out, I'll close this ticket by EOD Friday.

**Comment by flooose** [comment] 2023-12-20 15:16
@ph-One can I close this an proceed with https://github.com/department-of-veterans-affairs/va.gov-team/issues/70742?

**Comment by patrick-black-oddball** [comment] 2024-01-09 14:29
Closing ticket as suggested by comment stream - confirmed user has aws access

**Closed by patrick-black-oddball** 2024-01-09 14:29 UTC
Labels: operations, external-request, ops-access-request, Infrastructure-Services
