### ISSUE TITLE
Copy of Port over FE business logic (calculateIncome.js)

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#72790] opened 2024-01-02 19:10 UTC
As we approach FSR 3.0 the BE intends to take responsibility for as much FSR business logic as possible.

Port the logic in vets-website file _src/applications/financial-status-report/utils/calculateIncome.js_ into a service on the BE and expose it as an endpoint.

**Comment by HeatherRienks** [comment] 2024-03-05 20:12
This appears to be a dupe of this closed ticket: #72789.

**Closed by HeatherRienks** 2024-03-05 20:12 UTC
Labels: backend, vsa-debt, medium-priority
