### ISSUE TITLE
[DUPLICATE][FE] Display Confirmation Page to User Who Visits Pre-Check-In Link after Completing Check In

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#37986] opened 2022-03-03 21:28 UTC
## Questions
@acrollet @randomsync We need to ask Stephen how long we can keep the PII in the LoROTA entry....
@acrollet Will talk to Stephen and get sign off on this ticket based on our approach.

## User Story
As a Veteran, if I have forgotten that I already completed pre-check-in and attempt to do it again, I want to know that I already completed the process so that I don't have try to do it again and waste my time.
 
## Background Info 
Currently when a veteran clicks the pre-check-in link again (and it is still valid AND pre-check-in is already completed) they are prompted to go through the entire PCI workflow again where they receive an error message at the end.
Desired behavior would be to show the veteran that they have already completed pre check in early in the workflow (immediately after clicking the link).

## Wireframes
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/PGkmnvx    
    
## User workflow
- When I
     - Click a pre-check-in link after I have already completed pre-check-in for the appointment
     - Log in using LoROTA
- Then I
    - See the confirmation page that tells me I have completed pre-check-in for my appointment with my appointment information
     
## To Do 
- [ ] Route to confirmation page
- [ ] Suppress call to check in
- [ ] Evaluate if our existing routing system will work for this w/o hacks (do we need to refactor)

**Comment by acrollet** [comment] 2022-04-19 18:32
@stephenBarrs we're planning on keeping the pre-check-in LoROTA entry populated until the end of the day of the appointment, in order to enable this improvement for Veterans. Please let us know if you think that's counter to our directive to keep information in LoROTA for as little time as necessary.

**Comment by brdunfield** [comment] 2022-05-04 14:04
Duplicate of https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/32782

**Comment by loripusey** [comment] 2022-05-04 14:53
This is not a duplicate, one if for pre-check-in and one is for check-in

**Closed** 2022-05-04 18:51 UTC
Labels: frontend, needs-info, HCE-Checkin
