### ISSUE TITLE
Frontend- Add caregiver certification to 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#14697] opened 2020-10-09 21:29 UTC
As a CSC,
I would like to see a PDF that indicates whether the Primary Family Caregiver is:

- An immediate family member
- Not an immediate family but currently lives with the Veteran full time or will do so upon to approval to the PFAFC

Note: designs are still in progress, and it's possible we might not need to make any front end changes. See @jonathanjnelson

**Comment by LinnJS** [comment] 2020-10-19 18:24
Blocked by design decisions and stakeholder decisions.

**Comment by LinnJS** [comment] 2020-11-03 15:25
Was working on this issue again, but is now blocked by platform transformSubmit mis-mutating the certification array will post more details.

**Comment by LinnJS** [comment] 2020-11-03 15:45
The schema dictates a [shape like this](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/528/files#diff-5317e46e82e43b1fb10a2eba27ab160be3d52c2c012257b4342ee87d2e0f073fR435). In the redux data everything looks as it should but when passing it to the [VSP transformForSubmit](https://github.com/department-of-veterans-affairs/vets-website/blob/LinnJS-signature-content/src/platform/forms-system/src/js/helpers.js#L625) mutates the enums array from an array of strings to an array of objects with a key of one letter and a value of none.

Here is a screen shot of the console.log of the redux data:
![Screen Shot 2020-11-02 at 12.35.07 PM.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/f5d4fcba-6747-4a80-8629-30068876b3b1)

Here is that same data being formatted in a JSON formatter with the results of the transformed data:
![Screen Shot 2020-11-02 at 12.35.30 PM.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/05390ba1-50d5-4f8e-a746-b392b2573ca4)

and

![Screen Shot 2020-11-02 at 12.35.18 PM.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/1f17f97b-6dac-412e-a2c2-9868bb2432e9)

There seems to be some kind of bug in this generic data transformer or the replacer function not sure what it is or why it is happening currently.

**Comment by hdjustice** [comment] 2022-04-29 13:13
Closing - This ticket has not been addressed in over a year, and there are no initiatives linked.  Any new work will have new tickets created.

**Closed by hdjustice** 2022-04-29 13:13 UTC
Labels: frontend, 1010-team
