### ISSUE TITLE
[FE] 10-10EZR: Ensure Vet DOB and Sex are being pulled and saved on submission

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74751] opened 2024-01-29 17:16 UTC
As a Veteran, I would like my Sex and DOB to prefill when I go to the online EZR so that I can update and submit my data without it failing.

- [ ] where is the disconnect on DOB and Sex and why is it not available to be prefilled for some users?
- [ ] Figure out why the check and have user fill this out isn't working like it is on EZ
- [ ] Implement
- [ ] Test
- [ ] Release to Prod
- [ ] **Success: We are never missing DOB and Sex from EZR**

Lihan's comment below:
I wasn't able to reproduce this issue, but since the backend and the frontend are pulling from the same data source, I think this is probably a frontend bug. Maybe the frontend is not sending the date of birth and gender fields from the form when submitting. The code looks different on the 1010EZ submit transformer.

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/ezr/utils/helpers/submit-transformer.js#L38

https://github.com/department-of-veterans-affairs/vets-website/blob/12582f1dcc60b2bd0308ef216614b0c55d49f141/src/applications/hca/utils/helpers.js#L142

**Comment by lihanli** [comment] 2024-01-29 17:33
it looks like the frontend is actually not pulling those fields from va profile, will try to test in staging to see if i can reproduce the issue

**Comment by lihanli** [comment] 2024-01-30 20:30
@alexseelig 
I wasn't able to reproduce this issue, but since the backend and the frontend are pulling from the same data source, I think this is probably a frontend bug. Maybe the frontend is not sending the date of birth and gender fields from the form when submitting. The code looks different on the 1010EZ submit transformer.


https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/ezr/utils/helpers/submit-transformer.js#L38

https://github.com/department-of-veterans-affairs/vets-website/blob/12582f1dcc60b2bd0308ef216614b0c55d49f141/src/applications/hca/utils/helpers.js#L142

**Comment by alexseelig** [comment] 2024-01-31 17:36
Thanks @lihanli, @mkerns1 @JoshingYou1 I'm going to make this a FE bug and we'll discuss in Refinement.

**Comment by alexseelig** [comment] 2024-01-31 17:47
Test

**Comment by alexseelig** [comment] 2024-01-31 17:47
Test 2

**Comment by aagosto90** [comment] 2024-01-31 17:58
Test

**Comment by mkerns1** [comment] 2024-02-27 15:26
PR merged into main.

Link to PR [here](https://github.com/department-of-veterans-affairs/vets-website/pull/27855).

**Closed** 2024-02-27 15:26 UTC
Labels: frontend, 1010-team, mvp, 1010-ezr

**Comment by emily-brown34** [comment] 2024-03-19 19:13
ticket was closed as the issue could not be reproduced, new ticket created for DOB issue
