### ISSUE TITLE
Debt Letters Debt Details Page 404

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27923] opened 2021-07-27 17:44 UTC
## What happened?
After shipping [Debt Letters Details Refresh bug#26974](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26974) I checked the feature in staging and looks like anything past `https://staging.va.gov/manage-va-debt/your-debt/` is not configured as a route and results in a 404.

This is likely problem with the DevOps or Backend routing configuration. 

When navigating to `https://staging.va.gov/manage-va-debt/your-debt` user should be able to select a debt and refresh and that debt should be persisted via URL ID. This logic works on localhost but does not work in any other environment because the client-side route is not whitelisted as a valid URL and results in a 404.

Need to setup a whitelisted route in this [file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml) and match the route of `/manage-va-debt/your-debt/debt-detail/[0-9]*`

## Steps to Reproduce
- Test User: [test user 1](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L3)

- Sign in as any test user, the above should work
- Navigate to `https://staging.va.gov/manage-va-debt/your-debt/`
- Select any debt
- Refresh
- Application should not have debt and debt should be persisted
- Selected debt URL should look something like `https://staging.va.gov/manage-va-debt/your-debt/debt-detail/79612120071`

## Desired behavior
When refreshing on the route in the steps to reproduce the reload should not result in a 404.

## Acceptance Criteria
- [ ] Reloading a selected debt does not result in a 404

**Comment by LinnJS** [comment] 2021-09-15 18:01
Here is a [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1628264694224600?thread_ts=1628260407.224000&cid=CBU0KDSB1) asking platform around this error during discovery

**Comment by LinnJS** [comment] 2021-09-15 18:37
[PR](https://github.com/department-of-veterans-affairs/devops/pull/9949) where this working is being done

**Comment by LinnJS** [comment] 2021-09-21 15:58
After testing this change with DevOps the config changes did not have the effect we desired. So opened a support ticket up with Platform Support for assistance [here](https://dsva.slack.com/archives/CBU0KDSB1/p1632237484399700)

**Comment by LinnJS** [comment] 2021-09-22 14:58
Merged this PR, still need to validate that the changes works in staging once deployed as advised by VSP platform support in thread linked above.

**Comment by LinnJS** [comment] 2021-12-15 17:30
This bug is still happening and needs to be revised and communicated with VSP but is low priority in light of MCP. 

With that being said this will also be an edge case for MCP but not 100% needed for launch,

**Comment by denisecoveyduc** [comment] 2022-10-12 18:11
@Dr-Pongo and @OptionSelect will confirm, we think this has been resolved.

**Comment by Dr-Pongo** [comment] 2023-01-31 17:45
Could not reproduce in the combined debt portal experience with the following steps:

- Test User: test user 1 (Also attempted with 228)
- Sign in as any test user, the above should work
- Navigate to `https://staging.va.gov/manage-va-debt/summary/debt-balances/`
- Select any debt
- Refresh
- Page shows same debt as before
- Selected debt URL should look something like `https://staging.va.gov/manage-va-debt/summary/debt-balances/details/79610443730`

Closing out as no longer an issue

**Closed by Dr-Pongo** 2023-01-31 17:45 UTC
Labels: bug, frontend, devops, vsa-debt, Debt Portal, benefits-crew
