### ISSUE TITLE
Analytics Implementation for Disability 21-686c Form

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7560] opened 2020-04-03 13:17 UTC
# Analytics Implementation

## Description
- Implementation for 'Add or Remove Dependents' - Form 21-686c and 21-674

- Who is this request for?
   Jason Wolf
    
- What team/project is this work for?
    _Disability Benefits_
    
- Provide the Domain where Google Analytics needs to be implemented
    [Current Mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

## Acceptance Criteria - 
- [x] Verify accurate execution of events for start of form 
- [x] Verify accurate execution of events for form completion
- [x] Verify accurate dataLayer metadata passed at form completion
- [x] QA has been completed
- [x] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [x] All appropriate issue tagging is completed
- [x] All AC completed

**Comment by jonwehausen** [comment] 2020-04-13 19:05
Description of Form Interaction | Screenshot | Datalayer Push
------------ | ------------- | -------------
Click on 'Sign in to start your application'|![image](https://user-images.githubusercontent.com/48527022/78362935-f08d1000-7588-11ea-9320-b973bbf2f1f1.png)|`dataLayer.push({`<br>`'event': 'login-modal-opened'`<br>`});` `dataLayer.push({`<br>`'event': 'login-link-clicked-cta-form'`<br>`});`
Click 'Add or remove a dependent' to start 21-686c form |![image](https://user-images.githubusercontent.com/48527022/78363341-950f5200-7589-11ea-950f-52258753dffe.png)|`dataLayer.push({`<br>`'event': 'cta-primary-button-click'`<br>`});` `dataLayer.push({`<br>`'event': 'disability-21-686c-start-form'`<br>`});`
ALL submissions of 21-686c (successful or failure)|![image](https://user-images.githubusercontent.com/48527022/78363853-7d849900-758a-11ea-91e2-51465cfd30a8.png)|`dataLayer.push({`<br>`'event': 'disability-21-686c-submission'`<br>`});`
Successful submissions of 21-686c|![image](https://user-images.githubusercontent.com/48527022/78363853-7d849900-758a-11ea-91e2-51465cfd30a8.png)| `dataLayer.push({`<br>`'event': 'disability-21-686c-submission-successful'`<br>`});`
Failed submissions of 21-686c|![image](https://user-images.githubusercontent.com/48527022/78363853-7d849900-758a-11ea-91e2-51465cfd30a8.png)|`dataLayer.push({`<br>`'event': 'disability-21-686c-submission-failure'`<br>`});`
Start of 21-674 (within 21-696c) | _placeholder_ |`dataLayer.push({`<br>`'event': 'disability-21-674-start-form'`<br>`});`

## Successful Form Submission Data
Description of Form Interaction | Screenshot | Datalayer Push
------------ | ------------- | -------------
Final successful submission of the form | ![image](https://user-images.githubusercontent.com/48527022/79151228-18098700-7d98-11ea-9724-e517ca0c3127.png)  | `dataLayer.push({`<br>`'event': 'disability-21-686c-submission-successful,'` <br> `'disability-under18AndUnmarried': true\|false,`<br>`'disability-childAttendingSchool': true\|false,`<br>`'disability-reportingDivorce': true\|false,`<br>`'disability-stepchildLeftHousehold': true\|false,`<br>`'disability-deathOfDependent': true\|false,`<br>`'disability-marriageOfChild': true\|false,`<br>`'disability-childStoppedAttendingSchool': true\|false`<br>`});`

**Comment by cohnjesse** [comment] 2020-04-23 20:38
@jonwehausen It looks like the last two key value pairs in the successful form submission data are duplicates of ones earlier in the event. 

dataLayer.push({
'event': 'disability-21-686c-submission-successful,'
'disability-under18AndUnmarried': true|false,
'disability-childAttendingSchool': true|false,
'disability-reportingDivorce': true|false,
'disability-stepchildLeftHousehold': true|false,
'disability-deathOfDependent': true|false,
**'disability-marriageOfChild': true|false,
'disability-childStoppedAttendingSchool': true|false**
});

the bold ones are duplicates, `disability-marriageOfChild` might be a duplicate of `disability-under18AndUnmarried` and `disability-childAttendingSchool` might be a duplicate of `disability-childStoppedAttendingSchool`. For the first one the workflow for the duplicate is `addChild` so using that might make more sense? For the second one I don't think we need an event for both child attending school and child not attending school, we don't have a workflow for reporting a child attending school. Also it looks like we are missing key value pairs for the `addSpouse` workflow and the `report674` workflow. Does that all make sense?

**Comment by jonwehausen** [comment] 2020-04-24 19:51
Hey @cohnjesse ,

Good eye, thank you for this context! As you know, each of these DL variables was designed to correlate with each of the selections on this page: 
![image](https://user-images.githubusercontent.com/48527022/80250214-5ed16980-8641-11ea-98b2-0d2f30ea940b.png)

You're correct in that looks like we were missing ones for add spouse and 674. Below I've listed out each checkbox and what DL variable it should map to, however, if you feel like `disability-marriageOfChild` and `disability-under18AndUnmarried` are duplicates for example we can talk about an alternate. 

The naming convention was designed to capture which checkboxes were clicked, that said if some do not alter the workflow in a meaningful and ultimately reflect any additional insight you would want we can remove duplicates as needed. 

Checkbox | DL variable
------------ | -------------
_Claim benefits for your spouse_ | `'disability-claimSpouse'`
_Claim benefits for your child under 18 and unmarried_ | `'disability-under18AndUnmarried'`
_Claim benefits for your child 18 to 23 years old who'll be attending school_ | `'disability-childAttendingSchool'`
_Report a divorce_ | `disability-reportingDivorce`
_Report that a stepchild under 18 has left your household_ | `'disability-stepchildLeftHousehold'`
_Report the death of a spouse, child or dependent parent_ | `'disability-deathOfDependent'`
_Report the marriage of a child under 18_ | `'disability-marriageOfChild'`
_Report that a child 18 to 23 years old has stopped attending school_ | `'disability-childStoppedAttendingSchool'`

Let's talk about which ones we want to retain.

**Comment by cohnjesse** [comment] 2020-04-27 22:13
@jonwehausen As long as you and the team know which ones are which I'm good with it :-)

**Comment by jonwehausen** [comment] 2020-04-29 13:43
@bsmartin-ep Can work #7560 in tandem

**Comment by jonwehausen** [comment] 2020-06-11 12:39
### Datalayer Update
- Per slack conversation with Jason, we are requesting an addition to the dataLayer to track when a VA File Number is successfully found or not.   

Description | Screenshot | Datalayer Event
------------ | -------- | -------------
When response of API call for VA file number is successfully returned | ![image](https://user-images.githubusercontent.com/48527022/84386192-e86fd300-abbe-11ea-86ac-0c403cf46dd3.png) | `dataLayer.push{(`<br>`'event': 'disability-file-number-gate-successful'`<br>`});`
When response of API call for VA file number is unsuccessfully returned | ![image](https://user-images.githubusercontent.com/48527022/84386239-f9204900-abbe-11ea-8544-803cf4f68f52.png) | `dataLayer.push{(`<br>`'event': 'disability-file-number-gate-failed',`<br>`'error-key': 'xxx_error_description'`<br>`});`

**Comment by jonwehausen** [comment] 2020-06-17 14:52
## QA - WIP

### Test Notes (6/17/2020)
- Currently only able to test with the deep link provided [here](https://staging.va.gov/view-change-dependents/add-remove-form-686c/veteran-information) 
- Currently not able to test a successful submission


Interaction | Screenshot | Data Layer | Pass?
:-- | --- | --- | ---
Submission of 686c | ![image](https://user-images.githubusercontent.com/48527022/84913034-11dda280-b088-11ea-97d3-65be36f2b66e.png) | ![image](https://user-images.githubusercontent.com/48527022/84913100-24f07280-b088-11ea-96d2-9b7b5ca5835b.png) |  **:heavy_check_mark: &nbsp;PASS**
**Failed** submission of 686c | ![image](https://user-images.githubusercontent.com/48527022/84913223-4c473f80-b088-11ea-8dbd-4213db4c9ac7.png) | ![image](https://user-images.githubusercontent.com/48527022/84913267-58330180-b088-11ea-8492-23bf5a49b635.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment] 2020-06-17 15:02
@bmcgrady-ep Could please you begin configuring the goal funnel within GA in the **Non-Prod property Disability and Claims Modernized view**? URLs are most likely still being finalized but we can begin staging according to documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

As a start, take a look at some of the existing funnels we have configured for Education forms for example.

**Comment by joanneesteban** [comment] 2020-06-24 15:55
Adding the `blocked` label until we receive test users for staging.

**Comment by jonwehausen** [comment] 2020-07-08 13:06
Good morning @jason-gcio and @cohnjesse ,

We have attempted to QA this again this morning utilizing user+271, did you have a recommendation on a user we should try? 

Would like to get this this tracking thoroughly tested for you all. Very much appreciated.

**Comment by bmcgrady-ep** [comment] 2020-07-29 22:39
@jason-gcio - Also following up on this issue. Do you have any test users for testing a successful submission event?

**Comment by jason-gcio** [comment] 2020-07-29 23:12
@bmcgrady-ep & @jonwehausen - some great and late breaking news! We think we have this straightened out; can you try vets.gov.user+EBN2@gmail.com with the usual password that has a "Z" in it?  I canDM if that doesn't ring a bell.  They might not any dependents yet actually but it should pass the VA file number check.

**Comment by jason-gcio** [comment] 2020-07-30 20:01
User 1 on this url should get us to where we need to be: https://staging.va.gov/view-change-dependents/view

**Comment by jonwehausen** [comment] 2020-08-06 18:21
## QA - Round 1

### Form Library Events

- @jason-gcio QA of the standard form library events mostly look good! 
- Only case we saw is a small syntax tweak for `sip-form-saved` -- We are seeing the following event taxonomy:
![image](https://user-images.githubusercontent.com/48527022/89567037-089ec580-d7ef-11ea-883e-bae56728d12f.png)
- We will want to adjust to be `disability-21-686c-sip-form-saved` with a hyphen delimitter between `686c` and `sip-form-saved`. 
- @jason-gcio We will also need to revisit when a successful submission is available. 

 -----------------------
### Disability Form Change
- In our [original scope](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7560#issuecomment-613045739) we had mapped out a `disability-form-change` event, we weren't seeing this event configured within staging. 
- That said, the intent of this event is to help better tell the abandonment story prior to submissions, however if that insight is not needed, and we are okay with only understanding the user's selection upon submission -- we can just simply stick with the `--submission-successful` dataLayer variables indicated in the scope above.

**Comment by jonwehausen** [comment] 2020-08-06 18:27
### Next Steps
- Goal funnel mapping: @bmcgrady-ep If you could start mapping out the Goal Funnel for 686c within Non-Prod and Prod according to these URLs that would be very much appreciated. Please do so within the disability modernized view. 
- Where you see `/0/` indicates their may be several versions of the URL depending on how many children/spouses the veteran is needing to put in, so make sure your RegEx logic accounts for the dynamic nature of this url 
- Since this is a dynamic form, it may also be worth going through a couple more times and make sure I didn't miss any along with connecting with Jason to validate.

```HTML
/view-change-dependents/add-remove-form-686c/veteran-address
/view-change-dependents/add-remove-form-686c/add-spouse
/view-change-dependents/add-remove-form-686c/current-marriage-information
/view-change-dependents/add-remove-form-686c/current-marriage-address
/view-change-dependents/add-remove-form-686c/current-spouse-marriage-history
/view-change-dependents/add-remove-form-686c/veteran-marriage-history
/view-change-dependents/add-remove-form-686c/add-child
/view-change-dependents/add-remove-form-686c/add-child/0/
/view-change-dependents/add-remove-form-686c/add-child/0/additional-information
/view-change-dependents/add-remove-form-686c/report-674
/view-change-dependents/add-remove-form-686c/report-674-student-address
/view-change-dependents/add-remove-form-686c/report-674-student-school-address
/view-change-dependents/add-remove-form-686c/report-674-student-last-term-information
/view-change-dependents/add-remove-form-686c/686-stepchild-no-longer-part-of-household
/view-change-dependents/add-remove-form-686c/686-stepchild-no-longer-part-of-household/0
/view-change-dependents/add-remove-form-686c/686-report-dependent-death
/view-change-dependents/add-remove-form-686c/686-report-dependent-death/0/additional-information
/view-change-dependents/add-remove-form-686c/686-report-marriage-of-child
/view-change-dependents/add-remove-form-686c/report-child-stopped-attending-school
/view-change-dependents/add-remove-form-686c/review-and-submit
/view-change-dependents/add-remove-form-686c/confirmation
```

**Comment by bmcgrady-ep** [comment] 2020-08-06 22:31
@jonwehausen - The Goal Funnel for 686c is now staged in both Non-Prod and Prod.

**Comment by joanneesteban** [comment] 2020-08-26 16:29
@jason-gcio - ^ this is in non-prod. Let us know if you need anything around the goal funnel!

**Comment by jonwehausen** [comment] 2020-09-09 17:43
### Reopening to QA test remaining items from successful submission

**Comment by jonwehausen** [comment] 2020-09-14 22:52
### Update
cc: @jason-gcio @cohnjesse - thank you guys again for your assistance here

Will post metadata QA results in a separate comment...here are the key items we identified we will want to correct: 

### Extra Successful Submission Event
⚠️ We are noticing an extra `disability-21-686c-submission-successful` is firing to the dataLayer. This should be corrected to only fire one of these events for each submission and include dataLayer metadata
![image](https://user-images.githubusercontent.com/48527022/93137880-2bed4800-f6ac-11ea-99e4-537c3560e9a2.png)

-----------------------------------------

### Missing `-` as delimitter
⚠️ The save event `sip-form-saved` could use a small taxonomy tweak...currently the event is firing `disability-21-686csip-form-saved`, if we could update to include the extra hyphen delimiter after `686c` and before `sip` that would be great...full event should look like `disability-21-686c-sip-form-saved`. Other form events appear to have this taxonomy correct. 

![image](https://user-images.githubusercontent.com/48527022/93138524-22b0ab00-f6ad-11ea-88d8-0eb4a4195020.png)

----------------
### Add additional `-` to `-submission-successful`
⚠️ This is most likely coming from the tracking prefix -- we like to have two dash marks prior to the `submission-successful` 
 and `submission-failed` ending...full event should look like `disability-21-686c--submission-successful`  | `disability-21-686c--submission-failed`

**Comment by jonwehausen** [comment] 2020-09-15 00:21
## Update
- @jason-gcio & @cohnjesse thanks again for all of your help here -- the logic of the option selections have been tested (see results below) and look great
- @cohnjesse doesn't look like there will need to be any changes here apart from the items we discussed above and via slack. Let us know when we've got those adjustments made and we can circle back and get this issue ticket closed out

## Documentation of Custom Metrics
The following custom metrics have been configured in GA to increment according to submissions involving the selections of checkboxes from the 1st question steps

Custom Metric Index Value | Custom Metric Name | DL Variable
------------ | ------------- | -------------
31 | Disability - Claim for Spouse | `disability-claimSpouse`
32 | Disability - Child under 18 and Unmarried | `disability-under18AndUnmarried`
33 | Disability - Child Attending School | `disability-childAttendingSchool`
34 | Disability - Divorce Reported | `disability-reportingDivorce`
35 | Disability - Step Child Left Household | `disability-stepchildLeftHousehold`
36 | Disability - Death of Dependent or Spouse | `disability-deathOfDependent`
37 | Disability - Child Married | `disability-marriageOfChild`
38 | Disability - Child Stopped Attending School | `disability-childStoppedAttendingSchool`

--------------------

## QA Testing of Submission Option Selections
Description of Test Scenario | Test Case Screenshot | DL Screenshot | GTM Tagging Screenshot |Test Status
------------ | ------------- | ------------- | ------------- | -------------
Selection of first 4 options on `/686-options-selection` page | ![image](https://user-images.githubusercontent.com/48527022/93149155-a07fb100-f6c3-11ea-9a99-79bb95a95dea.png) | ![image](https://user-images.githubusercontent.com/48527022/93149412-42070280-f6c4-11ea-973a-362f28115bb7.png) | ![image](https://user-images.githubusercontent.com/48527022/93149875-9494ee80-f6c5-11ea-9282-866a725c099f.png) | :heavy_check_mark **PASS**
Selection of last 4 options on `/686-options-selection` page | ![image](https://user-images.githubusercontent.com/48527022/93150055-23097000-f6c6-11ea-969c-4f0392fe8f4b.png) | ![image](https://user-images.githubusercontent.com/48527022/93150005-02411a80-f6c6-11ea-846b-1baf6ec070ab.png) | ![image](https://user-images.githubusercontent.com/48527022/93149961-e0e02e80-f6c5-11ea-9060-f6f45bccdedc.png) |  :heavy_check_mark **PASS**
Selection of all options on `/686-options-selection` | ![image](https://user-images.githubusercontent.com/48527022/93150131-52b87800-f6c6-11ea-8ff2-d8155ad8af5b.png) | ![image](https://user-images.githubusercontent.com/48527022/93150483-47b21780-f6c7-11ea-89aa-95076058d5a1.png) | ![image](https://user-images.githubusercontent.com/48527022/93150508-58628d80-f6c7-11ea-82d7-86277854e0df.png) | :heavy_check_mark **PASS**

**Comment by jonwehausen** [comment] 2020-09-16 22:28
### Final Round QA 

Description of Interaction | Screenshot of Interaction | DL Screenshot | GTM Screenshot | Test Status
------------ | ------------- | ------------- | ------------- | -------------
Saving of form | ![image](https://user-images.githubusercontent.com/48527022/93398010-bec2e980-f848-11ea-8e36-021a80f68904.png) | ![image](https://user-images.githubusercontent.com/48527022/93398047-c97d7e80-f848-11ea-94e0-ebc4e2070324.png) | ![image](https://user-images.githubusercontent.com/48527022/93398077-dd28e500-f848-11ea-8e02-46fbeae58016.png) | ✔️ **PASS**
Successful submission | ![image](https://user-images.githubusercontent.com/48527022/93398547-c59e2c00-f849-11ea-9ff5-279baa358ec9.png) | ![image](https://user-images.githubusercontent.com/48527022/93398571-d0f15780-f849-11ea-950b-c030a6da1954.png) | ![image](https://user-images.githubusercontent.com/48527022/93398635-f1211680-f849-11ea-9648-66d3aff3046d.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/93398896-67257d80-f84a-11ea-9ff7-f4b0efcd4646.png) | ✔️ **PASS** <br><br> Confirmed only received 1 `--submission-successful` event and added the double hypen per expectation (`--`)

**Closed** 2020-09-16 22:32 UTC
Labels: analytics-insights, analytics-request, collaboration-cycle, gtm
