### ISSUE TITLE
Design | Profile | Contact Info Documentation Improvements

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43750] opened 2022-06-30 22:29 UTC
### Description

We're in the process of reviewing our product documentation to make sure it is accurate, up-to-date and complete. Similar to the work done recently for Direct Deposit, we will tackle Contact Information next.

[Here is the contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/README.md).

#### All docs
- [x] Clarify abbreviations and add links where it makes sense (e.g. spelling out the full name of a backend service and linking to docs about it)

#### Use cases
- [x] Document all use cases (not just edge cases)

#### Flow documentation
- [x] Wireflow of feature for visual overview

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment] 2022-07-01 17:27
FYI -- Christina put together [use case documentation for the confirmation modal when someone updates their home address](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-change-messaging/use-cases). We can move these around, if needed, to live with general use case docs for all of contact information.

**Comment by andaleliz** [comment] 2022-07-12 20:39
This is in progress, but will need to continue into the next sprint.

**Comment by andaleliz** [comment] 2022-07-19 23:49
Hi @Samara-Strauss and @SKasimow - I think this is just about ready to be closed out! Below is a list of what's been completed. I welcome any feedback, and am especially interested to know if there are any use cases missing that I didn't capture. 

@adamwhitlock1 and @tpharrison, can you please review the BE and FE sections of the main [contact info product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/README.md), as well as the [address validation product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-validation#readme)? Curious if there are any details or links missing that you think would be helpful for Future You or a new dev joining the team.

---
### Documented use cases and user flows
- I created a [use cases folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/use-cases) and added all those I could think of. 
- Other docs now link back to these use cases instead of duplicating information
- Created a high level user flow doc for add/edit/deleting contact information, and added links to Christina's Mural board flow for address change. I don't think it's necessary to duplicate her work from Mural to Sketch, but lmk if you disagree. They're both[ linked in the product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/README.md#flow-diagrams.)
- I'm waiting until @cgednalske  is done with the BAI research to create the use case and flow diagrams for that
- **Question** Are any use cases missing?

### Clean up and reorganization
- Updated and cleaned up the main [contact info product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/README.md), as well as the [address validation product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-validation#readme).
- Moved older research study called "Address updates" inside a new `discovery-and-research` folder, and renamed it to [Address Management April 2020](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/discovery-and-research/address-management-april-2020) so it makes more sense
- Deleted working files related to the address change modal since the information in them is captured in the use cases and the FE build is complete

**Comment by Samara-Strauss** [comment] 2022-07-21 15:56
@andaleliz this is an incredible amount of incredible work! Thank you so much for doing this.

I only have a few minutes before another meeting, so here are some initial notes:

## Contact information

### Product outline

For how to test, I actually don't think we should link back to the overall profile outline (even though I'm the person who did that originally). Can we add info that addresses the following? It should be pretty short and straightforward for contact info:

  - Which staging users can access? (all of them)
  - What do you need to do to test?
  - Do we need to have a backend team (eg. VA Profile) help in any way to be able to test the feature?

## Use cases

> Question Are any use cases missing?

There is nothing that immediately sticks out as missing, but I am reviewing quickly and will let you know if I think of something.

### [Contact information use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/use-cases)

> [User needs to add contact information (addresses, phone numbers, or contact email address)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/add-edit-delete-contact-info.md#adding-information)
> [User needs to edit contact information (addresses, phone numbers, or contact email address)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/add-edit-delete-contact-info.md#editing-information)
> [User needs to remove contact information (home address, phone numbers, or contact email address)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/add-edit-delete-contact-info.md#removing-information)

You can list these all as one thing instead of three things, since they all link to the same document.

As for the "How to reproduce" section of that document, I would clarify that any user can access contact info, and people can test with any staging user to add/edit/remove, with the exception of the mailing address field, as you noted. I do think it's useful to have the two accounts we know of *without* a mailing address listed, but I might actually list that separately and clarify that those users are to see that specific use case.

> [Home address is updated but does not match Mailing address](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/use-cases/README.md)

This link 404s for me.

> [Home address is updated but does not match Mailing address](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/use-cases/README.md)
> [Address can’t be confirmed with USPS, and a suggested address is found.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-validation.md#address-cant-be-confirmed-with-usps-and-a-suggested-address-is-found)
> [Address and/or unit number can’t be confirmed with U.S. Postal Service (USPS), and a suggestion is not found.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-validation.md#address-andor-unit-number-cant-be-confirmed-with-us-postal-service-usps-and-a-suggestion-is-not-found)
> [Address is missing a unit number](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-validation.md#address-is-missing-a-unit-number)

Same as above -- you can list these as one item instead of four since they all go to the same place.

**Comment by SKasimow** [comment] 2022-07-21 16:43
Hi Liz - this looks great!

**Comment by andaleliz** [comment] 2022-07-21 19:32
Thanks for the feedback! I've made all the updates you recommended @Samara-Strauss. I'll stay tuned for more before closing this out. I also completed all the user flows by now.

**Comment by Samara-Strauss** [comment] 2022-07-21 19:41
Just reviewed the address validation stuff as well, and everything looks good to me. I didn't test all links like last time, but the overall content looks great. This is outstanding! Thank you so much for all your help.

**Closed** 2022-07-22 13:21 UTC
Labels: documentation, vsa, vsa-authenticated-exp, profile, contact-information

**Comment by adamwhitlock1** [comment] 2022-07-22 17:08
@andaleliz I think this all looks good overall, sorry I hadnt had a change to look at them till now.

One thing I quickly updated was removing adding myself and @tpharrison to the outline for address validation and removing old engineers
