### ISSUE TITLE
[CAIA Intake] [a11y Support] Ongoing screen reader testing with Chatbot MHV Prescription Skill team

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#68026] opened 2023-10-19 21:23 UTC
## a11y Assignees
`Based on participation in the chatbot audit. 
`
- @sara-amanda 
- @SarahKay8 
- @coforma-jamie 
- @eli-oat 

## VA Chatbot Team

- **Team name:** VA Chatbot (MHV Prescription Skill Team)
- **OCTO-DE product owner:** @LucianaAlexanderMorais and @nathalierayter 
- **Product manager:** @Joy-Elizabeth 
- **Designer:** @mterwilliger 
- **Accessibility specialist:** NA
- **Content writer:** NA
- **Slack channel:** [#va-virtual-agent-public](https://dsva.slack.com/archives/C01KTS3F493)
 
### Describe what you need in a few sentences:

Chatbot MHV Prescription Skill team is making progress to address a11y concerns. This is a request to get assistance from CAIA members to partner with the team and validate these fixes as they go with JAWS and other screen readers.

<details><summary>Toggle to view support request details</summary>

### Which are you doing?
- [x] **Launching a new** page, tool, form, or app
- [ ] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [x] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content

</details>
 
## Timeframe

_Chatbot MHV Prescription Skill was scheduled to ship today (Oct. 19, 2023) but the team needs to address a11y issues before they can ship as well as Rx content issues._ 

<details><summary>Toggle to view timeframe details</summary>

_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** to work on addressing all of the findings from staging and delineate what needs communicated to Microsoft. 
- **Provide date if available**: `TBD`

#### Timing for your next step: 
  - [x] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
</details>
  
## Collaboration Cycle
_Staging review is already completed._ 

<details><summary>Toggle to view Collaboration Cycle details</summary>
 
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No (staging review is complete) #66754 

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #61873
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [x] Midpoint Review
- [x] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
 
</details>
 
## Supporting artifacts
_Refer to the `Related Tickets` section at the bottom of this ticket._ 

<details><summary>Toggle to view intake ticket supporting artifacts</summary>

*Please provide links to supporting artifacts as available.*
- **Product outline**:
- **User flows**:
- **Prototype or mockups**:
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:**
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 
</details>

## Additional Support

<details><summary>Toggle to view additional support details</summary>
 
#### Have you already worked with someone from OCTO leadership?
- [x] Danielle
- [ ] Beth
- [ ] Mikki
- [x] Martha

#### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.
</details>

## Next steps
_`Task lists` can be found at the bottom of this ticket._
<details><summary>Toggle to view next steps for an intake ticket</summary>

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

</details>

### Nov. 1, 2023
- **CAIA A11y Sync and Feedback:** 11/1/2023 ([Shared via Slack](https://dsva.slack.com/archives/C01KTS3F493/p1698868772911999))
- Link to [Deliverable provided](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/CAIA/accessibility/Deliverables/VA%20Chatbot/2023-11-01-virtual-agent-feedback.md) to the Chatbot Team

#### Topics Discussed: 
- Chatbot Team Progress on the Accessibility Defects
- Challenges Chatbot Team is Facing
- Clarifications and questions from Chatbot Team

<details><summary>Toggle to view an overview of a11y-related support given during CAIA Office Hours on 10/31/2023</summary>

- **Attendees:**  `1` Team: Chatbot Team
- **Support types:** `Accessibility`
- **CAIA Presence**: `Sara`and `Lily`
- **Group Needing Support's Slack Channel:** [va-virtual-agent-public ](https://dsva.slack.com/archives/C01KTS3F493)
- **Resources Exchanged:** 
    -  #67376 
    - [Links to the Chatbot Playbook in Column A of the Deliverable](https://docs.google.com/spreadsheets/d/1KY_apLWtdDMxbA42sfuDqC81umA3yF1Yt5NwXZqbEYE/edit#gid=98119274)
    - **Chatbot Team** [Chatbot Team Ticket #1201](https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1201). 
        - **Asking CAIA:** Would the [Microsoft recommendation](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#ux-navigating-activities-in-the-chat-history) of the [Grid Layout Widget](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) be applicable here (see W3 standards).
    - #67309 
    - **Screen Recordings:** Anita added a comment with the [recordings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67309#issuecomment-1788042975) they showed on 10/31/2023 [#67309](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67309).

</details>

<details><summary>Toggle to view an expanded view of a11y-related notes from 10/31/2023</summary>

#### Keyboard Navigation

- **Scroll with a mouse and scroll up and down smoothly with arrow keys.** 
    - Similar functionality in our chatbot. 
    - Keyboard navigation instead of the smooth scroll it jumps from message to message. 
    - **Not their expectations** - _Governance Team_ 
- **Use a semantic tool to look at Dev tools to mitigate those issues.** 
    - **Raina**: Recommendations that were given from the findings, made those changes to see if we could achieve the desired behavior. Using some of the pattern for a grid widget, that is why we are able to use up and down arrow keys in the chat history. 
    
> **Question**
 _Since Microsoft has done research on best practices, on applications similar to our chatbot. Is that a guideline that we could be following?_
>- Chatbot Team [Chatbot Team Ticket #1201](https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1201) 
>- Would the [Microsoft recommendation](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#ux-navigating-activities-in-the-chat-history) of the [Grid Layout Widget](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) be applicable here? (see W3 standards). 

##### VoiceOver // Windows NVDA // JAWS 
- [CAIA Card Ticket #67309 related issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67309): Instead of reading every message out, the screen reader for VO will not read them one at a time, as they are appearing. 
    - Microsoft would be submitting a ticket to VoiceOver. 
    - They can look into it. 
    - Microsoft is not able to replicate it.
    - Inconsistencies within VoiceOver using the same flow. 

#### Adaptive Cards // Larger Blocks
- **How they are being read out … have implemented some changes:** 
    - Decided to add a delay based on the number of characters in the message itself. 
    - Depending on how long the message is, added a slight delay, increase the delay in between messages, when a bubble appears, to give the user more time to understand the message delivered by the SR. Give them more time to react to the message as well, if certain actions need to be delivered. 
    - This helps to get around messages appearing too fast. 
    - The next change, for the adaptive card, they have added a summary to that card, so that it actually displays key characteristics, summary to let the SR know that a card is being displayed on the screen, use keyboard to get elements within the card. 
    - It improves the experience. 
    - **Video from Anita shown.** 
        - Display message → Delay → adaptive card → delayed 
        - Separate outputs with delay in between
        - It takes longer for the message to be there. 
        - Summary of the adaptive card reading is off a bit, previously it would have been skipped. 
            - Speech synthesis markup language being read. 
                - That same tag is being used by the SR. 
                - Jaws reads that correctly, VO does not, and reads it as intended.) 
                - There is some inconsistency across screen readers, the speak tag of the adaptive card, and how it works across SR.
- **Microsoft’s Expectations vs VA Expectations how to navigate:** 
    - Summary of the card, but you would need for keyboard navigation to dive into the card to be able to get to each of the fields. 
    - Speak tag to the card as a whole, card and short description, like a caption on an image as a summary. The intent of the speak tag is not to expose every text content in the card itself. Expectation is that if the user wants more details and what labels and values that they can use the keyboard to navigate in the chat history to get into the card to get the detail. 
    - _**Functionality as expressed by Microsoft. ^**_
    - **Additional information** - originally this functionality was for a voice experience with no screen at all. Screen you got a card if no card summary text above and ability to ask follow-up questions. This functionality still exists. The experience can stand without that card being read out on a screen reader because the reader has the ability to ask other questions. 
    - No Microsoft Documentation - Mark Tucker. 
    - **_Read off one at a time so that navigation only goes to the previous one, in the event there are multiple prescriptions._** 

#### Questions
- **Is it possible to create a VoiceOver Transcript?**
- **Overarching Categories (team is thinking this through further - how to approach):**
    - Face-Value Feedback
    - Limitations of Microsoft 
    - VA Standards
- **Next Time: Chatbot Team Will** ... 
    - Go over the cards and come back with the essence that is remaining … Microsoft or CAIA support. 
    - Level 1 Feedback Impact so far? 
    - Defect at face value - Microsoft’s feedback on behavior and how it relates to the VA standard. 
- **Current Approach by Chatbot Team**
    - Overarching themes SR and Keyboard Navigation Issues
    - Are there any other overarching umbrellas for feedback to see if anything is missing.
- **Should we consider the W3 Patterns, based on feedback from Microsoft?** 
- **Who owns the VA Accessibility Standards?** (DST/USWDS) 
</details>

<details><summary>Toggle to view Oct. 31, 2023 Chatbot future sync information</summary>

## CAIA Future Sync on Chatbot
- CAIA is going to meet and discuss the items mentioned in Office Hours on `11/1/2023`.
- CAIA will update the Chatbot Team, with feedback when finalized. 
</details>

### Oct. 20, 2023
**Topic Discussed:** Big buckets are keyboard navigation and screen readers for now.
<details><summary>Toggle to view Oct. 20, 2023 Chatbot updates from Nathalie and Joy</summary>

[c/o Nathalie on 10/20/2023 via DSVA Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1697815335357489?thread_ts=1697750893.578519&cid=C01K37HRUAH) @nathalierayter 

> Right now, we are going to prioritize investigating the following issues that we think **may have to be punted to MSFT and/or result in technical debt for us (MHV Chatbot RX Team).** 
> 
> **So big buckets are `keyboard navigation` and `screen readers` for now.** 
> - This just represents the current focus. 
> - There is of course more we can tackle, and we hope to engage with y'all to make sense of those issues and prioritize together!

[c/o Joy on 10/20/2023 via DSVA Slack](https://dsva.slack.com/archives/C04NXEQM8TY/p1697833484660359) @Joy-Elizabeth 
Joy's [accessibility issue tracking spreadsheet (Google Sheet)](https://docs.google.com/spreadsheets/d/15rwVvmmgz-WdgAGoofcBE9p4Y4rKRIWZwW8WLWgJsTQ/edit#gid=0)

> Our Zenhub board will be the single source of truth for our devs to look for prioritization and details of these. This is for organization purposes only.
> Note: items that are completed, those rose are hidden.
</details>

### Additional Updates

<details><summary>Toggle to view additional Chatbot updates</summary>

`Placeholder for future updates`

</details>

```[tasklist]
### Chatbot Team
- [ ] **KEYBOARD NAV:** Page functionality is not keyboard accessible
- [ ] **KEYBOARD NAV:** Content causes the user's keyboard focus to get trapped
- [ ] **KEYBOARD NAV:** Custom keyboard navigation interfering with default navigation patterns
- [ ] **SCREEN READER:** Screen reader does not read content from all cards, only most recent
- [ ] Microsoft Progress Update to CAIA and OCTO
- [x] Office Hours: Angela Fowler might be able to demonstrate the experience of using a screen reader for context.
- [x] Attend CAIA Office Hours or Schedule a Meeting with CAIA A11ys
```
```[tasklist]
### Related Tickets
- [ ] #61873
- [ ] #66754
- [ ] #67376 
```
```[tasklist]
### CAIA a11y Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68359
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68963
- [x] 11/1/2023 - Post-Office Hours [Deliverable provided](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/CAIA/accessibility/Deliverables/VA%20Chatbot/2023-11-01-virtual-agent-feedback.md) to the Chatbot Team via [Slack](https://dsva.slack.com/archives/C01KTS3F493/p1698868772911999)
- [x] **WATCH** Slack channel for incoming questions relating to a11y fixes for Chatbot
- [x] **EMBED:** Embed two CAIA Team Members [per Martha](https://dsva.slack.com/archives/C0335Q88X0S/p1698936039698199?thread_ts=1698863448.895659&cid=C0335Q88X0S)
- [ ] **FUTURE ITEM:** Coordinate another meeting to sync on a11y issues with Chatbot Team
- [ ] **DEFINITION OF DONE**: Work with OCTO for Definition of Done, high-level priority items and aligning on launch-blocking items (Martha, Danielle, Chatbot Team and a11ys)
- [ ] **R&D:** Inquire about other chatbots (check with POs) - @eli-oat
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68968
```

```[tasklist]
### OCTO (Martha & Danielle)
- [ ] 508 Office Meeting w/o 10/30/2023: Regarding Mobile Testing in General (Martha)
- [ ] Follow-up with OCTO contracting re: mobile devices for testing (Martha)
- [ ] Content topics needing "sign off" from clinicians before shipping (Danielle)
- [ ] Definition of Done (Martha and Danielle)
- [ ] Determination of final ship date for Chatbot RX based on remaining work (Martha and Danielle)
- [ ] Ok given to embed 1 or more CAIA Team Members on MHV Chatbot
```

**Comment by sara-amanda** [comment] 2023-10-20 20:49
## CAIA Ticket Updates
- [x] Task lists, based on linked slack communications
- [x] References previous related tickets, for connectivity
- [x] Assignees have been added, based on previous audit involvement
- [x] Project team slack linked and team members tagged
- [x] Intake renamed
- [x] Sections collapsed with toggles
- [x] GHP fields updated
- [x] Ticket moved from "`new stuff`" to "`in progress`"

**Comment by sara-amanda** [comment] 2024-01-08 15:46
@eli-oat are you able to update this ticket, based on your close work with the chatbot team, post swarm?

**Comment by Joy-Elizabeth** [comment] 2024-01-24 23:11
**Chatbot updates:** 
KEYBOARD NAV: Page functionality is not keyboard accessible _- dependent on MSFT updates,_ **not done**
KEYBOARD NAV: Content causes the user's keyboard focus to get trapped _- dependent on MSFT updates,_ **not done**
KEYBOARD NAV: Custom keyboard navigation interfering with default navigation patterns _- dependent on MSFT updates,_ **not done**
SCREEN READER: Screen reader does not read content from all cards, only most recent _- dependent on MSFT updates,_ **not done**

I am adding our VA Chatbot Accessibility Specialist here so she has visibility and tracking purposes. @anitadewitt-va 

I am adding our new VA Chatbot Product Manager here for visibility and tracking purposes, since I will be rolling off. @patilvrushali

**Comment by anitadewitt-va** [comment] 2024-02-01 16:13
@eli-oat To address "Microsoft Progress Update to CAIA and OCTO"

**Comment by eli-oat** [comment] 2024-02-05 16:55
@anitadewitt-va I checked in with @artsymartha68 who confirmed I'm good to close this -- we're all aligned on the info we need.

**Closed by eli-oat** 2024-02-05 16:55 UTC
Labels: sitewide CAIA, sitewide accessibility
