### ISSUE TITLE
4 Modifications to Tagalog Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#87810] opened 2024-07-08 17:28 UTC
## Description
We received feedback from the State Department for our recent Tagalog translations.

## List of Modifications

1. Highlighted text until … “personal,” should not be in bold per source

    <img width="415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXEvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c9de50f37ff3751720c4f1c656c65c630e1b577/image.png" alt="image.png" />

2. All dates should be in Tagalog (see this [reference](https://discover.hubpages.com/education/How-to-Tell-the-Date-and-Time-in-Filipino-or-Tagalog-Language))

3. Highlighted text needs to be “pagkakakulong”
    <img width="396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXkvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2389ed371af02ed0546a4637cf795f36ee4515c9/image.png" alt="image.png" />

4. Highlighted text needs to be “tinatanggap”
    <img width="320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXUvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdd97a33068e90ac135dcd3b570e4e27a31fac6b/image.png" alt="image.png" />

**Comment by loripusey** [comment] 2024-07-08 17:32
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/87810?planning-poker) with Zenhub @brianseek @wullaski

**Comment by wullaski** [comment] 2024-07-09 12:55
@loripusey I can't see the images in the description.

**Comment by wullaski** [comment] 2024-07-09 12:59
@brianseek I'm looking at our date i18n utility and it looks like we are only doing English and Spanish. Was there a reason for that? My estimate could be off since I'm not sure what the level of effort will be to add Tagalog to that utility.

**Comment by loripusey** [comment] 2024-07-09 13:08
I'll paste the images in Slack, I see them

**Comment by brianseek** [comment] 2024-07-22 15:37
I spent some time focused on just the date element of this. Our application uses [date-fns locales](https://date-fns.org/v3.6.0/docs/I18n) to accomplish our date translations. The problem is that there is no Tagalog locale in the library. There have been a couple of issues to add it, but no traction.
https://github.com/date-fns/date-fns/issues/1208
https://github.com/date-fns/date-fns/issues/3343

We could add one our selves and open a PR to have it added and patch it in the mean time. But we would need to setup the module then work with the state dept. to a get full set date translations. This would be a decent sized lift.

Still looking into alternative options that just cover the few date scenarios that we use.

**Comment by brianseek** [comment] 2024-07-22 17:15
@loripusey The text update portion of this work is ready to validate in the following screenshots:
<img width="144" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDM3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed11227f14bc5eb854039bfc111e4ccc1c7370a6/localhost_3001_health-care_appointment-check-in_travel-vehicle.png" alt="localhost_3001_health-care_appointment-check-in_travel-vehicle.png" />
<img width="102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDc3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fa19ad260e5900d79ed411912d36e2b8546c35b/localhost_3001_health-care_appointment-check-in_travel-vehicle%20%281%29.png" alt="localhost_3001_health-care_appointment-check-in_travel-vehicle (1).png" />

**Comment by loripusey** [comment] 2024-07-22 17:24
Looks good to close.

**Comment by brianseek** [comment] 2024-07-22 17:29
closing this ticket, code review and merging to take place in this ticket for next sprint: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/88841

**Closed by brianseek** 2024-07-22 17:29 UTC
Labels: frontend, HCE-Checkin
