### ISSUE TITLE
Implement "Pending" Items into RD Staging

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1992] opened 2019-09-24 16:03 UTC
## Story
Once `pending disabilities` has been located, we want to build it into the "View My Rated Disabilities" page on staging so that we can test it further and eventually deploy it.As a backend engineer, I want to know how 'pending disabilities' are generated and defined, and where they live, so I can query that data and send it to the appropriate frontend application for consumption.

## Considerations
- Upon clicking for more information on a pending item, the user is taken to the Claim Status Tool
- If this appears to be a dead-end, note findings and discuss

## Tasks
- [ ] Query data from the `vets-api` and send it to the appropriate front end application for consumption.

## Definition of Done
- [ ]  `pending disabilities` has been found and can be sent to the frontend

**Comment by micahchiang** [comment] 2019-09-24 22:23
@jason-gcio, @kathleencrawford  - This feels like a duplicate of #1890, should we consider closing this out?

**Comment by micahchiang** [comment] 2019-09-24 22:24
Oh wait, I just realized that this is the implementation ticket that follows up #1890. Maybe we can update the user story so it reflects more implementation that research?

**Closed** 2019-09-26 23:34 UTC
Labels: vsa, vsa-ebenefits
