### ISSUE TITLE
  Business intake form for Visitor Engagement Reporting Application (VERA)

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/va.gov-team#28680] opened 2021-08-12 19:15 UTC
## What is the business outcome you are trying to achieve? (required 1-2 sentences) 

Leverage SMS to support the implementation of a centralized system for scheduling appointments which is accessed via a public VA internet page. The organization also strives for process efficiency by implementing a singular scheduling application to replace disparate technology and manual systems being used by varying RO.

## What is an overview of the notification use case? (required 3-5 sentences) 

Users are able to use the VERA app to schedule RO appointments for various service support needs. As part of the ability to track/manage their own appointments users consequently receive automatic notifications for the following: booking confirmation, appointment reminder (1 day prior to appointment), appointment rescheduling confirmation, and appointment cancellation confirmation.

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 

Users log into a dedicated SF platformed scheduling portal from the web to schedule appointments. As part of the ability to track/manage their own appointments, users consequently receive automatic notifications for the following: booking confirmation and an appointment reminder (1 day prior to appointment).  The appointment confirmation notification contains a link that is used by the user to reschedule or cancel appointments.  Upon either action appointment rescheduling confirmation and appointment, cancellation confirmation notifications are received.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 

Currently, automatic system email notifications are being sent within the VERA application.  These emails would likely remain minimally for users who prefer email to texts. Additionally, texts are being sent by one RO who is using an external application that was not specifically built for VA use.

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 

We don’t have it at the moment but would be able to provide it at a later date.

## Have you spoken to your Privacy Officer about your content/use case and has it been approved? (Yes, No, Not Sure) 

We are replacing the use of a non-fedramped app leveraging SMS capabilities that had been approved for the same use case. Our application has also undergone security review and approval. Based on these factors we expect no additional privacy/security concerns which would mitigate moving forward with this SMS use case.

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 

The notification will be triggered from Salesforce.

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 

We anticipate some additional configuration work will be required but details as to what logic specifically-  will need to be defined based on gathering additional insight around the VA Notify for VERA implementation.

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure) 

Not sure (to be determined based on parameters defined by VA Notify technical requirements)

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure) 

We expect to have access to budgeting but further detail and certainty will need to be defined based on total level of effort, operating costs, etc.

## What is your estimated volume of notifications per day, week, month? (optional - open space) 

FY 2022 Go-Live Forecast: 56k/ mo or 672k/yr

We also want to account for year over year growth for FY 2023 and FY 2024 as follows:

FY 2023: 112k/mo or 1.3M/yr

FY 2024: 224k/mo or 2.6M/yr

## When does this notification need to be in production? (optional - open space) 

Base SMS functionality is desired within the current calendar year.

**Comment by ffafara-tw** [comment] 2021-09-07 17:50
**9/7/2021 meeting notes:**
- unauthenticated users can go to web app (salesforce) to schedule appointments
- during that process they can provide contact information (email/phone number) and grant any necessary consents
- for opt outs as base minimum we could use AWS opt out feature (global black list) or build our own black list that would be per number / use case
- will need to think through a proper `opt back in` process
- there is time pressure from customers -> need volume estimates to see if we need to provision short code

**Comment by ffafara-tw** [comment] 2021-09-07 17:52
@toddstanich anything else we should capture?

**Comment by toddstanich** [comment] 2021-09-07 18:13
**Adding notes from the previous meeting (9/2)**
• Users: visitors to VBA office
• Visitors are usually Veterans, but not always
• Delivered MVP, allow VA employees to schedule appointments for Veterans. Allows Veterans to self schedule as well.
• Need SMS capability - right now any notification that goes out automatically via email
• Currently using Waitwhile - not Fedrampped application (originally for food service)
• Goal: Get ROs off of non-fedramped solution and stop additional ROs from getting on the solution

**Notifications**
• Book -> confirmation
• Reschedule -> confirmation
• Within notifications - visitor relies on receiving a link to be able to access their appointment (no account created)
• Reminders - you have a scheduled appointment one day prior. Embedded link within the notification 
• Emails automatically generated as part of the flows/logic already configured. Out of box from Salesforce
• Two-way SMS if they need to communicate out to visitors and have them respond

**Comment by miabecker** [comment] 2021-09-23 13:49
Original email: 


From: Stein, Andrew J. (Liberty IT Solutions)-Orlando <Andrew.Stein2@va.gov>
Sent: Friday, July 30, 2021 8:45 AM
To: Fafara, Filip (Liberty IT Solutions) <Filip.Fafara@va.gov>; Radle, Timothy L.(Liberty IT Solutions) <Timothy.Radle@va.gov>; Becker, Maria S. (Liberty IT Solutions) <Maria.Becker@va.gov>
Cc: Mashburn, Travis S. (Liberty IT Solutions) <Travis.Mashburn@va.gov>; Schuck, Timothy G.(Liberty IT Solutions) <Timothy.Schuck@va.gov>
Subject: VANotify Inquiry

 

Hi,

 

I’m with Liberty/BAH and do a lot of integration work with VA Salesforce. Recently I’m getting asked about handling SMS notifications to veterans from Salesforce modules and I had ran across VANotify mentions before. I have a few questions:

 

From the github readme, I see mentions of AWS, so can I assume you are hosted in an AWS VAEC account (probably BPE 311, 312, 313 like us?)
Do you currently have any integrations with VA Salesforce modules. For Salesforce to talk to our APIs required ESECC RFCs from their BPEs (first 320 Salesforce GovCloud and now 314 for Salesforce GovCloud Plus)
If there is no direct connection between Salesforce and VANotify, either they could submit the ESECC RFC requesting it, or we could proxy their API calls to you as DVP/DIP is sort of the Gateway for all VA Salesforce connections to VA backend SORs. Thoughts?
 

Thanks,

Andy

**Comment by bevnobev** [comment] 2023-05-18 18:58
@mjones-oddball Here is the VERA ticket I mentioned earlier today

**Comment by mjones-oddball** [comment] 2023-08-04 20:19
Duplicate of - https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/issues/gh/department-of-veterans-affairs/va.gov-team/61688

**Closed** 2023-08-04 20:18 UTC
Labels: vanotify-intake
