### ISSUE TITLE
Access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#32641] opened 2021-11-09 14:27 UTC
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Kevin Duensing

### Your Email

kevin.duensing@va.gov

### Name of Your Team

Platform Spike Teams - Access Management

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJSF+tp91ZItgwV8wb4fv6gKn2hLU+QPwUzxZQmxn90qJvtgGjGe+u1j2fobn45osgwTlNHRK0CtIykVrY46rxYqEqHxKhTMQM4UeTbrjLUDdvcpRcQQjJUXCP0pzK0/EysQHCVARzhhb63gtFUyec7JiAvsqjbNC0ThkcOPsVhTNMCeaQamvyx9RAWB9LdkdSP0SHr+f01MvHWVRkCdbiUfREYdrVvKswIPKHYr4TqWjqJ6MZZTZ0POdAk5JbHds1lZGbE24zK5WL04yry2sbo30TDvgY3iS8xwNsTECm9vSqo2oNbkftEhmZ3Vj0IC/ynmup4U9m+r70IHSlHPD/PSwkZtNJWoV43b/j2Ghl5xve93t9tuy6ZyD7HVb913/ldJXpRXNL8/izGeySQpFTsv3Q1879U3smtTOySYqmpz2bN2q683C+Loe/BP6L3r3hHXnW88XjjV/o763EnifxOGqoDAJYQJ+8NnHemB0Ti80AxfQVc70r4JfnzwkEtXM= kevinduensing@kevin-macbook.lan

### Desired AWS Services

platform-amt role

**Comment by kjduensing** [comment] 2021-11-09 14:27
My onboarding representative has been Sabrina Ammon: Sabrina.Ammon@libertyits.com | Sabrina.Ammon@va.gov.

Thanks!

**Comment by mleclerc00** [comment] 2021-11-23 18:29
Hi @kjduensing 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

Can you confirm that socks is working as intended so we can close this ticket?

Thanks!

**Comment by mleclerc00** [comment] 2021-11-29 17:39
**For AWS Access:**
User: Kevin Duensing
COR: Cecila Lee
Approval needed: @mchelen-gov

**Comment by mchelen-gov** [comment] 2021-12-08 20:36
@mleclerc00 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by mleclerc00** [comment] 2021-12-09 19:23
aws account information passed along to Kevin, closing this ticket

**Closed by mleclerc00** 2021-12-09 19:23 UTC
Labels: operations, external-request, ops-access-request, AxMan PST
