### ISSUE TITLE
BUG: Basic auth page showing up in search and going to 401 error page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14474] opened 2020-10-06 20:13 UTC
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

1. I searched for debt management on our site (onsite search): https://www.va.gov/search/?query=debt+management
2. On Chrome, on VA network. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/1823d244-82d5-4ec4-b4f9-673b051af42b)

3. One of the results was a modern VA.gov looking benefit hub page - see screen shot. Wehn I clicked on the link, it gave me a 401 error (see screenshot). 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/6fd3c9d4-e210-416b-84b4-888bc7ff6993)

If this page is not available yet without basic auth, it should have a noindex to prevent it coming up in searches.

**Comment by johnhashva** [comment] 2020-10-07 14:51
Looks like this page is in the https://www.va.gov/sitemap.xml

<img width="330" alt="Screen Shot 2020-10-07 at 10 48 27 AM" src="https://user-images.githubusercontent.com/63107147/95347442-e414a780-088a-11eb-9a6d-b0873e2e9454.png">

But now that auth has been removed does this matter -- and can we close this one?

**Comment by DanielleThierryUSDSVA** [comment] 2020-10-07 16:34
We archived this page in Drupal because the debt management team were told to pull it down. So it definitely needs to not show up in search. Will look into it Drupal as well.

**Comment by mnorthuis** [comment] 2020-10-07 16:47
It needs to be removed from the sitemap if its going to be down for an extended period of time.  We should also look at where Google is picking it up (if they are) and how to temporarily remove it from search.gov index.  We may need to put a temporary redirect on it to go back the legacy site if it was already indexed.

**Comment by DanielleThierryUSDSVA** [comment] 2020-10-13 14:32
@mnorthuis My understanding from the team is that this page will be down until January. I think that qualifies as extended period of time. Do you agree? I think a temporary redirect could work nicely. 

I did go into the Drupal page and no-index it, but I don't know that that will do anything if it was already indexed and it's no longer published.

**Comment by mnorthuis** [comment] 2020-10-13 16:18
A temporary redirect would be helpful since the URL is out there in the wild so users do not get a 404.  Can you open a redirect request for that?

**Comment by brianalloyd** [comment] 2020-11-10 18:45
@johnhashva should we transfer this over to the new Search Team?

**Comment by mnorthuis** [comment] 2020-11-10 18:50
Issue #14806 implemented a temporary redirect for the page to resolve the 404.  Technically it should also be removed from the xml sitemap.  I'm not sure who is technically the owner/manager of the xml sitemap.

**Comment by johnhashva** [comment] 2020-11-10 20:15
@brianalloyd Yes -- we will take Site Map updates.  Thanks!

**Comment by jenniferlee-dsva** [comment] 2020-11-10 20:59
Just pointing out that I reported this weird bug on Oct 6. Then on Oct 7 @johnhashva said that the page became available without basic auth gate. So - this might be moot point now, as we are in Nov and theoretically the page is now live and ungated (I haven't checked).

**Comment by brianalloyd** [comment] 2020-11-10 21:48
@jenniferlee-dsva great point.  Sounds like we might be able to validate and close out this ticket.  @johnhashva do you want to confirm and I'll close out once validate?  Thanks everyone for the assistance.

**Comment by johnhashva** [comment] 2020-11-12 16:48
@brianalloyd per this Slack thread, @srsuddath (with @denisecoveyduc FYSA) are going to noindex the following URL in the VA.gov sitemap -- http://va.gov/manage-va-debt/your-debt -- before we close this one.

<img width="476" alt="Screen Shot 2020-11-12 at 10 58 35 AM" src="https://user-images.githubusercontent.com/63107147/98969463-dc28d280-24dc-11eb-8e89-3017e53f147c.png">

**Comment by johnhashva** [comment] 2020-11-12 16:49
@denisecoveyduc a good opportunity for Sam to become familiar with the VA.gov site map xml.

**Comment by mnorthuis** [comment] 2020-11-12 18:33
@johnhashva We shouldn't have a noindex in the xml sitemap, that provides conflicting information to search engines - the xml sitemap tells them what to crawl and then says don't crawl.  We should remove this entry from the xml sitemap and resubmit the sitemap to google.  The temporary redirect will take care of any traffic that finds its way.

**Comment by johnhashva** [comment] 2020-11-12 18:36
@denisecoveyduc let's prioritize this small task in today's grooming session.  Be a good small problem to solve right-away.  TY.

**Comment by denisecoveyduc** [comment] 2020-11-12 19:59
@srsuddath will review and strive to work on this in Sprint 34

**Comment by srsuddath** [comment] 2020-11-16 18:21
@ncksllvn Hey Nick, I have been told to reach out to you and get some info on how to take care of this? Is that something you can drop me a quick how to? or do we need to set up a call?

**Comment by ncksllvn** [comment] 2020-11-16 18:28
I think this is resolved already. I don't see any paths beginning with `/manage-va-debt/` in the sitemap and I don't see the page showing in search results anymore either.

**Comment by johnhashva** [comment] 2020-11-16 18:37
^^^ confirmed.  Closing ticket.

**Closed by johnhashva** 2020-11-16 18:37 UTC
Labels: bug, frontend, needs-grooming, vsa-search-discovery
