### ISSUE TITLE
Add feature into the Webpack build to single applications and an array of applications

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29134] opened 2021-08-24 15:23 UTC
## Description

Webpack current runs a full build of all applications each time. We want to add a feature be able to build single, multiple, or all applications.

## Definition of Done

- [x] Webpack can build files for a single application
- [x] Webpack can build a list of applications
- [x] Webpack can still build the full application suite
- [x] The custom build command can be called in CI (Github Actions)

**Comment by meganhkelley** [comment] 2021-09-01 17:38
Out of scope: unit tests, end to end tests, anything with test selection 

But we might already have the ability to run isolated unit tests?

**Comment by theodur** [comment] 2021-09-02 03:59
I don't know why this slipped my mind during sprint planning, but we already have a way of doing this. Passing the `--entry` flag with the entry name of the app will only build the app's bundle, along with the shared modules. You can pass multiple entry names with this option too.

**Comment by theodur** [comment] 2021-09-03 18:54
After testing the `--entry` flag in GitHub Actions, the single application builds themselves work as expected. Only the application bundles along with shared modules are built. Production builds seem to take on average 1-2 minutes.

The issue is with the test selection that occurs for Cypress tests. The application specific Cypress tests pass just fine, but because test selection always runs **all** Cypress tests in the `src/platform` directory, most of those tests do not pass. This is because tests in the `src/platform` directory use other applications for testing. For example, the forms system test `src/platform/forms/tests/save-in-progress/01-sip-review.cypress.spec.js` uses the `hca` app for it's tests, and because the bundle for `hca` isn't built for other single app builds, this test will always fail.

Regardless, even if all tests in the `src/platform` directory passed, single app deploys would still be dependent on platform tests with how test selection currently works. So if there is a bug or flaky test in the `src/platform` code, single app builds will fail, even though that application isn't related to the flaky platform test.

Here is a list of the platform Cypress tests that run in every CI workflow:
- [src/platform/forms/tests/save-in-progress/01-sip-autosave.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/tests/save-in-progress/01-sip-autosave.cypress.spec.js)
- [src/platform/forms/tests/save-in-progress/01-sip-finish-later.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/tests/save-in-progress/01-sip-finish-later.cypress.spec.js)
- [src/platform/forms/tests/save-in-progress/01-sip-load-fail.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/tests/save-in-progress/01-sip-load-fail.cypress.spec.js)
- [src/platform/forms/tests/save-in-progress/01-sip-review.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/tests/save-in-progress/01-sip-review.cypress.spec.js)
- [src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js)
- [src/platform/site-wide/side-nav/tests/e2e/sideNav.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/side-nav/tests/e2e/sideNav.cypress.spec.js)
- [src/platform/site-wide/tests/sanity-check/smoke-test.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/tests/sanity-check/smoke-test.cypress.spec.js)
- [src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js)
- [src/platform/site-wide/user-nav/tests/user-nav.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/tests/user-nav.cypress.spec.js)
- [src/platform/user/tests/unauthed-flows.cypress.spec.js](src/platform/user/tests/unauthed-flows.cypress.spec.jshttps://github.com/department-of-veterans-affairs/vets-website/find/master)

**Comment by theodur** [comment] 2021-09-03 23:46
At first, it looked like the only problem with test selection was that is runs all platform Cypress tests, but another issue is the cross app import graph. The cross app import graph looks at whether an app A imports code from app B, and if so, it adds the Cypress tests of both app A and B to the list of tests to run. This is problematic because if the CI build is a single app build for app A, all the tests for app B will fail since we aren't building app B.

The hca app is a perfect example. hca imports an object from the Dashboard app, specifically [DASHBOARD_ALERT_TYPES](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/hca/enrollment-status-helpers.jsx#L7). When running a single app build for hca, we shouldn't need to run tests for the Dashboard app, because no code in the Dashboard app has been modified. But if we were doing a single app build for the Dashboard app, then we would need to run hca tests as well because there's now way of knowing that the code modified in the Dashboard app won't affect the hca import. And this won't work for autonomous deploys.

This touches on the deeper issue of apps importing code from other apps. As long as we have apps importing from other apps, autonomous deploys won't work because one app's deploy might affect another app's functionality.

**Comment by timwright12** [comment] 2021-09-07 18:25
@theodur Do we need to do a dependency map and build apps that are connected to other apps or is this to a manageable level where we can just fix the apps that import from other apps?

**Comment by theodur** [comment] 2021-09-07 20:50
@timwright12 Do you mean do a dependency map and build dependent apps in CI for autonomous deploys? Looking at the latest [cross_app_import_graph.json](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/cross_app_import_graph.json) in `master`, it seems like there are a lot of cross app dependencies. Many of them do seem to deal with static pages, which is a kind of a special situation. The cross app import graph probably isn't 100% accurate since it looks like it's only looping through the `src/applications` directory and considering each sub-directory as an app. Fixing cross app dependencies may not be a quick task, but it's probably something that will be needed to avoid problems with autonomous deploys.

**Comment by timwright12** [comment] 2021-09-07 21:09
We can generally leave static-pages alone since it's a separate app/mess by itself, but let's chat in parking lot about what we need to do to move this one forward.

**Comment by theodur** [comment] 2021-09-07 21:17
Yeah, static-pages cross app dependencies will be different from regular apps. That sounds good to me. I can see two potential paths we can take, by either removing cross app dependencies, or working with the cross app dependencies we have, and trying to do autonomous deploys around that.

**Comment by theodur** [comment] 2021-09-08 15:52
Followup items:
- Determine whether we should remove cross app imports. If so, create a ticket for that.
  - If we take this route, we can use the cross app import graph to help with this. Many of the cross app imports are static-pages and the dashboard app importing from other apps. The dashboard app imports the root URL from other app's manifest files. Those imports may need to stay, but others look like they can be removed.
- Reach out to Testing Tools Team to see if they can update test selection to account for applications in subdirectories

**Comment by theodur** [comment] 2021-10-06 18:24
Closing this, since we confirmed that we can use the `entry` option to select which apps to build.

**Closed by theodur** 2021-10-06 18:24 UTC
Labels: tools-fe
