### ISSUE TITLE
Priority #2: Update program page to support launch of new online 10-10CG form - Review feedback, Implementation

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9376] opened 2020-05-20 19:13 UTC
Based on the content generated as part of 7892:

## Acceptance Criteria
- [x] Mockup of what page will look like when supporting online form shared with caregiver team.
- [x] Feedback from caregiver team addressed.
- [x] Issue created for engineers to update react widget per caregiver team feedback.
- [x] React widget updated.
- [x] Updates to family member benefits page made and published in accordance with mockup shared with caregiver team
- [x] Issue created to change URL for published Drupal page.
- [x] Issue opened for redirect of caregiver program page URL.
- [x] Issue created to add react widget to draft Drupal page.

**Comment by stephorkandatx** [comment] 2020-06-01 17:58
@DanielleThierryUSDSVA have we received feedback or final sign off?

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-01 18:54
Hi @stephorkandatx. Yes. I've been communicating about just 1 piece of feedback on button. Will post final note here this week and get the button updated in the relevant ticket. But in general, we're all good and on track.

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-10 02:25
# Notes for records

### Email sent 5.14.20

Hi all,

Hope the week is going well for everyone!

Following up from our meeting last week, I’m attaching a mockup of the current PCAFC page with updated content to support the online application. I’ve placed a red box around the updated content in the attached pdf.

The content reflects tweaks to work the online application option into the flow of how to apply instructions, consistent with our approach to forms such as this. I would greatly appreciate any feedback on the updated application content by Thursday, 5.21.20.

**To confirm for these updates:**

1. Our goal is to be ready to support the online application by May 29. But the changes will not go live until everything is set on the back end and we get the go-ahead from your team.

2. I’m working with our development team to put an on/off mechanism in place so that this page can easily have the updated “How do I apply for this program?” content and button switched off should the online application need to be taken down.

Should that need arise, the copy in that section will default to the current “How do I apply for this program?” content on the live page at https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/.

**Updated URLs:**

As requested, here are the updated URLs that we’ll have ready for when the online application launches.

- **Main PCAFC page:** va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/
 This new URL reflects the decision we talked about in our meeting to move the PCAFC page out from within the health care section and into to the family member benefits hub, where it will live alongside the new online 10-10CG application. We’ll redirect the current URL (va.gov/health-care/family-caregiver-benefits/comprehensive-assistance ) to this new URL so that users who may go to the current URL will still seamlessly find the page.
- **Online application:** va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/
 This URL will take users directly to the online 10-10CG application.

As always, please feel free to reach out with any questions.
Thank you!
Danielle

Attachement: [PCAFC page with application call to action 5.13.20](https://app.zenhub.com/files/133843125/ebc5b4bc-0b3c-4589-bac8-afa95e88be85/download)

### Email sent 6.2.20 (in response to feedback)

Hi all,

I hope you’re all well. Wanted to check in on this page.

We have the on/off functionality ready to support the online form, but will hold off on implementing on live pages until we get the go ahead from you all, in coordination with our forms team.

Pam, I did want to follow up on 2 things on the edits to the “how to apply” content in support of the online form:

1. In consultation with our design and accessibility experts, I’ve confirmed that we should keep the button length to <35 characters so that the button isn’t overly long (especially important for mobile devices). So we can’t include the full program title in the button itself.

 Our accessibility expert recommends “Apply for caregiver assistance” for the button text for the greatest cognitive clarity for all users, and especially those using a screen reader.
 
And then we can do 2 things to make sure both sighted readers and those using a screen reader have the full context:

1) I’ve added the full program name into the descriptive copy above the button (see screenshot below).

 2) We’ll add code to the button that will read the full program name for the button for screen readers.
 
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/041db240-e320-4d42-8433-3f9a43119733) 

- There was a note re: the “Am I eligible…?” line, so I just wanted to confirm that that content hasn’t changed from what’s on the live site https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/. The only content that we’ll be changing is the “How to apply…” section.

As always, feel free to reach out with questions.
Take care,
Danielle






https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10000

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-11 02:11
Hi @RLHecht. I've updated the Family Member Benefits hub page to match the attached mockup. Citrix is down at the moment, so I can't grab preview link, but it's this page: /family-member-benefits/.

Could you please review and publish? If you have any questions, please let me know. Thank you!

[family member benefits page updates](https://app.zenhub.com/files/133843125/b1fce65a-a6ac-44a8-86d9-87c207a07f03/download)

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-11 02:17
@stephorkandatx A question for you when you have a moment. 

We need to change the url for **The Program of Comprehensive Assistance for Family Caregivers**

from:
/health-care/family-caregiver-benefits/comprehensive-assistance/

to:
/family-member-benefits/comprehensive-assistance-for-family-caregivers/

Randi and I can make the change in Drupal. But we'll also need to implement a redirect. Do you think this is something Nick or Kelson can fit into this week? If yes, I can create the issue now and coordinate between us. But wanted to check first since I know they're poised to be potentially super busy.

cc: @mnorthuis for IA awareness

**Comment by RLHecht** [comment] 2020-06-11 13:21
@DanielleThierryUSDSVA All your changes look ok on the hub page. Published page! FYSA @stephorkandatx

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-11 13:47
Woo-hoo! Thank you so much, @RLHecht.

**Comment by mnorthuis** [comment] 2020-06-11 20:43
@stephorkandatx @DanielleThierryUSDSVA  Please use the redirect template for the redirect :-)

**Comment by stephorkandatx** [comment] 2020-06-16 14:46
@mnorthuis and @DanielleThierryUSDSVA redirect ticket is now at #10277. It will be an item to cover in our sprint planning tomorrow. Mikki, are there additional pieces of information needed for the request ticket?

**Comment by DanielleThierryUSDSVA** [comment] 2020-06-16 16:26
@stephorkandatx @RLHecht Per our conversation, I've created the 2 new issues needed to finish this work and labeled them for next sprint. Closing this issue now. Thanks!

**Closed** 2020-06-16 16:26 UTC
Labels: content, vsa-public-websites
