### ISSUE TITLE
[Design] Direct deposit for edu: Add pngs or jpegs of design files to Github

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#22664] opened 2021-04-05 20:47 UTC
## Background

So we can easily link to/share the information, especially in a case where we lose access to old prototypes, we need the PNGs or JPEGs of the direct deposit for edu screens uploaded to GitHub.

## Tasks

- [ ] Upload direct deposit for edu screens [to this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/images).

## Accepted Criteria
- [ ] Images uploaded to folder mentioned above

**Comment by jason-gcio** [comment] 2021-04-16 18:08
Dupe of #22665

**Closed by jason-gcio** 2021-04-16 18:08 UTC
Labels: design, direct deposit, documentation, vsa-authenticated-exp, vsa-ebenefits
