### ISSUE TITLE
Staging:  User Able to Navigate through VAOS even though timed out

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#39682] opened 2022-04-06 17:54 UTC
Discussed on the 4/6 scrum.

I haven't really had to the time to triage this and pin down exactly when/why this happens.   Nevertheless Brad Gross asked that I log an issue.

If I am in the VAOS application in certain places and I time out, meaning I get diverted to another task after I have started doing something in VAOS, when I come back to the VAOS I can continue making selections and then when I hit something after doing a couple things, I get a "you have been logged out of the VAOS message".  

Again, I haven't had the time to nail down exactly when/why this occurs. I know it is because I stopped doing what I was doing in VAOS and came back to the app at least some significant time later.  

User impact:  User able to navigate through VAOS and take some actions only then at some point getting a logged out message displaying.  Need to inform user earlier in the process that they have been logged out.

**Comment by aagosto90** [comment] 2022-04-06 17:59
@marcynadeau Was this intentionally assigned to me?

**Comment by ldelacosta** [comment] 2022-06-07 23:14
@simiadebowale - Per our discussion during our meeting, can you check if this is a standard time out behavior for all applications or this is an issue that we need to address in VAOS. Please let us know your findings.

**Comment by ldelacosta** [comment] 2022-07-18 16:16
Validated in staging. After 30 minutes of inactivity, the application signs the user out of the application. 

![Screen Shot 2022-07-18 at 12.13.49 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/4fb9a300-928a-476c-b59e-8f9d4beed171)

@marcynadeau - If you can double check when you have a chance to confirm.

**Comment by aarathi-poldass** [comment] 2022-07-21 20:44
Reviewed on 7.21.22 with PM and project leads and this issue was given a **Low** priority

**Comment by aarathi-poldass** [comment] 2022-07-28 13:07
@ldelacosta I can give this a try and come up with steps to reproduce. I'll let you know once I have that figured out.

**Comment by aarathi-poldass** [comment] 2022-07-28 17:55
@ldelacosta I tried multiple scenarios and not able to replicate the issue in staging.

**Comment by marcynadeau** [comment] 2022-07-29 23:23
I saw this again last Sunday when I was catching up on other work. It is like I am in the middle of direct scheduling or request and then I got sidetracked and came back to the app and was able to navigate backwards but then when I took an action that would call the backend I would find that I had been timed out. If you could leave open until I get back, I'll work on this defect and will either close or add detailed steps to recreate. It will always be low priority because it's not like veterans would be doing the same thing I do. I just got stuck looking into SM or VATS or Vista or CDW to figure out why I couldn't direct schedule or request. Veterans would probably be singularly focused in the app unlike me.

**Comment by marcynadeau** [comment] 2022-09-22 12:37
@ldelacosta You can close this defect as invalid/unable to reproduce.  I am not able to reproduce this sporadic issue and Aarathi and Beth report that they not seeing the issue.

**Comment by ldelacosta** [comment] 2022-09-22 12:53
Cannot reproduce this issue in staging. Closing out the ticket.

**Closed by ldelacosta** 2022-09-22 12:53 UTC
Labels: frontend, vaos
