### ISSUE TITLE
Investigate instances of applications importing code from other applications

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18323] opened 2021-01-08 23:07 UTC
Audit our usage of `~/applications` and `applications/` Babel aliases to determine if we have any applications that are importing code from _other_ applications. This is a bad practice. Any shared code should live in `platform`.

In particular we should look for:
- instances where our code is importing other application's code and make tickets to fix those instances
- instances where other apps are importing _our_ code and make tickets to fix those instances

 Additional tickets can be created based on this spike.

**Comment by ajakabcin** [comment] 2022-12-14 19:13
Closing - duplicate of #46649

**Closed by ajakabcin** 2022-12-14 19:13 UTC
Labels: frontend, authenticated-experience, tech-debt
