### ISSUE TITLE
Filter Logs before going into Datadog

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47100] opened 2022-09-15 13:13 UTC
- Document all sources (index's)
- Document types of logs going into each index
- Document required logs from a compliance perspective
- Document required logs from an app perspective
- Document how long each type of log is required to be live, archived, deleted
- Create a write-up in github which documents all of these details (not just inside this ticket/epic)

### current log sizing
- how many logs per day, week, month; per source
- what is size in S3 of the logs, per day, week, month

### Index List Notes
Note: We are only going to analyze log sources which generate more than 500 logs per 5 minutes.
- main is the only index
- what is the gate at which we exclude log for pricing? Is at the agent level or index level
- does it make sense to break these into different indexes

#### Approach
- Document queries for each log source and environment
- we dont care about logs staging and below, if teams want to fix them thats on them
- Look at each service in DD.
  - Document the things that generate the most logs in each source
  - Find out if we can reduce these in some way
  - Determine retention period for each service/source

#### Things we exclude already in DD
- external-secrets (all)
- sentry (everything except utility)
- observability (all)
- cluster-autoscaler.* (all)

#### Current Retention
- in datadog we archive logs at 30 days to S3
- all s3 logs are kept for 24 months
- after 24 months logs go into glacier and stay for a total 6 years (2 years in s3, 4 in glacier)
- after logs are are 6 years old, they are deleted

#### Services

- Vets-Api
   - can we set the following to debug only (enable debug in logs to see them, otherwise they arent written to datadog)
      - feature toggles
      - active model (some loader for feature toggles)..need example
- CMS
- ELB
- traefik
  - Loki generates lots of logs here, can we reduce these in some way? Ask Infra
- sentry
- goldilocks (CMS)
- argo
- datadog-k8s-agent
- keycloak
- platform-console
- apache
- vsp-test-user-dashboard
- datadog-private-location
- platform-console-ui
- calico
- network-status-exporter
- node-8
- tel2
- gibct-data-service

### Documentation on filtering / processing logs before hitting Datadog
- coarse filtering
  - https://docs.datadoghq.com/agent/guide/autodiscovery-management
- granular
  - https://docs.datadoghq.com/agent/logs/advanced_log_collection

**Comment by joeniquette** [comment] 2022-09-16 17:13
met with the DD folks (Sarah and April) to discuss the current state of our instance. 

- logs and logging in DD are free
- if logs are kept in DD after 30 days we accrue a charge
- best practice is to archive logs at 30 days to S3
- if you archive 100% of logs, there is no cost
- we are charge per rehydration of logs per GB
- the DD team will discuss our use cases with their team to determine what we can do regarding opening this window of keeping live logs to 90 days
  - **Use case 1:** need logs that go back 30, 60, 90 days to troubleshoot outages or for development purposes (outages are rare but the development requirement is daily)
  - **Use case 2:** need logs when asked to help the contact center with a Veteran reported issue (2-3 times per week, data can go back as far as 90 days)
  - **Use case 3:** need logs for the FWA team to investigate all user activity for specific users. These can sometimes need to go back 12-18 months. Because of this it may be more appropriate to better set expectations around how often a rehydration may be required, how much data, any restrictions or guidance on how best to do this. We may ultimately decide we need a different logging solution for this?
  - Sarah stated we should expect to hear back from them next week
- We (platform team) mentioned that we currently generate roughly 165M logs per day and still had work to do to reduce those, we will be able to cut back roughly 10% of these logs if not more

**Comment by ianhundere** [comment] 2022-09-22 14:00
just a heads up that `sentry` logs are back in the mix. i think it's worth considering to remove it, or at least only allow error logs from sentry.

**Comment by joeniquette** [comment] 2022-10-10 21:43
Met with Kyle and Eric on Friday, obtained some information from them about what we want to attempt. Ian is going to make some PRs to make the suggested changes for filtering logs.

Eric also already made a change which removes the rack-support logs, which reduces the logs by 38% overall (404k total over 5 minutes, with rack support coming in at 156k over 5 minutes)

Meeting with lighthouse attempting to be setup for the 13th

**Comment by ianhundere** [comment] 2022-10-14 17:40
prs are up:
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/933
- https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/145

will start with dev/utility for `vsp-infra-application-manifests`

**Comment by ianhundere** [comment] 2022-10-17 15:10
the first PR is working as intended, will keep playing with argo to get that to work as well.

**Comment by ianhundere** [comment] 2022-10-17 15:24
so for whatever reason, the `log_processing_rules` are not working as intended though the env vars for excluding logs are (e.g. `DD_CONTAINER_EXCLUDE_LOGS` and `DD_CONTAINER_EXCLUDE`). 

reaching out to datadog to see if there's anything special we need to do in order to get `log_processing_rules` working in our dd govcloud instance.

**Comment by ianhundere** [comment] 2022-10-17 16:11
traefik has been substantially reduced:![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/c051ea21-212e-4a73-a17f-cc5c6a6937c1)

**Comment by ianhundere** [comment] 2022-10-17 17:07
i'm gonna change the `logLevel` for argo until i hear back from datadog.

**Comment by ianhundere** [comment] 2022-10-18 15:56
i tried disabling info logs at the application layer (via `values.yaml`; `extraArgs` / `logLevel`), but still wasn't able to remove them. i'm going to wait to hear back from dd in regards to `log_processing_rules` via pod annotations.

**Comment by ianhundere** [comment] 2022-10-19 15:57
found a solution for the annotations, wasn't using the correct container name. i'll have PRs out for goldilocks and argo shortly.

**Comment by ianhundere** [comment] 2022-10-19 17:39
argo + goldilocks in dev are done. will do the rest of envs for goldilocks.

**Comment by ianhundere** [comment] 2022-10-19 23:14
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/5874fb0a-01c0-4cdd-9892-10b218c13810)
so it should be pretty straightforward to do this in the future if there are any other noisy logs and/or logs we want to mask etc. as per:
https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes

**Comment by alyssagallion** [comment] 2022-10-20 17:52
Demoing as a win, ticket here: https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/48543

Closing!

**Closed by alyssagallion** 2022-10-20 17:52 UTC
Labels: Identity, eks-move
