### ISSUE TITLE
[Components and pattern standards] Design component or pattern is not functioning or working as expected. (04.12.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29376] opened 2021-08-26 15:15 UTC
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Ryan Thurlwell (OCTO Design Lead)

---

### Platform Issue
Design component or pattern is not functioning or working as expected.

### Issue Details
On the compare page, the table seems to jump 2 rows when scrolling down

### Link, screenshot or steps to recreate
https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities=14952435%2C10040835%2C21853035

### VA.gov Experience Standard
[Category Number 04, Issue Number 12](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
This should be a smooth scroll

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by dneel-bah** [comment] 2021-09-08 16:26
This is a duplicate of the QA launch blocking issue that was resolved with #29431.  Closing this issue as completed.

**Closed by dneel-bah** 2021-09-08 16:26 UTC
Labels: design, bah-edu, collab-cycle-feedback, Staging, CCIssue04.12
