### ISSUE TITLE
SPIKE | 686 | Missing Veteran Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70132] opened 2023-11-16 18:44 UTC
## Issue Description
_Some 686/674 claims are failing the primary and backup submission pathways because they are missing veteran_information. (See examples in #67710 )._

Claim IDs that were previously remediated:
- 2023-10-14T23:11:09.082296Z - 7889911 - Missing veteran-information
- 2023-10-25T05:59:56.872673Z - 7941666 - Missing veteran-information
- 2023-10-25T09:02:59.966758Z - 7941801 - Missing veteran-information

---
## Tasks
- [ ] Determine why claims were missing veteran_information
- [ ] Remediate

## Acceptance Criteria
- [ ] Claims no longer fail for this reason
---

**Comment by steele-lm** [comment] 2024-10-03 19:41
@evansmith Do you recall if this issue was fixed?

**Comment by evansmith** [comment] 2024-10-03 19:47
@steele-lm missing Veteran Info happens a lot less than it used to but we occasionally do see one pop up. This will trigger a failed backup submission like last weeks.

**Comment by sanjabaj2** [comment] 2024-10-16 23:42
@steele-lm This seems to be remediation ticket. Is the milestone correct?

**Comment by steele-lm** [comment] 2024-10-17 15:47
@sanjabaj2 The claims involved have been remediated, so this ticket is to find the root cause of the missing info and fix if (if possible). I had been thinking of this as code reliability (stage 2). Should I reclassify it as remediation?

**Comment by sanjabaj2** [comment] 2024-10-17 15:54
CodeReliability is good label. Just update description to be clear that we are talking about code fix and the individual incidents are already remediated.

**Comment by va-albers** [comment] 2024-11-29 19:39
Watch Officer noted a significantly increased error rate for this occurring recently.  Conversation thread is posted [here](https://dsva.slack.com/archives/C063YELFVLM/p1732867069969359).

**Comment by evansmith** [comment] 2024-12-04 15:44
Update:

I believe I have found the cause of this issue. In most instances a 'veteran_information' hash is inside of dependents_application because of data entered on the form. In rare instances it appears not to be, most likely due to prefilled data from the profile. This is not an issue in the PDF job or the sidekiq 686c/674 jobs because before processing we create another 'veteran_information' hash on the outermost layer of the payload and only reference that. However, on the backup job, we are attempting to reference the 'veteran_information' hash that is inside of dependents_application, which might not always be present. This should be an easy fix and I'll have a PR ready for review today.

**Comment by evansmith** [comment] 2024-12-06 15:13
This has been deployed to production. @steele-lm I think we can close this issue and just keep an eye out for any monitoring issues.

**Closed** 2024-12-06 16:01 UTC
Labels: backend, monitoring, 686, alerting, engineering, code-yellow, dependents-benefits, zero-silent-failures, ZSF:CodeReliability
