### ISSUE TITLE
[Design] Determine design applications for non disability claim types, STEM, and decision review cards

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#62217] opened 2023-07-18 19:49 UTC
## Acceptance Criteria

- [ ] Mock designs for the key non-disability claim types, STEM, and decision review cards
- [ ] Design aesthetic matches approach to disability card redesign.

**Comment by skylerschain** [comment] 2023-08-01 17:11
This is a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/62179.

**Closed by skylerschain** 2023-08-01 17:11 UTC
Labels: design, benefits-team-1, squad-1
