### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Account Sign-up - Learn-more link broken

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#50578] opened 2022-12-09 18:27 UTC
## What happened?
In Staging Redesigned Homepage, Account-Signup section, **Learn how an account can help you** link is broken.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/

In **hero section** > **account-signup**, click **Learn how an account can help you** link.  Observe that it does not navigate to **Resources and support** page.

## Desired behavior
- [ ] Link should navigate to **Resources and support" page [/`resources/`].

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jilladams** [comment] 2022-12-21 22:27
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11771

**Closed by jilladams** 2022-12-21 22:27 UTC
Labels: bug, frontend, Shared Support Team, VA.gov homepage
