### ISSUE TITLE
[Combined Debt Portal] 'Your VA debt and bills' overview page - base state

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#39001] opened 2022-03-23 17:49 UTC
## Issue Description
As part of the Combined VA Debt Portal, we need to create a new page that shows an overview of the VBA debts and VHA copay bills on a Veteran's record. 

**Use case:** 
This ticket captures the design for if the Veteran has both debts and bills available. [Please refer to this UXPin prototype ](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148519709/simulate/no-panels?mode=i)

---
## Tasks
- [ ] Build the 'Your VA debt and bills' overview page according to the provided UXPin 

**Note:** There may be comments on the prototype. Please reach out to Riley with any additional questions! 

## Acceptance Criteria
- [ ] The page has been developed and matches the provided UXPin

**Comment by denisecoveyduc** [comment] 2022-04-06 18:08
This is a duplicate of #39366

**Closed by denisecoveyduc** 2022-04-06 18:08 UTC
Labels: frontend, vsa, vsa-debt, CombinedVADebt
