### ISSUE TITLE
[PM] DD4edu Oversee analytics implementation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19128] opened 2021-01-27 14:57 UTC
## Background
As part of setting up analytics for DD4edu, we need to make sure to answer any questions, get FE tickets created, and make sure everything is setup correctly.

## Tasks
- [ ] Set up FE+analytics team sync to discuss implementation/answer any questions
- [ ] Create FE analytics implementation tickets
- [ ] Analytics have been implemented

**Comment by Samara-Strauss** [comment] 2021-02-05 20:46
We should move this out of this sprint, since the actual analytics implementation isn't happening until next sprint at the earliest.

**Comment by mshea0606** [comment] 2021-02-05 21:02
@Samara-Strauss agreed, I was thinking the same thing. I'll go ahead and remove it from the S40 epic.

**Comment by Samara-Strauss** [comment] 2021-03-18 14:34
This is a duplicate of #20652. Closing.

**Closed by Samara-Strauss** 2021-03-18 14:34 UTC
Labels: direct deposit, vsa-authenticated-exp
