### ISSUE TITLE
Add Flipper features for soft rollout (BE/FE)

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35622] opened 2022-01-20 05:20 UTC
## Issue Description
Create a Flipper for the Banner (MHV Inherited Proofing) work

---
## Tasks
- [ ] Adds feature flag in vets-api for the banner
- [ ] Adds feature flag in vets-website for the banner

## Acceptance Criteria
- [ ] A feature flag for the MHV Inherited Proofing is created

**Comment by AGarcia-Clarity** [comment] 2022-04-13 14:10
@nsoutouras this can be closed. Duplicate of https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/39128

**Closed** 2022-04-14 15:47 UTC
Labels: Identity, Identity-Frontend, Identity-Backend
