### ISSUE TITLE
10-7959f-2 Review page: Microsoft Edge issues

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95231] opened 2024-10-17 19:00 UTC
Submit button not showing in Microsoft Edge when Error appears. 

In Microsoft Edge "I live on a U.S. military base outside of the United States." appears on the accordion enver though it was not checked "yes" in the form

### Timebox
Limit this to a day of investigation at most if we're unable to reproduce the issues in edge.

**Comment by jamiefiore** [comment] 2024-10-23 17:26
@baltes the submit button disappears during the error state

**Comment by michaelclement** [comment] 2024-10-25 16:43
The Military checkbox issue affected Chrome as well. I've added a fix in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32724).

As far as the second issue goes, we have seen that error (disappearing resubmit button) intermittently in Chrome before as well. It's been notoriously difficult to reproduce, and as far as I know we haven't seen it while developing locally. I'll keep poking around.

**Comment by michaelclement** [comment] 2024-10-25 18:50
Following up about the disappearing resubmit button - turns out it's explicitly disabled in production at a Form Library level:
<img width="587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWwyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2d8727b1cdb97d37c7d5ed2ba0d4f613dffee44/btn.png" alt="btn.png" />

**Comment by michaelclement** [comment] 2024-10-25 18:52
Based on these findings/the fix for the military checkbox, I think this ticket is all finished (just have to get the checkbox fix merged in - waiting until Monday for that since it will impact production and needs a review).

@baltes If you'd like to check out the checkbox fix in a review instance, the GitHub branch to [linked here](https://github.com/department-of-veterans-affairs/vets-website/tree/95231-fix-bug-military-base-checkbox). Alternatively, I can walk you through it in a call whenever you'd like.

**Closed** 2024-10-29 15:04 UTC
Labels: frontend, ivc-forms, 10-7959f-2
