### ISSUE TITLE
Back to top component is not displayed in IE-11

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25103] opened 2021-05-21 22:20 UTC
## Issue Description
"Back to top component is not visible when viewed with IE-11. This is a known component defect

## Steps to reproduce
Visit Escanaba Vet Center Main page using (preview-prod.vfs.va.gov/preview?nodeID=3756 using IE-11, PIV or SOCKs
Scroll down to the bottom of the page 

## Expected behavior 
Back to top component can be used to navigate back to the top of the page. 

## Actual behavior
Back to the top component is not present

**Comment by mmiddaugh** [comment] 2021-05-24 20:48
Documented in #24309

**Comment by Rleahy22** [comment] 2021-07-29 13:16
For validation: Many pages have the back to top button, but https://www.va.gov/escanaba-vet-center/ was the one I was looking at.

**Comment by mmiddaugh** [comment] 2021-07-30 22:33
I just viewed the Escanaba Vet center in prod. The Back to top component does not seem to be present, @Rleahy22

**Comment by Rleahy22** [comment] 2021-08-02 13:58
It appears that we have syntax errors in IE11 that stop JavaScript rom running due to trailing commas in function parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#browser_compatibility
<img width="223" alt="Screen Shot 2021-08-02 at 9 57 16 AM" src="https://user-images.githubusercontent.com/3144003/127873327-5ad632b3-784e-41fc-b401-ac04c9c24421.png">
<img width="217" alt="Screen Shot 2021-08-02 at 9 57 05 AM" src="https://user-images.githubusercontent.com/3144003/127873328-e5808845-77f8-48be-8758-e35156940310.png">
I'll have to either modify the build to strip these out or remove them manually. This could be a lot of work

**Comment by Rleahy22** [comment] 2021-08-02 20:00
@mmiddaugh I removed any instances of what was causing the earlier issue, but I cannot tell if what I am seeing now is a result of browserstack issues or va.gov. Are you able to see the Back to top button in IE11 now?

**Comment by mmiddaugh** [comment] 2021-08-02 22:27
Hi @Rleahy22 - I just looked at Escanaba as well as Colorado Springs and Cincinnati (hoping to avoid any weird caching situations). I viewed both the main and location pages. The Back to top button is not visible on either page for any of the locations.

**Comment by Rleahy22** [comment] 2021-08-03 13:44
Thanks for looking into this @mmiddaugh. I'm having a very hard time tracking down the root cause. Would you mind checking to see if you have any errors on those pages in IE11? I see this error when using a virtual machine, and I'm not sure if regular IE11 users see the same thing,
<img width="1041" alt="Screen Shot 2021-08-03 at 9 43 13 AM" src="https://user-images.githubusercontent.com/3144003/128026077-a4e0b417-8444-4ed4-8925-b773218c5f97.png">

**Comment by mmiddaugh** [comment] 2021-08-18 12:09
apologies @Rleahy22 I didn't see your comment until now! I just looked in IE11 and do not see any errors similar to those in your comment above. 

Feel free to message me in #facilities or direct DM if you'd like my eyes on anything. I don't want to be a blocker for you!

**Comment by Rleahy22** [comment] 2021-09-01 19:49
@mmiddaugh are you still not seeing the back to top button in IE11? I checked in browserstack and I see it, but I realize that may not be a perfect test.

<img width="1786" alt="Screen Shot 2021-09-01 at 3 48 23 PM" src="https://user-images.githubusercontent.com/3144003/131734715-a3bb2978-ca34-4991-95e8-b5823b468c09.png">

**Comment by Rleahy22** [comment] 2021-09-10 15:19
Is this still an issue? From what I can tell it is fixed.

**Comment by brianalloyd** [comment] 2021-09-22 18:01
Completed and closing.

**Closed by brianalloyd** 2021-09-22 18:01 UTC
Labels: bug, vsa-public-websites, frontend, vsa, vsa-facilities, vet-center
