### ISSUE TITLE
Analytics New KPI dashboard request & KPI dashboard update request for [Benefits Non-Disability | Burial 530EZ Form]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#90434] opened 2024-08-09 21:03 UTC
# Request a New Standardized KPI Dashboard or an Update to an Existing Dashboard
## What this form is for

Use this ticket template to request a new standardized KPI dashboard or an update to an existing KPI dashboard on Domo for your product. 

**Tell us what you need done:**
- [ ] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
- [x] [Updates to Existing Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-updates-to-existing-dashboards)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [x] Change basic product info
- [x] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other
   - If possible, change any metric that involves "form start" to capture clicks of the form's start button/link and not visits to the form's intro page.
   - Remove duplicate "21-530EZ" dashboard
   - Update name of dashboard to "21**P**-530EZ - Burial Allowance)
   - Add 530EZ dashboard to VA.gov KPI Dashboard Eligibility Board
  
Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

**If you cannot locate your original worksheet you can create a new one:**
- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: [Burial 21P-530EZ KPI Dashboard Product Details](https://docs.google.com/spreadsheets/d/1ptfQI71LP85un1kXfrwOwzwbl9VYKrjBVHxLCBlyAgQ/edit?usp=sharing)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] **Add your team label to follow progress**

**Additional Info For Both Options**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by johnny-jesensky-adhoc** [comment] 2024-08-14 13:09
Hi @steele-lm, thanks for submitting this, confirming we have it in our backlog. We'll plan to review in an upcoming refinement meeting.

FYI @Blivaditis, @ChristineYoungZA

**Comment by Blivaditis** [comment] 2024-08-19 17:46
Hi @steele-lm what is your forms landing page?

**Comment by steele-lm** [comment] 2024-08-19 17:53
@Blivaditis The [intro page](https://www.va.gov/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez/introduction) would be considered the landing page.

**Comment by Blivaditis** [comment] 2024-08-19 18:02
@steele-lm perfect, thank you I wanted to confirm.

**Comment by Blivaditis** [comment] 2024-08-26 20:02
The new funnel has been loaded in BQ and is visible in the Domo Dashboard under 21P-530EZ - Burial Allowance. [Uploading... Screenshot 2024-08-26 at 12.59.03 PM.png]

**Comment by Blivaditis** [comment] 2024-08-26 20:03
We are still working on the name update.   FYI @ChristineYoungZA

**Comment by Blivaditis** [comment] 2024-08-27 20:06
Closing the ticket out as the majority it is completed, we will continue to work on fixing the form names.

**Closed** 2024-08-27 20:06 UTC
Labels: analytics-insights, analytics-request, kpi-dashboard, Burial, non-disability-benefits

**Comment by steele-lm** [comment] 2024-08-29 19:10
@Blivaditis When I look at the updated 530EZ dashboard, I'm seeing a few elements that don't seem to be populating (successful submissions and completion rate by step). Are those still being worked on?

**Comment by Blivaditis** [comment] 2024-08-29 19:47
Hi @steele-lm, yes sorry about that, I noticed an issue with the links and we updated the funnel load, it should be picked up in the updates on Monday. I will check the dashboard Monday and update you with confirmation. The removal of the old form names/funnels was successful, we can add them back in if they are ever needed again.

**Comment by steele-lm** [comment] 2024-09-05 15:13
@Blivaditis It looks like the Burial form Domo dashboard is still not functioning quite right. The forms by status still appears to be counting visits to the intro page as starting the form (vs clicking the start button), and the completion rate by step is missing most of the form steps. Can you look into it?

**Comment by Blivaditis** [comment] 2024-09-06 14:53
Hi @steele-lm the update for the funnel worked in one dataset but not another hence why the funnel chart is looking off. Our BQ expert is back today so I will inform him of the issue. As far as form status goes, we will look into the issue and determine how to go about updating it.

**Comment by Blivaditis** [comment] 2024-09-06 14:54
Will update when the issue is resolved.

**Comment by Blivaditis** [comment] 2024-09-09 14:14
Hi @steele-lm, The 530 funnel update was successful this time around. There are two versions of the form so when you filter make sure to filter by version as well. 
<img width="1310" alt="Screenshot 2024-09-09 at 9 12 52 AM" src="https://github.com/user-attachments/assets/4c287103-3942-4c82-ae91-b8233f64de32">

**Comment by steele-lm** [comment] 2024-09-09 15:50
@Blivaditis Great! Can you also take a look at the "forms by status" (not submitted) and "total form starts" sections? These numbers seem artificially high. I'd like to make sure they are capturing the number of times a user clicks the start button of the form rather than viewing the intro page.

**Comment by Blivaditis** [comment] 2024-09-09 16:39
@steele-lm I will take a look, depending on what I find, updates to the dash may need further discussion before being implemented since this is a Standard KPI Dashboard. I will update you when I have some more information!

**Comment by steele-lm** [comment] 2024-09-23 19:36
@Blivaditis Checking in to see if our dashboard can be updated to reflect forms starts as start button clicks vs page views.

**Comment by Blivaditis** [comment] 2024-09-23 19:52
Hi @steele-lm we are in the process of updating the dashboard, we are finalizing the discovery portion and the implementation will take place in a future sprint. Thank you for your patience.
