### ISSUE TITLE
PCPG |  Document Failure points

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#90180] opened 2024-08-07 17:26 UTC
Please document the various Failure scenarios that can occur in Career Counseling submissions, and what we do in each scenario
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?wid=0-1721321111054&sender=u0e23f90bc2aa6d1f44e99992

What happens when:
- vets-api is down
- vets-api controller unreachable
- SavedClaim cant be saved
- Benefits API fails
- Benefits API succeeds, but polling job shows failure
- anything else I missed

Acceptance Criteria:

- [ ]  update mural board to reflect failure locations and current monitoring. Include link to actual monitor for each log/statsd being recorded. 
- [ ]  Create tickets as needed (Identify proper statsd metric vs. logs)
- [ ]  Schedule meeting to review findings with team lead and VA eng lead

**Comment by sanjabaj2** [comment] 2024-08-26 19:47
Consider [this requirement ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89252)as well.

**Comment by steele-lm** [comment] 2024-09-30 18:06
Closing this ticket as a duplicate of #93323

**Closed** 2024-09-30 18:07 UTC
Labels: backend, monitoring, PCPG-CH36, non-disability-benefits, career-counseling, ENG:Excellence, zero-silent-failures, ZSF:Monitoring
