### ISSUE TITLE
Update Documentation on Radio Buttons, Checkbox, and Checkbox Groups

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#33179] opened 2021-11-23 01:32 UTC
Linked Tickets:
* https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33177
* https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33114

Task: 
* Documentation on https://design.va.gov/ will need to be updated to reflect the changes made in the linked tickets

Goal:
Provide a straight forward guideline of:
* Why we are moving to web components from react components
* How to use the web component instead of the react component
* The issues that are being solved now by the web component

**Comment by k80bowman** [comment] 2021-11-29 20:10
Closing, duplicate of #33178

**Closed by k80bowman** 2021-11-29 20:10 UTC
Labels: vsp-design-system-team
