### ISSUE TITLE
[Infrastructure Request] DataDog: Setup Puma integration for Console Services team

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#41703] opened 2022-05-20 15:42 UTC
### Team name

Console Services 

### Application name

Datadog

### Product owner

Thomas D

### Product manager

Nathan Peterson

### DevOps resource

none

### Related issue

https://github.com/department-of-veterans-affairs/va.gov-team/issues/39887

### Infrastructure needed

@jhouse-solvd We need to get Puma integrated with Datadog and need some help from the Infrastructure team.  

The vets-api puma control app endpoint was enabled in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/9565/files#diff-24409379bdb75ad446bb4e2c18fd4cced1a263b99a3ff96fc3777d8fd8faeab9R10). The ansible code to define the [control app config](https://github.com/department-of-veterans-affairs/devops/compare/eb-puma-int-dd) was applied, but no puma stats were being reported. John or Matt may be able to do a deeper dive. John suggested that we may have to use a custom image (according to https://github.com/department-of-veterans-affairs/va.gov-team/issues/39887#issuecomment-1112361564) to enable the correct config needed to utilize the puma control app endpoint. Could we utilize a [unix socket](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=host) somehow as we have for APM?

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/39887 and comments for further detail

### Acceptance Criteria

- [ ]  Stats are populated through Datadog's puma plugin

**Comment by jbritt1** [comment] 2022-06-22 15:24
Awaiting feedback on if this is a duplicate of #39887 or vice versa: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39887#issuecomment-1163255281

**Comment by mleclerc00** [comment] 2022-06-30 18:08
This is now working in eks dev cluster 
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/76792875/176745294-1d5990a5-f854-47af-b364-7c829a6be08a.png">
![image](https://user-images.githubusercontent.com/76792875/176747557-0ed604b0-ef54-4e2e-a12b-08987e8ad511.png)

**Closed** 2022-07-21 15:54 UTC
Labels: operations, devops, monitoring, Awaiting Feedback, infrastructure-request
