### ISSUE TITLE
10-10d: Update flow for signer email 

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96561] opened 2024-11-06 16:01 UTC
As a user signing and submitting a CHAMPVA application, I need to provide my email address to the VA so they have the ability to contact me in the event of a silent failure.

### Acceptance criteria
This story will update the flow of the form to match Figma mocks.

**Comment by michaelclement** [comment] 2024-11-13 21:56
@rspope @jamiefiore - with respect to the error states, as far as I'm aware we can't selectively hide fields on the review section. I'll do a little more digging and let you know if that's not the case, but this may not be implementable as designed (since we have to use the standard review page component)

**Comment by baltes** [comment] 2024-11-13 22:11
@michaelclement @rspope @jamiefiore    We need to keep the changes to the review section as simple as possible--this isn't the time for functional changes. We can look at it again after go live.

**Comment by rspope** [comment] 2024-11-14 14:10
@michaelclement It's fine to use the standard component if what I suggested is not possible. Sorry for not making that clear.

**Comment by michaelclement** [comment] 2024-11-14 14:29
Got it, thanks for clarifying! Everything else should be good. I'm working on the changes now.

**Comment by michaelclement** [comment] 2024-11-14 21:44
I've got most of this done, but I'm running into a weird issue with the Cypress tests that doesn't seem directly related to my changes. Looking into it, but just wanted to raise that this is delaying me from getting this wrapped up and over to the other engineers to review today. @baltes

**Comment by michaelclement** [comment] 2024-11-15 19:32
[Platform ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1731698524902089) to track the Cypress testing issue I'm seeing. Looks like something is wrong with the Axe functionality (totally unrelated to our apps), and it is impacting other teams at this point. I'll update here when I know more.

**Comment by michaelclement** [comment] 2024-11-15 20:15
@baltes The work is completed in [this branch](https://github.com/department-of-veterans-affairs/vets-website/pull/33032). I can't merge to staging yet, so please let me know if you'd like to have a call to walk through the additions (@jamiefiore @rspope too!)

**Comment by michaelclement** [comment] 2024-11-19 14:00
Merged to staging, visible there. Thanks!

**Closed** 2024-11-25 16:43 UTC
Labels: frontend, needs-refinement, 10-10d, ivc-forms
