### ISSUE TITLE
[Bug] Facility Locator - IE11 - Page content not loading

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17305] opened 2020-12-10 19:18 UTC
## What happened?
On both Live & Staging **Find VA Locations** page, in IE11, page-content didn't load.

NOTE: Strange thing is, this happened on my Windows 10 PC and via BrowserStack, BUT not via SauceLabs.

## Specs:
- Device: Windows 10 PC
- Browser: IE11

## Steps to Reproduce
1. In **IE11**, go to **https://staging.va.gov/find-locations/** or **https://va.gov/find-locations/** -- if prompted for geolocation permissions, click **Allow once**.
1. Observe that loader GIF remains spinning indefinitely -- page main-content doesn't load.

**Screenshot**
![fl-me-bug-ie11-page-content-2](https://user-images.githubusercontent.com/587583/101823549-2dca7a00-3ae8-11eb-8d01-e96e84f7c899.png)

## Desired behavior
Page main-content should load.

## Acceptance Criteria
- [ ] [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brangi** [comment] 2020-12-11 15:32
@tlei123, this issue seems to be related to the flipper client and this code is not owned by the facility locator but the platform team.


<img width="985" alt="Screen Shot 2020-12-11 at 9 28 18 AM" src="https://user-images.githubusercontent.com/100468/101922497-c538d700-3b93-11eb-8feb-d25b54073fae.png">


<img width="1097" alt="Screen Shot 2020-12-11 at 9 28 37 AM" src="https://user-images.githubusercontent.com/100468/101922508-c8cc5e00-3b93-11eb-8865-258d8b92099a.png">

**Comment by tlei123** [comment] 2020-12-11 16:35
> this issue seems to be related to the flipper client and this code is not owned by the facility locator but the platform team

@pjhill , any suggestions who on Platform-side might be able to look at this apparent IE11-specific Flipper bug?

cc @mmiddaugh

**Comment by pjhill** [comment] 2020-12-11 16:49
> > this issue seems to be related to the flipper client and this code is not owned by the facility locator but the platform team
> 
> @pjhill , any suggestions who on Platform-side might be able to look at this apparent IE11-specific Flipper bug?
> 
> cc @mmiddaugh

I think this [revert PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15323) might positively affect this issue. I think this PR is already merged and deployed to staging -- have another look at staging?

**Comment by pjhill** [comment] 2020-12-11 16:52
> > > this issue seems to be related to the flipper client and this code is not owned by the facility locator but the platform team
> > 
> > 
> > @pjhill , any suggestions who on Platform-side might be able to look at this apparent IE11-specific Flipper bug?
> > cc @mmiddaugh
> 
> I think this [revert PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15323) might positively affect this issue. I think this PR is already merged and deployed to staging -- have another look at staging?

Nevermind, this appears to still be broken in staging for me.  I will point the FE tools team at this issue and ask for some input.

**Comment by erikphansen** [comment] 2020-12-11 18:41
This seems to be the offending line, and it's been there for well over a year. IE11 does not support `Object.values()` https://github.com/department-of-veterans-affairs/vets-website/blob/363599279a49a487dc57255cb5daaf9da1de3498/src%2Fplatform%2Futilities%2Ffeature-toggles%2Fflipper-client.js#L8 I can probably fix this pretty easily

**Comment by erikphansen** [comment] 2020-12-11 18:48
I guess that particular file is not run through Babel? Anyway, PR to fix is at https://github.com/department-of-veterans-affairs/vets-website/pull/15336

**Comment by erikphansen** [comment] 2020-12-11 18:55
You can likely ignore my comments above. The Babel config/polyfills need to get sorted out.

**Comment by brangi** [comment] 2020-12-11 19:01
> You can likely ignore my comments above. The Babel config/polyfills need to get sorted out.

@erikphansen, does it mean the issue is in the configuration of babel?

**Comment by erikphansen** [comment] 2020-12-11 19:46
It seems that way. That line of code I changed has been there for over a year and that code should definitely be transpiled/polyfilled. For whatever reason `Object.values` did not get polyfilled in IE11.

**Comment by pjhill** [comment] 2020-12-16 14:09
FYI, I've passed this ticket on to the FE Tools team and they are looking into it.

**Comment by alexandec** [comment] 2020-12-16 16:05
Updated PR for the polyfill upgrades is here (currently being tested): https://github.com/department-of-veterans-affairs/vets-website/pull/15369. You can see the list of polyfills which will be included in [the diff here](https://github.com/department-of-veterans-affairs/vets-website/pull/15369/files#diff-ce20f0111018a9323dcdb6358e9fab31224ff729ae171cd40e53d5b2908c7e2e).

**Comment by mmiddaugh** [comment] 2020-12-16 17:11
Additionally, the issue is present on Prod (not introduced during our enhancements). This was declared not to be a launch blocker during Staging review this morning.

**Comment by alexandec** [comment] 2020-12-16 22:38
I've merged the polyfill upgrade PR (https://github.com/department-of-veterans-affairs/vets-website/pull/15369) and it's now deployed to staging. Testing `https://staging.va.gov/find-locations` I don't see the error described above, but I do see an `Object doesn't support property or method 'forEach'` error in IE 11. This is probably due to IE 11 supporting forEach only for arrays, and not for lists of DOM nodes.

**Comment by erikphansen** [comment] 2020-12-16 23:14
@alexandec so a different error? can you share a screenshot of the error in the IE11 console?

**Comment by alexandec** [comment] 2020-12-16 23:30
Yes, a different error. Unfortunately the error message doesn't provide the source of the error:
![staging-find-locations-error](https://user-images.githubusercontent.com/5805150/102418185-78516800-3fba-11eb-85c1-9fa284c64421.png)

**Comment by mpelzsherman** [comment] 2020-12-16 23:46
We were able to connect a BrowserStack session to our local dev instance. We're now getting a bit more info from the stack trace. It looks like an issue in React?

![Screenshot_12_16_20__6_45_PM](https://user-images.githubusercontent.com/80267/102419960-ef90f700-3fce-11eb-8a19-9c5ba6120a1b.png)

**Comment by alexandec** [comment] 2020-12-16 23:56
I think the error is here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/utils/helpers.jsx#L81. Replacing it with this fixes it locally for me:
```
  .forEach(el => el.parentNode.removeChild(el));
```
IE 11 doesn't support `.remove()` and core-js doesn't polyfill DOM methods.

**Comment by mpelzsherman** [comment] 2020-12-17 00:07
I just pushed a fix to https://github.com/department-of-veterans-affairs/vets-website/pull/15394.

Once that's merged, please re-test.

**Closed** 2020-12-22 19:13 UTC
Labels: bug, facility locator, frontend, vsa-facilities

**Comment by tlei123** [comment] 2020-12-23 00:48
@mpelzsherman , all failed test-cases re-run, and 100% Passed.  Re-run include failed cases for both this bug and the copy-bug #17261.

[Post-Staging-Review Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/179)

Sorry for the late response!

cc @pjhill
