### ISSUE TITLE
Alert when Backup Path doesnt start

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#88652] opened 2024-07-17 18:19 UTC
We recently had an issue where backup submissions did not start when primary path failed. This ticket will figure out how to create an alert for this scenario

[this datadog query is a good place to start](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22BGS%3A%3ASubmitForm686cJob%20failed%2C%20retries%20exhausted%21%22%20OR%20%40message_content%3A%22BGS%3A%3ASubmitForm674Job%20failed%2C%20retries%20exhausted...%22%20&additional_filters=%5B%7B%22filterType%22%3A%22event_platform%22%2C%22track%22%3A%22logs%22%2C%22included%22%3Afalse%2C%22compute%22%3A%7B%22aggregation%22%3A%22count%22%2C%22metric%22%3A%22count%22%7D%2C%22queryString%22%3A%22%40message_content%3A%5C%22CentralMail%3A%3ASubmitCentralForm686cJob%20running%21%5C%22%20%22%2C%22fields%22%3A%22%40payload.saved_claim_id%22%2C%22groupBy%22%3A%5B%7B%22facet%22%3A%22%40payload.saved_claim_id%22%2C%22limit%22%3A1000%2C%22sort%22%3A%7B%22aggregation%22%3A%22count%22%2C%22metric%22%3A%22count%22%2C%22order%22%3A%22desc%22%7D%7D%5D%7D%5D&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.saved_claim_id%2C%40request_id&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1719806400000&to_ts=1721236260000&live=false)

**Comment by sanjabaj2** [comment] 2024-07-17 19:26
I am assuming we are talking about datadog / internal alert. Not to the end user.

**Comment by sanjabaj2** [comment] 2024-08-16 15:36
This will be interesting to solve. If we don't know why backup path didn't start, how are we going to 'catch' it?

**Comment by mjknight50** [comment] 2024-08-16 16:10
I think we can separate the **why** it didn't start from **knowing** it didn't start?

@tfink419 - Can you add your two thoughts on this?

**Comment by tfink419** [comment] 2024-08-16 17:05
I agree that in this case we are simply trying to know when this occurring. We want at minimum to be able to mitigate the issue but if we can also determine the cause while it is occurring that would be ideal.

**Comment by mjknight50** [comment] 2024-08-19 20:23
The monitor is here:
https://vagov.ddog-gov.com/monitors/254804?view=spans

**Comment by tfink419** [comment] 2024-08-22 19:42
I was successfully able to trigger the situation in the staging environment. The process involved using rails console to copy and submit the same claim multiple times (50-100). In addition jobs can be given a lower retry count through a method when submitting in console. The process involved these lines of code pasted into console:

```ruby
claim = SavedClaim::DependencyClaim.last
vet_info = JSON.parse(claim.form)['dependents_application']
uuid = nil
icn = 1234

(1..50).each do |i|
  vet_info['veteran_information']['icn'] = icn += 1
  encrypted_vet_info = KmsEncrypted::Box.new.encrypt(vet_info.to_json)
  claim = SavedClaim::DependencyClaim.create(form: claim.form)
  BGS::SubmitForm686cJob.set(retry: 1).perform_async(uuid, icn, claim.id, encrypted_vet_info)
end

queue = Sidekiq::Queue.new
while true do
  queue.each { |j| j.delete if j.klass == 'CentralMail::SubmitCentralForm686cJob' }
end # interrupt after sufficient time to delete backup submissions
```

**Comment by sanjabaj2** [comment] 2024-08-22 20:32
Are you sure you did it in staging? Production monitor just triggered. 
https://vagov.ddog-gov.com/monitors/254804?view=spans

**Comment by tfink419** [comment] 2024-08-22 23:35
@mjknight50 Had altered the production monitor for this instead of creating a new monitor

**Comment by sanjabaj2** [comment] 2024-08-23 01:06
lol. Hadn’t noticed it :).
Thank you. Glad it worked. Appreciate it.
________________________________
From: Tyler Fink ***@***.***>
Sent: Thursday, August 22, 2024 4:35:32 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Bajovic, Sanja ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Alert when Backup Path doesnt start (Issue #88652)


@mjknight50<https://github.com/mjknight50> Had altered the production monitor for this instead of creating a new monitor

**Comment by mjknight50** [comment] 2024-08-23 14:39
I'm satisfied with this as a reasonable attempt to catch future cases of sidekiq not starting.  
@sanjabaj2 - Any additional concerns before we move it to closed?

**Comment by sanjabaj2** [comment] 2024-08-23 15:18
Looks good re function. Just need to update monitor description to indicate what is monitor about.

**Comment by mjknight50** [comment] 2024-08-23 15:39
Done.

**Closed by mjknight50** 2024-08-23 15:39 UTC
Labels: backend, monitoring, alerting, current sprint, code-yellow, dependents-benefits, ENG:Excellence
