### ISSUE TITLE
2nd and 3rd dependent incorrect in PDF

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#75002] opened 2024-01-31 03:11 UTC
### Background
I filled form on staging on 1/30 in staging and generated a PDF. I entered 3 dependents. 

Issues noticed:
- 2nd dependent birth place is incorrect
- 3rd dependent birth place is incorrect

Data entered and PDF generated are in this folder: https://drive.google.com/drive/folders/1XZufB2A8z32Kx32FrN1X4HxUNMb1qyBp

**Screenshot 1:**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71348ca836c671009104d080a65a6bd6a1ae8c3f/image.png" alt="image.png" />

**Screenshot 2:**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7c3460aa4b506d1625182cf123c75406a2baaac/image.png" alt="image.png" />

### Expected behavior
- Birth place entered for all dependents should appear accurately in the review step
- Birth place entered for all dependents should appear accurately in the PDF that's generated

**Comment by aplatt-coforma** [comment] 2024-01-31 05:59
Closing this ticket as a duplicate of #74697

**Closed by aplatt-coforma** 2024-01-31 05:59 UTC
Labels: pension
