### ISSUE TITLE
Convert Checkbox Group from React Component to Web Component

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#33177] opened 2021-11-23 01:21 UTC
Ticket is a side effect ticket of https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33114

Core Issue:
* Checkboxes in groups move because margin is removed when error input label is present due to css written in formation scss

Fix: 
* Convert React Component to Web Component to be able to leverage localized CSS files and match design mocks created here: https://www.sketch.com/s/cbfcac05-b6fa-4f3d-a1b6-5defe1dd79c6

Analysis: 
* Use va-checkbox web component as base line
* Checkbox Group uses Fieldset and Legend to wrap multiple checkboxes
* getMatchingSubSection needs to be ported over and is unique to Checkbox Group
* optionAdditional needs to be ported so the additional content can be revealed
* Port over options function to loop through the creation of multiple checkboxes

CSS: 
* Bring CSS over from https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-form-elements.scss

Tests to write:
* Component should render
* Component should reveal additional content
* Component should pass aXe check
* Component analytics event should be triggered when field is checked
* Component should show invalid when submission is invalid

**Comment by pdavies88** [comment] 2022-01-11 19:22
@k80bowman @bkjohnson so I wanted to recap this ticket and the related ticket of https://github.com/department-of-veterans-affairs/va.gov-team/issues/33114
The original issue presented to the team was that with the current React Components the Checkbox Group was moving when the error message would become enabled.

After discovery it was determined that this was caused by some of the globalized Formation scss files and instead of updating that global css we would create a web component for the Checkbox Group that would have the fix in it.

Also during this discovery process Natalie suggested that we adjust the Radio and Checkbox Button Groups so that they have the same uniform spacing on them because the React Components have some small styling tweaks between the two groups that make them look inconsistent.

So this ticket and the related PR accomplish the work of creating a Web Component for the Checkbox Group that doesn't move when the error state is enabled and also makes it so the styling of the Radio and Checkbox Groups are visually the same for the Web Components.

However we paused on this work because we realized that all forms use the React Components version of the Radio and Checkbox Groups and having teams switch them to Web Components might not be the best choice because we currently left form related components alone when doing the conversion to Web Components.

So this brings up some larger questions:
1. Do we want to pull in these PRs and have the Web Components available in storybook even though they won't be used?
2. Do we want to have a larger conversation about the effort to have forms use Web Components instead of React Components and if it is the best strategy to do? Also this would include conversations around documentation of usage
3. Since the React Components are the components in use and will remain that way in the near term, should we go about the task of trying to fix the Formation scss so that the Radio and Checkbox Groups have the same spacing and that the Checkbox Group error message does not cause the buttons to move? Originally we said no, but if we don't plan on having teams adapt over to the Web Components because that is a larger effort we may want to reconsider this bullet

**Comment by bkjohnson** [comment] 2022-01-12 14:48
I think there would be value in discussing your second question. Answers from that may inform questions one and three.

**Comment by k80bowman** [comment] 2022-01-12 20:12
@bkjohnson I know you mentioned at one point that Formulate was designed to make use of web components. Is that true for form control components like these?

**Comment by bkjohnson** [comment] 2022-01-12 22:22
Yes, that's true for form controls. Formulate is [using our web component React bindings](https://github.com/department-of-veterans-affairs/formulate/blob/8e6e4efbcdfcbdd9d8a501c401ec97b1196dd2c2/src/form-builder/CheckboxField.tsx#L6) to [connect the event handlers to the global form state](https://formik.org/docs/api/useField) provided by Formik.

**Comment by k80bowman** [comment] 2022-01-13 01:42
Next question, would it be a problem for our current forms system to use web components?

**Comment by bkjohnson** [comment] 2022-01-13 16:08
I'm not totally sure. We could probably do the same kind of thing we did with formulate and have the widgets wrap our web components and set the props to whatever they needed to be, but that might break some styling. We could put our web components in the widgets and do some testing to see what happens.

**Comment by k80bowman** [comment] 2022-01-13 19:53
Ok, thank you. I think we should finish off these two tickets and make the components available. I know they can't be used right now, but I'd like to create a ticket for us to do a little discovery on what you mentioned @bkjohnson just to see if it is possible and what it would take to use these web components in the Forms System. Having the component already published and available will make that experiment much easier. I would also like to bring this up as a consideration with the Forms Library Team as they move forward. We definitely want whatever shape the Forms System takes in the future to include use of our components.

Any objections?

**Comment by k80bowman** [comment] 2022-01-13 20:28
In answer to your other two questions, @pdavies88:
1. I don't know yet. @bkjohnson I'd like to hear your thoughts on this. We could always wait, see how our experiment turns out, and add them to Storybook later.
3. I agree that we need to address the original issue in the CSS. Do you want to create a ticket for getting that work done?

**Comment by pdavies88** [comment] 2022-01-13 21:10
@k80bowman here is the new ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35373

**Comment by bkjohnson** [comment] 2022-01-14 21:35
I'm fine with waiting. It sounds like the spike team is [doing some similar testing](https://github.com/department-of-veterans-affairs/formulate/issues/60#issuecomment-1012430419) that we may want to talk about.

**Comment by k80bowman** [comment] 2022-01-17 13:44
Oh nice. Ok, then yes, let's finish and merge these two PRs, but don't add them to Storybook yet. Once they're merged, we can let the FLT know that these components are available, if they want to use them for testing.

**Closed** 2022-01-21 23:36 UTC
Labels: vsp-design-system-team
