### ISSUE TITLE
Enable display of multiple personal health care contacts

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#72549] opened 2023-12-22 19:23 UTC
### User story

As a Veteran who has provided multiple Personal Health Care Contacts to the VA, I want to see them all listed on the Medical Contacts page of my profile, so that I don't have a frustrating experience calling the VA to correct the data.

### Notes

Assumptions:
- API will be returning multiple contacts when we start this story
- existing experience got a11y review prior to usability testing sessions

Possible tasks:

- [x] consult with UX about design needs for this ticket (desktop and mobile)
  - Jonathan may have draft designs from last year
- [x] design will adapt to various data possibilities
- [ ] ~share with Samara~ Samara is no longer on the auth-exp team.
- [x] a11y review before dev
- [x] QA is part of this ticket
- [x] design review
- [x] a11y review of implementation

Current design for 1 of NoK and EC is below. Note:
- ~Singular "person" in description text above each~ Decided to go with plural because there can be multiple.
- No obvious pattern present (e.g. a border/line) to create a boundary between multiple contacts. May not be needed if padding is sufficient to distinguish between separate components

<details><summary>Screenshots</summary>

<img width="476" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/930237c4-b5d3-4b52-8d5c-f8ff98529df2">

</details>

## Acceptance criteria

- Got approval from Samara / AuthExp for updated design before implementation
- A11y review prior to development
- Profile NoK/EC displays multiple ECs or NoKs when present in back-end

**Comment by wesrowe** [comment] 2024-02-02 19:43
I've added a screenshot to the body of this ticket with a couple notes on how the single-contact UI might need to adapt for multiple contacts of either type (NoK or EC).

I think pluralizing the description is probably a no-brainer, i.e. `The person we’ll contact in an emergency` becomes `The people we’ll contact in an emergency`.

@radavis, I think there's a data question that will drive the UX design. When test data has been created, we'll want to see if  there is an indication of priority coming from the API – i.e., if a user has two ECs, do they come back in a clear order as primary and secondary?

Please add a comment here when you find that out.

**Comment by radavis** [comment] 2024-02-02 20:37
The `contactType` field will contain one of the following:

- 'Primary Next of Kin'
- 'Other Next of Kin'
- 'Emergency Contact'
- 'Other emergency contact'

When I had access to the dev Enrollment System on Wednesday, it seemed as if you could only enter one record per type, if I remember correctly.

**Comment by wesrowe** [comment] 2024-02-05 23:06
If what Richard says above is the case, then I might make this suggestion for the UX: add a label in the UI for each contact. Such that each contact person would be labeled "Primary Net of Kin", "Other Next of Kin" if present, etc.

I think we need UX advice on what the label should look like. @fmccaf1 @jonathanjnelson @keithcheung828

**Comment by wesrowe** [comment] 2024-02-20 19:14
screenshot of current implementation, from Staging (user 11):
<img width="539" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/ba70ffe9-9f92-420e-8986-a2fcab4a1bb1">

**Comment by wesrowe** [comment] 2024-02-24 00:06
obvious point for when Jonathan is back: we need the various cases fleshed out. one contact, no contacts, etc. Maybe it's obvious, but it would be very helpful to see them all together as a source of truth for dev and QA.

**Comment by radavis** [comment] 2024-03-05 14:35
Create TestRail scenarios for the following:

![Screenshot 2024-03-05 093333](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1299034/8796a7e1-3cc4-4c1c-a839-201c3b76a080)

**Comment by radavis** [comment] 2024-03-06 20:46
Notes:

- Cheng Z. expressed some concern over the change in terminology with contact types within ES and what's displayed on VA.gov. (e.g. - Primary Next of Kin/Other Next of Kin vs. Primary next of kin/Secondary next of kin, Emergency Contact/Other emergency contact vs. Primary emergency contact/Secondary emergency contact).

- Dan B. reports that VoiceOver reads phone numbers as actual numbers (e.g. - two million...). Fix w/ aria-label.

**Comment by danbivins** [comment] 2024-03-06 20:52
I huddled with Richard this morning and performed the initial a11y review this afternoon. I relayed to Richard one somewhat minor issue that was found. 

Issue: The static text for the phone numbers gets read by a screen reader as a number, like "two hundred and 2, four hundred thirty-three ..." rather than a telephone number. So I think we should handle it similar to [the DS telephone number pattern](https://design.va.gov/components/telephone) and use an aria-label to spell out the number more explicitly. 

I'd like to review once the fix is in place to make sure it's working as intended. 

Tested with:
* Axe
* WAVE
* NVDA + Chrome
* JAWS + Edge and Chrome
* VoiceOver + Safari 
* Zoom to 400%

**Comment by danbivins** [comment] 2024-03-07 20:08
The issue noted above with the phone number readout in VoiceOver is resolved. This work is good to go from an a11y perspective.  @radavis

**Comment by jonathanjnelson** [comment] 2024-03-07 22:13
Designs in Figma: [Mobile](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=0%3A1&mode=design&t=dGThg81nSSeQ4EdX-1), [Desktop](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=0%3A444&mode=design&t=dGThg81nSSeQ4EdX-1)

**Comment by jonathanjnelson** [comment] 2024-03-08 19:55
Awesome work on this @radavis. 

Documenting our conversation here: 

- The headings in Profile are semantically correct in the code but visually styled differently (e.g., _Personal health care contacts_ is styled as an H2) 
- If, 2 Emergency Contacts  yields the output:
     - **Primary emergency contact**
          - The person we'll contact in an emergency.  
     - **Secondary emergency contact**
          - The person we'll contact if your primary contact isn't available. 
- If possible, do not display the subheading (e.g., Primary emergency contact) if displaying just one emergency contact

**Comment by radavis** [comment] 2024-03-14 14:18
Allan's QA work for this feature:

- Test Plan: https://dsvavsp.testrail.io/index.php?/plans/view/5310
- Regression: https://dsvavsp.testrail.io/index.php?/runs/view/5313&group_by=cases:section_id&group_order=asc
- Coverage Report: https://dsvavsp.testrail.io/index.php?/reports/view/709
- Summary of Defects: There wasn't any defects, so there isn't a report for this.

Collab Cycle Asks:
- e2e tests for feature: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/tests/e2e/personal-health-care-contacts/contacts.cypress.spec.js#L1:L1
- code coverage for `src/applications/personalization` application folder: 80%

![Screenshot 2024-03-14 at 09-20-48 Code coverage report for src-applications-personalization](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1299034/1131981e-4004-4b2c-b269-74727ec54f32)

**Closed** 2024-03-14 14:20 UTC
Labels: ux, my-health, Cartographers
