### ISSUE TITLE
Look into Jenkins fails 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2514] opened 2019-10-16 17:54 UTC
Take some time to look into why these issues are happening ie a few hours and then spend a few more into fixing the issues.

**Comment by jbritt1** [comment] 2019-10-17 13:17
```
jenkinsAPP 9:16 AM
Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-reporter/162/console

Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-self-service/177/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:18
```
Failed to deploy cms to vagov-staging!
http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-staging/42/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:18
Failed to deploy revproxy to vagov-prod!
http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-prod/142/console

**Comment by jbritt1** [comment] 2019-10-17 13:19
```
Failed to deploy revproxy to vagov-sandbox!
http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-sandbox/7/console

Failed to deploy revproxy to vagov-staging!
http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-staging/150/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:20
```
Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-reporter/161/console

Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-self-service/176/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:20
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:20
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:21
```
jenkinsAPP 2:44 PM
Failed to deploy cms to vagov-staging!
http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-staging/41/console

jenkinsAPP 2:53 PM
Failed to deploy cms to vagov-dev!
http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-dev/128/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:21
```
Failed to run post-deploy action on vets-api-server in vagov-prod!
http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-prod-post-deploy/11/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:21
```
vets-website master branch CI failed. |http://jenkins.vfs.va.gov/job/testing/job/vets-website/job/master/5299/display/redirect
```

**Comment by jbritt1** [comment] 2019-10-17 13:22
```
Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-self-service/175/console

Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-reporter/160/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:22
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:23
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:23
```
SSL certificate scan result
URGENT: /ssl/wildcard.vets.gov.chained.crt expires in less than 30 days: 2019-11-12T23:59:59+00:00
URGENT: /ssl/wildcard.vets.gov.crt expires in less than 30 days: 2019-11-12T23:59:59+00:00
One or more certificates is expiring soon. Investigate ASAP!
Full Report: http://jenkins.vfs.va.gov/job/utility/job/cert-expiry-scanner/465/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:29
```
Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-self-service/174/console

Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-reporter/159/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:29
```
Failed to create build for base-encrypted!
http://jenkins.vfs.va.gov/job/builds/job/base-encrypted/87/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:30
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:31
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:31
```
(Testing) @jbalboni: integration tests failed. |http://jenkins.vfs.va.gov/job/testing/job/vets-website-integration-testing/113/display/redirect
```

**Comment by jbritt1** [comment] 2019-10-17 13:31
```
vets-website master branch CI failed. |http://jenkins.vfs.va.gov/job/testing/job/vets-website/job/master/5288/display/redirect
```

**Comment by jbritt1** [comment] 2019-10-17 13:32
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:32
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:32
```
Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-reporter/158/console

Failed to create release for developer-portal!
http://jenkins.vfs.va.gov/job/releases/job/developer-portal-self-service/173/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:33
```
Unapplied database migrations: vets-api-server-vagov-staging.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:33
```
jenkinsAPP 3:45 PM
Unapplied database migrations: vets-api-worker-vagov-staging.
 down    20191007182427  Feature toggle event

jenkinsAPP 3:46 PM
Unapplied database migrations: vets-api-worker-vagov-dev.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:33
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:33
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:33
```
Unapplied database migrations: vets-api-server-vagov-dev.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:34
```
jenkinsAPP 2:48 PM
Unapplied database migrations: vets-api-worker-vagov-dev.
 down    20191007182427  Feature toggle event

Unapplied database migrations: vets-api-worker-vagov-staging.
 down    20191007182427  Feature toggle event
Unapplied database migrations: vets-api-server-vagov-staging.
 down    20191007182427  Feature toggle event
Unapplied database migrations: vets-api-server-vagov-dev.
 down    20191007182427  Feature toggle event
jenkinsAPP 3:01 PM
Unapplied database migrations: vets-api-worker-vagov-dev.
 down    20191007182427  Feature toggle event
```

**Comment by jbritt1** [comment] 2019-10-17 13:34
```
Failed to deploy saml-proxy to dvp-staging!
http://jenkins.vfs.va.gov/job/deploys/job/saml-proxy-dvp-staging/96/console

Failed to deploy saml-proxy to dvp-dev!
http://jenkins.vfs.va.gov/job/deploys/job/saml-proxy-dvp-dev/89/console
Failed to deploy saml-proxy to dvp-prod!
http://jenkins.vfs.va.gov/job/deploys/job/saml-proxy-dvp-prod/76/console
Failed to create build for unbound-dns!
http://jenkins.vfs.va.gov/job/builds/job/unbound-dns/42/console
Failed to create build for api-gateway!
http://jenkins.vfs.va.gov/job/builds/job/api-gateway/34/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:35
```
jenkinsAPP 11:51 AM
Failed to create build for gi-bill-data-service!
http://jenkins.vfs.va.gov/job/builds/job/gi-bill-data-service/257/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:35
```
Failed to create build for cms!
http://jenkins.vfs.va.gov/job/builds/job/cms/155/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:35
```
Failed to create release for saml-proxy!
http://jenkins.vfs.va.gov/job/releases/job/saml-proxy/38/console

Failed to create build for utility-exporter!
http://jenkins.vfs.va.gov/job/builds/job/utility-exporter/300/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:35
```
Failed to deploy developer-portal to prod!
http://jenkins.vfs.va.gov/job/deploys/job/developer-portal-prod/234/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:36
```
Failed to update Base OS for staging!
http://jenkins.vfs.va.gov/job/infrastructure/job/os-update-staging/412/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:36
```
Failed to update Base OS for prod!
http://jenkins.vfs.va.gov/job/infrastructure/job/os-update-prod/406/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:36
```
Failed to update Base OS for utility!
http://jenkins.vfs.va.gov/job/infrastructure/job/os-update-utility/412/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:36
```
Failed to update Base OS for dev!
http://jenkins.vfs.va.gov/job/infrastructure/job/os-update-dev/438/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:37
```
Failed to update Jumpboxes and VA Socks Proxy!
http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/372/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:37
```
Failed to update Jumpboxes and VA Socks Proxy!
http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/371/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:37
```
Failed to create release for sentry!
http://jenkins.vfs.va.gov/job/releases/job/sentry/333/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:37
```
Unapplied database migrations: vets-api-server-vagov-prod.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:37
```
Unapplied database migrations: vets-api-worker-vagov-prod.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:38
```
Unapplied database migrations: vets-api-server-vagov-dev.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:38
```
Unapplied database migrations: vets-api-worker-vagov-staging.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:38
```
Unapplied database migrations: vets-api-worker-vagov-dev.
 down    20191004164703  Add min max to drivetime bands
```

**Comment by jbritt1** [comment] 2019-10-17 13:39
```
OS check needs attention in prod!
http://jenkins.vfs.va.gov/job/utility/job/os-check-prod/726/console

OS check needs attention in dev!
http://jenkins.vfs.va.gov/job/utility/job/os-check-dev/758/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:39
```
jenkinsAPP 7:01 AM
OS check needs attention in prod!
http://jenkins.vfs.va.gov/job/utility/job/os-check-prod/725/console

4 replies
Last reply 10 days agoView thread

jenkinsAPP 7:02 AM
OS check needs attention in dev!
http://jenkins.vfs.va.gov/job/utility/job/os-check-dev/757/console
```

**Comment by jbritt1** [comment] 2019-10-17 13:40
```
vets-website master branch CI failed. |http://jenkins.vfs.va.gov/job/testing/job/vets-website/job/master/5306/display/redirect
```

**Comment by jbritt1** [comment] 2019-10-17 13:42
##All Jenkins failures for the past week and a half (Sunday, October 6 - Present [Thursday, October 17@0941]).##

Plan is to investigate each of the above and search for patterns / work with teams to get as many of them resolved as possible during this sprint.

**Comment by jbritt1** [comment] 2019-11-06 15:03
As we near completion of this task (most of what is left is a single issue / process that needs a solid solution implemented) I see that even outside of the scope of this assignment some jobs do continue to fail due to one-offs (testing failures, typos, etc.) and I believe that to be somewhat expected to some degree. We will need to continue to monitor the channel and I plan to help out going forward by researching failures and attempting to post what I think is the root cause to the appropriate Slack channels.

**Comment by jbritt1** [comment] 2019-11-14 17:15
All of the work for this will be done as soon as the PR's are merged.

**Closed** 2019-11-14 19:09 UTC
Labels: operations
