### ISSUE TITLE
General Analytics Request for Clipboard / Digital Health Forms

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#25278] opened 2021-05-26 15:49 UTC
# Metrics Reporting Request

Clipboard/Digital Health Forms is requesting assistance from the analytics team with knowing, for users who directly visit our [application URL](https://staging.va.gov/health-care/health-questionnaires/questionnaires/) as their first page in a session:
* how many authenticate though to our application
* how many do not try to authenticate
* how many try and fail to authenticate

The current GA Dashboard template: https://analytics.google.com/analytics/web/template?uid=ijXEbsLdSci9BrJRHvw8EA

Relevant Slack Thread: https://dsva.slack.com/archives/C1Q4294JJ/p1621975042031000

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Stephen Barrs (stephen.barrs@va.gov)
    
- What team/project is this work for?
* Clipboard / Digital Health Forms
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
* all times in the future

## Analytics to Track Down
for users who directly visit our [application URL](https://staging.va.gov/health-care/health-questionnaires/questionnaires/) as their first page in a session:
 - [ ]  how many authenticate though to our application
 - [ ]  how many do not try to authenticate
 - [ ]  how many try and fail to authenticate 

## Which Product Questions are you trying to answer?
* We want to know if requiring authentication is a barrier to Veterans completing these forms

## Other Helpful Questions to think through
- Who is your audience? OCTO Product Managers 
- Why do you need this data? We are launching a pilot for digital health forms and need to know if full authentication is a barrier to Veterans completing these important forms. 
- What are you hoping to find? That full authentication is not a barrier to Veterans completing forms
- What is your hypothesis that you're ~~hoping~~expecting the data will support? That full authentication is a barrier to Veterans completing these forms
- What area of the VA are you hoping to assess? completion of digital health forms
- How frequently do you need this data? we would like to collect all data at this point as this is a limited pilot at a single VAMC and Clinic with limited participants

## Link to Metrics
https://analytics.google.com/analytics/web/template?uid=ijXEbsLdSci9BrJRHvw8EA

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment] 2021-05-27 01:19
@stephenBarrs -

We may have to approach these questions a bit differently.  And - a warning - GA dashboards are remarkably limited and can't even do basic arithmetic on metrics.  Your best bet would be getting the individual metrics outlined below or - eventually - moving this to Domo/BigQuery where we can SQL all of this.

### Total Successful Logins

Anyone who logs in via this page is redirected to this URL:  `https://staging.va.gov/health-care/health-questionnaires/questionnaires/?postLogin=true`  <br><br>A `Pageviews` of this URL should get you your total logins.

### Total Attempted Logins

We can see how many people **do** try to login with these `login-attempted-` [events on this page](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20210526&_u.date01=20210526&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22staging.va.gov~2F%3Fnext=~2Fhealth-care~2Fhealth-questionnaires~2Fquestionnaires~2F%22,0%5D,%5B0,%22analytics.eventLabel%22,%22BW%22,%22login-attempted-%22,0%5D%5D/).

### Didn't attempt to login

I think we can get this by getting total login prompts - `Pageviews` for `https://staging.va.gov/?next=%2Fhealth-care%2Fhealth-questionnaires%2Fquestionnaires%2F` - and subtracting the attempts above.

### Tried to login, but failed

This one is a bit tough outside of BigQuery or a sequence segment in GA.  We get `login-error` and `login-mismatch` events, but in very low numbers.

Would inferring this # from the above `Attempted Logins` - `Successful Logins` get us there?

**Comment by stephenBarrs** [comment] 2021-06-01 19:00
@bsmartin-ep Thanks for all the ideas and guidance.  I think we have enough for now and if we need more it sounds like we will need to set up analytics in Domo for this.  For our pilot this will get us the data we need. 

related question: I want to share this dashboard with the other users of our analytics view (not sure that is the correct term, but with the other people who can authenticate and see this data), and it looks like i need to be able to see a `share -> share object` option to do that, but I cannot see that.  Is this a permissions issue or is there some other way that I can have this dashboard shared appropriately for both Staging and Prod?  

Here is the link to the latest template work: https://analytics.google.com/analytics/web/template?uid=WtydHbl8QIWo7o_DIzC4bA

**Comment by bsmartin-ep** [comment] 2021-06-01 19:02
Try to share again @stephenBarrs.  You didn't have Collaborate permissions on the account for some reason.

**Comment by stephenBarrs** [comment] 2021-06-01 19:04
Thanks @bsmartin-ep the share option is available now!

**Comment by stephenBarrs** [comment] 2021-06-03 15:34
@bsmartin-ep 
I shared this GA Dashboard for production and ran some prod testing yesterday, but am not seeing the expected data in Prod.  It does show up in the Staging.  Specifically the `Total Logon Success` widget which collects page-views that end with `health-care/health-questionnaires/questionnaires/?postLogin=true` is not logging any events and I have logged on a few times.  Could I get a sanity check on this dashboard? 

[Prod Dashboard](https://analytics.google.com/analytics/web/#/dashboard/-Hcb3V55SRCZU83OOaHQtg/a50123418w177519031p184624291/_u.date00=20210601&_u.date01=20210603/)

[Staging Dashboard](https://analytics.google.com/analytics/web/#/dashboard/gzg4SouDT4SN0-gADcjOCg/a50123418w178298118p176884211/)

**Comment by bsmartin-ep** [comment] 2021-06-06 21:50
Ah @stephenBarrs - I think the issue is that the Production one is using the "WBC" view, which - infuriatingly - was configured years ago to drop in a default document of _/index.html_ for each Page URL.

If you switch this to the All View, it should work as-is.  You also change your filter to a regex to work with both...

```
health-care\/health-questionnaires\/questionnaires\/(index\.html)?\?postLogin=true
```

**Comment by bsmartin-ep** [comment] 2021-07-09 02:41
Hey @stephenBarrs - anything else you needed for this request?

**Comment by joanneesteban** [comment] 2021-08-11 17:38
@stephenBarrs @dillo Hello! The Analytics team is closing this ticket, but please feel free to reopen if you need additional support from us.

**Closed by joanneesteban** 2021-08-11 17:38 UTC
Labels: analytics-insights, analytics-request
