### ISSUE TITLE
Analytics Implementation or QA Support for Public Websites [Yellow Ribbon]

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7199] opened 2020-03-24 23:08 UTC
# Analytics Implementation or QA Request

## Description
- **Is this request for Google Analytics implementation or QA?**
  - Google Analytics, Foresee

- **Who is this request for?**
  - @jenniferlee-dsva , @MickinSahni 
    
- **What team/project is this work for?**
    - Public Websites, Yellow Ribbon

- **Provide the Domain where Google Analytics needs to be implemented**
    - www.staging.va.gov (Does this automatically roll up to va.gov?)
     
- **Please provide any upcoming deadlines or important milestones**
    - Launch date revised for May 8th

- **Typical Website Interactions to Track**   
    - https://staging.va.gov/education/yellow-ribbon-participating-schools/
    - Search refinements before and after initial search
    -  Exits to university pages
    - Screenshots
       - <img src="https://user-images.githubusercontent.com/13204473/77832230-e2fc0400-710a-11ea-96f2-5afef555a38f.png" width="200px">       
       - <img src="https://user-images.githubusercontent.com/13204473/77485132-c60dbb00-6e02-11ea-9422-4402261ae930.png" width="200px">

- **No authentication**
 
> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

### Yellow Ribbon Search

<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>Search on Yellow Ribbon Page</td>
<td>
<img src="https://user-images.githubusercontent.com/62304138/80405686-ee208c00-8890-11ea-8aec-d5b33fae41f5.png" />
</td>
<td><pre>{
    'event': 'edu-yellow-ribbon-search',
    'edu-yellow-ribbon-name': 'string' | undefined,
    'edu-yellow-ribbon-state': 'string' | undefined,
    'edu-yellow-ribbon-city': 'string' | undefined,
    'edu-yellow-ribbon-contribution-amount': 'unlimited' | undefined,
    'edu-yellow-ribbon-number-of-students': 'unlimited' | undefined,
    'edu-yellow-ribbon-number-of-search-results': n | undefined
} </pre></td>
</tr></table>

### Pagination

<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>
Click on <em>Next</em> link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405725-fd073e80-8890-11ea-9d5d-f181b7f9ace9.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-next',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>

<tr>
<td>
Click on <em>Previous</em> link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405767-0abcc400-8891-11ea-8184-5798eeafc71c.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-previous',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>

<tr>
<td>
Click on <em>Numerical</em> link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405800-160fef80-8891-11ea-9052-34254b7d4e72.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-number',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>
</table>

**Comment by nedierecel** [comment] 2020-03-27 20:44
@jonwehausen @bsmartin-ep This is a new analytics request to review. Thanks!

**Comment by joanneesteban** [comment] 2020-04-01 15:30
@MickinSahni can you let us know when the new launch date might be?

**Comment by MickinSahni** [comment] 2020-04-01 17:39
> @MickinSahni can you let us know when the new launch date might be?

Hey @joanneesteban, this likely looking like the end of the month as we have some additional BUILD items to complete. I commented on our other analytics request that [that one is more important](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174) than this and can be prioritized before Yellow Ribbon.

**Comment by jonwehausen** [comment] 2020-04-09 15:59
Hi @MickinSahni,

### Existing Tracking: 
- If it's alright with you -- we won't do any formal link tracking for the 3 helpful links since they appear to be unique and aren't duplicated anywhere else on the page. Instead we'll deliver a custom page path report similar to what we did on #7345
- Also for the `.edu` links -- If you can confirm those will simply go to the exact URL it's identified, those will come back as outbound where we have existing global tracking - we can do a custom report around these too if needed

## Config Changes
- @bsmartin-ep Within the Non-Production Education Modernized View I've configured the following:

**Comment by jonwehausen** [comment] 2020-04-09 16:12
Hi @MickinSahni,

### Outstanding Question
- Could you refine for us what you mean by "before and after" search refinements? For this scope, we are planning on delivering the OOB GA Metric for Search Refinements. 
- What were you looking to report on in the context of "before" and "after" ?
- What type of insight are your trying to get to? 

### Existing Tracking: 
- If it's alright with you -- we won't do formal link tracking for the 3 helpful links since they appear to be unique and aren't duplicated anywhere else on the page. Instead we'll deliver a custom page path report similar to what we did on #7345
- For the `.edu` links -- If you can confirm those will simply go to the exact URL it's identified, those will come back as outbound where we have existing global tracking - we can do a custom report around these too if needed

### Config Changes - @bsmartin-ep 
-  Within the Non-Production Education Modernized View I've configured and saved the following: 
**Query Parameters:** `name, city`
**Category parameter:** `country, state, category, contributionAmount, numberOfStudents`
- My thought is to keep those items that the user actually types into the text field, in this case "School Name" and "City", as the parameters and items that are dropdowns or checkboxes as the categories
- Keep in mind this view is used for other searches within the Education portion of the site, such as GIBCT
- @bsmartin-ep Could you spend some time and run a bunch of different variations using each of those search components test searches (@MickinSahni feel free to add to the fun 😆) within staging and we can use this as our validation in preparation for launch?
- It may be worth documenting the types of searches you can do and then we can run Site Search reports within staging that things look good. 

Following @MickinSahni's clarification on what he's looking to tracking, we can verify whether there will need to be anymore config work and can move this to Review/QA and begin seaerch testing fun. 

cc: @joanneesteban

**Comment by MickinSahni** [comment] 2020-04-09 21:15
Hey @jonwehausen tried to clarify some of your questions. 

> Could you refine for us what you mean by "before and after" search refinements? For this scope, we are planning on delivering the OOB GA Metric for Search Refinements.

> What were you looking to report on in the context of "before" and "after" ?

Sure. This is about making sure we're tracking usage of search refiners like `School name` field or `Only show schools that provide funding to all eligible students` toggle when a user first lands on the Yellow Ribbon landing page **and** usage of those refiners after they've completed an initial search. The goal is/was to be as exhaustive with our analytics coverage as possible so might've been overkill on my part.

>If it's alright with you -- we won't do formal link tracking for the 3 helpful links since they appear to be unique and aren't duplicated anywhere else on the page. Instead we'll deliver a custom page path report similar to what we did on #7345

That works too. If it's in a consolidated place that's a pretty important win (so we don't have to dig for it). For example and context, we're embedding the reports/dashboards/etc. you're providing us into [the associated product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md#kpis) cc @joanneesteban 

>For the .edu links -- If you can confirm those will simply go to the exact URL it's identified, those will come back as outbound where we have existing global tracking - we can do a custom report around these too if needed

Is the implication that if the list of schools in the results ever changes, we won't dynamically capture changes?

**Comment by bsmartin-ep** [comment] 2020-04-10 15:54
@jonwehausen  - I generated these searches this AM. 

I didn't see a way to generate the _category_ param from the UI.

```
/?name=New+York
/?state=PA
/?state=AL
/?city=Montgomery
/?city=Harrisburg
/?name=New+York&numberOfStudents=unlimited
/?name=New+York&numberOfStudents=unlimited&contributionAmount=unlimited
/?numberOfStudents=unlimited&contributionAmount=unlimited&state=GU
/?contributionAmount=unlimited&state=PA&city=York
/?contributionAmount=unlimited&state=PA
/?contributionAmount=unlimited&numberOfStudents=unlimited
```

**Comment by bsmartin-ep** [comment] 2020-04-10 15:55
@MickinSahni -

I noticed while testing that the checkboxes themselves aren't clickable - but the labels are. If you tab in and hit enter / space, it does work.

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/d11e0b51-769b-4de4-b25c-770b6e1470ef)

**Comment by jonwehausen** [comment] 2020-04-10 16:06
@bsmartin-ep - Good catch. 

Updated prior comment to say those we need to test and are part of this functionality.

**Comment by MickinSahni** [comment] 2020-04-10 19:52
> I noticed while testing that the checkboxes themselves aren't clickable - but the labels are. If you tab in and hit enter / space, it does work.

Thanks for the find, @bsmartin-ep. We're addressing that here!: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7791

**Comment by kelsonic** [comment] 2020-04-14 18:11
@bsmartin-ep @MickinSahni Thanks for finding that! We have [a PR up](https://github.com/department-of-veterans-affairs/vets-website/pull/12218) for that issue now. Any update here? We have a couple tickets left addressing content + e2e tests, but then analytics will be one of our last blockers to launching YR.

**Comment by MickinSahni** [comment] 2020-04-15 15:42
> Any update here? We have a couple tickets left addressing content + e2e tests, but then analytics will be one of our last blockers to launching YR.

👋 Morning, @bsmartin-ep @jonwehausen.
Deferring to you for this one. We know you prioritized Find VA Forms + AMA pt. 2 for us so understand if this Yellow Ribbon request is on-deck.

**Comment by jonwehausen** [comment] 2020-04-15 16:20
Hi @MickinSahni 

Thanks for reaching out and clearing up those questions above, taking a look at our test searches Brian conducted within staging that flow to our non-production property. 

To follow-up on those items: 
1. Our OOB Search Refinements and Search Refinements % will cover those users that are changing their search using those components. 
2. Great 👍 
3. Outbound link tracking will continue to track those links as long as they lead to `.edu` pages

**Comment by MickinSahni** [comment] 2020-04-15 19:07
> Hi @MickinSahni
> 
> Thanks for reaching out and clearing up those questions above, taking a look at our test searches Brian conducted within staging that flow to our non-production property.
> 
> To follow-up on those items:
> 
> 1. Our OOB Search Refinements and Search Refinements % will cover those users that are changing their search using those components.
> 2. Great 👍
> 3. Outbound link tracking will continue to track those links as long as they lead to `.edu` pages

Awesome. Thanks, @jonwehausen. Regarding 3. just for our awareness, is that based on pattern-matching to `.edu`?

**Comment by jonwehausen** [comment] 2020-04-16 17:20
@MickinSahni Correct - as long as the links go out to a `.edu` URL, they will render as outbound link clicks.

**Comment by kelsonic** [comment] 2020-04-22 19:33
Any update here? 🙂

**Comment by jonwehausen** [comment] 2020-04-22 21:32
Hi @kelsonic ,

@bsmartin-ep and I are working on a solution here... for your awareness, some of the out of box GA site search metrics we thought would initially would suffice are presenting some problems based on how the search is setup from the FE, so we've been solutioning how we can deliver the metrics you all need in a more meaningful way. We're making progress and should have a direct path forward here shortly. 

We will have this done this sprint by 4/30.

**Comment by kelsonic** [comment] 2020-04-23 13:55
Perfect! Thanks for the update @jonwehausen!

So I'm currently hypothesizing we'll likely want to add:

1. An event each time a search is made

![image](https://user-images.githubusercontent.com/12773166/80106413-0f067b80-8537-11ea-88a6-4c077d7cf5ff.png)

2. An event each time someone clicks on a school website

![image](https://user-images.githubusercontent.com/12773166/80106431-17f74d00-8537-11ea-936d-8f94a97f0e3c.png)

Would there be any other event we should add other than these two? 🙂

**Comment by bsmartin-ep** [comment] 2020-04-27 13:03
@jonwehausen -

A first pass at the data layer:

https://docs.google.com/document/d/1Qn5EAdZ62_XVynsWpjy5RT7L_VT-ts8udpXBFBE0Fzo/edit?usp=sharing

Still on the fence if the `page-number` should be something more specific like `paginate-page-number`.

**Comment by jonwehausen** [comment] 2020-04-27 16:53
@bsmartin-ep Thanks for getting a jump on this! A few recommendations I have following review: 

- Prefix event name and each DL variable with `edu-`
- Replace `page-number` with `paginate-page-number`

Other than this, we're ready to move forward! Please document the final DL in a comment below and tag @kelsonic so he can create a ticket on his part.

**Comment by bsmartin-ep** [comment] 2020-04-27 18:25
## Datalayer Requirements

### Yellow Ribbon Search

<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>Search on Yellow Ribbon Page</td>
<td>
<img src="https://user-images.githubusercontent.com/62304138/80405686-ee208c00-8890-11ea-8aec-d5b33fae41f5.png" />
</td>
<td><pre>{
    'event': 'edu-yellow-ribbon-search',
    'edu-yellow-ribbon-name': 'string' | undefined,
    'edu-yellow-ribbon-state': 'string' | undefined,
    'edu-yellow-ribbon-city': 'string' | undefined,
    'edu-yellow-ribbon-contribution-amount': 'unlimited' | undefined,
    'edu-yellow-ribbon-number-of-students': 'unlimited' | undefined,
    'edu-yellow-ribbon-number-of-search-results': n | undefined
} </pre></td>
</tr></table>


## Pagination

<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>
Click on _Next_ link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405725-fd073e80-8890-11ea-9d5d-f181b7f9ace9.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-next',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>

<tr>
<td>
Click on _Previous_ link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405767-0abcc400-8891-11ea-8184-5798eeafc71c.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-previous',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>

<tr>
<td>
Click on _Numerical_ link in pagination control </td>
<td>  <img src="https://user-images.githubusercontent.com/62304138/80405800-160fef80-8891-11ea-9052-34254b7d4e72.png" />  </td>
<td><pre>{
    'event': 'nav-paginate-number',
    'paginate-page-number': n | undefined
}</pre></td>
</tr>
</table>

cc @kelsonic @jonwehausen

**Comment by bsmartin-ep** [comment] 2020-04-27 18:51
@kelsonic -

I should have specifically mentioned that you should pass in an _undefined_ if you don't have a value for these params (to prevent bleed over between events) as opposed to just leaving it out of the JS object.

**Comment by bsmartin-ep** [comment] 2020-04-27 23:21
@jonwehausen -

GTM workspaces are updated and ready for you to QA when the data layer changes are ready.

### Yellow Ribbon Search

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000266

- Added DL variables (with default values of _(Not Set)_)
- Enabled # of search results metrics in non-prod GA
- Updated Yellow Ribbon Search event tag to use data layer variables for custom dimensions and new metric
- Removed unused URL and CJ stuff
- Added exception to main Form Events tag for Yellow Ribbon Search
- Reminder: this is all still pointing to the staging base config in GTM

### Pagination

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000278

- Updated page number variable name

**Comment by kelsonic** [comment] 2020-04-28 19:29
Hmm, we perhaps should make a different ticket for the Pagination analytics since that will affect all pages across va.gov that use the common `<Pagination />` component 🙂CC @stephorkandatx @bsmartin-ep

**Comment by bsmartin-ep** [comment] 2020-04-28 19:52
Sounds good to me @kelsonic.  We split our GTM implementation into two parts juuuuuust in case.

Is this a ticket we would open?

**Comment by kelsonic** [comment] 2020-04-28 20:17
@bsmartin-ep Awesome! Great foresight! 😉I think I can go ahead and accomplish it in this one, all good!

**Comment by jonwehausen** [comment] 2020-04-29 17:10
Hi @kelsonic ,

Thank you for getting the dataLayer in place so quickly. First thing we are noticing is duplicate event fires for search.

**Comment by bsmartin-ep** [comment] 2020-04-29 17:26
@kelsonic -

I also see a `edu-yellow-ribbon-search` event when I paginate.  We should only see this once with the search.

Thanks!

**Comment by jonwehausen** [comment] 2020-04-29 18:44
@kelsonic  Thanks for your updates here, here's what we're thinking for this tracking:
1. We would like (if possible) to limit the edu-yellow-ribbon-search event to ONLY actual searches and ONLY the yellow ribbon page. We are concerned running this multiple times within the pagination would cause inaccurate data on true search volume.
2. Please continue with the pagination events at a global level.
As part of this, we'll generate some test data and confirm we can get to the analysis of searches, pagination effect, etc. Does this make sense?

**Comment by jonwehausen** [comment] 2020-04-29 19:29
@joanneesteban @bsmartin-ep Confirmed with Stephanie launch date shifted to May 8th.

**Comment by kelsonic** [comment] 2020-04-29 19:46
Perfect! Thanks @jonwehausen and @bsmartin-ep! To confirm, this is what I plan to implement (let me know if this needs adjusting at all):

1. When a user clicks search, track API request event.
```js
    // Track the API request.
    recordEvent({
      event: 'edu-yellow-ribbon-search',
      'edu-yellow-ribbon-name': name || undefined,
      'edu-yellow-ribbon-state': state || undefined,
      'edu-yellow-ribbon-city': city || undefined,
      'edu-yellow-ribbon-contribution-amount': contributionAmount || undefined,
      'edu-yellow-ribbon-number-of-students': numberOfStudents || undefined,
      'edu-yellow-ribbon-number-of-search-results': response?.totalResults,
    });
```
2. When a user lands on the page, do **NOT** track api request event.
3. When a user paginates on the page, do **NOT** track api request event.
4. When a user clicks on the `next` page button, track pagination event.
```js
    // Track the API request.
    recordEvent({
      'event': 'nav-paginate-next',
      'paginate-page-number': page | undefined
    });
```
5. When a user clicks on the `previous` page button, track pagination event.
```js
    // Track the API request.
    recordEvent({
      'event': 'nav-paginate-previous',
      'paginate-page-number': page | undefined
    });
```
6. When a user clicks on a pagination `number` button, track pagination event.
```js
    // Track the API request.
    recordEvent({
      'event': 'nav-paginate-number',
      'paginate-page-number': page | undefined
    });
```

**Comment by bsmartin-ep** [comment] 2020-04-30 12:51
That looks correct to me @kelsonic.

**Comment by kelsonic** [comment] 2020-04-30 18:55
All PRs merged, on next deploy ticket is ready for validation! 🎉

**Comment by kelsonic** [comment] 2020-04-30 23:51
Whoops! Still need to send up a PR to fix these 2 points:
```
When a user lands on the page, do NOT track api request event.
When a user paginates on the page, do NOT track api request event.
```

**Comment by kelsonic** [comment] 2020-05-01 16:25
PR merged! https://github.com/department-of-veterans-affairs/vets-website/pull/12456

**Comment by bsmartin-ep** [comment] 2020-05-01 21:22
@kelsonic -

I believe the `nav-paginate-number` event is not firing.  Everything else looks good!

Description | Event + dataLayer
--- | ---
Initial Yellow Ribbon search on page | ![image](https://user-images.githubusercontent.com/62304138/80842311-41ffdd80-8bcf-11ea-90e6-8bda4066710d.png)
URL Query Param Preset with options | (none, as expected)
Paginate Next click | ![image](https://user-images.githubusercontent.com/62304138/80842389-6eb3f500-8bcf-11ea-8a80-3192b0981813.png)
Paginate Previous click | ![image](https://user-images.githubusercontent.com/62304138/80842435-8d19f080-8bcf-11ea-9a20-817abaef333c.png)
Paginate Number click | (missing.  Expected `nav-paginate-number` event)

cc @jonwehausen

**Comment by kelsonic** [comment] 2020-05-01 23:51
Just reproduced that on staging... 🤔bummer, the code is definitely there https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/Pagination/Pagination.jsx#L169

Sorry about that, I'll dig into this first thing Monday morning!

**Comment by kelsonic** [comment] 2020-05-01 23:51
Oh snap! I know what it is, let me send up a fix real quick haha

**Comment by kelsonic** [comment] 2020-05-04 14:29
PR is up to fix this, tested it locally and the event `nav-paginate-number` is triggering! 🎉https://github.com/department-of-veterans-affairs/vets-website/pull/12474 (check out #Screenshots in the PR description)

**Comment by kelsonic** [comment] 2020-05-05 15:08
Hey @bsmartin-ep and @jonwehausen, could you validate the fix works as desired on your side when you have a chance? 🙂

**Comment by bsmartin-ep** [comment] 2020-05-05 15:14
dataLayer stuff looks good to me, @kelsonic 

![image](https://user-images.githubusercontent.com/62304138/81082617-85a16280-8ec1-11ea-9f9e-6890de8e8c4c.png)

Ready for your QA and deployment, @jonwehausen 

Search:
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000266

Pagination:
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000278

**Comment by kelsonic** [comment] 2020-05-05 16:16
@stephorkandatx I believe we can close this one out 🙂

**Comment by jonwehausen** [comment] 2020-05-06 13:31
Reopening for tag management QA.

**Comment by jonwehausen** [comment] 2020-05-06 13:48
## Pagination QA

Description of Interaction | Screenshot | Test Status | Notes
------------ | ------------- | ------------- | -------------
**Clicked on a pagination number directly at the bottom** | ![image](https://user-images.githubusercontent.com/48527022/81183527-43d5f200-8f7d-11ea-9220-b0f8af2b4849.png) | ✔️ **PASSED** | Performed clicks on several other pagination numbers, screenshots include two examples, Also test on other pages such as GIBCT
**Clicked "< Prev" to move to the previous pagination number at the bottom** | ![image](https://user-images.githubusercontent.com/48527022/81184057-f0b06f00-8f7d-11ea-9bea-0bad278a226b.png) | ✔️ **PASSED** | Performed a few different clicks on "Prev" 
**Clicked "Next >" to move forward in the pagination number at the bottom** | ![image](https://user-images.githubusercontent.com/48527022/81184256-32d9b080-8f7e-11ea-9781-4d837fffec8d.png) | ✔️ **PASSED** | Performed a few different clicks on "Next" 

This functionality has in fact been published and deployed.

**Comment by stephorkandatx** [comment] 2020-05-06 14:21
Thanks @jonwehausen we will close this out

**Comment by jonwehausen** [comment] 2020-05-06 16:48
Reopening once more for phase 2 QA.

**Comment by jonwehausen** [comment] 2020-05-06 18:37
### QA Part 2 - Search Functionality (in progress)

Description of Interaction | Screenshot | Status | Notes
------------ | ------------- | ------------- | -------------
Searching with the following parameters: <br> - **School name**: birmingham <br> - **State or territory**: Alabama <br> - **City**: None given <br> - **Each checkbox clicked** | ![image](https://user-images.githubusercontent.com/48527022/81214020-3896bc80-8fa5-11ea-9c3c-5f3329f3b117.png) | ✔️ **PASSED** | Each colored arrow corresponds with its appropriate value
Searching with the following parameters: <br> - **School name**: birmingham <br> - **State or territory**: Armed Forces Pacific <br> - **City**: None given <br> - **Only funding for eligible students selected** |  ![image](https://user-images.githubusercontent.com/48527022/81214410-cd011f00-8fa5-11ea-950f-3fb751b5e32f.png) | ✔️ **PASSED**
Only searched with 'academy' keyword | ![image](https://user-images.githubusercontent.com/48527022/81214619-1e111300-8fa6-11ea-9970-a98521b254c0.png) | ✔️ **PASSED**
Same search as above but with "Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)" checked | ![image](https://user-images.githubusercontent.com/48527022/81214756-4d278480-8fa6-11ea-87c3-cda154f22acf.png) | ✔️ **PASSED**
Searching with the following parameters: <br> - **School Name**: academy <br> - **State or territory**: Maryland <br> - **City**: Waldorf <br> - **Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill) checked** | ![image](https://user-images.githubusercontent.com/48527022/81215113-d6d75200-8fa6-11ea-81e0-f44067095f82.png) | ✔️ **PASSED**

**Comment by jonwehausen** [comment] 2020-05-06 19:43
### Google Analytics Update
cc: @bsmartin-ep 

 - Added `city`, `state`, `contributionAmount`, `numberOfStudents` as parameters to both Non-Prod and Prod properties 'Exclude URL Query Parameters' in the following GA views: 
   - All VA.gov Website Data [Production]
   - Education Modernized View
![image](https://user-images.githubusercontent.com/48527022/81220824-f32bbc80-8faf-11ea-9c79-81149d850974.png)

- Also proposing adding `name` in addition to the ones listed above for "WBC - VA.gov Modernized Content" since this was not pre-configured as a search (where "strip query parameters out of URL is checked") or exclusion query parameter
![image](https://user-images.githubusercontent.com/48527022/81220723-c9729580-8faf-11ea-92dc-66adf7e26e3d.png)

@bsmartin-ep Let's discuss these tomorrow

**Comment by jonwehausen** [comment] 2020-05-07 14:04
Per conversation with @stephorkandatx over Slack, yellow ribbon has now been scheduled for Thursday 5/14.

**Comment by bsmartin-ep** [comment] 2020-05-11 00:21
@jonwehausen -

Tested this sequence:

```
?name=new
nav-paginate-next

Reset

?city=Austin&state=TX
?city=Houston&state=TX
nav-paginate-number - 2

Reset

?city=New+York&contributionAmount=unlimited&numberOfStudents=unlimited
?city=New+York&contributionAmount=unlimited&numberOfStudents=unlimited&name=College
?city=New+York&numberOfStudents=unlimited&name=College

Direct URL Entrance:
?state=MD
```
LGTM in GA:

#### Custom Dimensions

![image](https://user-images.githubusercontent.com/62304138/81514044-c6064380-92fa-11ea-892f-f7ecd901a105.png)

#### Search Terms (_name_ only) - Education / All

![image](https://user-images.githubusercontent.com/62304138/81514089-049bfe00-92fb-11ea-8bcb-2d2434d56d98.png)

I can test the same sequence with city, state _etc_ as site search parameters if you're interested in that.

> Also proposing adding name in addition to the ones listed above for "WBC - VA.gov Modernized Content" since this was not pre-configured as a search (where "strip query parameters out of URL is checked") or exclusion query parameter

Sounds good to me.

**Comment by stephorkandatx** [comment] 2020-05-11 18:05
@bsmartin-ep or @jonwehausen any blockers or critical issues coming up?

**Comment by jonwehausen** [comment] 2020-05-11 21:48
Hi @stephorkandatx , 

Thanks for reaching out! 

No, no blockers on our end, just wrapping up solutioning / testing.

**Comment by jonwehausen** [comment] 2020-05-15 14:01
@bsmartin-ep Ready for deployment at 3pm today.

**Comment by jonwehausen** [comment] 2020-05-15 20:01
### post launch 

![image](https://user-images.githubusercontent.com/48527022/82091419-4fd05b00-96c5-11ea-8326-60a50e8d8bf7.png)

**Closed** 2020-05-15 20:01 UTC
Labels: PR-open, analytics-insights, analytics-request, vsa-public-websites
