### ISSUE TITLE
[Due on 03/10] Redirect Request: Disability Legacy URLs based on rewriting work

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#6087] opened 2020-02-21 16:49 UTC
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information.

**This is a clean ticket based on work completed in ticket #2053** 

### Requestor team info
Public Websites

### Implementation date
**03/10****

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : Seven (7) business days after URLs are vetted

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
~www.vets.gov/disability-benefits/after-you-apply/date/  *This URL is already redirected, but the redirect needs to be updated to the newer page*~ | ~https://www.va.gov/disability/effective-date/~
https://www.benefits.va.gov/compensation/rates-index.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/resources-rates-read-compAndSMC.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/read_rates.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/resources_comp01.asp | https://www.va.gov/disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp02.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
https://www.benefits.va.gov/compensation/sb2018.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/compensation/claimexam.asp | https://www.va.gov/disability/va-claim-exam/
https://benefits.va.gov/compensation/add-dependents.asp | https://www.va.gov/disability/add-remove-dependent/
~www.vets.gov/disability-benefits/apply/dependents/form-686c-dependents *This URL is already redirected, but the redirect needs to be updated to the newer page*~  | ~https://www.va.gov/disability/add-remove-dependent/~
~www.vets.gov/disability-benefits/apply/dependents *This URL is already redirected, but the redirect needs to be updated to the newer page*~ | ~https://www.va.gov/disability/add-remove-dependent/~

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment] 2020-03-02 23:27
@lunascoop These redirects have been vetted and can be implemented when your team is ready.

**Comment by lunascoop** [comment] 2020-03-04 13:34
@ncksllvn Redirects have been scheduled for implementation on **03/10**.

**Comment by ncksllvn** [comment] 2020-03-04 15:46
PR is implemented - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6087 - but the Vets.gov redirects are server-side, so will need to be done in a separate PR.

I am wondering if we actually need to be concerned about Vets.gov redirects at all, since that domain was retired in November of 2018. If not, it would save me the trouble of coordinating with DevOps to review and deploy those redirects. Changing the Vets.gov redirects is kind of confusing.

**Comment by mnorthuis** [comment] 2020-03-04 22:25
@ncksllvn After reviewing the the 2 vets.gov URLs above in SEMrush, it looks as though they do not have any backlinks leading to them.  I will take a separate action step to potentially review our logs for users attempting to access these pages directly, but I suspect given there are no backlinks, that traffic will be minimal, and therefore I don't feel we need to update the existing redirect.   

I removed them from the redirect list above. This means that the existing redirect on those URLs should stay in place, and will just be 2 hops for now.  Once I review these and other vets.gov URLs, we will clean up the server side redirects for all vets.gov redirects. 

Thanks for checking on this!

**Comment by AkucherGCIO** [comment] 2020-03-10 20:44
@ncksllvn - Are we good to close this ticket ?

**Comment by lunascoop** [comment] 2020-03-10 20:50
@kelsonic @AkucherGCIO I have validated the redirects and all but two are working. @kelsonic they are: 

https://www.benefits.va.gov/compensation/claimexam.asp | https://www.va.gov/disability/va-claim-exam/
-- | --
https://benefits.va.gov/compensation/add-dependents.asp | https://www.va.gov/disability/add-remove-dependent/

**Comment by kelsonic** [comment] 2020-03-11 03:19
Oops sorry just saw this! So I can confirm that these 2 redirects were merged in and they do look correct to me when I compare them to the ones you posted.

```json
  {
    "domain": "www.benefits.va.gov",
    "src": "/compensation/claimexam.asp",
    "dest": "/disability/va-claim-exam/"
  },
  {
    "domain": "www.benefits.va.gov",
    "src": "/compensation/add-dependents.asp",
    "dest": "/disability/add-remove-dependent/"
  }
```

Therefore, I think something funky is going on with those 2 redirects. Do we need to add them to the devops repo instead perhaps @ncksllvn?

**Comment by ncksllvn** [comment] 2020-03-11 13:51
Uh oh, yeah, those pages do not include our JavaScript file that executes the redirect. This means we do not have the ability to redirect those pages. They must have been built using a different template of some sort.

So...if we need to redirect those, we need to get in touch with some at benefits.va.gov. We can either have them include our JavaScript file (a few lines into the HTML code) into their page, or ask them to set up the redirect themselves.

**Comment by AkucherGCIO** [comment] 2020-03-11 17:34
03/11/20 Sprint 17 Planning
@jenniferlee-dsva will reach out to Sandy and Josh from the benefits.va.gov to get their feedback.

**Comment by AkucherGCIO** [comment] 2020-03-11 17:37
03/11/20 Sprint 17 Planning
@AkucherGCIO - Create new ticket for the new Url's that are not re-directing and another ticket for updating the rate tables.

**Comment by jenniferlee-dsva** [comment] 2020-04-17 19:44
Hi @lunascoop @kelsonic  - Was asked to look at this ticket about 2 urls:

https://www.benefits.va.gov/compensation/claimexam.asp 
https://benefits.va.gov/compensation/add-dependents.asp

1/ Are these ready to be redirected (or re-redirected) - in terms of parity/legacy? 
2/ What was the original issue why these could not redirected? 

It looks like from way back thread, I needed to have communicated something to Sandy. However, I confess I either forgot or this got sidetracked with the several UN-redirects that followed.

fysa @mnorthuis @DanielleSoCompany @johnhashva

**Comment by jenniferlee-dsva** [comment] 2020-04-17 19:51
TB'd with @mnorthuis  - ^ 2 urls never got redirected bc of those pages not having our injection code in their header. 

I'll reach out to Sandy Tadeo to implement the redirects and communicate to the stakeholders. 

To confirm the urls are being redirect to: 
https://www.benefits.va.gov/compensation/claimexam.asp | https://www.va.gov/disability/va-claim-exam/
-- | --
https://benefits.va.gov/compensation/add-dependents.asp | https://www.va.gov/disability/add-remove-dependent/

I can't find another ticket tracking these separately, so will comment back here when that has been requested.

**Comment by lunascoop** [comment] 2020-04-17 19:52
Hi @jenniferlee-dsva, they were/are ready to be redirected, but there was an issue with the template that wouldn't allow @kelsonic  to implement the redirects. I think we determined we would need there assistance the redirect.
 
<img width="790" alt="Screen Shot 2020-04-17 at 3 48 28 PM" src="https://user-images.githubusercontent.com/42546515/79608521-2a9afd80-80c3-11ea-8a88-000e203d8aae.png">

**Comment by jenniferlee-dsva** [comment] 2020-04-17 19:59
Question for FE engineering - if THEY are implementing the redirect from their side, do they even need the legacy pages to stay up? Can they just kill those 2 pages and implement the redirects to our new pages, since they can do it server side from their end? @ncksllvn or @kelsonic

**Comment by stephorkandatx** [comment] 2020-04-21 13:59
@ncksllvn and @kelsonic from the question above, do we need to leave the legacy pages?

**Comment by jenniferlee-dsva** [comment] 2020-04-22 12:45
I believe they can delete those 2 legacy pages AND implement a permanent 301 redirect. I just want to confirm with engineering before I reach out to Sandy et al in VBA. @stephorkandatx @kelsonic @ncksllvn (fysa @mnorthuis ).

**Comment by ncksllvn** [comment] 2020-04-22 20:41
Since those pages are non-www, we can't server-side redirect them because requests don't pass through our infrastructure. 

In these cases, we would do a client-side redirect via JS. However, those two pages must be using a non-standard TeamSite template, because our JS code isn't included on their pages. I think we need to ask a TeamSite author/admin how to do the redirect

**Comment by mnorthuis** [comment] 2020-04-29 17:46
Email sent to stakeholders to request redirect for 2 remaining legacy pages be done through their technical teams.   All other redirects on this issue are complete.  @jenniferlee-dsva can we close this issue out since there is no other action from our teams needed?

![image](https://user-images.githubusercontent.com/20994159/80628752-7761cb00-8a17-11ea-84de-483c7f198631.png)

**Comment by stephorkandatx** [comment] 2020-05-04 22:46
Closing this per comment above

**Closed by stephorkandatx** 2020-05-04 22:46 UTC
Labels: PR-open, Website redirects, content, content-ia-team, ia, vsa-public-websites
