### ISSUE TITLE
Incorrect heading level for spotlight section on health services page

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64838] opened 2023-09-04 13:16 UTC

**Comment by CherylEvans** [comment] 2023-09-04 14:31
This ticket was recreated from VAMC Facility Accessibility Audit EPIC 12060 - department-of-veterans-affairs/va.gov-cms#12060VAMC Facility Accessibility Audit Ticket # [12080](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-cms/12080)

**Comment by laflannery** [comment] 2023-09-05 12:26
Wouldn't this be a duplicate of the issue already created in the team repo here? [#64420](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64420)

**Comment by CherylEvans** [comment] 2023-09-05 12:40
@laflannery This ticket was recreated in error. Reference Ticket [64420](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/gh/department-of-veterans-affairs/va.gov-team/64420) as the correct ticket. Closing as a duplicate of 64420.

**Closed** 2023-09-05 12:44 UTC
Labels: accessibility, a11y-defect-2, collaboration-cycle, collab-cycle-feedback, CCIssue02.04
