### ISSUE TITLE
Staging Review finding: Error state on `representative-contact` page without more instructions appears to be end of form

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98995] opened 2024-12-12 16:40 UTC
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Accredited Representation Management
**Product:** Appoint a Representative MVP
**Feature:** Appoint a Representative + Representative Status Widget

## Findings details
**VA.gov Experience Standard - issue:** [User has enough information to complete a task.](https://design.va.gov/about/experience-standards/#user-has-enough-information-to-complete-a-task)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The error message `Contact the accredited representative` on the `representative-contact` page encourages users to contact their representative. But there is nothing else on this page besides the `Continue` button to indicate that it is okay to proceed through the form. It might not be clear to Veterans that if they have contacted or plan to contact their representative, they may proceed through the form. Instead, it might look like they cannot go any further.

<details><summary>Link, screenshot or steps to recreate</summary>

![no content indicating user may proceed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/71535-erin-error-continue.png?raw=true)

</details>

## Recommended action

Add content to tell users that once they have notified their rep they may proceed with the form.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by oddball-lindsay** [comment] 2024-12-12 20:30
@erinrwhite we have tested this experience multiple times and there have been no user challenges around this step. Here are some relevant findings: 
1. First test: [2024-01-ARM-appointarep-usertest](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest)
   1. See the "Contact the Representative" section under [2024-01-ARM-appointarep-usertest](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest)
   2. "Half of participants assumed they would have contacted the representative before this point and would not have started this process to begin with if they hadn’t. One participant mentioned they’d pause and call the representative at this point. Most interpreted the replace and contact pages as confirmations that no steps were missed. Some commented that if that were the case they’d expect them to be more in their face through color or modals."
   3. This is what led to us adding in the alert design for the "Contact the Representative" language.
2. Later test: [2024-06-ARM-appointarep-digitalsubmit-usertest](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-06-ARM-appointarep-digitalsubmit-usertest)
   1. See the "Step 1 of 5 Accredited representative information: Contact the accredited representative" section under [Task 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-06-ARM-appointarep-digitalsubmit-usertest/research-findings.md#task-2-complete-appoint-a-representative-21-22-form-and-provide-feedback-on-the-experience)
   2. "All participants understood the task and next steps."
   3. This verified that our enhancement from the last test (adding in the alert design) was perceived as intended by users.
3. Even later test with representatives: [2024-08-ARM-appointarep-crossaccreditedVSOR-usertest](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-08-ARM-appointarep-crossaccreditedVSOR-usertest)
   1. See the "Contact the accredited representative" section under [Appoint a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-08-ARM-appointarep-crossaccreditedVSOR-usertest/research-findings.md#appoint-a-representative)
   2. "All participants understood the task and next steps."

cc @jfinnerty13 in case she has anything to add.

Given the research, I would argue that this step is not confusing for users and this should not be launch-blocking. Can you please confirm with Mikki if we can remove this as a launch-blocking item?

And if it's not launch blocking, could you or @jfinnerty13 help remove the label (and possibly close this ticket) since I will be out starting tomorrow? 🙏

**Comment by erinrwhite** [comment] 2024-12-12 20:32
@oddball-lindsay Thank you for the in-depth research findings here! This is good enough for me to remove the launch-blocking label. I'll go ahead and do that. Thanks for doing this extra work.

**Comment by jfinnerty13** [comment] 2024-12-12 21:16
Nothing to add thank you @oddball-lindsay !

**Closed** 2024-12-12 21:20 UTC
Labels: ia, collab-cycle-feedback, Staging, CC-Dashboard, accredited-representation-management-team, appoint-a-representative, representative-status-widget, Comprehension, exp-std-task-completion, context-flow
