### ISSUE TITLE
[Bug] Check-in: Reloading check-in page returns to initial-landing page

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#28100] opened 2021-07-30 00:15 UTC
## What happened?
On Staging Check-in experience (exclusively mobile), after reloading the check-in page [**Your appointment**, w/ check-in button], browser returned to initial-landing [Check in at VA] page.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]

## Steps to Reproduce
[See [Test Data Setup doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-data-setup.md) for detailed steps]
- Create an **appointment** <30 min. in the future.  
- Send "**check in**" SMS msg.
- In SMS-reply, tap **check-in** link.
- On Staging **Check in at VA** page, tap **No**.
- On **Your appointment** page, after initial page-load, and _without_ tapping check-in button, **Reload** the page.
- Observe that browser returns to initial **Check in at VA** page.  In order to return to check-in page, you have to re-tap **No**.

## Desired behavior
- [ ] Reloading **Your appointment** check-in page should reload this same page, NOT initial **Check in at VA**.

## Acceptance Criteria
[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jparker0425** [comment] 2021-08-02 17:38
@mdewey is this something you could take a look at? Sounds like a refresh of the actual check-in screen redirects to a different URL.

**Comment by mdewey** [comment] 2021-08-02 17:48
@jparker0425  and @tlei123  That is expected behavior. UX and Engineering had a discussion around that issues. I will find the original thread, but the gist is that when a user re-enters the workflow mid-way (via page refresh or other means), they should be directed to restart the workflow.

**Comment by jparker0425** [comment] 2021-08-03 14:33
Thanks @mdewey, good to know.  @tlei123 after discussing with @mdewey about the decision points, the main reason for the redirect back to the landing page is due to validation points. That main landing page is the single point of validation, so if there is a refresh (or perhaps the page does not get closed out initially and opened back up later) the page load would need to go back to the point of validation. 

Let me know please if you have any questions. If not, I will close this ticket out.

**Comment by tlei123** [comment] 2021-08-03 19:19
@mdewey , do you want to fix your [Test Case I](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-cases.md#test-case-i-edge-case---user-refreshes-the-app-before-finishing-the-check-in-process) or should I?

![Screen Shot 2021-08-03 at 11 20 12 AM](https://user-images.githubusercontent.com/587583/128073239-b1e97167-bd7e-4c2e-8f9f-8d9e5b470943.png)

**Comment by mdewey** [comment] 2021-08-04 19:56
Good Catch @tlei123  I will update the testing doc 👍

**Closed** 2021-08-05 00:54 UTC
Labels: HCE-Checkin, bug, frontend, vsa-healthcare-exp, vsa-qa-false-positive
