### ISSUE TITLE
CT: Improve error messaging when there is a timeout

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6662] opened 2020-03-09 00:08 UTC
The GI Bill Comparison Tool currently handles an outage or timeout of the GIDS service by endlessly spinning, so this story seeks to provide those using the CT with an error message letting them know what they need to do. 

## Assumptions
1. The search results and profile page timeouts include both the standard pages and the VET TEC pages.
2. This work will be completed behind a prod flag so that upon merge it is only available on staging. 
 

## Acceptance Criteria
1. When the GI Bill Comparison Tool experiences an outage or timeout of the GIDS service, the following alert is displayed: 

**We’ve run into a problem**
We’re sorry. Something went wrong on our end. Please try again or check back soon.

{ button on all pages except GIBCT landing page }

2. This will be implemented on for load of the following pages:
a.  Comparsion Tool Landing page
b.  Comparison Tool Search Results page
c. Profile Page. 

## Supporting Artifacts
1. https://design.va.gov/patterns/messaging-dictionary#access-messaging
2. Screenshot of current infinite spinner on Landing Page: 
![landing.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/1ccb4995-a447-4747-99bf-0961cf435832)
3. Screenshot of current infinite spinner on Search Results: 
![search.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/5c1eab07-e72a-46b0-91c9-ae85dbace95f)
4. Screenshot of current infinite spinner on Profile Page:
 ![profilepage.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/c144f7d2-4c46-4193-94bb-d58cd9c1bfe8)
5.  Screenshot of current infinite spinner on Vettec Search Results: 
![vettecsearch.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/2c2cfbe1-6388-4f0e-a468-32a08f18cfcb)

**Comment by amyknox** [comment] 2020-03-09 13:44
Confirmed with dev team that referesh the page will (should) fix the issue.

**Comment by amyknox** [comment] 2020-03-10 13:53
Per recent DEPO Design conversations, we should move away from alert box and display content on the page, in context.  Example from GI Bill Status Checker... ![image (3).png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/e9a42f20-73f1-490d-9f6f-cf7b013d30ee)

**Comment by WillMcCormack** [comment] 2020-03-10 16:40
We can have a FE dev get started on it and then have @ccruzgra review & provide fine-tuning on styles when she's back. Going to let someone from the team pick this one up.

**Comment by amyknox** [comment] 2020-03-10 18:48
Per @ksantiagomorgan6 - error message can't be  "We’re sorry. Something went wrong on our end. **Please refresh this page** or try again later." because refreshing the page would leave the same error message.  Instead, we're adding a button to return user to GIBCT landing page.  Viola.

**Comment by amyknox** [comment] 2020-03-10 18:55
@ksantiagomorgan6 Updated error message: 

We’re sorry. Something went wrong on our end. Please try again or check back soon.

**Comment by ksantiagomorgan6** [comment] 2020-03-11 11:48
Pull request:

https://github.com/department-of-veterans-affairs/vets-website/pull/11867

**Comment by sonntag-adam** [comment] 2020-03-12 17:46
Moving back to in progress as research on this story continues to develop.

**Comment by ccruzgra** [comment] 2020-03-12 19:10
@sonntag-adam Do you have a screenshot of what's been currently implemented?

**Comment by ccruzgra** [comment] 2020-03-12 19:12
@sonntag-adam Do you have a screenshot of the original page showing the spinner when GIDS is down?

**Comment by sonntag-adam** [comment] 2020-03-20 16:25
Landing
![Screen Shot 2020-03-20 at 11.27.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cd2afffd-ab1c-4a83-9057-efde42e11816)
##
Results
![Screen Shot 2020-03-20 at 11.53.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/eee56e40-4215-4c7b-9e58-fae8ed012e62)
##
Profile
![Screen Shot 2020-03-20 at 12.01.54 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/90dc9ef3-f444-46eb-904b-9d7fe48bfea3)
##
vettec search
![Screen Shot 2020-03-20 at 12.19.43 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6b1a004d-df15-4327-8152-263c0518ef7a)
##
vettec profile
![Screen Shot 2020-03-20 at 12.22.53 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0e354a4c-7cab-4378-bcc3-6a2eb4809c1a)

**Comment by sonntag-adam** [comment] 2020-03-20 16:41
Pages continue to load with infinite spinner on productions build

**Comment by sonntag-adam** [comment] 2020-03-20 17:12
Testing passes 
https://dsvavsp.testrail.io/index.php?/runs/view/219&group_by=cases:section_id&group_order=asc

**Comment by ccruzgra** [comment] 2020-03-20 19:18
@ksantiagomorgan6 demo'ed to UX the new error functionality and different scenarios on GIBCT, both for standard searches/profile pages and for VET TEC. He explained that they are not including the blue button for returning to the GIBCT landing page in search results and profile pages because you’d see the same error message on the landing page, as well, which renders the button as redundant. UX approved the updates, but suggested tweaking the error message to:

**We've run into a problem.**
We're sorry. Something went wrong on our end. Please refresh this page or check back soon."

The copy adjustment provides users with a suggested action to follow since the blue button to take them to the landing page is not provided.

**Comment by sonntag-adam** [comment] 2020-03-23 18:55
In staging, closing story

**Closed by sonntag-adam** 2020-03-23 18:55 UTC
Labels: bah-comparisontool, bah-sprint-43, functional
