### ISSUE TITLE
Analytics Implementation or QA Support for Higher Level Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3825] opened 2019-11-28 01:24 UTC
# Analytics Implementation 

## Description
- This request is for Google Analytics implementation.

- Who is this request for?

    - Andrea Schneider (VA) and Yana Roy (GovernmentCIO)

    
- What team/project is this work for?
    
    - Benefits and Memorials: Higher Level Review
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [**Invision App**](https://vsateams.invisionapp.com/share/PMVHSE4DRN6#/400541600_Signed_In-File_A_Higher_Level_Review)
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here] TBD

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required

    - [Provide users here]

- Test Users to replicate the event

    - [Provide test users here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] Ensure GTM event uses the following syntax: 
   > Event Category: Interactions
   > Event Action: Forms - <change_me>
   > Event Label: {{event}}
- [ ] Push event for start of higher level review form ```-start-form```
- [ ] Push event for ALL submissions of higher level review form on successful submission ```-submission```
- [ ] Push event for completion of higher level review form on successful submission ```--submission-successful```
- [ ] TENTATIVE: Push DL variable `true` of `false` if notes section was used during form
- [ ] TENTATIVE: Push DL variable `true` of `false` for in-form questions, example: 'would you like the same office...'

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment] 2019-12-12 21:17
Hi @YanaRoy Shifting this to our Analytics-Insights Ready column. Can we sync up during the next 1.5 weeks on requirements? 

Including @jonwehausen for visibility

**Comment by joanneesteban** [comment] 2020-01-29 15:38
@jonwehausen to follow up with B&M engineers on Slack.

**Comment by jonwehausen** [comment] 2020-02-03 20:39
Updated Acceptance Criteria 2/3 -- more requirements to follow. 

cc: @joanneesteban @nedierecel

**Comment by jonwehausen** [comment] 2020-02-03 20:51
Kevin and team to meet with AMO again sometime next week.

**Comment by joanneesteban** [comment] 2020-02-10 16:59
@kevinstachura - hi there! Checking in to see B&M's update for the Google Tag Manager requirements for Higher Level Review.

CC: @luke-gcio

**Comment by luke-gcio** [comment] 2020-02-10 17:29
Hi @joanneesteban , we have some notes from the meeting and we will have a tagup with AMO before we submit the final info. 

**Notes from analytics team meeting (HLR):**
- Determined that view changes (route or URL changes) will be tracked - helps to understand user flow
- Tentatively plan to track yes/no for same office, will track users going from submit page --> track status
- Before determining exactly what we want to track and at what level, BaM1 needs to get in contact with AMO 
   - What screens must be kept from a legal perspective (and if we need to keep, what state changes we want to track)
   - What details have value for us and AMO collectively 

**Action Items**
- Set up meeting with AMO to coordinate with them on the above items
- Design changes - consider pages being condensed (e.g. opt out living within contested issues view)
- Meet or coordinate with Analytics team to communicate what exactly we want tracked after results of AMO coordination

**Comment by jonwehausen** [comment] 2020-02-25 13:45
Hi @luke-gcio and @kevinstachura ,

Any further updates on this request? Thanks in advance. 

Best,
Jon Wehausen

**Comment by kevinstachura** [comment] 2020-02-25 21:21
Hi @jonwehausen ,

We have not been able to coordinate with AMO on this yet - however we understand that this needs to move forward. I think we're good if we can monitor these metrics/event tracking:

- How user flows through the HLR application
- Where user exits in the HLR process (where they might drop off from the process)
- Submit page - where user goes next from the submission page (next page they navigate to)
- Same office - whether user clicks yes or no
- informal conference - whether user selects 'no', 'yes, call me', or 'yes, call my representative'

I think this covers most of the forks in the road or paths that ourselves or AMO might be interested in monitoring. There is another thing re: legacy appeals that we may want to track in the future but it has yet to be determined so I think we're good to move forward without for now (not a showstopper).

Please let us know if you have any questions or if any of these things are not possible to grab metrics on. Thanks Jon and team!

cc: @luke-gcio

**Comment by jonwehausen** [comment] 2020-03-27 12:17
@kevinstachura and @luke-gcio Thanks for your patience here! Here is a markdown of what we propose for dataLayer events for the new HLR form based on what we saw above. This includes our standard form tracking framework as well as the additional questions within the form you're wishing to track (same office & informal conference). 

Let us know if these make sense and if we need to make any tweaks / additions. 

### Datalayer Events

Description of Interaction | Screenshot | DataLayer Event / Variable
------------ | ------------ | ------------- | 
When the veteran starts the form | ![image](https://user-images.githubusercontent.com/48527022/77752973-f621ad80-6ffe-11ea-9394-03a75da0278a.png) | ```dataLayer.push({'event': 'decision-reviews-va20-0996-start-form'});```
**In conjunction with ```-submission```, ```-submission-successful```, and ```-submission-failure``` event push**, record the vets selection to "Would you like the same office that issued your prior decisions to conduct the review?" | ![image](https://user-images.githubusercontent.com/48527022/77753567-274ead80-7000-11ea-8dcc-eeea5789ae23.png) | ```decision-reviews-sameOffice: 'yes' //or 'no``` | 
**In conjunction with ```-submission```, ```-submission-successful```, and ```-submission-failure``` event push**, record the vets selection to "Would you like to request an informal conference?" | ![image](https://user-images.githubusercontent.com/48527022/77754114-0e92c780-7001-11ea-96e4-fb95b9fca289.png) | ```decision-reviews-informalConf: 'yes' //or 'no', or 'yes-with-rep'```|
Form completion | ![image](https://user-images.githubusercontent.com/48527022/77754353-94167780-7001-11ea-94eb-3bc0f2064785.png) | ```dataLayer.push({'event': 'decision-reviews-va20-0996-submission});```

### Form Submission Events: 
Form Interaction | DataLayer Event / Variable
------------ |  ------------- | 
ALL submissions (failure or not) | ```dataLayer.push({'event': 'decision-reviews-va20-0996-submission'});```
ALL SUCCESSFUL submissions | ```dataLayer.push({'event': 'decision-reviews-va20-0996-submission-successful'});```
ALL FAILURE submissions | ```dataLayer.push({'event': 'decision-reviews-va20-0996-submission-failure'});```

### Example of full datalayer push on submission successful
```javascript
dataLayer.push({
  'event': 'decision-reviews-va20-0996-submission-successful',
  'decision-reviews-sameOffice': 'yes', //or 'no'
  'decision-reviews-informalConf': 'yes' //or 'no', or 'yes-with-rep'
})
```

**Comment by jonwehausen** [comment] 2020-04-29 12:55
Hi @kevinstachura and @luke-gcio , wanted to see if you guys had an update here? Thanks in advance

**Comment by kevinstachura** [comment] 2020-04-29 13:59
Hi @jonwehausen - thanks so much for your patience! We have ironed out the final details on the HLR flow. From your latest message above, the only thing that has changed is same office. The wording has essentially been flipped to say 'different office', It has now become a checkbox as opposed to a radio and now lives on the contested issues screen. This is how it will look:

<img width="639" alt="Screen Shot 2020-04-29 at 9 48 11 AM" src="https://user-images.githubusercontent.com/54544300/80603775-dcf58d80-89fe-11ea-827c-765b4ac33795.png">

So we obviously still want that metric (we want to know if the user checks 'I want a different office' - if it has a 'true' value) but I believe that's the only change we have! @luke-gcio let me know if I've missed anything. Also Luke, do we have a rough estimate we can give Jon about when we anticipate a production launch of this product? I'd say about a month, but you would know better than I.

@jonwehausen you can assume this is otherwise good to go. Thank you again!

**Comment by jonwehausen** [comment] 2020-05-11 21:54
Hi @kevinstachura and @luke-gcio ,

Thanks for this update and your patience in our response! I've updated the dataLayer requirements to reflect the change in verbiage to `differentOffice`. 

Do we have an idea of when launch might be? If coming up here in a couple weeks we may want to try to move forward with getting an FE on implementing the DL requirements. 

Thanks so much and let us know if you have any questions.

**Comment by kevinstachura** [comment] 2020-05-12 16:13
Thanks so much @jonwehausen! Currently chatting with Luke about launch expectations so I can get you a better answer on this. 👍

**Comment by jonwehausen** [comment] 2020-05-19 19:37
Hi @kevinstachura ,

Would you happen to have an update to provide here? 

Thanks in advance.

**Comment by luke-gcio** [comment] 2020-05-20 16:55
Hi Jon - we are back working this and expect some UAT testing some time in sprint 23 and launch mid to end of June.

**Comment by joanneesteban** [comment] 2020-06-24 16:27
@luke-gcio - do you have an update on the launch for this? Thanks!

**Comment by Mottie** [comment] 2020-07-06 21:37
We had some higher priority tasks push the HLR launch date. I don't think we have a specific date set right now, but hopefully it'll be soon.

**Comment by Mottie** [comment] 2020-07-08 16:04
The HLR analytics code has been merged into master. As I mentioned before, we don't have a definite launch date set, but I hope it'll be soon.

I'm not sure if I should I close this ticket?

**Comment by jonwehausen** [comment] 2020-07-08 16:20
Hi @Mottie , 

Very much appreciated! We will leave this ticket open as we work towards getting QA done here. We will be in touch with our QA findings.

**Comment by jonwehausen** [comment] 2020-09-02 17:54
Spoke with @Mottie this afternoon and confirmed HLR is still working through functional fixes...QA is blocked until these issues are sorted out. 

Test user for use when ready: vetsgov+test233@id.me / Password1234!

**Comment by joanneesteban** [comment] 2020-09-22 17:49
@Mottie @luke-gcio Let us know if you have any updates. We're moving this issue to the backlog until then!

**Comment by joanneesteban** [comment] 2020-11-04 19:28
@luke-gcio - checking in here again; let us know if you have an update on rollout and we can reprioritize this!

**Comment by jonwehausen** [comment] 2020-11-16 17:52
Test users link provided by Luke: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx

**Comment by jonwehausen** [comment] 2020-11-16 18:57
## QA Testing of Form Events: 
- @Mottie Thank you very much for your work here, please find the test results for form 0996 below
- Apologies in advance recognize some of the items that need correction that were outlined in the original spec were inaccurate from the start and are from an old spec, and that was my mishap -- you can find documentation around our form events [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md)m, these are baked into the forms library platform code

Description of Event | Screenshot of Data Layer | Test Status
------------ | ------------- | ------------- 
Click to start form ![image](https://user-images.githubusercontent.com/48527022/99291561-05fc3500-280e-11eb-9030-fa289a370324.png) | ![image](https://user-images.githubusercontent.com/48527022/99291643-22986d00-280e-11eb-842a-ecb744348562.png) | ✔️ **PASS**
Form loaded | ![image](https://user-images.githubusercontent.com/48527022/99291886-7b680580-280e-11eb-99be-ba98b011fcdd.png) | ✔️ **PASS**
Form saved ![image](https://user-images.githubusercontent.com/48527022/99292520-4f994f80-280f-11eb-9b35-036721ed3031.png) | ![image](https://user-images.githubusercontent.com/48527022/99292542-5758f400-280f-11eb-85c5-6bd8b18e76dd.png) | ✔️ **PASS**
Form submission (_intended to fire once for every successful and failed submission_) ![image](https://user-images.githubusercontent.com/48527022/99293032-11506000-2810-11eb-90bc-76e024f53ff4.png) | ![image](https://user-images.githubusercontent.com/48527022/99293077-1e6d4f00-2810-11eb-8e63-7656f075bedb.png) | ⚠️ **DOES NOT PASS** <br>**_there is currently duplicate `--submission` events firing_**
Successful submission | ![image](https://user-images.githubusercontent.com/48527022/99293360-8d4aa800-2810-11eb-8ee9-399ecb435972.png) | ✔️ **PASS**
Failed submission via internet connection loss ![image](https://user-images.githubusercontent.com/48527022/99294357-f4b52780-2811-11eb-9fa4-eeaaab1dfffe.png) | ![image](https://user-images.githubusercontent.com/48527022/99294447-11515f80-2812-11eb-9bc8-b0dcbf39090e.png) | ✔️ **PASS** single `-failed-client` event fired
Failed submission | ![image](https://user-images.githubusercontent.com/48527022/99294626-4e1d5680-2812-11eb-83f8-1999e2fb00df.png) | ⚠️ **DOES NOT PASS** <br>**need to replaced `--submission-failure` with `--submission-failed`



Let us know any questions you have on the above @Mottie , in addition, please find our standardized wizard tracking specification [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13060#issuecomment-712852345) that can be implemented to supply analytics on the how to wizard of 0996. 

### Next Steps: 
- [ ] @bsmartin-ep could you modify our global form tag to include `decision-reviews` as a prefix to fire our standard form events
- [ ] @bmcgrady-ep could you setup the goal funnel for this new form with the following page paths: 
```
Step 1: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
Step 2: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/veteran-information
Step 3: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/contact-information
Step 4: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/contested-issues
Step 5: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/request-informal-conference
Step 6: va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/review-and-submit
```
- [ ] Revisit QA following data layer adjustments

**Comment by Mottie** [comment] 2020-11-18 20:14
We haven't addressed this yet. Should I rename the event data names from "different office" to "same office"?

![Screen Shot 2020-11-18 at 2 11 29 PM](https://user-images.githubusercontent.com/136959/99582850-48597980-29a8-11eb-9169-01e708bc5420.png)

**Comment by bsmartin-ep** [comment] 2020-11-21 14:41
@jonwehausen -

We have two GTM workspaces for this:

One for the How To Wizards:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000387

And one for the product specific changes. 

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000390

You wanted these extra params in CDs, correct?

![image](https://user-images.githubusercontent.com/62304138/99879857-90adad00-2bdd-11eb-8117-d2ad7da00d8f.png)

(pardon my placeholder CD indices)

**Comment by jonwehausen** [comment] 2020-11-24 18:15
Hi @Mottie , 

Thank you for your patience here, to follow-up on a few items: 
- [Here ](https://tagassistant.google.com/#source=TAG_MANAGER&id=GTM-WFJWBD&gtm_auth=inC4EKQce9vlWpRVcowiyQ&gtm_preview=env-661&url=https%3A%2F%2Fstaging.va.gov) you can utilize a Google Tag Manager preview link to see what we see within the data layer 
- Yes, the data layer variable for `decision-reviews-differentOffice` should be changed, to ensure verbiage changes don't restrict us here, can we add a bit more specificity to be `'decision-reviews-same-office-to-review'`
- Lastly, I just wanted to re-surface our generic [How To Wizard data layer spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md), this is intended to be flexible enough to support any current and future wizards, we would like to request this be implemented as well

Thank you very much again for your work here. 

cc: @luke-gcio @joanneesteban

**Comment by jonwehausen** [comment] 2020-11-24 18:16
Moving back to Stand By on project board pending new data layer changes -- will shift back to QA following confirmation changes have merged to staging.

**Comment by Mottie** [comment] 2020-11-24 20:36
Thanks @jonwehausen! I'll get that same office change in today, but I'll have to work on the wizard events next week since I have to take care of a higher-priority ticket.

**Comment by bmcgrady-ep** [comment] 2020-12-07 21:31
Hi @Mottie - Jon is OOO this week, but I am following up to see the status on this and if a launch date has been decided for this. 

If there is anything on the analytics end that needs to be done, let us know. Thanks!

**Comment by Mottie** [comment] 2020-12-07 21:44
We're holding off for the Central Mail endpoint change, which probably won't be done until next week (Dec 14th). We'll discuss what happens then, but maybe we won't launch a week before the holiday code freeze...

**Comment by joanneesteban** [comment] 2020-12-16 17:24
Thanks for the update, @Mottie ! Please let us know when you're ready, and we can prioritize this.

**Comment by Mottie** [comment] 2020-12-16 17:33
Launch of HLR has been delayed until Jan 14th

**Comment by jonwehausen** [comment] 2020-12-30 14:40
## QA Testing of How To Wizard Data Layer 

### Context
- Testing was executed according to our latest [how to wizard data layer specification](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md) 


| Description / Screenshot of Interaction | Data Layer | Test Status
| -- | -- | -- |
Click on radio button toggle ![image](https://user-images.githubusercontent.com/48527022/103356505-062f5780-4a7f-11eb-8fef-e4b37996035a.png) | ![image](https://user-images.githubusercontent.com/48527022/103356523-134c4680-4a7f-11eb-9db5-d71a778d870f.png) | ✔️ **PASS**
Alert displayed following radio button toggle ![image](https://user-images.githubusercontent.com/48527022/103356646-54445b00-4a7f-11eb-8888-0a9fae4545a8.png) | ![image](https://user-images.githubusercontent.com/48527022/103356659-5c03ff80-4a7f-11eb-96d4-43e5cb729712.png) | ✔️ **PASS**
Click on link inside of alert ![image](https://user-images.githubusercontent.com/48527022/103356786-a5ece580-4a7f-11eb-93fb-12ad8d35e77d.png) | ![image](https://user-images.githubusercontent.com/48527022/103356868-dc2a6500-4a7f-11eb-94b1-a86c8733671d.png) | ✔️ **PASS**
CTA Displays to start form ![image](https://user-images.githubusercontent.com/48527022/103357163-80aca700-4a80-11eb-98c0-798e92b37c45.png) | ![image](https://user-images.githubusercontent.com/48527022/103357191-928e4a00-4a80-11eb-81e3-fd5c69a0d93c.png) | ✔️ **PASS** 
CTA click to begin form | ![image](https://user-images.githubusercontent.com/48527022/103357269-c2d5e880-4a80-11eb-8bf7-483fcc07ac00.png) | ✔️ **PASS**
Click on go back and answer questions again ![image](https://user-images.githubusercontent.com/48527022/103357294-d4b78b80-4a80-11eb-86b3-1e5c68ebd319.png) | ![image](https://user-images.githubusercontent.com/48527022/103357336-e9941f00-4a80-11eb-862b-776e77c2d153.png) | ✔️ **PASS**

## Outstanding Question
- @luke-gcio or @Mottie If there is an option to skip the form? Did not run into this in testing?
![image](https://user-images.githubusercontent.com/48527022/103358127-de41f300-4a82-11eb-8f89-a0b2e300ebed.png)

**Comment by jonwehausen** [comment] 2020-12-30 14:46
### Answer
- Per @Mottie 
> We don't allow skipping the wizard because we need the user to answer the type of HLR so that we can make an API call to get type-specific contestable issues

**Comment by jonwehausen** [comment] 2020-12-30 15:15
### How To Wizard GTM QA Testing

| Description / Screenshot of Interaction | GTM Tag Screenshot | Test Status
| -- | -- | -- |
Radio button toggle click ![image](https://user-images.githubusercontent.com/48527022/103359038-15b19f00-4a85-11eb-9480-1e3f0a8c4e5e.png) | ![image](https://user-images.githubusercontent.com/48527022/103359057-2104ca80-4a85-11eb-9d39-d46b1b680bcb.png) | ✔️ **PASS**
Alert displayed ![image](https://user-images.githubusercontent.com/48527022/103359214-83f66180-4a85-11eb-9795-affcd3102c22.png) | ![image](https://user-images.githubusercontent.com/48527022/103359353-c1f38580-4a85-11eb-8750-4ee1f3c8037e.png) | ✔️ **PASS**
CTA Displayed ![image](https://user-images.githubusercontent.com/48527022/103359435-ed767000-4a85-11eb-85bd-b3957dc0670d.png) | ![image](https://user-images.githubusercontent.com/48527022/103359560-18f95a80-4a86-11eb-8a9f-f04f10480b00.png) | ✔️ **PASS**
Alert link click | ![image](https://user-images.githubusercontent.com/48527022/103359631-375f5600-4a86-11eb-882c-35be83479cf8.png) | ✔️ **PASS**
Click on CTA to begin form | ![image](https://user-images.githubusercontent.com/48527022/103362937-e6e8f800-4a87-11eb-9922-8fc203d36c1c.png) | ✔️ **PASS** <br><br> **Aligns with standardized primary button tracking specification**
Hidden wizard (upon how to wizard completion) | ![image](https://user-images.githubusercontent.com/48527022/103359894-bd7b9c80-4a86-11eb-9bbf-143dee233c2b.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment] 2020-12-30 15:39
### Content Grouping Addition
- HLR has been published to our products content grouping to include pages beginning with `/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996` to be displayed in Google Analytics as `Benefits & Memorials - Higher Level Review (20-0996)`

cc: @bmcgrady-ep @joanneesteban @luke-gcio

**Comment by jonwehausen** [comment] 2020-12-30 17:24
## QA Testing of Custom Dimension Scenarios

### Test Results
| Description of Scenario | Data Layer | Tag | Test Status
| -- | -- | -- | -- |
Successful submission with **same office to review checked** and **informal conference requested** | ![image](https://user-images.githubusercontent.com/48527022/103369674-c07f8880-4a98-11eb-98c1-00c8b9108535.png) | ![image](https://user-images.githubusercontent.com/48527022/103369616-9b8b1580-4a98-11eb-95d4-36630012ed65.png) ![image](https://user-images.githubusercontent.com/48527022/103367462-223cf400-4a93-11eb-94df-7702aef268f6.png) | ✔️ **PASS**
Successful submission with **same office to review not checked** and **informal conference requested** | ![image](https://user-images.githubusercontent.com/48527022/103369736-ead14600-4a98-11eb-9192-7fde57e77543.png) | ![image](https://user-images.githubusercontent.com/48527022/103369759-fb81bc00-4a98-11eb-9ddd-e9de9e58b597.png) | ✔️ **PASS**

## Outstanding Questions & Last Steps to Close! 
- @Mottie I have not yet been able to test a scenario with "yes for an informal conference with a representative" with the test users I have tried. Can you tell me does this [commit here](https://github.com/department-of-veterans-affairs/vets-website/pull/15001/commits/e4df3610fc0ddd9bccd5e46bf81beb9a7cdf99a0) indicate this scenario is supposed to populate with `'yes`' or `'yes-with-rep'`? Thanks in advance
- Another point to call-out -- Thank you for correcting the `-failed` events...One thing here, I have not seen either of the data layer variables pushed with the `-failed` event. This is completely up to you all if you would like to do so, I would recommend we include just in case we want to interpret the metadata in the failed scenarios as well. 

![image](https://user-images.githubusercontent.com/48527022/103370066-d5a8e700-4a99-11eb-838a-5d5988890354.png)

**Comment by Mottie** [comment] 2021-01-07 16:31
Hi @jonwehausen!

First off, the design of the contested issues, same office and informal conference pages have changed. This won't effect the analytics, but I wanted you to be aware that the screenshot I'm sharing isn't like it was before.

> * I have not yet been able to test a scenario with "yes for an informal conference with a representative" with the test users I have tried

Any of the test users can be set to have their representative get called by choosing the appropriate radio button

<details><summary>Yes, call my representative</summary>


![Screen Shot 2021-01-07 at 9 00 12 AM](https://user-images.githubusercontent.com/136959/103909238-12dc2d00-50c9-11eb-8426-9293a15c6eb9.png)</details>

Once that choice is made, the next page will ask for the representative's name and phone number. Then the following page will ask for time choices.

> * Can you tell me does this [commit here](https://github.com/department-of-veterans-affairs/vets-website/pull/15001/commits/e4df3610fc0ddd9bccd5e46bf81beb9a7cdf99a0) indicate this scenario is supposed to populate with `'yes`' or `'yes-with-rep'`?

Yes, that is the unit test for what is sent to analytics

> * I have not seen either of the data layer variables pushed with the `-failed` event.

We're using the default platform code for submission, so I don't think it allows adding additional data. I could duplicate some of the code to add the extra data.

> * there is a warning alert box at the start of the form if the form cannot be started

I think this would be data we would be interested in. Hmm, I thought we included logs to Sentry, but I don't see any. Let me consult the team on this.

**Comment by jonwehausen** [comment] 2021-01-07 18:35
Hi @Mottie , 

Thank you for this here!

Okay, we don't need to worry about the `-failed` event metadata here. 

If you and your team are wishing to track when the warning alert boxes is visible, this is the recommended spec for doing so, please fire **only when the warning alert box becomes visible**

```javascript
'event': 'visible-alert-box', 
'alert-box-type': 'warning', //correlates with the type of alert box
'alert-box-heading': //top level heading of the alert box next to icon
'alert-box-subheading': //if there is an additional subheading with the alert box
'error-key': //if there is an additional error key you would like to pass for further context of why the alert box was shown, errorCode_description_of_error, prefixed with an error code if there is one and snake case description of error
'alert-box-full-width': //true or false if the full width is enabled
'alert-box-background-only': true|false //correlates with the flag for when the alert box is background color only 
'alert-box-closeable': true|false //correlates with if the alert box is capable of being closed
```

If not wishing to track this, we can close out this issue, Thanks @Mottie !

**Comment by Mottie** [comment] 2021-01-08 14:44
I've merged in code that records the visible alert box event. There's no easy way to test the "no contestable issues" alert with the users we have currently, but you can log into any non-HLR user and see the loading error alert.

**Comment by jonwehausen** [comment] 2021-01-08 15:35
Thanks @Mottie! 

Data layer looks good here! ✔️ **PASS**

![image](https://user-images.githubusercontent.com/48527022/104033096-13de8e80-519d-11eb-83a4-13fe60b9d926.png)

**Comment by jonwehausen** [comment] 2021-01-08 15:57
### Next Steps 


https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000440

@bsmartin-ep I'm going to hand this off to you, a couple things to note on this QA: 
- In this case it's safe to say now and in the foreseeable future we will want the event category as "API Calls", but we may introduce a situation in the future where this visibility is the product of a user interaction. Maybe there's another potential variable we can look at introducing to set us up for that. 
- Ensure each of the variables have `(not set)` set for DL variables when value is undefined or null

**Comment by bsmartin-ep** [comment] 2021-01-08 23:18
## QA

Interaction|Data Layer|Tag
---|----|-----
Display of alert box|![image](https://user-images.githubusercontent.com/62304138/104074234-938c4d80-51dd-11eb-9a64-28ca8977ad94.png)|![image](https://user-images.githubusercontent.com/62304138/104074265-a6068700-51dd-11eb-87e0-ad961f8b77db.png)

@jonwehausen -

Do we want to prefix this event action with the component name - like 'Alert Box' ?

**Comment by jonwehausen** [comment] 2021-01-08 23:19
Yes, good catch @bsmartin-ep. Yes please, feel free to update that.

**Comment by bsmartin-ep** [comment] 2021-01-08 23:30
OK cool @jonwehausen...

FYI I had to remove this default value to get the `(not set)` to fall through.  LGTM now...

![image](https://user-images.githubusercontent.com/62304138/104074939-6e98da00-51df-11eb-82ee-c057a54f1a3b.png)

---

Interaction|Data Layer|Tag|Pass
---|----|----|---
Display of alert box|![image](https://user-images.githubusercontent.com/62304138/104074234-938c4d80-51dd-11eb-9a64-28ca8977ad94.png)|![image](https://user-images.githubusercontent.com/62304138/104074857-32657980-51df-11eb-9081-8ab79e7b22be.png)|✔️ **PASS**
Display with null dataLayer params|![image](https://user-images.githubusercontent.com/62304138/104074887-47daa380-51df-11eb-9b92-3ac9f6e7feeb.png)|![image](https://user-images.githubusercontent.com/62304138/104074806-106bf700-51df-11eb-82f8-9b6cbefe6d11.png)|✔️ **PASS**

**Comment by jonwehausen** [comment] 2021-01-13 12:19
Thanks @bsmartin-ep, appreciate you testing the `(not set)` scenario. 

@Mottie @luke-gcio For your teams awareness, tracking has now been published and ready for go-live! 🎆 

cc: @joanneesteban @JasonTheBearded I attempted to update the platform collaboration point tracker (Cell L19) but was unable to do so

**Closed** 2021-01-13 12:21 UTC
Labels: HLR, analytics-insights, analytics-request, collaboration-cycle, frontend, gtm, vsa-benefits, vsa-decision-reviews
