### ISSUE TITLE
Expose hidden/collapsed content to users

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#2203] opened 2019-10-02 17:26 UTC
## Problem descriptions
1. How might we "expose" hidden/collapsed content (e.g., accordion content) for users relying on screen readers?
2. How might we allow users to use their browser's find-on-page utility to search all page content, including hidden/collapsed content (e.g., accordion content)?

## Notes
- Use this page to explore solutions to the problem descriptions: https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
- We know Google indexes hidden/collapsed content, so this is not an SEO problem. These are UX and accessibility problems.

## Objectives or Key Results this is meant to further
- A write-up of recommended solutions to the problem statements.

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by 1Copenut** [comment] 2019-10-02 22:43
@andrewlewandowski I've been thinking about this one all afternoon and have a couple of questions:

1. Are we concerned screen reader users aren't finding the content inside the accordion headings?
2. Are we looking at a secondary "full-text" version of the page with no interactivity?

I don't have any data to suggest one way or the other for question 1, but if question 2 does include a text-heavy version of this page with all content rolled out, we could collaborate with content and design to refine heading nesting for the page-specific goals. I'm attaching a Firefox screen shot with the CSS turned off and headings called out with an accessibility plugin. The buttons we are using for accordions wouldn't make sense in this type of environment, but `<h3>` would for screen readers and visual scanning.

Happy to talk more as this evolves!

---
![Screen Shot 2019-10-02 at 5 35 14 PM](https://user-images.githubusercontent.com/934879/66087144-17b44780-e53c-11e9-87c7-2607425ab968.png)

**Comment by andrewlewandowski** [comment] 2019-10-17 17:53
@1Copenut - Thanks for this! Do you think we need to start exposing accordion titles as new h3 classes for screenreaders? This would be a global change to all our accordions.

Based on your research, I don't think there is a way to "expose" collapsed accordion content to users who want to utilize the control+f/search-on-page tool in their browser.

**Comment by Karak888** [comment] 2019-10-23 17:30
will be mostly all FE engineering effort. will size at grooming

**Comment by 1Copenut** [comment] 2019-10-23 17:34
@andrewlewandowski I think we need a way to set the heading level of our accordions on the fly, as it makes sense to nest them. I can see cases where accordions make sense as H3's because they're sub-points to H2 main points, but will that always be the case, or will there be times the accordions are nested deeper, at an H4 level for instance?

Let's chat about this when you've got a few minutes.

**Comment by Karak888** [comment] 2019-11-13 18:12
@kelsonic please review and let us know if there is front end work and any estimate please.

**Comment by kelsonic** [comment] 2019-11-13 18:17
I'm not exactly sure what needs to be done here after reading tbh... @1Copenut @andrewlewandowski Would either of you be able to update the acceptance criteria on this ticket so that @ncksllvn and I can knock out whatever needs to be done on the frontend? :)

**Comment by andrewlewandowski** [comment] 2019-11-13 18:35
@kelsonic and @ncksllvn - There won't be any new development work as part of this issue. This is more of a research spike. We will create new backlog items if we want to move forward with any proposed solutions.

@1Copenut - As a next step, can you please schedule a meeting with me, @jenniferlee-dsva, @rtwell, @jenstrickland, and @Karak888? I'd like to have a discussion about this together. And after the meeting, I'd like documented recommendations in this ticket. Thank you!

**Comment by 1Copenut** [comment] 2019-12-09 19:35
## Accordion Discussion Wrap Up From 11/27
We are looking to create actionable todos for the accordion discussion first raised in [Github issue #2203](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2203). The DEPO team is looking for ways to help users find content inside accordion expand/collapse sections without having to open those accordions and then search.

What we want to accomplish:

* Surface the accordion content to assistive technology users (screen readers) without requiring users to click / expand the content area.
* `Command + F` searches do not show the content in accordions. This is caused by the accordion content being contained in `display: none;` CSS, which removes it from the DOM (document object model and the accessibility tree.
* VSA has proposed a clipping method, to move content off-screen instead out removing it from the DOM. This should allow the content to be found with a browser search, but will need tested with actual users. Specifically:
	* Are users aware their cursor is off-screen?
	* Are users aware which accordion contains the keyword(s) they're searching for?

### TODOS:
1. Create a Zenhub epic to capture these todos as individual items to accomplish after agreeing on the final list
1. Add keyword text as a second line item to the accordion headings. This could be a bit longer and more descriptive as a first step toward full `Command + F` findability.
2. Add guidance documents for accordion headings. We want to clarify when to use accordions, and what heading text to include.
3. Develop a Codepen or JSBin to test accordion improvements. Key testing facets:
	* Mobile experience
	* Testing mobile devices with screen readers
	* Testing typical `Command + F` browser searches for "hidden" keywords
	* New interaction patterns such as a slide-in from the left, especially at the mobile size
3. Line up user testing for the new interaction pattern. Specifically focus on mobile users, screen reader users, magnifier users, power users who search in browser.
3. Develop a component or adjust the existing component, that allows us to pass in the right heading level (h3 when it's nested in an h2, h4 when nested in an h3...)

/cc @andrewlewandowski && @rtwell && @jenstrickland

**Comment by aeltarhoni** [comment] 2020-01-08 18:50
We are going to unassign this ticket from public websites. Let us know if you need anything.

**Comment by jenstrickland** [comment] 2020-01-09 13:50
@1Copenut If I recall correctly, this was assigned to public websites because they currently have instances of the accordions and we discussed the possibility of testing the solution during one of their projects. Does that match your recollection?

**Comment by 1Copenut** [comment] 2020-01-09 14:41
Ultimately public websites will probably be involved in implementing any findings. Right now we're at a point we need to work on some experiments, maybe in Codepen, to test 1-2 potential solutions. I'm creating an epic in Zenhub and a research ticket, assigning it to myself and @jenstrickland as a first step. It may be a sprint or two before we can get started on research code/testing.

**Comment by Mottie** [comment] 2022-01-04 21:15
@joshkimux With the use of the new `va-accordion` and `va-additional-info` web components. The content exists in the DOM while the component is collapsed, but migration has not yet been fully completed. Granted the hidden content would still be ignored by the screenreader and won't be searchable.

**Comment by joshkimux** [comment] 2022-01-18 15:40
This all sounds good to me @Mottie , feel free to close this out whenever you feel like it's ready.

**Comment by laflannery** [comment] 2023-08-23 18:32
@Mottie Looking back at the comments on this ticket, it looks like we were waiting on migration to the DS components. Now that it's been over a year, do we feel that this has been sufficiently completed and we are able to close this now? Or are there specific instances you know of where content still needs to migrate?

**Comment by Mottie** [comment] 2023-08-23 21:44
I think migration has been complete. I don't have access to CMS data, but I think there was an effort to update all the accordions there as well. We can probably close this issue.

**Closed** 2023-08-24 12:19 UTC
Labels: Public Websites, frontend, accessibility, sitewide, 508-experiment
