### ISSUE TITLE
 [Design] Bad Unit Number design flow Mock Up 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3660] opened 2019-11-21 21:19 UTC
## User Story 

As a designer I need to create a design mock up to show the flow to account for a veteran needing to input a missing unit number into the form. 

## User Goal 

To account for a missing unit number on the form being flagged and prompting the user with the correct messaging to correct their missing unit number. 

## Acceptance Criteria 

If the response is a single suggestion with a "delivery_point_validation" value of "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER" or "STREET_NUMBER_VALIDATED_BUT_BAD_UNIT_NUMBER", tell the user that they appear to have left off the unit number or entered an invalid unit number and prompt them to edit. But also give them the option to force the address through.

## Design MockUps Below:

**Comment by artistgreen** [comment] 2019-12-04 16:56
Tech discovery with @erikphansen and @bradl3yC 

- Confirmed that we can show slightly different modal messaging based on if the entered address has a missing unit number versus a bad unit number.  
This will allow our messaging to be more accurate to users as to what is going and what they need to do in order to update their address.

- Still testing to see if a user can input their missing unit number into any street field

**Comment by artistgreen** [comment] 2019-12-04 17:06
Mockups - the flow is similar to address validation, when the user is only given the option to 'edit address' without an option to override.  We need them to enter or check their entered unit number on the edit mailing address form and clicking 'Edit address' in these screens will send them back to the form.

User needs to enter a unit number
![Missing Unit Number modal.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/c421172f-741f-4b54-81c9-45df46f606a9)


User needs to edit a unit number
![Missing Unit Number modal 2.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/9746fec2-e852-4459-a02f-42625b583b1f)

Working through these screens, we can also consider showing a single modal message to address a bad/missing unit number scenario:
![Missing Unit Number modal 3.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/9cc11312-f723-429b-b13e-730ebfca22d1)

**Comment by artistgreen** [comment] 2019-12-04 17:08
@peggygannon - based on our discussions, please take a look at these screens and provide copy for the modals.  Thank you!

**Comment by artistgreen** [comment] 2019-12-09 20:29
Hi @peggygannon - we are boiling down the UX to this screen in my last post.  We won't be able to discern whether the user needs to edit or enter a unit number, so the messaging needs to address both potential scenarios:

![image.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/ebf6c645-c644-4fa7-9800-70328b5118d5)

Let me know if you have any questions/concerns.  Thanks Peggy!

**Comment by Samara-Strauss** [comment] 2019-12-11 16:39
Has this UX been reviewed with @bradl3yC? I don't remember the specifics, but it sounded like he mentioned on standup on Monday that this might be more complicated than a copy update.

**Comment by erikphansen** [comment] 2019-12-11 16:46
Point of clarity: we CAN tell if the user needs to enter a unit number OR if the user had entered a bad unit number. They are two different error codes. And TBH it isn't clear in that mock what hitting CONTINUE would do. If we're allowing users to move forward without adding a unit number we need to make them take very explicit action to do so.

**Comment by Samara-Strauss** [comment] 2019-12-11 17:04
@artistgreen 

> And TBH it isn't clear in that mock what hitting CONTINUE would do. If we're allowing users to move forward without adding a unit number we need to make them take very explicit action to do so.

I agree with Erik. The mockup and UX you left for Peggy is confusing and unclear. Also, given that it seems like someone *can* edit OR need to add a unit number, let's make sure there are screenshots for that (like you originally outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3660#issuecomment-561739236)).

Also, for bad unit number, will there ever be override/suggestions? Or will the only option ever be to edit the original address?

Finally, I realize the copy in the screenshot is mock copy, but let's make sure Peggy knows the most important points she should be communicating:

- The heading should communicate that someone needs to edit or add a unit number (based on the error code).
- The body copy should provide any other necessary clarification and let them know what their options are for moving forward.

**Comment by erikphansen** [comment] 2019-12-11 17:09
There won't be suggestions from the API if the unit number is bad or missing.

**Comment by bradl3yC** [comment] 2019-12-11 18:21
> complicated

I said that it was just a copy change but if it was decided that the modal needed to change its behavior in some way, it would be more complicated

**Comment by bradl3yC** [comment] 2019-12-11 18:22
> There won't be suggestions from the API if the unit number is bad or missing. But it will be possible to override the error and force through the address with the bad/missing unit number so we should allow users to do that if they are sure the address they entered is correct.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/1287#issuecomment-553951745 . Case 6

**Comment by erikphansen** [comment] 2019-12-11 18:36
@bradl3yC You mean Case 5?

Sorry, to be crystal clear, the error code that the unit number is bad/missing _is_ attached to a suggestion. So technically there is a suggestion from the API in this case. But the API isn't going to suggest unit numbers if you left one off or entered a bad one (in my experience).

**Comment by bradl3yC** [comment] 2019-12-11 18:39
@erikphansen I realize it won't suggest a unit number.  We couldn't do that anyway.  I think the idea was to just treat this like an error state and either allow them to override or edit the address based on the presence of a validationKey and then change the copy if one suggestion (even if its the only one) contains the bad or missing unit number error.

**Comment by erikphansen** [comment] 2019-12-11 18:55
I think we're on the same page

**Comment by peggygannon** [comment] 2019-12-11 19:06
Hello, @artistgreen 

Is this ready for me to work on today? I want to be sure I'm understanding what is needed . Please let me know if I have this correct:  

1. The message heading should say that you need to edit or add a unit number before you  can move forward
2. The user can then: Edit their address or Cancel.. 
3. Is **Continue** still an option? if so, where does that take the user?

**Comment by Justin-Pickett** [comment] 2019-12-11 19:47
@peggygannon Arthur is out of pocket at this present moment for a bit taking care of an injured child, but possibly due to moving this along maybe @Samara-Strauss can provide her design perspective of what should happen and confirm what is needed for us to get this copy finalized soon. I will follow back up by end of day to see if any progress has been made on the above questions. Also @bradl3yC  and @erikphansen please chime in on Peggy's questions above if you think something else should be taken into consideration for flow above.

**Comment by Samara-Strauss** [comment] 2019-12-11 20:45
@peggygannon here is each use case and what we need:

**Add missing unit number with override**

Copy needed: We need to explain that people need to add a unit number because one is likely missing. However, these people can override and move forward with the address they entered, so we need to let them know their options are to edit or save the address as-is.

This is similar to the "confirm" use case we discussed [in 3741](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3741#issuecomment-561759438), so we should treat it as such.

![Add missing unit number with override](https://user-images.githubusercontent.com/34068740/70658541-2d28aa80-1c2c-11ea-9db9-b7dc98ae5396.png)

**Add missing unit number without override**

This is the same as above, except override is not an option. It is more like the "verify" use case we discussed [in 3741](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3741#issuecomment-561759438).

![Add missing unit number without override](https://user-images.githubusercontent.com/34068740/70658543-30bc3180-1c2c-11ea-885f-ec7d58aacf9f.png)

**Edit bad unit number with override**

Copy needed: We need to explain that people need to edit the unit number they had originally included because there is likely something wrong with it. However, these people can override and move forward with the address they entered, so we need to let them know their options are to edit or save the address as-is.

Like the add with override use case, this is more like the "confirm" use case we discussed [in 3741](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3741#issuecomment-561759438).

![Edit bad unit number with override](https://user-images.githubusercontent.com/34068740/70658570-40d41100-1c2c-11ea-9351-a383f3180ae3.png)

**Edit bad unit number without override **

Same as above, but without override. Like the add without override use case, this is more like the "verify" use case we discussed [in 3741](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3741#issuecomment-561759438).

![Edit bad unit number without override](https://user-images.githubusercontent.com/34068740/70658580-43cf0180-1c2c-11ea-85fa-d3ef5be59eca.png)

**Comment by bradl3yC** [comment] 2019-12-11 21:28
@erikphansen Do these screens make sense in the scenario that only one of the suggested addresses reports bad/missing unit number? Or should I look at the highest confidence score and check that one only?

**Comment by Samara-Strauss** [comment] 2019-12-11 21:34
@bradl3yC @erikphansen if I misunderstood a use case or we need updates to the design, please let me know ASAP so Peggy isn't having to rewrite copy.

**Comment by erikphansen** [comment] 2019-12-11 21:35
@bradl3yC These screens should handle the scenario where we there is only a single suggestion from the API and it says the unit number is bad or missing.

**Comment by bradl3yC** [comment] 2019-12-11 21:37
@erikphansen right, so we should only use this copy IF there is only 1 response.  If there is more suggested address, we use the other flows previously approved?

**Comment by erikphansen** [comment] 2019-12-11 21:41
Correct

**Comment by bradl3yC** [comment] 2019-12-11 21:41
@Samara-Strauss Nope! We're good to go with the proposed changes.

**Comment by peggygannon** [comment] 2019-12-11 21:51
@Samara-Strauss @artistgreen Hello, please see copy recommendations below. Let me know if you have any questions or you need me to provide additional tweaks. 



Scenario 1
Add missing unit number with override

**Please add a unit number**
 It looks like your address is missing a unit number. Please edit your address to add a unit number or continue with the address you entered below.  

----

Scenario 2
Add missing unit number without override
**Please add a unit number**
We couldn’t verify your address with the U.S. Postal Service because it’s missing a unit number. Please edit your address below to add a unit number. 

-------

Scenario 3
Edit bad unit number with override
**Please update or confirm your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number or continue with the address you entered below.  

-------

Scenario 4
Edit bad unit number without override
**Please update or confirm your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address below to update the unit number.

**Comment by Samara-Strauss** [comment] 2019-12-11 22:05
@peggygannon my suggestions:

For both the add and edit cases with override, I think we need to clarify that they can override because we know the address might already be correct. I want to make sure we give enough context here user testing participants were confused about why we'd allow override if we knew the address to be wrong/problematic. That's why we decided to frame the other use cases that allow override in #3741 as confirming their original address instead of "the address isn't valid."

**Scenario 1**

Can we say something like:

**Please add a unit number**

It looks like your address is missing a unit number. Please edit your address to add a unit number. If you do not have a unit number and the address you entered below is correct, please select Continue.

**Scenario 3**

Can we say something like:

**Please update or confirm your unit number**

We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number. If your unit number is already correct, please continue with the address you entered below.

**Comment by Samara-Strauss** [comment] 2019-12-11 22:06
Also, the heading for scenario 4 should be "Please update your unit number" since override is not allowed and they can not confirm/move forward with the address entered.

**Comment by peggygannon** [comment] 2019-12-11 22:26
@Samara-Strauss OK, thank you. Updates to the copy are below. 


Scenario 1

**Please add a unit number**
It looks like your address is missing a unit number. Please edit your address to add a unit number. If you don't have a unit number and the address you entered below is correct, please select Continue.

---

Scenario 2
**Please add a unit number**
We couldn’t verify your address with the U.S. Postal Service because it’s missing a unit number. Please edit your address below to add a unit number.

----
Scenario 3
**Please update or confirm your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number. If your unit number is already correct, please continue with the address you entered below.

----

Scenario 4
**Please update your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address below to update the unit number.

**Comment by Samara-Strauss** [comment] 2019-12-12 14:27
@peggygannon these are great! I'll get the copy updated in mockups and pass off to FE.

**Comment by Samara-Strauss** [comment] 2019-12-12 14:48
Copy has been passed to FE in #3891. Closing.

**Closed by Samara-Strauss** 2019-12-12 14:48 UTC
Labels: content, design, vsa-authenticated-exp
