### ISSUE TITLE
Bug: build in vfs-tools repo is failing

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16616] opened 2020-11-25 18:26 UTC
Christopher Valarida  6:37 PM
In related news, I haven't gotten a veteran-facing-services-tools build to pass all day. I think the doc site build is failing, preventing me from making changes to formation-react (and whatever else in that repo).
https://dsva.slack.com/archives/CQH357ZTP/p1605915436063700

Devin McCurdy
I was really confused at first!  Anyway, not sure why I’m still seeing the old versions here (which is what is linked from https://github.com/department-of-veterans-affairs/vets-website)
https://dsva.slack.com/archives/CBU0KDSB1/p1606244787089900

Definition of Done: 
- [ ] Fix the build in vfs-tools repo 
- [ ] Ensure that deploy is working

**Comment by U-DON** [comment] 2020-12-07 21:32
Related support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1607027209029400
Support ticket: department-of-veterans-affairs/vsp-support#53

In progress branch is `gatsby-fix-attempt`. [With the fixes so far, it’s currently failing on the gatsby-plugin-sharp plugin.](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/compare/master...gatsby-fix-attempt?expand=1)

**Comment by billfienberg** [comment] 2020-12-16 22:00
Potentially Relevant Links:
- https://github.com/gatsbyjs/gatsby/pull/28614
- https://github.com/gatsbyjs/gatsby/issues/24774

**Comment by billfienberg** [comment] 2020-12-16 22:42
![image](https://user-images.githubusercontent.com/6130520/102415274-83f25e00-3fbd-11eb-875c-f2df80a5d49a.png)

It failed on [`packages/documentation/src/images/platform/sitewide_primary.png`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/images/platform/sitewide_primary.png)

>`It is probably corrupt, so please try replacing it.  If it still fails, please open an issue with the image attached.`

**Comment by billfienberg** [comment] 2020-12-17 00:01
Inside `gatsby-config.js`, I commented out [the `gatsby-remark-images` object in the `gatsbyRemarkPlugins` array](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/a10d4427380be0e6bb7210d233aa943055ead258), and the [`build` step passed](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fveteran-facing-services-tools/detail/gatsby-fix-attempt/18/pipeline/40) (the `test` step still failed).

So it seems like the problem is with the `gatsby-remark-images` plugin and/or how it's configured.

**Comment by KyleAMathews** [comment] 2020-12-17 03:29
Hi, saw this issue was linked :-D

Could you try opening the above file in something like photoshop and resaving it? There's something goofy about the image itself so if you open and export it, it hopefully will be fixed.

**Comment by billfienberg** [comment] 2020-12-17 14:22
@KyleAMathews thanks for the suggestion. We can give that a try. 

I tried temporarily removing [`packages/documentation/src/images/platform/sitewide_primary.png`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/images/platform/sitewide_primary.png) to see if that single image was the culprit, but our build still failed on a different image. So either we have multiple goofy images, which is possible, or there's something wrong with our Gatsby plugins/configs.

**Comment by KyleAMathews** [comment] 2020-12-17 16:19
Yeah builds fail on the first broken image. You can see the same warnings in development which lets you more easily see all the possible problems.

**Comment by timwright12** [comment] 2020-12-17 21:53
PR for this https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/561

**Closed** 2020-12-17 21:59 UTC
Labels: tools-fe

**Comment by meganhkelley** [comment] 2021-01-04 16:16
@timwright12 to confirm, this is fixed and the VFS Tools repo is deploying as expected? When I look at the commit history I see a lot of red Xs https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commits/master
