### ISSUE TITLE
Refreshing on confirmation page is generating an error

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#9251] opened 2020-05-19 14:13 UTC
Sentry error: http://sentry.vfs.va.gov/vets-gov/website-production/issues/120138/?query=is%3Aunresolved%20source%3Avaos

We should fix this so that you don't get an error, you just hit the existing redirect logic as expected.

**Comment by narin** [comment] 2020-05-27 17:56
Looks like this was fixed by @jbalboni's [PR for FHIR slots](https://github.com/department-of-veterans-affairs/vets-website/pull/12746/files#diff-6673a65f9c75e1d767e6b795b9de19ca) (line 53). 

Confirmed on staging that no error is thrown, no sentry error is logged, and redirect to first step works as expected.  Closing this out.

**Closed by narin** 2020-05-27 17:56 UTC
Labels: bug, frontend, needs-grooming, vaos
