### ISSUE TITLE
file-manifest.json points to .scss font

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18317] opened 2021-01-08 21:41 UTC
https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/file-manifest.json

Look into: 
1. why this is happening. 
2. If we need it, 
3. If we don’t need it, remove it, if we do document why somewhere

**Comment by meganhkelley** [comment] 2021-01-08 21:41
Tim Wright Jan 6th at 10:17 AM
Does anyone have any insight as to why the last item in this file is “style.scss” and it’s pointing to a font? https://www.va.gov/generated/file-manifest.json
:eyes:
2
:face_with_raised_eyebrow:
1

8 replies

Tim Wright  2 days ago
Wondering if it’s used in some way or it’s something we should clean up.

Bill Fienberg  2 days ago
I don’t know why it’s like that, and that seems strange.

Tim Wright  2 days ago
Yeah, I saw it locally and thought it was something with the Webpack work I’m doing, but it’s in prod as well.

Jhonny Gonzalez:spiral_calendar_pad:  2 days ago
yeah, that's bizarre, Why is there a font?

Tim Wright  2 days ago
¯\_(ツ)_/¯

Tim Wright  2 days ago
@Megan Kelley Can we spin up a maintenance ticket for this^ ? For someone to look into 1. why this is happening. 2. If we need it, 3. If we don’t need it, remove it, if we do document why somewhere

Megan Kelley:spiral_calendar_pad:  2 days ago
sure, but we should check with design system team first to see if they have any insight — cc @chris.valarida I believe you're on support this week

Christopher Valarida  2 days ago
Ohh, funky! Not just that it's pointing to a font, but also that it's .scss. The style.css above looks fine, but the style.scss is the font. :confused:
My hunch is that it has to do with the fact that we need to give Webpack an entry file and have it generate style.js and style.js.map just so we can get style.css. Given that it's the only .scss file in the manifest, I'd start my investigation there.

**Comment by theodur** [comment] 2021-07-28 23:42
After investigating, the cause seems to be coming from a [bug](https://github.com/shellscape/webpack-manifest-plugin/issues/208) in the [webpack-manifest-plugin](https://github.com/shellscape/webpack-manifest-plugin), specifically when used with the `mini-css-extract-plugin` ([more context](https://github.com/shellscape/webpack-manifest-plugin/issues/167)). The version mentioned in one of the bug tickets is the same version we are currently using, `2.2.0`, which is almost 2 years old 😬.

I created a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/18052) for upgrading the plugin to the latest version `4.0.1`. The plugin has [required](https://github.com/shellscape/webpack-manifest-plugin#requirements) Webpack v4.44.0+ since `v3.0.0` was released, and we are currently using Webpack v4.43.0. Even though everything seemed to work fine with our current version, I upgraded Webpack to `4.44.0` just to be safe. It's only one bugfix ahead so it should effect anything.

**Comment by theodur** [comment] 2021-07-29 16:54
The PR for this ticket has been merged ✅

**Closed by theodur** 2021-07-29 16:54 UTC
Labels: tools-fe
