### ISSUE TITLE
Discovery: How do we transition k8s review apps to K8s

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42714] opened 2022-06-13 13:09 UTC
## Description
As part of moving vets-api to K8s, we will need to rework the review apps for the new k8s environment. The current review apps are deployed via the current BRD strategy and will need to be modified to function in the k8s environment. This will require cross collaboration with the Infrastructure team. 

[More notes from meeting ](https://vfs.atlassian.net/wiki/spaces/OT/pages/2227077139/2022-06-10+Vets-API+on+EKS+next+steps+for+Q3?src=mail&src.mail.action=view&src.mail.notification=com.atlassian.confluence.plugins.confluence-mentions-plugin%3Amention-created-notification&src.mail.recipient=8a7f808975418369017542cb31a7044a&src.mail.timestamp=1654887966650)between Infrastructure, Console Services and Testing tools

## Acceptance Criteria
- [ ] Discover what will break moving review apps to k8s

Potentially keep these pointing to a BRD solution until we can get these moved over

**Comment by ericboehs** [comment] 2022-10-06 18:16
Duplicate of Team 4's initiative.

**Closed by ericboehs** 2022-10-06 18:16 UTC
Labels: console-services, vets-api
