### ISSUE TITLE
Access for Ryan Smith - AWS

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#38063] opened 2022-03-07 15:41 UTC
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ryan Smith

### Your Email

ryan.smith@adhocteam.us

### Name of Your Team

~~Platform SRE, Software Engineer, Ad Hoc~~
**QA Standards, Software Engineer, Ad Hoc**

### Service(s) You Want Access To

AWS

### Desired AWS Access

~~SRE role and permissions, if possible.~~

~~Otherwise, the same as Zachary Lewis.~~

**The services that a full-stack developer would have access to. I believe you can copy permissions from Holden Hinkle**

### Access Expiration

Ongoing

**Comment by td-usds** [comment] 2022-03-10 13:47
Reached out to VOR

**Comment by td-usds** [comment] 2022-03-17 13:11
Reached out to VOR

**Comment by td-usds** [comment] 2022-03-24 13:22
Checked with VOR again; awaiting information

**Comment by td-usds** [comment] 2022-03-31 12:32
Reached out to VOR again, no update yet

**Comment by td-usds** [comment] 2022-04-07 13:20
Reached out to VOR, awaiting confirmation

**Comment by rmtolmach** [comment] 2022-04-07 20:25
@rsmithadhoc Since you're changing teams, do you still need AWS or can we close this request?

**Comment by rsmithadhoc** [comment] 2022-04-08 14:25
> @rsmithadhoc Since you're changing teams, do you still need AWS or can we close this request?

@rmtolmach I will still need access but I have edited the request according to my new team, thanks!

**Comment by td-usds** [comment] 2022-04-11 20:56
VOR confirmed

**Comment by jbritt1** [comment] 2022-04-12 13:06
First-time login credentials provided to user via Slack DM at this time

**Closed** 2022-04-12 13:07 UTC
Labels: operations, external-request, ops-access-request
