### ISSUE TITLE
Fix web components for TeamSites

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#47966] opened 2022-10-07 22:29 UTC
## Issue Description
This ticket will track the body of work of fixing the VA Design System web components to work on external team-sites like (https://www.va.gov/health) which only import vets-website's Header (aka the injected header). This should be a joint collaboration between the VA Design System team (web components) and the Sitewide Public Websites team (fixing CORS issues & ensure web components js|css) are loaded into team-sites.

---
## Tasks
- [ ] Fix team-sites so that web components are available

## Acceptance Criteria
- [ ] Fix team-sites so that web components are available

**Comment by jilladams** [comment] 2024-01-23 19:49
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11313

**Closed by jilladams** 2024-01-23 19:49 UTC
Labels: Public Websites, VA.gov frontend, sitewide-header
