### ISSUE TITLE
Draft Accessibility guidelines for PDF Forms

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/va.gov-team#49754] opened 2022-11-16 20:49 UTC
### **Description**
Begin best practices recommendation (or find out if they already exist).

### **Supporting Documentation**
[508 Office Request Instructions for PDF review](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#HowtorequestsupportfromtheVA508Office-AuditRequest)

**Comment by jeana-adhoc** [comment] 2022-11-21 20:24
Here are [notes about what I've discovered](https://docs.google.com/document/d/1rKemieiU28v0Y_iaOAiVBhwQPUFQ8c99m00DGhhu0M4/edit?usp=sharing) so far:

- 508 Office Uses built in Adobe Accessibility testing for guidance/standards.
- 508 Office does not have an opinion on software used to create PDFs

**Comment by jeana-adhoc** [comment] 2022-11-22 21:55
There is 1 PDFs listed in the github repo as having accessibility issues:

[10-10ez in Spanish](https://www.va.gov/vaforms/medical/pdf/10-10EZ_Spanish.pdf) - Rarely downloaded ([Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22651 ))

There are others I've discovered that haven't been submitted as having issues, and many are listed in the audit spreadsheet we got from Martha. The 508 office leaves it to the business unit to remediate/fix the PDF issues.

**Comment by tbaker1026** [comment] 2022-12-15 21:58
Talking to Kevin Reed, Wes, how does the form get into the Forms DB, how can we insert some review of the PDF
Understand the process

**Comment by tbaker1026** [comment] 2023-01-31 20:00
Duplicate of #49096

**Closed by tbaker1026** 2023-01-31 20:00 UTC
Labels: forms-audit-digitize
