### ISSUE TITLE
Create a set of intake questions to ask new VFS Teams during the intake process

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#226] opened 2019-06-10 17:22 UTC
## Story
As a VSP product support member, we need information about what a new VFS team is intending to create, their team structure and more before kickoff.

## Goal
Create a set of intake questions that enables VSP product support team to prepare for a new team kickoff

## AC
- [ ] A list of questions has been compiled
- [ ] Reviewed by DSVA platform owners
- [ ] Shared in Github for new VFS team onboarding

## Def of Done
- [ ] AC is complete
- [ ] Connected to an epic

**Comment by smoonpeyes** [comment] 2019-07-11 19:55
@accbjt Is this a duplicate of the intake form that you created?

**Comment by accbjt** [comment] 2019-07-12 06:07
Yes this looks like a duplicate

**Comment by smoonpeyes** [comment] 2019-07-12 11:24
Closing. This is a duplicate of #413.

**Closed by smoonpeyes** 2019-07-12 11:24 UTC
Labels: documentation, product support
