### ISSUE TITLE
Multiple EPs for VA.gov submissions

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#61191] opened 2023-06-29 19:45 UTC
## Issue Description
EP130 (Dependency) -- Multiple EPs for [VA.gov](http://va.gov/) submissions
- Issue: When a Veteran submits multiple claim submissions through [VA.gov](http://va.gov/) (e.g. add/remove dependent, approval of school attendance), multiple claims are being established
- Action: Workgroup contacted [VA.gov/eBenefits](http://va.gov/eBenefits) regarding the issue in September 2022, but additional information was needed. OFO conducted reviews and met with BEST divisions to identify examples. NWQ grouping functionality attempts to distribute the concurrent EPs together (capacity exempt) to minimize delays and impacts to available capacity. Since November 2022, CAs have reviewed claims for potential cancellation prior to field distribution.
- Timeline: Identified August 2022
- Pending: meeting with OBA scheduled March 6, 2023 to discuss potential fix to [VA.gov](http://va.gov/) claim submission process
- Claim impact: 13,087 Ep130s were cancelled b/w July 2022 and January 2023. 10, 499 were incremental EPs (e.g. EP131, 132, etc)
- 11, 563 cancelled by BEST sites (0 cancelled by PMCs)
- Key stakeholder: OBA

## Current Behavior
When a Veteran submits multiple claim submissions through [VA.gov](http://va.gov/) (e.g. add/remove dependent, approval of school attendance), multiple claims are being established.

## Expected Behavior
When a Veteran submits multiple claim submissions through [VA.gov](http://va.gov/) (e.g. add/remove dependent, approval of school attendance)...
- Are different dependent changes/updates submitted at the same time intended to generate a single claim?
- Or, is any change/update intended to append itself to the original claim vs creating an additional claim?

## Tasks 
- [ ] XX

## Acceptance Criteria
- [ ] Laura and Thomas to determine AC

**Comment by steele-lm** [comment] 2023-06-29 20:08
@sortizsh Is this a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/61190 ?

**Closed** 2023-06-29 20:12 UTC
Labels: bug, needs-grooming, needs-refinement, Umbrella
