### ISSUE TITLE
[Ops/VSP] 526: File Upload Network Error Issues

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15687] opened 2020-11-02 19:48 UTC
## Issue Description
When I make a request from vets-website that fails at the revproxy rather than vets-api from vets-website I get see a CORS error rather than the actual error sent from the revproxy because the revproxy does not set the `Access-Control-Allow-Origin` header. If I were to make the same request as a non-ajax request (through command line or postman or something) I would successfully see the revproxy error. 

So, for example, if I sent a too-large file  (>151mb) from vets-website the revproxy would return `413 Request Entity Too Large` but it would appear in the browser as being blocked by the CORS policy. 

<img width="1516" alt="Screen Shot 2020-10-06 at 9 33 05 AM" src="https://user-images.githubusercontent.com/19188/95208402-09d07c80-07b7-11eb-8e37-c2e40bc61849.png">

Placeholder for followup to https://github.com/department-of-veterans-affairs/va.gov-team/issues/14427

I'm thinking that the correct fix is to set the  `Access-Control-Allow-Origin` header in the [nginx config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/base-shared.conf.j2)

to the same [values we use](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L6) in vets-api

**Comment by annaswims** [comment] 2021-02-09 01:06
we should set Access-Control-Allow-Origin in nginx to these values if the headers aren't set by rails

**Comment by jason-gcio** [comment] 2021-02-16 19:23
Thank you Anna!

**Comment by omgitsbillryan** [comment] 2021-02-16 19:55
1. You mention "fwdproxy" - did you mean the `revproxy`?
> the fwdproxy would return `413 Request Entity Too Large`


2. The `vets-api` rails app has a middleware that responds with it's own CORS headers. Is the assumption that the revproxy is rejecting the request immediately, such that, it never gets to the rails app?

3. Would you mind posting the full `curl` (or equivalent) command to reproduce the issue?

4. Since the rails app already returns CORS response headers, there might need to be some additional logic to prevent us from accidentally returning multiple / duplicate CORS response headers from rails & nginx.

**Comment by omgitsbillryan** [comment] 2021-02-16 19:58
WRT point 4 ☝️ , looks like we may have already experienced & solved - [link to code](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/enable-auth.conf.j2#L4-L13)

**Comment by annaswims** [comment] 2021-02-16 21:05
> You mention "fwdproxy" - did you mean the revproxy?

yeah, I fixed it above.  This is all about the proxy between the browser and rails.

**Comment by annaswims** [comment] 2021-02-17 00:37
> Would you mind posting the full curl (or equivalent) command to reproduce the issue?

I think this sort of gets you what you're looking for.  I'd want the response to have a `Access-Control-Allow-Origin` header.  Just replace /path/to/my_largefile.mp4 with some >151 mb file you have.   We first saw this before we uploaded files that were larger than what the proxy allowed, but since then we've upped the proxy limit. 

````
curl -i --location --request POST 'https://staging-api.va.gov/v0/whatever' --form 'file=@"/path/to/my_largefile.mp4"'
HTTP/1.1 100 Continue

HTTP/1.1 413 Request Entity Too Large
Date: Wed, 17 Feb 2021 00:32:11 GMT
Content-Type: text/html
Content-Length: 180
Connection: close
Cache-Control:
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty</center>
</body>
</html>
````

**Comment by omgitsbillryan** [comment] 2021-02-17 04:21
Thanks for reproducing. 

WRT adding the CORS response headers via nginx - isn't the real problem that nginx is denying these requests in the first place? If nginx allowed the request through, rails would tack on the appropriate CORS response headers.

It looks like [you already addressed this problem](https://github.com/department-of-veterans-affairs/devops/pull/7990/files#diff-24ad4d69a588144e90ff8a437aa07000c91197f3ef40819fa509f80ae9feeeafR56) by setting `client_max_body_size 151m;` for any directive that include `base-shared.conf` which includes [the entire api server directive itself](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L13). Do you have any idea why nginx is still denying this request?

**Comment by annaswims** [comment] 2021-02-17 12:14
Without the headers it's a timesuck of troubleshooting.  The nginx error appears to be a cord error and fe devs never see the real error

https://dsva.slack.com/archives/CBU0KDSB1/p1612826771412600

**Comment by omgitsbillryan** [comment] 2021-02-22 21:41
I started deep-diving on this one, and so far, I hate all my solutions 😄 

- disabling the nginx check altogether --- exposes us to some DOS attacks
- conditionally adding `Access-Control-Allow-Origin` response header if it doesnt exist --- seems rather clunky since these CORS headers are more intricate than that and I don't pretend to know all the subtle nuances of how these headers work 

I think we might be able to disable the nginx max_size check in conjunction with a vets-api change that enforces a max_size check. I think this enforcement can be done with Carrierwave which vets-api already uses. That way, Rack::Cors would gracefully handle all response CORS headers and as an added bonus - the response body would actually be in JSON instead of HTML (which is what nginx returns with its `413`)

Another possibility that I know a lot less about, would be to have the front-end JS implement some kind of uploading chunking/slicing to keep each upload under the limit. That's a bit outside my expertise and would need some additional input.

**Comment by omgitsbillryan** [comment] 2021-02-23 19:10
I hacked this together ☝️ which really only fixes the error messaging. I think we need a more comprehensive solution to allow for large uploads while also not exposing us to DOS attacks.

**Comment by omgitsbillryan** [comment] 2022-01-03 19:29
Today's my last day - we should probably just close this as "Will not fix".

I wasn't confident enough in [my bandaid PR (that was never merged)](https://github.com/department-of-veterans-affairs/devops/pull/8565) didn't cause more problems than it solved. The real solution to this problem is the [Epic that I linked to where we have a centralized / global solution for handling file uploads](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20503).

**Closed** 2022-01-03 19:48 UTC
Labels: vsa-devops
