### ISSUE TITLE
Add new header to CARMA submission request

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#8872] opened 2020-05-07 12:14 UTC
Given that we need to be able to send form submission to CARMA
I want to ddd new header to CARMA submission request
So that submissions can be successful.

**Comment by kevinmirc** [comment] 2020-05-08 19:42
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/7789

**Closed by kevinmirc** 2020-05-08 19:42 UTC
Labels: backend, vsa-caregiver
