### ISSUE TITLE
[FE] [BUG] When an address save fails we don't stop polling the endpoint

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17209] opened 2020-12-09 19:14 UTC
## Background
We need to investigate if we are recording multiple save errors each time an update fails.

See [slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1608151618218800?thread_ts=1608145951.213700&cid=C909ZG2BB)

## Tasks
- [ ] Prevent continuous pulling of endpoint

**Comment by Samara-Strauss** [comment] 2020-12-16 20:48
Also, per conversation in Slack, this ticket should also investigate whether we are tracking singular errors multiple times, therefore elevating our error count.

**Comment by erikphansen** [comment] 2020-12-16 21:12
I'm going to start looking into this ASAP, in hopes that this is the cause of our massive difference in total events and unique events.

**Comment by erikphansen** [comment] 2020-12-17 17:10
PR merged! This should go out with today's release. So starting Friday Dec 18 our ratios of total events to unique events should look more normal. Meaning "duplicate" events will be from users manually trying to save their changes after a failure, not from our code being stupid.

**Closed by erikphansen** 2020-12-17 17:10 UTC
Labels: bug, frontend, profile, vsa-authenticated-exp

**Comment by Samara-Strauss** [comment] 2020-12-17 19:23
Awesome! Thank you! This will definitely give us a better idea of the scale of the errors we're seeing.
