### ISSUE TITLE
Adding [naomi.eke@coforma.io] to DSVA Slack

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#83381] opened 2024-05-17 14:04 UTC
Please add naomi.eke@coforma.io as a full member, they will be joining the CEDAR CDS project. We will add them to the appropriate channels once they are in.

Please reach out to Jeff Langworthy on DSVA slack for any questions/clarifications.

**Comment by coforma-terry** [comment] 2024-05-17 18:26
I think we can close this one @jlang10761 as it's a duplicate of this one:
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/82066](url)

**Closed** 2024-05-22 17:58 UTC
Labels: Slack Request
