### ISSUE TITLE
SPIKE: Create SiS Engineer Portal

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55972] opened 2023-03-29 15:18 UTC
## Description

We want to create an engineer portal for our SiS tooling that allows external teams to come in and understand SiS and integrating it seamlessly into their application. We need to investigate what this portal will look like, what the content will consist of and where it will live. Our vision is that the portal will consist of the config dashboard, developer page and client config page (plus more?)

## Acceptance Criteria

- [ ]

**Comment by bosawt** [comment] 2023-03-29 22:07
Closing as this is a duplicate of: https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55971

**Closed by bosawt** 2023-03-29 22:07 UTC
Labels: Identity
