### ISSUE TITLE
CMS Export Build error: Breadcrumb errors from unpublished pages

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#19313] opened 2021-02-01 15:19 UTC
## Details

**Notes from Standup 1/28/21:**
* Not sure if this is an issue we would see in production — seems to be creating breadcrumbs for pages that aren’t yet published
* This is failing the build — saying that some nodes don’t have links to parent or children nodes? 
* Kevin Walsh updated the node in question and fixed it, but build is still failing. Node does seem to published as part of test data. 

**Relevant Slack threads:**
- FE Tools discussion https://dsva.slack.com/archives/CQH357ZTP/p1611762273045600
- Discussion with CMS team https://dsva.slack.com/archives/C01512KN35G/p1611756619152200

## Definition of Done

- [x] Investigate and determine cause of issue
- [x] Determine whether this will be an issue in production
- [ ] If this will be an issue in production, troubleshoot & fix
   - [ ] If solution involves significant lift, we can spin up a separate ticket for it

**Comment by k80bowman** [comment] 2021-02-01 22:02
In order to run the build with the test data currently, we are having to comment out the lines calling the addGetUpdatesFields function in `src/site/stages/build/drupal/metalsmith-drupal.js`
- [1st line](https://github.com/department-of-veterans-affairs/vets-website/blob/59aabdbe6a99c3981fa457a881312e455e72a01b/src/site/stages/build/drupal/metalsmith-drupal.js#L65)
- [2nd line](https://github.com/department-of-veterans-affairs/vets-website/blob/59aabdbe6a99c3981fa457a881312e455e72a01b/src/site/stages/build/drupal/metalsmith-drupal.js#L68)

**Comment by k80bowman** [comment] 2021-02-04 16:23
Some notes regarding generalized breadcrumbs errors (not necessarily pulling from unpublished pages, but just in general). In talking with @indytechcook today, I found out that the content team does test the data in demo environments before it goes live. However, there are no guarantees that we won't see breadcrumbs errors in the future.

> We have planning a more sophisticated UI/UX around editorial experience and validation to avoid this in the CMS but it's probably at least 1/2 a year off.

> I'm going to bring this specific issue so we can figure out a process to address it

Full convo can be found in this thread: https://dsva.slack.com/archives/C01512KN35G/p1612455472414700?thread_ts=1612360771.352700&cid=C01512KN35G

**Comment by k80bowman** [comment] 2021-02-08 15:19
I think we can close this one out. We were concerned that the CMS Export build could be trying to create breadcrumbs from pages that weren't yet published. We weren't seeing this problem with production data, however, only with test data, which made me wonder if the problem was more that we just weren't 100% sure what data was published and what wasn't.

I went through our code to verify where the data was coming from for the function we were seeing fail (`addGetUpdatesFields`). I traced it back to the `getNonNodeContent` function in src/site/stages/drupal/api.js where I found we are running the same query we do for the GraphQL build, just without the "today" variable set and with useTomeSync set to true, which tells the query to not include the `nodeQuery` subquery as part of the larger GraphQL query.

The `onlyPublshedContent` variable is included in the query header, however, and it does not appear that any of the subqueries included in the GraphQL query override it. I confirmed this with @indytechcook in Slack ([thread](https://dsva.slack.com/archives/C01512KN35G/p1612795423010200)).

<img width="431" alt="image" src="https://user-images.githubusercontent.com/12739849/107239646-11b75c00-69f7-11eb-9fd4-f29b40f36022.png">

**Closed** 2021-02-08 17:05 UTC
Labels: cms-transformer, tools-fe
