### ISSUE TITLE
Alert - EC request limit reached

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12426] opened 2020-08-12 17:40 UTC
If a Veteran has too many open requests for Express Care concurrently, they need to be prompted with an alert that they have reached their limit for express care requests. 

## Acceptance criteria:
- [ ] request care limit check happens when Veteran clicks "Continue express care request" on the How express care works
- [ ] if veteran has reached limit they are how the 'request limit' alert

**Comment by narin** [comment] 2020-08-13 16:10
I think this is a duplicate of #11978.  I have most of the check logic done. Just need to move it to the correct spot in the flow. @rtwell can you drop in a design in #11978 once it's ready?

**Closed** 2020-08-13 16:10 UTC
Labels: content, design, frontend, vaos
