### ISSUE TITLE
(Staging) 662 test user doesn't see Express Care section

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20853] opened 2021-03-04 17:49 UTC
## What happened?
Report from MHV SQA

> MHV has a test user in the SQA environment with San Francisco CA VAMC (662). Our system recognizes the test user as a San Francisco CA VAMC (662) patient. However, VA.gov staging environment appears not to and doesn’t display the Express Care button. We are trying to find out whether there is an issue with the account or the VA.gov staging environment. Can someone look into this and let us know whether things work as expected in VA.gov staging environment?

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8123972f-723f-41fc-ba8e-e60e822698e6)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:
> MHV User ID: mhvcss03
> ICN: 1013223409V330424

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Actual Behavior
Express Care section does not display

## Expected Behavior
Express Care section displays to San Francisco CA VAMC (662) registered user

**Comment by jbalboni** [comment] 2021-03-04 18:22
What's happening now is the expected behavior. Express Care is marked as disabled for site 662 in staging and because there's no test VistA instance with an id of 662 in staging, there's not a clear way to enable Express Care. And even you did get the VATS settings changed, you won't be able to submit or manage a request because there's no staging VistA instance for 662.

The way we test Express Care is by using users who are registered at one of the two staging test sites, 983 and 984.

**Comment by laurenernest** [comment] 2021-03-04 18:27
Can we pull the list of sites this test user is registered at? Or if there's a way for them to see those, then instructions I can send would be great as well.

**Comment by jbalboni** [comment] 2021-03-04 18:28
@laurenernest Yes, if we get the credentials for that account and can log in with it.

**Comment by jbalboni** [comment] 2021-03-04 19:11
@laurenernest That user is registered at 662, 622, and 757.

**Closed** 2021-03-04 20:25 UTC
Labels: bug, frontend, vaos
