### ISSUE TITLE
[Bug] Find Forms - Sort

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#19429] opened 2021-02-03 00:45 UTC
## What happened?
On Staging **Find a VA Form** page, in certain devices/browsers [listed below], the Sort feature wasn't functioning.

## Specs:
- Device: Apple iPad & iPhone, Windows PC, & MacBook Pro
- Browser: iOS & Mac Safari, Win & Mac Firefox

## Steps to Reproduce
1. In one of the devices/browser listed above, go to https://staging.va.gov/find-forms/
2. In **Enter a keyword...** text-field, input **10-10ez**, then click **Search** button.
3. Observe that the results' **Form last updated** dates are not sort by newest-first.
4. In **Enter a keyword...**, input **higher level review**, then **Search**.
5. Observe same sort issue.
4. From **Sort by** menu, choose **Last updated (Oldest)**.
5. Observe same sort issue. [Results don't appear to reload at all.]

### Video [Win Firefox example]

https://user-images.githubusercontent.com/587583/106682348-8a459500-657f-11eb-88df-aa662ebd059a.mp4

**NOTE**: Issue also same for Mac Firefox, iOS & Mac Safari.

## Desired behavior
Results should be sorted by newest-first on initial search, and by oldest-first upon choosing Last Updated (Oldest) from Sort-by menu.

## Acceptance Criteria
- [ ] [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by MarciMcGuireGCIO** [comment] 2021-02-03 01:45
Hi @zacharymorel can you please review this when you have time? It’s for the sort that is meant to deploy on Monday. Thank you!

**Comment by MarciMcGuireGCIO** [comment] 2021-02-03 11:28
@tlei123 I do want to clarify that the initial sort should not be in order by date, but rather in the default order (alphabetical, I believe) that was presented when the MVP was built. We will eventually be adding logic to weight the results so that we can present them in order of relevance.

The sort by date is an option requested for a  small subset of users for a specific use case where they need to discern the age of available forms.

**Comment by zacharymorel** [comment] 2021-02-03 13:56
@tlei123 can you do a hard refresh of the page? It's interesting that I am not having the sorting issue. 
![Screen Shot 2021-02-03 at 8 56 02 AM](https://user-images.githubusercontent.com/26075258/106756867-b4d63300-65fd-11eb-8f79-3ca3661722bd.png)

**Comment by MarciMcGuireGCIO** [comment] 2021-02-03 13:58
@zacharymorel - can confirm I reproduced in Firefox on Windows.  Were you finally able to get access to a Virtual Desktop?

**Comment by zacharymorel** [comment] 2021-02-03 15:27
I have figured out the bug, a fix should be up shortly.

**Comment by tlei123** [comment] 2021-02-03 17:56
> @tlei123 can you do a hard refresh of the page? It's interesting that I am not having the sorting issue.
> ![Screen Shot 2021-02-03 at 8 56 02 AM](https://user-images.githubusercontent.com/26075258/106756867-b4d63300-65fd-11eb-8f79-3ca3661722bd.png)

@zacharymorel , sorry for late reply, but in addition to @MarciMcGuireGCIO 's Win Firefox replication, I just replicated the issue again on Mac Firefox as well.

**Comment by tlei123** [comment] 2021-02-03 18:12
> @tlei123 I do want to clarify that the initial sort should not be in order by date, but rather in the default order (alphabetical, I believe) that was presented when the MVP was built. We will eventually be adding logic to weight the results so that we can present them in order of relevance.
> 
> The sort by date is an option requested for a small subset of users for a specific use case where they need to discern the age of available forms.
> 
> cc @zacharymorel

@MarciMcGuireGCIO , thx for clarification, but can your team confirm this please?  I wanna ensure the Use-/Test-Cases are updated if needed.

Also, assuming alpha-ascending is confirmed initial-search default-sort...

It might be confusing that the **Sort By** menu has **Last Updated (Newest)** _selected by default_ on initial search.  This screenshot of the menu shows the default selection, when I just clicked to expand it:

![Screen Shot 2021-02-03 at 11 04 51 AM](https://user-images.githubusercontent.com/587583/106789694-d7714780-660f-11eb-960c-52ac04282581.png)

It'd prob'ly be prudent to explicitly add this menu-option as the pre-selected default.

Thx much!  :)

**Comment by zacharymorel** [comment] 2021-02-03 18:17
@MarciMcGuireGCIO I built the sorting to sort default by what is selected. 
Does this need to be changed? 

I agree with Tze, if it was default sorting by alpha-ascending, that could cause some confusion from a ux perspective I think?

**Comment by MarciMcGuireGCIO** [comment] 2021-02-03 19:14
@zacharymorel let's also get @laurellawrence and @johnhashva to weigh in.   

Since the date sort is for a edge case, and the MVP sorted alphabetically (which most people will probably find more useful than sort by date), I think we should add alpha A-Z and alpha Z-A to the select.

**Comment by zacharymorel** [comment] 2021-02-03 19:34
OK! I'll hang tight until they can give feedback. I will hold off on asking for a peer review for my work!.

**Comment by johnhashva** [comment] 2021-02-03 19:38
I agree with @MarciMcGuireGCIO --- let's see if @laurellawrence gives us a thumbs up for consensus.

**Comment by johnhashva** [comment] 2021-02-03 22:22
@MarciMcGuireGCIO just re-reading/thinking this a bit -- and now confused.   Marci, let's walk through this during our 9:30am meet on Thursday.

**Comment by laurellawrence** [comment] 2021-02-03 22:42
Agree with @MarciMcGuireGCIO that it makes sense to add the A-Z sort options to the dropdown since this sort method was MVP by default. The sort by component update is in review which includes theses options - Ascending (A-Z) and Descending (Z-A). 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/375

**Comment by zacharymorel** [comment] 2021-02-04 14:27
Okay, if everyone gives it the okay? We'll need a new user story for the addition options of the sorting.
There's a 50/50 chance this will be ready by 2/9.

**Comment by johnhashva** [comment] 2021-02-04 14:57
@MarciMcGuireGCIO helped me understand this better and we are all set to go.  Marci will work with @laurellawrence to finalize the spec. TY.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-04 15:49
@zacharymorel, please refer to the mockup in the component [@laurellawrence provided](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19429#issuecomment-772876823), but TLDR; the order will be:

A-Z
Z-A
By Date Decending
By Date Ascending

**Comment by laurellawrence** [comment] 2021-02-04 17:03
https://xd.adobe.com/view/e5588086-506e-49af-9202-939481ab3b5f-b00b/
<img width="926" alt="Find a Form - Final Design" src="https://user-images.githubusercontent.com/75386943/106928127-7bbec100-66d8-11eb-8a09-f2f34626905f.png">

I've also updated our component update ticket with a screenshot and the order of the filters. [#375
](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/375)

**Comment by zacharymorel** [comment] 2021-02-04 18:00
@MarciMcGuireGCIO I am going to make another user story for this work. 
Am I correct that this will get inserted in to our sprint?

**Comment by MarciMcGuireGCIO** [comment] 2021-02-04 20:10
@zacharymorel yes, this should go in since it's part of what we'd committed to this sprint.  I saw the new issue you created  (thanks!) and will also add to the list of deliverables cross-browser testing just so that's covered.

**Comment by MarciMcGuireGCIO** [comment] 2021-02-10 21:58
@zacharymore I am still seeing the sort bug on Staging in Firefox on Windows 10.

**Comment by zacharymorel** [comment] 2021-02-11 20:09
Closing this, as the the testing has passed!

**Closed** 2021-02-11 20:09 UTC
Labels: PR-open, bug, dt-find-va-form, frontend, unplanned-work, vsa-decision-tools
