### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#26537] opened 2021-06-23 20:23 UTC
# Request Google Analytics and/or Domo access

## What this form is for
Domo Accesws

## User Email Address
curt.bonade@oddball.io

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

_No additional requirements at this time_

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
_No Rush_

## Product Team / External Team / VA Office
_VSP Testing Tools Team_

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment] 2021-06-24 14:35
@CBonade - you have been added to Domo.  You should receive an email with an invite.

You're in the _Default_ group right now, but let me know if you can't access any dashboards.

**Comment by joanneesteban** [comment] 2021-06-24 15:02
@bsmartin-ep can you add Curt to the VSP Testing Tools group, please?

**Comment by bsmartin-ep** [comment] 2021-06-24 15:16
@joanneesteban - weird, I looked for a testing tools team when I created the account, but it didn't come up in the search.

Do I need to change the owner from Lauren to the shared account?

![image](https://user-images.githubusercontent.com/62304138/123288400-88a04d80-d4dd-11eb-9d2f-4475409908ce.png)

**Comment by bsmartin-ep** [comment] 2021-06-25 00:25
@1Copenut - can you add Curt the VSP Testing Domo group?  I am unable to do so...

https://va-gov.domo.com/admin/groups/1936574845

Thanks!

**Comment by bsmartin-ep** [comment] 2021-07-08 16:08
Not entirely sure what the issue is with the group assignment, but Curt should be set up in GA and Domo.  Closing.

**Closed by bsmartin-ep** 2021-07-08 16:08 UTC
Labels: access-request, analytics-insights, analytics-request
