### ISSUE TITLE
Add retry logic for unit tests 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9574] opened 2020-05-28 13:39 UTC
- Some of our unit tests intermittently fail 
- Add retry logic for unit tests 
- Add a todo to remove retry logic after app separation project

**Comment by rianfowler** [comment] 2020-10-16 21:51
- Retry logic added to unit tests
- Monitor failures over the next week to determine if approach reduces flakey test failures

**Comment by meganhkelley** [comment] 2020-12-30 18:57
Duplicate of #16941

**Closed by meganhkelley** 2020-12-30 18:57 UTC
Labels: tools-fe
