### ISSUE TITLE
Dependents | Document 686C-674 Failure points

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#89258] opened 2024-07-24 19:48 UTC
Recently, we realized that when the DependentsService fails for PDF Upload, we both notify the Veteran and submit the claim down back process.

Please document the various Failure scenarios that can occur in 686C-674 submissions, and what we do in each scenario
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?wid=0-1721321111054&sender=u0e23f90bc2aa6d1f44e99992

What happens when:
- vets-api is down
- vets-api controller unreachable
- SavedClaim cant be saved
- PDF cant be uploaded
- Evidence Upload fails
- 686 cant be submitted
- 674 cant be submitted
- backup submission fails
- backup submission succeeds, but polling job shows failure
- anything else I missed

# Acceptance Criteria
This ticket is solely about addressing the dead-ends and potential opportunities for remediation of 686c/674.
This is not a ticket about code quality or an effort to capture silent failures.

- [ ] - Present findings to product team for next steps.

**Comment by sanjabaj2** [comment] 2024-08-19 22:21
[Potential sub ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83273), as one of the findings.

**Comment by mjknight50** [comment] 2024-08-28 16:15
@evansmith - Is this actually done?  What was the outcome?  
If not, can we please move back to backlog?

**Comment by evansmith** [comment] 2024-08-28 16:23
@mjknight50 I completed the mural board addition. I can move it to review.

**Comment by mjknight50** [comment] 2024-08-28 16:40
We'll need to present out findings on 686c/674.  Can you please link any tickets that were created as a result.
If you are ready to present on this, we'll need to schedule a meeting with Sanja and Steve.
cc @steele-lm

**Comment by evansmith** [comment] 2024-08-28 16:47
@tblackwe do you know which tickets were created from this?

**Comment by steele-lm** [comment] 2024-08-28 16:50
@evansmith @mjknight50 @tblackwe I believe we need to review the documentation created, determine where the gaps are, create tickets to mitigate/improve, and then meet with Sanja and Steve.

**Comment by steele-lm** [comment] 2024-08-28 17:12
@mjknight50 to talk to @tblackwe about next steps.

**Comment by mjknight50** [comment] 2024-08-28 20:55
This ticket is solely about addressing the dead-ends and potential opportunities for remediation of 686c/674.
This is not a ticket about code quality or an effort to capture silent failures.

**Comment by sanjabaj2** [comment] 2024-09-10 21:41
I created additional monitors as I worked on [this ticket ](https://github.com/orgs/department-of-veterans-affairs/projects/1262/views/1?filterQuery=&pane=issue&itemId=76418767)
The outcome of the ticket should be to:
1. Document failure scenarios (i.e. mural)
2. Create tickets for identified shortcomings in error catching 
3. Create tickets for identified shortcomings in monitors. 

When this ticket is complete, we have good picture of work needed to be properly and accurately detecting and monitoring for silent failures.

**Comment by sanjabaj2** [comment] 2024-09-10 21:42
Also, did someone edit acceptance criteria that I added couple weeks back?

**Comment by steele-lm** [comment] 2024-09-30 18:22
Closing this as a duplicate of #93326 and #93327

**Closed** 2024-10-23 17:55 UTC
Labels: backend, monitoring, dependents-benefits
