### ISSUE TITLE
[Discovery] Possible bug on 10-10EZ static personal info page

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42457] opened 2022-06-07 15:40 UTC
## The situation
In staging, authenticated. 
- I was on the static (personal info page)
- Was working on something else- the "you're about to be logged out" model was on screen when I navigated back to it
- I clicked on "I need more time" button (granted maybe the time was expired, but I don't know, because I was still able to click on the model
- The static page was blank (see screenshot)

## Expected UX
- If what happened is that I was logged out (likely) then it should've taken me back to the intro page
- If I wasn't then I am wondering if this has anything to do with the other errors around this page

![Static screen.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d9aad502-0707-4cfb-83bf-39dc6d26cd2e)

**Comment by markfallows** [comment] 2022-07-06 19:20
Unable to reproduce, closing ticket.

**Closed by markfallows** 2022-07-06 19:20 UTC
Labels: bug, 1010-team, 1010-ez
