### ISSUE TITLE
Discovery: test content build with 48k nodes on GitHub Actions

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25859] opened 2021-06-09 17:08 UTC
See Jenkins test ticket #24022 

## Details

Jenkins can support 48K nodes but we are switching to GHA as a CI tool. We need to test on GitHub Actions to confirm scalability. Now that Ops has configured the self-hosted runners in the content-build repo at four runners per EC2 instance, we can test in an accurate way.

## Definition of Done 
- [x] Content build is tested on GHA with 48k+ nodes (multiple runs)
 - [x] Memory use, build time, and any errors are documented here

**Comment by alexandec** [comment] 2021-07-08 19:48
@meganhkelley found it! I will update the Details section

**Comment by alexandec** [comment] 2021-07-12 23:32
The production build is running well on GHA at 48k nodes. However the dev and staging builds are being killed due to lack of memory in the final step (Adding debug info to Drupal pages). I'm looking into the cause and will test potential solutions. Most likely the issue is reading in too many files at once, so the contents are stored in memory together.

**Comment by mchelen-gov** [comment] 2021-07-13 18:35
requested GHA runner instance be increased from 32 -> 64gb if it helps https://github.com/department-of-veterans-affairs/va.gov-team/issues/27243

**Comment by alexandec** [comment] 2021-07-13 19:51
Thanks for requesting that Mike! I think it will really help us focus on other improvements by freeing us from memory optimization work.

**Comment by alexandec** [comment] 2021-07-15 23:24
### Summary

I ran builds with 48k nodes on both Jenkins and GHA to compare the two.

### Pipeline Benchmarks

Build configuration: Staging build, 48k nodes, 60-second manual garbage collection interval, 10gb max heap size. A couple new optimizations are in place (see Optimizations below).

|               | Setup   | Build       | Prearchive | Compress | Upload | Total         |
| -------- | ------- | -------- | ---------- | ---------- | ---------| --------- |
| Jenkins  | 2 mins | 53 mins | 9 mins       | 2 mins      | 3 mins    | 69 mins    |
| GHA       | 1 min    | 50 mins | 9 mins      | 82 mins   | 22 mins  | 164 mins   |

The GHA pipeline is a bit faster than the Jenkins build, with the large exception of the Compress and Upload steps. Something strange is happening with our self-hosted runner on those steps. This may be related to disk IO for the Compress step and network IO for the Upload step. But that's just a guess at this point. More research is needed here.

#### Execution time
Both pipelines have a total execution time greater than an hour. This is a problem given our goal of hourly content releases. Prime areas for optimization on GHA are the Compress and Upload steps. Hopefully we can reduce execution time for those steps so it's similar to what we have now on Jenkins.

The Build and Prearchive steps are also candidates for optimization. However, they may be more challenging to optimize since we've already improved them significantly in the past.

#### Memory use
Memory use on GHA should not be a problem given the upgraded self-hosted runners there. They have 64gb of memory, which is double what our Jenkins nodes have available. We can work on optimizing build time on GHA without worrying too much about memory use.

#### Other notes
Cypress and Nightwatch tests are not included here. I removed them because they were failing and terminating the build with the 48k test data. This removal should only have a small effect on build time (2-3 minutes).

I used the staging build because it contains debug info, which requires more time and memory than the production build without debug info.

### Optimizations
In my testing I found a couple optimizations that would reduce build time:
- With the increased available memory I was able to reduce manual garbage collection frequency from 10 seconds to 60 seconds. I also increased maximum heap size to 10gb to enable the change to work. Reduced GC frequency sped up the build by about **3 minutes**.
- Limiting concurrency when reading and writing debug information reduced build time by about **8 minutes**. Limiting concurrency also reduced peak memory use. I recommend we create a ticket to limit concurrency when adding debug info.

We can implement the concurrency limit anytime. We'll need to wait on the GC frequency reduction until we switch over to GHA. The current Jenkins nodes are still at 32gb and could run out of memory without frequent GC.

#### Failed optimizations
I tried combining the per-letter "Apply layouts" steps together into a single step. I was able to prevent running out of file descriptors by forcing global use of graceful-fs like this:
```
const realFs = require('fs');
const gracefulFs = require('graceful-fs');
gracefulFs.gracefulify(realFs);
```
However the build process ran out of heap memory even with a limit of 20gb. That amount of memory usage isn't feasible even with the increased memory on the self-hosted runners.

### Build summary

Here's a build summary from GHA:
![gha-48k-summary.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/8ea9df1a-b9f1-4099-9e94-9da976fba6d5)!

Here's one from Jenkins:
![jenkins-48k-summary.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/4c1778a5-c2e8-483c-bf39-81323dcbaf28)

Note that the step to add debug information is not included in the summary. That final step took about 5 minutes in each case.

**Comment by mchelen-gov** [comment] 2021-07-20 15:04
Ops ticket for GHA compression & upload: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27182

**Comment by alexandec** [comment] 2021-07-20 16:24
I've been looking into why the "Compress prearchived build" step takes so much longer on GHA (about 80 mins) compared to on Jenkins (about 2 mins) at 48k nodes.

Here's the size of the build directories after the build completes:

```
30G  build/vagovdev
30G  build/vagovstaging
4.4G build/vagovprod
```

The debug info adds a very large amount of data to the dev and staging builds. But this doesn't account for the huge compression time difference between Jenkins and GHA.

Investigating further, I noticed the `tar` command options on Jenkins are slightly different than the options on GHA. I tried timing both commands locally using `time` with the following results (Jenkins options first, then GHA options):

```
tar -C build/vagovstaging -cf build/vagovstaging.tar.bz2 .  4.13s user 48.34s system 49% cpu 1:46.38 total
tar -C build/vagovstaging -cjf vagovstaging.tar.bz2 .  3751.30s user 29.12s system 98% cpu 1:03:59.62 total
```

There is indeed a huge time difference: 2 minutes for the Jeknins options versus 64 minutes for the GHA options. The `-j` flag is the difference here. It tells tar to use bzip2 compression. On Jenkins the flag is absent, so although a tar file is created, no compression is used. This is evident when comparing the resulting tar file sizes. The Jenkins tar file is 29gb in size, while the GHA tar file is 2.3gb. 

So the Jenkins filename `vagovstaging.tar.bz2` is actually incorrect. It's a tar file, but it's not compressed at all. This means that during the Archive step at 48k nodes, Jenkins is uploading a 29gb file to S3. Impressively this takes only 2 minutes. GHA, by comparison, only has to upload a 2.3gb compressed file -- but it takes 22 minutes to do so. The reason for the difference in upload time remains unclear.

**Comment by alexandec** [comment] 2021-07-20 22:47
I also tried configuring the build to upload an uncompressed staging build tar file on GHA. GHA's `upload-artifact` action automatically applies its own gzip compression before uploading. This reduced the staging build tar file size from 30gb to 4.7gb. Upload time was 52mins which is significantly improved over the compressed file upload time of 80mins.

However, we can't afford to wait 52 minutes just for the file upload to complete. As described above, additional work will be required to improve upload time.

**Comment by alexandec** [comment] 2021-07-21 17:53
I created two followup implementation tickets based on my investigation in this ticket:

- Limit concurrency when writing debug information [#27670](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/27670)
- Reduce manual garbage collection frequency [#27672](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/27672)

Will close this ticket and begin work on those.

**Closed by alexandec** 2021-07-21 17:53 UTC
Labels: tools-fe
