### ISSUE TITLE
[FE] Profile, Notification Prefs: Add named anchors to the Personal and Contact Info section

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#25769] opened 2021-06-07 19:32 UTC
We want the ability to "deep link" people directly to particular bits of contact info on their Profile, so we can have a link that reads something like "add your email address to your profile" and when they click that link they are directed to the "Contact email address" section of their Profile.

Two possibile approaches:
1. ~The named anchor would wrap the "Contact email address" header~
![Screen Shot 2021-06-07 at 12.29.47 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/a5fe3e5c-b311-4110-939f-202ebee1ad52)
2. Or, the named anchor would be on the "Edit email address" button
![Screen Shot 2021-06-07 at 12.30.07 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d1759f7f-0b8f-43e0-9d57-5b3bbd32fb38)

[Based on this comment from Liz](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25769#issuecomment-856232310), we will go with option 2 and set focus on the `edit` button. So the URL will be something like `/profile/personal-information#edit-mobile-phone`, focus will be on the `edit` button, and the `edit` button will be scrolled to the top of the browser window (or as close to the top as possible).

**Comment by erikphansen** [comment] 2021-06-07 19:38
@andaleliz @tressaellen do either of you have feelings about where the target for these deeps links should be? I outlined two basic options above.

@andaleliz If/when we implement these deep links, I wonder if the Notification settings links would change? Something like this, maybe?

![Screen Shot 2021-06-07 at 12.35.05 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d951c015-4178-4b10-912c-5575b4fef396)

**Comment by andaleliz** [comment] 2021-06-07 19:57
@erikphansen I think what we landed on w/ a11y means the 1st option - targeting the header - would be the way to go since it provides more context than just the edit button and it's "native" (for lack of a better term) browser/DOM behavior for a heading to receive focus? Thought now that I type that I'm questioning if that's correct because a button can also receive focus...

Yes, you're totally right that the links would change - [the prototype](https://preview.uxpin.com/5ecec4de6ec34eddc9f095677a881be3646124ce#/pages/139049744/simulate/sitemap?mode=i) reflects how the links will look with deep linking (check the text inside the groups too), but the static mock-ups don't yet.  I'll make those updates this week. 

I think the first `update your contact information` link would stay as-is, so it doesn't need to change if a person has both email AND mobile phone numbers on file. We have enough conditionals as it is!  Open to discussing that if you disagree though.

**Comment by erikphansen** [comment] 2021-06-07 20:02
@andaleliz option one is fine. But what I realized is that headers actually do not get focus. By default heading elements are not focusable. So what we actually do is add a new `a` element, give it an `id`, and voila, you can deep link to that new anchor tag.

I was thinking that option 1 makes a lot of sense for the link to the email address. But option 2 makes more sense for linking to the mobile phone number since the mobile phone number is the 3rd phone number under the "Phone numbers" heading.

**Comment by andaleliz** [comment] 2021-06-07 20:18
@erikphansen that's a really good point. We should be consistent with however we do it.  I don't _think_ there are any negative impacts to sending focus to that edit button instead of the section heading since it already has the aria label that provides context.  @joshkimux or @AngelaFowler82 can you please confirm?

**Comment by joshkimux** [comment] 2021-06-07 20:24
@erikphansen , a simpler approach could be to just give the heading a `tabindex="-1"` 👍 

@andaleliz sending the focus to the edit button would be good anticipatory design in this case as the user has committed to an action from the previous stage; it would save them some steps. For sighted keyboard users, it's an immediate cue to action. Screen reader users will still get the context too thanks to the `aria-label`

**Comment by andaleliz** [comment] 2021-06-07 20:28
@joshkimux thanks for the super quick reply! ⚡   I like the anticipatory design angle; we're sending them here because they specifically clicked on something that says `update` or `add`. Currently the button will say `edit` regardless if they are adding or not (for consistency across the many sections) but that's something we can revisit after this study and we pull those `remove` buttons out of the edit mode and into read mode.

@erikphansen given that, let's send the focus to the edit button, por favor.

**Comment by AngelaFowler82** [comment] 2021-06-07 20:40
Sounds good.

**Comment by erikphansen** [comment] 2021-06-07 20:44
Original message edited to reflect the direction we have settled on.

**Comment by ajakabcin** [comment] 2021-06-30 16:18
Confirmed on staging

**Closed by ajakabcin** 2021-06-30 16:18 UTC
Labels: frontend, planned-work, profile, vsa-authenticated-exp
