### ISSUE TITLE
Analytics Implementation or QA Support for [Public Websites - Resources and Support MVP 1.0]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15196] opened 2020-10-22 19:24 UTC
# Google Analytics Implementation

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- This request for Google Analytics. 

- Who is this request for?

    - @jenniferlee-dsva , PO; @brianalloyd , PM
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - Team: Public Websites team

    - Learning center (official name: __Resources and support__)
    
- Provide the Domain where Google Analytics needs to be implemented
    - www.va.gov/resources/ (Drupal node for the LC 'homepage'
https://prod.cms.va.gov/node/8296)
    
    _No PII is passed in URL or title tag_ 
    
    - [URL and Title Tag Chart] 
![Screen Shot 2020-10-20 at 11 00 48 AM](https://user-images.githubusercontent.com/70410912/96620595-e2080b00-12c4-11eb-981d-b7eeaa9efbc4.png)

- Category: Account and profile
    - URL: www.va.gov/resources/account-and-profile/
    - BC: Home > Resources and support > All articles in: Account and profile
    - Article page UPDATE 10/16/2020

- Example H1: Frequently asked questions (FAQs) about signing in to VA.gov
    - URL: www.va.gov/resources/frequently-asked-questions-faq-about-signing-in-to-va-gov/
    - BC: Home > Resources and support > Frequently asked questions (FAQs) about signing in to VA.gov
    - URL: www.va.gov/resources/account-and-profile/frequently-asked-questions-faq-about-signing-in-to-va-gov/
    - BC: Home > Resources and support > Account and profile > Frequently asked questions (FAQs) about signing in to 
     VA.gov
    - Tag landing page

- Tag: Claims and appeals status
   - Example H1: All articles tagged: Claims and appeals status
   - URL: www.va.gov/resources/tag/claims-and-appeals-status/
   - BC: Home > Resources and support > All articles tagged: Claims and appeals status
      Search results page

- Example search: claim status
   - Example H1: Search results for: "claim status"
   - URL: www.va.gov/resources/search/?query=claim+status
   - BC: Home > Resources and support > Search results for: "claim status"

- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - MVP 1.0 Production beta launch: ~ Nov 4, 2020
    - MVP 1.1 Production full launch: ~ December 'TBD' 2020

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._

## Website Interactions to Track
**Note: the url structure of the Resources and Support pages is **

## Search Engagement 
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Origin/Acquisition     | Search refinements after initial search (What terms are bringing users to Resources and Support components?)  | Table                   |
|2| Baselining             | Organic Search - want to measure out-preform from previous to post launch                                                                       | Table and/or Line graph |
|3| Conversions/Engagement | How often users switch to search "All VA.gov" after searching resources and support articles.                                                                                 | Table                   |
|4| Conversions/Engagement | Resource & Support (LC) search - How often is R&S search component is engaged                                                       |       Table                  |
|5| Conversions/Engagement | Scroll depth - What are the users behaviors in finding related content                                                                                     | Table                   |
|6| Conversions/Engagement | Search Terms (what are users searching for on LC)              | Table                   |

## Exits/Navigation from an Article
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | global search in the utility nav  | Table            |
|2| Navigation/Engagement         | Breadcrumb                  | Table and/or Line graph |
|3| Navigation/Engagement  | Global menu (fat nav)                                                                                | Table and/or Line graph (However best to view)     |

## Engagement Metrics
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | Tags (Which tags are being clicked? Frequency?            | Table   |
|2| Navigation/Engagement         | Related information link clicks/engagement                 | Table  |
|3| Navigation/Engagement  | VA benefits link clicks/engagement               | Table and/or Line graph (However best to view)     |
|4| Navigation/Engagement  | CTA button(s) how many clicks on each page/article, bounce rate post click to determine user behavior              | Table and/or Line graph (However best to view)     |

## Customer Satisfaction via: GA Dashboard or Medalia (DOMO)
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Satisfaction/Engagement    | `How do you rate your experience on this page` track response with comparable between good and bad         | Chart/Graph   |
|2| Navigation/Engagement         | Calls via phone number links in the `Need more help` component                | Table  |

Screenshots:

Please reference the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b) board in support of requested items tabled above. 

Customer Satisfaction Elements:

How do you rate: 
![Screen Shot 2020-10-20 at 10 54 15 AM](https://user-images.githubusercontent.com/70410912/96618927-c865c400-12c2-11eb-92fe-52169e5f5483.png)

Tags:
![Screen Shot 2020-10-20 at 10 54 08 AM](https://user-images.githubusercontent.com/70410912/96619005-df0c1b00-12c2-11eb-86da-a99c9a156e2e.png)

Need More Help:
![Screen Shot 2020-10-20 at 10 54 36 AM](https://user-images.githubusercontent.com/70410912/96619053-edf2cd80-12c2-11eb-9b79-84f6e199cef0.png)

Search Component: Resources and Support Vs. All of VA.gov
![Screen Shot 2020-10-20 at 10 55 00 AM](https://user-images.githubusercontent.com/70410912/96619124-04008e00-12c3-11eb-8c4d-e82105ef4b20.png)

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment] 2020-10-23 00:03
HI @brianalloyd , 

Thanks for the request, acknowledging receipt here! We will review and reach out if needing to setup a meeting here.

**Comment by brianalloyd** [comment] 2020-11-02 23:04
@joanneesteban just checking to see if their is anything I can help with this request and if you had an idea of when Analytics implementation might be in place for R&S based on our 11/4/2020 launch schedule.

**Comment by jonwehausen** [comment] 2020-11-03 01:05
Hi @brianalloyd, 

Thank you very much for your patience here, will be giving this a thorough review and reaching out with questions.

**Comment by jonwehausen** [comment] 2020-11-03 12:34
Hi @brianalloyd, 

Thank you for filling out this request very thoroughly! - apologies again for the delay here. 

### KPIs
- As part of our due diligence with each request we receive, we wanted to ask if the team had a product outline we could review? I reviewed the mural [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b), and just wanted to ensure we weren't missing any other documentation available. 
- Secondary, if the team had documentation on long-term KPIs for Resources and Support? We would like to give those a review as well with the goal of developing a DOMO KPI dashboard for you all. We also are developing a framework to assist on KPI setting if necessary. 

### Data Layer / Items to track
- @brianalloyd As for the items you drafted within the issue, here is the data layer specification we are proposing to track and measure the areas of content you have identified, we will want to connect with an FE to have this implemented.  
- Some of the items below are items that can be configured now in prep for 1.1

Description of Interaction | Screenshot of Interaction | Data Layer Specification
------------ | ------------- | -------------
Clicks on primary button CTAs on `/resources` subpages |  ![image](https://user-images.githubusercontent.com/48527022/97979561-64043380-1d9d-11eb-80ae-626e5002d954.png) | `'event': 'cta-button-click',`<br>`'button-type': 'primary',`<br>`'button-click-label': 'Go to eBenefits to change your info' //dynamically populate with button text`
Clicks on page tags | ![image](https://user-images.githubusercontent.com/48527022/97980103-41bee580-1d9e-11eb-9f8f-f066b50cfb92.png) ![image](https://user-images.githubusercontent.com/48527022/97980922-85661f00-1d9f-11eb-8ce3-c81f80f236a1.png) | `'event': 'nav-page-tag-click',`<br>`'page-tag-click-label': 'Lorem impsum' //dynamically populate with tag text`<br>`'page-tag-category-label': 'Topics' //dynamically populate with category of tag`
Clicks on breadcrumb links | ![image](https://user-images.githubusercontent.com/48527022/97981319-16d59100-1da0-11eb-82ce-a0793a15f5ce.png) | `'event': 'nav-breadcrumb',`<br>`'breadcrumb-click-label': 'Resources and support' //dynamically populate with click label,`<br>`'breadcrumb-click-level': 2 //from LEFT TO RIGHT, level of the breadcrumb that is clicked`<br>`'breadcrumb-total-levels': 3 //total number of breadcrumbs in series (including one currently on)`<br>`'breadcrumb-mobile-first-enabled': true\|false //Boolean if the mobileFirst flag is used at time of click`
Clicks on additional info component [1.1] | ![image](https://user-images.githubusercontent.com/48527022/97981752-c27ee100-1da0-11eb-8e7e-bd5fedfc860b.png) | `'event': 'int-additionalInfo-expand' //or 'int-additionalInfo-collapse'`,<br>`'additionalInfo-click-label' //dynamically populate with click label`
Clicks on links within "Related information", "VA benefits", "Need more help?" section | ![image](https://user-images.githubusercontent.com/48527022/97985547-6ae37400-1da6-11eb-9334-86122e221d64.png) | `'event': 'nav-linkslist',`<br>`'links-list-header': //populate with blue header text (link),`<br>`'links-list-section-header': //dynamically populate with high level section, i.e "Related information"` 

### Search

#### On Search
- The following data layer code should execute following the user **completing a search** from any R+S page 
```javascript
recordEvent(
  'event': 'view_search_results', //fyi this taxonomy difference is to align with upcoming 2021 GA4 taxonomy
  'search-text-input': //populate precisely with query user initiated search
  'search-selection': //populate with "Resources and support", "All VA.gov" 
  'search-results-total-count': //populate with total count of search results returned
  'search-results-total-pages': //populate with total page count returned on search
)
```
#### On Search Result Click
- The following data layer code should execute when a user has **clicked on a search result**
```javascript
recordEvent(
  'event': 'onsite-search-results-click', //fyi this taxonomy difference is to align with upcoming 2021 GA4 taxonomy
  'search-text-input': //populate precisely with query user initiated search
  'search-selection': //populate with "Resources and support", "All VA.gov" 
  'search-results-total-count': //populate with total count of search results returned
  'search-results-total-pages': //populate with total page count returned on search
  'search-results-position-number':  //populate with the numerical position of the search result, relative to the current result page
)
```


### Good/Bad Feedback Component
- Will revisit upon @joanneesteban's return on next steps towards capturing
- We can determine next steps towards GA tracking if pivoting from Medallia

### Outstanding Questions
- From your request template verbiage, when you say "global nav" do you mean the nav at the very top with "VA Benefits and Health Care" -- just want to make sure as we have existing tracking in place here
- When are the `/resources` pages going to be made available within staging? 
- Is 1.0 rolling out to only a subset of users? phased roll-out?

**Comment by jonwehausen** [comment] 2020-11-03 17:08
ccing @bsmartin-ep and @bmcgrady-ep for visibility

**Comment by brianalloyd** [comment] 2020-11-03 22:00
@jonwehausen let me see if I can answer your questions posted below; 

**1** From your request template verbiage, when you say "global nav" do you mean the nav at the very top with "VA Benefits and Health Care" -- just want to make sure as we have existing tracking in place here (Answer - Yes, by global we do mean the nav at the top as described above.)

**2** When are the /resources pages going to be made available within staging? (Answer: They should be available in Demo/Staging, with a plan to publish to prod tomorrow). 

**3** Is 1.0 rolling out to only a subset of users? phased roll-out? (Answer: Roll out will not be phased, and will be available to full span of users however it will have limited content as we ramp up to MVP 1.1 with another content load in and on-going forward). 

CCing @jenniferlee-dsva for any additional details and updates from her prospective (and to keep me straight on the details).

**Comment by jenniferlee-dsva** [comment] 2020-11-03 22:40
I am not clear on the global nav answer. @jonwehausen could you point me to where it says that? REason I ask is because if we reference global search, it would be in the  utility nav (which is also 'global'), not the global menu nav where we link to benefit pages. But I can't tell without seeing the context of reference.

**Comment by jonwehausen** [comment] 2020-11-04 00:07
Sure @jenniferlee-dsva, [here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196#issue-727660641) last row in the "Exits/Navigation from an Article" section.

**Comment by jenniferlee-dsva** [comment] 2020-11-04 22:26
Replying to ^ - yep confirming Brian. 

3 | Navigation/Engagement | Global menu (fat nav) | Table and/or Line graph (However best to view)
-- | -- | -- | --


This refers to : 

![image](https://user-images.githubusercontent.com/43381063/98174405-d6baff00-1ec2-11eb-8599-0b8dce6e97c9.png)

**Comment by jonwehausen** [comment] 2020-11-05 13:04
Hi @jenniferlee-dsva and @brianalloyd, 

Thank you for confirming here! Yes, we have pre-existing tracking at each level of the top level navigation. 

### Here are a couple event-based reports for safekeeping to analyze this: 
- [Global nav clicks by navigation level](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventLabel&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22(nav-header-link%7Cnav-header-top-level%7Cnav-header-second-level%7Cnav-hub-containers)%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=100)
- [Global nav clicks by navigation level AND page](https://analytics.google.com/analytics/web/template?uid=1GloPaFyR6WZvz-VhDJ8lQ)
   - _The link provided is a custom report template you will want to add to your GA profile by selecting the view "All VA.gov Website Data [Production]" when prompted_ 
   - _One intriguing thing here is since we added a post-auth parameter of `?postlogin=true` a few months back to our URLs it helps reveal how many users authenticate directly before they use the navigation_

Screenshot | Event Label
------------ | -------------
![image](https://user-images.githubusercontent.com/48527022/98241032-533bf500-1f38-11eb-94a4-35285d74050c.png) | nav-header-top-level
![image](https://user-images.githubusercontent.com/48527022/98241220-a44be900-1f38-11eb-9391-fa00e72360a6.png) | nav-header-second-level
![image](https://user-images.githubusercontent.com/48527022/98241442-f4c34680-1f38-11eb-9b05-774184907431.png) | nav-header-link 
![image](https://user-images.githubusercontent.com/48527022/98241530-14f30580-1f39-11eb-9cd0-44f76553c668.png) | nav-hub-containers

**Comment by jonwehausen** [comment] 2020-11-05 23:02
Referencing Mickin's comment from duplicate ticket for visibility: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14408#issuecomment-712927368

**Comment by bsmartin-ep** [comment] 2020-11-06 22:54
@bmcgrady-ep / @jonwehausen -

Here is my working GTM workspace for this:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

Some pretty extensive changes, including the first pass at the new Interaction events.

Thoughts on this JS structure to return dash delimited values?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382/variables/957

We need to make sure this new design system stuff and the old implementations can coexist for now, so please let me know if anything looks off in your QA.

**Comment by brianalloyd** [comment] 2020-11-12 20:54
@jonwehausen checking up on this ticket.  Do you need anything else from our team in support this request?  Appreciate it.

**Comment by jonwehausen** [comment] 2020-11-12 21:38
Hi @brianalloyd , 

Thanks for checking in here, very much appreciated. 

I wanted to re-surface our Slack conversation here for context: https://dsva.slack.com/archives/C52CL1PKQ/p1604439488366600

Next steps are for us to have your FE team members implement the data layer as designed here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196#issuecomment-721089451. We thank you in advance here and please let us know any further questions you may have here. 

It is my understanding we will revisit the feedback component tracking piece in December following further progression on the Medallia roll-out. 

Once implemented, we can QA @bsmartin-ep's GTM tagging changes, deploy the tracking, and begin surfacing these insights for you all. 

cc: @joanneesteban

**Comment by brianalloyd** [comment] 2020-11-12 22:15
Thanks @jonwehausen sounds good, thank you.

**Comment by jonwehausen** [comment] 2020-11-12 22:48
Thank you @brianalloyd , please don't hesitate to ask any further questions you may have

**Comment by brianalloyd** [comment] 2020-11-13 15:54
@jonwehausen @joanneesteban could we schedule a quick roundtable review early next week.  I have a few questions that I think might be easier to discuss via Zoom.  Thanks, Brian

**Comment by brianalloyd** [comment] 2020-11-16 20:19
@kelsonic I discussion with the analytics team we need to connect the data layers to the FE as suggested [Here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196#issuecomment-721089451) once that is complete can you please comment on this ticket for @jonwehausen to begin analytics implementation.  Please ping me if you have any questions and we can do a quick zoom call to discuss the details.  CC @jenniferlee-dsva

**Comment by joanneesteban** [comment] 2020-11-18 17:25
Thanks, all. @bsmartin-ep is going to work on this while @jonwehausen is OOO at the end of the week.

**Comment by brianalloyd** [comment] 2020-11-18 22:53
Thanks @joanneesteban appreciate the support.  Please reach out with any questions.  Also have a KPI Dashboard Ticket #16233 in flight as well.

**Comment by kelsonic** [comment] 2020-11-19 19:48
PR merged, ready for validation following the daily deploy 🙂

**Comment by brianalloyd** [comment] 2020-11-23 19:41
@kelsonic just validating PR was merged and @bsmartin-ep has everything to work the request. Thanks.

**Comment by bsmartin-ep** [comment] 2020-11-25 15:03
@jonwehausen / @bmcgrady-ep -

This is ready to QA on staging:

#### Design system stuff:
>https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

(Guess we **do** need to keep that CTA button stuff in there for this one, Ben.)

#### Non-design system stuff:
>https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000395

Jon, I saw you had [this workspace out there](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000381) for this ticket, but it looks like it's a test workspace.  Disregard?

Let me know if you have any other questions.

**Comment by jonwehausen** [comment] 2020-11-25 22:04
### WIP - QA Testing - 11/25/2020

Description of Interaction | Screenshot of Data Layer | Test Status
------------ | ------------- | -------------
Clicks on default button CTAs on `/resources` subpages |  ![image](https://user-images.githubusercontent.com/48527022/100283496-a1db1e80-2f3b-11eb-914b-9b06bc12c874.png) | ✔️ **PASS**
Clicks on page tags | ![image](https://user-images.githubusercontent.com/48527022/100283683-eff02200-2f3b-11eb-9135-48f603a9cf88.png) ![image](https://user-images.githubusercontent.com/48527022/100283752-0a2a0000-2f3c-11eb-97ab-0deeefd712b2.png) | ✔️ **PASS**
Clicks on breadcrumb links | ![image](https://user-images.githubusercontent.com/48527022/100284054-8e7c8300-2f3c-11eb-872c-e1730c77f1c1.png) | ✔️ **PASS**
Clicks on links within "Related information", "VA benefits", "Need more help?" section | ![image](https://user-images.githubusercontent.com/48527022/100284659-7f4a0500-2f3d-11eb-8108-1fd195b8e119.png)  ![image](https://user-images.githubusercontent.com/48527022/100284724-a1438780-2f3d-11eb-9d4b-f72b0bae155d.png) | ✔️ **PASS**

cc: @kelsonic - this is in progress, but looks good so far, thank you for your work here

**Comment by jonwehausen** [comment] 2020-11-25 22:36
GTM QA documentation to follow....

GTM Tags published so far: 
- Button CTA tracking (according to new design system taxonomy) 
- Content page tags

cc: @bsmartin-ep for your awareness, no action necessary -- QA will continue here

**Comment by jenniferlee-dsva** [comment] 2020-12-01 16:01
Hello - It looks like a lot has happened here! Thx @kelsonic @jonwehausen @bsmartin-ep . 

Is there anything for me to do here to validate, since this ticket is in the Validate column?  When can we begin to see analytic events being tracked?

**Comment by jenniferlee-dsva** [comment] 2020-12-01 16:05
Also - I see page elements like tags and buttons being tracked. We also need to be tracking search - what user queries are entered and searched on, user behavior wrt to search (do they refine search term, do they switch to `All VA.gov` search option, etc.). 

I do see this in the section called "Search engagement" above, but just wanted to make sure we don't forget about that aspect of this analytics ticket.

**Comment by brianalloyd** [comment] 2020-12-02 17:40
@jonwehausen @joanneesteban @bsmartin-ep Just wanted to get a status update on this ticket as I know the KPI dashboard is being worked actively.  @jenniferlee-dsva has some questions above as well.  Please advise, thanks.

**Comment by jonwehausen** [comment] 2020-12-03 13:00
Hi team,

Thank you for the follow-ups here -- we are in process of doing some incremental QA + publishing here due some new standardized tagging efforts our team introduced. 

The items previously QA'ed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196#issuecomment-733966292) have been published, and you can find `/resources/` page GA events [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22BW%22,%22www.va.gov~2Fresources%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=25)

We will be working thru the remaining QA items before weeks end. Thanks again here team

@kelsonic @srsuddath I will reach out over Slack with a separate question we have regarding search from R+S and the new type ahead POC roll-out. 

cc: @brianalloyd @jenniferlee-dsva @joanneesteban

**Comment by brianalloyd** [comment] 2020-12-07 16:01
@jonwehausen thanks for closing the loop on this greatly appreciated.  Keep us updated on what else you need to close this out and we'll ensure we provide follow up and resolution soonest.  Thanks, Brian.

**Comment by bsmartin-ep** [comment] 2020-12-11 02:23
@brianalloyd -

The type ahead portion of the tagging is ready to go:

### QA

Description|Data Layer|GTM Tag|Pass
----|----|-----|-----
Search on /resources/|![image](https://user-images.githubusercontent.com/62304138/101853341-722c3900-3b2d-11eb-8732-5d3b585a3108.png)|![image](https://user-images.githubusercontent.com/62304138/101853495-a9024f00-3b2d-11eb-9c16-42108eb01286.png)|:heavy_check_mark: PASS
Search result chosen|![image](https://user-images.githubusercontent.com/62304138/101853516-b7506b00-3b2d-11eb-9a87-f66bb67ec70d.png)|![image](https://user-images.githubusercontent.com/62304138/101853403-8c661700-3b2d-11eb-8d97-01450efacadd.png)|:heavy_check_mark: PASS

**Comment by brianalloyd** [comment] 2020-12-16 19:45
Thanks @bsmartin-ep appreciate the follow up.  Can you or @jonwehausen advise on what's remaining on this ticket?   Thanks.

**Comment by jonwehausen** [comment] 2020-12-16 20:20
Hi @brianalloyd , 

Thanks for following up here, I am in the process of doing additional QA here with the goal of closing out very soon. 

Thanks again, 
Jon Wehausen

**Comment by brianalloyd** [comment] 2020-12-17 14:45
Awesome, thanks @jonwehausen for the update and appreciate the support on this, thanks.

**Comment by jonwehausen** [comment] 2020-12-17 19:37
## QA Testing

### On Search
Test Case Description | Data Layer Screenshot | GTM Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Search query with no test results on resources & support | ![image](https://user-images.githubusercontent.com/48527022/102526590-e2751600-4069-11eb-8c41-6cd23484bf88.png) | ![image](https://user-images.githubusercontent.com/48527022/102526704-151f0e80-406a-11eb-9ce5-984ae26cda3d.png) ![image](https://user-images.githubusercontent.com/48527022/102528462-9b3c5480-406c-11eb-875a-f32dcdb18c0f.png)  | ✔️ **PASS**
Search for _claims status_ on resources & support | ![image](https://user-images.githubusercontent.com/48527022/102527210-c1f98b80-406a-11eb-9343-453be760900b.png) | ![image](https://user-images.githubusercontent.com/48527022/102527245-d3429800-406a-11eb-9576-cd59d0fed105.png) ![image](https://user-images.githubusercontent.com/48527022/102527298-e35a7780-406a-11eb-8d0f-5a9f30f98f53.png) ![image](https://user-images.githubusercontent.com/48527022/102527613-59f77500-406b-11eb-8c95-ce5f0ed2c70e.png) | ✔️ **PASS**
Search from resources & support page for all va.gov | _did not push event to data layer_ | _did not fire tag_ | ⚠️  **DOES NOT PASS**

### On Search Result Click 
Test Case Description | Data Layer Screenshot | GTM Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Search for _claims_ on resources & support and clicked on "How to check your VA claim, appeal or decision review status online (2rd position) | ![image](https://user-images.githubusercontent.com/48527022/102528036-fc175d00-406b-11eb-9757-eb951e5c1b69.png) | ![image](https://user-images.githubusercontent.com/48527022/102528723-ebb3b200-406c-11eb-90f6-e0ca3683f733.png) ![image](https://user-images.githubusercontent.com/48527022/102528753-f5d5b080-406c-11eb-9241-654936ddb770.png) | ✔️ **PASS**
Search for _claims_ on resources & support and clicked on "What your claim status means" (3rd position) | ![image](https://user-images.githubusercontent.com/48527022/102528593-c58e1200-406c-11eb-80dd-48aeeeb8fc25.png) | ![image](https://user-images.githubusercontent.com/48527022/102528341-68925c00-406c-11eb-8b7f-93b77f136ca0.png) ![image](https://user-images.githubusercontent.com/48527022/102528140-20733980-406c-11eb-87b7-59f291d4bf51.png) | ✔️ **PASS**

### Updates 
- @kelsonic We will re-test when we are able to verify the data layer on search when the "All VA.gov option is used. Thanks again for your efforts here. 
- We have begun collecting search metadata for the Resources + Support only searches

**Comment by jonwehausen** [comment] 2020-12-18 20:51
Connected with @kelsonic on the above fix, PR on the way

**Comment by kelsonic** [comment] 2020-12-18 20:55
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/15437

**Comment by brianalloyd** [comment] 2020-12-21 16:02
Thanks @kelsonic and @jonwehausen for working these details, greatly appreciated.

**Comment by jonwehausen** [comment] 2020-12-29 15:53
Closing this ticket. Tracking has been published following the latest PR. 

Thanks for the team effort here @kelsonic @brianalloyd

**Closed by jonwehausen** 2020-12-29 15:53 UTC
Labels: analytics-insights, analytics-request, collab-cycle-review, collaboration-cycle, frontend, gtm, vsa, vsa-public-websites
