### ISSUE TITLE
Unpublished (archived) VAMC facilities show up on VAMC side nav

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#29782] opened 2021-09-09 14:04 UTC
## What happened?

An editor archived two mobile facilities in Fayetteville Coastal, but they still show up on the left nav on the Locations page https://www.va.gov/fayetteville-coastal-health-care/locations/

https://prod.cms.va.gov/fayetteville-coastal-health-care/locations/fayetteville-va-mobile-clinic
https://prod.cms.va.gov/fayetteville-coastal-health-care/locations/fayetteville-2-va-mobile-clinic

We resolved this by disabling the menu items for these, but that shouldn't be necessary. 

## Steps to Reproduce

On a tugboat environment, 

1. Go to https://prod.cms.va.gov/fayetteville-coastal-health-care/locations/fayetteville-va-mobile-clinic and https://prod.cms.va.gov/fayetteville-coastal-health-care/locations/fayetteville-2-va-mobile-clinic and note that they are archived. 
2. enable the menu items for the two archived mobile clinics at Fayetteville Coastal by going to admin/structure/menu/manage/va-fayetteville-coastal-health-c and checking the two boxes in the screenshot below.

<details><summary>Screnshot</summary>

![Edit_menu_VA_Fayetteville_Coastal_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/132699419-eb18c727-b926-4fbf-b351-d852e090b72f.png)

</details>

3. Trigger content release in tugboat
4. Go to /fayetteville-coastal-health-care/locations/ in tugboat , and see that they show up on the left nav. 

## Desired behavior
Unpublished nodes should not show up on left nav. 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by gescobardev** [comment] 2021-09-28 00:53
@kevwalsh @swirtSJW We found that the query we are using for the facility side bar nav (see attached screenshot) doesn't make it easy to filter unpublished facilities.
Not quite sure how to filter `menuByName`. There is a field called `attribute` but not entirely sure what we can pass it or if it would even be useful in this case?
<details>
<summary>facilitySidebar.nav.graphql</summary>
<img width="1083" alt="Screen Shot 2021-09-27 at 7 19 16 PM" src="https://user-images.githubusercontent.com/84030819/135002856-41404e6e-cee4-4369-ae18-ab30f1653945.png">

</details>

We have 2 thoughts on this.
1. Could this possibly be filtered on your end? 
2. Can we instead use the `locationsListingPage` graphql data? (see attached screenshot) Since it looks like the facilities within `fieldOffice` are already filtered out. 

<img width="569" alt="Screen Shot 2021-09-27 at 8 09 48 PM" src="https://user-images.githubusercontent.com/84030819/135002349-43c99d4c-8d38-4d15-a4b0-d96ee5d19092.png">


cc @mpelzsherman

**Comment by swirtSJW** [comment] 2021-09-28 13:51
Interesting.  It seems related to this issue https://www.drupal.org/project/drupal/issues/2665320
I think this may be related to the permissions of the user we are using making the menu request.  If that user has the permission to see unpublished nodes then they will get the links.   Let me dig into this a bit more.   There may be a simple solution on our end.

**Comment by swirtSJW** [comment] 2021-09-28 17:17
This is blocked by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6561

**Comment by swirtSJW** [comment] 2021-09-28 21:58
I found a drupal module that adds the ability to query entity data from within the menu query.  
Here is a tugboat environment with that module installed
https://pr6568-evjtc4b1rljtu67clslvtg444yrbfygw.ci.cms.va.gov/graphql/explorer

and here is a query that roughly does what you need
```
{
  menuByName(name: "va-alexandria-health-care") {
    description
    name
    links {
      ...MenuItem
      links {
        ...MenuItem
        links {
          ...MenuItem
        }
      }
    }
  }
}

fragment MenuItem on MenuLink {
  expanded
  description
  label
  url {
    path
  }
  entity {
    ... on MenuLinkContent {
      linkedEntity(language_fallback: true, bypass_access_check: true) {
        ... on Node {
          entityPublished
          moderationState
        }
      }
    }
  }
}

```

Let me know if meets your needs and I will get it merged.

**Comment by swirtSJW** [comment] 2021-09-28 21:59
![image](https://user-images.githubusercontent.com/5752113/135171521-77fb3aae-38bb-4b79-b3fa-270557b3ee7b.png)

**Comment by gescobardev** [comment] 2021-10-08 17:24
Hi @swirtSJW ! I'm now switching back to focusing on this issue again and I'm running into a different issue this time around.
The module you added works! But I get an error for `"va-western-colorado-health-care" `and `"va-central-california-health-car"` (see image below)

example query:
```
{
  menuByName(name: "va-central-california-health-car") {
    description
    name
    links {
      ...MenuItem
      links {
        ...MenuItem
        links {
          ...MenuItem
        }
      }
    }
  }
}

fragment MenuItem on MenuLink {
  expanded
  description
  label
  url {
    path
  }
  entity {
    ... on MenuLinkContent {
      linkedEntity(language_fallback: true, bypass_access_check: true) {
        ... on Node {
          entityPublished
          moderationState
        }
      }
    }
  }
}
```



<img width="1300" alt="Screen Shot 2021-10-08 at 1 02 31 PM" src="https://user-images.githubusercontent.com/84030819/136596711-dcb55714-3c22-4f8d-a4f7-e8fa6d4ecef9.png">

Again, this only seems to happen with those 2 facilities. As you can see, the data is there but that internal server error gets thrown and causes problems.
Any clue as to why that is happening?

cc @mpelzsherman

**Comment by swirtSJW** [comment] 2021-10-11 15:18
This is odd.  I checked out the va-central-california-health-car menu to see if I could spot anything odd.   Nothing seems unusual about it.  I opened up all 22 nodes that are in the menu and they each seem fine
![image](https://user-images.githubusercontent.com/5752113/136814670-0c8ea7ae-44de-49f8-adfc-96b6e373ced2.png)

My first thought was maybe Central California was a big system and had too many facilities for this to handle, but it only has 4.   So that's not it.

I'll have to try running that query and see if anything useful appears in the logs to indicate what the problem might be.
Let me do some testing and I'll get back to you.

**Comment by swirtSJW** [comment] 2021-10-11 16:44
@gescobardev I think I've figured out the issue.   These two menus aren't 5 levels deep.  If I change the query to only going three levels deep, there is no error.
```
{
  menuByName(name: "va-central-california-health-car") {
    name
    description
    links {
      ...MenuItem
      links {
        ...MenuItem
          links {
            ...MenuItem
            links {
              label
              expanded
              description
              url {
                path
              }
            }
          }
        }
    }
  }
}

fragment MenuItem on MenuLink {
  expanded
  description
  label
  url {
    path
  }
  entity {
    ... on MenuLinkContent {
      linkedEntity(language_fallback: true, bypass_access_check: true) {
        ... on Node {
          entityPublished
          moderationState
        }
      }
    }
  }
}
```
I am guessing these are only 3 levels deep because they have not been fully populated yet by the VACM upgrade team.

It seems problematic to have the query have to know how deep the menu goes before it can do the query. An initial query that gets the depths of all the menus might be possible to include in the query that we already have that gets the name of the menus.

As is, there are probably three options
1.  Alter the query for these two to go less deep (not really favorable to do custom code for these two).  Easiest but high on the tech debt.
2.  Talk to the VAMC upgrade team to get them to partially populate these two systems so they have the necessary depth.  Simple solution, but still creates some tech debt risk as the menu query is always assuming a specific depth.
3. We have an all menu query that lists all the sidebar menus (I am not sure it is even being used).  We might be able to alter that to get the depth at the same time.

**Comment by mpelzsherman** [comment] 2021-10-12 21:10
@kevwalsh @mmiddaugh @gescobardev Do we need to show Draft facilities in Preview mode on the side nav? This should be spelled out in the AC. Thanks!

**Comment by swirtSJW** [comment] 2021-10-13 13:46
I am still working on this depth thing.   The error bubbles up in GraphQL  not within Drupal GraphQL but GraphQL itself.  

However it is triggered by something happening in `Drupal\menu_item_extras\`
```
User warning: GraphQL Interface Type `MenuLinkContent` returned `null` from it`s `resolveType` function for value: instance of Drupal\menu_item_extras\Entity\MenuItemExtrasMenuLinkContent. Switching to slow resolution method using `isTypeOf` of all possible implementations. It requires full schema scan and degrades query performance significantly. Make sure your `resolveType` always returns valid implementation or throws. in GraphQL\Error\Warning::warnOnce() (line 90 of vendor/webonyx/graphql-php/src/Error/Warning.php).
```

There is no issue that seems related in the issue queue for that module
https://www.drupal.org/project/issues/menu_item_extras?categories=All
I'm still debugging this.

**Comment by swirtSJW** [comment] 2021-10-13 21:45
Related to this, I did find the cause of these menu items getting broken and are working on a fix so that this kind of thing can not happen again as this would create a fatal error on the content-build.  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6658   Including this here so all can sleep well and night and not worry about mangled menu nightmares.  ;)

**Comment by indytechcook** [comment] 2021-11-03 19:35
Cross posting my comment on the other issue

We ran the `content-build` on https://test.prod.cms.va.gov with the current version and again with the the new branch.

|                                       | Cold Cache       | Warm Cache |
|---------------------------------------|------------------|------------|
| Current                               | 3 min 49.967 sec | 8.882 sec  |
| vamc-filter-side-nav-facilities-29782 | 3 min 51.868 sec | 8.938 sec  |

The difference is 1.901 seconds which is in acceptable range.

**Closed** 2021-11-03 20:33 UTC
Labels: bug, frontend, vsa-facilities, frontend-vamc
