### ISSUE TITLE
[Pension Module] Add flipper feature flags to frontend to use new pension module routes

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#85962] opened 2024-06-14 15:37 UTC

**Comment by aplatt-coforma** [comment] 2024-06-27 18:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/85962?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel @ToddWebDev

**Comment by aplatt-coforma** [comment] 2024-06-27 19:12
Duplicate of #86460

**Closed by aplatt-coforma** 2024-06-27 19:12 UTC
Labels: frontend, pension, engineering
