### ISSUE TITLE
Support reverse proxy timeouts within the form system

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#25398] opened 2021-05-28 21:44 UTC
## User Story

Currently, when a Veteran submits a form and there's a reverse proxy timeout, they see this message:
![timeout.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/18b5e9ff-8d8c-4d89-9ea8-b09c192dbd5e)

This is inaccurate, and doesn't provide them with any steps forward.

## Ask

Can we update this error message to be more useful and accurate? It should specify that it is a server error (VA.gov's fault) not a client error. It should also give them a step to take (resubmit, download a PDF, etc)

**Comment by ala-yna** [comment] 2021-05-28 21:45
Hi @caw310 and @cvalarida - I wasn't sure which of you this ticket should go to, so I added you both! Please reach out to @kevinmirc and @Dene-human if you have any questions. Thank you!

**Comment by SKasimow** [comment] 2022-01-25 20:16
@Dene-human think we can close this; looks like message was updated to this; can you let me know if I'm missing any info?

:![Screen Shot 2022-01-20 at 8.23.54 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/728ef0f4-9480-4033-8f9d-2562babe1d0a)

**Comment by Dene-human** [comment] 2022-01-25 20:53
@SKasimow I think it is ok to close if that is confirmed as the error as a result of a **reverse proxy timeout.**

**Comment by hdjustice** [comment] 2022-11-01 18:06
Closing this ticket

**Closed by hdjustice** 2022-11-01 18:06 UTC
Labels: design system, forms, 1010-team
