### ISSUE TITLE
<CAIA> Updates to static pages: VA Claim Exam | Change Your Address static pages

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#63317] opened 2023-08-08 18:28 UTC
## About your team

- **Team name:** VBA
-	**OCTO-DE product owner**: 
-	**Product manager**: 
-	**Designer**: 
- **Accessibility specialist**:
- **Content writer**: 
-	**Slack channel**:
 
### Describe what you need in a few sentences:

Updates to static pages:

- **Change Your Address In Your VA.gov Profile | Veterans Affairs** and 
- **VA Claim Exam (C&P Exam) | Veterans Affairs**

### Tasks
- [ ] Make to static pages

### Type of CAIA Support
Which areas of CAIA
- [x] Content
- [ ] Accessibility
- [ ] IA

### Update Instructions
**TBA** 

### Links
[https://www.va.gov/disability/va-claim-exam/](url)
[https://www.va.gov/change-address/](url)

**Comment by laurwill** [comment] 2023-08-15 04:10
This ticket is a dupe of [this other ticket](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/3?pane=issue&itemId=35384504) — closing out!

**Closed by laurwill** 2023-08-15 04:10 UTC
Labels: sitewide content, sitewide CAIA
