### ISSUE TITLE
[Tech Debt] 526/BDD: Where and Why Did Veterans Stop In the Form (SIP Data)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15689] opened 2020-11-02 20:22 UTC
## Issue Description
Update Sprint 38: We are reviving this story to get a new pass at the data and take advantage of some of the new error logging we have put into production since this was last looked at.

Anna already did an initial pass at where folks are stuck.  This story is for Anna/Ed (if he is around) to help create and work through stories related to errors causing veterans to pile up and get stuck on a specific form.

## Acceptance Criteria
- [ ] Investigate the top 10 or so issues and cross reference with the new metadata in SIP that shows the errors
- [ ] Work to create stories
- [x] Put this and the previous "snapshot" into the product folder somewhere
---

Previous Snapshot: ~Nov 10th
1 “/new-disabilities/follow-up/30”
1 “/disabilities/ptsd-781a-additional-events-0"
1 “/disabilities/ptsd-incident-support-1”
1 “/new-disabilities/ptsd-additional-incident”
1 “/disabilities/ptsd-incident-unit-assignment-2”
1 “/disabilities/ptsd-individuals-involved-2"
1 “/disabilities/ptsd-secondary-incident-support-0”
1 “/disabilities/ptsd-secondary-incident-unit-assignment-1"
1 “/disabilities/ptsd-secondary-incident-unit-assignment-2”
1 “/disabilities/ptsd-secondary-other-sources-1"
1 “/disabilities/ptsd-secondary-other-sources-help-0”
1 “/disabilities/ptsd-secondary-permission-notice-0"
1 “/new-disabilities/ptsd-781a-social-changes”
1 “/new-disabilities/ptsd-781a-physical-changes”
1 “/new-disabilities/ptsd-781a-mental-changes”
1 “/new-disabilities/follow-up/13"
1 “/new-disabilities/follow-up/16”
1 “/new-disabilities/follow-up/18"
1 “/new-disabilities/follow-up/43”
1 “/new-disabilities/follow-up/20"
1 “/new-disabilities/follow-up/25”
2 “/disabilities/ptsd-incident-support-additional-break-0"
2 “/disabilities/ptsd-incident-unit-assignment-1”
2 “/new-disabilities/ptsd-781a-upload”
2 “/disabilities/ptsd-secondary-authorities-0”
2 “/disabilities/ptsd-secondary-incident-date-1"
2 “/new-disabilities/ptsd-781a-changes-intoduction”
3 “/disabilities/ptsd-secondary-incident-unit-assignment-0"
3 “/new-disabilities/ptsd-781a-additional-changes”
3 “/new-disabilities/follow-up/14"
3 “/disabilities/ptsd-individuals-involved-questions-1”
3 “/disabilities/ptsd-incident-description-2"
4 “/adaptive-benefits”
4 “/new-disabilities/follow-up/9"
4 “/new-disabilities/follow-up/8”
4 “/disabilities/ptsd-secondary-other-sources-0"
4 “/new-disabilities/follow-up/11”
4 “/new-disabilities/follow-up/17"
4 “/disabilities/ptsd-additional-events-1”
4 “/disabilities/ptsd-incident-date-1"
5 “/retirement-pay-waiver”
5 “/new-disabilities/follow-up/10"
5 “/disabilities/ptsd-incident-location-1”
6 “/new-disabilities/ptsd-781-upload”
6 “/disabilities/ptsd-medals-1”
6 “/training-pay-waiver”
7 “/disabilities/ptsd-incident-description-1”
7 “/retirement-pay”
8 “/terminally-ill”
8 “/disabilities/ptsd-secondary-incident-location-0"
8 “/new-disabilities/follow-up/7”
9 “/disabilities/ptsd-secondary-incident-date-0"
10 “/aid-and-attendance”
10 “/disabilities/ptsd-secondary-incident-description-0"
10 “/housing-situation”
12 “/disabilities/ptsd-additional-events-0"
12 “/disabilities/ptsd-incident-support-0”
13 “/new-disabilities/follow-up/6"
14 “/new-disabilities/ptsd-intro”
15 “/new-disabilities/walkthrough-781a-choice”
15 “/new-disabilities/additional-remarks-781”
15 “/training-pay”
16 “/new-disabilities/ptsd-intro-to-questions”
17 “/disabilities/ptsd-individuals-involved-0"
17 “/disabilities/ptsd-secondary-upload-supporting-sources-0”
18 “/new-disabilities/ptsd-type”
18 “/disabilities/ptsd-secondary-upload-supporting-sources-choice-0”
19 “/disabilities/ptsd-individuals-involved-questions-0"
20 “/new-disabilities/follow-up/5”
24 “/disabilities/ptsd-incident-location-0"
27 “/new-disabilities/follow-up/4”
30 “/disabilities/ptsd-incident-description-0"
34 “/separation-pay”
38 “/disabilities/ptsd-medals-0"
40 “/how-claim-exams-work”
40 “/disabilities/ptsd-incident-unit-assignment-0"
42 “/new-disabilities/follow-up/3”
44 “/review-veteran-details/military-service-history/federal-orders”
49 “/disabilities/ptsd-incident-date-0”
51 “/payment-information”
51 “/pow”
51 “/additional-disability-benefits-summary”
56 “/disabilities/orientation”
68 “/new-disabilities/walkthrough-781-choice”
72 “/supporting-evidence/summary”
74 “/contact-information”
75 “/new-disabilities/follow-up/2”
78 “/alternate-names”
106 “/new-disabilities/follow-up”
110 “/individual-unemployability”
121 “/additional-disability-benefits”
122 “/disabilities/summary”
163 “/new-disabilities/follow-up/1”
188 “/supporting-evidence/orientation”
191 “/va-employee”
276 “/review-veteran-details/combat-status”
284 “/new-disabilities”
308 “/disabilities/rated-disabilities”
331 “/veteran-information”
463 “/review-and-submit”
468 “/fully-developed-claim”
505 “/supporting-evidence/private-medical-records-release”
519 “/claim-type”
709 “/supporting-evidence/evidence-types”
777 “/review-veteran-details/military-service-history/reserves-national-guard”
826 “/supporting-evidence/additional-evidence”
948 “/new-disabilities/follow-up/0”
1019 “/supporting-evidence/va-medical-records”
1100 “/supporting-evidence/private-medical-records”
1157 “/review-veteran-details/military-service-history”
1276 “/new-disabilities/add”

**Comment by annaswims** [comment] 2020-11-10 21:17
https://github.com/department-of-veterans-affairs/vets-api/pull/5217 fixed the primary issue for “/review-veteran-details/military-service-history”

**Comment by annaswims** [comment] 2020-11-10 21:29
note to self - queries for digging in more. 

````
start_date = 7.days.ago.utc
end_date = 1.day.ago.utc
return_url = '"/new-disabilities/add"'
in_progress_forms = InProgressForm.where('updated_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day) .where(form_id: '21-526EZ')
results = in_progress_forms.where(%Q{CAST(metadata -> 'return_url' AS text) = '#{return_url}'}).limit(10)
results.collect {|r| r.metadata}
````

**Comment by annaswims** [comment] 2020-11-11 19:26
Places people get stuck or abandon and how we can measure it:
(rake tasks after  https://github.com/department-of-veterans-affairs/vets-api/pull/5267 is merged)

# They leave the in progress form 
either by choice, frustration, or need to gather evidence:
  - Choice/exhaustion/need more info: `bundle exec rake form_progress:abandon_url[21-526EZ,2020-10-06,2020-11-06]`
 -  Frustration/stuck with validation error -  `bundle exec rake form_progress:error_url[21-526EZ,2020-10-06,2020-11-06]`
 - Error  on submit -[grafana]( http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?viewPanel=18&orgId=1&from=now-7d&to=now) or [FE validation error in Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/241/events/?query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdisability%2Ffile-disability-claim-form-21-526ez%2Freview-and-submit&sort=freq&statsPeriod=14d)
- BE validation error - [sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/?project=3&query=transaction%3AV0%3A%3ADisabilityCompensationFormsController%23submit_all_claim&sort=freq&statsPeriod=14d)
- EVSS submission error [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/?project=3&query=assigned%3Ame%20transaction%3ASidekiq%2FEVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim&sort=freq&statsPeriod=14d), [grafana](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?viewPanel=8&orgId=1&from=now-7d&to=now)



Grafana for counts, Sentry for error details

..to be coninued

**Comment by annaswims** [comment] 2020-11-11 21:07
[slack
![sankeymatic_600x600 (2)](https://user-images.githubusercontent.com/19188/98864317-aed61900-2437-11eb-8e0f-d8a15f109d9f.png)
](https://dsva.slack.com/archives/C5AGLBNRK/p1603999885288700)

This is forms that have been updated/submitted within the last month, excluding today (as of October 29)

graph source made with http://sankeymatic.com/build/
```
Begin Form 526 [33440] Submit Form
Submit Form [33440] Success #4aa564
Begin Form 526 [3083] In Progress
In Progress [3083] Submit Form
Submit Form [3083]  Failed Submissions #e59393
Begin Form 526 [12872] In Progress
In Progress [1276] /new-disabilities/add  #f9c642
In Progress [1157] /review-veteran-details/military-service-history  #f9c642
In Progress [1100] /supporting-evidence/private-medical-records  #f9c642
In Progress [1019] /supporting-evidence/va-medical-records  #f9c642
In Progress [948] /new-disabilities/follow-up/0   #f9c642
In Progress [826] /supporting-evidence/additional-evidence   #f9c642
In Progress [777] /review-veteran-details/military-service-history/reserves-national-guard   #f9c642
In Progress [709] /supporting-evidence/evidence-types   #f9c642
In Progress [519] /claim-type   #f9c642
In Progress [505] /supporting-evidence/private-medical-records-release   #f9c642
In Progress [468] /fully-developed-claim  #f9c642
In Progress [463] /review-and-submit  #f9c642
In Progress [331] /veteran-information  #f9c642
In Progress [2774] Other   #f9c642
```

**Comment by annaswims** [comment] 2020-12-29 21:45
@Mottie when I see `"error_message"=>"vets_server_error: Unprocessable Entity", ` in the metadata after a person has tried to submit the form, can you save the details instead?  

Also, I used to see something in `metadata -> 'submission' -> 'errors` but I don't now. Any idea why?

**Comment by Mottie** [comment] 2020-12-29 22:44
> can you save the details instead?

It looks like we're saving the `req.statusText` in two places https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/config/submitForm.js#L46-L48

So the data you want is in the `req.details`? I can take care of it when I return next week

> I used to see something in `metadata -> 'submission' -> 'errors` but I don't now. Any idea why?

Nope, not a clue. The `errors` should contain the form validation errors, right?

**Comment by edmangimelli** [comment] 2020-12-29 23:59
@annaswims memorialized this [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/engineering/Where%20and%20Why%20Did%20Veterans%20Stop%20In%20the%20Form)

**Comment by annaswims** [comment] 2020-12-31 15:58
yeah, @Mottie `req.details` should have the interesting bits.

Thanks @edmangimelli !

**Comment by Mottie** [comment] 2021-01-05 15:45
> `req.details` should have the interesting bits.

This update will be available later today!

**Comment by annaswims** [comment] 2021-01-29 17:34
@kevinstachura / @chrvalla - Can we talk about why people might stop the form at these places? It it usability/bug/a challenging question?

"/pow"=>40, 
"/new-disabilities/follow-up"=>53, 
"/additional-disability-benefits"=>54, 
"/individual-unemployability"=>57, 
"/disabilities/summary"=>66, 
"/supporting-evidence/summary"=>70, 
"/review-veteran-details/combat-status"=>99, 
**"/va-employee"=>102,**  - What?  It's an easy y/n question.  Is there a bug? Maybe related to inflection
"/veteran-information"=>119, 
"/disabilities/rated-disabilities"=>126, 
"/supporting-evidence/orientation"=>126, 
"/review-veteran-details/military-service-history"=>248, 
"/supporting-evidence/private-medical-records-release"=>259, 
**"/fully-developed-claim"=>282,** 
**"/claim-type"=>293,** 
"/review-veteran-details/military-service-history/reserves-national-guard"=>339, 
**"/review-and-submit"=>357,**  - I'm assuming these are mostly submission errors.
"/supporting-evidence/evidence-types"=>365, 
"/supporting-evidence/additional-evidence"=>537, 
"/supporting-evidence/va-medical-records"=>596, 
"/supporting-evidence/private-medical-records"=>598, 
**"/new-disabilities/follow-up/NN"=>711,**
**"/new-disabilities/add"=>824**

**Comment by annaswims** [comment] 2021-01-29 21:14
@kevinstachura and I had a chat this afternoon and he had 7 potential design/research issues he was going to write up. 

I looked into the data of the people that stopped at "va-employee" and I couldn't find a way they got stuck, so I'm guessing it's not a bug.  I'm going to call this issue done.

**Closed by annaswims** 2021-01-29 21:14 UTC
Labels: 526, BDD, backend, tech-debt, vsa-benefits

**Comment by vhenry07** [comment] 2021-01-29 21:35
Thanks Anna.
Veronica Henry | PMP
Sr. Product Manager
| *mobile* 702-509-6192
| *e.* vhenry@governmentcio.com
