### ISSUE TITLE
Find a VA Form: FE design bug: double underline in blue Frequently Used VA Forms boxes

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#22307] opened 2021-03-29 17:20 UTC
## What happened?
_The line is rendering as dashed double lines in Edge. On Chrome, it is rendering as an extra thick, bolded line. Both are bugs. Per Ryan Thurlwell, both should look like how it is rendering in Firefox, as a simple 1 px rule. This is not affecting functionality as far as I can tell, so please triage accordingly. _

## Specs:
- Device: (Mac and HP)
- Browser: (e.g. Firefox, Edge, Chrome)

## Steps to Reproduce
- URL:https://www.va.gov/find-forms/
- View in Firefox, Chrome, and Edge.

### Edge
![image](https://user-images.githubusercontent.com/43381063/112874900-7d31b780-9091-11eb-9b61-780bb7e12d20.png)

### Chrome on default view
![image](https://user-images.githubusercontent.com/43381063/112875048-afdbb000-9091-11eb-8445-9c90be466a0b.png)

### Chrome after search - shows same FE bug as Edge (double line)
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/4ea9f78e-35b1-4269-95f7-771d3f1d0ff7)

### Firefox - this is rendering correctly
![image](https://user-images.githubusercontent.com/43381063/112875200-e0bbe500-9091-11eb-8f6a-3c6dab1b6d4b.png)

## Desired behavior
_See Acceptance Criteria._

## Acceptance Criteria
- [ ] _The line used in the blue boxes should use a 1 px rule, the way it shows on this Firefox screenshot._

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by johnhashva** [comment] 2021-03-31 13:20
@MarciMcGuireGCIO + @zacharymorel when you tackle this one, could you also align the Read more > and Apply online > links to the bottom of the blue box -- as seen here in the Campaign Landing page.
<img width="849" alt="Screen Shot 2021-03-31 at 9 17 26 AM" src="https://user-images.githubusercontent.com/63107147/113150521-2dbec900-9202-11eb-9e30-109a0198637b.png">

**Comment by MarciMcGuireGCIO** [comment] 2021-03-31 13:22
@johnhashva Thank you for adding the addition info!

**Comment by jenniferlee-dsva** [comment] 2021-04-05 18:41
Added new Chrome screenshot ^. (It looks like after you do a search, for whatever inexplicable FE behavior, the lines become doubled, same bug that's on Edge.)

**Comment by johnhashva** [comment] 2021-04-05 19:20
I'm unable to duplicate this in Chrome/Mac:
<img width="913" alt="Screen Shot 2021-04-05 at 3 11 15 PM" src="https://user-images.githubusercontent.com/63107147/113614977-41629900-9621-11eb-96bf-47e4d549029e.png">

I DO see this on Edge/PC:

<img width="643" alt="Find a Form-Edge Issue" src="https://user-images.githubusercontent.com/63107147/113615864-67d50400-9622-11eb-8fb4-a13adaa13390.png">

**Comment by zacharymorel** [comment] 2021-04-05 19:46
On Mac chrome I was unable to reproduce: 
![Screen Shot 2021-04-05 at 3 37 14 PM](https://user-images.githubusercontent.com/26075258/113618681-044cd580-9626-11eb-939f-c66ddf24b180.png)

On PC Edge I was unable to reproduce:
![Screen Shot 2021-04-05 at 3 16 09 PM](https://user-images.githubusercontent.com/26075258/113618732-1595e200-9626-11eb-94e6-cde0a2e75476.png)

**Comment by zacharymorel** [comment] 2021-04-05 19:50
NOTE: The class used here is **vads-u-border-color--primary** out of the VA design system.

**Comment by MarciMcGuireGCIO** [comment] 2021-04-05 19:52
@zacharymorel does the class or any other attribute change between the search & result states?

**Comment by zacharymorel** [comment] 2021-04-05 19:56
Nope, it stays the same. Also, the **hr** border remains 1 px and solid. I think we _could_ have discovered a browser difference between machines/versions.

**Comment by jenniferlee-dsva** [comment] 2021-04-06 14:22
@zacharymorel - on your PC/Edge screenshot, it does look like double lines to me. (Designer eyes.)  The images I captured were on both Mac (personal computer) and GFE (PC). So I can only report and upload the screenshots I took when I encountered them. 

Perhaps worth asking in the Design channel or with Nick Sullivan if anyone else has encountered similar issue. This could be a Forms thing, but it could be a design system thing. 🤷‍♀️

**Comment by MarciMcGuireGCIO** [comment] 2021-04-06 14:35
Here is some browser compatibility info on styling <hr> elements:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr

**Comment by MarciMcGuireGCIO** [comment] 2021-04-06 15:25
This may be a browser compatibility thing and needs more research.  Since it's not impacting users, I am moving it down below the outstanding 508 issues.

**Comment by MarciMcGuireGCIO** [comment] 2021-09-14 12:14
We are no longer able to reproduce this issue, and believe it to be resolved.   Recent changes to the blue boxes may have inadvertently corrected this problem.

**Closed by MarciMcGuireGCIO** 2021-09-14 12:14 UTC
Labels: bug, frontend, needs-grooming, vsa-decision-tools, dt-find-va-form
