### ISSUE TITLE
Configuration of Argo CD to manage Sign-in-Service deployment

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#55630] opened 2023-03-23 15:21 UTC
## Description
Point [Argo CD](https://argocd.vfs.va.gov/) to deploy/update Sign-in-Service in EKS. This can't be done until manifests are created for SiS.

repos:
- https://github.com/department-of-veterans-affairs/sign-in-service-infra (will need pipelines to plan/apply eks infra)
- https://github.com/department-of-veterans-affairs/sign-in-service (will need pipelines to build image)

# Acceptance Criteria 
- [ ] Point [Argo CD](https://argocd.vfs.va.gov/) at Sign-in-Service

**Comment by rileyanderson** [comment] 2023-04-26 15:47
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/56574. Closing

**Closed by rileyanderson** 2023-04-26 15:47 UTC
Labels: Identity, identity-devops
