### ISSUE TITLE
[Development] BDD: Handle separation location

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#10034] opened 2020-06-10 17:08 UTC
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Placeholder: Ensure we are passing separation location data correctly from the FE and are passing it to EVSS

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment] 2020-06-17 17:54
Duplicate of #10311.

**Closed by luke-gcio** 2020-06-17 17:54 UTC
Labels: backend, development, vsa-benefits
