### ISSUE TITLE
[FE] Profile, DD:  Update screen reader to so user hears "updating your preferences" instead of "dimmed"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24954] opened 2021-05-19 17:02 UTC
## Background
Following work on #23168 a minor issue was noted regarding the screen reader. Instead of "dimmed" the user should hear "updating your preferences" or something similar to indicate to the user that the section is in a loading state as their information is being saved:

_- Instead of "dimmed", screen reader users should hear "updating your preferences" or something more descriptive to indicate a loading state_

 [See Josh's comments and supporting video for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23168#issuecomment-844233581)

## Tasks
- [ ] Update screen reader functionality when information is being saved to be more descriptive (instead of the user hearing "dimmed")
- [ ] This update should apply to all contact info fields in profile as well as edit fields on Direct Deposit

**Comment by ajakabcin** [comment] 2021-08-06 20:42
@tmitchellgcio I'm going to move this to next sprint since we want to focus on progressing the radio button work

**Comment by tmitchellgcio** [comment] 2021-08-18 18:30
@joshkimux It says "Saving Changes", but afterwards shows, "You are on a button, this button is dimmed" I wasn't sure of the right way to handle this. Should I update the "Saving Changes" to be "Updating your preferences"? I couldn't find a way to override voiceover saying it's dimmed other than making the voiceover say "disabled" using aria-disabled="true".

**Comment by joshkimux** [comment] 2021-08-18 19:07
@tmitchellgcio , great question! I'd recommend exploring methods that don't involve overriding voiceover or the button itself. 

A possible approach could be to replace the button with a loading message through an aria live region (set to polite). That way the button itself won't become disabled and both sighted and screen reader users can receive messaging that information is currently saving.

**Comment by erikphansen** [comment] 2021-08-18 20:28
@joshkimux FYI, I think these issues are caused by the LoadingButton component we are using https://github.com/department-of-veterans-affairs/vets-website/blob/280a528d200cf2635582fc56f7effaea359729a5/src/platform/site-wide/loading-button/LoadingButton.jsx. That button is used in multiple places across the site so likely extend beyond the Profile.

Totally removing the button from the DOM while the API call is in flight is preferable to disabling the button?

**Comment by joshkimux** [comment] 2021-08-18 20:41
@erikphansen , thank you for pulling this up! Let me test this one more time, reading the component, there _should_ be loading text announced which I did not hear on my first run through. 🙏

**Comment by joshkimux** [comment] 2021-08-19 14:54
@erikphansen Look at that! I didn't see this in my first run through, but loving the "saving changes" update provided to screen reader users here 🥳  

Closing this out!

<img width="1020" alt="Screen Shot 2021-08-19 at 10 53 52 AM" src="https://user-images.githubusercontent.com/14154792/130090996-58c26e2c-81df-4391-94c9-521d830f3eab.png">

**Closed by joshkimux** 2021-08-19 14:54 UTC
Labels: frontend, blocked, vsa-authenticated-exp, profile, direct deposit, planned-work
