### ISSUE TITLE
[Backend] Investigate missing planned facility field from some 1010CG PDF attachments

### ISSUE THREAD

**Issue by dnalbach** [department-of-veterans-affairs/va.gov-team#28109] opened 2021-07-30 14:38 UTC
CSP staff brought an issue to the CARMA team’s attention that was reported to the VSA Caregiver product team. The 10-10CG PDF that generates after some Veterans and caregivers submit an online application is missing the typed name of the VAMC or clinic where the Veteran receives or plans to receive health care services. They provided us with 8 examples across 2 locations.

We need to investigate how and why this is suddenly happening, and whether it has any connection to recent changes in anticipation of making this planned facility field dynamic for the facility selector feature.

**Comment by dnalbach** [comment] 2021-07-30 14:45
I verified that the feature toggle for the vets-api controlling whether to pull the facility list live from the API or use the JSON schema is indeed turned off as expected. While off, the JSON schema should continue to be used as before.

**Comment by dnalbach** [comment] 2021-07-30 14:50
I pulled the success log entry via CloudWatch query for the four Ann Arbor cases and they have the following submission timestamps:

- 2021-07-23T20:20:26.030343Z
- 2021-07-24T02:29:48.613650Z
- 2021-07-26T17:02:24.799011Z
- 2021-07-26T19:32:44.661636Z

All four of these submissions were made without errors on the vets-api side, and the attachment job logs also look successful without error.

It does not appear that there are any server errors occurring during the creation of the PDF or the submission to CARMA. Whatever is causing this one field to be empty does not appear to be raising errors.

**Comment by tchrisdyer** [comment] 2021-08-04 14:16
Can't reproduce at the moment. Need to meet with Kevin who is out on PTO this week. Will put in blocked for now.

**Comment by tchrisdyer** [comment] 2021-08-10 20:50
Kevin and Daniel found the issue. So will close this ticket and open a new ticket for the fix.

The functionality to create the PDF exists in two places:
1. Download
2. Send to CARMA

It's working in Download but on in the job that sends to CARMA.

According to Kevin:

> We need to make sure the deliver attachment job also generates a label and sends it. We should also ensure we have a default value (whatever was provided in the payload)
> 
> The download PDF doesn’t use a background job. It’s an API req/res in process. When a submission is done, it triggers a job to send attachments. And in that job the PDF is generated. So it’s generated in two places
> 
> The PDF generation for the user has the label passed as an option. The PDF generation that goes to CARMA doesn’t have a label passed to it.

**Closed by tchrisdyer** 2021-08-10 20:50 UTC
Labels: vsa, vsa-caregiver
