### ISSUE TITLE
Triage Process - Access and SNOW Training for 2 Team Members

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38310] opened 2022-03-09 20:23 UTC
## Acceptance Criteria
- [x] Get access to SNOW for a minimum of 2 team members (Chris Horton can help) (Adrian)
    - Gaurav
    - Kanchana
    - Adrian
- [x] Attend a SNOW overview meeting with CHIP team/Chris Horton (Sarah can facilitate) (Lori)
- [x] Get a new label/category for our team's SNOW tickets created (Lori)
- [x] Confirm access to edit and update tickets assigned to us
- [x] Reach out to Contact Center with our new process (confirm with Stephen) (Lori)

**Comment by sarahknoppA6** [comment] 2022-03-23 15:13
I would like to recommend we modify and split this ticket because it is hard to complete as is. 
New ticket- Access and SNOW training for 2 team members
Criteria: 
- a minimum of 2 team members to get access to SNOW (strongly suggest Adrian is one of them)
- attend a SNOW overview meeting with CHIP team/Chris Horton (Sarah can facilitate)
- get a new label/category for our team's SNOW tickets created 
- confirm access to edit and update tickets assigned to us

2nd ticket: Document the Triage Process
- draft initial mural of triage statuses
- meeting with Chris Horton, Katie Roach, Allison S. to further define triage statuses and paths
- determine next steps to document and fully cross-train team on triage (to be completed in future tix)

**Comment by loripusey** [comment] 2022-03-23 17:20
I split into 2 tickets @sarahknoppA6

**Comment by acrollet** [comment] 2022-04-07 17:16
I've been added to the group and requested that @randomsync and @kanchanasuriya be added.

**Comment by acrollet** [comment] 2022-04-07 17:20
Confirmed access to edit/update tickets.

**Comment by acrollet** [comment] 2022-04-07 17:23
@randomsync & @kanchanasuriya have been added.

**Comment by loripusey** [comment] 2022-04-11 14:56
Had meeting with Chris Horton on 4/7, I now have access to SNOW.
Have meeting with Katherine Shelor on 4/13 regarding whether CIE should have its own SNOW Assignment Group or if we should use the eCheckinAPI one that is used by CHIP.

**Comment by loripusey** [comment] 2022-04-20 14:37
Submitted new assignment group form to Rene Kinsey for approval on 4/18; after I get approval I will submit the SNOW ticket requesting the group be created.

**Comment by loripusey** [comment] 2022-04-21 16:15
Received approval for new assignment group on 4/21
Submitted SNOW general request to create new assignment group on 4/21

**Closed** 2022-04-25 15:04 UTC
Labels: HCE-Checkin
