### ISSUE TITLE
[Data/FE/Testing] Reproduce and Diagnose Start Button Issue (Mobile)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61314] opened 2023-07-03 15:51 UTC
As a Veteran, I would like to be able to fill out the 1010-EZ form on my mobile phone so that I can quickly and easily apply for the VA healthcare benefits that I have earned.

- [x] - Determine what mobile Browsers users are having issues on
- [x] - Test against those browsers
- [x] - Come up with solution, either with JS replacements, or a notification for users to update their browser
- [x] - See if there is a front end solution (maybe reach out to platform team)
- [ ] - Work with Benefits group to divide and conquer (as needed)

**Browser Checklist (list of recent browsers with issues):**

**Mobile Safari**
- [x] 16.3
- [x] 15.3
- [x] 15.5
- [x] 15.6
- [x] 13.1.1
- [x] 13.1.2
- [x] 15.6.1
- [x] 15.6.3
- [x] 15.6.4

**Chrome Mobile**
- [x] 102.0.0.0
- [x] 103.0.0.0
- [x] 104.0.0.0
- [x] 105.0.0.0
- [x] 106.0.0.0
- [x] 107.0.0.0
- [x] 108.0.0.0
- [x] 109.0.0.0
- [x] 110.0.0.0
- [x] 110.0.5481.63
- [x] 74.0.3729.136
- [x] 80.0.3987.149
- [x] 83.0.4103.106
- [x] 85.0.4183.101
- [x] 90.0.4430.210
- [x] 94.0.4606.85
- [x] 96.0.4664.104
- [x] 96.0.4664.61
- [x] 97.0.4692.98
- [x] 99.0.4844.88

**Chrome Mobile iOS**
- [x] 104.0.5112.99
- [x] 109.0.5414.112
- [x] 110.0.5481.114
- [x] 110.0.5481.83

**Firefox Mobile**
- [x] 104

-----------------------------------------------------
We'll make a separate story for: 
- Make/suggest fix
- Test
- Go through review process
- Release to Prod

Matt L: Benefits Team 1 - Robin Garrison and his team are going to continue to track every single FE error through June.We were seeing the the same or similar errors on the load and login from our form as they are with their form.

**Comment by mkerns1** [comment] 2023-07-17 15:39
Notes for findings can be found here: https://docs.google.com/spreadsheets/d/1WiHzmVTWjCTptCyP2QGeXdut8ElHem-wCba-31wxi2M/edit?usp=sharing.

Overview:
I've conducted extensive manual testing but couldn't replicate the reported problem with the start form button. It's possible the issue is intermittent or influenced by specific user environments. To address this, I recommend gathering user feedback, implementing automated tests, enhancing logging and monitoring, collaborating with development, and continuing to monitor during regression testing. My commitment to ensuring application quality remains steadfast, and I'm eager to work together on resolving this matter.

**Comment by emily-brown34** [comment] 2023-07-17 15:41
@hdjustice @alexseelig

**Closed** 2023-07-31 15:46 UTC
Labels: frontend, backend, 1010-team, 1010-ez, 1010-analytics, 1010-bug
