### ISSUE TITLE
Education rewriting: Yellow Ribbon schools

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2612] opened 2019-10-21 15:24 UTC
@DanielleSoCompany commented on [Fri Jun 21 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039)

**What's needed:**

- Create a new branch/PR for this work for "education-rewriting-yellow-ribbon." We're going to be presenting the concept to SMEs first, and we need to wait for the new August rates before we fill in all the tables, so we want to make sure it's in a separate PR so as not to hold up the rest of the Education section.

- Create 2 new pages. URLs will be:
   - /education/about-gi-bill/post-9-11/yellow-ribbon-program/participating-schools/
   - /education/about-gi-bill/post-9-11/yellow-ribbon-program/participating-schools-alabama/

- On /education/about-gi-bill/post-9-11/yellow-ribbon-program/participating-schools/, please add:

   - H1: Yellow Ribbon schools
   - Draft intro text: Find out if your school takes part in the Yellow Ribbon Program. This program can help you pay for higher out-of-state, private, or graduate school tuition that the Post-9/11 GI Bill doesn't cover.
  - Draft text beneath intro: Click on the state or territory where your school is located to find the list of current Yellow Ribbon Program participating schools.
  - Then add a list of links based on those listed here: https://www.benefits.va.gov/GIBILL/yellow_ribbon/yrp_list_2018.asp. Break up the list with "States beginning with LETTER to LETTER" (i.e., States beginning with A to C) and then "U.S. territories" in a way that fairly evenly distributes the number of links in any one list and keeps lists to about 7 to 10 links max.

- On /education/about-gi-bill/post-9-11/yellow-ribbon-program/participating-schools-alabama/, please add:
   - H1: 2019 to 2020 Yellow Ribbon schools in Alabama 
   - intro text: Get information about Alabama schools participating in the Yellow Ribbon program for the 2019 academic year. 
  - First H2: Currently participating Yellow Ribbon schools by location
  - Tables: Recreate the table from https://www.benefits.va.gov/gibill/yellow_ribbon/2018/states/al.asp. But break it up by location as follows (with H3s above the tables):
    - Birmingham (can leave out "location" column)
    - Huntsville (can leave out "location" column)
    - Mobile (can leave out "location" column)
    - Montgomery (can leave out "location" column)
    - Other locations (need "location" column)
  - Second H2: Participating schools in past years
  - Copy: Learn what Alabama schools participated in the Yellow Ribbon Program in past years:
  - Links:
     - [Yellow Ribbon schools in Alabama in 2017 to 2018](https://www.benefits.va.gov/gibill/yellow_ribbon/2017/states/al.asp)
    - [Yellow Ribbon schools in Alabama in 2016 to 2017](https://www.benefits.va.gov/gibill/yellow_ribbon/2016/states/al.asp)
    - [Yellow Ribbon schools in all states in 2015 to 2016, and earlier](https://www.benefits.va.gov/GIBILL/yellow_ribbon/yrp_list_2015.asp)

---

@RLHecht commented on [Fri Jun 21 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-504611656)

@DanielleSoCompany The participating schools page is ready for you.
https://github.com/department-of-veterans-affairs/vagov-content/pull/480

---

@RLHecht commented on [Fri Jun 21 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-504617621)

@DanielleSoCompany Both pages are now ready for you.
https://github.com/department-of-veterans-affairs/vagov-content/pull/480

---

@RLHecht commented on [Mon Aug 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-520451318)

@Karak888 @AnneHurley The next step in this ticket what that the concept would be presented to the SMEs and we needed to add in August rates to complete the tables. There is no note on here saying that was done before the transition so I'm not sure where this stands. Who would we check with?

---

@Karak888 commented on [Mon Aug 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-520505568)

@peggygannon are you familiar with this one by chance? Thanks

cc:  @RLHecht @AnneHurley 

---

@RLHecht commented on [Tue Oct 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-542348214)

@AnneHurley @mnorthuis This is the other issue we were discussing today. Looks like it's still awaiting discussion with SMEs. Anne is this something you should follow up with Jen on?

---

@AnneHurley commented on [Tue Oct 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19039#issuecomment-542350961)

@jenniferlee-dsva Can you and I regroup on this issue? This and the other education rates pages appear to not have been shared with SMEs yet for their feedback. I'll tag you on the other ones as well and then when you are back in let's talk next steps. (thanks @RLHecht  and @mnorthuis )

**Comment by Karak888** [comment] 2019-10-21 15:28
Just FYI this is a copy for referencing ticket "Education rewriting: Yellow Ribbon schools **#19039"**

**Comment by RLHecht** [comment] 2019-10-23 16:20
@AnneHurley 

Heroku previews: https://vagov-content-pr-480.herokuapp.com/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/participating-schools/
https://vagov-content-pr-480.herokuapp.com/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/participating-schools-alabama/

**Comment by Karak888** [comment] 2019-10-23 17:18
@jenniferlee-dsva to review from @AnneHurley note.

**Comment by AnneHurley** [comment] 2019-11-08 17:50
[Yellow Ribbon updates from SMEs]
(https://app.zenhub.com/files/133843125/8ee443c3-6da6-4f86-8e04-9ba91d7dd6b6/download)

@mnorthuis @peggygannon @Karak888 
Here's the updated copy for Yellow Ribbon participating schools, for when we decide the IA.

**Comment by AnneHurley** [comment] 2019-11-08 17:53
Note from @jenniferlee-dsva re thoughts on IA; note @mnorthuis it sounds like you can make this call:

Clarification:
<<Jen is concerned that having Yellow Ribbon Schools as a separate page will introduce possible confusion, because it can't live "under" the main Yellow Ribbon page because the latter is already three levels/clicks down.>>

Not really a confusion issue, but thinking about near future state of flattened nav IA (which won't allow child pages below L3).

Since a) we are not going to migrate the 50 individual state table pages into the hub and b) only bring over the list of links pointing to each state table (on benefits.va.gov), I propose incorporating that links content and contextual intro copy as a new section on our current live Yellow Ribbon program page. Big caveat here being - could it be done in a way that makes sense and not difficult to find?

Few ideas is to use our "On this page" jump links at the top like we do here: http://preview-prod.vfs.va.gov/preview?nodeId=1013

The current H2s under the "Learn more..." section are actually subtopics of the "Learn more..." H2 and should be H3s.

That ^ means, that we might be able to add another H2 after or before the "Learn more..." H2 for participating schools -- like... 'Find/look up what schools offer Yellow Ribbon funding for tuition matching' or whatever. [And if needed using accordions for states by alpha groups?]

I think the 'What benefits can I get through...' H2 content is actually duplicative of the intro, and actually more specific and clearer, so there might be an opportunity there as well to eliminate this H2 and simply incorporate this language into the intro text or replace some of it.

This would be easier visually, so I'll upload an annotated screenshot later.

Longer term solution is to have a sortable/filterable table component in Drupal that we can migrate the state table info into, as its own 'tool' page.

@mnorthuis - leave you to recommend whether it would be better in terms of IA:

to create a separate participating schools page now (that later - no available time frame yet - turns into a table page;
or to combine this info with the main YRP info for now, since we don't have that dynamic table solution

**Comment by Karak888** [comment] 2019-11-13 18:58
@jenniferlee-dsva and @AnneHurley to have a discussion and figure things out!

**Comment by mnorthuis** [comment] 2019-11-13 22:46
Left my feedback in the other YR issue - my recommendation is to add links/combine this info into main YR page already in our hub.

**Comment by AnneHurley** [comment] 2019-11-15 01:10
@mnorthuis  Where is the other Yellow Ribbon issue? For now here is what I recommend for the revised current Yellow Ribbon page.
[Yellow Ribbon page revise to include accordion/section of schools](https://app.zenhub.com/files/133843125/d059b80e-18c7-416b-b96c-ed397f63868f/download)
@jenniferlee-dsva  for your review and @RLHecht  for copyedit

**Comment by AnneHurley** [comment] 2019-11-15 19:09
@RLHecht @jenniferlee-dsva  

Add to main Yellow Ribbon Program page, as H2 under subway map:

H2: Does my school participate in the Yellow Ribbon Program?

Text: 

There are two ways to find out if your school participates in the program. You can use the GI Bill Comparison Tool, or you can search by state or territory. 

Use the GI Bill Comparison Tool [https://www.va.gov/gi-bill-comparison-tool].
Search for your school by location below.

**Comment by RLHecht** [comment] 2019-11-18 17:48
@AnneHurley These additions have been added to the Yellow RIbbon page in Drupal. Preview link: preview-prod.vfs.va.gov/preview?nodeId=936

**Comment by AnneHurley** [comment] 2019-11-18 17:56
[Yellow Ribbon Program page from Drupal-for SME review]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/3859972/Yellow.Ribbon.Program.page.from.Drupal-for.SME.review.docx)
@RLHecht  @jenniferlee-dsva  @Karak888  I've sent this to the SMEs for their final review.

**Comment by AnneHurley** [comment] 2019-11-19 18:43
@jenniferlee-dsva  @Karak888 @RLHecht 
I received SME approval from Tammy and Luke today, and we are good to push this live.

**Comment by RLHecht** [comment] 2019-11-19 18:47
@peggygannon or @jenniferlee-dsva can you please review this page in Drupal and publish if all looks good. I had to rebuild a lot of it to fix some H2s and accordions and added in the specific schools info, so it would be good to have another set of eyes before going live. preview-prod-vfs.va.gov/preview?nodeId=936

**Comment by jenniferlee-dsva** [comment] 2019-11-19 19:47
@RLHecht - a few important items: 
1/ 'On this page' header should be H2 (we shouldn't jump from H1 to H3). 
2/ The TOC jump links should map to H2 headers, so you will need to fix some h2/h3 problems on this page as a whole. I like the text of your TOC links, so maybe using that as the header text...?
3/ DivFeature header (inside the blue box) should be H2.
4/ In the TOC list - the 'See if your school' jump link is #3, but on the body page, that content section comes BEFORE the funding/money content section. 
5/ Could we remove some redundancy in the accordions -- instead of "States beginning with  - to - " - just make it scannable like this:

States A to D
States F to K
so on...

**Comment by RLHecht** [comment] 2019-11-20 14:08
@jenniferlee-dsva The above changes have been made with @AnneHurley and I doing a screen share. When reviewed we can publish! @Karak888 fyi

**Comment by RLHecht** [comment] 2019-11-20 14:32
Page now published through Drupal. Moving to validate and will close once confirmed live on site later this afternoon 11/20.

**Comment by RLHecht** [comment] 2019-11-20 20:47
Validated on live site. Closing ticket.

**Closed by RLHecht** 2019-11-20 20:47 UTC
Labels: content, vsa-public-websites
