### ISSUE TITLE
Collaboration Cycle for Veteran Facing Forms - Form respondent pattern

### ISSUE THREAD

**Issue by JaciWilkinson** [department-of-veterans-affairs/va.gov-team#93813] opened 2024-09-27 16:52 UTC
### Verify information about your product or feature in the VFS Product Directory.

- [x] I have reviewed the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) and confirm that my information is correct (or that I have taken appropriate actions to update or add my product information to the directory).

### VFS team name

Veteran Facing Forms

### Product name

Patterns

### Feature name

Form respondent pattern

### GitHub label for team

1-forms-audit-digitize

### GitHub label for product

patterns

### Public DSVA Slack channel for VFS team

Veteran Facing Forms

### When did/will you start working on this product/feature?

September 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Both

### Does your work require non-trivial code changes or involve PII/PHI?

None

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

No

### Will a VA editor (Drupal) notice this change?

No

### Product outline

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Patterns/form%20respondant/product%20outline.md

### Verify all relevant materials provided to Governance Team

- [x] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [x] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

**Comment by erinrwhite** [comment] 2024-09-27 17:53
Duplicate of #93439 - closing!

**Closed by erinrwhite** 2024-09-27 17:53 UTC
Labels: collaboration-cycle, CC-Request, sitewide CAIA
