### ISSUE TITLE
Accessibility Testing for IVC Forms, Form 10-7959f-1

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#89740] opened 2024-07-31 18:23 UTC
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

rachaelpenfil

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### Who completed the axe scans?

rachaelpenfil

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction
- Heading levels should only increase by 1

### Who completed the content zoom and reflow test?

rachaelpenfil

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/review-and-submit
- if an email address is too long, it will cause the summary boxes to have a side scrollbar (text does not wrap). Not sure if this is an issue.

### Who completed the keyboard navigation test?

rachaelpenfil

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

**Comment by marywang2** [comment] 2024-08-30 14:08
Feedback from Brian: 
1) On the review page, all of the Edit buttons have an aria-label... except one. Guessing that was an oversight and not a deliberate choice! I guess it's technically got a unique accessible name since all of the other edit buttons are different, but seems like it should get an aria-label for consistency.
2) There are potentially two pages with H3 "Home address" --- the page where you say if your home address is the same as your mailing address, and (if you answer no) the page where you enter the address. When you get to the review page, that means you've got two sections right next to each other with the same heading at the same level, plus two edit buttons with the same aria-label. Hard for screen reader users to distinguish them. Not an issue if your home and mailing addresses are the same.

**Comment by reiting** [comment] 2024-09-05 14:47
@marywang2 I think we can close this ticket since we have other tickets for both of the issues above. This is just a duplicate of what we've already got.

**Comment by marywang2** [comment] 2024-09-05 14:53
Changes captured in other tickets.

**Closed** 2024-09-05 14:53 UTC
Labels: frontend, a11y-testing, ivc-forms, 10-7959f-1
