### ISSUE TITLE
508-defect-2: Upload on pre-need is out of date with design system standards and needs design review (and possibly redesign)

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#48297] opened 2022-10-17 15:52 UTC
## Point of contact

Josh Kim

## Severity level

2, Serious. Should be fixed in 1-2 sprints post-launch.

## Details

Several issues exist with the upload page on the pre-need form:

- [Content is out of date with the design system pattern](https://design.va.gov/patterns/ask-users-for/files)
- Post-upload document titles are not semantically written as headings (uses the `strong` element instead) despite starting subsections (cards)
- [The fax or toll free number does not follow design system guidance](https://design.va.gov/components/telephone)
- <del>Card is cut off on mobile</del>

A larger question to be explored is that the content here states:

> To apply, you'll need a copy of your sponsor's DD214

Which leads me to question if the opportunity to upload a DD214 should be prioritized in the process similar to what @skylerschain is [exploring in burials](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43256).

![image](https://user-images.githubusercontent.com/14154792/196212171-757cde5c-a379-41c5-b2ab-4f6e4d582d1c.png)

## Reproduction steps

1. [Start the pre need form unsigned in](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-contact-information)
2. Select "other" for relationship to service member
3. Reach the upload page

## Proposed solution or next steps

A designer should review this page to:
- determine what needs to be updated to current design system standards
- what content to keep or remove
- explore alternative more simpler approaches around uploading _multiple_ documents 
- determine if this should exist earlier in the process

## References, articles, or WCAG support

1.
2.
3.
...

## Type of issue

- [X] Screenreader
- [ ] Keyboard
- [ ] Focus
- [X] Headings
- [ ] Color
- [ ] Zoom
- [X] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by joshkimux** [comment] 2023-02-17 13:58
@MichelleDieudonne updated this as card issue is fixed 🥳 
The following issues remain:
- [Content is out of date with the design system pattern](https://design.va.gov/patterns/ask-users-for/files)
- Post-upload document titles are not semantically written as headings (uses the strong element instead) despite starting subsections (cards)
- [The fax or toll free number does not follow design system guidance](https://design.va.gov/components/telephone)

**Comment by sonntag-adam** [comment] 2023-07-13 19:33
@SarahKay8 @coforma-terry fix is in staging.

**Comment by coforma-terry** [comment] 2023-07-13 20:32
Awesome - thanks for the update @sonntag-adam :)

**Comment by carly-yamrus** [comment] 2023-07-14 16:40
@coforma-terry Hi Terry! Scrum Master from Self-Service here. We were wondering if you were going to verify this item and then close it? Or if by your response above you mean that you have already verified it, and we have your permission to close. Thank you!

**Comment by coforma-terry** [comment] 2023-07-14 17:44
Hi @carly-yamrus - lemme get someone to verify this real quick, and if all looks good, we'll go ahead and close it out!

**Comment by sara-amanda** [comment] 2023-07-15 02:27
## CAIA Inquiry

Hi, there, @carly-yamrus! A few questions for you, before we get started reviewing this ticket:

### Testing Environment
- Should this be tested in Staging or Production? If production, is there a specific test account we should be using? 
- I see the comment reference to "fixed in staging" above, so I assume staging, but wanted to be sure. 

### JIRA Ticket Access 
- @MichelleDieudonne,  we don't have access to the JIRA link in the comments above. 
- Can you share any information that is enclosed within this work item, if it is needing for validation of the fix in staging? 
> Memorials Self-Service Jira Work Item: https://jira.devops.va.gov/browse/MBMS-42629

### Remaining Items to Test
Can you confirm the validation needs to be reviewing the following remaining items, Josh is speaking to? 
> - Content is out of date with the design system pattern
> - Post-upload document titles are not semantically written as headings (uses the strong element instead) despite starting subsections (cards)
> - The fax or toll free number does not follow design system guidance

cc: @coforma-terry

**Comment by MichelleDieudonne** [comment] 2023-07-17 12:16
@sara-amanda The fix is in Staging and now also in PROD, so you can test in both or just PROD :-)  I will copy the Jira story below so that you can see what's written there. 

@ksantiagoBAH @ccruzgra Are you able to help Sara with the "Remaining Items To Test" questions.  

Thanks everyone!

Jira item: 
**Details:**

https://github.com/department-of-veterans-affairs/va.gov-team/issues/48297

**Issue:** 

Upload on Pre-Need is out of date with design system standards

**Feature Flag Status : Does not Impact**
(Yes/No/Does not Impact)

**Steps to reproduce:** 

[Start the pre need form unsigned in](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-contact-information)
Select "other" for relationship to service member
Reach the upload page
Expected results:

Veteran/service member flow 
Upload your supporting documents 

{new H3 heading; H5 styling}
If you have supporting documents readily available, you can upload them to help us make a determination quickly. 

You'll need to scan your documents onto the device you're using to submit this application, such as your computer, tablet, or mobile phone. You can upload your document from there. 

What kinds of documents should I provide?
{additional info component If you're applying for yourself:

{new H4 heading; H6 styling}
 

You'll need a copy of your DD214 or other separation papers. This will help us figure out if you qualify for burial in a VA national cemetery based on your military status and service history. If you don't have these documents, you can still apply—and we'll request the documents for you.

If you're applying on behalf of someone else: {new H4 heading; H6 styling}  

You'll need to provide supporting documents or an affidavit (a written statement of facts confirmed by an oath or affirmation) showing that you're: 
* The applicant's court-appointed representative, or
* The applicant's caregiver (including a spouse or other relative), or
* An attorney or agent acting on behalf of the applicant under a durable power of attorney, or
* The manager or principal officer of an institution in which the applicant is being cared for  {end additional info component}

If you’re applying for an unmarried adult child of a Veteran or service member:{new H4 heading; H6 styling}
You’ll need to provide supporting documents with information about the adult child’s disability. The Veteran or guardian of the child should also ask the child’s current doctor to verify the documents. These documents should include all of the following information: 

The date of the disability’s onset, and 
A description of the disability, mental or physical, and 
A description of how dependent the disabled child is on the Veteran, and 
The marital status of the child 
{end additional info component}

Can I mail or fax documents? {additional info component} 

We can process your request more quickly if you upload your documents here. If you can't upload your documents: 
1.  Make copies of the documents. 
2.  Make sure you write your name and confirmation number on every page. You will receive a confirmation number once you submit this application. 
3.  Submit application and supporting documents to the VA by mail:  {address block} 

NCA Intake Center 
P.O. Box 5237 
Janesville, WI 53547 {end address block} 
**

Or 

Fax documents to the National Cemetery Scheduling Office: 855-840-8299 {linked fax number}{end additional info component}
Guidelines for uploading a file: 

You can upload a .pdf file 
Your file should be no larger than 15MB 
Upload file {secondary button} 

Nonveteran/service member flow
Upload your supporting documents {new H3 heading; H5 styling}

If you have supporting documents readily available, you can upload them to help us make a determination quickly. 

You'll need to scan your documents onto the device you're using to submit this application, such as your computer, tablet, or mobile phone. You can upload your document from there. 

What kinds of documents should I provide? {additional info component} 

If you're applying for yourself:

{new H4 heading; H6 styling}

 

You'll need a copy of your sponsor's DD214 or other separation papers. This will help us figure out if you qualify for burial in a VA national cemetery based on your sponsor's military status and service history. If you don't have these documents, you can still apply—and we'll request the documents for you.
**

If you're applying on behalf of someone else: {new H4 heading; H6 styling}

You'll need to provide supporting documents or an affidavit (a written statement of facts confirmed by an oath or affirmation) showing that you're: 
* The applicant's court-appointed representative, or
* The applicant's caregiver (including a spouse or other relative), or
* An attorney or agent acting on behalf of the applicant under a durable power of attorney, or
* The manager or principal officer of an institution in which the applicant is being cared for  {end additional component}


If you're applying for an unmarried adult child of a Veteran or service member:{new H4 heading; H6 styling}
You'll need to provide supporting documents with information about the adult child's disability. The Veteran or guardian of the child should also ask the child's current doctor to verify the documents. These documents should include all of the following information: 

The date of the disability's onset, and 
A description of the disability, mental or physical, and 
A description of how dependent the disabled child is on the Veteran, and 
The marital status of the child 
{end additional info component} 

Can I mail or fax documents? {additional info component} 

We can process your request more quickly if you upload your documents here. If you can't upload your documents: 
1.  Make copies of the documents. 
2.  Make sure you write your name and confirmation number on every page. You will receive a confirmation number once you submit this application. 
3. Submit application and supporting documents to the VA by mail:  {address block} 

NCA Intake Center 
P.O. Box 5237 
Janesville, WI 53547  {end address block} 

Or 

Fax documents to the National Cemetery Scheduling Office: 855-840-8299 {linked fax number{end additional info component}
Guidelines for uploading a file: 

You can upload a .pdf file 
Your file should be no larger than 15MB 
Upload file {secondary button}
 

https://jira.devops.va.gov/secure/AddComment!default.jspa?id=2259494
Actual Results:
Form content is out of date and does not reflect correct information or flow

**Date and time tested:** 5/23/2023

**User role:** N/A

**Manual/Automation:** N/A

**Repeatable:** Yes

**Screenshots Included (No PII, Test data only):**  See GitHub item linked in the Details section

**Comment by sara-amanda** [comment] 2023-07-17 13:35
## CAIA Update

<mark>*Tested in Staging Environment</mark> 

### Headers Needed

> Post-upload document titles are not semantically written as headings (uses the strong element instead) despite starting subsections (cards)

Updates not rendering in staging environment. Review [details for the default card component](https://design.va.gov/components/card#default) on the DST site. Update file names with semantic HTML. The headers summarize the content on the cards.
- [ ] Remove `<strong>` 
- [ ] Add `<h3>`

![Screenshot 2023-07-14 at 9.59.14 PM.png](https://images.zenhubusercontent.com/63dbe59975ee0eef93e952b2/b3fadbcb-7eb3-4962-a40e-77a2ac289966)`
**Image Description:** Image of the DST section on "default" card components, displaying a wireframe, which highlights and reinforces the need for a heading structure. 


### Content Updates Needed

> [Content is out of date with the design system pattern](https://design.va.gov/patterns/ask-users-for/files)

It appears that the content is still out of date with the DST pattern. Most of the items needing fixed are below. Please review the full ["content considerations" ](https://design.va.gov/patterns/ask-users-for/files#content-considerations)section on the DST site for additional fixes.
- [ ] Mix of wording of documents and files. ... **Pattern recommends** using "**file**" instead of "document" 
    - [ ] 15 instances found on page.
- [ ] Form is using "add another" ... **Pattern recommends** "Upload" instead of "add."  
    - [ ] Change to: "add another file" 
- [X] "Delete file" is correct.
- [ ] Consider mobile users. ... **Pattern recommends** avoiding the word "scan" in file upload instructions. 

### Password Field 
- The password field is required, if left blank, and not applied yet, and another file is uploaded, attempting to add a password to the first file does not appear to be working (in an unauthenticated test).  
- The password field will work on the second file. 
- Changing the second document's name appears to also cause an issue when typing the field highlight focus jumps to the PDF password field for the previous file. This makes it very difficult to type a new document name.
- Deleting the first file and uploading it again appears to rectify the problem; however, if the user does not apply a password, prior to uploading the next document, this is still an issue. 
![Password field issue.png](https://images.zenhubusercontent.com/63dbe59975ee0eef93e952b2/ba17f602-405a-4c8a-b934-699c80dc659b)
![Fields Working Correctly.png](https://images.zenhubusercontent.com/63dbe59975ee0eef93e952b2/61ab95f9-235a-4f40-a54b-a411454bf34c)

**Image Description:** Two images of file uploads, with the first image displaying the issue with typing into the second file name field, and the other showing the heading fields should not be bolded (strong) but should be semantic and follow the structure of the page. In this example: h3.

### Telephone Number
- The phone number in the "Need help?" section of the page in HTML is: `<a href="tel:18005351117">800-535-1117</a>`
- [According to the component for telephone numbers on the DST site](https://design.va.gov/components/telephone#content-considerations): `<a href="tel:+18005351117" aria-label="8 0 0. 5 3 5. 1 1 1 7.">800-827-1000</a>`

![DST vs Staging.png](https://images.zenhubusercontent.com/63dbe59975ee0eef93e952b2/02746ded-c818-4b7e-85e9-69d9a786270f)
**Image Description:** Comparison of the telephone number format on the DST site vs. the staging site, when inspecting the code.

**Comment by sara-amanda** [comment] 2023-07-17 13:49
## CAIA New Team Member Update
- Our new team member, Jamie Klenetsky Fay [jamie.klenetsky@coforma.io](mailto:jamie.klenetsky@coforma.io) will be assisting on this ticket. 
- **Jamie's GitHub username:** @coforma-jamie
cc: @coforma-terry

**Comment by MichelleDieudonne** [comment] 2023-07-17 16:25
@sara-amanda @coforma-jamie We have looked at your additional requests above and agree that the header piece should have been included.  We will work this fix in upcoming epic/story work, and link this issue to that work

While we do agree that these are excellent requests and will make the form better for the Veterans and their families, since some of these were not part of the requests made when we met with the A11y team to discuss the path forward for this work back in February, we believe the rest of the requests to be out of scope for the original item.  We will definitely make these updates, however we ask that you file a new a GitHub item to address the requests we believe are out of scope(bulleted list below).  That way we can ensure requested changes are captured in their own item and we are able to plan for the capacity needed so that we can get these fixes and/or updates made in a timely manner.  

- Password Field update
- Telephone Number in the Need Help sub-footer
- Regarding your content suggestions, we implemented changes to the review page content based on the examples in the https://design.va.gov/patterns/ask-users-for/files#examples page, which use words like "document" and "scan", so the guidance on that page overall is unfortunately contradictory. 

As stated above, we will implement these items in future work.  

Please let us know if you have questions or issues with creating a new GitHub work item to capture these requests.

**Comment by sara-amanda** [comment] 2023-07-17 20:53
## CAIA New Ticket 

Thank you for the update, @MichelleDieudonne, not a problem at all. 

- It looks like @joshkimux identified the issues in the original ticket as a 508-defect-2, which is typically 1-2 sprints post launch, so postponing your out-of-scope work for future work on these items seems to be in line with the original ticket here. 
- [I went ahead and created the ticket (#62135) for the items that will spill over](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62135). @coforma-jamie or myself can be your point of contact on that as well. Happy to help! 

### The ticket will encompass the following: 

> - Password Field update
> - Telephone Number in the Need Help sub-footer
> - Regarding your content suggestions, we implemented changes to the review page content based on the examples in the https://design.va.gov/patterns/ask-users-for/files#examples page, which use words like "document" and "scan", so the guidance on that page overall is unfortunately contradictory.

> As stated above, we will implement these items in future work.

**Comment by sara-amanda** [comment] 2023-07-17 21:12
@MichelleDieudonne after reviewing the above update, please advise if you are wanting this ticket closed. Thanks so much!
cc: @coforma-jamie

**Comment by MichelleDieudonne** [comment] 2023-07-18 12:34
@sara-amanda @coforma-jamie Thank you so much for creating the new item!  Yes, please go ahead and close this item.

**Closed** 2023-07-18 19:44 UTC
Labels: accessibility, pre-need, a11y-defect-2, benefits-crew, sitewide CAIA, sitewide accessibility
