### ISSUE TITLE
Visual regression testing

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#6599] opened 2020-03-05 17:13 UTC
If something is updated in formation -- we need a way to make sure it's not going to break anything on VA.gov. 

We have E2E and unit tests to make sure functionality doesn't break but no way to make sure styling isn't breaking.

**Comment by JoeTice** [comment] 2021-10-08 16:14
Duplicate of [#22129](https://app.zenhub.com/workspaces/planning-board-testing-tools-team-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/22129)

**Closed** 2021-10-08 16:14 UTC
Labels: Epic, VSP-testing-team
