### ISSUE TITLE
Review Collab Cycle references/links in Research & Design section of Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35979] opened 2022-01-26 14:54 UTC

**Comment by chaseakirby** [comment] 2022-01-27 20:32
@shiragoodman This ticket appears to be a duplicate of [#35982](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/35982)

**Closed** 2022-05-27 20:58 UTC
Labels: governance-team
