### ISSUE TITLE
Midpoint Review - Content - Ask VA Integration - Ask VA #62304

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#71066] opened 2023-12-01 23:39 UTC
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts
Overall, considering how much content is in this flow, this is looking really good. Most of my comments are nit-picky: correcting grammar, capitalization, etc. However, two big takeaways to consider:
- Clearly indicate when an answer is required or not. There are times when the wording implies that the question is voluntary, but it’s actually required. With such a long form, the user needs to know what information they need to provide.
- This form requires a lot of information to ask VA a question. Consider changing when the question box is introduced in the flow. The question box appears early; as a user, I’d think that once I’ve input my question, the form must be over. However, that’s not the case here. The form has many more steps (chapters!) after that. This may frustrate the user, resulting in them abandoning the form altogether. If all this information is required, then having the questions box later may incentivize the user to continue.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### MUST
~- All pages - The user finds the tag “Get answers...services. And upload documents online.” The second sentence is an incomplete sentence. Please revise it so it’s a complete sentence. There are many ways the writer could do this. For example, they could write: “Get answers to your questions about VA benefits and services and upload documents online.”~
- Many pages - The user finds the example date “January 19 2000” throughout the form. This example date is formatted incorrectly because it doesn’t have commas between the day and year. Please revise so the example date is “January 19, 2000.” This may require a Design System update.

#### MUST
- Ask VA Homepage > Sign in for the best experience - The under finds the following note: “You can sign in after you ask a question. But your question won’t be tied to your account.” The second sentence is an incomplete sentence. Please revise it so it’s a complete sentence. There are many ways the writer could do this. For example, they could write: You can sign in after you ask a question, but your question won’t be tied to your account.”

#### SHOULD
- Ask VA Start page - The user finds an alert box with the sentence “Sign in to ask about education or debt.” They then find an explanation that reads: “You need to sign in if…” The title of the alert box doesn’t clearly indicate that the user must sign in to ask a question about those subjects. At a quick glance,  it looks like another plug to sign in, but isn’t required. It’s only when the user reads the text that they know they have to sign in to ask questions on those subjects. The writer should consider revising the subheader of this box so it clearly states that this is a requirement. There are several ways the writer could do this. For example, the header could be: “Sign in required to ask about education or debt”.
- Ask VA Start Page > Sign in for the best experience - When the user reads the list, they find this bullet: “You can track your question online when you’re signed in to VA.gov.” This bullet doesn’t fit the style of the other two bullets since it ends with “...when you’re signed in to VA.gov.” The writer should shorten this bullet so it matches the other two. There are several ways the writer could do this. For example, the bullet could be: “You can track your question’s status online.”
- Ask VA Start Page - The user finds an alert box with the sentence “Sign in to ask about education or debt.” They then find this explanation: “You need to sign in if your question is about education and training or debt.” This explanation differs from the subheader, which only mentions education, not training. The subheader should be revised so that it either includes “training” or indicates that a training-related question is something that the user needs to sign in for. 
- Chapter 2 > What’s your question? - The user finds a question box where they can type their question. Under the box, there’s a list where the user chooses why they’re contacting the team. This flow feels off - it feels repetitive to choose why I’m contacting the VA after I’ve already typed out my question. The page should be flipped: first the “Tell us the reason” and then the “What’s your question?” box.
- Chapter 2 > What’s your question about? - Like the previous comment, this question is in the wrong place in the flow on this page; the question box should be the last part of the page. Perhaps the flow should be > What’s your question about? > Tell us the reason > “What’s your question?” box.

#### CONSIDER
- Information card for category and topic > Tell us your question - The user finds the subheader “Tell us your question” and is given a questions box. Consider changing the header to “Ask us your question” rather than “Tell us.” Generally, we say that questions are asked, not told.

#### MUST
- Personal information > I’m a family member of the Veteran > Tell us more about your relationship - The user finds several options when asked to choose their relationship with the Veteran. One of the options is: “I’m the Veteran’s step child.” There is a small typo: “stepchild” is one word. Please revise. 
- Veteran > Personal information > Tell us about yourself > Pronouns - The user finds a section with the subheading “Pronouns” with the prompt: “Share this information if you’d like to help us understand the best way to address you.” This wording makes it sound like choosing pronouns is voluntary. However, the user is then required to choose their pronouns, which goes against the “If you’d like to” prompt. Please revise so the prompt and the action match. For example, if it’s required that they select pronouns, the prompt should reflect that. There are several ways the writer could do this. For example, if pronoun selection is required, the prompt could be: “Please help us understand the best way to address you” or “What is the best way to address you?”

#### SHOULD 
- Veteran > Personal information > Tell us about yourself > Gender identity - The user finds a section with the subheading “Gender identity” with multiple options. The final option is: “A gender not listed here.” This option isn’t worded in the same style as the other options. This should be revised so the option matches the others on the list. There are several ways the writer could do this. For example, the options could be: “Gender not listed.”

- Veteran > Personal information > Submitter chooses “Contact by US Mail” > Your address > I live on a United States military base - We just worked on language for something similar to this for [Dependent Experience Team, Dependency Claims, VA Form 21-686C Military Base Outside the U.S. Address Issues #68019](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68019). The wording they use for the question is: “I receive mail outside of the United States on a U.S. military base.” This should be something you want to apply so we remain consistent.

#### NOTE
- I got very confused about the flow for Veteran > Personal information >Submitter chooses “Contact by US Mail” > Conditional requires veteran’s postal code and they don’t choose Contact by Mail. I’m not sure how to best organize it in the future, but I got a little lost in how to navigate this flow.

#### MUST
- Review and submit > Personal information > Relationship information > Who you are to the Veteran - When the user is reviewing their personal information, the user’s response to the statement, “Who you are to the Veteran” has the response: “the Veteran’s spouse.” “The” should be capitalized in this instance. Please review and revise so the answers to this section begin with a capital letter. 

#### CONSIDER
- Your question was submitted - After the user successfully submits their question, they are given several pieces of information. In the last paragraph, they’re told: “If we need more information to answer your question, we’ll contact you.” Consider telling them how they’ll be contacted. Is it by email? Phone? This may make it easier to contact them if more information is needed.

## Final Note
Thank you for the opportunity to review this work. As stated above, considering how large this flow is, y'all have done some really great work. Continue working with CAIA to develop the content on this form. If you have any questions about my feedback, please let me know.

**Comment by tygindraux** [comment] 2023-12-04 18:16
Hi Rebecca (@rferguson13)! Thanks so much for this detailed feedback, and for attending and sharing back to us on Friday.

Everything you've noted makes sense. For peace of mind, I did want to clarify that we've worked closely with CAIA to develop the content in the form (they're so helpful!) but sometimes it was slightly at odds with the feedback here (for example, the subtitle on every page.) When there's a discrepancy, we'll follow your guidance.

And I wanted to try to explain the postal code confusion that you noted.

Basically, for the most part we won't collect postal code unless we need to contact someone by US Mail. But, certain business lines require a postal code in order to reply to an inquiry. That might be for different reasons (based on their business rules), for example the Caregiver support team requires a postal code in order to share information that's relevant to the place where the person is located. So in these cases (where we need to allow for this capability), there's some conditional logic that helps figure out whether the person is being contacted by US mail (if so, don't ask for postal code twice) or not (then collect postal code). Hope that helps.

We'll update this ticket once we've gotten through making changes based on your feedback.

**Comment by rferguson13** [comment] 2023-12-04 19:29
Hi @tygindraux ! Thanks for your response. I also wanted to update you on something - one part of my feedback was actually outside the scope of the Style Guide. My first "Must" (All pages - The user finds the tag “Get answers...") isn't actually a "Must." According to CAIA and the Style Guide, this was OK. I would follow CAIA's guidance on this. Sorry for creating any confusion!

**Comment by tygindraux** [comment] 2023-12-04 20:00
Another follow up question related to make it clear when something is required or not: We'll update the subtext in the pronouns component so it's more clear this is required. But I'm also wondering if we should use an 'Optional' label on questions that are optional (which we've tried as much as possible to limit/remove if so, but there are 1-2).

**Comment by tygindraux** [comment] 2023-12-05 19:08
Hi @rferguson13, we've finished updates based on your feedback. These included:
- updating the order of these fields (1) what's your question about (2) tell us the reason you're contacting us (3) what's your question
- revised subtext and labels so it's clear when an answer is required or not
- revised subtitle on all pages (although, let us know if we should change it back)
- revised example date to include a comma
- revised sign in page content (multiple updates based on your feedback)
- revised H3 to 'ask us your question' instead of 'tell'
- revised to 'stepchild'
- revised last option in gender list to 'Gender not listed'
- revised content for military based checkbox to match other use case you shared
- capitalized 'The' in 'The Veteran's spouse' on the review page
- confirmed we can/will include their contact method on the submission page, eg. "You should receive a reply [by email] within 7 business days."

We also considered your feedback about where the question box sits in the flow. We're deciding to keep the placement of the question box as is, for testing. Here's why:
- we actually made an intentional decision to move the question box earlier in the flow (compared to how it works right now)
- this is because a user's key task is to ask a question; we assume they start using this service with their question in mind and want to make it easy for them to 'get it out of their head' early on
- we also worry (as you do too) about drop-offs if it takes them forever to ask the question
- we're planning to pay close attention to this problem in testing

I hope that helps! Please let me know if you have any follow up feedback. I'm going to close this ticket now, as the MUST feedback has been incorporated. Thanks again!

**Closed** 2023-12-05 19:08 UTC
Labels: content, collaboration-cycle, collab-cycle-feedback, midpoint-review
