### ISSUE TITLE
IA design for Income Limits tool

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#52316] opened 2023-01-19 23:43 UTC
IA design and support for the Public Websites team in launch of new tool

Original intake: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/51132

**Comment by mnorthuis** [comment] 2023-01-19 23:48
1/19/2023 Meeting notes - Sitewide IA + PW team

- Income, in addition to disability rating, plays a part in eligibility and copay amounts in va health care
- Legacy tool
  - Asks for zip and dependents and gives them a complex set of results
  -  Current team can no longer continue to maintain the old tool
  - Legacy tool linked from About VA health, Costs of care, copay rates page
  - Possible additional pages: priority groups page?
- Doing this for transparency, but don't want to discourage Veterans from applying
- Also doing as a reference - if Veteran is arguing case from a previous year they could access previous years info - will be testing this use case
- Utilized by family/caregivers - yes, on behalf of a veteran, likely won't be testing with this audience
- Related task - report income changes form - 10-10ezr, available under "Manage benefits"
- There are times you are not eligible for VA health care - IA/content need to account for this scenario; team may add this into testing
- PG 5-7 needs to use the calculator, PG8 - one person said there's no such thing, and shouldn't be present
- Research not screening based on priority group, want people who don't have health care and have dis rating of 50% or higher
- Research starts when we get info from SCIA
- Meeting with Dave C on Feb 1, need time to update prototype prior to that, having IA info required for prototype (i.e. breadcrumb, left nav) by 1/27 will suffice, remaining IA details can be finalized after research

**Comment by jenniemc** [comment] 2023-01-24 18:43
@mnorthuis, did you assign this ticket to me by mistake?

**Comment by mnorthuis** [comment] 2023-01-24 18:49
@jenniemc very sorry, wrong Jenny!

**Comment by jenniemc** [comment] 2023-01-24 19:06
No worries :-)

**Comment by kristinoletmuskat** [comment] 2023-01-27 16:54
Hello! Update on this -- we have a draft of the ticket that is waiting on H1 decisions from content, so we are waiting to update and close ours out until that is finished. We did send a screenshot of the user flow and site map so the Income Limits team could see where we suggest the page lives. We're answering some quetstions the team had about our recs re: the user flow. It turns out they aren't doing use testing next week, but skipping to a stakeholder review.

**Comment by kristinoletmuskat** [comment] 2023-02-02 20:42
Suggested changes to IA Design Specs Doc
URL + breadcrumbs:
URL: /income-limits
Breadcrumb: Home > Health care > Income limits and your VA health care
Entry points:
Health care hub page - Add
Link label: Income limits and your VA health care
Link destination: va.gov/healthcare/income-limits
Health care hub left nav - Add
Link label: Income Limits
Link destination: va.gov/healthcare/income-limits
Your health care costs
Link label: TBD
Link destination: va.gov/healthcare/income-limits
Eligibility for VA health care
Link label: TBD
Link destination: va.gov/healthcare/income-limits

**Comment by kristinoletmuskat** [comment] 2023-02-03 21:52
Updated IA Design Specs doc based on feedback from Mikki: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/income-limits.md

**Comment by kristinoletmuskat** [comment] 2023-02-08 23:12
Confirmed with Mikki that we can close this for now and reopen if needed.

**Comment by RLHecht** [comment] 2023-02-10 14:53
Thanks, Kristin! Closing ticket!

**Closed by RLHecht** 2023-02-10 14:53 UTC
Labels: sitewide content, sitewide content-product support, Sitewide IA, sitewide CAIA
