### ISSUE TITLE
[Bug] Profile 2.0: Terms and condition text/link are overlapping other text on mobile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12024] opened 2020-08-04 18:51 UTC
## Overview

- Device: iPhone Xs
- iOS version: 13.5.1
- Brower: Safari

**Issue**

On mobile, the Terms and Conditions text/link is overlapping other text on mobile, making the page appear broken.

Since this makes part of the page appear broken, I would call this **medium/high** priority. But it's definitely lower priority than some of the more functional bugs Erik/Lihan found.

![IMG_1291.jpg](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/48af5d55-6750-4233-9346-87e18fdb25fb)

## Tasks

- [ ] Fix text overlap issue for Terms and Conditions field.

**Comment by erikphansen** [comment] 2020-08-04 18:54
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/12018

**Closed** 2020-08-04 18:55 UTC
Labels: bug, frontend, needs-grooming, profile, vsa-authenticated-exp
