### ISSUE TITLE
Staging:  Clinics filter if not seen within last 24 mos & VATS Setting is Last Seen within 36 months.

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#39812] opened 2022-04-11 19:20 UTC
Background from Lauren A:  Front End Clinic filtering;   This is working as designed. During research for the new VAOS redesign it was clear that clinics were confusing to Veterans. One, because of the naming conventions. Two, because many of the clinics were not actually available for Veterans to use which was resulting in high cancellation and reschedule rates. A key design principle for new VAOS is ensuring that Veterans are only seeing options that are available to them. This principle also applies to this new business in which Veterans are only enabled for self-schedule for VA appointments if they have been previously seen for that type of care at that specific VAMC in the past 24 months regardless of setting in VATS.

VATS Set to Direct Schedule Yes with in 36 months. And veteran has either a Checked in or Checked out appointment that is >24 mos but less than 36 mos, I get this in VAOS: The FE could not find any of the clinics returned by var-resources in the past 24 months of appointments.    The  User in VATS has specifically set Direct Scheduling to Yes Seen within Last 36 month but the front end UI  has logic that over rules that setting.  I think if VATS is set to Yes 36 months front end should change clinic filter to 36 months.

Steps to recreate:
1. Configure VATS to Cheyenne Direct Scheduling Move Yes Seen within Last 36 months
2.  Login as John Morrison (john.morrison@id.me).  All of John Morrison's checked in/out appointments are >24 mos and he has not had a Move appointment in the last 24 mos.  
3.  Select start scheduling.  Select Move, Select Cheyenne.  
4.  Results Seen:  Patient is dropped into the  the request flow.  
5  Results Expected:  Patient is dropped into Direct Scheduling flow.  Console displays:  The FE could not find any of the clinics returned by var-resources in the past 24 months of appointments.  The console verbiage was added by Jeff to aid in triage. 
It really isn't VAR Resources, the console verbiage is out of date  by referring to VAR-Resources.  

https://staging-api.va.gov/vaos/v2/eligibility?facility_id=983&clinical_service_id=audiology&type=direct   Call returns TRUE., so it is definitely clinic filtering to 24 mos that is causing the issue.  

{"data":{"id":"d8c9","type":"patient_metadata","attributes":{"decision_date":"2022-04-11T19:19:36.55093Z","clinical_service_id":"audiology","type":"direct","**eligible":true,**"id":"d8c9"}}}

**Comment by ldelacosta** [comment] 2022-04-12 18:18
Upon review, we will hold on with making this change until V2 is launched and stable in production. We will re-visit the logic and update the proposed requirements at a later date. 

CC: @JRRoof

**Comment by ldelacosta** [comment] 2022-04-13 18:20
Upon review with the team, we will work on this ticket. A [ticket 39812](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39812) has been created for the work. Once we have validated the changes, we will re-assign this ticket to the SQA team.

**Comment by ldelacosta** [comment] 2022-04-13 18:20
Upon review with the team, we will work on this ticket. A [ticket 39812](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39812) has been created for the work. Once we have validated the changes, we will re-assign this ticket to the SQA team.

**Comment by ldelacosta** [comment] 2022-04-28 19:54
@marcynadeau - the changes have been deployed to staging & production. If you can please validate and advise if there are any issues. Thanks!

**Comment by ldelacosta** [comment] 2022-04-28 20:29
Please hold off on validating. I think the issue is still happening.

**Comment by ldelacosta** [comment] 2022-04-29 18:19
@marcynadeau - This is ready for testing. Please let me know if there are any issues. Thanks. 

Recap: The UI will still accept 250 characters for the comment field if the reason is "My reason isn't listen." The response body was updated (See Examples in #39864). Reviewed the updated requirements during 04/29 standup with the team.

**Comment by ldelacosta** [comment] 2022-06-16 16:13
@marcynadeau - This is ready to be tested. Please let us know if you're still having issues. Thanks!

**Comment by marcynadeau** [comment] 2022-06-17 19:23
Note. John Morrison appointment data has changed and that data nullified the test.  So I need to set up another patient in order to test this exact scenario.  Will be updating scenario with new patient data set up.  cc @ldelacosta

**Comment by marcynadeau** [comment] 2022-06-24 14:56
Testing blocked by https://issues.mobilehealth.va.gov/browse/VAOSR-3242

**Comment by beth-wodzinski** [comment] 2022-06-30 19:10
Failed testing. Back end is returning clinic appointments and setting eligibility to true; front end is not finding appointments and allowing direct scheduling. Reach out to Beth or Marcy for more details. 

This seems to be mostly involving child clinics; parent clinics have worked. 

test patient jacobreid.r.iasimone@id.me, clinic FTC Amputation and Sidney Opthalmology.

**Comment by marcynadeau** [comment] 2022-06-30 20:56
@ldelacosta This failed testing. Assigning back to you.

**Comment by ldelacosta** [comment] 2022-07-01 23:36
Moving this ticket back to blocked since SQA found an issue. The working ticket is #39950

**Comment by ldelacosta** [comment] 2022-07-12 13:33
@beth-wodzinski @marcynadeau - This is ready to be tested.

**Comment by beth-wodzinski** [comment] 2022-07-13 17:30
This passed testing (and there was rejoicing throughout the land). See spreadsheet bw39812.xls for details of scenarios tested. [https://app.zenhub.com/files/133843125/c6f31033-62aa-4df9-878d-4c6a7e640826/download](https://app.zenhub.com/files/133843125/c6f31033-62aa-4df9-878d-4c6a7e640826/download)
@marcynadeau @ldelacosta

**Closed** 2022-07-13 17:32 UTC
Labels: frontend, vaos, testing, vaos-v2
