### ISSUE TITLE
Audit on user experience when switching credentials

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#30473] opened 2021-09-23 23:41 UTC

**Comment by bosawt** [comment] 2021-11-19 00:49
I have to test things, but here are my initial thoughts:


I think with regards to persistent data, there are two cases that need considering with login.gov:
Models that store account_uuid
I'm gonna go ahead and say this is not a huge problem. At worst, it's not really that worse than the problem we currently have with the accounts table. If a user has an existing Accounts table record, and they sign in with login.gov for the first time, we should find that Accounts table record, inject the logingov_uuid, and be fine. Of course, tens of thousands of users have multiple Account table records and that complicates this, but until my longterm solution is in, we probably just have to live with this
Models that store user_uuid
I think this will be a problem with login.gov specifically. Up until now, idme_uuid has exclusively been user_uuid, but now logingov_uuid will be user_uuid if the user logs in with that credential. I will attempt to test this next, but This will cause very easily reproducible difference in experience depending on whether you log in with ID.me or Login.gov, and, worst for us, they will appear to lose all persistent data that uses user_uuid (notably, InProgressForms), when they log in with Login.gov for the first time. I think to solve this for now, we're going to want to have user_uuid equal to idme_uuid if it exists (regardless of how the user logged in), and then logingov_uuid only if an idme_uuid can't be found. I believe this should reduce this user_uuid issue to the scope of the first bullet-point (models that store account_uuid)

**Comment by bosawt** [comment] 2021-11-22 23:32
There is a fundamental issue with the current accounts table that we have to figure out.
- Both idme_uuid and logingov_uuid have a uniqueness constraint on the Accounts table
- Accounts table records are created when a user is not verified with a credential
- When a user verifies a credential, their information is 'merged' with existing verified information. Our Accounts table does something similar, where we use an existing 'verified' Accounts table record
- The issue is when a user verifies with one credential (such as id.me), then creates an unverified login.gov credential, then verifies. There will be an account table record for the verified id.me record, an account table record for the unverified login.gov credential, then upon verification we will attempt to write a logingov_uuid to the id.me related account table record, and that will cause a uniqueness constraint issue.

**Comment by bosawt** [comment] 2021-11-22 23:34
Some possible solutions:
- Delete the unverified record when we find that a verified record already exists
- Set the offending field to 'nil', which frees up that value for the verified Account record
- Keep two different Account records (one for id.me, one for login.gov verified accounts)
- Add a 'deprecated' field to the Account table, then relax the uniqueness constraints so that they must be unique unless the 'deprecated' value is set
- Maybe other ideas?

**Closed** 2021-11-30 05:15 UTC
Labels: Identity, Identity-Backend
