### ISSUE TITLE
The address validation modal remembers the last option you selected between opens and closes

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4264] opened 2019-12-15 04:00 UTC
The address validation modal remembers the last option you selected between opens and closes

To reproduce:
1. edit mailing address. use `575 20th, San Francisco CA 12345` 
2. submit the address form
3. select something other than the first recommendation (so either the user-entered address or the 2nd recommendation)
4. cancel out of the modal
5. repeat steps 1 and 2 and see that the modal defaults to selecting whichever option you'd selected in step 3

This is not expected behavior and might lead to a crash if the second time you open the modal the index of the previously selected option is out of bounds.

**Comment by Samara-Strauss** [comment] 2019-12-30 20:07
Duplicate of #4271 which is done. Closing.

**Closed by Samara-Strauss** 2019-12-30 20:07 UTC
Labels: bug, frontend, profile, vsa-authenticated-exp
