### ISSUE TITLE
[FE] Make address comparison function 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3173] opened 2019-11-06 18:56 UTC
Make function that compares two address objects and determines if there is any real difference between them and if there is, return the suggested address with the differences highlighted

**Comment by erikphansen** [comment] 2019-11-12 18:21
I'm closing this ticket. In my research of how the address suggestion API works, I've determined that we're not going to need a custom function to compare addresses and determine if they are effectively identical. The suggestion API essentially does that work for us.

The specific situation where I anticipated using this address comparison function the most was when a user enters their valid address correctly and the suggestion API returns a single result that is essentially identical. For example, if you entered an address like `110 SE washington, Portland, OR 97214` the single suggestion from the API would be:

```
{
    "addresses": [
        {
            "address": {
                "address_line1": "110 SE Washington St",
                "address_type": "DOMESTIC",
                "city": "Portland",
                "country_name": "USA",
                "country_code_iso3": "USA",
                "county_code": "41051",
                "county_name": "Multnomah",
                "state_code": "OR",
                "zip_code": "97214",
                "zip_code_suffix": "2127"
            },
            "address_meta_data": {
                "confidence_score": 100.0,
                "address_type": "Domestic",
                "delivery_point_validation": "CONFIRMED",
                "residential_delivery_indicator": "BUSINESS"
            }
        }
    ],
    "validation_key": 1613425172
}
```

The plan was to use this address comparison function to determine that the suggestion was close enough to the user-entered address that we wouldn't want to even present the user with a choice between what they entered and what the suggestion API returned. But because the single suggestion has `"delivery_point_validation": "CONFIRMED"` and a `"confidence_score"` > 80, we can safely assume that the suggestion is effectively identical to the address that the user entered. And in this case we'll simply take the address that the user entered and send it to the add/update address endpoint. The add/update service will "correct" it (ie, use the suggestion instead) behind the scenes and save the suggested address to the database. _To the end user this will work exactly like it does now._

There is a remote edge case where we'd ideally want to highlight differences between the input address and a suggestion address to make it clear to the user what's different between the suggestions and what they had entered. This is when the suggestion API returns multiple valid suggestions that we need to show the user. But because this will be a _very_ rare event it is not worth the effort required to make the function that would compare two addresses and highlight the differences.

**Closed by erikphansen** 2019-11-12 18:21 UTC
Labels: frontend, vsa-authenticated-exp
