### ISSUE TITLE
Build education landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#77990] opened 2024-03-08 22:23 UTC
## Issue Description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Education:   http://preview-prod.vfs.va.gov/preview?nodeId=65340

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [x] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The landing page is live on VA.gov

**Comment by laurwill** [comment] 2024-05-14 16:30
@d-beyer while we're waiting to figure out the H3 additional benefits and helpful tools section styling, want to move ahead with building out the full landing page for education? 

As Danielle mentioned yesterday, let's skip the blurbs for the "Manage" section and rely on descriptive CTA links alone.

**Comment by laurwill** [comment] 2024-05-19 23:10
Update: We're keeping the Additional benefits and Helpful tools H3 sections and styling them as hyperlinked bold text for the links.

**Comment by laurwill** [comment] 2024-05-20 00:06
@kristinoletmuskat IA spec has a link to the main [Veteran chapter 36 educational and career counseling page](https://www.va.gov/careers-employment/education-and-career-counseling/).
But the existing family member hub page links to this [Employment benefits for dependent family members page](https://www.va.gov/careers-employment/dependent-benefits/) that seems to be the family version of chapter 36. Would we want to migrate that page into the hub and link there instead?

**Comment by kristinoletmuskat** [comment] 2024-05-20 18:02
@laurwill I'm wondering if we should migrate that page into family member hub as well, since it's family-focused already?

**Comment by laurwill** [comment] 2024-05-20 18:25
Yes! I think we can migrate

**Comment by kristinoletmuskat** [comment] 2024-05-20 22:43
I found another page that already exists in the veterans education hub about dependent education benefits: https://www.va.gov/education/survivor-dependent-benefits/

I think ideally we would redirect this page to the new family education/careers subhub, EXCEPT I think we would need to change the way the left nav has the benefits nested. Because if we redirected it, a user would not be able to see the nested pages --> clicking on the link would take them to our subhub, they would click on a benefit, which would take them back to this nav. It's kind of a weird circular thing.

**Here are a few options I see:**
1. We could migrate all of the nested pages as part of phase 1. Except, 2 of those pages are forms owned by other teams, and I don't think we can get them on board in time for our 6/13 launch goal. 
2. We could migrate all of the static pages out of the veterans hub and remove the left-nav links in veterans hub to the 2 applications. The 2 applications would then only be accessed from the benefit static pages (temporarily until we can migrate the applications under fam hub) **I think this is the best approach**
3. We could leave the veterans education hub as-is for now. The survivor/dependent content would be duplicated with our new edu/careers subhub, but this would give us more time to coordinate migrating the applications. 
4. We could flatten the veterans hub left nav structure so that the different survivor benefits are in-line with the 'survivor and dependent benefits'. I don't think this is a good idea, because veterans could be confused about whether some of these apply to them.
5. We could redirect the [survivor+dependent benefits](https://www.va.gov/education/survivor-dependent-benefits/) page to our subhub and just live with some weird circular-ness temporarily until phase 2. **this might be the second best option. Or maybe the first best if we don't have time to do the work of migrating 4 more pages.

![Screenshot 2024-05-20 at 4 31 18 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/7cbaefc8-08fd-448d-88ea-dacd1391997f)

I'm going to talk with Mikki about this tomorrow morning and get back to you, but feel free to lmk if you have any thoughts, or if I'm overthinking this in some way.

**Comment by laurwill** [comment] 2024-05-21 12:07
cc @aprocik1 for some shifting plans for education subhub phase 1 launch ⬆️

**Comment by kristinoletmuskat** [comment] 2024-05-21 15:31
Update -- I was getting ahead of myself with these -- we don't need to worry about this until we get to the education phase. For Phase 1, it's ok if the veteran hubs stay mostly the same (with the exception of moving champva). We just need to make sure the family hub is launched and pointing to veteran hub pages.

**Comment by d-beyer** [comment] 2024-05-23 14:49
Hi @laurwill -- I'm done with the draft of this page and it's ready for your review.

**Comment by laurwill** [comment] 2024-06-04 05:34
@kristinoletmuskat notes here:
- combined the spina bifida and CWVV links here as we did in the health subhub, and linked to the live combined page instead of legacy pages
- removed claim status tool as it doesn't have education claims

**Comment by kristinoletmuskat** [comment] 2024-06-04 18:33
Cool just updated IA spec and mural.

Just to confirm, the combined spina bifida and CWVV page is https://www.va.gov/disability/eligibility/special-claims/birth-defects/ right?

@laurwill

**Comment by laurwill** [comment] 2024-06-05 01:52
Yep! That's the one.

**Comment by saratorres2** [comment] 2024-06-11 15:27
@laurwill Copy edits complete. Will add the open question about whether to, in the future, consider hyphenating "GI Bill approved school" on this subhub page and the linked page to the [backlog ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85640).

**Comment by d-beyer** [comment] 2024-06-14 15:35
![Education-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/ad51346b-5e27-44c7-9291-f8b16cbfa90c)

**Comment by saratorres2** [comment] 2024-06-14 19:15
Copy edits of new related links section complete.

**Comment by kristinoletmuskat** [comment] 2024-07-10 19:17
Confirmed page is live in prod, closing out.

**Closed by kristinoletmuskat** 2024-07-10 19:17 UTC
Labels: sitewide content, sitewide IA, sitewide CAIA
