### ISSUE TITLE
FMB: Build housing landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#77994] opened 2024-03-08 22:30 UTC
## Issue description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Home loans: http://preview-prod.vfs.va.gov/preview?nodeId=65665

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [x] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The landing page is live on VA.gov

**Comment by laurwill** [comment] 2024-05-15 17:56
@d-beyer you can go forward with building out this landing page. 

Noting open question from our chat with Danielle to discuss with @kristinoletmuskat 
- Should H1 of landing page say "for family members" or "for spouses" since main benefit is only for spouses

**Comment by kristinoletmuskat** [comment] 2024-05-16 19:06
@laurwill @d-beyer I think fine to just mention spouses in the H1 if the programs are only for spouses. Which is kind of weird because you can own a home with anyone right?

**Comment by laurwill** [comment] 2024-05-19 23:27
Cool cool — then would this make sense? 
H1 of new subhub landing page = Housing assistance for surviving spouses
H1 of the main "Get benefits" page remains "VA home loan programs for surviving spouses"

**Comment by d-beyer** [comment] 2024-05-29 15:55
@laurwill -- I've finished drafting this page. It's ready for your review.

**Comment by laurwill** [comment] 2024-06-04 03:07
@kristinoletmuskat this [VA acquired properties page](https://www.benefits.va.gov/homeloans/realtors_property_mgmt.asp) in the IA spec is nested in a section for real estate professionals, and I don't see anything on the page that seems relevant for surviving spouses. Do you know why we're including this here?

**Comment by laurwill** [comment] 2024-06-04 03:10
Oh weird, I see it's in the Veteran housing hub too — this does not look like a Veteran-facing or family member-facing page to me at all.

**Comment by laurwill** [comment] 2024-06-04 03:15
I removed VA acquired properties for now. I also removed the link to claim status tool, because we learned the tool doesn't include home loan COE requests.

**Comment by kristinoletmuskat** [comment] 2024-06-04 18:36
Sounds good, I just removed CST and the acquired properties from the IA spec and mural. 

I think Mikki included a bunch of stuff in the initial draft (like VA acquired properties) that she thought might be relevant to Veterans, but trusts us to dive into the pages themselves and see if they fit or not. So I trust you that we should remove this one.

**Comment by laurwill** [comment] 2024-06-05 13:03
Okay awesome! Removed :)

**Comment by laurwill** [comment] 2024-06-10 12:35
Hi @saratorres2 , the housing subhub landing page is ready for your copyedit. Let me know if you have questions!

**Comment by saratorres2** [comment] 2024-06-11 15:31
@laurwill Copy edits complete!

**Comment by d-beyer** [comment] 2024-06-14 15:36
@saratorres2 I've added the related links and they're ready for copyedit. Screenshot attached.
![Housing-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/755fc214-e547-46f0-91a1-9ccbe5c757b4)

**Comment by saratorres2** [comment] 2024-06-14 18:44
@laurwill Copy edit of new related links section complete.

**Comment by laurwill** [comment] 2024-06-30 23:30
Update: SMEs didn't approve this landing page, so we linked directly to the home loans for surviving spouses page in phase 1 launch. We'll launch this page with the rest of the housing content instead.

**Comment by laurwill** [comment] 2024-09-22 21:14
@aprocik1 since you'll be doing the housing phase, I'm assigning this ticket to you instead. Let me know if any questions about this one!

**Comment by aprocik1** [comment] 2024-10-08 18:14
Note: This is the draft of the subhub landing page: [Housing assistance for surviving spouses](https://preview-prod.vfs.va.gov/preview?nodeId=65665)

**Comment by d-beyer** [comment] 2024-12-11 19:16
@aprocik1 I drafted an [update to the FMB hub landing page](https://preview-prod.vfs.va.gov/preview?nodeId=69595) to match the new housing page's H1, url, and gave it a suitable description.

**Comment by aprocik1** [comment] 2024-12-12 15:20
Thanks @d-beyer. I made one small change--changed "get" to "request." We've been working with the COE product team for a couple of months with the goal of clarifying all of the COE content on VA.gov. I appreciate the way you've simplified the link summary that's currently live.

**Comment by aprocik1** [comment] 2024-12-12 19:12
Update: Beth confirmed that we won't crosslink to [this legacy page](https://www.benefits.va.gov/homeloans/contact_rlc_info.asp) on this FMB housing sub hub page.

**Comment by kristinoletmuskat** [comment] 2024-12-12 19:46
Cool, I will remove it from the spec.

**Comment by saratorres2** [comment] 2024-12-16 14:43
@aprocik1 @d-beyer Subhub landing page [Housing assistance for surviving spouses](https://preview-prod.vfs.va.gov/preview?nodeId=65665) is published. Waiting for page to go live; will QA later today.

**Closed** 2024-12-18 13:30 UTC
Labels: sitewide content, sitewide IA, sitewide CAIA
