### ISSUE TITLE
[Design] Update Travel pay appt confirmation wireframes and prototype to be a single appt confirmation

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#47159] opened 2022-09-16 15:26 UTC
Task
- [ ] Update Travel pay appt confirmation wireframes to be a single appt confirmation
- [ ] Update Travel pay appt confirmation prototype to be a single appt confirmation

**Comment by loripusey** [comment] 2022-09-19 14:17
Closing because a duplicate of https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47158

**Closed by loripusey** 2022-09-19 14:17 UTC
Labels: design, ux, HCE-Checkin
