### ISSUE TITLE
Downtime notification for SSOe outage on VA.gov

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6249] opened 2020-02-26 21:52 UTC
**User Story**
As a user trying to authenticate on VA.gov, I want to know if there is an SSOe outage so that I am aware that I will not experience session continuity navigating from VA.gov to other SSOe-enabled sites.

**Tasks**
- Define verbiage of error message
- Get verbiage approved by Content & IA team
- Add a health check monitor on SSOe
- Define a maintenance window slot for SSOe

_This story may be split into smaller chunks, but capturing here for now_

**Comment by hinzed1127** [comment] 2020-02-27 18:53
@bridgethapner for reference, we utilize an alert component on the website that hits `vets-api` to grab a list of any services that might be down and displays relevant outages in the sign-in modal. I just quickly hardcoded them all to true so you could see the different messaging in one place:

![Screen Shot 2020-02-27 at 12.46.25 PM.png](https://images.zenhubusercontent.com/5ca254d7e268082e7bd49749/42fd82ac-fa6b-4752-9748-09eb6b87cbda)

![Screen Shot 2020-02-27 at 12.46.36 PM.png](https://images.zenhubusercontent.com/5ca254d7e268082e7bd49749/40bb9d8b-8fab-45b6-8c1d-504ec33b457b)

@patrickvinograd it looks like there's not currently any kind of IAM check in the `backend_services` lib of `vets-api`. Would that be the proper place to add a similar lookup for this?

**Comment by bridgethapner** [comment] 2020-03-03 16:32
Wireframe here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407514184

Deprioritized for launch per 3/2 meeting with DEPO folks.

**Comment by ambikaroos** [comment] 2020-03-04 19:25
We no longer need to have a user facing alert if SSOe is down, but we'll still need to define a maintenance window and add a health check monitor

**Comment by ambikaroos** [comment] 2020-03-04 20:21
Moving to Icebox in favor of #6528

**Comment by bridgethapner** [comment] 2020-03-12 15:31
@ambikaroos Moving to ready for content + UX work. #6528 can remain ticket for dev work.

**Comment by bridgethapner** [comment] 2020-03-12 15:45
Hi there @peggygannon - This ticket has been re-prioritized for SSOe launch as we have determined that when SSOe is down, sign in to VA.gov is down as well. 

Due to the fact that authenticating on VA.gov is inaccessible when SSOe is down, I used the existing "Our sign in process isn’t working right now" red error message. 

There are 2 reasons SSOe might be down: unplanned outage and planned maintenance. This alert definitely works for an unplanned outage, and _could_ work for planned maintenance IMO. Are you aware of any planned maintenance messaging on VA.gov today?

Wireframe of the error message to use in case of SSOe outage: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409053575

**Comment by peggygannon** [comment] 2020-03-18 16:46
Hi, @bridgethapner I have one clarifying question. 

I thought we were moving to single sign on, and as such do we need a specific VA.gov sign in message? 

Is this ticket meant to "unbrand" all of our sign in downtime notification messages?

**Comment by bridgethapner** [comment] 2020-03-18 17:12
That's a good question @peggygannon - I think we can keep this message focused on VA.gov somewhat and allude to other sites as we did with the modal. Maybe something like "We’re working to fix some problems with our sign in process, which is impacting VA.gov and also may be impacting some other VA sites. If you’d like to sign in to VA.gov, please check back later." 

The other sites that are affected should have their own downtime messages too, but we don't know exactly what those messages are.

**Comment by peggygannon** [comment] 2020-03-18 20:12
Hello @bridgethapner here is the recommended downtime message for SSOe outage. I also posted this in the wireframe. 


**Our sign in process isn’t working right now**
We’re working to fix some problems with our sign in process, which is affecting VA.gov and some other VA sites. If you’d like to sign in to VA.gov, please check back later.

**Comment by bridgethapner** [comment] 2020-03-19 15:45
Thanks @peggygannon!

@hinzed1127 copy for down message is in Peggy's comment above and in [desktop](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/409053575) and [mobile](https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/screens/409260164) wireframes too.

**Comment by peggygannon** [comment] 2020-03-19 20:19
Thanks, @bridgethapner Updated wireframes look good!

**Comment by hinzed1127** [comment] 2020-03-26 21:37
@patrickvinograd  given Damien's comments about a health check endpoint, is there a viable way to check for this right now to display a message this specific?

**Comment by annaswims** [comment] 2020-04-03 22:33
FWIW, the alerts are triggered when the ratio of login attempts (user clicked the "log in with x" button on our sign in page) to login success (we received a successful saml response) is low.  

So, regardless of the root cause, the "our sign in isn't working now..." will likely be appropriate for either identity broker being down.  Right now it is triggered by the id.me success rate and the id.me success rate will be low if SSOe is troubled.  

ID.me planned downtime has been quite rare so we haven't had any messaging for planned downtime.

**Comment by hinzed1127** [comment] 2020-04-06 18:06
@annaswims thanks for the clarification. I'll double check, but I'm guessing that might be sufficient for the scenario we're aiming to cover here.

**Comment by hinzed1127** [comment] 2020-04-07 19:25
@bridgethapner I guess this falls back to a design question. Is the existing generic "our sign in isn't working now..." sufficient? 

The same notifications apply and are present on the modal and standalone page, so there shouldn't be any discrepancies there.

**Comment by bridgethapner** [comment] 2020-04-08 15:55
Hi there @hinzed1127 -- Yes I think that message is sufficient for any unplanned reason SSOe is down. 

If possible, it would be useful to designate a down message for planned SSOe maintenance. The benefit of doing so would be letting people know when they should check back when there is a planned time sign in will be back up. 

Is it correct to say when SSOe is undergoing maintenance, all VA.gov sign in is down? If so, the message could be something like this (would want to get content input before implementing - can we implement something like this?)

![PlannedWork_SSOe_downmsg.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/3e1898f4-3b83-4700-b619-8685c534e91f)

**Comment by hinzed1127** [comment] 2020-04-09 17:36
@bridgethapner I don't think we need to account for that now, but more in the event that such planned maintenance were on the horizon. I honestly don't know how often that would be an issue, but something to surface as a quick question to the IAM team. There are past examples of schedule downtime notifications in `vets-website`, so it would probably be something to add if and when such maintenance were to occur.

We're on the email distribution list of SSOe partners, so any disruption of that nature should be communicated to us in advance.

**Comment by hinzed1127** [comment] 2020-04-21 19:12
I think this can be considered closed given previous responses and use cases covered right now around downtime

**Closed by hinzed1127** 2020-04-21 19:12 UTC
Labels: SSO Launch, SSO-Login, design
