### ISSUE TITLE
The education statement of benefits is showing incorrect benefit end dates for some users

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#43379] opened 2022-06-24 20:14 UTC
## Background
Users in receipt of P911 education benefits can use the [Statement of Benefits tool](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/) to see how much of their benefits they've used and how much they have left to use for education or training.

A while back, some users began reporting to the Education Service call center (ECC) that when trying to view the tool after logging in, they were seeing incorrect end dates (the tool itself uses the term 'Delimiting Date" for end date).

Access to the tool was removed from VA.gov ~07/15/22 (the access point was removed, the tool itself wasn't) to prevent users from seeing inaccurate dates.

# Current behaviour
Some users are reporting they are seeing incorrect end (delimiting) dates when accessing their Statement of Benefits on VA.gov.

## Expected behaviour
Logged-in users see correct start and end (delimiting) dates when viewing their Statement of Benefits on VA.gov.

**Comment by saderagsdale** [comment] 2022-06-27 13:47
@michelpmcdonald I pinged Chante again. She took the action item to schedule a meeting, so just waiting for it to hit calendars.

**Comment by saderagsdale** [comment] 2022-06-27 19:35
Note @cohnjesse: Reach out to Jennifer Waltz first, then Eddie Keith as a backup.

**Comment by mattpointzxer0** [comment] 2022-06-28 16:15
Received a sample case, i'll transmit it via email as it contains PII.

**Comment by saderagsdale** [comment] 2022-06-29 16:07
@cohnjesse same question here. shall we move this to in progress?

**Comment by cohnjesse** [comment] 2022-06-29 16:42
@saderagsdale I am not on a sprint team so my thinking is that the tickets I work on should stay out of the sprint.

**Comment by saderagsdale** [comment] 2022-07-11 18:27
@cohnjesse What's the progress status on this one?

**Comment by cohnjesse** [comment] 2022-07-11 19:11
@saderagsdale This turned out to be an issue with EVSS and they pushed a fix and the issue is now fixed in production. I will close this ticket.

**Closed by cohnjesse** 2022-07-11 19:11 UTC
Labels: bug, education, benefits-crew, benefits-team-1
