### ISSUE TITLE
Review order information page

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#98206] opened 2024-12-03 18:21 UTC
## User story

- As a Veteran ordering medical supplies, I want to have the assurance that my order has the correct shipping and contact information and have the opportunity to look at my order details.
- As a Veteran ordering medical supplies, I want to be able to update the details of my order before fully submitting it to be shipped out. 
- As a Veteran ordering medical supplies, I want to be able to submit my order for processing. 

## Possible tasks/User actions

- Veteran is shown the order details
   

   - [ ]  With contact information and selected supplies

- Veteran wants to update order details
  

    - [ ]  Need to investigate how to Navigate between form pages
- Veteran clicks button to submit the order

   - [ ]     Order is submitted to the API
   - [ ]     Need to process success and errors from API
   - [ ]      What happens on an API error?
   - [ ]         server error
   - [ ]         invalid order
   - [ ]         Is there a danger of the login timing out? If the form is automatically saved then the user can just resume the order -  _login will time out after 15 minutes of interaction, but the user should be able to resume with SiP_

**Comment by radavis** [comment] 2024-12-12 21:26
Duplicate of #96508

**Closed by radavis** 2024-12-12 21:26 UTC
