### ISSUE TITLE
Decision Review pages: Update Hub Page and Nav

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6800] opened 2020-03-11 22:12 UTC
# Decision Review pages: Create a new Hub Page

This is follow on work that should happen _after_ ticket #5541 is completed. It is interrelated to other tickets to updating the DR/AMA pages (like adding left nav; determining any updates to the IA). 

__Problem description:__
The Decision Review pages currently live on GH. During benefit hub migration into the CMS in 2019, these DR pages could not be migrated because they had too many content anomalies. 

__Action:__ 
In order to move these pages into Drupal, we need to remove or otherwise resolve these anomalies. Hub page and Nav needs to be updated to house these "Decision Review Pages"

__Checklist:__
[ ] Update Hub Page and Nav for Decision Review Pages

__Pages:__

1. VA decisions reviews and appeals https://www.va.gov/decision-reviews/
2. After you request a decision review https://www.va.gov/decision-reviews/after-you-request-review/
3. File a Supplemental Claim with new evidence  https://www.va.gov/decision-reviews/supplemental-claim/
4. Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
5. Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/
6. After a Board Appeal ... https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
7. Multiple party contested claims https://www.va.gov/decision-reviews/multiple-party-claims/
8. Fiduciary claims https://www.va.gov/decision-reviews/fiduciary-claims/
9. Insurance claims https://www.va.gov/decision-reviews/insurance-claims/
10. FAQs https://www.va.gov/decision-reviews/faq/
11. Get help with... https://www.va.gov/decision-reviews/get-help-with-review-request/

**Comment by MickinSahni** [comment] 2020-03-16 15:55
2020-03-16 PW Standup
* @lwalsh617 to confirm whether this and #6799 are dupes, etc.

**Comment by lwalsh617** [comment] 2020-03-17 13:20
@MickinSahni I am closing this ticket because it is a duplicate of 6799 (new hub page)

**Closed by lwalsh617** 2020-03-17 13:20 UTC
Labels: vsa-public-websites

**Comment by MickinSahni** [comment] 2020-03-17 20:51
thanks, laura. removing from sprint and estimate
