### ISSUE TITLE
[Other] Outdated form URL indexed in search tools (00.00.1)

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#52215] opened 2023-01-19 04:09 UTC
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
Authenticated 22-1990e Transfer of Entitlement (TOE) Form Updates

#### Point of Contact/Reviewers
Sara Sterkenburg - @sterkenburgsara - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found. This issue does not directly map to a VA.gov experience standard or WCAG standard

### Issue Details
If users search for this form using VA.gov's find a form feature, the best-bet URL in place is correct, but the link within the form details page is not.

This issue was identified post-staging review, at the additional staging review held with the Sitewide Content and IA team's staging review for the static Drupal entry page for the 22-1990e form. 

### Link, screenshot or steps to recreate
Screenshot of VA.gov search results (with old URL):
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50482_Sara_00001.png

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 2.4.5_AA

### Platform Recommendation
If you find the 22-1990e form via the find-a-form tool, the best-bet link itself is accurate. However, the find a form detail page then links out to the 1990e, and that link is what needs to be updated. It's not a search issue with the best bet., its an issue with the Find a form detail page. (per @mnorthuis )

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by sterkenburgsara** [comment] 2023-01-19 20:14
Mentioned at staging review for static page //cc @bethpotts @RLHecht

**Comment by shiragoodman** [comment] 2023-01-19 20:36
FYI @btruongafs  - This issue was discovered during the TOE Form 22-1990e Static Page staging review with Sitewide Content and IA team. However, the issue is applicable to your product. Please let me know if you have any questions. Thanks!

**Comment by btruongafs** [comment] 2023-01-25 18:24
@shiragoodman this is a change outside of our app. who is responsible for updating the Find Forms?

**Comment by sterkenburgsara** [comment] 2023-01-25 18:39
@btruongafs @shiragoodman - We discussed this at staging with @bethpotts @RLHecht @katherine-fung on the call. It is my understanding that their team is handling it. You can go ahead and close this issue.

**Comment by btruongafs** [comment] 2023-01-25 21:38
@sterkenburgsara thanks for the clarification. Closing out.

**Closed by btruongafs** 2023-01-25 21:38 UTC
Labels: ia, collab-cycle-feedback, afs-dgib, Staging, CCIssue00.00, CC-Dashboard, my-education-benefits, authenticated-22-1990e
