### ISSUE TITLE
Address hanging / lonely caret for action links on the home page

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#89477] opened 2024-07-29 15:35 UTC
### User story

As a Veteran, I want action links to be clear and not confusing me by being broken up in a weird way when screen size changes.

### Notes
- [See note from Kaitlin in our channel](https://dsva.slack.com/archives/C0581MN69TJ/p1722003847354279)
- To explain, when the screen size changes, sometimes action links on our page (those followed for a right-point caret) end up with the caret on a second line, sometimes with no word(s) attached.
- If the link is too large and the caret needs to move to the second line, then at least one word of the link text should also drop to the second line so it's clear the caret is part of the link

### Tasks:

- [ ] Identify range of device widths that show the behavior
- [ ] Approximate number of users affected

## Acceptance criteria
- There is no screen size that allows for a caret to be alone on line 2 of link text

**Comment by jzucadi** [comment] 2024-07-30 20:51
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31107

**Comment by LynneJohnson224** [comment] 2024-07-31 16:52
@jzucadi can you please add a story point estimate?

**Comment by jzucadi** [comment] 2024-08-14 19:27
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31107

**Comment by LynneJohnson224** [comment] 2024-08-22 16:32
@carlosfelix2 @dcloud @radavis - this PR looks like it might be ready to merge - can you please take a look and see if we can move this ticket through the process?

**Comment by dcloud** [comment] 2024-08-26 16:31
The now-closed PR didn't address the issue for most browsers, just the very recent versions that support an advanced text layout algorithm enabled via `text-wrap: balance;`

Reposting my comment on the PR:

> Per [Google](https://developer.chrome.com/docs/css-ui/css-text-wrap-balance):
> 
> > Without text-wrap: balance; designers, content editors and publishers have [few tools](https://developer.mozilla.org/docs/Web/CSS/CSS_Text/Wrapping_Text) to change the way lines are balanced.. The best options available being to use  or [­](https://developer.mozilla.org/docs/Web/CSS/hyphens) to help guide text layouts into smarter decisions about where to break lines and words.
> 
> The tools that are mentioned focus on wrapping long strings of text that ordinarily wouldn't break, whereas this scenario involves a place where there is a natural break between "words", though it looks displeasing to people.

**Comment by dcloud** [comment] 2024-08-26 19:14
Also did a quick test of the `va-link` component and can reproduce hanging chevron with the VADS component when the text is long enough, and presumably would happen if I made a `va-link` render at the same font size as the `mhv-c-navlink` we use.

For some historical knowledge, the `mhv-c-navlink` class was created from a copy of `va-link`, then altered to support the style customizations (font-size, different alignment on mobile, etc) that was asked of the team.

**Comment by katbrinkley** [comment] 2024-08-26 19:17
It seems that this only happens if the screen is large enough for 2 gray boxes to be next to each other on the same line, but not when they’re stacked directly on top of each other. Mobile is likely not affected because the gray boxes are vertically stacked, but ipad and desktop resolutions between 769 px and 1201 px will be affected. As the longer lines’ carets fall onto the second line, the shorter lines adjust and they go back to normal.

Starting point in staging: 320 x 800 px 
768 px - when boxes go from vertically stacked to 2 side by side (caret still fine)
769 px - first caret falls off (Appointments box; Schedule a new appointment)
781 px - second caret falls off (Appointments box; Manage upcoming appointments)
946 px - third caret falls off (Medical supplies box; Learn how to order other medical supplies)
962 px - fourth caret falls off (Medical supplies box; Order hearing aid batteries and accessories)
1201 px - all carets go back to same line

**Comment by wesrowe** [comment] 2024-10-02 18:12
Addressed in another ticket.

**Closed by wesrowe** 2024-10-02 18:12 UTC
Labels: development, engineering, needs refinement, Cartographers
