### ISSUE TITLE
AWS access changes for AMT Service Account

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#42260] opened 2022-06-02 22:05 UTC
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Other

### Your Name

Carl Alquisola

### Your Email

carl.alquisola@adhocteam.us

### Your Team, Role, and Company

Access Management, Senior Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Saipriya Gopalakrishnan

### Product Owner (PO) name and email

Thomas D., thomas.delrue@va.gov

### Desired AWS Access

Please give AMT's service account access to these terraform state files 
- dsva-shared-terraform-remote-state/terraform.tfstate.platform-keycloak-dev
- dsva-shared-terraform-remote-state/terraform.tfstate.platform-keycloak-utility

Please also give our service account "terraform -apply" permissions.  We'll only be using "terraform apply" within our Keycloak instances. Our terraform files are located [here](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/applications/keycloak). 

Our workflow will be running within a self hosted runner. We also requested access for self hosted runners in a different [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42261). 

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jsgarmon** [comment] 2022-06-17 19:08
@calquisola : the service account has been updated with permissions to modify keycloak statefiles.

In the future, you'll probably be better off using the [Ops issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+needs-grooming%2C+operations&template=ops_issue_template.md&title=), as the AWS access issues are for humans.

**Comment by calquisola** [comment] 2022-06-17 19:27
thanks! very much appreciated.  Will check

**Comment by jbritt1** [comment] 2022-06-21 13:32
@calquisola, are things working as intended?

**Comment by calquisola** [comment] 2022-06-21 14:27
hi! @iriteshp is testing it right now.  We'll let you guys know.

**Comment by iriteshp** [comment] 2022-06-21 20:12
I was able to do a plan and apply it from my local machine. I could not test from workflow because we do not have self-hosted runners yet. Thanks!

**Comment by jsgarmon** [comment] 2022-07-06 13:22
Following up on this, can we close this issue?

**Comment by calquisola** [comment] 2022-07-06 13:50
yes. you can close this. thanks!

**Comment by iriteshp** [comment] 2022-07-18 14:55
@jsgarmon I tried to apply the terraform on keycloak. it gives me access denied error as below:

```
╷
│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: AccessDenied: Access Denied
│ 	status code: 403, request id: R1KHJEYACYBF8K6T, host id:
│ +3voy+c/VCHNChgUhCHWCHcO07k5tW5v9PlhheWs46hO6WQ2z+6ZIMdh6oeWcJ2ghRr8oKXz7GA=
╵
╷
│ Error: Failed to persist state to backend
```

I am able to do terraform plan, but not apply. can you please help me with this? Thanks!

**Comment by iriteshp** [comment] 2022-07-18 16:11
got access now.

**Closed by iriteshp** 2022-07-18 16:11 UTC
Labels: operations, external-request, ops-access-request
