### ISSUE TITLE
Testing an auth'd endpoint with PACT

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#10355] opened 2020-06-17 13:08 UTC
## Issue Description
Getting an end-to-end working example with the search endpoint would take priority, but we'll need to consider testing an auth'd endpoint.

---
## Tasks
- [ ] Choose an auth'd endpoint to start with

**Comment by meganhkelley** [comment] 2020-08-05 13:13
Duplicate of #11565

**Closed by meganhkelley** 2020-08-05 13:13 UTC
Labels: backend, tools-be
