### ISSUE TITLE
Copy of 10-10d, 10-7959c: Verify save in progress 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84578] opened 2024-06-04 14:45 UTC
- 10-10D:
  - Verify save in progress (should be already set up)
- 10-7959c:
  - Verify save in progress (should be already set up)

**Comment by michaelclement** [comment] 2024-06-04 20:06
Duplicate of #84576

**Closed by michaelclement** 2024-06-04 20:06 UTC
Labels: 10-10d, ivc-forms, 10-7959c
