### ISSUE TITLE
Content Update for eBenefits (Rated Disabilities)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5403] opened 2020-01-31 21:37 UTC
### Description of request
*Detailed description of the request including background information and reason for the request*

 1. Is the request related to a VA.gov tool? If yes, provide brief description of the tool or functionality: _The Rated Disabilities static landing page needs a link to it from the Disability hub.  It looks like ([per Mikki](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2584); and we will make a separate request for the calc tool) the best place for this is to add as the second option under the "Manage" section on this page: https://www.va.gov/disability/.  So far, this has been the language used for that content:_

**Header: View your VA disability rating >
Description: See your combined VA disability rating as well as individual disabilities.
_Where the Header links to: https://staging.va.gov/disability/view-disability-rating/_**

 2. Provide a link to product brief or outline: _https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/README.md_
 3. Provide a link to wireframes, prototype: _https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/_
_https://app.moqups.com/Rnc4BDEKrA/view/page/ac5c05e4d_
 4. Provide a link to any user research synthesis: _N/A_
 5. Do you need new URLs, redirects? (If yes, submit URL and redirect requests first to @ Mikki Northuis on the Platform team.): _None needed at this time._
 

### Desired/target implementation date
Is there an ETA for a particular launch or completion date when request needs to be completed (for instance, for a user research session or eBenefits migration)? 
After UAT, Tuesday - Friday (2/4-7)

Our team's capacity will determine which sprint the work falls into.

### Type of support request
*Select all applicable* 

- [ ] Content support for authenticated app/tool. Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer.

In addition to the above general information, include:
      1. Word document with draft if available, or link to the URL where the draft content appears:
      2. Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      3. Scope: How many screens? (Or messages, etc.) 
      
      
- [x] Content support for a static public website page
      1. Is this to update existing static content? _Yes_
      2. Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.) _No_
      2. Provide a list of URL/s that need to be reviewed or updated. _https://www.va.gov/disability/_

The Rated Disabilities static landing page needs a link to it from the Disability hub.  It looks like the best place for this is the second option under the "Manage" section on this page: https://www.va.gov/disability/.  So far, this has been the language used for that content:

Header: View your VA disability rating >
Description: See your combined VA disability rating as well as individual disabilities.
_Where the Header links to https://www.va.gov/disability/view-disability-rating/_

      3. If it's a small copy section, list what the new info should be and what it is replacing.  (See above)

- [ ] FE engineering
      1. [Let's get Nick and Kelson to provide input here on what kind of details they typically need to get started]
      2. [more stuff???]
      
### Requestor info
*Indicate what team and who the primary contacts are on your team* 

Team name: *eBenefits*

DEPO product owner: *Steve Kovacs*

Product manager: *Jason Wolf*

Designer: *Jim Adams*

FE engineer: *Micah Chiang & Jesse Cohn*

Product/team Slack channel: *vsa-ebenefits*

### Steps to complete [UNLCLEAR WHO THIS SECTION IS FOR. IS THIS FOR THE REQUESTOR TO FILL OUT OR FOR PUBLIC WEBSITE PM?]

- [x] I've provided the __Description.__
- [x] I've provided the __Desired/target implementation date.__
- [x] I've selected all relevant __Type of request.__
- [x] I've filled out the __Requestor info.__
- [x] Issue is labeled with the relevant practice areas: Content, frontend
- [x] Request is assigned  *Public Websites Team* and *@ with Kara Kamahi and Jennifer Lee* for intake

**Comment by MickinSahni** [comment] 2020-02-05 17:05
@lunascoop to review/estimate before dragging into Sprint 14 (assuming we have the room).

**Comment by MickinSahni** [comment] 2020-02-12 18:36
2020-02-12 PW Sprint Planning
- Closing as a dupe of the IA ticket that was initially created

![image](https://user-images.githubusercontent.com/13204473/74365758-b4191100-4d9c-11ea-8827-39b627affc87.png)

**Closed by MickinSahni** 2020-02-12 18:36 UTC
Labels: content, vsa, vsa-public-websites
