### ISSUE TITLE
Upcoming Appointments List (UI)

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#13971] opened 2020-09-23 17:45 UTC
## User story
As a user, I want to see a list of my upcoming appointments so that I can plan ahead.

## Acceptance Criteria
1. Selecting "Upcoming" in the segmented selector navigates to the upcoming list of appointments
2. Styling and UI matches the design
3. The "Upcoming Appointments" section should list any appointments in the future, organized by proximity to current date (e.g. In a situation where it's October 1st, the order of appointments from top to bottom would be October 3rd, October 10th, November 6th, November 22nd, etc.) 
     - Appointments are grouped by month. Each section is labeled with the month in the top left. If there are no appointments in that month, that month name/ section should not appear. 
     - This list should include "Canceled" appointments as well, until the date of the canceled appointment has passed (UI covered in a [separate story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15739)) 
4. Each appointment in the list should include the date in [Day], [Month XX, XXXX] at [00:00] [am/ pm] [Timezone] format
     - The timezone should match the timezone the clinic is in (6 timezones)
5. The location or appointment type (if virtual) should be listed below the day/time
     - For VA Appointments and Community Care appointments, the VA Medical Center name or Community Care facility name should be shown
     - For virtual appointments the specific appointment type should be listed:
          - VA Video Connect at home
          - VA Video Connect at an ATLAS location
          - VA Video Connect at a VA location
          - VA Video Connect using a VA device

Covered in separate stories: Selecting an appointment takes the user to the details page for that appointment

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432442341

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Appointments" as Header 1

**Segmented Selector**
- accessibilityLabel="upcoming"
- accessibilityHint="view your upcoming appointments"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector

**List of Upcoming Appointments**
- accessibilityLabel= "upcoming appointments list"
- accessibilityRole= "menu"
- Mark each section title (e.g. September 2020) as Header 2
- For each field:
     - accessibilityLabel= field title (e.g. Friday, September 25, 2020 11:15 a.m. ET)
     - accessibilityHint= "view details of this appointment"
     - accessibilityRole= "menuitem"
     - accessibilityValue= contents of field
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by b-rocha** [comment] 2020-09-23 21:59
Which timezones should we account for and what abbreviations should we use? Here's a potential list:
- Pacific Time (PT)
- Central Time (CT) 
- Mountain Daylight Time (MDT)
- Mountain Standard Time (MST)
- Eastern Time (ET)
- Alaska Time (AT)
- Hawaiian Aleutian Time (HT)

@bridgethapner

**Comment by bridgethapner** [comment] 2020-09-23 22:51
@b-rocha This is a really good question! I am not sure -- I may be misspeaking here, but I think since the time zones as represented in the Appointment Titles are responses from the API, so we shouldn't have to worry about accounting for them or developing a list. @kreek, can you help answer this question?

**Comment by kreek** [comment] 2020-09-23 23:43
Mobile app wont't have to worry about it.

Looking at the VAOS va.gov website [code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/appointment-list/components/cards/confirmed/AppointmentDateTime.jsx#L23) it's figuring out the timezone by the facility id in the browser (in JS/React). For the mobile app we want to move that logic server side and just return a string with the date in the correct timezone.

**Comment by b-rocha** [comment] 2020-09-24 20:36
@bridgethapner @kreek Great, thanks for clarifying!

**Comment by digitalken** [comment] 2020-11-17 18:53
Added to TestRail.

**Comment by digitalken** [comment] 2020-11-20 23:42
Pass on UI / functionality, fails on accessibility. Moving to Design QA.

**Closed** 2020-12-21 16:07 UTC
Labels: DF, frontend, mobile API, va-mobile-app
