### ISSUE TITLE
[Discovery] Scheduled runs start at/near top of the hour

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#32702] opened 2021-11-10 15:49 UTC
## Description

It was noticed and observed that if a cron is scheduled at the top of the hour, there is usually a queue/wait time before it starts. While this is acceptable, what is noticed is it can potentially start until quarter past. See timestamps of screenshot

![image](https://user-images.githubusercontent.com/10648480/141146041-d0a8fffe-f792-4b1e-a590-1c5b5d974420.png)

**Comment by oseasmoran73** [comment] 2021-11-10 21:10
[Documentation](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events) from Github 

>Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.

@meganhkelley Going to follow up with the Github Team to investigate the definition of "high loads" and try to gather data for `vets-website` and `content-build`. `vets-website` seems bit reasonable, but we don't get much flow in `content-build` so bit curious as towards why

**Comment by oseasmoran73** [comment] 2021-11-12 22:39
>Hey Oseas Moran, so this is across all GitHub, not just your repository. The top of the hour and every 15 minute interval are the busiest. 12-3AM are the busiest times. The best thing you can do for yourself is set them to run at arbitrary times, such as “18 minutes past the hour.” Our compute teams are constantly working to bring this delay down, and they have been successful in getting down from hours to usually minutes.
2:22
They continue to work with the Azure Scale Set teams to get better scaling, and are even working on moving to a new Scale offering that Azure is working on. But some of these cron times cause a flux of multi-million cores that need to be provisioned.
2:22
Some of the numbers of the GitHub-Hosted runners are just crazy, when you think about a single service consuming million’s of core’s of compute at any moment in time
2:23
I know not the answer you were looking for, but laying our cards on the table. We are aware of the pain, and have a team of 30 engineers whose only job is to get that provision time even lower

[Slack](https://dsva.slack.com/archives/CU1E4CX9U/p1636582862123200) convo. It looks like this is a bit out of our scope and control. Shall we keep this ticket around or close @meganhkelley @timwright12

**Comment by timwright12** [comment] 2021-11-15 19:23
I think our options here are to offset by 5mins or just wait out the solution. Personally, I think they're well aware of the issue and will have a reasonable resolution in a timely manner so I would put this down and circle back in a couple weeks to check in. We have enough bugs to work on in the meantime

**Comment by meganhkelley** [comment] 2021-11-15 22:52
I have questions! :) 

(1) Does this only affect the scheduled job? Or would it also impact a manual content release that was triggered at say 8:30 (assuming the 30 min mark is another high traffic time)? 

(2) Relatedly, what would happen if at 9:10 (action A) the scheduled release still hadn't kicked off and (action B) someone triggered a manual content release? Would action B queue behind action A?

**Comment by oseasmoran73** [comment] 2021-11-22 23:02
@meganhkelley 

> (1) Does this only affect the scheduled job? Or would it also impact a manual content release that was triggered at say 8:30 (assuming the 30 min mark is another high traffic time)?

Yes. It primarily only affects scheduled jobs. The reason I say primarily is because all manual content-releases that I have seen still has a wait-time, but ranges between 30seconds - 1 min at most.

> (2) Relatedly, what would happen if at 9:10 (action A) the scheduled release still hadn't kicked off and (action B) someone triggered a manual content release? Would action B queue behind action A?

Technically, action B should queue behind action A. As of now, there can only be a max of two in the queue. So the current workflow is

Some content-release flow still currently running --> Action A (scheduled) is queued --> Action B (manual trigger) is queue (and Action A is now cancelled)

Does this have any major impact? Technically it does in the sense that the updated contented from action A is in action B since it is using the same tugboat/drupal address

**Comment by meganhkelley** [comment] 2021-11-23 20:24
Closing — ideal solution is for GitHub Actions to improve this functionality. In the meantime, the issue is not severe enough to warrant a FE Tools workaround.

**Closed by meganhkelley** 2021-11-23 20:24 UTC
Labels: tools-fe
