### ISSUE TITLE
Facility Locator - linked map pin goes to page without main content

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#2792] opened 2019-10-25 21:15 UTC
## What happened?

On the Facility Locator tool I tested a couple of cities and interacted with the map, clicked a pin, but the page that displayed only shows the header and footer with no content area.

## Specs:
- Device: MacBook
- Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- Test User _(if applicable)_: N/A

## Steps to Reproduce

1. Chicago Example URL: https://www.va.gov/find-locations/?address=chicago&context=Chicago%2C%20Illinois%2C%20United%20States&facilityType=health&location=41.8756%2C-87.6244&page=1&serviceType&zoomLevel=4
- No test user needed
- Click on the pin near Shaumberg

2. Dallas Example URL: https://staging.va.gov/find-locations/?address=Dallas%2C%20TX&context=Dallas%2C%20Texas%2C%20United%20States&facilityType=all&location=32.77688335023984%2C-96.79779052734376&page=1&serviceType&zoomLevel=9
- No test user needed
- Click on the pin above Benbrook (on the left side)

## Desired behavior

I expected content for the facility related to the pin would render between the header and footer.

## Acceptance Criteria
- As a user, if I click on any of the pins on the map, I expect to see content related to that pin rendered in the appropriate VA.gov page template.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [Ongoing Maintenance] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [product support] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [frontend] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by jenstrickland** [comment] 2019-10-25 21:18
Step 1 - click the pin near Shaumberg <img width="977" alt="facilitylocator-bug1" src="https://user-images.githubusercontent.com/57469/67605071-55774b00-f74b-11e9-9097-9926d190b5d8.png">

Step 2 - this is what renders <img width="975" alt="facilitylocator-bug2" src="https://user-images.githubusercontent.com/57469/67605072-55774b00-f74b-11e9-9db0-c1fdd8790ca7.png">

Same behavior for the Benbrook pin in the Dallas URL.

**Comment by mmiddaugh** [comment] 2019-12-30 15:45
Revisit after MVP redesign

**Comment by davidconlon** [comment] 2020-01-30 13:28
@mmiddaugh flag for retest, I think this is fixed.

**Comment by jenstrickland** [comment] 2020-01-30 20:46
@mmiddaugh @davidconlon — tested, and it is indeed fixed. 🥇

**Comment by mmiddaugh** [comment] 2020-01-30 23:16
Happily closing as the issue is resolved

**Closed by mmiddaugh** 2020-01-30 23:16 UTC
Labels: bug, frontend, vsa-facilities
