### ISSUE TITLE
Update backend processing that removes ICN

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12107] opened 2020-08-05 17:18 UTC
Given that CARMA could only process veterans as verified or unverified
We remove ICN for veterans that aren't found in eMIS.

Once CARMA updates their logic,
We can send them ICNs for those individuals
To make processing easier. 

See: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/carma/models/submission.rb#L13 

**Suggested Solutions**
1) Move this business logic to CARMA (have the CARMA devs run the logic on their end, and we always sent the ICN when found).
2) [since CARMA isn't willing to put this logic on their end] Add an additional property to all person's metadata of "personType" that is "VERIFIED_VETERAN" | "NON_VERIFIED_VETERAN" | "PERSON" etc. - what ever their person types are. This is more explicit and less bug-prone.

**Comment by mlighdc** [comment] 2021-05-28 03:07
@kevinmirc  and @ala-yna is this a duplicate of #12212

**Comment by ala-yna** [comment] 2021-05-28 20:56
I'm not sure - @kevinmirc ?

**Comment by kevinmirc** [comment] 2021-06-01 15:31
Not a duplicate, this ticket is just a refactor to allow CAMRA to receive the ICN for the veteran but still mark the veteran in CARMA as unverified.

**Comment by tchrisdyer** [comment] 2021-06-09 14:45
Closing this unless there is an explicit need by CARMA.

**Closed by tchrisdyer** 2021-06-09 14:45 UTC
Labels: Epic, tech-debt, vsa-caregiver
