### ISSUE TITLE
<CAIA Content> Fiscal Year 2024 Chapter 30 COLA Rates <VACO>

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#63277] opened 2023-08-08 15:02 UTC
## About your team

- **Team name:** Education Services
-	**OCTO-DE product owner**: 
-	**Product manager**: 
-	**Designer**: 
- **Accessibility specialist**:
- **Content writer**: 
-	**Slack channel**:
 
### Describe what you need in a few sentences:

Assess what’s needed as far as updates to the current, future, and past rates pages.
And then update those pages.

### Tasks
- [ ] Assess work required for updates to current and future rates pages
- [ ] Make updates

### Type of CAIA Support
Which areas of CAIA
- [x] Content
- [ ] Accessibility
- [ ] IA

**- Supporting Documents** [https://app.zenhub.com/files/133843125/b8ca19df-c72f-43c3-9b7b-95880f0c7a97/download](https://app.zenhub.com/files/133843125/b8ca19df-c72f-43c3-9b7b-95880f0c7a97/download)

**Comment by coforma-terry** [comment] 2023-08-08 15:05
Tagging @bethpottsVADEPO for visibility

**Comment by kristinoletmuskat** [comment] 2023-08-11 19:48
This sounds like a drupal update with no IA, so I'm untagging myself!

**Comment by laurwill** [comment] 2023-08-15 04:13
This is a dupe of [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63277) — closing out!

**Closed by laurwill** 2023-08-15 04:13 UTC
Labels: sitewide content, sitewide CAIA
