### ISSUE TITLE
Error creating va appointment - proposed

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33278] opened 2021-11-26 15:23 UTC
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2617 still exists
- This is also a duplicate of https://issues.mobilehealth.va.gov/browse/VAOSR-2451
- Coordinate with VAMF as needed to resolve

**Comment by grossb1** [comment] 2021-12-10 17:57
This is a duplicate of VAOSR-2451

**Comment by grossb1** [comment] 2021-12-10 18:02
We will still need to test creating the va appointment request prior to closing this ticket.

**Comment by grossb1** [comment] 2021-12-13 18:49
The following POST (https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012845331V153043/appointments) is timing out:
{
  "kind": "clinic",
  "status": "proposed",
  "locationId": "983",
  "contact": {
    "telecom": [
      {
        "type": "phone",
        "value": "2125688889"
      },
      {
        "type": "email",
        "value": "judymorisooooooooooooon@gmail.com"
      }
    ]
  },
  "serviceType": "primaryCare",
  "reasonCode": {
    "coding": [
      {
        "code": "Routine Follow-up"
      },
     "text": "text"
    ]
  },
  "comment": "test",
  "extension": {
    "desiredDate": "2021-06-15T23:59:00.000+00:00"
  },
  "patientIcn": "1012845331V153043"
}

**Closed** 2021-12-15 17:30 UTC
Labels: backend, vaos, testing, VAMF
