### ISSUE TITLE
Refresh-appointment list empty states

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25304] opened 2021-05-26 19:26 UTC
## Description
When there are no appointments to list based on the user's selection, display respective message.

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#empty-states)

## Definition of Done
- [ ] All acceptance criteria are met

---

**Original Description**

Log in as a veteran without any appt requests:  alfred.castillo@id.me or granath.e.woolever@id.me
On the home page under "Your Appointments" select "Requested"  from drop down list.

VAOS shows the following:  
You don’t have any appointments
You can schedule an appointment now, or you can call your VA medical center to schedule an appointment.

Schedule an appointment

Veteran does have appointments on upcoming appointment tabs so to say " You don't have any appointments" is incorrect.  And then maybe tweak the second line as well.

**Comment by jbalboni** [comment] 2021-05-26 19:28
@laurenernest I think this is an issue on all of the different views on the refreshed appointment list page. That text was reused from the current list page and it doesn't make sense for the past, requests, of canceled pages.

**Comment by laurenernest** [comment] 2021-05-27 23:09
I'll get a recommendation from Content

**Comment by jbalboni** [comment] 2021-06-15 14:15
@laurenernest Is there an update on this? It'd be good to get this fixed before homepage refresh launches, since I suspect it's not uncommon for users to have an empty list of requests.

**Comment by laurenernest** [comment] 2021-06-15 14:46
It's being reviewed as part of collab cycle 👍

**Comment by laurenernest** [comment] 2021-07-19 21:48
Top lines look good. The message body should say "...or call your..." instead.
![Screen Shot 2021-07-19 at 2.45.10 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/5f148b69-c5a1-434b-b1ce-c2ae0f5f4118)

**Comment by jbalboni** [comment] 2021-07-20 19:32
@laurenernest This should be fixed on staging now

**Comment by laurenernest** [comment] 2021-07-20 20:16
Confirmed. Thanks!
![Screen Shot 2021-07-20 at 1.15.44 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/67c2d8d3-e761-4bcd-839b-6b9f5f7b4dc0)

**Closed by laurenernest** 2021-07-20 20:16 UTC
Labels: frontend, vaos
