### ISSUE TITLE
[FE] 10-10EZR Emergency Contact: Refactor EC Code and update Unit Tests

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#93154] opened 2024-09-18 19:09 UTC
As a team member, I would like good code coverage with unit tests so that I know our application works before I ship it.

- [x] Refactor config EC files 
- [x] Update E2E Unit Tests
- [x] Add Unit test coverage
- [x] Talk to Robert H. about issue with L&L navigational errors
- [x] **Success: User can go through EC and it follows designs and we have test coverage to account for new code.**

**Comment by mkerns1** [comment] 2024-10-03 15:19
### Update:

Explanation of the Solution:

By removing the depends line from the emergencyContactsAddressPage block, you eliminated the condition that was preventing the page from being included in the form flow under certain circumstances.

Here's the updated code snippet:

`emergencyContactsSummary: {
  ...emergencyContactPages.emergencyContactsSummary,
},
emergencyContactsPage: {
  ...emergencyContactPages.emergencyContactsPage,
  depends: formData => formData['view:isEmergencyContactsEnabled'],
},
emergencyContactsAddressPage: {
  ...emergencyContactPages.emergencyContactsAddressPage,
  // 'depends' line removed
},`

Why This Fixes the Issue:

The depends Function Controls Page Inclusion:

The depends function determines whether a page should be included in the form flow based on a condition evaluated against formData.
If the condition returns false, the page is skipped during form navigation.
Potential Conflict with Custom Navigation Logic:

In your case, the emergencyContactsAddressPage relies on the navigation logic defined in the onNavForward function of the emergencyContactsPage.
This function decides whether to navigate to the address page or back to the summary based on the value of props.formData['view:hasEmergencyContactAddress'].
Redundancy and Unintended Behavior:

Having a depends function on the emergencyContactsAddressPage that may return false could prevent the page from being accessible, even when the onNavForward logic directs the user there.
This can cause the form to navigate back to the beginning or exhibit unexpected behavior because the next page in the sequence is missing.
By removing the depends function:

Ensures Page Availability:

The emergencyContactsAddressPage is always available in the form flow when the user navigates to it.
The decision to show or skip the page is now solely controlled by the onNavForward function.
Aligns with Custom Navigation Logic:

Allows the onNavForward function in emergencyContactsPage to work as intended, directing the user to the address page when necessary.
Key Takeaways:

Avoid Conflicting Conditions:

When using custom navigation logic like onNavForward, ensure that depends functions do not inadvertently override or conflict with that logic.
Use depends Functions Appropriately:

Reserve depends functions for situations where the inclusion of a page should be conditionally based on earlier form data that is reliably available.
Test Navigation Thoroughly:

After making changes to navigation logic or conditional page inclusion, thoroughly test the form flow to ensure pages appear and navigate as expected.
Next Steps:

Verify the Form Flow:

Walk through the form again to confirm that the navigation issue is fully resolved and that the emergency contact address page appears when it should.
Review Other Pages:

Check other pages with depends functions to ensure there are no similar issues.
Update Documentation:

Consider adding comments or documentation to your code to explain why the depends function was removed, which can be helpful for future maintenance.

**Comment by allanto-ah** [comment] 2024-11-27 21:15
Based on the AC being completed, will close this ticket. The actual QA work is being tracking in this ticket - [72844](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72844)

**Closed by allanto-ah** 2024-11-27 21:15 UTC
Labels: frontend, 1010-team, 1010-ezr, emergency-contact
