### ISSUE TITLE
[Tech Debt] Add Cypress test for 526 Wizard

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#13033] opened 2020-08-31 17:25 UTC
## Issue Description

The 526 wizard has been moved to the introduction page behind a feature flag. We need to include Cypress tests to verify the flow from the wizard to its various destinations.

## Tasks

- [ ] Add specific Cypress tests for the wizard within the introduction page

## Acceptance Criteria

- [ ] Form 526 Wizard is covered by e2e tests.

**Comment by vhenry07** [comment] 2021-02-09 20:06
Duplicate of 16517 - closing.

**Closed by vhenry07** 2021-02-09 20:06 UTC
Labels: 526, Wizards, frontend, needs-grooming, testing, vsa, vsa-benefits

**Comment by Mottie** [comment] 2021-02-09 20:24
Related https://github.com/department-of-veterans-affairs/vets-website/pull/15883
