### ISSUE TITLE
Access for Corey Ferris

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#19228] opened 2021-01-28 21:07 UTC
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Corey Ferris
- Please Provide your email.
   > corey.ferris@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VAOS Team, Senior Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCx8bTSJdZqIZ6CYOYPuzx70qmWZHbWZMZPgr4hBr1xBgNQcRIqqUIBT15Jdgbyus+TLJZfsW6x9h3TGYrI4fVM89jf/SJgKd9anBhHZQzYwXSlWw9wbfS+nXvES/k8UaD5MjJ18zdi9lVVmAASgSTQnGpcFpQ8jkSdMwA8Fn42fbXVfAXfIO+F7iX+h7Gfcc9z6o3/5k+KamiS3q7GPIszV/7nHZkw/v3/KZrbLm/ZOFCPInnKK/tzFkerRtnJ2JjNewlRWGQTZv47BI4Cy1oDT30NEv80AfZ6LvPljHgqBsU1GSCHd9SL32pcxNcc4szMCxSp9rL0RZmi9U78lGdDHokGW2XYAUEH71EgHv+y8frcSe7gUYypFem11UJjs+JEX4jXI+p0nluuosxoMZ5SaqfxgVhC9pmA6aq8g0LBfxINkvODq6OAnOtOXZKpeLTiXngAzE48i2X1oD1I4T9NPbrRBHaxeAB2IEa05DidPy2/e2kkJfLk4DXEC4Bwrf8= coreyferris@Corey-Ferris-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - I need access to AWS Console for reviewing logs and AWS API access for programatically reviewing logs

**Comment by mleclerc00** [comment] 2021-01-28 21:36
seems to be a duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16681

**Comment by mleclerc00** [comment] 2021-01-28 22:59
The ssh key has been updated.  Let me know if everything is working when you get an opportunity so I can close this ticket.

Thanks!

**Comment by cferris32** [comment] 2021-01-28 23:01
Everything looks good on my end - thank you!

**Closed** 2021-01-28 23:14 UTC
Labels: access-request, external-request, operations
