### ISSUE TITLE
Anchor link not working on the About VA disability ratings page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2132] opened 2019-10-01 14:19 UTC
## What happened?
_Anchor link is not working. 

On this page:  https://www.va.gov/disability/about-disability-ratings/  the text link "Go to the combined ratings table" (see screenshot) should link down to the content below with the tables. 

Screenshot:
![image](https://user-images.githubusercontent.com/43381063/65970187-0d0e8b00-e434-11e9-9308-02d6f4fd8030.png)

## Specs:
- Device: Dell PC
- Browser: (Chrome
- Test User _(if applicable)_:

## Acceptance Criteria
- [ ] _anchor link down to the combined ratings table section that's lower down on same page: 
https://www.va.gov/disability/about-disability-ratings/#How%20we%20determine%20combined%20VA%20disability%20ratings

![image](https://user-images.githubusercontent.com/43381063/65970328-5363ea00-e434-11e9-9f3a-a21370c37f20.png)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

@Karak888 - I'm not sure who this should be assigned to. FYI this page is now being pushed live through Drupal.

**Comment by Karak888** [comment] 2019-10-01 14:22
@ncksllvn can you please take a look at this anchor link issue not working? Thanks!!

**Comment by Karak888** [comment] 2019-10-01 14:23
oh wait sorry @ncksllvn @jenniferlee-dsva had just written that this was already published live in Drupal. Can you please advise if I should reach out to someone on CMS team?  Thank you!

**Comment by ncksllvn** [comment] 2019-10-01 14:48
It looks like this anchor link just needs to be updated. The link for `Go to the combined ratings table` should go to `#how-we-determine-combined-va-d`. Right now, it's linking to `#How we determine combined VA disability ratings`, which is invalid.

**Comment by ncksllvn** [comment] 2019-10-01 15:22
@jenniferlee-dsva yeah the value for that anchor link is generated from the heading text. It looks like the process for doing so is something like replacing spaces with hyphens and cutting it off at 30 characters.

I have no idea what's going on in the CMS interface unfortunately! I haven't explored that.

**Comment by jenniferlee-dsva** [comment] 2019-10-01 15:31
Thanks Nick. I'll share ^ info w/Kevin W on CMS team, in case this is something they can address on the CMS-FE template.

**Comment by kevwalsh** [comment] 2019-10-01 15:40
Yes this is expected behavior (cutting it off at 30 characters). There is no CMS interface for determining these, it's automatic.  

@ncksllvn one issue is that the anchor links in Preview do not match the ones that created in prod, so when creating new pages in drupal, authors/editors don't know what the final anchor link will be until the page is published. I believe that's what happened here. I don't know is involved in getting Preview anchor link behavior to match the prod behavior, or who should own that. This is one of several issues with Preview that may be fixed with some of the ongoing devops work.

**Comment by ncksllvn** [comment] 2019-10-01 15:42
Thanks @kevwalsh! I'm going to address that issue with the CMS Preview server in this ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/1625#issuecomment-537097584.

**Comment by jenniferlee-dsva** [comment] 2019-10-01 15:45
@ncksllvn  You are awesome, as always. Thank you. This anchor linking issue has been a persistent bug for us with things moving into the CMS.

**Comment by Karak888** [comment] 2019-10-18 19:07
this is being closed.

**Closed by Karak888** 2019-10-18 19:07 UTC
Labels: bug, vsa-global-ux
