### ISSUE TITLE
Sidekiq workers deployment to EKS

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42712] opened 2022-06-13 12:58 UTC
## Description
As part of moving vets-api to K8s, we will need to move the Sidekiq workers into a new deployment

## Acceptance Criteria
- [x] Sidekiq resource is moved into the manifests repo
- [x] Workers are running as a new k8s deployment

**Comment by RachalCassity** [comment] 2022-07-26 18:17
Found this[ sidekiq wiki](https://github.com/mperham/sidekiq/wiki/Kubernetes)

**Comment by laineymajor** [comment] 2022-11-18 17:24
Needs cleanup. Duplicate of work about to be done.

**Closed** 2022-12-15 20:19 UTC
Labels: infrastructure, team-platform-infrastructure, vets-api, platform-tech-team-1
