### ISSUE TITLE
[Bug] Profile 2.0: International addresses are being put through US address validation

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#13119] opened 2020-09-02 15:46 UTC
## Background

We are putting international addresses through US address validation, but we shouldn't be.

Steps to recreate:

1. Go to Profile 2.0. I used user 226 but it shouldn't matter.
2. Save the following international address:

Great Russell St, Bloomsbury, London WC1B 3DG, United Kingdom

(This is a real address for the British Museum in London. I don't know if the issue here is caused by this not being a residential address, but I doubt it. Feel free to try a another international address.)

You will see this:

![Screen Shot 2020-09-02 at 11.37.42 AM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/9e8dcf57-9ee2-429f-ad8d-d2798ba9eb57)

**Desired functionality**: International addresses should not be put through United States address validation.

## Tasks

- [x] Make it so that international addresses do not trigger address validation.
- [x] Once this is done, confirm address validation is still working properly for US addresses.

**Comment by Samara-Strauss** [comment] 2020-09-02 18:24
Just tested to confirm that override *does* work for international addresses, so people should still be able to save an international address despite address validation.

**Comment by erikphansen** [comment] 2020-09-02 19:52
So I'm a dummy. In this test address, what did you enter for city and what did you enter for province?

Anyway, I did a test where I just didn't enter the `Bloomsbury` part of the address, got a single suggestion with 96% confidence score, and still saw the validation screen. Getting back a single address with 96% confidence should skip the validation screen 🤔

**Comment by Samara-Strauss** [comment] 2020-09-02 19:56
> So I'm a dummy. In this test address, what did you enter for city and what did you enter for province?

Idk if this is right, but I entered Bloomsbury for the city and London for the region (and obviously UK for the country). This was a guess and I'm not 100% sure I did it right.

> Anyway, I did a test where I just didn't enter the Bloomsbury part of the address, got a single suggestion with 96% confidence score, and still saw the validation screen. Getting back a single address with 96% confidence should skip the validation screen 🤔

Isn't there a rule that if the zip code is bogus (e.g. 12345) we show the validation no matter what? Could that be what's causing this since the region code is so different from how we do zip codes in the US? Just a hypothesis.

**Comment by erikphansen** [comment] 2020-09-02 19:58
> Isn't there a rule that if the zip code is bogus (e.g. 12345) we show the validation no matter what? 

You're on the right track. If you flub the zip code, the confidence score seems to always be below 90. So we show the validation screen since it's below 90.

**Comment by erikphansen** [comment] 2020-09-02 20:01
I'm going to do more playing around with int'l addresses. But the reason we are showing the validation screen in this case is because, even though the single suggestion comes back with a high confidence score, it is lacking the `"deliveryPointValidation": "CONFIRMED"` bit.

This is the response when I entered the London address:
```
{
  "addresses": [
    {
      "address": {
        "addressLine1": "Great Russell Street",
        "addressType": "INTERNATIONAL",
        "city": "London",
        "countryName": "United Kingdom",
        "countryCodeIso3": "GBR",
        "internationalPostalCode": "WC1B 3DG"
      },
      "addressMetaData": {
        "confidenceScore": 96.0,
        "addressType": "International"
      }
    }
  ],
  "validationKey": 1520831034
}
```

And this is the response from a domestic address:
```
{
  "addresses": [
    {
      "address": {
        "addressLine1": "36320 Coronado Dr",
        "addressType": "DOMESTIC",
        "city": "Fremont",
        "countryName": "United States",
        "countryCodeIso3": "USA",
        "countyCode": "06001",
        "countyName": "Alameda",
        "stateCode": "CA",
        "zipCode": "94536",
        "zipCodeSuffix": "5537"
      },
      "addressMetaData": {
        "confidenceScore": 100.0,
        "addressType": "Domestic",
        "deliveryPointValidation": "CONFIRMED",
        "residentialDeliveryIndicator": "RESIDENTIAL"
      }
    }
  ],
  "validationKey": -874544140
}
```

Not sure if this is normal or intended or what. Also not sure if we need to look for that `"deliveryPointValidation": "CONFIRMED"` bit. Will keep digging.

**Comment by Samara-Strauss** [comment] 2020-09-02 20:04
Also, if you have questions or want answer about this before Friday, feel free to ping Mike Richard in the VA Profile Slack room. He'll be able to point us to who could help.

**Comment by erikphansen** [comment] 2020-09-02 20:26
More notes:

At least when dealing with domestic addresses, we _do_ need to filter out addresses that have `"deliveryPointValidation": "CONFIRMED"`. It's possible to get back addresses with high confidence scores but with `deliveryPointValidation: "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER` or `deliveryPointValidation: "UNDELIVERABLE"`

For the handful of international address I tried, the `addressMetaData` only has `confidenceScore` and `addressType`. We never get a `deliveryPointValidation` so the filtering we use to display the address validation screen never works correctly; even though we get suggestions from the validation API, we never show them to the user because they are not marked with `"deliveryPointValidation": "CONFIRMED"`.

I will check with VA Profile to see if this is expected behavior for international addresses. If it is, and we can expect to never get back `"deliveryPointValidation": "CONFIRMED"` for international addresses, my suggestion is to _treat _all_ international address suggestions as `CONFIRMED`_.

**Comment by Samara-Strauss** [comment] 2020-09-02 20:29
Sounds good. Looking forward to hearing what VA Profile has to say.

**Comment by erikphansen** [comment] 2020-09-02 20:50
Okay, confirmed that the `deliveryPointValidation` is only available for US addresses. So the work for this PR is to treat _all_ international suggestions as `CONFIRMED`.

**Comment by erikphansen** [comment] 2020-09-14 15:54
@Samara-Strauss the fix for this just got merged so it can be validated in staging whenever you have a few moments.

**Comment by Samara-Strauss** [comment] 2020-09-15 14:31
Looks good to me! We can close this out.

**Closed** 2020-09-15 17:49 UTC
Labels: bug, frontend, profile, vsa-authenticated-exp
