### ISSUE TITLE
Discovery: Audit content build memory usage

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20764] opened 2021-03-03 18:36 UTC
## Details 

Related tickets (maybe duplicative?)
* #5116
* #4099
* #13821

## Definition of Done 
- [x] Profile memory usage of each content build step 
- [x] Identify issues & recommend improvements

**Comment by alexandec** [comment] 2021-03-12 01:24
### Content build memory usage (vagovprod build on Jenkins, 3/11/2021)

![content-build-memory-use.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/94bd2e08-4c62-4322-aa0a-49be41351e70)

### Notes

- Memory usage increases from 29mb to 750mb in **Step 2: Get Drupal content**. The files object may be responsible, since the contents of all pages, along with metadata, are placed in the files object here.
- Usage fluctuates only slightly +/-50mb in steps 3 through 18, centered around a 750mb baseline.
- Usage more than doubles to 1.6gb in **Step 19: Apply layouts**. After this step it drops back to 782mb. While the increase is only temporary, it's important because it represents the peak memory usage of the content build process.

### Questions

- How does memory usage increase as nodes are added? Are we at risk of hitting a limit anytime soon?
- Why is 750mb of memory required in  the "Get Drupal Content" step since the pages.json file is only 37mb? Maybe we can trim the files object to save memory.
- Why does the "Apply layouts" step use an additional 830mb of memory? Is there any way to reduce this?

**Comment by meganhkelley** [comment] 2021-03-12 17:06
* Refer to node publishing schedule - Megan get from Oksana 
* Reach out to Neil to publish test data

**Comment by alexandec** [comment] 2021-03-12 22:14
Update: reached out to Neil regarding test data. Currently investigating the two steps with largest memory usage.

**Comment by alexandec** [comment] 2021-03-16 22:50
### Method
Command:
```
NODE_ENV=production yarn build:content --verbose --buildtype=vagovprod
```

Testing technique was to add copies to the files array to simulate additional nodes. In pipeDrupalPagesIntoMetalsmith():
```
const DUPLICATED_FILES = 20;
for (let i = 0; i <= DUPLICATED_FILES; i++) {
  files[`${drupalFileName}-${i}`] = createFileObj(
    pageCompiled,
    `${entityBundle}.drupal.liquid`,
  );
}
```

### Results

I recorded peak memory usage and total build time for the content build (see command above). Time projections are from the [Content Scaling](https://docs.google.com/spreadsheets/d/1pa0EgHuOXINvool4QHjV3lIDyYf-p9JRr8z1AuW4HFE/edit#gid=0) spreadsheet.

| Files | Peak memory | Total time | Projected date |
| ----- | -------- | ------------- | -------- |
| 4269 | 1675mB | 108 seconds | current |
| 17229 | 4149mB | 168 seconds |  Q2 |
| 27597 |  6630mB | 260 seconds | Q2 |
| 56109 | 14121mB | 840 seconds |  Q3 |
| 82029 | 20760mB | 1498 seconds | Q3 |

### Analysis

The current memory use and total content build time are acceptable. However, projected node count in Q3 is between 10x and 20x the current count. The projected build time and memory use will become unacceptable in Q3 based on these projections. Additional analysis would be required to determine how to keep memory use and build time at acceptable levels as large amounts of nodes are added.

**Comment by alexandec** [comment] 2021-03-19 14:31
I attempted to pull 48k nodes (25143 pages) for a more realistic test with this command:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 NODE_ENV=production yarn build:content --verbose --buildtype=vagovprod --drupal-address=https://test.staging.cms.va.gov --pull-drupal
```

However this resulted in the following error:

```
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/Users/chris/Documents/code/vets-website/node_modules/jsonfile/index.js:86:18)
    at Object.writeFileSync (/Users/chris/Documents/code/vets-website/node_modules/jsonfile/index.js:115:13)
    at Object.outputJsonSync (/Users/chris/Documents/code/vets-website/node_modules/fs-extra/lib/json/output-json-sync.js:15:12)
    at getContentViaGraphQL (/Users/chris/Documents/code/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:175:8)
```

The cause is this code which attempts to serialize the object containing all the GraphQL query results and output it to the pages.json file:

```
fs.outputJsonSync(drupalCache, drupalPages, { spaces: 2 });
```

In v8 the maximum string size is about 500mb.

**Comment by alexandec** [comment] 2021-03-19 17:37
### Current vs projected content build stats with 48k node GraphQL query

Having modified the caching logic to store each page in a separate file, I was able to successfully pull and cache the GraphQL query output for 48k nodes.

Commands run (pulled data first in each case, then ran on cached data to isolate build time and eliminate data fetching variability):
```
NODE_ENV=production yarn build:content --verbose --buildtype=vagovprod
NODE_TLS_REJECT_UNAUTHORIZED=0 NODE_ENV=production yarn build:content --verbose --buildtype=vagovprod --drupal-address=https://test.staging.cms.va.gov
```

Results:

| Nodes | Pages | Cache Size   | Peak memory | Content build time | Projected date  |
| ------- | ------ | ------------ | -------------- | ------------------ | --------------- |
| 5700    | 2904  | 43mb            | 1756mb           | 126 seconds          | Q1 2021             |
| 48000 | 25143 | 1100mb        | ?                       | ?                              |  Q2/Q3 2021     |

Currently the build process is freezing after the loadDrupal() function completes, so I am not yet able to get information on the following steps, or on the content build as a whole. I'm working on determining the cause of the freeze and how to resolve it.

**Comment by alexandec** [comment] 2021-03-22 21:01
### Scaling issue in replacePathInData() function

Circular reference detection logic in `replacePathInData()` adds an item to an array each time a new entity is found, and searches through the entire array each time. With current production data this function executes in about 45 seconds. However with projected test data it slows down rapidly as the array grows in size (> 400,000 items). Total execution time with 8 million items would probably be measured in hours.

#### Potential fix

By storing the list of entities in a Set instead of an array, lookups are O(1) instead of O(n). This allows completion in under 2 minutes rather than multiple hours. I modifed and benchmarked replacePathInData() as follows:

```
function replacePathInData(data, replacer, ancestors = new Set()) {
  if (ancestors.has(data)) {
    return data;
  } else {
    ancestors.add(data);
  }
  ...
}
```

#### Benchmarks

| Method | Nodes | Calls | Array length | Runtime |
| ------- | ------- | ----- | ------------ | -------- |
| Array  | 6,000 | 379,000 | 266,119 | 45 seconds |
| Set    | 6,000 | 379,000 | 266,119 | 4 seconds |
| Set    | 48,000 | 10,484,000 | 8,251,836 | 110 seconds |

#### Findings:
 - Switching from array to set would allow us to scale to 48k nodes, which is currently not possible
 - Switching from array to set would drop about 40 seconds from the existing content build
 - Additional optimization of replacePathInData() may be warranted since it will be called millions of times, but this is less urgent

**Comment by alexandec** [comment] 2021-03-24 18:17
### Too many open files error in Apply Layouts step

The "Apply Layouts" step was failing with this error: `EMFILE: too many open files`. Tried `ulimit -n 24500` locally (should allow 24500 files open simultaneously) but still received the error. Also tried setting Metalsmith concurrency but this didn't work either.

I then split Apply Layouts into multiple steps based on directory name (A-C, D-F, etc). This reduced the maximum number of open files so it didn't hit the limit. I tried increasing the number of files handled in a single step (A-F for example) but then I would get a timeout error. So I ended up with 8 steps:

```
['a-c', 'd-f', 'g-i', 'j-l', 'm-o', 'p-r', 's-u', 'v-z'].forEach(range => {
  smith.use(
    layouts({
      engine: 'liquid',
      directory: BUILD_OPTIONS.layouts,
      // Only apply layouts to markdown and html files.
      pattern: `**/[${range}]*/*.{md,html}`,
    }),
    `Apply layouts ${range}`,
  );
});
```

With this approach the build completed! Next step is to examine the memory use and execution time for the entire build and determine which steps are the best targets for improvement.

**Comment by alexandec** [comment] 2021-03-24 23:51
Currently summarizing memory use, execution time, and potential areas for improvement. Also doing spot checks on the build output to double check that all the pages are as they should be.

**Comment by alexandec** [comment] 2021-03-26 00:01
### Content build summary (48k nodes)
Command:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 DEBUG=metalsmith-layouts NODE_ENV=production yarn build:content --verbose --buildtype=vagovprod
```

Content build time with locally cached data (48,000 nodes, 1.1gb cache size): 1502 seconds (~25 minutes)

![content-build-summary-48k-nodes.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/f1f7077d-8be6-46f2-8be8-02e07f3ba312)

#### Changes required
To successfully complete the build with 48k nodes, three main changes were required:

- **Split the cache** from a single file into a separate file per page (25,143 files in this case). This is required when total cache size is over 500mb due to the V8 JS engine string length limit. Otherwise saving and loading the cached JSON fails.
- **Use a JS Set instead of an array** in the `replacePathInData()` function. This reduces circular reference detection lookup complexity from O(n) to O(1). With over 8 million items in the array, this change is critical to allow the build to complete in a reasonable amount of time.
- **Split the "Apply layouts" step** into multiple steps, each of which processes a subset of files. This is required to avoid the "EMFILE: too many open files" error from Metalsmith's Layouts plugin. Metalsmith claims to have fixed the error but has not, so a large node count requires this workaround.

Comments above contain code samples for each of these fixes. There's also a [20764-48k-node-content-build-investigation](https://github.com/department-of-veterans-affairs/vets-website/compare/20764-48k-node-content-build-investigation) branch with all the fixes which you can test locally. Note that some pieces of code are commented out because the test data has inconsistencies which cause failures.

#### Memory use
Memory use rises to 6.8gb in Step 2 when Drupal content is loaded, and stays in the 6-7gb range through the remainder of the build process. Peak memory use is 6.9gb which is reached in the final step. Because there is so little variation in memory use, there is probably not much room for optimization here. The "Get Drupal content" step is the place to look for optimization if needed. But build time is likely to become an issue before memory use does, so we should focus on time improvements first.

#### Time
Content build time with 48k nodes is 25 minutes with cached content. Based on the [Content Scaling spreadsheet](https://docs.google.com/spreadsheets/d/1pa0EgHuOXINvool4QHjV3lIDyYf-p9JRr8z1AuW4HFE/edit#gid=0) we may reach 48k nodes in Q2, but more likely in Q3. If we want to reduce execution time, we could target these steps first since they take longest:

**Get Drupal content** 3.1 mins
Since replacePathInData() is called about 10 million times, any further optimization there could make a difference. That said, we have already done some optimization -- see Set vs array description above. In the replacer function, cheerio could be replaced with a different approach, though we already know [cheerio is faster than jsdom](https://github.com/department-of-veterans-affairs/vets-website/pull/16276). Regexp maybe?

**Add permalinks and change foo.md to foo/index.html** 4.9 mins
This step seems slow considering what it's doing. The [metalsmith-permalinks](https://www.npmjs.com/package/metalsmith-permalinks) plugin used here is deprecated. We could try switching to the supported/recommended [@metalsmith/permalinks](https://www.npmjs.com/package/@metalsmith/permalinks) plugin instead. Maybe it would be faster. If not, we could write our own plugin. There's no guarantee it would be faster but we might be able to improve speed with an approach tightly focused on our use case.

**Apply layouts** 9.4 mins
This step takes longest so it makes sense to target it for improvements. However since it's performed entirely by the official [metalsmith-layouts](https://github.com/metalsmith/metalsmith-layouts) plugin, we have a limited abilty to make changes. We could see if there are any [engineOptions](https://github.com/metalsmith/metalsmith-layouts#engineoptions) which might improve performance.

**Parse a virtual DOM from every .html file and perform a variety of DOM sub-operations on each file** 6.1 mins
In this step, cheerio first parses each file, and then performs multiple DOM operations on the file. The most costly of these operations are `addNonceToScripts` and `checkBrokenLinks`. These would be good places to investigate optimizations. In addition, parsing the file with cheerio is often takes longer than all the operations performed on the file put together. Here's an example profile:

```
Parsing file with cheerio: 4.842ms
Running domModifier: addNonceToScripts: 0.671ms
Running domModifier: processEntryNames: 0.225ms
Running domModifier: updateExternalLinks: 0.125ms
Running domModifier: addSubheadingsIds: 0.322ms
Running domModifier: checkBrokenLinks: 1.206ms
Running domModifier: injectAxeCore: 0.002ms
```

If we could perform the required transformations without using a DOM at all, that might represent a substantial speed increase. However we'd have to be careful not to introduce regressions in doing this, and some discovery would be required to see if it's possible.

#### GraphQL note
For a complete content release picture we need to add GraphQL query response time to the 25 minute content build time. During testing I found GraphQL query time to vary between 1 and 15 minutes depending on the Drupal server cache state. It would be best to consult with the CMS team to determine what to expect in production as we scale. This would help us determine how long we can keep total query and content build time under an hour to enable hourly content releases.

**Comment by alexandec** [comment] 2021-03-26 00:04
@meganhkelley @timwright12 when you get a chance, please take a look and see if any further analysis or testing would be useful. I'm happy to do that, or make changes to improve clarity, etc.

**Comment by timwright12** [comment] 2021-03-30 14:43
@alexandec @meganhkelley  I think we should spin up tickets for all the things you had to do in order to get the 48k build running (Split the cache, Use a JS Set instead of an array, Split the "Apply layouts" step) - that would be an easy win for us. No need to sit and wait for that to break.

For further work I would set priorities as:
1. Parse a virtual DOM from every .html file and perform a variety of DOM sub-operations on each file
2. Add permalinks and change foo.md to foo/index.html 
3. Apply layouts
4. Get Drupal content 

For #1 I'd be interested in finding out if we can remove the broken link checker from the build and have it as part of the pipeline (or vice-versa) - I fee like we might be checking broken links multiple times and since it only reports a build failure on prod there's not need to run it on dev and staging. We're probably good with Cheerio here since Katy just added that in, but investigating addNonceToScripts and checkBrokenLinks would be good.

For #2 - Seems like this is just worth trying to upgrade, if it doesn't speed anything up, at least it will be up to date

For #3 - @k80bowman upgraded metalsmith layouts at one point, I don't think we released it, but might be good to just upgrade that anyway

For #4, I think this is going to be the root of our problems and all signs point to incremental builds here, which probably needs a large conversation

**Comment by alexandec** [comment] 2021-03-30 17:40
Thanks Tim! I agree on those priorities. We could create tickets for everything, or initially just for those first three tasks which prevent the build from breaking. @meganhkelley lmk if that's something I should do.

#1 I like that idea of removing the link checker from the build itself. It feels like something that makes more sense as a standalone CI thing anyway. The only thing I'm not sure of there is that there might be a performance hit when separating it. Currently because it's integrated as a Metalsmith step, we already have all the content loaded into memory for fast parsing.

#2 I definitely want to try upgrading that (and maybe upgrading other Metalsmith stuff too) just in case there are performance improvements we get for "free" (not really free since we'd probably have to fix breaking changes).

#3 Agree here too, upgrading is worth a try.

#4 Yeah, there's only so much optimization possible when you are working with a really large amount of data. And given that as we scale, not only will data quantity increase, but frequency of updates will also increase, incremental builds will probably become mandatory. Even if it requires switching to a different tool entirely!

**Comment by alexandec** [comment] 2021-03-30 17:53
Links from @mchelen-gov on JSON streaming which we can test/benchmark and compare to the caching approach described above:
- https://www.npmjs.com/package/stream-json
- https://ckhconsulting.com/parsing-large-json-with-nodejs/

**Comment by alexandec** [comment] 2021-03-31 20:58
### Move debug stringification to template

Currently before piping data into metalsmith we take each `page` object, stringify it, and add the string to the file object. Then later in the Apply Layouts step we include the string in a liquid template to help with debugging. However, all those strings use a large amount of extra memory and slow down the build process. To save memory and time we can instead perform the stringification in the liquid template itself. The impact of this change would be noticeable even in our current build, and will become much greater as we scale.

#### Benchmarks

| Method | Nodes | Peak memory use | Content build time |
| ------- | ------- | ------------------ | ------------------- | 
| Stringify in object  | 6,000 | 1641mb | 233 seconds |
| Stringify in template   | 6,000 | 780mb | 191 seconds |

Note, these benchmarks are for the local build since that includes debug data. Production build may vary a bit since debug data is not included in the template for that build.

#### Code changes

This change is straightforward. Here's the stringification removal in the `createFileObj()` function:

![files-object-debug.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/bcebefcc-d0d0-44c3-8f17-50b6e407c814)

And here's the addition of stringification in the debug.drupal.liquid template:

![liquid-template-debug.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/5e8e251f-69ec-4015-bc0d-fc76c6ba21d9)

I think we should give this change a high priority since it will give us an immediate improvement, as well as helping us scale in the future.

**Comment by alexandec** [comment] 2021-03-31 21:31
I'll close this ticket since there's enough research in it to satisfy the requirements. Next we'll move on to implementing some of the proposed solutions.

**Closed** 2021-03-31 22:49 UTC
Labels: tools-fe

**Comment by alexandec** [comment] 2021-04-22 14:49
@meganhkelley @timwright12 @mchelen Update with the new test data (49k nodes) and with all the changes merged to master except the caching change (here I'm using an initial pass at the single file streaming cache solution):

![build-summary-streaming-cache](https://user-images.githubusercontent.com/5805150/115733210-eaa9ce80-a345-11eb-955e-686553646525.png)

Peak memory use is about 4.3gb and total build time is about 38 minutes. I think we could get away with this as long as the GraphQL queries don't take too long. With this test server (test.dev.cms.va.gov) the queries are super fast, about 70 seconds total. Of course everything is fully cached in this case and the server probably has no other load on it. It would be interesting to try this with an empty cache to determine total worst case content build time.
