### ISSUE TITLE
OG: image size/aspect ratio

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20480] opened 2021-02-25 16:15 UTC
## Issue Description
The `og:image` for https://www.va.gov/pittsburgh-health-care/stories/tech-know-how-gets-kennedy-woman-va-job-love-of-va-keeps-her-there/ weighs in at 3Mb.  It seems like it could be using a different derivative of the cropped image. 

If it is occurring on this page, it may be happening elsewhere. 

meta property="og:image" content="/img/2020-12/Tauna%20Perenovich_20200901_0018.jpg" which maps to > https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/2020-12/Tauna%20Perenovich_20200901_0018.jpg (original source upload, 3.1MB)

Cropped derivative, smaller > https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/styles/2_1_medium_thumbnail/public/2020-12/Tauna%20Perenovich_20200901_0018.jpg (15KB)

Note: this will also speed up the builds by removing the requirement to download these large original files.

---
## Tasks
- [ ] Search vets-website (use https://developers.facebook.com/tools/debug/) for `og:image` to discover all occurrences of this issue
- [ ] Until all the options are [documented](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4464) we should enforce 2_1_large which is 1024x512, or 2_1_medium which is 480x240

## Acceptance Criteria
-[ ] Images use thumbnail version of URL 
-[ ] When a Veteran views stories via Facebook links, images render correctly (1.91:1)

**Comment by ElijahLynn** [comment] 2021-03-10 20:11
I updated the description with the correct link. https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/2020-12/Tauna%20Perenovich_20200901_0018.jpg, which shows the uncropped derivatieve/style that is 3.1MB vs the cropped derivative/style which is 15KB.

**Comment by mpelzsherman** [comment] 2021-03-29 18:05
I have confirmed that the `og:image` tags are being generated directly from Drupal data, specifically the `entityMetatags`.
This data is inserted directly into the page via the [metatags.drupal.liquid](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/metatags.drupal.liquid) template. The data that populates this particular page is using the wrong URL, as can be seen in the screen shot below:

![GraphiQL___VA_gov_CMS](https://user-images.githubusercontent.com/80267/112878945-81140880-9096-11eb-8335-208307f5eb35.png)

I see 2 options here:

1. Front-end Fix: inject the correct `og:image` URL into the `entityMetatags`
2. CMS fix: fix the image URLs in Drupal

**Comment by mpelzsherman** [comment] 2021-03-29 21:17
Closing since the CMS team will be handling this.

**Closed by mpelzsherman** 2021-03-29 21:17 UTC
Labels: frontend, frontend-vamc, stretch-goal, vsa, vsa-facilities
